### PR TITLE
driver/docker: pull image with digest

### LINKED ISSUE #4211: Docker image with sha256 doesn't work
### Nomad version

`0.7.1`

### Issue

```
config {
  image = "x.dkr.ecr.x.amazonaws.com/app/x@sha256:28c4ab3b66083da058ea1f44b5e6ed0c6854a54c28e1df387fd8f21c45d00cb6
}
```

fails with the following error in Nomad

```
failed to initialize task "server" for alloc "9fddd7ed-beba-584f-3905-e445f7d3b906": Failed to pull `x.dkr.ecr.x.amazonaws.com/app/x@sha256:28c4ab3b66083da058ea1f44b5e6ed0c6854a54c28e1df387fd8f21c45d00cb6`: API error (404): {"message":"manifest for x.dkr.ecr.x.amazonaws.com/app/x:latest not found"}
```

while `docker run` works fine with the same value

```
docker run --rm -it x.dkr.ecr.x.amazonaws.com/app/x@sha256:28c4ab3b66083da058ea1f44b5e6ed0c6854a54c28e1df387fd8f21c45d00cb6 bash
```

### Expected outcome

Like `docker run` Nomad should support format `${registry}/${image}@sha256:${sha256_value}`

Currently nomad only supports `${registry}/${image}:${some_tag}@sha256:${sha256_value}`

The `${some_tag}` should be optional :)

### LINKED ISSUE #4290: docker driver: doesn't accept 'digest' tags
### Nomad version

Nomad v0.7.1+ent (83ac1d7316a79aacb09d349298e14e23a0aa9853)

### Operating system and Environment details

Linux ... 4.13.0-1014-azure #17-Ubuntu SMP Fri Apr 6 02:37:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Issue

the nomad docker driver does not allow digest tags to be used when running an image.
It will fail to recognize the `@sha256:abcdef....` portion of the image and default to using `latest`

### Reproduction steps

Run any job using the `@sha256:...` digest instead of a tag

For example: `library/hello-world@sha256:f5233545e43561214ca4891fd1157e1c3c563316ed8e237750d59bde73361e77`

### PR DESCRIPTION
**Pull request by justenwalker**
Fixes #4290 
Fixes #4211 

Add digest support to the docker driver image config. This commit
factors out some common code to print the repo:tag (dockerImageRef) for
events/logs as well as parsing the image to retreive the repo,tag
(parseDockerImage) so that the results are consistent/sane for both
repo:tag and repo@sha256:... references.

When pulling an image with a digest, the tag is blank and the repo
contains the digest. See:
https://github.com/fsouza/go-dockerclient/blob/master/image_test.go#L471

### CODE REVIEW

File: client/driver/docker.go [hunk 1]
```diff
@@ -2183,3 +2180,24 @@ type createContainerClient interface {
 	ListContainers(docker.ListContainersOptions) ([]docker.APIContainers, error)
 	RemoveContainer(opts docker.RemoveContainerOptions) error
 }
+
+func parseDockerImage(image string) (repo, tag string) {
+	repo, tag = docker.ParseRepositoryTag(image)
+	if tag == "" {
```
Comment (jippi) [inline client/driver/docker.go]: `if tag != "" { return repo, tag }`

reduce indentation and make it explicit whats returned :)

File: client/driver/docker.go [hunk 2]
```diff
@@ -2183,3 +2180,25 @@ type createContainerClient interface {
 	ListContainers(docker.ListContainersOptions) ([]docker.APIContainers, error)
 	RemoveContainer(opts docker.RemoveContainerOptions) error
 }
+
+func parseDockerImage(image string) (repo, tag string) {
+	repo, tag = docker.ParseRepositoryTag(image)
+	if tag != "" {
+		return repo, tag
+	}
+	if i := strings.IndexRune(image, '@'); i > -1 { // Has digest (@sha256:...)
```
Comment (jippi) [inline client/driver/docker.go]: is there a risk of someone using `@` in their repo name/url/tag? wonder if its more safe to actually sniff for `@sha256:` in its entirely - not aware of the docker repo spec if its invalid or not

Comment (justenwalker) [reply client/driver/docker.go]: I'm pretty sure that '@' is not a valid repo name. The official spec is codified here:
https://github.com/docker/distribution/blob/master/reference/regexp.go

File: client/driver/docker_test.go [hunk 3]
```diff
@@ -2458,3 +2482,27 @@ func TestDockerDriver_AdvertiseIPv6Address(t *testing.T) {
...
+		{"library/hello-world:1.0", "library/hello-world", "1.0"},
+		{"library/hello-world", "library/hello-world", "latest"},
+		{"library/hello-world:latest", "library/hello-world", "latest"},
+		{"library/hello-world@sha256:f5233545e43561214ca4891fd1157e1c3c563316ed8e237750d59bde73361e77", "library/hello-world@sha256:f5233545e43561214ca4891fd1157e1c3c563316ed8e237750d59bde73361e77", ""},
+	}
+	for _, test := range tests {
+		t.Run(test.Image, func(t *testing.T) {
+			repo, tag := parseDockerImage(test.Image)
+			if repo != test.Repo {
+				t.Errorf("expected repo '%s' but got '%s'", test.Repo, repo)
```
Comment (nickethier) [inline client/driver/docker_test.go]: Could you change these to use the `require` package: https://godoc.org/github.com/stretchr/testify/require#Equal

File: client/driver/docker_test.go [hunk 4]
```diff
@@ -1092,6 +1092,30 @@ func TestDockerDriver_ForcePull(t *testing.T) {
...
+	task.Config["load"] = ""
+	task.Config["image"] = "library/busybox@sha256:58ac43b2cc92c687a32c8be6278e50a063579655fe3090125dcb2af0ff9e1a64"
+	task.Config["force_pull"] = "true"
+
+	client, handle, cleanup := dockerSetup(t, task)
+	defer cleanup()
+
+	waitForExist(t, client, handle)
+
+	_, err := client.InspectContainer(handle.ContainerID())
```
Comment (nickethier) [inline client/driver/docker_test.go]: Check that the inspected container's image is whats expected.

File: client/driver/docker_test.go [hunk 5]
```diff
@@ -1092,6 +1092,30 @@ func TestDockerDriver_ForcePull(t *testing.T) {
...
+	if err != nil {
```
Comment (nickethier) [inline client/driver/docker_test.go]: Use [`require.NoError`](https://godoc.org/github.com/stretchr/testify/require#Assertions.NoError)

File: client/driver/docker.go [hunk 6]
```diff
@@ -2183,3 +2180,25 @@ type createContainerClient interface {
...
+		// when pulling images with a digest, the repository contains the sha hash, and the tag is empty
+		// see: https://github.com/fsouza/go-dockerclient/blob/master/image_test.go#L471
+		repo = image
+	} else {
+		tag = "latest"
+	}
+	return repo, tag
+}
+
+func dockerImageRef(repo string, tag string) string {
```
Comment (nickethier) [inline client/driver/docker.go]: Would you mind adding a quick test for this. Could even just be a line in `TestParseDockerImage`

File: client/driver/docker_test.go (hunk 4 above)
Comment (justenwalker) [reply client/driver/docker_test.go]: I can do this, but the remote digest won't match the local digest due to "[reasons](https://github.com/docker/distribution/issues/1662)" so I'll have to just hard-code in another id for the local digest to match against. Not ideal
