### PR TITLE
address interpolation of artifact and template src/dest

### LINKED ISSUE #6929: interpolation does not work for destination in artifact stanza
Copy of now closed #2752 

> ### Nomad version
> Nomad v0.9.5
> 
> ### Operating system and Environment details
> CentOS Linux release 7.3.1611 (Core)
> 
> ### Issue
> interpolation does not work in artifact { destination = "_**destination**_" } stanza
> 
> ### Reproduction steps
> create job with example from "[Job file section](#Job-file)"
> 
> [`nomad validate` and `nomad run` executes with no errors](#Nomad-Server-logs).
> 
> [`nomad status -verbose example` shows that download has been completed and task started](#Nomad-Client-logs)
> but as you can see from logs, task is terminated because, in my case, start script expected to be in _**/tmp/example-job/start.sh**_
> 
> Checking content of allocation on node that was assigned to run a task:
> 
> ```
> ls your_nomad_allocation_dir
> 
> ...
> ...
> drwxr-xr-x   3 root   root      17 Jun 28 13:08 ${NOMAD_META_DESTINATION_DIR}
> ...
> ```
> 
> ### Nomad Server logs
> ```
> $ nomad validate example.nomad
> Job validation successful
> ```
> 
> ### Nomad Client logs
> ```
> 06/28/17 13:08:44 PDT  Restarting             Task restarting in 27.305774574s
> 06/28/17 13:08:44 PDT  Terminated             Exit Code: 1
> 06/28/17 13:08:44 PDT  Started                Task started by client
> 06/28/17 13:08:26 PDT  Downloading Artifacts  Client is downloading artifacts
> ```
> 
> ### Job file
> ```
> job "example" {
> .....
>   meta {
>      DESTINATION_DIR = "/tmp/example-job"
>      SOURCE_URL = "https://example_url/example.tar.gz"
>   }
> ....
>   task "task" {
> ....
>      artifact {
>         source = "${NOMAD_META_SOURCE_URL}"
>         destination = "${NOMAD_META_DESTINATION_DIR}"
>      }
> .....
> }
> ```

### LINKED ISSUE #9389: raw_exec and other unisolated drivers have buggy interpolation in templates
### Nomad version
Nomad v0.12.8 (b8501642d24a23c6788c267acfa2b38e50869cdf)

### Issue

Interpolation for `NOMAD_ALLOC_DIR`, `NOMAD_TASK_DIR`, and `NOMAD_SECRETS_DIR` is broken for `template` stanzas when using task drivers like `raw_exec` which do not have any filesystem isolation.

The way the `NOMAD_*_DIR` environment variables are initialized depends on whether or not the task driver supports filesystem isolation:

https://github.com/hashicorp/nomad/blob/v0.12.8/client/allocrunner/taskrunner/task_dir_hook.go#L77-L98

However, when interpolating these variables for templating we improperly handle them and cause them to be broken/unusable.

See https://github.com/hashicorp/nomad/pull/9383/files#r526105415 and the associated PR description.

### Reproduction steps

In an agent with raw_exec enabled (or the dev agent):

```
nomad run https://gist.githubusercontent.com/schmichael/2a9132537956c6c764461bb59671c45c/raw/cdf8d11b10c5db4d34e2bee3dff228aaf26719d7/rawexecrepro.hcl
```

### Job file (if appropriate) 

https://gist.github.com/schmichael/2a9132537956c6c764461bb59671c45c

### LINKED ISSUE #9610: Templating to shared alloc/ directory
### Nomad version
`Nomad v1.0.0 (cfca6405ad9b5f66dffc8843e3d16f92f3bedb43)`

### Issue
This seems to be a bug specifically with the `docker` driver.

I need to template a file in the group shared `alloc/data/` directory, such that all tasks in the group can read it. 
The docs for `template` indicate that `destination` is relative to the task working directory, and links to [this page](https://www.nomadproject.io/docs/runtime/environment#task-directories). This implies that I should be able to set the `destination` to `alloc/data/file`. However this results in an `alloc/` directory created next to the tasks `local/` directory, _inside_ the task-only working directory. 

ie: `/var/nomad/alloc/<alloc_id>` looks like
```
alloc/
<task1>/
 - alloc/data/file
- local/
- secrets/
<task2>/
- local/
- secrets/
```

when what I would expect to see is
```
alloc/
- data/file
<task1>/
- local/
- secrets/
<task2>/
- local/
- secrets/
```

in Nomad `0.12.4` I was able to circumvent this by using a destination of `../alloc/data/file`, however this is considered an alloc directory escape now, resulting in the error:  `destination path escapes the alloc directory`

### Reproduction steps
Run a job file as below

### Job file (if appropriate)
```
job "repro" {
  datacenters = ["dc1"]
  type = "batch"
  namespace = "eng-infra"

  group "repro" {

    task "a" {
      driver = "docker"
      config {
        image = "alpine:3"
        command = "cat"
        args = ["${NOMAD_ALLOC_DIR}/shared.txt"]
      }

      template {
        destination = "${NOMAD_ALLOC_DIR}/shared.txt"
        data = <<EOH
Hello, world!
EOH
      }
    }

    task "b" {
      driver = "docker"
      config {
        image = "alpine:3"
        command = "cat"
        args = ["${NOMAD_ALLOC_DIR}/shared.txt"]
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by cgbaker**
refactored #9668 for (imho) better abstraction

Resolves #9610 
Resolves #9389 
Resolves #6929

The main change is to use client-specific absolute paths in the environment maps for interpolating `source` for `template` and `destination` for `template` and `artifact`.

Because of this, it required adjusting the sandbox-escape checks to allow shared alloc dir, in addition to task working dir.

The result is that we should now support source and destination paths of the following forms:
* well-known interpolated paths: `${NOMAD_ALLOC_DIR}`, `${NOMAD_SECRETS_DIR}`, `${NOMAD_TASK_DIR}`
* task-dir relative paths: `local`, `secrets`, `../alloc`

The new [e2e test](https://github.com/hashicorp/nomad/pull/9668/files#diff-f806af7529cc10075671623ecd284693609d4014a3245fa05c34691feeac265a) shows the capability that we're targeting.

### CODE REVIEW

File: client/taskenv/env.go [hunk 1]
```diff
@@ -290,6 +306,51 @@ func (t *TaskEnv) ReplaceEnv(arg string) string {
...
+}
+
+// ClientPath interpolates the argument as a path, using the
+// environment variables with client-relative directories. The
+// result is an absolute path on the client filesystem.
+//
+// If the interpolated result is a relative path, it is made absolute
+// wrt to the task working directory.
+// The result is checked to see whether it escapes both the task working
+// directory and the shared allocation directory.
```
Comment (cgbaker) [inline client/taskenv/env.go:343]: this the result of the refactoring from #9668... it is potentially excessive refactoring. this method provides the functionality that we need for template and artifact path interpolation.

File: client/taskenv/env.go [hunk 2]
```diff
@@ -381,24 +454,23 @@ func NewEmptyBuilder() *Builder {
 	}
 }
 
-// Build must be called after all the tasks environment values have been set.
-func (b *Builder) Build() *TaskEnv {
-	nodeAttrs := make(map[string]string)
+// buildEnv returns the environment variables and device environment
+// variables with respect to the task directories passed in the arguments.
+func (b *Builder) buildEnv(allocDir, localDir, secretsDir string,
```
Comment (cgbaker) [inline client/taskenv/env.go:459]: there was a lot of interpolation that happened while creating these environment variables, so i did a back-of-the-envelope dependency analysis and broke out the code for creating the env vars and the device env vars into this method.

File: client/allocrunner/taskrunner/task_dir_hook.go [hunk 3]
```diff
@@ -93,11 +100,10 @@ func setEnvvars(envBuilder *taskenv.Builder, fsi drivers.FSIsolation, taskDir *a
 	// Set the host environment variables for non-image based drivers
 	if fsi != drivers.FSIsolationImage {
 		// COMPAT(1.0) using inclusive language, blacklist is kept for backward compatibility.
-		denylist := conf.ReadAlternativeDefault(
+		filter := strings.Split(conf.ReadAlternativeDefault(
```
Comment (cgbaker) [inline client/allocrunner/taskrunner/task_dir_hook.go:103]: just making this consistent with it's clone in plugins:
https://github.com/hashicorp/nomad/blob/master/plugins/drivers/testutils/testing.go#L252

File: e2e/consultemplate/consultemplate.go [hunk 4]
```diff
@@ -287,6 +292,73 @@ func (tc *ConsulTemplateTest) TestTemplatePathInterpolation_Bad(f *framework.F)
...
+			f.NoError(waitForTaskFile(allocID, task, "${NOMAD_ALLOC_DIR}/"+a,
+				func(out string) bool {
+					return len(out) > 0
+				}, nil), "expected artifact in alloc dir")
+		}
+
+		// test that we can load environment variables rendered with templates using interpolated paths
+		out, err := e2e.Command("nomad", "alloc", "exec", "-task", task, allocID, "sh", "-c", "env")
+		f.NoError(err)
+		f.Contains(out, "FROM=raw_exec")
```
Comment (tgross) [inline e2e/consultemplate/consultemplate.go:339]: Is this the check for the "hello from raw" part of the jobspec? Might be good to make it the full text `HELLO_FROM` just for clarity.

File: client/taskenv/env.go [hunk 5]
```diff
@@ -522,7 +586,29 @@ func (b *Builder) Build() *TaskEnv {
...
+	}
+	// Copy node attributes
+	for k, v := range b.nodeAttrs {
+		nodeAttrs[k] = v
+	}
+
+	envMap, deviceEnvs := b.buildEnv(b.allocDir, b.localDir, b.secretsDir, nodeAttrs)
+	envMapClient, _ := b.buildEnv(b.clientAllocDir, b.clientLocalDir, b.clientSecretsDir, nodeAttrs)
+
+	return NewTaskEnv(envMap, envMapClient, deviceEnvs, nodeAttrs, b.clientTaskDir, b.clientAllocDir)
```
Comment (tgross) [inline client/taskenv/env.go:611]: It looks like this is the only non-test caller? I'm wondering if we should make this internal to the package to force test callers to always use the full safe path?

**Review by tgross — COMMENTED** [review]
The overall approach here LGTM. I think this will be a big improvement in terms of comprehensibility for both the operators and us developers.

**Comment by cgbaker** [comment]
okay, it looks like i've got a problem... there is a use case that i didn't capture in this PR which may send this back to the drawing board:
https://github.com/hashicorp/nomad/pull/9671/files#diff-f40e85b67f576552c2d39989b55c983267bf19524185cc5f60d4716be0f71359R1683-L1686

it looks like the previous behavior of always joining against taskdir meant that absolute paths in the template destination would map to the same absolute path in the container: 
https://github.com/hashicorp/nomad/pull/9671/files#diff-90e77cdb4f5439161bf5a053bf2d0b74d3ac3ee65cfce482bbd8e02646a14a64L143
this is because something like `${taskDir}//etc` became `${taskDir}/etc` which was mounted on top of `/`

... except for docker, where this only worked if the absolute path was one of the bind-mounted paths: 
* `/secrets/...`
* `/local/...`
but not `/alloc` (which would go into `{taskdir}/alloc` which was not bind-mounted)

so, i need to figure out whether this invalidates the approach or not and deal with it.

**Review by schmichael — COMMENTED** [review]
Not sure I follow the hiccup you've hit. It's definitely awfully confusing as we have 3 "FSIsolation" modes that affect this:

1. None  (raw exec) - ClientPath == TaskPath but behavior is like Chroot (exec) in that you can write anywhere in the task's filesystem.
2. Chroot (exec/java) - ClientPath != TaskPath. Runtime paths are like Image *but* you can write to anywhere in the task's filesystem like None (raw exec) above.
3. Image (docker/podman) - ClientPath != TaskPath. Runtime paths are like Chroot *but* you can only write to the 3 bind-mounted paths (secrets, local, alloc).

For simplicities sake I think we should always be bind mounting `<alloc-dir>/<alloc-id>/alloc` to `<alloc-dir>/<alloc-id>/<task>/alloc` and doing all operations on that path. I'm not sure we ever need to reference the "real" `.../alloc`.

Image drivers like Docker and Podman should have `.../alloc` bind-mounted into their container filesystem as well.

I think that double bind mounting (once to create the task directory on the host, and the second time for Image based drivers) should make it so we never need to special case where the "alloc dir" is? It's the same as `local` and `secrets`.

While the ability to write anywhere on a Chroot driver's filesystem was likely an unintentional side effect, it should be considered a unique feature at this point distinct from how Image behaves. There's no point in trying to rememdy the discrepancy between the two now. In the future I hope Chroot goes away entirely in favor of Image, but obviously totally removing the Chroot behavior will take a long time.

File: client/taskenv/env.go [hunk 6]
```diff
@@ -316,6 +377,18 @@ type Builder struct {
...
+	// clientAllocDir is the shared alloc dir from the client's perspective; eg, <data-dir>/allocs/<allod-ic>/alloc
+	clientAllocDir string
+
+	// clientLocalDir is the local dir from the client's perspective; eg <data-dir>/allocs/<task>/local
+	clientLocalDir string
+
+	// clientSecrets is the secrets dir from the client's perspective; eg <data-dir>/allocs/<task>/secrets
+	clientSecretsDir string
+
+	// clientTaskDir is the task working directory from the client's perspective; eg <data-dir>/allocs/<task>
```
[the remark this answers is not in the document]
Comment (cgbaker) [reply client/taskenv/env.go:389]: > Not sure I follow the hiccup you've hit

the hiccup is that absolute path `destination` worked for `chroot` isolation before, but i've broken it at the moment.

**Comment by cgbaker** [comment]
> For simplicities sake I think we should always be bind mounting `<alloc-dir>/<alloc-id>/alloc` to `<alloc-dir>/<alloc-id>/<task>/alloc` and doing all operations on that path. I'm not sure we ever need to reference the "real" `.../alloc`.

We used to do this, but (if I'm understanding the PR correctly) we stopped because it required root for the Nomad client (which some docker-only users didn't need/want):
https://github.com/hashicorp/nomad/commit/0785109ae4285716082c5803d3bf3f442b12c2ca#diff-0626141dbc5bf9ed895f1d35410b05e96fdbe3aaf1f734c2dcdad9b3cab48552R92

**Comment by cgbaker** [comment]
rebased against master and re-enabled the disabled test from #9383
ready for an up-or-down vote on this one

File: client/taskenv/env.go [hunk 7]
```diff
@@ -290,6 +307,53 @@ func (t *TaskEnv) ReplaceEnv(arg string) string {
...
+}
+
+// ClientPath interpolates the argument as a path, using the
+// environment variables with client-relative directories. The
+// result is an absolute path on the client filesystem.
+//
+// If the interpolated result is a relative path, it is made absolute
+// wrt to the task working directory.
+// If joinEscape, an interpolated path that escapes will be joined with the
+// task dir.
```
Comment (schmichael) [inline client/taskenv/env.go:344]: Can you add an example usage here? Maybe it's the holidays, but I don't want to admit how long I stared at this and the relevant 2 lines of code to figure out what was going on. :sweat_smile:

File: client/taskenv/env.go [hunk 8]
```diff
@@ -726,6 +815,34 @@ func (b *Builder) SetTaskLocalDir(dir string) *Builder {
...
+	b.mu.Unlock()
+	return b
+}
+
+func (b *Builder) SetClientTaskSecretsDir(dir string) *Builder {
+	b.mu.Lock()
+	b.clientTaskSecretsDir = dir
+	b.mu.Unlock()
+	return b
+}
```
Comment (schmichael) [inline client/taskenv/env.go:844]: Since these are reqiured for `Build()`'s proper function it's a shame we can't enforce those dependencies through the New func or similar, but I can see how that gets awkward given the way Builder's are built up vs where FSIsolation is handled. A problem for another time perhaps.

**Review by schmichael — APPROVED** [review]
> We used to do this, but [...] we stopped because it required root for the Nomad client (which some docker-only users didn't need/want)

Argh of course, good catch. I even recognize that face on the PR :grimacing: 

An alternate fix for #2178 would have been to soft-fail on that `linkDir` call. I think that would make `raw_exec` behave more reasonably when Nomad is run as root.

I think this is a better solution all around thouhg? Distinctly rendering client paths vs task paths. Great work.

**Comment by wirat112535** [comment]
ส่งจาก iPhone ของฉัน

**Comment by wirat112535** [comment]
ส่งจาก iPhone ของฉัน

File: client/taskenv/env.go (hunk 7 above)
Comment (cgbaker) [reply client/taskenv/env.go:343]: yeah, will do. this is the hiccup that i ran up against, where previous behavior allowed for absolute destination paths for `artifact` and `template`: 
https://github.com/hashicorp/nomad/pull/9671/files#diff-90e77cdb4f5439161bf5a053bf2d0b74d3ac3ee65cfce482bbd8e02646a14a64L140-L144

i'll add a documenting test.

Comment (cgbaker) [reply client/taskenv/env.go:343]: documenting test here: 
https://github.com/hashicorp/nomad/pull/9671/files#diff-6c8db153b63f572b0e0d0f447c3071b491c157fee3fe7c2c1040aaa70b40bf76R895-R903
