### PR TITLE
consul: make failures_before_critical and success_before_passing work with group services

### LINKED ISSUE #10678: failures_before_critical does not get updated
### Nomad version
Nomad v1.1.0

### Operating system and Environment details
Ubuntu 18.04

### Issue
When changing [failures_before_critical](https://www.nomadproject.io/docs/job-specification/service#failures_before_critical), Nomad does not show a change in the value, always setting it to 0. I have also tried changing the `meta.uuid` field to force a deployment but the value stays at 0.

### Reproduction steps
Change the `failures_before_critical` value in the health check in the job file below.

#### Expected Result
Value changes as expected

#### Actual Result
Value remains at zero.

### Job file (if appropriate)

```hcl
job "dev-ops-httpbin" {
  meta {
    uuid = "51618dd2-5b10-44b6-8704-78e4d8b5b2e4"
    image_tag = "latest"
  }

  datacenters = ["dev-usw2-dev1"]

  type = "service"

  group "app" {
    count = 1

    network {
      port "http" {
        to = 80
      }
    }

    service {
      name = "${JOB}"
      port = "http"

      check {
        name     = "httpbin-ping"
        type     = "http"
        path     = "/anything"
        interval = "5s"
        timeout  = "2s"
        # TODO: Change this and plan again
        failures_before_critical = 3
      }
    }

    task "dev-ops-httpbin" {
      driver = "docker"

      config {
        image = "kennethreitz/httpbin:${NOMAD_META_image_tag}"
        ports = ["http"]
        force_pull  = true
        dns_servers = ["172.17.0.1"]
      }

      resources {
        cpu    = 100
        memory = 50
      }
    }
  }
}

```

### PR DESCRIPTION
**Pull request by shoenig**
This PR fixes some job submission plumbing to make sure the Consul check parameters
- failure_before_critical
- success_before_passing

work with group-level services. They already work with task-level services. Took this opportunity to apply a `todo` refactoring to re-use common API->structs services copying helper. 

Fixes #10678

### CODE REVIEW

File: command/agent/job_endpoint.go [hunk 1]
```diff
@@ -1044,67 +1044,7 @@ func ApiTaskToStructsTask(job *structs.Job, group *structs.TaskGroup,
...
-			}
-
-			// Task services can't have a connect block. We still convert it so that
-			// we can later return a validation error.
-			if service.Connect != nil {
-				structsTask.Services[i].Connect = ApiConsulConnectToStructs(service.Connect)
-			}
-		}
-	}
+	structsTask.Services = ApiServicesToStructs(apiTask.Services)
```
Comment (isabeldepapel) [inline command/agent/job_endpoint.go:1047]: So much cleaner 🎉

**Review by isabeldepapel — APPROVED** [review]
LGTM

File: CHANGELOG.md [hunk 2]
```diff
@@ -4,6 +4,7 @@ IMPROVEMENTS:
 * cli: Added `-monitor` flag to `deployment status` command and automatically monitor deployments from `job run` command. [[GH-10661](https://github.com/hashicorp/nomad/pull/10661)]
 
 BUG FIXES:
+* consul: Fixed a bug where consul check parameters missing in group services [[GH-10764](https://github.com/hashicorp/nomad/pull/10764)]
```
Comment (tgross) [inline CHANGELOG.md:7]: Let's add this to the 1.0.8 changelog as well (below)

**Review by tgross — APPROVED** [review]
LGTM
