### PR TITLE
drivers/docker: add support for STOPSIGNAL

### LINKED ISSUE #9989: Nomad doesn't respect Dockerfile's STOPSIGNAL directive
**Issue**

`Nomad stop` sends a SIGTERM signal first instead of sending STOPSIGNAL when terminating a task

When you issue a `docker stop`, docker sends a SIGTERM by default to the main process inside the container, and after a grace period a SIGKILL. The first signal can be overridden by setting the STOPSIGNAL instruction in the dockerfile. If this is set to let's say 9 then docker will send 9 to the container.
 
When you issue a `nomad stop` and STOPSIGNAL is not the default , Nomad calls the `kill` docker API endpoint first, sends a SIGTERM, after a grace period a SIGKILL and then calls the `stop` endpoint and sends the signal specified in the STOPSIGNAL instruction.

**Expected behavior**

Nomad calls two different docker API endpoints, one after another, and both send a signal to the container when it should use only one call to one of the endpoints.

For docker based tasks that use the default `kill_signal` (SIGTERM), we could just use one call to StopContainer with the kill_timeout set in [docker/handle.go](https://github.com/hashicorp/nomad/blob/7747124ef0cae2b1a60e132bf0ff9f0b5c4d780b/drivers/docker/handle.go#L158) 

**To Reproduce**

1 - Either add the `STOPSIGNAL 9` instruction to a dockerfile and build a new image or run the following existing image/job and save it as servicea.nomad:

```
job "servicea" {
    datacenters = ["dc1"]
    type = "service"

    group "api" {
        count = 1

        network {
            port "api" {
                to     = 9090
            }
        }

        task "api" {
            driver = "docker"
            config {
                image      = "monacosl/connect-flask:latest"
            }
        }

        service {
            name = "service-a"
            port = "api"
        }
   }
 }
```

2 - On another session run `docker system events`
 
3 - Run `nomad stop servicea`. The output of `docker system events` will show 3 signals being sent to the container:

```
2021-02-05T14:30:18.253744214Z container kill ab62e44b2127cebf8ecd2ad47dc54e7189efe2a226aead72420982aac22b9c31 (com.hashicorp.nomad.alloc_id=f8e94bee-e656-7b57-3cff-8e02fafe4124, image=monacosl/connect-flask:latest, name=api-f8e94bee-e656-7b57-3cff-8e02fafe4124, signal=15)
2021-02-05T14:30:23.253511363Z container kill ab62e44b2127cebf8ecd2ad47dc54e7189efe2a226aead72420982aac22b9c31 (com.hashicorp.nomad.alloc_id=f8e94bee-e656-7b57-3cff-8e02fafe4124, image=monacosl/connect-flask:latest, name=api-f8e94bee-e656-7b57-3cff-8e02fafe4124, signal=9)
2021-02-05T14:30:23.270211516Z container kill ab62e44b2127cebf8ecd2ad47dc54e7189efe2a226aead72420982aac22b9c31 (com.hashicorp.nomad.alloc_id=f8e94bee-e656-7b57-3cff-8e02fafe4124, image=monacosl/connect-flask:latest, name=api-f8e94bee-e656-7b57-3cff-8e02fafe4124, signal=9)
```
4 - Run the same job again

5 - Run `docker ps` and then `docker stop <container_id>`. This time the output will show only one signal (the STOPSIGNAL one)

```
2021-02-05T14:40:19.619410343Z container kill bb603cba835e0be05c873dd785eef3c4f4d315d89efa57da6ff4a3a27f0cb043 (com.hashicorp.nomad.alloc_id=0f116067-6936-ea75-1edb-d04c6a4e1e20, image=monacosl/connect-flask:latest, name=api-0f116067-6936-ea75-1edb-d04c6a4e1e20, signal=9)
```

**Environment**

**Nomad Version**

`Nomad v1.0.3`

**Docker Version**

```
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:35:01 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:57 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### PR DESCRIPTION
**Pull request by isabeldepapel**
Still need to figure out the tests but this is what I have so far

This fixes a bug where Nomad overrides a Dockerfile's STOPSIGNAL with
the default kill_signal (SIGTERM).

This adds a check for kill_signal. If it's not set, it calls
StopContainer instead of Signal, which uses STOPSIGNAL if it's
specified. If both kill_signal and STOPSIGNAL are set, Nomad tries to
stop the container with kill_signal first, before then calling
StopContainer.

Fixes #9989

### CODE REVIEW

File: drivers/docker/handle.go [hunk 1]
```diff
@@ -31,6 +33,7 @@ type taskHandle struct {
 	waitCh                chan struct{}
 	removeContainerOnExit bool
 	net                   *drivers.DriverNetwork
+	stopSignal            string
```
Comment (tgross) [inline drivers/docker/handle.go:36]: Does this new field ever get used?

File: drivers/docker/handle.go [hunk 2]
```diff
@@ -121,17 +124,49 @@ func (h *taskHandle) Signal(ctx context.Context, s os.Signal) error {
...
 // Kill is used to terminate the task.
-func (h *taskHandle) Kill(killTimeout time.Duration, signal os.Signal) error {
-	// Only send signal if killTimeout is set, otherwise stop container
-	if killTimeout > 0 {
+func (h *taskHandle) Kill(killTimeout time.Duration, signal string) error {
+	var err error
+	// Calling StopContainer lets docker handle the stop signal (specified
+	// in the Dockerfile or defaulting to SIGTERM). If kill_signal is specified,
+	// Signal is used to kill the container with the desired signal before
+	// calling StopContainer
```
Comment (tgross) [inline drivers/docker/handle.go:157]: 👍 Good explanatory comment for summarizing the domain-specific knowledge you'd need to understand the code here.

**Review by tgross — COMMENTED** [review]
This is looking good, @isabeldepapel.

It looks like there are some tests that exercise the stop behavior vs a real Docker already ([example](https://github.com/hashicorp/nomad/blob/main/drivers/docker/driver_test.go#L266)). So you can probably verify this works by querying for [Docker API events](https://pkg.go.dev/github.com/fsouza/go-dockerclient@v1.6.5#APIEvents) and then making assertions about those events.

**Review by notnoop — COMMENTED** [review]
This looks great.  Thanks @isabeldepapel 

Made a couple of comments - mostly how the existing code doesn't follow some golang convention. Noting them for educational value only.

File: drivers/docker/driver_test.go [hunk 3]
```diff
@@ -2911,28 +2911,159 @@ func TestDockerDriver_memoryLimits(t *testing.T) {
...
-	t.Run("default", func(t *testing.T) {
-		s, err := d.parseSignal(runtime.GOOS, "")
-		require.NoError(t, err)
-		require.Equal(t, syscall.SIGTERM, s)
-	})
+	for _, tc := range tests {
+		t.Run(tc.name, func(t *testing.T) {
+			s, err := parseSignal(tc.runtime, tc.specifiedSignal)
+			if tc.expectedSignal == "NA" {
+				require.Error(t, err)
```
Comment (notnoop) [inline drivers/docker/driver_test.go:2950]: As a habit, I suggest asserting on the exact error. It's not an issue here. I've seen failures being suppressed because the test was capturing an error, but of the wrong type.

File: drivers/docker/driver_test.go [hunk 4]
```diff
@@ -2911,28 +2911,159 @@ func TestDockerDriver_memoryLimits(t *testing.T) {
...
+	testutil.DockerCompatible(t)
+	stopSigTaskCfg := newTaskConfig("stopsignal", []string{"sleep", "9001"})
+	defaultTaskCfg := newTaskConfig("", []string{"sleep", "9001"})
+	stopTask := &drivers.TaskConfig{
+		ID:        uuid.Generate(),
+		Name:      "stopsig-only",
+		AllocID:   uuid.Generate(),
+		Resources: basicResources,
+	}
+	require.NoError(t, stopTask.EncodeConcreteDriverConfig(&stopSigTaskCfg))
```
Comment (notnoop) [inline drivers/docker/driver_test.go:2974]: These can also be expressed as table-driven tests.  Would something like this work?

```go
cases := []struct {
      name            string
      image           string
      jobKillSignal   string
      expectedSignals []string
}{}
```

File: drivers/docker/driver_test.go [hunk 5]
```diff
@@ -2911,28 +2911,159 @@ func TestDockerDriver_memoryLimits(t *testing.T) {
...
+	}()
+
+	for task, info := range taskList {
+		t.Run(task.Name, func(*testing.T) {
+			_, _, err = d.StartTask(task)
+			require.NoError(t, err)
+			require.NoError(t, d.WaitUntilStarted(task.ID, 5*time.Second))
+			err = d.StopTask(task.ID, 1*time.Second, info.killSig)
+
+			actualSigs := sigList[fmt.Sprintf("%s-%s", task.Name, task.AllocID)]
```
Comment (notnoop) [inline drivers/docker/driver_test.go:3065]: `sigList` is accessed in multiple goroutines without locking. This might cause the test to panic depending on how it's run.  Let's pair on how to improve it.

File: drivers/docker/driver_test.go [hunk 6]
```diff
@@ -2911,28 +2911,159 @@ func TestDockerDriver_memoryLimits(t *testing.T) {
...
+	}
+}
 
-	t.Run("set", func(t *testing.T) {
-		s, err := d.parseSignal(runtime.GOOS, "SIGHUP")
-		require.NoError(t, err)
-		require.Equal(t, syscall.SIGHUP, s)
-	})
+// This test asserts that Nomad isn't overriding the STOPSIGNAL in a Dockerfile
+func TestDockerDriver_StopSignal(t *testing.T) {
```
Comment (notnoop) [inline drivers/docker/driver_test.go:2960]: This is a great test. Captures all conditions :).

File: drivers/docker/driver_test.go [hunk 7]
```diff
@@ -2911,28 +2911,159 @@ func TestDockerDriver_memoryLimits(t *testing.T) {
...
+	}
+
+	d := dockerDriverHarness(t, nil)
+
+	for task := range taskList {
+		cleanup := d.MkAllocDir(task, true)
+		defer cleanup()
+
+		if task.Name == "stopsig-only" || task.Name == "stopsig-killsig" {
+			copyImage(t, task.TaskDir(), "busybox_stopsignal.tar") // Default busybox image with STOPSIGNAL 19 added
```
Comment (notnoop) [inline drivers/docker/driver_test.go:3019]: I'd suggest adding a comment in `test-resources/docker` on how the image got created - or a bash script for regenerating it.

**Review by notnoop — COMMENTED** [review]
This is great! I have few suggestions for the tests; but it's solid.  I'll be happy to pair, specially with regards to the concurrency issue.

**Comment by isabeldepapel** [comment]
Ready for another pass @notnoop

File: drivers/docker/test-resources/docker/gen_stopsignal.sh [hunk 8]
```diff
@@ -0,0 +1,5 @@
+#!/bin/sh
+
+# Create the tarball used in TestDockerDriver_StopSignal
+echo "FROM busybox:1.29.3\nSTOPSIGNAL 19" > tmpfile && docker build -t busybox:1.29.3-stopsignal - < tmpfile && rm tmpfile
```
Comment (notnoop) [inline drivers/docker/test-resources/docker/gen_stopsignal.sh:4]: I suspect you can avoid needing the tmp file. Also it might a bit nicer to use here-doc style in this case to avoid new lines:

```suggestion
cat <<'EOF' | docker build -t busybox:1.29.3-stopsignal -
FROM busybox:1.29.3
STOPSIGNAL 19
EOF
```

**Review by notnoop — APPROVED** [review]
Looks great.  A minor suggestion to the shell script - but merge away 🎉
