### PR TITLE
Fixed permissions of migrated allocation directories

### LINKED ISSUE #2053: Migrated ephemeral_disk data does not retain ownership/permissions
### Nomad version

Nomad v0.5.0

### Operating system and Environment details

CentOS 7.2

### Issue

When the allocation directory is migrated from one nomad client to another, permissions on the files are not retained.  Files are unarchived as `root` (as that's what Nomad's running as in my environment).

### Reproduction steps

Use jobspec below; set the constraint so that the job runs to completion on one host, then run it again with the constraint updated so that it runs on another node.  The 2nd placement will fail because the permissions are wrong on the files that were transferred from the other node.

### Job file

```hcl
job "migration-test" {
    region = "ci_aws_gen_us-east-1"
    
    datacenters = [
        "us-east-1d",
    ]
    
    type = "batch"
    
    constraint {
        attribute = "${attr.unique.hostname}"
        value     = "nomad-client-01425692"
    }

    group "grp" {
        ephemeral_disk {
            sticky = true
            migrate = true
            size = 101
        }

        task "test" {
            driver = "exec"

            config {
                command = "/bin/bash"
                
                args = [
                    "-c", "ls -al ${NOMAD_ALLOC_DIR}/data; (echo \"==> ${NOMAD_ALLOC_ID}\"; env) >> ${NOMAD_ALLOC_DIR}/data/test.out"
                ]
            }
        }
    }
}
```

### PR DESCRIPTION
**Pull request by diptanu**
Fixes #2053

### CODE REVIEW

File: client/client.go [hunk 1]
```diff
@@ -1578,6 +1578,18 @@ func (c *Client) migrateRemoteAllocDir(alloc *structs.Allocation, allocID string
 		return nil, fmt.Errorf("error getting snapshot for alloc %v: %v", alloc.ID, err)
 	}
 
+	if err := c.unarchiveAllocDir(resp, allocID, pathToAllocDir); err != nil {
+		return nil, err
+	}
+
+	// If there were no erorrs then we create the allocdir
```
Comment (dadgar) [inline client/client.go]: errors spelled wrong

File: client/client.go [hunk 2]
```diff
@@ -1578,6 +1578,18 @@ func (c *Client) migrateRemoteAllocDir(alloc *structs.Allocation, allocID string
...
+	prevAllocDir := allocdir.NewAllocDir(pathToAllocDir)
+	return prevAllocDir, nil
+}
+
+// unarchiveAllocDir reads the stream of compressed allocation directory and
```
Comment (dadgar) [inline client/client.go]: of a

File: client/client.go [hunk 3]
```diff
@@ -1586,40 +1598,38 @@ func (c *Client) migrateRemoteAllocDir(alloc *structs.Allocation, allocID string
 	stopMigrating, ok := c.migratingAllocs[allocID]
 	if !ok {
 		os.RemoveAll(pathToAllocDir)
-		return nil, fmt.Errorf("couldn't find a migration validity notifier for alloc: %v", alloc.ID)
+		return fmt.Errorf("couldn't find a migration validity notifier for alloc: %v", allocID)
```
Comment (dadgar) [inline client/client.go]: Very odd message. "Allocation %q is not marked for remote migration"
