### PR TITLE
fix system sched constraint errors

### LINKED ISSUE #2381: Output of "nomad run" seems wrong for system job with constraints.
Reference: https://groups.google.com/forum/#!topic/nomad-tool/t3bFTwSVgdQ

### Nomad version
Nomad v0.5.4

### Issue
* When we run a system job, a placement failure error is raised (status code: 2) if one node has been exclude by a constraint. So it's impossible to know programmatically if at least one allocation was successfully placed or not.
* The output displays wrong counts (see below) for filtered nodes.

Quoted from the mailing list:

> We have a system job that runs on an auto scaling group (on AWS).
> The instances of this group have a nomad class "foo" so the job definition is like:
> 
> job "test" {
>     datacenters = ["dc1"]
> 
>     type = "system"
> 
>     constraint {
>         attribute = "${node.class}"
>         value     = "foo"
>     }
> 
>     [...]
> }
> 
> So the job will be deployed on all servers in the autoscaling group and if we scale up the group,
>     Nomad automatically deploys the job on the newly instantiated server.
> 
> It's really cool but at the job submission, we have strange output.
> 
> Here is our (simplified) cluster nodes:
>  - A: Instance with class="bar
>  - B: Instance with class="bar"
>  - C: Instance with class="baz"
> Autoscaling group:
>  - D1: Instance with class="foo"
> 
> When we run the job above we have the following output:
> 
> ==> Monitoring evaluation "d1e000cd"
>     Evaluation triggered by job "test"
>     Allocation "51b3d960" modified: node "a45700d3", group "test"
>     Evaluation status changed: "pending" -> "complete"
> ==> Evaluation "d1e000cd" finished with status "complete" but failed to place all allocations:
>     Task Group "test" (failed to place 3 allocations):
>       * Class "bar" filtered 1 nodes
>       * Constraint "${node.class} = foo" filtered 1 nodes
> 
> I think it's because a system job has only one evaluation but these numbers are weird:
>  - Class "bar" really filtered 2 nodes
>  - Constraint node.class filtered 3 nodes (or indeed 1 if we subtract the previous line)
> 
> The output contains a specific line for class "bar" but not class "baz" ? (It's pretty weird)
> 
> And, our main problem is that the status code of the "nomad run" command is 2.

### PR DESCRIPTION
**Pull request by langmartin**
Fix the system scheduler so that filtered nodes are not reported to the user as failures.
Fixes #2381 and #5169

### CODE REVIEW

File: scheduler/system_sched_test.go [hunk 1]
```diff
@@ -1307,6 +1307,80 @@ func TestSystemSched_Queued_With_Constraints(t *testing.T) {
...
+
+// No errors reported when constraints prevent placement
+func TestSystemSched_ConstraintErrors(t *testing.T) {
+	h := NewHarness(t)
+
+	var node *structs.Node
+	// Register some nodes
+	// the tag "aaaaaa" is hashed so that the nodes are processed
+	// in an order other than good, good, bad
+	for _, tag := range []string{"aaaaaa", "foo", "foo", "foo"} {
```
Comment (preetapan) [inline scheduler/system_sched_test.go]: Shouldn't the last tag be "bar" or something else that doesn't match?

File: scheduler/system_sched_test.go [hunk 2]
```diff
@@ -1307,6 +1307,80 @@ func TestSystemSched_Queued_With_Constraints(t *testing.T) {
...
+		node = mock.Node()
+		node.Meta["tag"] = tag
+		node.ComputeClass()
+		require.Nil(t, h.State.UpsertNode(h.NextIndex(), node))
+	}
+
+	// Mark the last node as ineligible
+	node.SchedulingEligibility = structs.NodeSchedulingIneligible
+	// node.ComputeClass() // should only need to be updated at registration?
```
Comment (preetapan) [inline scheduler/system_sched_test.go]: remove comment

File: scheduler/system_sched_test.go [hunk 3]
```diff
@@ -1307,6 +1307,80 @@ func TestSystemSched_Queued_With_Constraints(t *testing.T) {
...
+
+	// Make a job with a partially matching constraint
```
Comment (preetapan) [inline scheduler/system_sched_test.go]: Suggested rewording for this - make a job with a constraint that matches a subset of nodes

File: scheduler/system_sched.go [hunk 4]
```diff
@@ -297,13 +297,28 @@ func (s *SystemScheduler) computePlacements(place []allocTuple) error {
 					desired := s.plan.Annotations.DesiredTGUpdates[missing.TaskGroup.Name]
 					desired.Place -= 1
 				}
+				continue
```
Comment (preetapan) [inline scheduler/system_sched.go]: Would be good to add a comment on why we continue here

File: scheduler/system_sched.go [hunk 5]
```diff
@@ -313,67 +328,58 @@ func (s *SystemScheduler) computePlacements(place []allocTuple) error {
...
+			},
+		}
 
-			// If the new allocation is replacing an older allocation then we
-			// set the record the older allocation id so that they are chained
-			if missing.Alloc != nil {
-				alloc.PreviousAllocation = missing.Alloc.ID
-			}
+		// If the new allocation is replacing an older allocation then we
+		// set the record the older allocation id so that they are chained
```
Comment (preetapan) [inline scheduler/system_sched.go]: nit: remove "set the". Looks like an old grammar error in the comment

File: scheduler/system_sched.go (hunk 4 above)
Comment (langmartin) [reply scheduler/system_sched.go]: @preetapan I put the comment up at the top of the `option == nil` where it applies to all 3 of the `continue` statements

Comment (notnoop) [reply scheduler/system_sched.go]: probably worth commenting why why we don't increment failedTGAllocs if `NodeFiltered > 0`.

Comment (preetapan) [reply scheduler/system_sched.go]: yeah that ^ is what i was getting at - documenting that we don't increment failedTGAllocs because  nodeFiltered is > 0 only when there's a constraint that didn't match, and a failed constraint condition should not be counted as a failure to place that task group.

Comment (langmartin) [reply scheduler/system_sched.go]: Let me know if the additional comments provide enough context.

Comment (preetapan) [reply scheduler/system_sched.go]: lgtm :shipit:
