### PR TITLE
Don't fail other tasks when retrying artifact get

### LINKED ISSUE #1558: dead task in job after node fail
### Nomad version
Nomad v0.4.1-dev
commit: 044e067

### Issue
After isssue in our test infrastructure(failt of one server) some jobs have dead task, which doens't restarted(nomad run doesn't helps to kick nomad update state of dead task):

```
# nomad status townshipDynamoNode
ID          = townshipDynamoNode
Name        = townshipDynamoNode
Type        = service
Priority    = 50
Datacenters = test
Status      = running
Periodic    = false

Summary
Task Group          Queued  Starting  Running  Failed  Complete  Lost
townshipDynamoNode  0       0         1        0       1         0

Allocations
ID        Eval ID   Node ID   Task Group          Desired  Status
dc917914  23ef25df  6660088f  townshipDynamoNode  run      running
```

then we see alloc-status:

```
nomad alloc-status dc917914
ID            = dc917914
Eval ID       = 23ef25df
Name          = townshipDynamoNode.townshipDynamoNode[0]
Node ID       = 6660088f
Job ID        = townshipDynamoNode
Client Status = running

Task "fluend" is "dead"
Task Resources
CPU      Memory   Disk     IOPS  Addresses
100 MHz  300 MiB  300 MiB  0

Recent Events:
Time                   Type        Description
08/09/16 16:18:29 MSK  Killed      Task successfully killed
08/09/16 16:18:28 MSK  Restarting  Task restarting in 15.987723567s
08/09/16 16:18:28 MSK  Terminated  Exit Code: 0
08/09/16 16:18:27 MSK  Started     Task started by client
08/09/16 16:18:27 MSK  Received    Task received by client

Task "townshipDynamoNode" is "running"
Task Resources
CPU         Memory           Disk     IOPS  Addresses
18/100 MHz  130 MiB/800 MiB  300 MiB  0     appport: 172.16.7.4:24295

Recent Events:
Time                   Type                      Description
08/09/16 16:28:51 MSK  Started                   Task started by client
08/09/16 16:26:32 MSK  Downloading Artifacts     Client is downloading artifacts
08/09/16 16:26:15 MSK  Restarting                Task restarting in 17.452112152s
08/09/16 16:26:15 MSK  Failed Artifact Download  GET error: Get http://social.playrix.local/playrix-webworker-t19.tar.gz: dial tcp 172.16.4.220:80: getsockopt: connection refused
08/09/16 16:26:15 MSK  Downloading Artifacts     Client is downloading artifacts
08/09/16 16:25:58 MSK  Restarting                Task restarting in 16.941858047s
08/09/16 16:25:58 MSK  Failed Artifact Download  GET error: Get http://social.playrix.local/playrix-webworker-t19.tar.gz: dial tcp 172.16.4.220:80: getsockopt: connection refused
08/09/16 16:25:58 MSK  Downloading Artifacts     Client is downloading artifacts
08/09/16 16:25:41 MSK  Restarting                Task restarting in 16.491063421s
08/09/16 16:25:41 MSK  Failed Artifact Download  GET error: Get http://social.playrix.local/playrix-webworker-t19.tar.gz: dial tcp 172.16.4.220:80: getsockopt: no route to host
```

It seems that nomad, moved job from dead node(we shutdown that node, from linux console by the shutdown -P now), and make wrong decisions, as a result it get fluend task state from dead node, and doesn't update it on live node
our job file looks like this:

```
job "townshipDynamoNode" {
	region = "global"
	datacenters = ["test"]
	type = "service"

	priority = 50

	constraint {
		attribute = "${attr.kernel.name}"
		value = "linux"
		distinct_hosts = true
	}

	update {
		stagger = "10s"
		max_parallel = 1
	}

	group "townshipDynamoNode" {
		count = 1

		task "townshipDynamoNode" {
			driver = "docker"

			artifact {
				source = "http://social.playrix.local/playrix-webworker-t19.tar.gz"

				options {
				        archive=false
				}
			}

			config {
				image = "playrix/webworker:t19"
				load = ["playrix-webworker-t19.tar.gz"]
				network_mode = "plrx-aws"
				hostname = "townshipDynamoNode"
				command = "/sbin/init_plrx"
				args = ["-c", "/opt/startup.sh"]

				port_map {
				    appport = 8124
				}
			}

			env {
			    APPNAME = "townshipDynamoNode"
			}

			service {
				name = "townshipDynamoNode"
				port = "appport"
				check {
					name = "alive"
					type = "tcp"
					interval = "10s"
					timeout = "2s"
				}
			}

			service {
				name = "townshipDynamoNode-codedeploy"
			}

			logs {
				max_files = 3
				max_file_size = 10
			}

			resources {
				memory = 800

				network {
					mbits = 10
					port "appport" {}
				}
			}
		}

		task "fluend"
		{
			driver = "raw_exec"

			config {
				command = "/usr/sbin/td-agent"
				args = ["--no-supervisor", "-c", "/etc/td-agent/td-agent.conf"]
			}

			env {
				APPNAME = "townshipDynamoNode"
			}

			logs {
				max_files = 3
				max_file_size = 10
			}

			resources {
				memory = 300
				cpu = 100
			}
		}
	}
}

```

### PR DESCRIPTION
**Pull request by schmichael**
The artifact fetching may be retried and succeed, so don't set the task
as dead.

Fixes #1558

### CODE REVIEW

File: client/alloc_runner_test.go [hunk 1]
```diff
@@ -61,6 +63,45 @@ func TestAllocRunner_SimpleRun(t *testing.T) {
 	})
 }
 
+// TestAllocRuner_RetryArtifact ensures that if one task in a task group is
+// retrying fetching an artifact, other tasks in the the group should be able
+// to proceed. See #1558
```
Comment (dadgar) [inline client/alloc_runner_test.go]: We generally don't do code references back to github issues

File: client/alloc_runner_test.go [hunk 2]
```diff
@@ -61,6 +63,45 @@ func TestAllocRunner_SimpleRun(t *testing.T) {
...
+	upd, ar := testAllocRunnerFromAlloc(alloc, true)
+	go ar.Run()
+	defer ar.Destroy()
+
+	testutil.WaitForResult(func() (bool, error) {
+		if upd.Count < 6 {
+			return false, fmt.Errorf("Not enough updates")
+		}
+		last := upd.Allocs[upd.Count-1]
+		if last.TaskStates["web"].State != structs.TaskStatePending {
```
Comment (dadgar) [inline client/alloc_runner_test.go]: Check the desired states at the end of the test

**Comment by dadgar** [comment]
LGTM after comments + tests passing
