### PR TITLE
scheduler: avoid importing the Planner test harness in scheduler calls

### LINKED ISSUE #26542: bug: Production code incorrectly depends on testing infrastructure (scheduler.Harness)
### Nomad version
Output from `nomad version`

In the main branch with the latest commit https://github.com/hashicorp/nomad/commit/d1186ae53e3033569d8473a48a34c5ce3e2fdac6 .

### Issue

Production code in `fsm.go` and `job_endpoint.go` currently imports and uses `scheduler.Harness`, which is testing infrastructure designed for unit tests. So I was wondering that if this represents an architectural violation where production code depends on testing utilities. IMHO, this will lead to unnecessary binary bloat, performance overhead, and maintenance complexity.

### PR DESCRIPTION
**Pull request by pkazmierczak**
For a while now, we've had only 2 implementations of the [`Planner` interface](https://github.com/hashicorp/nomad/blob/main/scheduler/structs/interfaces.go#L108-L133) in Nomad: one was the [`Worker`](https://github.com/hashicorp/nomad/blob/main/nomad/worker.go#L92-L125), and the other was [the scheduler test harness](https://github.com/hashicorp/nomad/blob/main/scheduler/tests/testing.go#L52-L72), which was then used as argument to the scheduler constructors in FSM and job endpoint RPC. That's not great, and one of the [recent refactors](https://github.com/hashicorp/nomad/pull/26031) made it apparent that we're importing testing code in places we really shouldn't. We finally got [called out](https://github.com/hashicorp/nomad/issues/26542) for it, and this PR attempts to remedy the situation by splitting the `Harness` into `Plan` (which contains actual plan submission logic) and separating it from testing code. 

Fixes #26542

### CODE REVIEW

**Comment by pkazmierczak** [comment]
> I assume we don't need to test the new planner as we already have those in place?

the new planner isn't new, it's the same code we've always had except without the `testing` field. So to be more accurate, our old/existing code shouldn't have been called "testing harness" in the first place, because it contained actual plan submission logic _and_ also some fields and switches that allowed it to be easily used in unit tests. This "grew organically" over the years and we never noticed that the planner passed over to the scheduler constructor always contained the testing code, too.

File: scheduler/structs/structs.go [hunk 1]
```diff
@@ -51,3 +60,201 @@ func (ev *PortCollisionEvent) Sanitize() *PortCollisionEvent {
...
 }
+
+// NewPlanWithSateAndIndex is used in the testing harness
+func NewPlanWithSateAndIndex(state *state.StateStore, nextIndex uint64, serversMeetMinimumVersion bool) *Plan {
+	return &Plan{State: state, nextIndex: nextIndex, serversMeetMinimumVersion: serversMeetMinimumVersion}
+}
+
+// Plan is used to submit plans.
+type Plan struct {
+	State *state.StateStore
```
Comment (tgross) [inline scheduler/structs/structs.go:71]: This field tells me that this struct isn't correctly named -- this isn't a "plan". Maybe this is a "plan builder"?

File: scheduler/structs/structs.go [hunk 2]
```diff
@@ -51,3 +60,201 @@ func (ev *PortCollisionEvent) Sanitize() *PortCollisionEvent {
 
 	return clean
 }
+
+// NewPlanWithSateAndIndex is used in the testing harness
+func NewPlanWithSateAndIndex(state *state.StateStore, nextIndex uint64, serversMeetMinimumVersion bool) *Plan {
+	return &Plan{State: state, nextIndex: nextIndex, serversMeetMinimumVersion: serversMeetMinimumVersion}
+}
+
+// Plan is used to submit plans.
```
Comment (tgross) [inline scheduler/structs/structs.go]: If we're refactoring this for the sake of cleanliness and not function anyways, can we put all this relocated code somewhere that isn't the 13k+ line `structs.go` file?

File: scheduler/structs/structs.go [hunk 3]
```diff
@@ -51,3 +60,201 @@ func (ev *PortCollisionEvent) Sanitize() *PortCollisionEvent {
 
 	return clean
 }
+
+// NewPlanWithSateAndIndex is used in the testing harness
+func NewPlanWithSateAndIndex(state *state.StateStore, nextIndex uint64, serversMeetMinimumVersion bool) *Plan {
```
Comment (tgross) [inline scheduler/structs/structs.go]:
```suggestion
func NewPlanWithStateAndIndex(state *state.StateStore, nextIndex uint64, serversMeetMinimumVersion bool) *Plan {
```

~Also, this constructor appears to be test-only. Maybe this belongs in the scheduler?~ Edit: :facepalm:

File: scheduler/structs/structs.go [hunk 4]
```diff
@@ -51,3 +60,201 @@ func (ev *PortCollisionEvent) Sanitize() *PortCollisionEvent {
...
+		for _, preemptions := range plan.NodePreemptions {
+			for _, preemptedAlloc := range preemptions {
+				allocDiff := preemptedAlloc.AllocationDiff()
+				allocDiff.ModifyTime = now
+				preemptedAllocDiffs = append(preemptedAllocDiffs, allocDiff)
+			}
+		}
+		req.AllocsPreempted = preemptedAllocDiffs
+	} else {
+		// COMPAT 0.11: Handles unoptimized log format
```
Comment (tgross) [inline scheduler/structs/structs.go]: Should we really be carrying forward `COMPAT 0.11` code?

**Comment by tgross** [comment]
> contained actual plan submission logic 

Doesn't this double-down on the problem? The consumer in the `Job.Plan` endpoint doesn't submit a plan either.

File: scheduler/structs/structs.go (hunk 1 above)
Comment (pkazmierczak) [reply scheduler/structs/structs.go:71]: I agree the name is not great, `PlanBuilder` makes more sense indeed.

File: scheduler/structs/structs.go (hunk 2 above)
Comment (pkazmierczak) [reply scheduler/structs/structs.go]: This isn't our famed `structs.go`, this is the structs.go that's internal to the scheduler package, a new file introduced by recent refactors.

Comment (tgross) [reply scheduler/structs/structs.go]: Serves me right for reviewing before my second cup of coffee.

File: scheduler/structs/structs.go (hunk 4 above)
Comment (pkazmierczak) [reply scheduler/structs/structs.go]: sorry, I missed it. removed in d12bf0e.

**Comment by pkazmierczak** [comment]
> Doesn't this double-down on the problem? The consumer in the `Job.Plan` endpoint doesn't submit a plan either.

I'm not sure I understand. The `PlanBuilder` implements `Planner` interface, which is what schedulers expect. Any time it's being created is because the scheduler needs `Planner` methods like plan submission, or eval related methods. The only difference this PR introduces is that we're not having any test-related code in the scheduler constructors anymore. 

Or am I missing something?

**Comment by imjoey** [comment]
Hi @pkazmierczak @jrasell , thank you for this great work. May I ask that shall we backport this pr to `release/1.10.x` branch, like many others?
