### PR TITLE
Use joint context to cancel prestart hooks

### LINKED ISSUE #6382: Missing Vault secrets causes Nomad Client to ignore shutdown request
This does not include full reproduction; just something I saw today that should be investigated later.

### Nomad version
Nomad v0.9.5+ent (5926e0dc9fec0c13e6fc6f622cea7546ce42a27f)
(probably not enterprise-dependent)

### Operating system and Environment details
Darwin

### Issue
Nomad client did not immediately shutdown on SIGINT.

### Reproduction steps
I had a single agent cluster (server+client, non-dev) with vault integration enabled. There was a Nomad job using a vault secret in a `template` stanza, but the secret was missing. On CTRL-C/SIGNIT, the Nomad agent did not finish shutting down... it continued to try to start an allocation (which failed, because of the missing Vault secret), until exhausting whichever retry count it was subject to. At this point, the agent finally shut down. The most recent log message was: 
```
    2019/09/25 17:44:43.475093 [ERR] (view) vault.read(someca/cert/ca): no secret exists at someca/cert/ca (exceeded maximum retries)
```

### Job file (if appropriate)
I imagine any vault secret will work. Here was mine:
```
      template {
        data = <<EOH
{{ with secret "someca/cert/ca"}}{{ .Data.certificate }}{{ end }}
EOH

        destination = "secrets/someca_rootca.pem"
      }
```

### PR DESCRIPTION
**Pull request by drewbailey**
The prestart hook for templates blocks while it resolves vault secrets.
If the secret is not found it continues to retry. If a task is shutdown
during this time, the prestart hook currently does not receive
shutdownCtxCancel, causing it to hang.

This PR joins the two contexts so either killCtx or shutdownCtx cancel
and stop the task.

fixes #6382

### CODE REVIEW

File: client/allocrunner/taskrunner/task_runner_test.go [hunk 1]
```diff
@@ -1742,6 +1742,72 @@ func TestTaskRunner_Template_Artifact(t *testing.T) {
...
+		ts := tr.TaskState()
+
+		if len(ts.Events) == 0 {
+			return false, fmt.Errorf("no events yet")
+		}
+
+		foundMissingVaultSecretEvent := false
+		for _, e := range ts.Events {
+			if e.Type == "Template" && strings.Contains(e.DisplayMessage, "vault.read(foo/secret)") {
+				foundMissingVaultSecretEvent = true
```
Comment (notnoop) [inline client/allocrunner/taskrunner/task_runner_test.go]: It's probably safe to return true here and avoid needing `foundMissingVaultSecretEvent`.

File: client/allocrunner/taskrunner/task_runner_test.go [hunk 2]
```diff
@@ -1742,6 +1742,68 @@ func TestTaskRunner_Template_Artifact(t *testing.T) {
...
+
+	task.Vault = &structs.Vault{Policies: []string{"default"}}
+
+	conf, cleanup := testTaskRunnerConfig(t, alloc, task.Name)
+	defer cleanup()
+
+	tr, err := NewTaskRunner(conf)
+	require.NoError(t, err)
+	go tr.Run()
+
```
Comment (schmichael) [inline client/allocrunner/taskrunner/task_runner_test.go]:
```suggestion
defer tr.Shutdown()

```

...to cleanup as much as possible if the test fails.
