### PR TITLE
Fix memory fingerprinting on 32bit

### LINKED ISSUE #6134: 32 bit nomad reports 0 memory resources
Using nomad version 0.9.4 32 bit on windows 2016 and the memory resources of the client gets reported as 0. Setting the "memory_total_mb" in the client config did not make a difference. The same issue was reported here: https://github.com/hashicorp/nomad/issues/5048

Here's the output of the 32 bit nomad
```
 nomad node status 2a2a3d91
ID            = 2a2a3d91
Name          = Ops1
Class         = <none>
DC            = aws
Drain         = false
Eligibility   = eligible
Status        = ready
Uptime        = 70h12m28s
Driver Status = raw_exec

Node Events
Time                  Subsystem  Message
2019-08-15T13:18:37Z  Cluster    Node registered

Allocated Resources
CPU         Memory   Disk
0/5000 MHz  0 B/0 B  0 B/76 GiB

Allocation Resource Utilization
CPU         Memory
0/5000 MHz  0 B/0 B

Host Resource Utilization
CPU           Memory           Disk
138/5000 MHz  1.4 GiB/3.9 GiB  (c:)

Allocations
No allocations placed
```
Here's the 64 bit running on the same server
```
nomad node status 2a2a3d91
ID            = 2a2a3d91
Name          = Ops1
Class         = <none>
DC            = aws
Drain         = false
Eligibility   = eligible
Status        = ready
Uptime        = 70h26m59s
Driver Status = raw_exec

Node Events
Time                  Subsystem  Message
2019-08-15T13:54:23Z  Cluster    Node re-registered
2019-08-15T13:53:25Z  Cluster    Node heartbeat missed
2019-08-15T13:18:37Z  Cluster    Node registered

Allocated Resources
CPU           Memory           Disk
200/5000 MHz  600 MiB/3.0 GiB  600 MiB/76 GiB

Allocation Resource Utilization
CPU         Memory
0/5000 MHz  59 MiB/3.0 GiB

Host Resource Utilization
CPU            Memory           Disk
3611/5000 MHz  1.6 GiB/3.9 GiB  (c:)
```

### LINKED ISSUE #6222: 0.95 nomad arm reports 0mb memory available
### Nomad version
0.95 and 0.94

### Operating system and Environment details
Linux Raspbian Buster on Raspberry PI 4
### Issue
cannot allocate jobs as nodes are always exhausted of memory - reports 0B available. 
setting memory in client.hcl does not help.

### Reproduction steps
pi@leader-01:~ $ nomad  node status 74f1611a
ID            = 74f1611a
Name          = client-01
Class         = <none>
DC            = homecluster
Drain         = false
Eligibility   = eligible
Status        = ready
Uptime        = 1h22m55s
Driver Status = docker,exec

Node Events
Time                       Subsystem  Message
2019-08-26T22:59:16+01:00  Cluster    Node registered

Allocated Resources
CPU         Memory   Disk
0/6000 MHz  0 B/0 B  0 B/16 EiB

Host Resource Utilization
CPU          Memory           Disk
60/6000 MHz  351 MiB/3.8 GiB  1.8 GiB/58 GiB

Allocations
No allocations placed

### Job file (if appropriate)
using example.nomad from nomad init. 

### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

### PR DESCRIPTION
**Pull request by endocrimes**
Also introduce regression ci for 32 bit fingerprinting

fixes #6134
fixes #6222

### CODE REVIEW

File: client/fingerprint/memory.go [hunk 1]
```diff
@@ -25,32 +25,33 @@ func NewMemoryFingerprint(logger log.Logger) Fingerprint {
...
+			totalMemory = int64(memInfo.Total)
 		}
 	}
 
 	if totalMemory > 0 {
 		resp.AddAttribute("memory.totalbytes", fmt.Sprintf("%d", totalMemory))
 
-		// COMPAT(0.10): Remove in 0.10
+		memoryMB := totalMemory / bytesInMB
+
```
Comment (schmichael) [inline client/fingerprint/memory.go]:
```suggestion

		// COMPAT(0.10): Unused since 0.9.
```
