### PR TITLE
keyring: safely handle missing keys and restore GC

### LINKED ISSUE #14981: failed to submit plan for evaluation: ... no such key \"<snip>\" in keyring error after moving cluster to 1.4.1
### Nomad version
Nomad v1.4.1 (2aa7e66bdb526e25f59883952d74dad7ea9a014e)

### Operating system and Environment details
Ubuntu 22.04, Nomad 1.4.1

### Issue
After moving the Nomad server and clients to v1.4.1, I noticed that sometimes (unfortunately not always) after cycling Nomad server ASGs and Nomad client ASGs with new AMIs, jobs scheduled on the workers can't be allocated. So to be precise:

1. Pipeline creates new Nomad AMIs via Packer
2. Pipeline terraforms Nomad server ASG with server config
3. Pipeline terraforms client ASG or dedicated instances with updated AMI
4. Lost jobs on worker (like for instance the Traefik ingress job) can't be allocated

This literally never happened before 1.4.X

Client output looks like this:

`nomad eval list`

ID        Priority  Triggered By      Job ID                     Namespace  Node ID   Status    Placement Failures
427e9905  50        failed-follow-up  plugin-aws-ebs-nodes       default    <none>    pending   false
35f4fdfb  50        failed-follow-up  plugin-aws-efs-nodes       default    <none>    pending   false
46152dcd  50        failed-follow-up  spot-drainer               default    <none>    pending   false
71e3e58a  50        failed-follow-up  plugin-aws-ebs-nodes       default    <none>    pending   false
e86177a6  50        failed-follow-up  plugin-aws-efs-nodes       default    <none>    pending   false
2289ba5f  50        failed-follow-up  spot-drainer               default    <none>    pending   false
da3fdad6  50        failed-follow-up  plugin-aws-ebs-nodes       default    <none>    pending   false
b445b976  50        failed-follow-up  plugin-aws-efs-nodes       default    <none>    pending   false
48a6771e  50        failed-follow-up  ingress                    default    <none>    pending   false

### Reproduction steps
Unclear at this point. I seem to be able to somewhat force the issue, when I cycle the Nomad server ASG with updated AMIs.

#### Expected Result
Client work that was lost, should be rescheduled once the Nomad client comes up and reports readiness.

#### Actual Result
Lost jobs that can't be allocated on worker with an updated AMI.

`nomad status`

ID                         Type     Priority  Status   Submit Date
 auth-service               service  50        **pending**  2022-10-09T11:32:57+02:00
 ingress                    service  50        **pending**  2022-10-17T14:57:26+02:00
 plugin-aws-ebs-controller  service  50        running  2022-10-09T14:48:11+02:00
 plugin-aws-ebs-nodes       system   50        running  2022-10-09T14:48:11+02:00
 plugin-aws-efs-nodes       system   50        running  2022-10-09T11:37:04+02:00
 prometheus                 service  50        **pending**  2022-10-18T21:19:24+02:00
 spot-drainer               system   50        running  2022-10-11T18:04:49+02:00

### Job file (if appropriate)
```
variable "stage" {
  type        = string
  description = "The stage for this jobfile."
}

variable "domain_suffix" {
  type        = string
  description = "The HDI stage specific domain suffix."
}

variable "acme_route" {
  type = string
}

variables {
  step_cli_version = "0.22.0"
  traefik_version  = "2.9.1"
}

job "ingress" {

  datacenters = [join("-", ["pd0011", var.stage])]

  type = "service"

  group "ingress" {

    constraint {
      attribute = meta.instance_type
      value     = "ingress"
    }

    count = 1

    service {
      name = "traefik"
      tags = [
        "traefik.enable=true",

        "traefik.http.routers.api.rule=Host(`ingress.dsp.${var.domain_suffix}`)",
        "traefik.http.routers.api.entrypoints=secure",
        "traefik.http.routers.api.service=api@internal",
        "traefik.http.routers.api.tls.certresolver=hdi_acme_resolver",
        "traefik.http.routers.api.tls.options=tls13@file",
        "traefik.http.routers.api.middlewares=dspDefaultPlusAdmin@file",

        "traefik.http.routers.ping.rule=Host(`ingress.dsp.${var.domain_suffix}`) && Path(`/ping`)",
        "traefik.http.routers.ping.entrypoints=secure",
        "traefik.http.routers.ping.service=ping@internal",
        "traefik.http.routers.ping.tls.certresolver=hdi_acme_resolver",
        "traefik.http.routers.ping.tls.options=tls13@file",
        "traefik.http.routers.ping.middlewares=dspDefault@file"
      ]

      port = "https"

      check {
        name     = "Traefik Ping Endpoint"
        type     = "http"
        protocol = "http"
        port     = "http"
        path     = "/ping"
        interval = "10s"
        timeout  = "2s"
      }
    }

    network {

      port "http" {
        static = 80
        to     = 80
      }
      port "https" {
        static = 443
        to     = 443
      }
    }

    ephemeral_disk {
      size    = "300"
      sticky  = true
      migrate = true
    }

    task "generate_consul_cert" {
<snip>
    }

    task "generate_nomad_cert" {
<snip>
    }


    task "traefik" {

      driver = "docker"

      env {
        LEGO_CA_CERTIFICATES = join(":", ["${NOMAD_SECRETS_DIR}/cacert.pem", "${NOMAD_SECRETS_DIR}/root_ca_${var.stage}.crt"])
        # LEGO_CA_SYSTEM_CERT_POOL = true
      }

      config {
        image = "traefik:${var.traefik_version}"
        volumes = [
          # Use absolute paths to mount arbitrary paths on the host
          "local/:/etc/traefik/",
          "/etc/timezone:/etc/timezone:ro",
          "/etc/localtime:/etc/localtime:ro",
        ]
        network_mode = "host"
        ports        = ["http", "https"]
      }

      resources {
        cpu    = 800
        memory = 128
      }
      # Controls the timeout between signalling a task it will be killed
      # and killing the task. If not set a default is used.
      kill_timeout = "60s"

      template {
        data        = <<EOH
<snip>
    }
  }
}

```

### Nomad Server logs (if appropriate)
```Oct 20 15:00:30 uat-nomad-95I nomad[485]:     2022-10-20T15:00:30.571+0200 [ERROR] worker: failed to submit plan for evaluation: worker_id=c4d91fc3-5e23-dbec-a85d-8fc830f375ab eval_id=ee89b346-b351-9c56-fd2e-168fb3834013 error="rpc error: no such key \"7d11bdf6-26f0-c4fa-5c04-b73b0f46eedb\" in keyring"
Oct 20 15:00:30 uat-nomad-95I nomad[485]:     2022-10-20T15:00:30.571+0200 [ERROR] worker: error invoking scheduler: worker_id=c4d91fc3-5e23-dbec-a85d-8fc830f375ab error="failed to process evaluation: rpc error: no such key \"7d11bdf6-26f0-c4fa-5c04-b73b0f46eedb\" in keyring"
Oct 20 15:00:42 uat-nomad-95I nomad[485]:     2022-10-20T15:00:42.948+0200 [ERROR] worker: failed to submit plan for evaluation: worker_id=c4d91fc3-5e23-dbec-a85d-8fc830f375ab eval_id=827f0dfe-0584-b44a-92e2-9a92ab649c48 error="rpc error: no such key \"7d11bdf6-26f0-c4fa-5c04-b73b0f46eedb\" in keyring"
```

### Nomad Client logs (if appropriate)
```Oct 20 11:55:00 uat-worker-wZz nomad[464]:                 Client: true
Oct 20 11:55:00 uat-worker-wZz nomad[464]:              Log Level: INFO
Oct 20 11:55:00 uat-worker-wZz nomad[464]:                 Region: europe (DC: pd0011-uat)
Oct 20 11:55:00 uat-worker-wZz nomad[464]:                 Server: false
Oct 20 11:55:00 uat-worker-wZz nomad[464]:                Version: 1.4.1
Oct 20 11:55:00 uat-worker-wZz nomad[464]: ==> Nomad agent started! Log data will stream in below:
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.798+0200 [INFO]  agent: detected plugin: name=exec type=driver plugin_version=0.1.0
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.798+0200 [INFO]  agent: detected plugin: name=qemu type=driver plugin_version=0.1.0
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.798+0200 [INFO]  agent: detected plugin: name=java type=driver plugin_version=0.1.0
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.798+0200 [INFO]  agent: detected plugin: name=docker type=driver plugin_version=0.1.0
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.798+0200 [INFO]  agent: detected plugin: name=raw_exec type=driver plugin_version=0.1.0
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.817+0200 [INFO]  client: using state directory: state_dir=/opt/hsy/nomad/data/client
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.826+0200 [INFO]  client: using alloc directory: alloc_dir=/opt/hsy/nomad/data/alloc
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.826+0200 [INFO]  client: using dynamic ports: min=20000 max=32000 reserved=""
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.831+0200 [INFO]  client.fingerprint_mgr.cgroup: cgroups are available
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.852+0200 [WARN]  client.fingerprint_mgr.network: unable to parse speed: path=/usr/sbin/ethtool device=ens5
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.856+0200 [WARN]  client.fingerprint_mgr.network: unable to parse speed: path=/usr/sbin/ethtool device=lo
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.870+0200 [WARN]  client.fingerprint_mgr.network: unable to parse speed: path=/usr/sbin/ethtool device=ens5
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.897+0200 [INFO]  client.plugin: starting plugin manager: plugin-type=csi
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.900+0200 [INFO]  client.plugin: starting plugin manager: plugin-type=driver
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.900+0200 [INFO]  client.plugin: starting plugin manager: plugin-type=device
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:54:58.906+0200 [ERROR] client: error discovering nomad servers: error="client.consul: unable to query Consul datacenters: Get \"https://127.0.0.1:8501/v1/catalog/datacenters\": dial tcp 127.0.0.1:8501: connect: connection refused"
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:55:00.437+0200 [INFO]  client: started client: node_id=5f21ebef-e0a9-8bd2-775a-61b3e32cac6e
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:55:00.437+0200 [WARN]  agent: not registering Nomad HTTPS Health Check because verify_https_client enabled
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:55:00.438+0200 [WARN]  client.server_mgr: no servers available
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:55:00.439+0200 [WARN]  client.server_mgr: no servers available
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:55:00.453+0200 [INFO]  client.consul: discovered following servers: servers=[10.194.73.146:4647, 10.194.74.253:4647, 10.194.75.103:4647]
Oct 20 11:55:00 uat-worker-wZz nomad[464]:     2022-10-20T11:55:00.501+0200 [INFO]  client: node registration complete
Oct 20 11:55:06 uat-worker-wZz nomad[464]:     2022-10-20T11:55:06.856+0200 [INFO]  client: node registration complete
Oct 20 11:55:14 uat-worker-wZz nomad[464]:     2022-10-20T11:55:14.893+0200 [INFO]  client.fingerprint_mgr.consul: consul agent is available
Oct 20 11:55:21 uat-worker-wZz nomad[464]:     2022-10-20T11:55:21.417+0200 [INFO]  client: node registration complete
```

### PR DESCRIPTION
**Pull request by tgross**
Fixes https://github.com/hashicorp/nomad/issues/14981 https://github.com/hashicorp/nomad/issues/15088

When replication of a single key fails, the replication loop breaks early and therefore keys that fall later in the sorting order will never get replicated. This is particularly a problem for clusters impacted by the bug that caused #14981 and that were later upgraded; the keys that were never replicated can now never be replicated, and so we need to handle them safely.

Included in the replication fix:
* Refactor the replication loop so that each key replicated in a function call that returns an error, to make the workflow more clear and reduce nesting. Log the error and continue.
* Improve stability of keyring replication tests. We no longer block leadership on initializing the keyring, so there's a race condition in the keyring tests where we can test for the existence of the root key before the keyring has been initialize. Change this to an "eventually" test.

But these fixes aren't enough to fix #14981 because they'll end up seeing an error once a second complaining about the missing key, so we also need to fix keyring GC so the keys can be removed from the state store. Now we'll store the key ID used to sign a workload identity in the Allocation, and we'll index the Allocation table on that so we can track whether any live Allocation was signed with a particular key ID.

(Best reviewed commit-by-commit.)

### CODE REVIEW

File: nomad/state/schema.go [hunk 1]
```diff
@@ -686,6 +688,15 @@ func allocTableSchema() *memdb.TableSchema {
...
 				},
 			},
+
+			indexSigningKey: {
+				Name:         indexSigningKey,
+				AllowMissing: true,
+				Unique:       false,
+				Indexer: &memdb.UUIDFieldIndex{
+					Field: "SigningKeyID",
+				},
```
Comment (tgross) [inline nomad/state/schema.go:698]: Note: An alternative to storing this field in the `Allocation` struct would be to extract it from the signed identity claim in an indexer. I got that to work but it brought all the JWT parsing down here into the state store code and parsing JWTs every time we restore a snapshot, which seemed terrible. The key ID isn't a lot of data (just a UUID string), and having it on the `Allocation` will be convenient for later use anyways, I'm sure.

File: nomad/core_sched.go [hunk 2]
```diff
@@ -958,9 +1030,20 @@ func (c *CoreScheduler) variablesRekey(eval *structs.Evaluation) error {
 			return err
 		}
 
-		// we've now rotated all this key's variables, so set its state
+		// we've rotated this key's variables, but we need to ensure it hasn't
+		// been used to sign any live workload identities before it's safe to
+		// mark as deprecated
+		inUse, err := c.snap.IsRootKeyMetaInUse(keyMeta.KeyID)
```
Comment (tgross) [inline nomad/core_sched.go:1036]: TODO before we can merge: this is causing a failure in `TestCoreScheduler_VariablesRekey` because we're reusing the snapshot from before we deleted the variables, so the keys always look like they're still in use. Will fix.

File: nomad/core_sched.go [hunk 3]
```diff
@@ -893,23 +895,93 @@ func (c *CoreScheduler) expiredACLTokenGC(eval *structs.Evaluation, global bool)
...
+			continue // never GC the active key or one we're rekeying
+		}
+		if keyMeta.CreateIndex > oldThreshold {
+			continue // don't GC recent keys
+		}
+
+		// don't GC a key that's deprecated, that's encrypted a variable or
+		// signed a live workload identity
+		inUse := false
+		if !keyMeta.Deprecated() {
```
Comment (angrycub) [inline nomad/core_sched.go:941]: This looks like it will reach the delete case if `keyMeta.Deprecated()` returns true, which doesn't seem to jibe with the comment.

File: nomad/encrypter.go [hunk 4]
```diff
@@ -529,6 +505,53 @@ ERR_WAIT:
...
+			return fmt.Errorf("failed to fetch key from any peer: %v", err)
+		}
+	}
+
+	err = krr.encrypter.AddKey(getResp.Key)
+	if err != nil {
+		return fmt.Errorf("failed to add key to keyring: %v", err)
+	}
+
+	krr.logger.Info("added key", "key", keyID)
```
Comment (schmichael) [inline nomad/encrypter.go:551]: Do we need before and after log lines at Info level? If knowing how long replication takes is critical it seems reasonable, but I'd have trouble explaining to folks why they need to see these.

File: nomad/state/state_store.go [hunk 5]
```diff
@@ -6959,3 +6959,36 @@ func (s *StateStore) GetActiveRootKeyMeta(ws memdb.WatchSet) (*structs.RootKeyMe
 	}
 	return nil, nil
 }
+
+// IsRootKeyMetaInUse determines whether a key has been used to sign a workload
+// identity for a live allocation or encrypt any variables
+func (s *StateStore) IsRootKeyMetaInUse(keyID string) (bool, error) {
```
Comment (schmichael) [inline nomad/state/state_store.go:6965]: This made me a little nervous at first glance because it could trend toward quadratic over time if there's at-least-one alloc for every key that's ever existed...

...however at the default key rotation rate of 30 days even in the maximally pathological case of 1-alloc-for-every-key-ever, that's a whopping 120 iterations over all allocations after *a decade.*

If we ever become concerned with the performance here we can always add ref counting to keys and update it when allocs are created or updated (or even just wait to decrement when the allocs are gc'd if we want to be really lazy). I'm guessing we'll never need to do that.

Making a compound index that only includes non-terminal allocs would be an easier optimization if not quite as effective.

**Review by schmichael — APPROVED** [review]
Can you remove `CoreScheduler.getOldestAllocationIndex`? It doesn't appear to be used anymore. FWIW I have seen clusters with running allocs whose last modify time/index was over a year ago (which is absolutely fine and not necessarily a bug/problem), but it means basing logic purely off of that may mean the index very very rarely changes.

File: nomad/encrypter.go (hunk 4 above)
Comment (tgross) [reply nomad/encrypter.go:551]: Eh, probably not. I'll be honest and say I got a little overzealous with the logging here because the internal customer was not collecting any debug-level logs. But they're also not seeing _any_ logs from this code path for some reason (something to do with their collection, I think), so that really is just excessive. Will fix.

File: nomad/encrypter.go [hunk 6]
```diff
@@ -152,7 +152,7 @@ const keyIDHeader = "kid"
 
 // SignClaims signs the identity claim for the task and returns an
 // encoded JWT with both the claim and its signature
-func (e *Encrypter) SignClaims(claim *structs.IdentityClaims) (string, error) {
+func (e *Encrypter) SignClaims(claim *structs.IdentityClaims) (string, string, error) {
```
[the remark this answers is not in the document]
Comment (tgross) [reply nomad/encrypter.go:155]: Oops, good catch!

File: nomad/state/state_store.go (hunk 5 above)
Comment (tgross) [reply nomad/state/state_store.go:6965]: Yeah, there are a lot of cases where I want a cheap `Count()` method in memdb. 😀 I can do that compound index though: it reduces the memory usage for the index a bit for clusters with lots of short-lived allocs, and reduces the number of iterations we have to do here at a tiny cost on `txn.Insert`. Seems worth it.

File: nomad/encrypter.go (hunk 4 above)
Comment (tgross) [reply nomad/encrypter.go]: Done

File: nomad/core_sched.go (hunk 3 above)
Comment (tgross) [reply nomad/core_sched.go]: Dropping from our sidebar discussion on Slack:

> I think I've figured out why it exists, and we don't need it anymore:
>
> In the original design, we didn't have a way of determining if the key was in use by a WI except by guessing (incorrectly, as it turned out) based on the indexes. So we marked it as deprecated b/c the GC that actually removed it could happen much later and having a status that let the user know we've done a rekey on it was maybe helpful for diagnostics.
>
> In the new design, we can just not touch the key at all in the rekey pass. It'll already be marked inactive because the key was rotated. The next periodic GC will delete the key if it's not in use. Much simpler.

I've done that and I think this looks pretty good?

**Review by schmichael — APPROVED** [review]

**Review by schmichael — APPROVED** [review]
