### PR TITLE
Remove rkt pods when exiting

### LINKED ISSUE #3561: rkt driver should remove pods when stopping tasks
### Nomad version

0.7.0

### Operating system and Environment details

Linux, rkt 1.29.0

### Issue

Docker removes containers once they exit: https://github.com/hashicorp/nomad/blob/master/client/driver/docker.go#L1685-L1688

rkt does not: 

https://github.com/hashicorp/nomad/blob/master/client/driver/rkt.go#L769-L787

### Reproduction steps

```
nomad run rkt.nomad # see below
nomad stop echo
rkt list
# echo's container still exists
```

### Job file (if appropriate)

```hcl
job "echo" {
  datacenters = ["dc1"]

  group "echo" {
    task "echo" {
      driver = "rkt"

      config {
        image = "docker://ubuntu"
        command = "/foo/ping"
        args    = ["google.com"]
        dns_servers = ["host"]
        volumes = ["/bin:/foo"]
      }

      resources {
        network {
          mbits = 10
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by schmichael**
Fixes #3561

### CODE REVIEW

File: client/driver/rkt.go [hunk 1]
```diff
@@ -781,6 +789,13 @@ func (h *rktHandle) run() {
 	}
 	h.pluginClient.Kill()
 
+	// Remove the pod
+	if err := rktRemove(h.uuid); err != nil {
+		h.logger.Printf("[ERR] driver.rkt: error removing pod %q - must gc manually", h.uuid)
```
Comment (dadgar) [inline client/driver/rkt.go]: Print the error

File: client/driver/rkt_test.go [hunk 2]
```diff
@@ -187,6 +188,18 @@ func TestRktDriver_Start_Wait(t *testing.T) {
...
+
+	// Make sure pod was removed #3561
+	var stderr bytes.Buffer
+	cmd := exec.Command(rktCmd, "status", handle.uuid)
+	cmd.Stdout = ioutil.Discard
+	cmd.Stderr = &stderr
+	if err := cmd.Run(); err == nil {
+		t.Fatalf("expected error running 'rkt status %s' on removed container", handle.uuid)
+	}
+	if out := stderr.String(); !strings.Contains(out, "no matches found") {
```
Comment (preetapan) [inline client/driver/rkt_test.go]: This seems brittle if the returned error message ever changes, but other than checking for a non empty error message I don't have a better idea.

File: client/driver/rkt.go [hunk 3]
```diff
@@ -781,6 +789,13 @@ func (h *rktHandle) run() {
 	}
 	h.pluginClient.Kill()
 
+	// Remove the pod
+	if err := rktRemove(h.uuid); err != nil {
```
Comment (dadgar) [inline client/driver/rkt.go]: Thinking: Should it use the created resources feature so that cleanup gets retried?

File: client/driver/rkt_test.go (hunk 2 above)
Comment (schmichael) [reply client/driver/rkt_test.go]: Yeah, I hate resorting to `strings.Contains`, but if it ever fails due to a string change it should be a quick and easy fix (and caught by Travis, not a user at runtime).

File: client/driver/rkt.go (hunk 3 above)
Comment (schmichael) [reply client/driver/rkt.go]: I just tried to match Docker's behavior and this is how we do it there. I'll update rkt to use created resources.

Comment (schmichael) [reply client/driver/rkt.go]: Investigated this route and it's a bit more work than I'd like to put in this PR. It involves returning CreatedResources from Driver.Start which isn't already happening and ensuring TaskDriver cleans up containers exactly when desired. Following Dockers lead for now seems safest.
