### PR TITLE
CSI: volume and plugin allocations in the API

### LINKED ISSUE #8362: [ui] CSI Volume Listing has invalid Allocation Count
### Nomad version
Nomad 0.12.0-beta2

### Issue
The `# Allocs` column in the CSI Volume Listing page (`/ui/csi/volumes`) is not correct:
Screen Shot 2020-07-05 at 3 54 46 PM
It is always zero. The network trace suggests this is being populated from `GET /v1/volumes`, which does not include the necessary `allocations` array in the list stub entries.

### Reproduction steps
Create a CSI volume and use it from an allocation (reach out to me for a reproduction environment).

### PR DESCRIPTION
**Pull request by langmartin**
API representations of individual plugins and volumes include correct allocation data

Fixes #8362 and similar issue for plugins

### CODE REVIEW

File: command/agent/csi_endpoint.go [hunk 1]
```diff
@@ -57,11 +62,11 @@ func (s *HTTPServer) CSIVolumeSpecificRequest(resp http.ResponseWriter, req *htt
 	id := tokens[0]
 
 	switch req.Method {
-	case "GET":
+	case http.MethodGet:
 		return s.csiVolumeGet(id, resp, req)
-	case "PUT":
-		return s.csiVolumePut(id, resp, req)
-	case "DELETE":
+	case http.MethodPut:
```
Comment (tgross) [inline command/agent/csi_endpoint.go:67]: If we're allowing `POST` in `csiVolumePut` should we allow it here as well?

File: command/agent/csi_endpoint.go [hunk 2]
```diff
@@ -57,11 +62,11 @@ func (s *HTTPServer) CSIVolumeSpecificRequest(resp http.ResponseWriter, req *htt
 	id := tokens[0]
 
 	switch req.Method {
-	case "GET":
+	case http.MethodGet:
 		return s.csiVolumeGet(id, resp, req)
-	case "PUT":
-		return s.csiVolumePut(id, resp, req)
```
Comment (tgross) [inline command/agent/csi_endpoint.go:63]: Is getting rid of the ID here intentional?

Comment (tgross) [reply command/agent/csi_endpoint.go:63]: Oh, and just a heads up that this changeset is going to conflict with #8584 [here](https://github.com/hashicorp/nomad/pull/8584/files#diff-91535e68265a2446b33edbefba3453d0R59) so whichever gets merged last will need a fix for that.

File: command/agent/csi_endpoint.go [hunk 3]
```diff
@@ -210,5 +220,294 @@ func (s *HTTPServer) CSIPluginSpecificRequest(resp http.ResponseWriter, req *htt
 		return nil, CodedError(404, "plugin not found")
 	}
 
-	return out.Plugin, nil
+	return structsCSIPluginToApi(out.Plugin), nil
```
[the remark this answers is not in the document]
Comment (langmartin) [reply command/agent/csi_endpoint.go:223]: I don't think so, unless we want to use reflection, which is a departure from the rest of the code base. I don't think there's a technical reason not to use reflection this far out in the API. This copies the pattern from other parts of casting between `structs.T` and `api.T`. I agree about the risks (the difference in fields I found demonstrates it).

[the remark this answers is not in the document]
Comment (tgross) [reply command/agent/csi_endpoint.go:223]: Fair enough, let's keep it consistent at least for now.

File: command/agent/csi_endpoint.go (hunk 1 above)
Comment (langmartin) [reply command/agent/csi_endpoint.go:67]: Well, we don't have to allow `POST` in the other, our rest conventions are a little weird around here. The method is missing `id` because our raft messages can send multiple volumes in the body, and passing the id is redundant. It also allows just using the same method for `POST`. If we're sticking close to typical rest conventions, `PUT` is for changing an object you've specified in the url and `POST` is directed at the parent and produces children as a side-effect. `csiVolumePut` allows `POST` so that `POST` can be supported up in `CSIVolumesRequest` where it could be used with multiple volumes.

Comment (tgross) [reply command/agent/csi_endpoint.go:67]: Sounds good.

File: command/agent/csi_endpoint.go [hunk 4]
```diff
@@ -210,5 +220,294 @@ func (s *HTTPServer) CSIPluginSpecificRequest(resp http.ResponseWriter, req *htt
...
+
+		// DEPRECATION NOTICE: The following fields are all deprecated. see TaskEvent struct in structs.go for details.
+		FailsTask:        te.FailsTask,
+		RestartReason:    te.RestartReason,
+		SetupError:       te.SetupError,
+		DriverError:      te.DriverError,
+		DriverMessage:    te.DriverMessage,
+		ExitCode:         te.ExitCode,
+		Signal:           te.Signal,
+		Message:          te.Message,
```
[the remark this answers is not in the document]
Comment (langmartin) [reply command/agent/csi_endpoint.go:477]: yes, it should

File: nomad/state/testing.go [hunk 5]
```diff
@@ -24,14 +24,27 @@ func TestStateStore(t testing.T) *StateStore {
 	return state
 }
 
-// CreateTestPlugin is a helper that generates the node + fingerprint results necessary to
-// create a CSIPlugin by directly inserting into the state store. It's exported for use in
-// other test packages
+// CreateTestCSIPlugin is a helper that generates the node + fingerprint results necessary
+// to create a CSIPlugin by directly inserting into the state store. The plugin requires a
+// controller.
```
[the remark this answers is not in the document]
Comment (langmartin) [reply nomad/state/testing.go:29]: I agree!

File: command/agent/csi_endpoint.go (hunk 2 above)
Comment (langmartin) [reply command/agent/csi_endpoint.go]: Yes, the ID is redundant in `csiVolumePut`, and the token length check is already done for `PUT`

Comment (langmartin) [reply command/agent/csi_endpoint.go]: The force push was a rebase to cover that merge conflict.
