### PR TITLE
exec: Fix incorrect `HOME` and `USER` env variables for tasks that have `user` set

### LINKED ISSUE #25854: `driver = "exec" user = "ubuntu"` sets incorrect environment variables
### Nomad version
Nomad v1.8.3
BuildDate 2024-08-13T07:37:30Z
Revision 63b636e5cbaca312cf6ea63e040f445f05f00478

### Operating system and Environment details
```
Linux ubuntu-buildhost2 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Issue

Though I set here user "ubuntu" the variables HOME and USER refers to root. This does not happen for the job of `type = "service"` and only exists for `type = "system"`.

Output for this job:
```
ubuntu
NOMAD_ALLOC_PORT_dd-tcp=8126
NOMAD_ALLOC_PORT_dd-udp=8125
NOMAD_HOST_ADDR_dd-udp=172.31.47.122:8125
NOMAD_HOST_IP_dd-udp=172.31.47.122
NOMAD_HOST_ADDR_dd-tcp=172.31.47.122:8126
NOMAD_HOST_IP_dd-tcp=172.31.47.122
SHELL=/usr/bin/bash
NOMAD_PORT_dd_udp=8125
NOMAD_REGION=planitar
NOMAD_CPU_LIMIT=100
MEMORY_PRESSURE_WRITE=XXX
NOMAD_JOB_ID=dd-agent
NOMAD_TASK_NAME=prepare-credentials-task
PWD=/
NOMAD_SECRETS_DIR=/secrets
LOGNAME=root
NOMAD_CPU_CORES= 
SYSTEMD_EXEC_PID=1776
HOME=/root
LANG=C.UTF-8
NOMAD_ADDR_dd_tcp=172.31.47.122:8126
MEMORY_PRESSURE_WATCH=/sys/fs/cgroup/system.slice/nomad.service/memory.pressure
NOMAD_NAMESPACE=default
NOMAD_IP_dd_udp=172.31.47.122
INVOCATION_ID=dfcc84824d4942c6876dd136f50e0256
NOMAD_ALLOC_INDEX=0
NOMAD_ALLOC_DIR=/alloc
NOMAD_JOB_NAME=dd-agent
NOMAD_HOST_PORT_dd_udp=8125
NOMAD_IP_dd_tcp=172.31.47.122
NOMAD_SHORT_ALLOC_ID=3eb50db8
USER=root
NOMAD_DC=plntr_dc
NOMAD_ALLOC_NAME=dd-agent.monitoring[0]
NOMAD_ADDR_dd_udp=172.31.47.122:8125
SHLVL=1
NOMAD_GROUP_NAME=monitoring
NOMAD_PARENT_CGROUP=nomad.slice
NOMAD_TASK_DIR=/local
NOMAD_MEMORY_LIMIT=300
JOURNAL_STREAM=8:13468
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/snap/bin
NOMAD_ALLOC_ID=3eb50db8-b911-b81e-1bd1-bdc2acb17440
NOMAD_HOST_PORT_dd_tcp=8126
NOMAD_PORT_dd_tcp=8126
_=/usr/bin/env
```

Error tab:
```
Unable to find image 'planitar/tools:latest' locally
docker: Error response from daemon: pull access denied for planitar/tools, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

cat: /root/.docker/config.json: No such file or directory
```

This cause issue that docker can not read properly `/home/ubuntu/.docker/config.json` and fail.

### Reproduction steps

Create job of type="system" and driver="exec" with user="ubuntu". Though Nomad start the job under ubuntu user not all environment variable are adjusted accordingly. This does not happen for the job of type="service".

```
job .. {
    type = "system"

    ....

      driver = "exec"
      user   = "ubuntu"

      config {
        command = "/bin/bash"
        args    = ["local/script.sh"]
      }

      template {
        destination = "local/script.sh"
        data        = <<-EOH
          set -xe
                whoami
                env
                cat ~/.docker/config.json
      ....

```

#### Expected Result
USER/HOME should point to "ubuntu" user.

#### Actual Result
USER/HOME points to "root" user.

### Job file (if appropriate)
see above

### PR DESCRIPTION
**Pull request by pkazmierczak**
Fixes #25854

### CODE REVIEW

**Comment by pkazmierczak** [comment]
> should we be setting them on other Unix platforms as well?

yeah I got a little confused in the `executor` code. `setCmd` implementation that we have in the linux file should actually be called on any Unix, because it calls stdlib methods underneath that should play nicely with all unixes.

File: drivers/shared/executor/executor_unix.go [hunk 1]
```diff
@@ -51,3 +55,55 @@ func (e *UniversalExecutor) shutdownProcess(sig os.Signal, proc *os.Process) err
...
+			return fmt.Errorf("unable to convert user's group to uint32 %s: %v", gidString, err)
+		}
+
+		gids = append(gids, uint32(u))
+	}
+
+	// Convert the uid and gid
+	uid, err := strconv.ParseUint(u.Uid, 10, 32)
+	if err != nil {
+		return fmt.Errorf("unable to convert userid to uint32: %s", err)
```
Comment (tgross) [inline drivers/shared/executor/executor_unix.go:86]:
```suggestion
		return fmt.Errorf("unable to convert userid to uint32: %w", err)
```

(typical of the errors here)

File: drivers/shared/executor/executor_linux_test.go [hunk 2]
```diff
@@ -830,6 +830,39 @@ func TestExecutor_WorkDir(t *testing.T) {
...
+// tricky on GHA runners.
+func TestExecutor_UserEnv(t *testing.T) {
+	t.Parallel()
+	testutil.ExecCompatible(t)
+
+	testExecCmd := testExecutorCommandWithChroot(t)
+	execCmd, allocDir := testExecCmd.command, testExecCmd.allocDir
+	execCmd.Cmd = "/bin/bash"
+	execCmd.Args = []string{"-c", "echo $USER"}
+	execCmd.User = "runner"
```
Comment (tgross) [inline drivers/shared/executor/executor_linux_test.go:844]: This test is always going to fail anywhere _except_ GitHub runners, right? Is there a `testutil` flag we can set to skip it?

**Review by tgross — APPROVED** [review]
LGTM

File: drivers/shared/executor/executor_linux_test.go (hunk 2 above)
Comment (pkazmierczak) [reply drivers/shared/executor/executor_linux_test.go:845]: good shout. Look at 92908a9.

**Review by tgross — APPROVED** [review]
LGTM

**Comment by schmichael** [comment]
Mind updating our docs to mention this behavior?

Unrelated https://developer.hashicorp.com/nomad/docs/job-specification/task#user incldues the weird phrase `This can only be set on Linux platforms` before describing how to use it on Windows. Maybe clean that up and mention the env var implications?

I think the most important docs would be to add `HOME` and `USER` here: https://developer.hashicorp.com/nomad/docs/runtime/environment

File: drivers/shared/executor/executor_unix.go [hunk 3]
```diff
@@ -51,3 +55,55 @@ func (e *UniversalExecutor) shutdownProcess(sig os.Signal, proc *os.Process) err
...
+	if cmd.SysProcAttr.Credential == nil {
+		cmd.SysProcAttr.Credential = &syscall.Credential{}
+	}
+	cmd.SysProcAttr.Credential.Uid = uint32(uid)
+	cmd.SysProcAttr.Credential.Gid = uint32(gid)
+	cmd.SysProcAttr.Credential.Groups = gids
+
+	// Override HOME and USER environment variables
+	cmd.Env = append(cmd.Env, fmt.Sprintf("USER=%s", u.Username))
+	cmd.Env = append(cmd.Env, fmt.Sprintf("HOME=%s", u.HomeDir))
```
Comment (EugenKon) [inline drivers/shared/executor/executor_unix.go:106]: There are could be a lot of variables missing. Also this could depend on the system where this is run.

@jbardin , @pkazmierczak 
I expect that something like `su - <username> -c "<command>"` will be run and let the system to decide which variables should adjusted.

Comment (EugenKon) [reply drivers/shared/executor/executor_unix.go:106]: If `HomeDir` will have spaces the code above will not work. Probably it should be "HOME=\"%s\"".

Comment (schmichael) [reply drivers/shared/executor/executor_unix.go:106]: > I expect that something like su - <username> -c "<command>" will be run and let the system to decide which variables should be adjusted.

The exec family of task drivers does *not* invoke a subshell to execute the task command. Docker, podman, systemd units, etc operate the same way to avoid security issues and crossplatform issues. Tasks which expect shell semantics should invoke the shell themselves. An `su`/subshell task driver would be an interesting experiment, but would be backward incompatible with the exec family.

> I suspect, if HomeDir will have spaces the code above will not work. Probably it should be "HOME=\"%s\"".

Quoting is a shell feature, not inherent to how UNIX encodes environment variables. Quotes should not be necessary even if the values contain spaces or additional equal signs. See: https://go.dev/play/p/FiV8FXiaNPr

Also please don't ping engineers in comments. `jbardin` hasn't worked on Nomad in years and is quite busy with other things. Commenting on PRs is welcome, but the author should be expected to receive a notification with being explicitly pinged.
