### PR TITLE
Check for changes to affinity, constraints and spread during update

### LINKED ISSUE #6334: v0.9.5: node-affinity stays after removing it from job spec
### Nomad version
v0.9.5 (1cbb2b9a81b5715be2f201a4650293c9ae517b87)

### Operating system and Environment details
Debian GNU/Linux 10 (buster)

### Issue
Node affinity stays in `Placement Metrics` after moving it out from the job spec.

### Reproduction steps

Testing Nomad cluster consists of single server and three client nodes, two of them have `meta.tier = hi`, the last one has `meta.tier = lo`.

Submitting the following job definition:

```
job "example" {
  datacenters = ["dc1"]
  type = "service"

  affinity {
    attribute = "${meta.tier}"
      value     = "hi"
      weight    = 100
  }

  group "cache" {
    count = 2

    task "redis" {
      driver = "docker"

      config {
        image = "redis:3.2"
        port_map {
          db = 6379
        }
      }

      resources {
        cpu    = 150 # 150 MHz
        memory = 64 # 64 MB
        network {
          mbits = 10
          port "db" {}
        }
      }

      service {
        name = "redis-cache"
        tags = ["global", "cache"]
        port = "db"
        check {
          name     = "alive"
          type     = "tcp"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }
  }
}
```

```
root@master:~# nomad run redis.nomad
==> Monitoring evaluation "6b5c6106"
    Evaluation triggered by job "example"
    Allocation "98832f04" created: node "6fc7950f", group "cache"
    Allocation "9a2567d2" created: node "16a5491e", group "cache"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "6b5c6106" finished with status "complete"
```

One node wins due to `node-affinity` (two of them match, because there are two nodes with `meta.tier = hi`):
```
root@master:~# nomad alloc status -verbose 98832f04
ID                  = 98832f04-2bd7-a1ac-500a-ea0dec112bf3
Eval ID             = 6b5c6106-9291-a65b-cbd6-98b88edd7dd6
Name                = example.cache[0]
Node ID             = 6fc7950f-6af1-001f-dc85-76690174e6a2
Node Name           = worker1
Job ID              = example
Job Version         = 824636458128
Client Status       = running
Client Description  = Tasks are running
Desired Status      = run
Desired Description = <none>
Created             = 2019-09-16T16:57:40Z
Modified            = 2019-09-16T16:58:05Z
Evaluated Nodes     = 3
Filtered Nodes      = 0
Exhausted Nodes     = 0
Allocation Time     = 137.848µs
Failures            = 0

Task "redis" is "running"
Task Resources
CPU        Memory           Disk     Addresses
6/150 MHz  1008 KiB/64 MiB  300 MiB  db: 10.0.2.15:29844

Task Events:
Started At     = 2019-09-16T16:57:50Z
Finished At    = N/A
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                  Type        Description
2019-09-16T16:57:50Z  Started     Task started by client
2019-09-16T16:57:40Z  Driver      Downloading image
2019-09-16T16:57:40Z  Task Setup  Building Task Directory
2019-09-16T16:57:40Z  Received    Task received by client

Placement Metrics
Node                                  node-affinity  binpack  job-anti-affinity  node-reschedule-penalty  final score
6fc7950f-6af1-001f-dc85-76690174e6a2  1              0.192    0                  0                        0.596
16a5491e-a3ed-8f4e-af18-e29e05f45b52  1              0.192    0                  0                        0.596
d711dc5e-20f5-fb6f-f227-2c91081672d2  0              0.192    0                  0                        0.192
```

Now I decide to remove the `affinity`:
```
job "example" {
  datacenters = ["dc1"]
  type = "service"

#  affinity {
#    attribute = "${meta.tier}"
#      value     = "hi"
#      weight    = 100
#  }

  group "cache" {
    count = 2

    task "redis" {
      driver = "docker"

      config {
        image = "redis:3.2"
        port_map {
          db = 6379
        }
      }

      resources {
        cpu    = 150 # 150 MHz
        memory = 64 # 64 MB
        network {
          mbits = 10
          port "db" {}
        }
      }

      service {
        name = "redis-cache"
        tags = ["global", "cache"]
        port = "db"
        check {
          name     = "alive"
          type     = "tcp"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }
  }
}
```

Looks like it'll go away as expected:
```
root@master:~# nomad plan redis.nomad 
+/- Job: "example"
- Affinity {
  - LTarget: "${meta.tier}"
  - Operand: "="
  - RTarget: "hi"
  - Weight:  "100"
  }
  Task Group: "cache" (2 in-place update)
    Task: "redis"

Scheduler dry-run:
- All tasks successfully allocated.
```

```
root@master:~# nomad job run redis.nomad 
==> Monitoring evaluation "d49d8c57"
    Evaluation triggered by job "example"
    Allocation "98832f04" modified: node "6fc7950f", group "cache"
    Allocation "9a2567d2" modified: node "16a5491e", group "cache"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "d49d8c57" finished with status "complete"
```

But there are still two nodes with `node-affinity` equal to 1
```
root@master:~# nomad alloc status -verbose 98832f04
ID                  = 98832f04-2bd7-a1ac-500a-ea0dec112bf3
Eval ID             = d49d8c57-d5be-a1f4-bb9e-67afe53aae3f
Name                = example.cache[0]
Node ID             = 6fc7950f-6af1-001f-dc85-76690174e6a2
Node Name           = worker1
Job ID              = example
Job Version         = 824635190912
Client Status       = running
Client Description  = Tasks are running
Desired Status      = run
Desired Description = <none>
Created             = 2019-09-16T16:57:40Z
Modified            = 2019-09-16T16:59:47Z
Evaluated Nodes     = 3
Filtered Nodes      = 0
Exhausted Nodes     = 0
Allocation Time     = 137.848µs
Failures            = 0

Task "redis" is "running"
Task Resources
CPU        Memory           Disk     Addresses
5/150 MHz  1008 KiB/64 MiB  300 MiB  db: 10.0.2.15:29844

Task Events:
Started At     = 2019-09-16T16:57:50Z
Finished At    = N/A
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                  Type        Description
2019-09-16T16:57:50Z  Started     Task started by client
2019-09-16T16:57:40Z  Driver      Downloading image
2019-09-16T16:57:40Z  Task Setup  Building Task Directory
2019-09-16T16:57:40Z  Received    Task received by client

Placement Metrics
Node                                  node-affinity  binpack  job-anti-affinity  node-reschedule-penalty  final score
6fc7950f-6af1-001f-dc85-76690174e6a2  1              0.192    0                  0                        0.596
16a5491e-a3ed-8f4e-af18-e29e05f45b52  1              0.192    0                  0                        0.596
d711dc5e-20f5-fb6f-f227-2c91081672d2  0              0.192    0                  0                        0.192
```

### PR DESCRIPTION
**Pull request by drewbailey**
Adds checks for affinity and constraint changes when determining if we
should update inplace.

fixes #6334

### CODE REVIEW

**Comment by drewbailey** [comment]
:question: If the same affinity is moved from the Job stanza into a TG stanza, this would result in a new alloc. Do we want to check for the calculated difference between all 3 possible levels of constraints/affinities ?

File: scheduler/util_test.go [hunk 1]
```diff
@@ -384,6 +384,89 @@ func TestShuffleNodes(t *testing.T) {
...
+	j1 := mock.Job()
+	j2 := mock.Job()
+	name := j1.TaskGroups[0].Name
+
+	require.False(t, tasksUpdated(j1, j2, name))
+
+	// TaskGroup Affinity
+	j2.TaskGroups[0].Affinities = []*structs.Affinity{
+		{
+			LTarget: "",
```
Comment (preetapan) [inline scheduler/util_test.go]: Can this be more realistic with operand "=", ltarget "node.datacenter" etc?

File: scheduler/util.go [hunk 2]
```diff
@@ -341,6 +341,15 @@ func tasksUpdated(jobA, jobB *structs.Job, taskGroup string) bool {
 	a := jobA.LookupTaskGroup(taskGroup)
 	b := jobB.LookupTaskGroup(taskGroup)
 
+	// Check Job level Affinities and Constraints
```
Comment (preetapan) [inline scheduler/util.go]: I think a cleaner way to do this would be to merge all affinities into a single slide and then check for equality. (same with Constraints). 
something like https://github.com/hashicorp/nomad/blob/master/scheduler/rank.go#L592 but you'd build the slice here. 

Also, Spreads is another similar concept (spreading instances based on node metadata) where we;d want to do the same thing here (apply a destructive update if the values changed).

Comment (preetapan) [reply scheduler/util.go]: This would address your question above (when something moves from a job to a task group level). It still wouldn't address cases where the ordering of multiple affinity stanza's changed but that seems like a rare edge case so an unnecessary destructive update is fine.

Comment (drewbailey) [reply scheduler/util.go]: Makes sense and I'll add a check for spreads as well, thanks

File: scheduler/util.go [hunk 3]
```diff
@@ -442,6 +457,93 @@ func networkPortMap(n *structs.NetworkResource) map[string]int {
...
+func affinitiesUpdated(jobA, jobB *structs.Job, taskGroup string) bool {
+	var aAffinities []*structs.Affinity
+	var bAffinities []*structs.Affinity
+
+	tgA := jobA.LookupTaskGroup(taskGroup)
+	tgB := jobB.LookupTaskGroup(taskGroup)
+
+	// Append jobA job and task group level affinities
+	aAffinities = append(aAffinities, jobA.Affinities...)
+	aAffinities = append(aAffinities, tgA.Affinities...)
```
Comment (preetapan) [inline scheduler/util.go]: This will panic if the taskgroup was added in jobB but didn't exist in jobA. (tgA will be nil). Should guard access to tgA behind a nil check

Worth adding a test case for as well.

Comment (preetapan) [reply scheduler/util.go]: Determined that before this method is called we short circuit if task group was removed (https://github.com/hashicorp/nomad/blob/c346a47b5b3db306c60a8a598f20dd13c5599db9/scheduler/reconcile.go#L317) 

Worth adding a comment for future readers of this code though

Comment (drewbailey) [reply scheduler/util.go]: comment added
