### PR TITLE
use both job and type query on scaling policy list endpoint

### LINKED ISSUE #9227: Scaling policy list filter with job and type ignores type
### Nomad version
`Nomad v1.0.0-beta2+ent (877c4b3c4a19a548f7dce72a12fcb152c325636a)`

### Operating system and Environment details
MacOS

### Issue
When querying for scaling policies, if both `job` and `type` are specified, only `job` will be used to filter results.

### Reproduction steps

```shellsession
$ nomad run example.nomad
$ curl -s 'http://localhost:4646/v1/scaling/policies?job=example&type=horizontal' | jq '.'
[
  {
    "ID": "0aaa0bea-15ca-e085-99d0-7cb0a172c951",
    "Enabled": false,
    "Type": "horizontal",
    "Target": {
      "Group": "foo",
      "Namespace": "default",
      "Job": "example"
    },
    "CreateIndex": 21,
    "ModifyIndex": 21
  },
  {
    "ID": "87777f10-6219-d901-6551-7b50ed5f4a70",
    "Enabled": true,
    "Type": "vertical_cpu",
    "Target": {
      "Namespace": "default",
      "Job": "example",
      "Group": "foo",
      "Task": "foo"
    },
    "CreateIndex": 21,
    "ModifyIndex": 21
  },
  {
    "ID": "8f26421c-8e99-433d-1c14-abe2dd23eb16",
    "Enabled": true,
    "Type": "vertical_mem",
    "Target": {
      "Task": "foo",
      "Namespace": "default",
      "Job": "example",
      "Group": "foo"
    },
    "CreateIndex": 21,
    "ModifyIndex": 21
  }
]
```

### Expected Result

```json
[
  {
    "ID": "0aaa0bea-15ca-e085-99d0-7cb0a172c951",
    "Enabled": false,
    "Type": "horizontal",
    "Target": {
      "Group": "foo",
      "Namespace": "default",
      "Job": "example"
    },
    "CreateIndex": 21,
    "ModifyIndex": 21
  },
]
```

### Job file (if appropriate)
```hcl
job "example" {
  datacenters = ["dc1"]
  group "foo" {
    scaling {
      enabled = false
      min     = 1
      max     = 20
      type    = "horizontal"
      policy {
        cooldown = "20s"
        check "avg_instance_sessions" {
          source = "prometheus"
          query  = "query"
          strategy "target-value" {
            target = 5
          }
        }
      }
    }
    task "foo" {
      driver = "raw_exec"
      config {
        command = "/bin/sleep"
        args    = ["10"]
      }
      scaling "cpu" {
        policy {
          check "check" {
            query = "query"
          }
        }
      }
      scaling "mem" {
        policy {
          check "check" {
            query = "query"
          }
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by cgbaker**
the `/v1/scaling/policies` list endpoint allows filtering by `?job` and `?type`. unfortunately, the code path for `job` ignored the `type` query. this PR remedies this. 

unsurprisingly, there weren't any tests protecting this behavior, so those are added as well.

resolves #9227

### CODE REVIEW

**Review by shoenig — APPROVED** [review]
LGTM!

File: nomad/state/state_store.go [hunk 1]
```diff
@@ -5760,9 +5760,27 @@ func (s *StateStore) ScalingPoliciesByNamespace(ws memdb.WatchSet, namespace, ty
...
+	if policyType == "" {
+		return iter, nil
+	}
+
+	filter := func(raw interface{}) bool {
+		p, ok := raw.(*structs.ScalingPolicy)
+		if !ok {
+			return true
+		}
+		return policyType != p.Type
```
Comment (krishicks) [inline nomad/state/state_store.go:5780]: I think my only comment about this is that it seems like this check could be moved into `ScalingPoliciesByJobTxn`, where the new `policyType string` would be passed through to it.

Looking at `ScalingPoliciesByJobTxn`, it already does the same kind of type assertion we see here, so it happening again (specifically the `!ok` part, which I think is _inconceivable_) makes me want a single `filter` that lives in a single place.

**Review by krishicks — APPROVED** [review]

File: nomad/state/state_store.go (hunk 1 above)
Comment (cgbaker) [reply nomad/state/state_store.go:5780]: yeah, maybe 50/50? this short-circuits the filter on the outside of the loop when `policyType == ""`, as opposed to doing it on every filter operation. merging them avoids duplicate cast assertion checks.
