### PR TITLE
drivers/docker: refactor use of clients in docker driver

### LINKED ISSUE #17023: docker task driver overrides max_kill_timeout
#### Describe the bug
 
The Docker Task drivers' [dockerTimeout setting](https://github.com/hashicorp/nomad/blob/891999789689240006b2a6076b73ddc67249d48d/drivers/docker/config.go#L39-L41) supersedes Nomad's `max_kill_timeout` setting.
 
#### Steps to reproduce the behavior.
Configure a `max_kill_timeout` for a period longer than 5 minutes.  Run a Nomad job that utilizes the docker driver and then initiate a stop.  Once an initial signal is sent via nomad alloc stop <allocid> the docker driver will send another signal in `5 * time.Min`
 
#### Expected behavior
The expected behavior is that Nomad's max_kill_timeout will override task driver timeout settings.
 
Product Version: _Current_ 1.5.x

```
ubuntu@ip-172-31-17-63:~$ cat /etc/nomad.d/nomad.hcl | grep max
  max_kill_timeout = "10m"
ubuntu@ip-172-31-17-63:~$
```
```
job "simple" {
  datacenters = ["dc1"]
  type = "batch"

  periodic {
    cron             = "*/1 * * * *"
    prohibit_overlap = true
  }

  group "simple" {
    task "simple" {
      driver       = "docker"
      kill_timeout = "10m"

      config {
        image   = "ubuntu:latest"
        command = "bash"
        args    = ["-c", "/local/script.sh"]
      }

      template {
        data        = <<EOF
#!/bin/bash

# set trap
trap 'echo "Received SIGTERM doint nothing..."' SIGTERM
i=1

for i in {1..250}; do
#Print message with counter i
echo "[$(date -u)] running the loop for $i times; sleeping"
sleep 5
#Increment the counter by one
((i++))
done
EOF
        perms       = "755"
        destination = "local/script.sh"
      }

      resources {
        cpu    = 100
        memory = 100
      }
    }
  }
}
```
```
ubuntu@ip-172-31-17-63:~$ nomad job status
ID                          Type            Priority  Status   Submit Date
example                     service         50        running  2022-07-22T15:15:01Z
plugin-aws-ebs-controller   service         50        running  2022-07-23T01:11:39Z
plugin-aws-ebs-nodes        system          50        running  2022-07-23T01:11:35Z
plugin-efs                  system          50        running  2022-07-23T01:08:48Z
simple                      batch/periodic  50        running  2022-08-02T05:45:57Z
simple/periodic-1659454200  batch           50        running  2022-08-02T15:30:00Z
```
```
ubuntu@ip-172-31-17-63:~$ nomad job status simple/
ID            = simple/periodic-1659454200
Name          = simple/periodic-1659454200
Submit Date   = 2022-08-02T15:30:00Z
Type          = batch
Priority      = 50
Datacenters   = dc1
Namespace     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
simple      0       0         1        0       0         0     0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created  Modified
0d0aca38  4885b6de  simple      0        run      running  7s ago   4s ago

ubuntu@ip-172-31-17-63:~$ nomad alloc status 0d
ID                  = 0d0aca38-4195-e8e0-cd70-a8785a5ef2a6
Eval ID             = d28788f4
Name                = simple/periodic-1659454200.simple[0]
Node ID             = 4885b6de
Node Name           = ip-172-31-17-63
Job ID              = simple/periodic-1659454200
Job Version         = 0
Client Status       = running
Client Description  = Tasks are running
Desired Status      = run
Desired Description = <none>
Created             = 30s ago
Modified            = 27s ago

Task "simple" is "running"
Task Resources
CPU        Memory           Disk     Addresses
3/100 MHz  416 KiB/100 MiB  300 MiB

Task Events:
Started At     = 2022-08-02T15:30:02Z
Finished At    = N/A
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                  Type        Description
2022-08-02T15:30:02Z  Started     Task started by client
2022-08-02T15:30:00Z  Driver      Downloading image
2022-08-02T15:30:00Z  Task Setup  Building Task Directory
2022-08-02T15:30:00Z  Received    Task received by client

ubuntu@ip-172-31-17-63:~$ nomad alloc stop 0d
==> 2022-08-02T15:30:50Z: Monitoring evaluation "eef8571c"
    2022-08-02T15:30:50Z: Evaluation triggered by job "simple/periodic-1659454200"
    2022-08-02T15:30:50Z: Allocation "d66f9e99" created: node "4885b6de", group "simple"
    2022-08-02T15:30:51Z: Evaluation status changed: "pending" -> "complete"
==> 2022-08-02T15:30:51Z: Evaluation "eef8571c" finished with status "complete"
```
```
ubuntu@ip-172-31-17-63:~$ nomad alloc status 0d
ID                   = 0d0aca38-4195-e8e0-cd70-a8785a5ef2a6
Eval ID              = d28788f4
Name                 = simple/periodic-1659454200.simple[0]
Node ID              = 4885b6de
Node Name            = ip-172-31-17-63
Job ID               = simple/periodic-1659454200
Job Version          = 0
Client Status        = running
Client Description   = Tasks are running
Desired Status       = stop
Desired Description  = alloc is being migrated
Created              = 1m ago
Modified             = 10s ago
Replacement Alloc ID = d66f9e99

Task "simple" is "running"
Task Resources
CPU        Memory           Disk     Addresses
0/100 MHz  420 KiB/100 MiB  300 MiB

Task Events:
Started At     = 2022-08-02T15:30:02Z
Finished At    = N/A
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                  Type        Description
2022-08-02T15:30:50Z  Killing     Sent interrupt. Waiting 10m0s before force killing
2022-08-02T15:30:02Z  Started     Task started by client
2022-08-02T15:30:00Z  Driver      Downloading image
2022-08-02T15:30:00Z  Task Setup  Building Task Directory
2022-08-02T15:30:00Z  Received    Task received by client
```

##### Here is the log output. The first SIGTERM is when I ran nomad alloc stop 0d. I didn't touch Nomad after that and I observed another SIGTERM @ [Tue Aug 2 15:35:52 UTC 2022] running the loop for 71 times; sleeping

```
ubuntu@ip-172-31-17-63:~$ nomad alloc logs -f 0d
[Tue Aug  2 15:30:02 UTC 2022] running the loop for 1 times; sleeping
[Tue Aug  2 15:30:07 UTC 2022] running the loop for 2 times; sleeping
[Tue Aug  2 15:30:12 UTC 2022] running the loop for 3 times; sleeping
[Tue Aug  2 15:30:17 UTC 2022] running the loop for 4 times; sleeping
[Tue Aug  2 15:30:22 UTC 2022] running the loop for 5 times; sleeping
[Tue Aug  2 15:30:27 UTC 2022] running the loop for 6 times; sleeping
[Tue Aug  2 15:30:32 UTC 2022] running the loop for 7 times; sleeping
[Tue Aug  2 15:30:37 UTC 2022] running the loop for 8 times; sleeping
[Tue Aug  2 15:30:42 UTC 2022] running the loop for 9 times; sleeping
[Tue Aug  2 15:30:47 UTC 2022] running the loop for 10 times; sleeping
Received SIGTERM doint nothing...                               
[Tue Aug  2 15:30:52 UTC 2022] running the loop for 11 times; sleeping
[Tue Aug  2 15:30:57 UTC 2022] running the loop for 12 times; sleeping
[Tue Aug  2 15:31:02 UTC 2022] running the loop for 13 times; sleeping
[Tue Aug  2 15:31:07 UTC 2022] running the loop for 14 times; sleeping
[Tue Aug  2 15:31:12 UTC 2022] running the loop for 15 times; sleeping
[Tue Aug  2 15:31:17 UTC 2022] running the loop for 16 times; sleeping
[Tue Aug  2 15:31:22 UTC 2022] running the loop for 17 times; sleeping
[Tue Aug  2 15:31:27 UTC 2022] running the loop for 18 times; sleeping
[Tue Aug  2 15:31:32 UTC 2022] running the loop for 19 times; sleeping
[Tue Aug  2 15:31:37 UTC 2022] running the loop for 20 times; sleeping
[Tue Aug  2 15:31:42 UTC 2022] running the loop for 21 times; sleeping
[Tue Aug  2 15:31:47 UTC 2022] running the loop for 22 times; sleeping
[Tue Aug  2 15:31:52 UTC 2022] running the loop for 23 times; sleeping
[Tue Aug  2 15:31:57 UTC 2022] running the loop for 24 times; sleeping
[Tue Aug  2 15:32:02 UTC 2022] running the loop for 25 times; sleeping
[Tue Aug  2 15:32:07 UTC 2022] running the loop for 26 times; sleeping
[Tue Aug  2 15:32:12 UTC 2022] running the loop for 27 times; sleeping
[Tue Aug  2 15:32:17 UTC 2022] running the loop for 28 times; sleeping
[Tue Aug  2 15:32:22 UTC 2022] running the loop for 29 times; sleeping
[Tue Aug  2 15:32:27 UTC 2022] running the loop for 30 times; sleeping
[Tue Aug  2 15:32:32 UTC 2022] running the loop for 31 times; sleeping
[Tue Aug  2 15:32:37 UTC 2022] running the loop for 32 times; sleeping
[Tue Aug  2 15:32:42 UTC 2022] running the loop for 33 times; sleeping
[Tue Aug  2 15:32:47 UTC 2022] running the loop for 34 times; sleeping
[Tue Aug  2 15:32:52 UTC 2022] running the loop for 35 times; sleeping
[Tue Aug  2 15:32:57 UTC 2022] running the loop for 36 times; sleeping
[Tue Aug  2 15:33:02 UTC 2022] running the loop for 37 times; sleeping
[Tue Aug  2 15:33:07 UTC 2022] running the loop for 38 times; sleeping
[Tue Aug  2 15:33:12 UTC 2022] running the loop for 39 times; sleeping
[Tue Aug  2 15:33:17 UTC 2022] running the loop for 40 times; sleeping
[Tue Aug  2 15:33:22 UTC 2022] running the loop for 41 times; sleeping
[Tue Aug  2 15:33:27 UTC 2022] running the loop for 42 times; sleeping
[Tue Aug  2 15:33:32 UTC 2022] running the loop for 43 times; sleeping
[Tue Aug  2 15:33:37 UTC 2022] running the loop for 44 times; sleeping
[Tue Aug  2 15:33:42 UTC 2022] running the loop for 45 times; sleeping
[Tue Aug  2 15:33:47 UTC 2022] running the loop for 46 times; sleeping
[Tue Aug  2 15:33:52 UTC 2022] running the loop for 47 times; sleeping
[Tue Aug  2 15:33:57 UTC 2022] running the loop for 48 times; sleeping
[Tue Aug  2 15:34:02 UTC 2022] running the loop for 49 times; sleeping
[Tue Aug  2 15:34:07 UTC 2022] running the loop for 50 times; sleeping
[Tue Aug  2 15:34:12 UTC 2022] running the loop for 51 times; sleeping
[Tue Aug  2 15:34:17 UTC 2022] running the loop for 52 times; sleeping
[Tue Aug  2 15:34:22 UTC 2022] running the loop for 53 times; sleeping
[Tue Aug  2 15:34:27 UTC 2022] running the loop for 54 times; sleeping
[Tue Aug  2 15:34:32 UTC 2022] running the loop for 55 times; sleeping
[Tue Aug  2 15:34:37 UTC 2022] running the loop for 56 times; sleeping
[Tue Aug  2 15:34:42 UTC 2022] running the loop for 57 times; sleeping
[Tue Aug  2 15:34:47 UTC 2022] running the loop for 58 times; sleeping
[Tue Aug  2 15:34:52 UTC 2022] running the loop for 59 times; sleeping
[Tue Aug  2 15:34:57 UTC 2022] running the loop for 60 times; sleeping
[Tue Aug  2 15:35:02 UTC 2022] running the loop for 61 times; sleeping
[Tue Aug  2 15:35:07 UTC 2022] running the loop for 62 times; sleeping
[Tue Aug  2 15:35:12 UTC 2022] running the loop for 63 times; sleeping
[Tue Aug  2 15:35:17 UTC 2022] running the loop for 64 times; sleeping
[Tue Aug  2 15:35:22 UTC 2022] running the loop for 65 times; sleeping
[Tue Aug  2 15:35:27 UTC 2022] running the loop for 66 times; sleeping
[Tue Aug  2 15:35:32 UTC 2022] running the loop for 67 times; sleeping
[Tue Aug  2 15:35:37 UTC 2022] running the loop for 68 times; sleeping
[Tue Aug  2 15:35:42 UTC 2022] running the loop for 69 times; sleeping
[Tue Aug  2 15:35:47 UTC 2022] running the loop for 70 times; sleeping
[Tue Aug  2 15:35:52 UTC 2022] running the loop for 71 times; sleeping
Received SIGTERM doint nothing...
[Tue Aug  2 15:35:57 UTC 2022] running the loop for 72 times; sleeping
[Tue Aug  2 15:36:02 UTC 2022] running the loop for 73 times; sleeping
[Tue Aug  2 15:36:07 UTC 2022] running the loop for 74 times; sleeping
[Tue Aug  2 15:36:12 UTC 2022] running the loop for 75 times; sleeping
[Tue Aug  2 15:36:18 UTC 2022] running the loop for 76 times; sleeping
[Tue Aug  2 15:36:23 UTC 2022] running the loop for 77 times; sleeping
```

### PR DESCRIPTION
**Pull request by shoenig**
This PR refactors how we manage the two underlying clients used by the
docker driver for communicating with the docker daemon. We keep two clients

One with a hard-coded timeout that applies to all operations no matter
what, intended for use with short lived / async calls to docker.

The other has no timeout and is the responsibility of the caller to set a
context that will ensure the call eventually terminates (except in the `.Wait` case).

The use of these two clients has been confusing and mistakes were made
in a number of places where calls were making use of the wrong client.

This PR makes it so that a user must explicitly call a function to get
the client that makes sense for that use case.

Fixes #17023

### CODE REVIEW

File: drivers/docker/handle.go [hunk 1]
```diff
@@ -159,7 +167,13 @@ func (h *taskHandle) Kill(killTimeout time.Duration, signal string) error {
...
 	// calling StopContainer
 	if signal == "" {
-		err = h.client.StopContainer(h.containerID, uint(killTimeout.Seconds()))
+		// give the context timeout some wiggle room beyond the kill timeout
+		// docker will use, so we can happy path even in the force kill case
+		graciousTimeout := killTimeout + dockerTimeout
+		ctx, cancel := context.WithTimeout(context.Background(), graciousTimeout)
+		defer cancel()
+		apiTimeout := uint(killTimeout.Seconds())
+		err = h.infinityClient.StopContainerWithContext(h.containerID, apiTimeout, ctx)
```
Comment (tgross) [inline drivers/docker/handle.go:176]: This is the major user-facing change, right? We'll want a changelog item for this.

File: drivers/docker/handle.go [hunk 2]
```diff
@@ -239,7 +253,7 @@ func (h *taskHandle) run() {
 		werr = fmt.Errorf("Docker container exited with non-zero exit code: %d", exitCode)
 	}
 
-	container, ierr := h.waitClient.InspectContainerWithOptions(docker.InspectContainerOptions{
+	container, ierr := h.dockerClient.InspectContainerWithOptions(docker.InspectContainerOptions{
```
Comment (tgross) [inline drivers/docker/handle.go:256]: This seems to be the only other behavior change... but I'm not sure how user facing it is in practice? Should we add it to the changelog anyways?

**Review by tgross — APPROVED** [review]
LGTM

File: drivers/docker/handle.go [hunk 3]
```diff
@@ -25,8 +25,15 @@ import (
 )
 
 type taskHandle struct {
-	client                *docker.Client
-	waitClient            *docker.Client
+	// dockerClient is useful for normal, non blocking docker API calls. It is
+	// configured with the default timeout (5 minutes).
```
[the remark this answers is not in the document]
Comment (shoenig) [reply drivers/docker/handle.go:29]: Reworded these a bit to avoid "blocking" and just refer to the specific docker API we care about

File: drivers/docker/handle.go (hunk 1 above)
Comment (shoenig) [reply drivers/docker/handle.go:176]: Yup!
