### PR TITLE
Return FailedTGAlloc metric instead of no node err

### LINKED ISSUE #5169: system scheduler: error when performing plan/run with disabled nodes
### Nomad version
Output from `Nomad v0.8.6 (ab54ebcfcde062e9482558b7c052702d4cb8aa1b+CHANGES)`

### Operating system and Environment details
OS: `ubuntu-18.04`

### Issue
When attempting to plan/run a Nomad system job (which includes constraints) on a node pool which includes administratively disabled nodes, the call will fail with the following error:

```
Unexpected response code: 500 (rpc error: could not find node \"f5dd4bad-ddec-796d-6ab5-d11d80324ad5\")
``` 

The plan/run will succeed once the node is enabled in the cluster.

### Reproduction steps
Disable a node client node and then attempt to deploy a system job, potentially with constraints as I am not sure if this is a key part of this issue.

### Job file (if appropriate)

```
job "example" {
  datacenters = ["dc1"]
  type        = "system"

  group "example" {
    constraint {
      operator  = "="
      attribute = "${meta.role}"
      value     = "specificrole"
    }
...
```

### PR DESCRIPTION
**Pull request by drewbailey**
If an existing system allocation is running and the node its running on
is marked as ineligible, subsequent plan/applys return an RPC error
instead of a more helpful plan result.

This change logs the error, and appends a failedTGAlloc for the
placement.

fixes #5169

### CODE REVIEW

File: scheduler/system_sched.go [hunk 1]
```diff
@@ -275,7 +275,13 @@ func (s *SystemScheduler) computePlacements(place []allocTuple) error {
...
 		node, ok := nodeByID[missing.Alloc.NodeID]
 		if !ok {
-			return fmt.Errorf("could not find node %q", missing.Alloc.NodeID)
+			s.logger.Debug("could not find node %q", missing.Alloc.NodeID)
+			if s.failedTGAllocs == nil {
+				s.failedTGAllocs = make(map[string]*structs.AllocMetric)
+			}
+
+			s.failedTGAllocs[missing.TaskGroup.Name] = s.ctx.Metrics()
+			continue
```
Comment (drewbailey) [inline scheduler/system_sched.go]: Alternatively we could just log the error here and then call `s.stack.SetNodes(nodes)` with zero nodesto allow `stack.Select` to occur and possibly populate more Metrics

Comment (langmartin) [reply scheduler/system_sched.go]: This way we get a record of which node was missing when we tried to place the alloc, though, right? That seems better than the alternative.

Comment (tgross) [reply scheduler/system_sched.go]: Previously we'd return early but now we're collecting the metrics info (which is great!) but then continuing on. From the operator's perspective does this mean that we're going to have a partial placement?

Comment (tgross) [reply scheduler/system_sched.go]: :+1: Makes sense.
