### PR TITLE
cli: operator debug: respect NOMAD_REGION env var

### LINKED ISSUE #25672: nomad operator debug ignores NOMAD_REGION
### Nomad version
Nomad v1.10.0
BuildDate 2025-04-09T16:40:54Z
Revision e26a2bd2acac2dcdcb623f4d293bac096beef478

### Operating system and Environment details
Ubuntu 24.04.2 LTS on amd64

### Issue
Running `NOMAD_REGION=global nomad operator debug` does not capture the `NOMAD_REGION` env variable. 

Fun fact: if you set this to a non-existing nomad region, you get this error instead:

```
Error querying node info: Unexpected response code: 500 (rpc error: No path to region)
```

Providing the `-region` parameter does always work; this is environment variable related. 

Note that I am now writing `global` as the region - this can be any region that exists.

### Reproduction steps
- Run  `NOMAD_REGION=global nomad operator debug`
- See the `Region` output be empty

#### Expected Result
To have the region listed in the output. 

#### Actual Result
```
Starting debugger...

Nomad CLI Version: Nomad v1.10.0
BuildDate 2025-04-09T16:40:54Z
Revision e26a2bd2acac2dcdcb623f4d293bac096beef478
           Region:
        Namespace:
```

And a bit later, during the `Capturing cluster data...`

```
server/nomad01-del.delmenhorst: Failed to retrieve agent host data, err: Unexpected response code: 500 (rpc error: unknown Nomad server nomad01-del.delmenhorst)
server/dock01-nomad-del.delmenhorst: Failed to retrieve agent host data, err: Unexpected response code: 500 (rpc error: unknown Nomad server dock01-nomad-del.delmenhorst)
server/mini-ubuntu-nomad-del.delmenhorst: Failed to retrieve agent host data, err: Unexpected response code: 500 (rpc error: unknown Nomad server mini-ubuntu-nomad-del.delmenhorst)
```

These are the servers in a different region.

### Job file (if appropriate)
Not applicable.

### Nomad Server logs (if appropriate)
Not applicable.

### Nomad Client logs (if appropriate)
Not applicable.

### PR DESCRIPTION
**Pull request by gulducat**
Fixes #25672 - tl;dr `NOMAD_REGION` and `NOMAD_NAMESPACE` are ignored by `nomad operator debug`

I thought about having `Meta.clientConfig()` _write_ `Meta.region` and `Meta.namespace`, but that felt off, so I opted for a couple of getters that can hopefully be easily discovered if needed for other cases.

Before:

```
$ NOMAD_REGION=global NOMAD_NAMESPACE=default nomad operator debug
Starting debugger...

Nomad CLI Version: Nomad v1.10.0
BuildDate 2025-04-09T16:40:54Z
Revision e26a2bd2acac2dcdcb623f4d293bac096beef478
           Region:
        Namespace:
          Servers: (1/1) ... etc etc ...
```

After:

```
$ NOMAD_REGION=global NOMAD_NAMESPACE=default nomad operator debug
Starting debugger...

Nomad CLI Version: Nomad v1.10.1-dev
BuildDate 2025-04-21T18:49:12Z
Revision c86d63da13145326ae69649fa9c51601dc16914a+CHANGES
           Region: global
        Namespace: default
          Servers: (1/1) ... etc etc ...
```

### CODE REVIEW

File: command/operator_debug.go [hunk 1]
```diff
@@ -512,7 +512,7 @@ func (c *OperatorDebugCommand) Run(args []string) int {
 	}
 
 	c.opts = &api.QueryOptions{
-		Region:     c.Meta.region,
+		Region:     c.Meta.Region(),
```
Comment (tgross) [inline command/operator_debug.go:515]: This PR fixes the reported bug, but why are we passing the region like this at all in an API request? I think `operator debug` is the only command to do so. This should already go to the right region by virtue of how the API client gets constructed.

```suggestion
```

**Review by tgross — APPROVED** [review]

File: command/operator_debug.go (hunk 1 above)
Comment (gulducat) [reply command/operator_debug.go:515]: good point. I believe here in `QueryOptions` an empty region is ignored, and specifying it is redundant, because yes it's a part of the API client, so may as well drop this line.

for clarity, the actual bugfix is passing the proper region into `filterServerMembers` below.

and now I'm realizing that `NOMAD_NAMESPACE` is unaffected by this bug, and its only shortcoming was not being `c.Ui.Output` properly.

**Review by tgross — APPROVED** [review]
LGTM!
