### PR TITLE
cli: Fix bug in `var put` command using mix of flags and spec.

### LINKED ISSUE #19420: cli: panic within `var put` command with certain combination of inputs
### Nomad version
```
$ nomad version
Nomad v1.7.2-dev
BuildDate 2023-12-08T21:05:05Z
Revision e551814df5f271a3ad2f69ed4fd812ce2807be84
```

### Issue
The locally run Nomad CLI panics with the following output:
```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/hashicorp/nomad/command.(*VarPutCommand).Run(0x14000638480, {0x140001a8210, 0x2, 0x2})
	github.com/hashicorp/nomad/command/var_put.go:306 +0x1558
github.com/mitchellh/cli.(*CLI).Run(0x14000a4a640)
	github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x4a8
main.Run({0x140001a81f0, 0x4, 0x4})
	github.com/hashicorp/nomad/main.go:110 +0x21c
main.main()
	github.com/hashicorp/nomad/main.go:80 +0x54
```

### Reproduction steps
1. Run Nomad in dev mode via `nomad agent -dev`
2. Create a local file name `spec.nv.hcl` with the following contents:
```
path      = "path/to/variable"
namespace = "default"
```
3. Run the Nomad CLI command `nomad var put @spec.nv.hcl 'key=value'`

### PR DESCRIPTION
**Pull request by jrasell**
closes #19420

### CODE REVIEW

File: command/var_put_test.go [hunk 1]
```diff
@@ -107,6 +108,44 @@ func TestVarPutCommand_GoodJson(t *testing.T) {
...
+	must.NoError(t, err)
+
+	// Create the variables, ensure we clean it up, and check the command
+	// response.
+	code := cmd.Run([]string{"-address=" + url, "@" + osFile.Name(), "k1=v1", "k2=v2"})
+	must.Zero(t, code)
+
+	t.Cleanup(func() {
+		_, _ = client.Variables().Delete("test/var", nil)
+	})
```
Comment (tgross) [inline command/var_put_test.go:142]: We don't need to worry about this, as we'll be throwing away the in-memory test server at the end of the test.

**Review by tgross — APPROVED** [review]
LGTM!
