### PR TITLE
Synchronously deregister agent on shutdown

### LINKED ISSUE #2891: Failed/left agents never deregister from Consul
### Nomad version
nomad 0.6.0rc2 (Nomad was doing this since at least 0.5.6 or before)

### Reproduction steps
Terminate a nomad agent node (client or server), or run `nomad server-force-leave`

### Issue
When a nomad agent (client or server) "fails, leaves, or most likely scaled in" it never deregisters from Consul due to some HTTP health checks remain incorrectly passing although the serf health check is failing as expected. What seems strange about this is that the IPs listed in the Consul check don't even have listening instances after the scale-in event. This behavior only appears to affect Nomad which is what leads me to believe it's in an issue with the way nomad registers with Consul.

Manual curl run from healthy consul server which times out as expected
```
[user@qa-consul-0d2b38c891e622c31 ~]$ curl http://192.177.177.212:4646/v1/status/peers
curl: (7) Failed to connect to 192.177.177.212 port 4646: Connection timed out
```

Actual Consul status screenshots
screen shot 2017-07-23 at 9 16 05 am

screen shot 2017-07-23 at 9 17 00 am

### PR DESCRIPTION
**Pull request by schmichael**
Fixes #2891

Previously the agent services and checks were being asynchronously deregistered on shutdown, so it was a race between the sync goroutine deregistering them and Nomad shutting down.

This switches to synchronously deregister agent services and checks. The only downside is that we can't use the main sync loops error tracking to know whether or not to log errors.

I added the `Seen()`/`MarkSeen()` methods to allow easily squelching error messages if Consul has never been seen. Might be useful elsewhere in the future.

### CODE REVIEW

File: client/alloc_runner.go [hunk 1]
```diff
@@ -289,6 +289,12 @@ func (r *AllocRunner) RestoreState() error {
 		name := task.Name
 		state := r.taskStates[name]
 
+		// Nomad exited before task could start, nothing to restore.
+		// AllocRunner.Run will start a new TaskRunner for this task
+		if state == nil {
+			continue
+		}
```
Comment (schmichael) [inline client/alloc_runner.go]: Snuck in this state check as well. Sorry.

File: command/agent/consul/int_test.go [hunk 2]
```diff
@@ -31,7 +31,6 @@ func testLogger() *log.Logger {
 // TestConsul_Integration asserts TaskRunner properly registers and deregisters
 // services and checks with Consul using an embedded Consul agent.
 func TestConsul_Integration(t *testing.T) {
-	t.Skip("-short set; skipping")
```
Comment (dadgar) [inline command/agent/consul/int_test.go]: Ah my bad I leaked this in. So I am not 100% sure it is this test but 85+% sure that it can leak the Consul agent sometimes. I noticed running make test many times that *1* consul agent sticks around and consumes a lot of CPU (70+%). May be worth looking into

File: command/agent/consul/client.go [hunk 3]
```diff
@@ -139,6 +144,21 @@ func NewServiceClient(consulClient AgentAPI, skipVerifySupport bool, logger *log
 	}
 }
 
+// seen is used by MarkSeen and Seen
```
Comment (dadgar) [inline command/agent/consul/client.go]: Gave offline comments.

File: command/agent/consul/int_test.go (hunk 2 above)
Comment (schmichael) [inline command/agent/consul/int_test.go]: Tracked it down. I was calling `testtask.Path()` without setting the environment which caused these tests to be re-executed and killed... when the erroneously re-executed tests were killed it would leak a Consul.

(This was as fun to debug as it sounds.)
