### PR TITLE
template: protect use of template manager with a lock

### LINKED ISSUE #15189: Nomad 1.4.2 - panic: runtime error: invalid memory address or nil pointer dereference
### Nomad version
1.4.2

### Operating system and Environment details
Ubuntu 22.04 AMD64
1 x Nomad Server (1.4.2)
3 x Nomad Clients (1.4.2)
cni plugins (1.1.1) - using some nfs volumes

### Issue
Nomad's service panic in our CI/DEV Cluster after upgrade to 1.4.2. 
It happens in all the clients, Nomad service keeps restarting.
Draining the affected node seems to stop the panic/restarts.

### Reproduction steps
Restart nomad service (systemd)

#### Actual Result
Nomad service panics and keeps restarting

### Nomad Client logs (if appropriate)

Nov  8 17:37:40 <computer_name> nomad[998943]: panic: runtime error: invalid memory address or nil pointer dereference
Nov  8 17:37:40 <computer_name> nomad[998943]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x16b105d]
Nov  8 17:37:40 <computer_name> nomad[998943]: goroutine 1522 [running]:
Nov  8 17:37:40 <computer_name> nomad[998943]: github.com/hashicorp/nomad/client/allocrunner/taskrunner/template.(*TaskTemplateManager).SetDriverHandle(0x1?, {0x31c6440?, 0xc00282c780?})
Nov  8 17:37:40 <computer_name> nomad[998943]: #011github.com/hashicorp/nomad/client/allocrunner/taskrunner/template/template.go:201 +0x3d
Nov  8 17:37:40 <computer_name> nomad[998943]: github.com/hashicorp/nomad/client/allocrunner/taskrunner.(*templateHook).Poststart(0xc0019ac480?, {0x31c66e0?, 0xc00012f580?}, 0xc004aa8270?, 0xc000ae4870?)
Nov  8 17:37:40 <computer_name> nomad[998943]: #011github.com/hashicorp/nomad/client/allocrunner/taskrunner/template_hook.go:120 +0x3d
Nov  8 17:37:40 <computer_name> nomad[998943]: github.com/hashicorp/nomad/client/allocrunner/taskrunner.(*TaskRunner).poststart(0xc0019b4000)
Nov  8 17:37:40 <computer_name> nomad[998943]: #011github.com/hashicorp/nomad/client/allocrunner/taskrunner/task_runner_hooks.go:346 +0x63d
Nov  8 17:37:40 <computer_name> nomad[998943]: github.com/hashicorp/nomad/client/allocrunner/taskrunner.(*TaskRunner).Run(0xc0019b4000)
Nov  8 17:37:40 <computer_name> nomad[998943]: #011github.com/hashicorp/nomad/client/allocrunner/taskrunner/task_runner.go:606 +0x965
Nov  8 17:37:40 <computer_name> nomad[998943]: created by github.com/hashicorp/nomad/client/allocrunner.(*allocRunner).runTasks
Nov  8 17:37:40 <computer_name> nomad[998943]: #011github.com/hashicorp/nomad/client/allocrunner/alloc_runner.go:395 +0x6c
Nov  8 17:37:43 <computer_name> nomad[1000004]: ==> Loaded configuration from /opt/nomad/nomad.d/nomad-consul.json, /opt/nomad/nomad.d/nomad-docker.hcl, /opt/nomad/nomad.d/nomad-docker.json, /opt/nomad/nomad.d/nomad-tls.json, /opt/nomad/nomad.d/nomad.json, /opt/nomad/nomad.d/nomad_dogstatsd.json
Nov  8 17:37:43 <computer_name> nomad[1000004]: ==> Starting Nomad agent...

### PR DESCRIPTION
**Pull request by shoenig**
This PR protects access to `templateHook.templateManager` with its lock. So
far we have not been able to reproduce the panic - but it seems either Poststart
is running without a Prestart being run first (should be impossible), or the
Update hook is running concurrently with Poststart, nil-ing out the templateManager
in a race with Poststart.

Fixes #15189

Backport only to 1.4.x and 1.3.x

### CODE REVIEW

File: client/allocrunner/taskrunner/template_hook.go [hunk 1]
```diff
@@ -116,11 +116,14 @@ func (h *templateHook) Prestart(ctx context.Context, req *interfaces.TaskPrestar
 }
 
 func (h *templateHook) Poststart(ctx context.Context, req *interfaces.TaskPoststartRequest, resp *interfaces.TaskPoststartResponse) error {
-	if req.DriverExec != nil {
+	h.managerLock.Lock()
+	defer h.managerLock.Unlock()
+
+	if req.DriverExec != nil && h.templateManager != nil {
```
Comment (lgfa29) [inline client/allocrunner/taskrunner/template_hook.go:122]: It seems like the root cause was the missing lock acquisition?

`Update` hooks [run concurrently with others](https://github.com/hashicorp/nomad/blob/v1.4.2/client/allocrunner/taskrunner/task_runner.go#L540-L543) and so if an update happens while the `Poststart` hook is running the `SetDriverHandle` call may happen between [these two lines](https://github.com/hashicorp/nomad/blob/v1.4.2/client/allocrunner/taskrunner/template_hook.go#L189-L192), causing `h.templateManager` to be `nil`.

Apart from this I'm not sure how else `templateManager` could be `nil`, should we just no-op like [in `Update`](https://github.com/hashicorp/nomad/blob/v1.4.2/client/allocrunner/taskrunner/template_hook.go#L174-L177)?

**Review by lgfa29 — APPROVED** [review]
A few comments, but nothing major. I also think this needs to be backported to 1.3.x since that's when we introduced `change_mode = "script"`.

File: client/allocrunner/taskrunner/template_hook.go [hunk 2]
```diff
@@ -166,33 +169,40 @@ func (h *templateHook) Stop(ctx context.Context, req *interfaces.TaskStopRequest
...
 	h.managerLock.Lock()
 	defer h.managerLock.Unlock()
 
-	// Nothing to do
+	// just quit if we are being killed anyway
+	select {
+	case <-ctx.Done():
+		return nil
+	default:
+	}
```
[the remark this answers is not in the document]
Comment (shoenig) [reply client/allocrunner/taskrunner/template_hook.go:182]: Hmm yeah, actually this is unrelated to the bug fix at hand so I'll just eliminate it

File: client/allocrunner/taskrunner/template_hook.go (hunk 1 above)
Comment (shoenig) [reply client/allocrunner/taskrunner/template_hook.go:122]: > should we just no-op like [in Update]

I think so, yeah - as in lets check & exit on nil before entering this if/else.
