### PR TITLE
vault: protect against empty Vault secret response

### LINKED ISSUE #4921: SIGSEGV when seems vault have stale state
### Nomad version
0.8.6

### Issue
We found this in our server logs

```
Nov 24 19:56:06 vol-cl-control-01 nomad.sh[2388]:     2018/11/24 19:56:06.640571 [ERR] http: Request /v1/acl/token/b5ff0f93-0ae9-0f77-b706-af148b36bc3e, error: rpc error: Cannot delete nonexistent tokens: b5ff0f93-0ae9-0f77-b706-af148b36
Nov 24 19:56:08 vol-cl-control-01 nomad.sh[2388]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 24 19:56:08 vol-cl-control-01 nomad.sh[2388]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xfb1d1b]
Nov 24 19:56:08 vol-cl-control-01 nomad.sh[2388]: goroutine 45 [running]:
Nov 24 19:56:08 vol-cl-control-01 nomad.sh[2388]: github.com/hashicorp/nomad/nomad.(*vaultClient).parseSelfToken(0xc42023af70, 0x1, 0x0)
Nov 24 19:56:08 vol-cl-control-01 nomad.sh[2388]:         /opt/gopath/src/github.com/hashicorp/nomad/nomad/vault.go:603 +0x9b
Nov 24 19:56:08 vol-cl-control-01 nomad.sh[2388]: github.com/hashicorp/nomad/nomad.(*vaultClient).establishConnection(0xc42023af70)
Nov 24 19:56:08 vol-cl-control-01 nomad.sh[2388]:         /opt/gopath/src/github.com/hashicorp/nomad/nomad/vault.go:428 +0x164
Nov 24 19:56:08 vol-cl-control-01 nomad.sh[2388]: github.com/hashicorp/nomad/nomad.(*vaultClient).(github.com/hashicorp/nomad/nomad.establishConnection)-fm()
Nov 24 19:56:08 vol-cl-control-01 nomad.sh[2388]:         /opt/gopath/src/github.com/hashicorp/nomad/nomad/vault.go:247 +0x2a
Nov 24 19:56:08 vol-cl-control-01 nomad.sh[2388]: github.com/hashicorp/nomad/nomad.wrapNilError.func1(0x0, 0x0)
Nov 24 19:56:08 vol-cl-control-01 nomad.sh[2388]:         /opt/gopath/src/github.com/hashicorp/nomad/nomad/vault.go:1186 +0x24
Nov 24 19:56:08 vol-cl-control-01 nomad.sh[2388]: github.com/hashicorp/nomad/vendor/gopkg.in/tomb%2ev2.(*Tomb).run(0xc420338f00, 0xc420374240)
Nov 24 19:56:08 vol-cl-control-01 nomad.sh[2388]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/gopkg.in/tomb.v2/tomb.go:153 +0x2b
Nov 24 19:56:08 vol-cl-control-01 nomad.sh[2388]: created by github.com/hashicorp/nomad/vendor/gopkg.in/tomb%2ev2.(*Tomb).Go
Nov 24 19:56:08 vol-cl-control-01 nomad.sh[2388]:         /opt/gopath/src/github.com/hashicorp/nomad/vendor/gopkg.in/tomb.v2/tomb.go:149 +0xb9
Nov 24 19:56:08 vol-cl-control-01 systemd[1]: nomad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

This happens after demaged vault in our enviroment, and when we restore it state(vault) from backup

### PR DESCRIPTION
**Pull request by notnoop**
Fixes #4921

Sadly, we don't have proper mechanism to mock Vault client, so not sure how to best test this.

I inspected the Vault client interactions, specially for cases where returned value is nil even if the error is also nil.  I believe we covered all correctly now:
* [`v.client.Sys().InitStatus()`](https://github.com/hashicorp/nomad/blob/f3853f11daa51336a2d46d883b1aff6feeddc7ec/nomad/vault.go#L427) - the value is non-nil boolean
* [`v.client.Sys().CapabilitiesSelf(path)`](https://github.com/hashicorp/nomad/blob/f3853f11daa51336a2d46d883b1aff6feeddc7ec/nomad/vault.go#L812): Capabilities handles empty bodies in [`hasCapability`](https://github.com/hashicorp/nomad/blob/f3853f11daa51336a2d46d883b1aff6feeddc7ec/vendor/github.com/hashicorp/vault/api/sys_capabilities.go#L43-L45) - also the `nil` array is handled with proper fail-safe default.
* [`v.client.Logical().Read(fmt.Sprintf("auth/token/roles/%s", role))`](https://github.com/hashicorp/nomad/blob/f3853f11daa51336a2d46d883b1aff6feeddc7ec/nomad/vault.go#L834-L840) handles when `rsecret` is nil

### CODE REVIEW

File: nomad/vault.go [hunk 1]
```diff
@@ -630,20 +630,11 @@ func (v *vaultClient) getWrappingFn() func(operation, path string) string {
...
-	// Get the initial lease duration
-	auth := v.client.Auth().Token()
-	var self *vapi.Secret
-
 	// Try looking up the token using the self endpoint
-	secret, err := auth.LookupSelf()
+	secret, err := self.lookupSelf()
 	if err != nil {
-		// Try looking up our token directly
-		self, err = auth.Lookup(v.client.Token())
```
Comment (notnoop) [inline nomad/vault.go]: The assignment to `self` here is ineffective - as if this try succeeds, `self` is stomped by assignment in L646, as @tantra35 identified.  Thanks!
