### PR TITLE
fix potential race condition in API client

### LINKED ISSUE #10301: Race condition in SDK client
### Nomad version
v1.0.4 (and much before)

### Issue
When headers are present on the Nomad client config, the header map from the config is assigned to the request header map in `newRequest`:
https://github.com/hashicorp/nomad/blob/v1.0.4/api/api.go#L680-L682
This means that downstream usage of this header map (esp. mutation) can result in concurrent access to the map from the client config. We ran into this problem in the Nomad terraform provider:
https://travis-ci.org/github/hashicorp/terraform-provider-nomad/builds/765624353

The assignment linked above needs to be a copy, in the spirit of the initialization in `doRequest`:
https://github.com/hashicorp/nomad/blob/v1.0.4/api/api.go#L657

### Reproduction steps
Documenting test in https://github.com/hashicorp/nomad/pull/10302

### PR DESCRIPTION
**Pull request by cgbaker**
Resolves #10301 

* Updates the `/api` tests to run with `-race`.
* Documenting test for #10301 
* Resolves race condition

Commit 4e25e8e2350579581b88bf96e67c18627008e65e shows a documenting test, which fails under `-race`:
https://app.circleci.com/pipelines/github/hashicorp/nomad/15527/workflows/d2032205-895a-4d7b-8ec6-41301a1614cb/jobs/147802

New test passes after 60648672518b642ea3b4dcab431ca521b3e6597b

### CODE REVIEW

File: api/api_test.go [hunk 1]
```diff
@@ -538,3 +539,36 @@ func TestCloneHttpClient(t *testing.T) {
...
+	client, err := NewClient(conf)
+	require.NoError(err)
+
+	wg := sync.WaitGroup{}
+	wg.Add(2)
+
+	go func() {
+		for i := 0; i < 2500; i++ {
+			req, err := client.newRequest("GET", "/any/path/will/do")
+			require.NoError(err)
```
Comment (notnoop) [inline api/api_test.go:559]: `requires` and `t.FailNow` aren't meant to be only invoked from the main test goroutine: https://golang.org/pkg/testing/#B.FailNow .

File: api/api_test.go [hunk 2]
```diff
@@ -538,3 +539,36 @@ func TestCloneHttpClient(t *testing.T) {
 	})
 
 }
+
+func TestClient_HeaderRaceCondition(t *testing.T) {
```
Comment (notnoop) [inline api/api_test.go:543]: I feel a bit odd about this test: `-race` can detect the condition deterministically I suspect without needing to  thousands of iterations. Also, it's probably sufficient to check that `conf.Headers` aren't mutated.

**Review by notnoop — COMMENTED** [review]
LGTM.  I suspect the significant violation here is that we are mutating the input header object, resulting into a  request contaminating subsequent requests even without concurrency. The concurrency race is a consequence of that.

File: api/api_test.go (hunk 2 above)
Comment (cgbaker) [reply api/api_test.go:543]: Yeah, I struggled to get `conf.Headers` to be mutated. I _think_ that's because the underlying map was being reallocated, but wasn't able to easily validate because of the effort that go expends to pretend that `map` isn't a pointer.

File: api/api_test.go (hunk 1 above)
Comment (cgbaker) [reply api/api_test.go:559]: Cool,  will update this.

File: api/api_test.go (hunk 2 above)
Comment (cgbaker) [reply api/api_test.go:543]: Will look into `-race` testing.

**Comment by cgbaker** [comment]
>I suspect the significant violation here is that we are mutating the input header object, resulting into a request contaminating subsequent requests even without concurrency. The concurrency race is a consequence of that.

Correct. It's not necessarily even us... the downstream code in `net/http` will do this as well, although this test was a short-cut to that which didn't require actually making an HTTP call.

File: CHANGELOG.md [hunk 3]
```diff
@@ -17,6 +17,7 @@ IMPROVEMENTS:
 
 BUG FIXES:
  * agent: Only allow querying Prometheus formatted metrics if Prometheus is enabled within the config [[GH-10140](https://github.com/hashicorp/nomad/pull/10140)]
+ * api: Fixed race condition around headers in API client [[GH-10302](https://github.com/hashicorp/nomad/issues/10302)]
```
Comment (notnoop) [inline CHANGELOG.md:20]: I feel a bit odd about the wording here. Race condition is too low level and doesn't clarify the scope/impact.  I'd probably suggest a more specific phrasing akin: "Fixed a panic that may occur if when multiple goroutines initiate requests using the same api client"?

**Review by notnoop — APPROVED** [review]
Couple of tweaks - but feel free to merge as you see fit.

File: .circleci/config.yml [hunk 4]
```diff
@@ -293,11 +293,15 @@ jobs:
       goarch:
         type: string
         default: "amd64"
+      enable_race_testing:
+        type: string
```
[the remark this answers is not in the document]
Comment (cgbaker) [reply .circleci/config.yml:297]: for the circleci bit, probably. however, downstream usage would require that it be converted to an empty string when `false`, because of the way that conditionals work in GNU make:
https://github.com/hashicorp/nomad/pull/10302/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R304

[the remark this answers is not in the document]
Comment (cgbaker) [reply .circleci/config.yml:297]: okay, i've changed my mind. will do that, at least for the purpose of documentation.

[the remark this answers is not in the document]
Comment (cgbaker) [reply .circleci/config.yml]: @notnoop , when you have a chance, i'd appreciate your feedback on this approach.

[the remark this answers is not in the document]
Comment (cgbaker) [reply .circleci/config.yml]: specifically, this: 
https://github.com/hashicorp/nomad/pull/10302/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R304

File: .circleci/config.yml [hunk 5]
```diff
@@ -293,11 +293,15 @@ jobs:
...
         default: "amd64"
+      enable_race_testing:
+        type: boolean
+        default: false
     environment:
       GOTEST_PKGS_EXCLUDE: "<< parameters.exclude_packages >>"
       GOTEST_PKGS: "<< parameters.test_packages >>"
       GOTEST_MOD: "<< parameters.test_module >>"
       GOTESTARCH: "<< parameters.goarch >>"
+      ENABLE_RACE: "<<# parameters.enable_race_testing >>TRUE<</ parameters.enable_race_testing >>"
```
Comment (notnoop) [inline .circleci/config.yml:304]: TIL about circleci conditionals!

**Review by notnoop — APPROVED** [review]

File: CHANGELOG.md [hunk 6]
```diff
@@ -17,6 +17,7 @@ IMPROVEMENTS:
 
 BUG FIXES:
  * agent: Only allow querying Prometheus formatted metrics if Prometheus is enabled within the config [[GH-10140](https://github.com/hashicorp/nomad/pull/10140)]
+ * api: Fixed a panic that may occur on concurrent access to an SDK client [[GH-10302](https://github.com/hashicorp/nomad/issues/10302)]
```
Comment (notnoop) [inline CHANGELOG.md:20]: 💯 This is even better than I was proposing about - thanks!
