### PR TITLE
better error handling around Scaling->Max

### LINKED ISSUE #8355: confusing defaults when enabling scaling stanza
### Nomad version
Output from `nomad version`
Nomad v0.12.0-beta2 (5b80d4e638f1a27eee3ca245f8babb115e4c098d)

### Operating system and Environment details
CentOS 7/8, Ubuntu 16.04/18.04

### Issue

For the scaling stanza, the `min`  value should use the default group count of `1`.
It overrides the default group count of `1` with the `min` value in the `scaling` stanza.

### Reproduction steps

starting with the default job file, perform the steps mentioned below ...

### Job file (if appropriate)

1. start with the default "short" example.nomad:

```hcl
job "example" {
  datacenters = ["dc1"]

  group "cache" {
    task "redis" {
      driver = "docker"

      config {
        image = "redis:3.2"

        port_map {
          db = 6379
        }
      }

      resources {
        cpu    = 500
        memory = 256

        network {
          mbits = 10
          port "db" {}
        }
      }
    }
  }
}
```

2. I want to enable `scaling` so I proceed to "just" add the scaling stanza (I would assume this should work)

```hcl
job "example" {
  datacenters = ["dc1"]

  group "cache" {
    scaling {
      enabled = true
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:3.2"

        port_map {
          db = 6379
        }
      }

      resources {
        cpu    = 500
        memory = 256

        network {
          mbits = 10
          port "db" {}
        }
      }
    }
  }
}
```

only **this** much doesn't work ... it complains about `min` not set with error and some spurious whitespaces and a bracket ...

```
$ nomad plan example.nomad
Error during plan: Unexpected response code: 500 (1 error occurred:
        * Task group cache validation failed: 1 error occurred:
        * Task group scaling policy validation failed: 2 errors occurred:
        * Scaling policy invalid: maximum count must not be less than minimum count
        * Scaling policy invalid: task group count must not be greater than maximum count in scaling policy





)
```

3. so now I set the `min` value to `0` ...

```hcl
job "example" {
  datacenters = ["dc1"]

  group "cache" {
    scaling {
      enabled = true
      min = 0
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:3.2"

        port_map {
          db = 6379
        }
      }

      resources {
        cpu    = 500
        memory = 256

        network {
          mbits = 10
          port "db" {}
        }
      }
    }
  }
}
```

```
$ nomad plan example.nomad
+/- Job: "example"
+/- Task Group: "cache" (1 ignore)
  +/- Count: "1" => "0" (forces destroy)
      Task: "redis"

Scheduler dry-run:
- All tasks successfully allocated.

Job Warnings:
1 warning(s):

* Group "cache" has warnings: 1 error occurred:
        * Update max parallel count is greater than task group count (1 > 0). A destructive change would result in the simultaneous replacement of all allocations.

```

BUG! (I think), The unspecified default group count of `1` was over-ridden by the `min` value.
Also, the error about `max` has gone away as it plans to kill off the running instance (!!)
Even if I add `min = 0` and `max = 10`, the error is the same.

### Expected behavior
Possible solutions could be:
* `min` should use the current default `count` of `1`
1. `max` should default to the job `count`, which is `1`.
2. generate the job file with the explicit default `count` of `1`  ???

### Nomad Client logs (if appropriate)
na

### Nomad Server logs (if appropriate)
na

### PR DESCRIPTION
**Pull request by cgbaker**
* made api.Scaling.Max a pointer, so we can detect (and complain) when it is neglected
* added checks to HCL parsing that it is present
* when Scaling.Max is absent/invalid, don't return extraneous error messages during validation
* tweak to multiregion handling to ensure that the count is valid on the interpolated regional jobs

we don't do validation on the `api` objects, just on the structs objects on the other side of the RPC call. therefore, as a hack that i'm not entirely happy with, when `api.ScalingPolicy.Max` is missing, i set an invalid value for `structs.ScalingPolicy.Max` (I don't want this to be a pointer), and then respond during validation with a catch-all error message.

also updated website to document `Group->Count` default value

@tgross , does https://github.com/hashicorp/nomad/pull/8360/files#diff-396d9428285e4245041a3d0b15546d5dR5963 look okay? i did a local multiregion test and everything behaved.

resolves #8355

### CODE REVIEW

File: jobspec/parse_test.go [hunk 1]
```diff
@@ -1345,7 +1345,7 @@ func TestParse(t *testing.T) {
 						Name: helper.StringToPtr("group"),
 						Scaling: &api.ScalingPolicy{
 							Min:     nil,
-							Max:     0,
+							Max:     helper.Int64ToPtr(10),
```
Comment (shoenig) [inline jobspec/parse_test.go:1348]: Intentionally changed from 0 to 10?

File: website/pages/docs/job-specification/group.mdx [hunk 2]
```diff
@@ -36,8 +36,10 @@ job "docs" {
   node attribute or metadata. See the
   [Nomad spread reference](/docs/job-specification/spread) for more details.
 
-- `count` `(int: 1)` - Specifies the number of the task groups that should
-  be running under this group. This value must be non-negative.
+- `count` `(int)` - Specifies the number of instances that should be running
+  under for this group. This value must be non-negative. This defaults to the
+  `min` value specified in the [`scaling`](/docs/job-specification/scaling)
+  block, if present; otherwise, this defaults to `1`.
```
Comment (shoenig) [inline website/pages/docs/job-specification/group.mdx:42]: Should `max` be documented?

Comment (cgbaker) [reply website/pages/docs/job-specification/group.mdx:42]: lol. yes. thanks 😄

Comment (cgbaker) [reply website/pages/docs/job-specification/group.mdx:42]: uh, actually, i'll leave it alone. i was just trying to update the default here, not the mechanics of `count`

**Comment by tgross** [comment]
> @tgross , does https://github.com/hashicorp/nomad/pull/8360/files#diff-396d9428285e4245041a3d0b15546d5dR5963 look okay? i did a local multiregion test and everything behaved.

LGTM
