### PR TITLE
Fix for Java fingerprinter on macOS

### LINKED ISSUE #7865: [enhancement] Update Java driver fingerprinting for macOS
On versions of macOS without Java installed, there is a stub executable that presents a warning to users that there is no longer a default JDK installed on macOS. 
Screen Shot 2020-05-04 at 5 09 14 PM

 The fingerprinter runs this stub command every 30 seconds while Nomad is running because of 
https://github.com/hashicorp/nomad/blob/65f09ed11941f78db20a8ec4bbd1381dad4f83a7/drivers/java/driver.go#L29-L30
https://github.com/hashicorp/nomad/blob/65f09ed11941f78db20a8ec4bbd1381dad4f83a7/drivers/java/utils.go#L11-L27

It appears that we could fingerprint for an installed JDK (that would be seen by this stub) by looking for one or more symlinks in `/Library/Java/JavaVirtualMachines`.  This would definitely improve the getting started experience on macOS.

### PR DESCRIPTION
**Pull request by angrycub**
Fixes #7865

Found that `/usr/libexec/java_home` will provide information about whether or not a JVM is installed and not stimulate the "Install a JVM" popup window that running the shim commands do.

### CODE REVIEW

File: drivers/java/driver.go [hunk 1]
```diff
@@ -223,6 +223,16 @@ func (d *Driver) buildFingerprint() *drivers.Fingerprint {
...
 	}
+	if runtime.GOOS == "darwin" {
+		_, err := checkForMacJVM()
+		// return no error, as it isn't an error to not find java, it just means we
+		// can't use it.
+
+		fp.Health = drivers.HealthStateUndetected
+		fp.HealthDescription = ""
+		d.logger.Trace("macOS jvm not found", "error", err)
+		return fp
```
Comment (cgbaker) [inline drivers/java/driver.go:234]: shouldn't this be in a conditional?

File: drivers/java/utils.go [hunk 2]
```diff
@@ -9,10 +9,29 @@ import (
...
+	return true, nil
+}
 
+func javaVersionInfo() (version, runtime, vm string, err error) {
+	var out bytes.Buffer
+	_, err = checkForMacJVM()
+	if err != nil {
+		err = fmt.Errorf("failed to check java version: %v", err)
+		return
+	}
```
Comment (schmichael) [inline drivers/java/utils.go:34]: Only run this code for Darwin.

File: drivers/java/driver.go (hunk 1 above)
Comment (angrycub) [reply drivers/java/driver.go]: Indeed. Manual testing is manual. :(

**Comment by angrycub** [comment]
Smoke testing allowed me to remove and install a JVM under a running Nomad without getting a popup at any point. Health updated as you would expect.

**Review by cgbaker — APPROVED** [review]
:thum
