### PR TITLE
services: un-mark group services as deregistered if restart hook runs

### LINKED ISSUE #16616: Services not unregistered
Just upgraded to Nomad 1.5.2. Since then, services are not always unregistered from Consul service catalog when they are shuted down / upgraded. So old services versions appear as failed, eg

image

Environment : 
- Nomad 1.5.2 (with ACL), using the prebuilt binary
- Consul 1.15.1 (with ACL), using the pre-built binary
- Alma Linux 8

Haven't found yet a pattern to reproduce it 100% of the time

### PR DESCRIPTION
**Pull request by shoenig**
This PR may fix a bug where group services will never be deregistered if the group undergoes an alloc restart.

Fixes #16616

Adds an e2e test case covering the repro in ^

### CODE REVIEW

File: e2e/consul/alloc_restart_test.go [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+	// make sure our service is still registered
+	services, _, err = cc.Service("alloc-restart-http", "", nil)
+	must.NoError(t, err)
+	must.Len(t, 1, services)
+
+	err = e2eutil.StopJob(jobID)
+	must.NoError(t, err)
+
+	// make sure our service is no longer registered
+	services, _, err = cc.Service("alloc-restart-http", "", nil)
```
Comment (tgross) [inline e2e/consul/alloc_restart_test.go:56]: I'm pretty sure by the time the alloc is marked running the service will be registered. But service deregistration isn't synchronous with the `Job.Deregister` RPC, right? I think we need to `must.Wait` for this API call.

**Review by tgross — APPROVED** [review]
LGTM

File: e2e/consul/alloc_restart_test.go (hunk 1 above)
Comment (shoenig) [reply e2e/consul/alloc_restart_test.go:56]: Good catch, will add that
