### PR TITLE
reconciler: Handle canaries when client disconnects

### LINKED ISSUE #12503: canaries: Allocation count rises indefinitely if client disconnects while canary in progress
### Nomad version

1.3.0 beta.1

### Operating system and Environment details

Nomad Vagrantfile Cluster
1 Server
2 Clients

### Issue

Nomad creates more and more allocations if a client disconnects while a job configured with `max_client_disconnect` is in the middle of canarying.

### Reproduction steps

- Run a job configured with `max_client_disconnect`, a spread that forces deployment across multiple nodes, and canary updates
- Wait for the initial deployment to finish
- Run a second version of the job that causes an update
- Wait for the deployment status to indicate 2 or more allocations have been placed but not all 
- Simulate a disconnect on one of the clients (e.g. sudo iptables -I INPUT -s 192.168.56.11 -j DROP)
- Watch the allocation count continue to rise indefinitely
- The deployment just keeps showing more and more allocations

#### Expected Result

- The allocations on the disconnected client should be marked stop/unknown
- The deployment should finish correctly and place the desired number of allocations on the connected node
- When the disconnected node reconnects the allocations that were places during before the disconnect should gracefully shutdown
- `docker ps` on the reconnected client shows no zombie processes

#### Actual Result

- The deployment continues indefinitely and schedules more and more allocations

### Job file (if appropriate)

*Version 1*

```hcl
job "canary" {
  datacenters = ["dc1"]

  group "cache" {
    count = 6

    update {
      max_parallel     = 1
      canary           = 1
      min_healthy_time = "3s"
      healthy_deadline = "20s"
      auto_revert      = true
      auto_promote     = true
    }


    max_client_disconnect = "5m"

    spread {
      attribute = "${node.datacenter}"

      target "nomad-client01" {
        percent = 50
      }

      target "nomad-client02" {
        percent = 50
      }
    }

    network {
      port "db" {
        to = 6379
      }
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:3.2"

        ports = ["db"]
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

*Version 2*

```hcl
job "canary" {
  datacenters = ["dc1"]

  group "cache" {
    count = 6

    update {
      max_parallel     = 1
      canary           = 1
      min_healthy_time = "3s"
      healthy_deadline = "20s"
      auto_revert      = true
      auto_promote     = true
    }


    max_client_disconnect = "5m"

    spread {
      attribute = "${node.datacenter}"

      target "nomad-client01" {
        percent = 50
      }

      target "nomad-client02" {
        percent = 50
      }
    }

    network {
      port "db" {
        to = 6379
      }
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:5.0"

        ports = ["db"]
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

### Nomad Server logs (if appropriate)

Varies based on the number of allocations that were placed before the disconnect. When it failed some version his log entry repeats over and over. 

```shell
Apr 07 18:30:41 nomad-server01 nomad[29687]:   | Total changes: (place 2) (destructive 0) (inplace 0) (stop 2) (disconnect 2) (reconnect 0)
Apr 07 18:30:41 nomad-server01 nomad[29687]:   | Desired Changes for "cache": (place 2) (inplace 0) (destructive 0) (stop 2) (migrate 0) (ignore 6) (canary 0)
```

### PR DESCRIPTION
**Pull request by DerekStrickland**
Closes #12503 

This PR contains the changes necessary to support the Disconnected Clients feature when a client disconnects and is part of an in-process canary deployment. It also fixes some bugs that surfaced during the implementation. 

- [bc0a951](https://github.com/hashicorp/nomad/pull/12539/commits/bc0a951294b33f12b5f0cd4f395b0c94bb7e3ff5): Previously, a plan that contained disconnect updates was considered invalid if it contained anything other than `unknown` alloc updates. In the case of canaries, this won't work. A `disconnect` reconciler pass that contains canaries may detect both the disconnect updates as well as `stop` and `place` results for the allocs currently running on the disconnected node. This constraint has been removed.
- [3f4ba23](https://github.com/hashicorp/nomad/pull/12539/commits/3f4ba2380d0571f1e7ba6313bb3124f22e4fa416): When appending `unknown` allocs to the plan, we were stripping the `Job` as an optimization. This can trigger a timing-based panic in `StateStore.AllocsByJob` if the job is `nil` which was uncovered by running `watch nomad status [jobname]`.
- [822e63e](https://github.com/hashicorp/nomad/pull/12539/commits/822e63e2134c04b827d33a6d3ef23abf36afa142): The helper method that stops allocs when a job is purged was updated to also stop `unknown` allocs.
- [1a6263f](https://github.com/hashicorp/nomad/pull/12539/commits/1a6263f676f335dd11d3f478a71da0cd504e362b):    
  - The filter function for tainted nodes was updated to handle disconnected clients earlier in the sequence.
  - The reschedule filter function was updated to ignore allocs that have already been marked `unknown`.
  - A new helper filter was added to filter allocs by client status. This function is currently used when stopping all allocs for a job.
- [2b726fc](https://github.com/hashicorp/nomad/pull/12539/commits/2b726fc042a71d1f54592a0890182cdacccc4217): A bug was found and fixed in the `heartbeat`/`node_endpoint` logic that could result in evaluations not getting created when the `heartbeat` timer ticked for a node that was already `disconnected`.  
- [dd9d2d2](https://github.com/hashicorp/nomad/pull/12539/commits/dd9d2d22b397e928febcf3c1ff1e2fcb6c7d5792): Adds back guard clause that was lost during the rebase.

### CODE REVIEW

File: nomad/plan_apply.go [hunk 1]
```diff
@@ -705,7 +705,7 @@ func evaluateNodePlan(snap *state.StateSnapshot, plan *structs.Plan, nodeID stri
 // The plan is only valid for disconnected nodes if it only contains
 // updates to mark allocations as unknown.
 func isValidForDisconnectedNode(plan *structs.Plan, nodeID string) bool {
-	if len(plan.NodeUpdate[nodeID]) != 0 || len(plan.NodePreemptions[nodeID]) != 0 {
+	if len(plan.NodePreemptions[nodeID]) != 0 {
```
Comment (DerekStrickland) [inline nomad/plan_apply.go:708]: @tgross  Reading the comments for this NodePreemptions field, it seems like we should remove this check too.  Do you agree?

Comment (tgross) [reply nomad/plan_apply.go:708]: Interestingly, that field is deprecated... if we're looking at it at all shouldn't we be looking at `AllocsPreempted` instead? But yeah, I agree it's fine to remove.

File: scheduler/reconcile.go [hunk 2]
```diff
@@ -620,7 +620,9 @@ func (a *allocReconciler) cancelUnneededCanaries(original allocSet, desiredChang
 		canaries = all.fromKeys(canaryIDs)
 		untainted, migrate, lost, _, _, _ := canaries.filterByTainted(a.taintedNodes, a.supportsDisconnectedClients, a.now)
 		a.markStop(migrate, "", allocMigrating)
+		desiredChanges.Stop += uint64(len(migrate))
```
Comment (DerekStrickland) [inline scheduler/reconcile.go:623]: @tgross While adding my tests, I didn't see the stop count I expected on desired changes so I added these 2 lines, but of course, other tests now fail. Before I refactor those, let me ask. Were we not adding these stops to desiredChanges on purpose? It seemed like an oversight to me because a few lines above other stops by this function do add to the stop count.

Comment (tgross) [reply scheduler/reconcile.go:623]: That's odd. I'm not sure why we'd mark migrating allocs for stop at all. They're left running until we can complete the [`migration`](https://www.nomadproject.io/docs/job-specification/migrate) and _then_ stopped. I would definitely make sure you have tested your understanding of what it's doing currently (and in 1.2.6, tbh... this code has been completely reworked for 1.3 after all) before making further changes here.

Comment (DerekStrickland) [reply scheduler/reconcile.go:623]: I did a little digging and this part of this function does look like it has changed since 7/7/17. My understanding of what's happening here is this:

- This function is dealing specifically with canaries that have been placed but not yet finished being verified as healthy.
- Research indicates that once a canary gets marked healthy it won't be in the `PlacedCanaries` but instead will be counted in the `PlacedAllocs` count field.
- I think the intent of this code is similar to how we treat pending allocs when a node disconnects, which is, if it isn't verified running, mark it for stop.
- As far back as 7/5/17, this function is not adding these stop counts to `desiredChanges.Stop`. 
- The earlier version of this function before 7/5/2017 had a slightly better comment - "Handle canaries on migrating/lost nodes here by just stopping them" - so it seems intentional.
- I can see a justification for both incrementing and not incrementing the counter. 
  - On the one hand, a stop is going to get added to the reconciliation result, and work is going to be performed.
  - On the other hand, this is an uncommitted, in-progress long-running transaction. 
  - If you mentally model it as an uncommitted transaction, this is a rollback/abort, which philosophically isn't changing cluster state, because the state was never committed. But in practical terms is work that has to be performed. 
- I guess I'm in favor of keeping existing behavior, reverting these changes, and updating my tests to account for this along with some comments explaining the why.

Thoughts?

Comment (DerekStrickland) [reply scheduler/reconcile.go:623]: One last realization.  The lines of the function right above this actually report stops for in-process canaries in the case of a failed deployment or one that is from an older deployment.  I guess we could ask Alex what his intention was but I doubt he'd remember 😄

File: scheduler/reconcile_util.go [hunk 3]
```diff
@@ -557,6 +562,18 @@ func (a allocSet) delayByMaxClientDisconnect(now time.Time) (later []*delayedRes
 	return
 }
 
+// filterByClientStatus returns allocs from the set with the specified client status.
```
Comment (tgross) [inline scheduler/reconcile_util.go:565]: No big deal but something to look out for in the future when you're cutting up a PR: `filterByClientStatus` got added in 1a6263f676f335dd11d3f478a71da0cd504e362b but is called in 822e63e2134c04b827d33a6d3ef23abf36afa142 which came before it. We'll squash this PR anyways so it doesn't _really_ matter but it makes reviewing commit-by-commit a little trickier for a large PR like this.

File: nomad/heartbeat.go [hunk 4]
```diff
@@ -181,8 +180,8 @@ func (h *nodeHeartbeater) disconnectState(id string) (bool, bool) {
 		return false, false
 	}
 
-	// Exit if this is the node already in a state other than ready.
-	if node.Status != structs.NodeStatusReady {
+	// Exit if the node is already down.
+	if node.Status == structs.NodeStatusDown {
 		return false, false
 	}
```
Comment (tgross) [inline nomad/heartbeat.go:186]: Mini optimization opportunity here. There are (now) 4 node states, and the original intent here included `NodeStatusInitializing`. Can we still return early from that so we don't have to do a state store lookup?

File: scheduler/reconcile_test.go [hunk 5]
```diff
@@ -5631,3 +5632,366 @@ func TestReconciler_Disconnected_Client(t *testing.T) {
...
+				desiredTGUpdates: map[string]*structs.DesiredUpdates{
+					updatedJob.TaskGroups[0].Name: {
+						Place:  2,
+						Canary: 0,
+						Ignore: 3,
+						// The 2 stops in this test are transient failures, but
+						// the deployment can still progress. We don't include
+						// them in the stop count since DesiredTGUpdates is used
+						// to report deployment progress or final deployment state.
+						Stop: 0,
```
Comment (tgross) [inline scheduler/reconcile_test.go:5866]: Solid comment! 👍

**Review by tgross — APPROVED** [review]
LGTM!

File: scheduler/reconcile_util.go (hunk 3 above)
Comment (DerekStrickland) [reply scheduler/reconcile_util.go:565]: Ahh thanks.  Totally makes sense.

File: nomad/heartbeat.go (hunk 4 above)
Comment (DerekStrickland) [reply nomad/heartbeat.go:186]: Yes!

File: nomad/heartbeat.go [hunk 6]
```diff
@@ -181,8 +180,8 @@ func (h *nodeHeartbeater) disconnectState(id string) (bool, bool) {
...
 
-	// Exit if this is the node already in a state other than ready.
-	if node.Status != structs.NodeStatusReady {
+	// Exit if the node is already down.
+	if node.Status == structs.NodeStatusDown {
```
Comment (DerekStrickland) [inline nomad/heartbeat.go:184]:
```suggestion
	if node.Status == structs.NodeStatusDown || node.Status == structs.NodeStatusInit {
```
