### PR TITLE
Fix upgrade path for created resources

### LINKED ISSUE #2295: Segfault on upgrade from 0.5.1 to 0.5.4
### Nomad version
Nomad v0.5.4

### Issue
Upgrading Nomad from 0.5.1. to 0.5.4 causes a segfault:

    Feb 09 12:14:03 backend-generic-xxx nomad[9570]: panic: runtime error: invalid memory address or nil pointer dereference
    Feb 09 12:14:03 backend-generic-xxx nomad[9570]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5ebe54]
    Feb 09 12:14:03 backend-generic-xxx nomad[9570]: goroutine 121 [running]:
    Feb 09 12:14:03 backend-generic-xxx nomad[9570]: panic(0x1000940, 0xc420010090)
    Feb 09 12:14:03 backend-generic-xxx nomad[9570]: /opt/go/src/runtime/panic.go:500 +0x1a1
    Feb 09 12:14:03 backend-generic-xxx nomad[9570]: github.com/hashicorp/nomad/client/driver.(*CreatedResources).Merge(0x0, 0xc4200661d0)
    Feb 09 12:14:03 backend-generic-xxx nomad[9570]: /opt/gopath/src/github.com/hashicorp/nomad/client/driver/driver.go:131 +0xe4
    Feb 09 12:14:03 backend-generic-xxx nomad[9570]: github.com/hashicorp/nomad/client.(*TaskRunner).startTask(0xc42025c000, 0xc4204274a0, 0x0)
    Feb 09 12:14:03 backend-generic-xxx nomad[9570]: /opt/gopath/src/github.com/hashicorp/nomad/client/task_runner.go:1169 +0x2e3
    Feb 09 12:14:03 backend-generic-xxx nomad[9570]: github.com/hashicorp/nomad/client.(*TaskRunner).run(0xc42025c000)
    Feb 09 12:14:03 backend-generic-xxx nomad[9570]: /opt/gopath/src/github.com/hashicorp/nomad/client/task_runner.go:902 +0x38a
    Feb 09 12:14:03 backend-generic-xxx nomad[9570]: github.com/hashicorp/nomad/client.(*TaskRunner).Run(0xc42025c000)
    Feb 09 12:14:03 backend-generic-xxx nomad[9570]: /opt/gopath/src/github.com/hashicorp/nomad/client/task_runner.go:444 +0x6a1
    Feb 09 12:14:03 backend-generic-xxx nomad[9570]: created by github.com/hashicorp/nomad/client.(*AllocRunner).RestoreState
    Feb 09 12:14:03 backend-generic-xxx nomad[9570]: /opt/gopath/src/github.com/hashicorp/nomad/client/alloc_runner.go:190 +0x891

### PR DESCRIPTION
**Pull request by schmichael**
Fixes #2295

### CODE REVIEW

File: client/task_runner.go [hunk 1]
```diff
@@ -247,9 +247,13 @@ func (r *TaskRunner) RestoreState() error {
 	}
 	r.artifactsDownloaded = snap.ArtifactDownloaded
 	r.taskDirBuilt = snap.TaskDirBuilt
-	r.createdResources = snap.CreatedResources
 	r.payloadRendered = snap.PayloadRendered
 
+	// Pre-0.5.3 state snapshots won't have created resources
+	if snap.CreatedResources != nil {
```
Comment (dadgar) [inline client/task_runner.go]: As mentioned offline, may be worth going to a getter

File: client/task_runner.go [hunk 2]
```diff
@@ -1474,6 +1463,30 @@ func (r *TaskRunner) Destroy(event *structs.TaskEvent) {
...
+	r.createdResourcesLock.Unlock()
+
+	return cr
+}
+
+// setCreatedResources updates the resources created by drivers. If passed nil
+// it will set createdResources to an initialized struct.
+func (r *TaskRunner) setCreatedResources(cr *driver.CreatedResources) {
+	if cr == nil {
+		cr = driver.NewCreatedResources()
```
Comment (dadgar) [inline client/task_runner.go]: This should just be a return?

Comment (schmichael) [inline client/task_runner.go]: Well since this is for safety I figured might as well always set it.

I could have avoided the Copy call on this path too, but it shouldn't cost much or be called often.

Honestly I've botched the seemingly trivial code around this field so many times now that I just wanted these methods to be as succinct and robust as possible.
