### PR TITLE
UI: fix variable formatting for jobs submitted with non-string var flags

### LINKED ISSUE #23462: /v1/job/<job_id>/submission VariableFlags supports only strings
### Nomad version
```
Nomad v1.7.7
BuildDate 2024-04-16T19:26:43Z
Revision 0f34c85ee63f6472bd2db1e2487611f4b176c70
```

### Issue

The Nomad API endpoint to retrieve a job submission assumes all HCL2 variables submitted with a job to be of type string: https://github.com/hashicorp/nomad/blob/release/1.7.7/api/jobs.go#L929

This causes problems in the UI when editing the Job Spec of a submitted job whose variables are of types other than string. A list is rendered in the UI as: 
```
datacenters="["dc-1a","dc-1b","dc-1c"]"
```
And it will cause the following error when attempting to plan the edited job from the UI:
Screenshot 2024-06-28 at 08 30 46

### Reproduction steps

Submit a job with a -var file containing a variable of type list(string).

#### Expected Result

The variable is returned by the API with the correct type.

#### Actual Result

The variable is casted to string.

### PR DESCRIPTION
**Pull request by navyadas-dev**
### Description
This pr fixes variable formatting in UI for jobs submitted with list/map types via -var flags

Fix added : 

- Added logic to detect string values that are already JSON arrays or objects(by checking if they start with [ or { and end with ] or }). 

- These values are now preserved as it is without additional stringification, while regular string values still get properly quoted.This ensures that variable values maintain correct HCL syntax.

### Testing & Reproduction steps

**Reproduction  steps:**
 Submit a job with a -var  containing a variable of type list(string). Open the UI, edit the HCL Variable Values and click on plan. Below error is dispalyed.
Screenshot 2026-03-16 at 9 03 00 PM

**Testing**
Scenario 1
- Submit a job with a **-var** containing a variable of type list(string). Open the UI, edit the HCL Variable Values and click on plan.

https://github.com/user-attachments/assets/bc910191-eba9-45e6-aa80-81b8820dfcd9

Scenario 2
- Submit a job with a **-var-file**  containing a variable of type list(string). Open the UI, edit the HCL Variable Values and click on plan.

https://github.com/user-attachments/assets/002c8ea0-7e93-4465-af8a-9f643ada3225

Scenario 3 
Edit other type(number, boolean) fields and validate it if it works correctly

https://github.com/user-attachments/assets/dbc232ef-263a-4a18-b6ac-5b702d3cbba5

The UI displays variables as strings (e.g., instance_count="3"), and HCL type system handles the conversion based on the variable's declared type(Number). 
If the value ( instance_count="3a") cannot be converted to the declared type, Nomad returns a error message during plan. I hope this is the expected behavior—just wanted to confirm.

### Links

Fixes: #23462
Ref: https://hashicorp.atlassian.net/browse/NMD-531

### Contributor Checklist
- [ ] **Changelog Entry** If this PR changes user-facing behavior, please generate and add a
  changelog entry using the `make cl` command.
- [ ] **Testing** Please add tests to cover any new functionality or to demonstrate bug fixes and
  ensure regressions will be caught.
- [ ] **Documentation** If the change impacts user-facing functionality such as the CLI, API, UI,
  and job configuration, please update the Nomad product documentation, which is stored in the
  [`web-unified-docs` repo](https://github.com/hashicorp/web-unified-docs/). Refer to the [`web-unified-docs` contributor guide](https://github.com/hashicorp/web-unified-docs/blob/main/CONTRIBUTING.md) for docs guidelines.
  Please also consider whether the change requires notes within the [upgrade
  guide](https://developer.hashicorp.com/nomad/docs/upgrade/upgrade-specific). If you would like help with the docs, tag the `nomad-docs` team in this PR.

### Reviewer Checklist
- [ ] **Backport Labels** Please add the correct backport labels as described by the internal
  backporting document.
- [ ] **Commit Type** Ensure the correct merge method is selected which should be "squash and merge"
  in the majority of situations. The main exceptions are long-lived feature branches or merges where
  history should be preserved.
- [ ] **Enterprise PRs** If this is an enterprise only PR, please add any required changelog entry
  within the public repository.

- [ ] If a change needs to be reverted, we will roll out an update to the code within 7 days.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### CODE REVIEW

**Comment by tgross** [comment]
@navyadas-dev I've edited your PR description: I've fixed the title into something that's intended to communicate to human beings, and added links to the appropriate issues in the links section.

File: ui/app/utils/json-to-hcl.js [hunk 1]
```diff
@@ -16,7 +16,22 @@ export default function jsonToHcl(obj) {
 
   for (const key in obj) {
     const value = obj[key];
-    const hclValue = typeof value === 'string' ? JSON.stringify(value) : value;
+    let hclValue;
+
+    if (typeof value === 'string') {
+      // Check if it's a JSON array or object (starts with [ or {)
+      if (
+        (value.startsWith('[') && value.endsWith(']')) ||
```
Comment (mismithhisler) [inline ui/app/utils/json-to-hcl.js]: Out of curiosity, why not try/catch `JSON.parse(value)` here?

**Comment by tgross** [comment]
None of the videos playback for me. But what should be noted here is that the behavior is different for `-var-file` and `-var`. As far as I can tell, using `-var-file` works fine but using `-var` does not. 

<details><summary>example.nomad.hcl</summary>

```hcl
variable "datacenters" {
  type    = list(string)
  default = ["dc1"]
}

job "example" {

  datacenters = var.datacenters

  group "group" {

    task "task" {

      driver = "docker"
      user   = "www-data"

      config {
        image   = "busybox:1"
        command = "httpd"
        args    = ["-vv", "-f", "-p", "8001", "-h", "/local"]
      }

      resources {
        cpu    = 100
        memory = 100
      }

    }
  }
}
```

</details>

```
$ nomad job run -var='datacenters=["dc1", "dc2"]' ./example.nomad.hcl
...
$ nomad job inspect example | jq '.Job.Datacenters'
[
  "dc1",
  "dc2"
]

$ nomad operator api "/v1/job/example/submission?version=0"  | jq .
{
  "Format": "hcl2",
  "JobID": "example",
  "JobModifyIndex": 68,
  "Namespace": "default",
  "Source": "variable \"datacenters\" {\n  type    = list(string)\n  default = [\"dc1\"]\n}\n\njob \"example\" {\n\n  datacenters = var.datacenters\n\n  group \"group\" {\n\n    task \"task\" {\n\n      driver = \"docker\"\n      user   = \"www-data\"\n\n      config {\n        image   = \"busybox:1\"\n        command = \"httpd\"\n        args    = [\"-vv\", \"-f\", \"-p\", \"8001\", \"-h\", \"/local\"]\n      }\n\n      resources {\n        cpu    = 100\n        memory = 100\n      }\n\n    }\n  }\n}\n",
  "VariableFlags": {
    "datacenters": "[\"dc1\", \"dc2\"]"
  },
  "Variables": "",
  "Version": 0
}
```

Broken, as reported:
var-flag-broken

With the fix in this PR, it now works as expected:
var-flag-fixed

vs

```
$ nomad job run -var-file ./vars.hcl ./example.nomad.hcl
...
$ nomad operator api "/v1/job/example/submission?version=1"  | jq .
{
  "Format": "hcl2",
  "JobID": "example",
  "JobModifyIndex": 84,
  "Namespace": "default",
  "Source": "variable \"datacenters\" {\n  type    = list(string)\n  default = [\"dc1\"]\n}\n\njob \"example\" {\n\n  datacenters = var.datacenters\n\n  group \"group\" {\n\n    task \"task\" {\n\n      driver = \"docker\"\n      user   = \"www-data\"\n\n      config {\n        image   = \"busybox:1\"\n        command = \"httpd\"\n        args    = [\"-vv\", \"-f\", \"-p\", \"8001\", \"-h\", \"/local\"]\n      }\n\n      resources {\n        cpu    = 100\n        memory = 100\n      }\n\n    }\n  }\n}\n",
  "VariableFlags": null,
  "Variables": "datacenters=[\"dc1\", \"dc2\"]\n\n",
  "Version": 1
}
```

Works without changes:
var-file-works

**Review by tgross — COMMENTED** [review]
Looks like it fixes the bug as reported. I'd like to see a test for this change, preferably one that exercises what happens in this scenario where the HCL type _is_ a string:

```
variable "example" {
  type    = string
  default = "[\"dc1\"]"
}
```

**Comment by mismithhisler** [comment]
> Looks like it fixes the bug as reported

@tgross this fixes this bug, but introduces the exact same bug when variables begin/end with []/{} but are not valid JSON.

This should really be using `JSON.parse`

**Comment by navyadas-dev** [comment]
> > Looks like it fixes the bug as reported
> 
> @tgross this fixes this bug, but introduces the exact same bug when variables begin/end with []/{} but are not valid JSON.
> 
> This should really be using `JSON.parse`

@mismithhisler Yes , You are right!  I have added JSON.parse() validation and try/catch to handle SyntaxError exceptions from invalid JSON .

File: ui/app/utils/json-to-hcl.js (hunk 1 above)
Comment (navyadas-dev) [reply ui/app/utils/json-to-hcl.js]: I have updated the changes with  try/catch JSON.parse(value)

**Comment by navyadas-dev** [comment]
> Looks like it fixes the bug as reported. I'd like to see a test for this change, preferably one that exercises what happens in this scenario where the HCL type _is_ a string:
> 
> ```
> variable "example" {
>   type    = string
>   default = "[\"dc1\"]"
> }
> ```

I have added the test case for validating above scenarios . Can you re review it ?

**Comment by navyadas-dev** [comment]
> None of the videos playback for me. But what should be noted here is that the behavior is different for `-var-file` and `-var`. As far as I can tell, using `-var-file` works fine but using `-var` does not.
> 
> example.nomad.hcl
> ```
> $ nomad job run -var='datacenters=["dc1", "dc2"]' ./example.nomad.hcl
> ...
> $ nomad job inspect example | jq '.Job.Datacenters'
> [
>   "dc1",
>   "dc2"
> ]
> 
> $ nomad operator api "/v1/job/example/submission?version=0"  | jq .
> {
>   "Format": "hcl2",
>   "JobID": "example",
>   "JobModifyIndex": 68,
>   "Namespace": "default",
>   "Source": "variable \"datacenters\" {\n  type    = list(string)\n  default = [\"dc1\"]\n}\n\njob \"example\" {\n\n  datacenters = var.datacenters\n\n  group \"group\" {\n\n    task \"task\" {\n\n      driver = \"docker\"\n      user   = \"www-data\"\n\n      config {\n        image   = \"busybox:1\"\n        command = \"httpd\"\n        args    = [\"-vv\", \"-f\", \"-p\", \"8001\", \"-h\", \"/local\"]\n      }\n\n      resources {\n        cpu    = 100\n        memory = 100\n      }\n\n    }\n  }\n}\n",
>   "VariableFlags": {
>     "datacenters": "[\"dc1\", \"dc2\"]"
>   },
>   "Variables": "",
>   "Version": 0
> }
> ```
> 
> Broken, as reported: var-flag-broken
> 
> With the fix in this PR, it now works as expected: var-flag-fixed
> 
> vs
> 
> ```
> $ nomad job run -var-file ./vars.hcl ./example.nomad.hcl
> ...
> $ nomad operator api "/v1/job/example/submission?version=1"  | jq .
> {
>   "Format": "hcl2",
>   "JobID": "example",
>   "JobModifyIndex": 84,
>   "Namespace": "default",
>   "Source": "variable \"datacenters\" {\n  type    = list(string)\n  default = [\"dc1\"]\n}\n\njob \"example\" {\n\n  datacenters = var.datacenters\n\n  group \"group\" {\n\n    task \"task\" {\n\n      driver = \"docker\"\n      user   = \"www-data\"\n\n      config {\n        image   = \"busybox:1\"\n        command = \"httpd\"\n        args    = [\"-vv\", \"-f\", \"-p\", \"8001\", \"-h\", \"/local\"]\n      }\n\n      resources {\n        cpu    = 100\n        memory = 100\n      }\n\n    }\n  }\n}\n",
>   "VariableFlags": null,
>   "Variables": "datacenters=[\"dc1\", \"dc2\"]\n\n",
>   "Version": 1
> }
> ```
> 
> Works without changes: var-file-works

Thanks for checking! The videos are playing fine for me - I'm not sure why they're not playing back for you. I've included the full workflow in those videos. The video was demonstrating this exact scenario - submitting via -var and then viewing/editing in the UI and plan job.

File: ui/app/utils/json-to-hcl.js [hunk 2]
```diff
@@ -16,7 +16,24 @@ export default function jsonToHcl(obj) {
...
   for (const key in obj) {
     const value = obj[key];
-    const hclValue = typeof value === 'string' ? JSON.stringify(value) : value;
+    let hclValue;
+
+    if (typeof value === 'string') {
+      // Try to parse as JSON to validate it's actually valid JSON
+      try {
+        const parsed = JSON.parse(value);
+        if (typeof parsed === 'object' && parsed !== null) {
```
Comment (mismithhisler) [inline ui/app/utils/json-to-hcl.js]: Leaving this as a comment because I had to look it up. The [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#return_value) state JSON.parse can return various types. You would think a JSON array like `'["1", "2"]'` might return a typeof array, but it's really an object.

File: ui/app/utils/json-to-hcl.js [hunk 3]
```diff
@@ -16,7 +16,24 @@ export default function jsonToHcl(obj) {
...
+          hclValue = value;
+        } else {
+          hclValue = JSON.stringify(value);
+        }
+      } catch {
+        // Not valid JSON, treat as a regular string
+        hclValue = JSON.stringify(value);
+      }
+    } else {
+      hclValue = JSON.stringify(value);
```
Comment (mismithhisler) [inline ui/app/utils/json-to-hcl.js]: The original conditional was `if value is of type 'string' : stringify : else value`. But it looks like here we've changed it to always stringify?

Comment (mismithhisler) [reply ui/app/utils/json-to-hcl.js]: @navyadas-dev any update on this?

Comment (navyadas-dev) [reply ui/app/utils/json-to-hcl.js]: We're not always stringifying - we're preserving valid JSON objects/arrays while stringifying everything else. I have updated the code changes with extracting the helper function for better readability.

Let me explain in detail

- **Before the fix** 

if (typeof value === 'string') {
  hclValue = JSON.stringify(value);  // Always stringify strings
}
// Input: '["dc1"]' → Output: "\"[\\\"dc1\\\"]\""  (double-escaped)

- **After the fix**

The Nomad API returns VariableFlags with all values as strings (regardless of their original type):

{
  "datacenters": "[\"dc1\"]",           // String containing JSON array
  "count": "1",                          // String containing number
  "app_name": "my-app"                   // Plain string
}

Example 1: Plain String Variable

1.  When API returns:

value = 'my-app'  // Plain string

Code execution:
```
JSON.parse('my-app')  // → throws SyntaxError
// catch block:
return JSON.stringify('my-app');  // ← Add quotes
```

// Output: app_name="my-app" 


Example 2: Array Variable 

2. When API returns:

value = '["dc1","dc2"]'  // String containing JSON array

Code execution:
```
JSON.parse('["dc1","dc2"]')  // → ["dc1","dc2"] (array)
typeof ["dc1","dc2"] === 'object'  // → true
return value;  // ← NO JSON.stringify! Keep original string
```

// Output: datacenters=["dc1","dc2"] 


Example 3: Number Variable

3.  When API return:
value = '1'  // String containing number

 Code execution:
```
JSON.parse('1')  // → 1 (number)
typeof 1 === 'object'  // → false
return JSON.stringify('1');  // ← Add quotes

```
// Output: count="1"

Comment (mismithhisler) [reply ui/app/utils/json-to-hcl.js]: Do you see how the original logic was:
```
const hclValue = typeof value === 'string' ? JSON.stringify(value) : value <-- this;
```
And you changed that last bit `... :JSON.stringify(value)`???
```
      const hclValue =
        typeof value === 'string'
          ? convertStringValue(value)
          : JSON.stringify(value); // Defensive: handle non-string values <- to this
```

Comment (navyadas-dev) [reply ui/app/utils/json-to-hcl.js]: Yes we can update it. Although the Nomad API returns VariableFlags as an object of string values, this has been added as a defensive measure. The original logic still makes sense, as non-string values should be passed through as-is.

Comment (mismithhisler) [reply ui/app/utils/json-to-hcl.js]: I think what I'm wondering is, what is this defending against? What if VariablesFlags supported numbers in the future? Now the UI is changing the type.

Is there something in the UI that would fail if this was a number or other type?

Comment (navyadas-dev) [reply ui/app/utils/json-to-hcl.js]: @mismithhisler  No. UI will not fail.
**Current behavior:** the API always returns VariableFlags as map[string]string., UI handles them correctly
**If the API changes to support native types (numbers, booleans)**- code will correctly pass them through as-is without stringifying.(else part (: value) passes them through unchanged).

The issue was never about type conversion. It was:

**Before fix:**
UI displayed: `datacenters="[\"dc1\",\"dc2\"]" `(double-escaped)
User edits and clicks "Plan"
UI sends this malformed HCL to /v1/job/{job}/plan
Result: Parse error 

Screenshot 2026-04-22 at 11 17 38 AM


 **After fix:**
UI displays: datacenters=["dc1","dc2"] (correct HCL)
User edits and clicks "Plan"
UI sends correct HCL to /v1/job/{job}/plan
Result: Success 
Screenshot 2026-04-22 at 11 19 30 AM



**Here the fix is correctly formatting those strings for HCL display, not type conversion.**

The API supporting other native types is unlikely, since the UI converts VariableFlags to HCL and sends them to endpoints that expect map[string]string:

```
/v1/jobs/parse → VariableFlags as map[string]string
/v1/job/{job}/plan → VariableFlags as map[string]string
```

**Review by mismithhisler — APPROVED** [review]

File: ui/app/utils/json-to-hcl.js [hunk 4]
```diff
@@ -7,19 +7,46 @@
...
+    .map(([key, value]) => {
+      const hclValue =
+        typeof value === 'string' ? convertStringValue(value) : value; // Defensive: handle non-string values
 
-    hclLines.push(`${key}=${hclValue}\n`);
-  }
+      return `${key}=${hclValue}`;
+    });
+
+  return hclLines.length > 0 ? hclLines.join('\n') + '\n' : '';
```
Comment (mismithhisler) [inline ui/app/utils/json-to-hcl.js:31]: Why the extra newline here?

Comment (navyadas-dev) [reply ui/app/utils/json-to-hcl.js:31]: The extra newline + '\n'  maintains the same behaviour as the old code where each line included a trailing newline. 

Here the code refactoring changed 
**From**: Including \n in each item + joining with empty string
**To**: Not including \n in items + joining with \n + adding final \n

Old code with 2 items:

hclLines.push(`key1=value1\n`);  // "key1=value1\n"
hclLines.push(`key2=value2\n`);  // "key2=value2\n"
hclLines.join('');               // "key1=value1\nkey2=value2\n"

New code with 2 items:

map returns: ["key1=value1", "key2=value2"]
join('\n'):  //"key1=value1\nkey2=value2"
+'\n':     // "key1=value1\nkey2=value2\n"

Both approaches produce the same output.
