### PR TITLE
Fixed merging consul config

### LINKED ISSUE #2099: Consul auto_advertise value not being used
### Issue

`auto_advertise` can be set to false but the agent will still advertise

### Reproduction steps

```
consul {
  auto_advertise = false
}
```

### PR DESCRIPTION
**Pull request by diptanu**
Fixes #2099

### CODE REVIEW

File: nomad/structs/config/consul.go [hunk 1]
```diff
@@ -98,8 +98,8 @@ func (a *ConsulConfig) Merge(b *ConsulConfig) *ConsulConfig {
 	if b.ClientServiceName != "" {
 		result.ClientServiceName = b.ClientServiceName
 	}
-	if b.AutoAdvertise {
-		result.AutoAdvertise = true
+	if !b.AutoAdvertise {
```
Comment (dadgar) [inline nomad/structs/config/consul.go]: All the booleans in the config really need to be updated to this style: https://github.com/hashicorp/nomad/blob/master/nomad/structs/config/vault.go#L26

The difference is that by making it a pointer we can tell if the user set it. This gives us three states: unset, false, true. If it is Unset we use the default and if not use what ever is set.

https://github.com/hashicorp/nomad/blob/master/nomad/structs/config/vault.go#L132

**Comment by dadgar** [comment]
@diptanu Some tests are breaking from this PR https://travis-ci.org/hashicorp/nomad/builds/193861597#L928
