### PR TITLE
job: Validate the constraint attribute.

### LINKED ISSUE #17435: computed class inelligible message is not clear and difficult to debug
### Nomad version
1.5.6

### Issue
`Constraint computed class ineligible filtered 1 node` is not helpful.

### Reproduction steps
Here are three completely different ways to reproduce this error message
1) https://github.com/hashicorp/nomad/issues/8411
2) https://stackoverflow.com/questions/56660651/nomad-job-failed-to-place-all-allocations
3) https://discuss.hashicorp.com/t/how-to-find-out-why-a-job-placement-is-failing-with-a-constraint/32209

The 3rd post there lead me to the correct solution, but still required reading between the lines.

#### Expected Result

A human readable sentence.  "Constraint computed class ineligible" is not that.

The docs for [attribute](https://developer.hashicorp.com/nomad/docs/job-specification/constraint#attribute) suggest that all acceptable values must start with a [Nomad Interpolated Value](https://developer.hashicorp.com/nomad/docs/runtime/interpolation#interpreted_node_vars) something like `/\$\{(node|attr|meta)/` though I suspect it's more complicated than that.  A message indicating that `attribute = "${platform.aws.placement.availability-zone}"` was unacceptable because it did not start with `attr` would have been better.

### PR DESCRIPTION
**Pull request by jrasell**
This change adds better validation of the job specification constraint block attribute parameter. The parameter has a well defined set of possible formats, meaning we can catch these before submitting the job to the scheduler. This validation is returned to the job submitter who can make adjustments to any errors.

Before this change, no validation of the parameter contents was conducted, meaning a job could be submitted to the scheduler that would never be placable.

I took the opportunity to update the existing constraint validation test to be table driven and use the `must` library.

### Testing & Reproduction steps
Tested using this example job:
```hcl
job "example" {
  constraint {
    attribute = "${platform.aws.placement.availability-zone}"
    operator  = ">"
    value     = "3"
  }

  group "cache" {
    network {
      port "db" {
        to = 6379
      }
    }

    task "redis" {
      driver = "docker"

      config {
        image          = "redis:7"
        ports          = ["db"]
        auth_soft_fail = true
      }

      identity {
        env  = true
        file = true
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

### Links
Closes #17435
Jira https://hashicorp.atlassian.net/browse/NMD-1022

### Contributor Checklist
- [x] **Changelog Entry** If this PR changes user-facing behavior, please generate and add a
  changelog entry using the `make cl` command.
- [x] **Testing** Please add tests to cover any new functionality or to demonstrate bug fixes and
  ensure regressions will be caught.
- [x] **Documentation** If the change impacts user-facing functionality such as the CLI, API, UI,
  and job configuration, please update the Nomad product documentation, which is stored in the
  [`web-unified-docs` repo](../web-unified-docs/). Refer to the [`web-unified-docs` contributor guide](../web-unified-docs/tree/docs/contribute.md) for docs guidelines.
  Please also consider whether the change requires notes within the [upgrade
  guide](https://developer.hashicorp.com/nomad/docs/upgrade/upgrade-specific). If you would like help with the docs, tag the `nomad-docs` team in this PR.

### Reviewer Checklist
- [x] **Backport Labels** Please add the correct backport labels as described by the internal
  backporting document.
- [x] **Commit Type** Ensure the correct merge method is selected which should be "squash and merge"
  in the majority of situations. The main exceptions are long-lived feature branches or merges where
  history should be preserved.
- [x] **Enterprise PRs** If this is an enterprise only PR, please add any required changelog entry
  within the public repository.

### CODE REVIEW

**Review by pkazmierczak — DISMISSED** [review]

File: nomad/structs/structs.go [hunk 1]
```diff
@@ -9955,9 +9955,17 @@ func (c *Constraint) Validate() error {
...
 	}
 
-	// Ensure we have an LTarget for the constraints that need one
-	if requireLtarget && c.LTarget == "" {
-		mErr.Errors = append(mErr.Errors, fmt.Errorf("No LTarget provided but is required by constraint"))
+	// If the constraint must have a "LTarget" (attribute in the job spec), then
+	// ensure it is not an empty string and is valid.
+	if requireLtarget {
+		if c.LTarget == "" {
+			mErr.Errors = append(mErr.Errors, fmt.Errorf("No LTarget provided but is required by constraint"))
```
Comment (tgross) [inline nomad/structs/structs.go]: I know we're just using the existing language here but `LTarget` and `RTarget` are in the HTTP API but not the HCL or the jobspec documentation. Is there a reasonable way to improve upon this error message?

File: nomad/structs/constraint.go [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+		return nil
+	}
+
+	// Must have closing brace
+	if !strings.HasSuffix(target, "}") {
+		return fmt.Errorf("attribute %q is missing a closing brace", target)
+	}
+
+	// Extract the interpolatable content between the delimiters.
+	interior := strings.TrimSuffix(strings.TrimPrefix(target, "${"), "}")
```
Comment (tgross) [inline nomad/structs/constraint.go]: We could probably skip this step by having the `validConstraintExactTargets` include the `${...}` and the `validConstraintPrefixTargets` include the `${`. Arguably we could skip the previous checks entirely but I do like the friendly error messages you can give this way.

File: nomad/structs/constraint.go [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+// validateConstraintAttribute ensures the constraint attribute is valid. It
+// does this by ensuring any interpolated field can be handled by the
+// resolveTarget function.
+func validateConstraintAttribute(target string) error {
+
+	// If no prefix delimieter is included, we assume this is a literal value
+	// and is therefore valid.
+	if !strings.HasPrefix(target, "${") {
+		return nil
+	}
```
Comment (tgross) [inline nomad/structs/constraint.go:39]: I looked through all the feasibility checking code and couldn't figure out which case where `LTarget` is ever going to be a non-interpreted literal. I suppose you _could_ do:

```hcl
constraint {
  attribute = "test"
  operator  = "="
  value     = "test"
}
```

and that would always evaluate to true. Maybe we need to keep this in for backwards compatibility of "weird" constraints like this if nothing else?

File: nomad/structs/structs_test.go [hunk 4]
```diff
@@ -3645,75 +3645,154 @@ func TestTaskWaitConfig_Equals(t *testing.T) {
...
+	}{
+		{
+			name:             "missing operand",
+			inputConstraint:  &Constraint{},
+			expectedErrorMsg: "Missing constraint operand",
+		},
+		{
+			name: "valid",
+			inputConstraint: &Constraint{
+				LTarget: "$attr.kernel.name",
```
Comment (tgross) [inline nomad/structs/structs_test.go]: This works without the bracket? Even if it worked before, the new code is skipping right over the attribute validation here.

**Review by tgross — DISMISSED** [review]
LGTM but I've got a few minor questions / comments.

File: nomad/structs/constraint.go (hunk 3 above)
Comment (jrasell) [reply nomad/structs/constraint.go:39]: Agreed.

fwiw I used https://github.com/hashicorp/nomad/blob/cc8af59be96e89869f77a3f1d5ccd896299fc30d/scheduler/feasible/feasible.go#L992 as my basis for the added validation functionality. The particular idea on this is > 10 years old, so it's possible something we can remove like you say, but I assume people are using it in ways we can't quite predict.

File: nomad/structs/structs_test.go (hunk 4 above)
Comment (jrasell) [reply nomad/structs/structs_test.go]: Good call. I've tightened the validation logic up within https://github.com/hashicorp/nomad/pull/27355/commits/d87018305d1d94ecbd392c8ee6eaeed5cdbfa2fe

File: nomad/structs/constraint.go (hunk 2 above)
Comment (jrasell) [reply nomad/structs/constraint.go]: Updated this within https://github.com/hashicorp/nomad/pull/27355/commits/d87018305d1d94ecbd392c8ee6eaeed5cdbfa2fe

File: nomad/structs/structs.go (hunk 1 above)
Comment (jrasell) [reply nomad/structs/structs.go]: Tried to make a nicer message within https://github.com/hashicorp/nomad/pull/27355/commits/d87018305d1d94ecbd392c8ee6eaeed5cdbfa2fe

**Review by tgross — DISMISSED** [review]
LGTM!

**Review by tgross — DISMISSED** [review]

**Review by tgross — APPROVED** [review]

**Comment by chrisboulton** [comment]
Is there a chance this breaks constraints using device attributes within `device {}` blocks? I've some unrelated changes (somewhat related, but I don't think would cause this) locally right now and I'm seeing a bunch of `unsupported attribute` error messages from some [E2E tests I added for devices](https://github.com/hashicorp/nomad/compare/main...chrisboulton:nomad:device-first-available#diff-c7317ed73e3ffc84a8ad13dbae3d7803dd0abcff57866b5902fb5600854ec140)..

Device: (I'm just using the example device plugin)

```json
~/Dev/nomad/e2e/devices:main ● ● $ nomad node status -json -self | jq '.NodeResources.Devices'

[
  {
    "Attributes": {
      "cool-attribute": {
        "String": "attribute-wearing-sunglasses",
        "Unit": ""
      }
    },
```

job spec:

```hcl
job "device-with-constraint" {
  type = "batch"

  group "test" {
    count = 1

    task "sleep" {
      driver = "raw_exec"

      config {
        command = "sleep"
        args    = ["30"]
      }

      resources {
        cpu    = 10
        memory = 64

        device "nomad/file/mock" {
          count = 1

          constraint {
            attribute = "${device.attr.cool-attribute}"
            value     = "attribute-wearing-sunglasses"
          }
        }
      }
    }
  }
}
```

Error:

```
  error=
  | 1 error occurred:
  | \t* Task group test validation failed: 1 error occurred:
  | \t* Task sleep validation failed: 1 error occurred:
  | \t* 1 error occurred:
  | \t* device 1 failed validation: 1 error occurred:
  | \t* Constraint 1 validation failed: 1 error occurred:
  | \t* unsupported attribute "${device.attr.cool-attribute}"
```

My assumption is the same validation (through the structs?) is being called for device affinities/constraints?

[edit] Yup, it does -- I backed out the validation PR and the E2E tests I added to validate device constraints/affinities now pass. This is something we might want to fix as [I noticed the backport of these changes into 1.11.x](https://github.com/hashicorp/nomad/pull/27365).

**Comment by jrasell** [comment]
Great spot @chrisboulton and thanks! I'll get a fixed raise at some point soon.
