### PR TITLE
drivers/exec: use an independent name=systemd cgroup path

### LINKED ISSUE #5736: Driver exec sometimes fails to SIGKILL a task if the SIGINT is ignored
### Nomad version
Nomad v0. 9.1

### Operating system and Environment details
OS: RedHat Enterprise Linux 7.3

### Issue
Driver exec sometimes fails to SIGKILL a task if the SIGINT is ignored

### Reproduction steps
I have created a simple test job made up of the following two scripts which for simplicity I have put in the /usr/bin directory of my test server:

 trap.sh:
```
#!/bin/bash
trap "echo sigint" SIGINT
trap "echo sigterm" SIGTERM

/usr/bin/trap_sleep.sh
```
trap_sleep.sh:
```
#!/bin/bash
while :
do
    sleep 60
done
```
And am running the job with the following JSON payload:
```
{
  "Job": {
    "Constraints": [],
    "Datacenters": [
      "dc1"
    ],
    "ID": "sigtest",
    "Name": "sigtest",
    "Priority": 50,
    "TaskGroups": [
      {
        "Count": 5,
        "EphemeralDisk": {
          "Migrate": false,
          "SizeMB": 500,
          "Sticky": false
        },
        "Name": "group",
        "Update": {
          "HealthyDeadline": 900000000000,
          "MaxParallel": 1,
          "MinHealthyTime": 10000000000,
          "ProgressDeadline": 0
        },
        "Tasks": [
          {
            "Artifacts": [],
            "Config": {
              "command": "/usr/bin/trap.sh",
              "args": []
            },
            "Driver": "exec",
            "Env": {
              "Redeploy": "1"
            },
            "Leader": true,
            "Name": "sigtest",
            "Resources": {
              "CPU": 200,
              "Devices": null,
              "DiskMB": 0,
              "IOPS": 0,
              "MemoryMB": 75,
              "Networks": []
            },
            "Services": []
          }
        ]
      }
    ],
    "Type": "service",
    "Update": {
      "MaxParallel": 1
    }
  }
}
```
I then try to redeploy the job by increasing the value of the Redeploy env variable and resubmitting.

When Nomad needs to stop the running allocations the script traps the default SIGINT signal and I expect Nomad to force the kill with a SIGKILL five seconds later.

Most of the time this works, but occasionally the SIGKILL is never sent. For example this log file is from an allocation that was never killed:
```
2019-05-20T16:25:21.476+0100 [DEBUG] client.driver_mgr.exec.executor: using plugin: alloc_id=06db34f1-a57e-9004-27eb-942f9bf9e479 driver=exec task_name=sigtest version=2
2019-05-21T10:00:10.408+0100 [DEBUG] client.alloc_migrator: waiting for previous alloc to terminate: alloc_id=56043f29-ac4a-8d31-dfce-4e55f3dfd04a previous_alloc=06db34f1-a57e-9004-27eb-942f9bf9e479
2019-05-21T10:00:30.406+0100 [ERROR] client.alloc_runner.task_runner: failed to kill task: alloc_id=06db34f1-a57e-9004-27eb-942f9bf9e479 task=sigtest backoff=5s error="executor Shutdown failed: rpc error: code = Unknown desc = process failed to exit after 15 seconds"
2019-05-21T10:00:55.410+0100 [ERROR] client.alloc_runner.task_runner: failed to kill task: alloc_id=06db34f1-a57e-9004-27eb-942f9bf9e479 task=sigtest backoff=20s error="executor Shutdown failed: rpc error: code = Unknown desc = process failed to exit after 15 seconds"
2019-05-21T10:01:35.414+0100 [ERROR] client.alloc_runner.task_runner: failed to kill task: alloc_id=06db34f1-a57e-9004-27eb-942f9bf9e479 task=sigtest backoff=1m20s error="executor Shutdown failed: rpc error: code = Unknown desc = process failed to exit after 15 seconds"
2019-05-21T10:03:15.418+0100 [ERROR] client.alloc_runner.task_runner: failed to kill task: alloc_id=06db34f1-a57e-9004-27eb-942f9bf9e479 task=sigtest backoff=2m0s error="executor Shutdown failed: rpc error: code = Unknown desc = process failed to exit after 15 seconds"
2019-05-21T10:05:35.423+0100 [ERROR] client.alloc_runner.task_runner: failed to kill task: alloc_id=06db34f1-a57e-9004-27eb-942f9bf9e479 task=sigtest backoff=2m0s error="executor Shutdown failed: rpc error: code = Unknown desc = process failed to exit after 15 seconds"
2019-05-21T10:07:35.423+0100 [ERROR] client.alloc_runner.task_runner: failed to kill task. Resources may have been leaked: alloc_id=06db34f1-a57e-9004-27eb-942f9bf9e479 task=sigtest error="executor Shutdown failed: rpc error: code = Unknown desc = process failed to exit after 15 seconds"
```
By running strace against the trap.sh process I can see that the SIGINT is being sent correctly so Nomad is certainly still capable of sending signals:
```
wait4(-1, 0x7ffcfa3f96b0, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGINT {si_signo=SIGINT, si_code=SI_USER, si_pid=72333, si_uid=0} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
wait4(-1, 0x7ffcfa3f96b0, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
wait4(-1, 0x7ffcfa3f96b0, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGINT {si_signo=SIGINT, si_code=SI_USER, si_pid=72333, si_uid=0} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
wait4(-1,
```
This is not perfectly reproducible but appears to happen fairly consistently if the allocation has been running for at least twelve hours to a day. If the job is redeployed quickly then the SIGKILL correctly gets sent after five seconds.
```
wait4(-1, 0x7ffea53306c0, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGINT {si_signo=SIGINT, si_code=SI_USER, si_pid=18014, si_uid=0} ---
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
wait4(-1, 0x7ffea53306c0, 0, NULL)      = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
+++ killed by SIGKILL +++
```

### PR DESCRIPTION
**Pull request by notnoop**
We aim for containers to be part of a new cgroups hierarchy independent
from nomad agent.  However, we've been setting a relative path as
libcontainer `cfg.Cgroups.Path`, which makes libcontainer concatinate
the executor process cgroup with passed cgroup, as set in [1].

By setting an absolute path, we ensure that all cgroups subsystem
(including `name=systemd` get a dedicated one).  This matches behavior
in Nomad 0.8, and behavior of how Docker and OCI sets CgroupsPath[2]

Fixes #5736

[1] https://github.com/hashicorp/nomad/blob/d7edf9b2e42348865908735996359c7869fb16b5/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/apply_raw.go#L326-L340
[2] https://github.com/moby/moby/blob/238f8eaa31aa74be843c81703fabf774863ec30c/vendor/github.com/containerd/containerd/oci/spec.go#L229

### CODE REVIEW

File: drivers/exec/driver_test.go [hunk 1]
```diff
@@ -436,7 +436,7 @@ func TestExecDriver_HandlerExec(t *testing.T) {
 		}
 		// Skip systemd and rdma cgroups; rdma was added in most recent kernels and libcontainer/docker
```
Comment (schmichael) [inline drivers/exec/driver_test.go]: Update comment

File: drivers/shared/executor/executor_linux_test.go [hunk 2]
```diff
@@ -164,6 +164,59 @@ passwd`
...
+			return false, fmt.Errorf("was expected cgroup files but found:\n%v", output)
+		}
+		lines := strings.Split(output, "\n")
+		for _, line := range lines {
+			// Every cgroup entry should be /nomad/$ALLOC_ID
+			if line == "" {
+				continue
+			}
+
+			// Skip systemd and rdma cgroups; rdma was added in most recent kernels and libcontainer/docker
```
Comment (schmichael) [inline drivers/shared/executor/executor_linux_test.go]: Update comment
