### PR TITLE
Fix returned EOF error when calling Nodes GC/GcAlloc API

### LINKED ISSUE #5506: Error while calling go library api [client gc]
### Nomad version
0.9.0-rc2

This happens when I call the client gc api:

nomadgc

I called it like this:
nomadgc3

and got the error: "EOF" 
the error returns when decoding the resp.

### PR DESCRIPTION
**Pull request by jrasell**
Internally Nomad returns a http.NoBody when calling nodes GC, therefore attempting to decode the body results in an EOF error returned to the user. This fix updates the decodeBody function to check both the response content length and the passed out object.

The following code snippet can be used to locally test:

```go
package main

import (
	"fmt"

	"github.com/hashicorp/nomad/api"
)

func main() {
	nomadClient, _ := api.NewClient(api.DefaultConfig())
	nodeSelf, _ := nomadClient.Agent().Self()
	fmt.Println(nomadClient.Nodes().GC(nodeSelf.Stats["client"]["node_id"], nil))
}
```

Closes #5506 #5994

### CODE REVIEW

File: api/api.go [hunk 1]
```diff
@@ -769,8 +769,10 @@ func (c *Client) query(endpoint string, out interface{}, q *QueryOptions) (*Quer
 	parseQueryMeta(resp, qm)
 	qm.RequestTime = rtt
 
-	if err := decodeBody(resp, out); err != nil {
-		return nil, err
+	if out != nil {
+		if err := decodeBody(resp, out); err != nil {
```
Comment (langmartin) [inline api/api.go]: This allows us to use the `nil` to signal query that we expect an empty body. I'd prefer to change decodeBody to read `resp.ContentLength` to avoid parsing an empty response. Does that make sense?

**Comment by tgross** [comment]
@langmartin it looks like the requested changes were made, but I can't get Travis to rebuild it because we've removed the scripts for Travis since this was last pushed. Maybe if @jrasell would be willing to squash his commits and re-push, it'll trigger CircleCI and we can get this merged?

**Comment by langmartin** [comment]
Yes! @jrasell the age on this is my fault, it got mixed up with some followup work: we shouldn't be using side effecting `GET` requests for making changes. I'll capture that in another ticket, and this should be fine to merge. @tgross suggestion to squash is right. Sorry about letting this fall through the cracks!

File: api/api.go [hunk 2]
```diff
@@ -930,8 +931,16 @@ func parseWriteMeta(resp *http.Response, q *WriteMeta) error {
 
 // decodeBody is used to JSON decode a body
 func decodeBody(resp *http.Response, out interface{}) error {
```
Comment (notnoop) [inline api/api.go]: Should we always skip decoding body if `out == nil`?  I noticed that we wrap few `decodeBody` invocations with a nil check already:
https://github.com/hashicorp/nomad/blob/d890ddbfd9125f36bc7ff70cc7a584dd038e8432/api/api.go#L858-L862 .

It would simplify caller code a bit, and it doesn't seem like an error if caller explicitly passes nil and ignores response body (though body may need to be consumed... a potential bug in current code).
