### PR TITLE
Switch to pre-0.9 behaviour for handling volumes

### LINKED ISSUE #5562: named docker volume doesn't work anymore with 0.9.0
### Nomad version
`Nomad v0.8.7 (21a2d93eecf018ad2209a5eab6aae6c359267933+CHANGES)`
`Nomad v0.9.0 (18dd59056ee1d7b2df51256fe900a98460d3d6b9)`

### Operating system and Environment details
ArchLinux

### Issue
After upgrading to nomad 0.9.0 named docker volumes are not working anymore.

### Reproduction steps
* nomad config:
```
data_dir  = "/var/lib/nomad"
log_level = "debug"
server {
    enabled = true
    bootstrap_expect = 1
}
client {
    enabled = true
}
```
* run the job with nomad 0.8.7 and inspect resulting docker container:
```
---snip---
        "HostConfig": {
            "Binds": [
                "/var/lib/nomad/alloc/d6d8e0cf-61fb-8c46-d278-e56ab11337f6/alloc:/alloc",
                "/var/lib/nomad/alloc/d6d8e0cf-61fb-8c46-d278-e56ab11337f6/test/local:/local",
                "/var/lib/nomad/alloc/d6d8e0cf-61fb-8c46-d278-e56ab11337f6/test/secrets:/secrets",
                "test:/testing"
            ],
---snip---
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/lib/nomad/alloc/d6d8e0cf-61fb-8c46-d278-e56ab11337f6/alloc",
                "Destination": "/alloc",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/lib/nomad/alloc/d6d8e0cf-61fb-8c46-d278-e56ab11337f6/test/local",
                "Destination": "/local",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/lib/nomad/alloc/d6d8e0cf-61fb-8c46-d278-e56ab11337f6/test/secrets",
                "Destination": "/secrets",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "test",
                "Source": "/var/lib/docker/volumes/test/_data",
                "Destination": "/testing",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
---snip---
```
* deploy the same job on nomad 0.9.0 and inspect resulting docker container:
```
---snip---
        "HostConfig": {
            "Binds": [
                "/var/lib/nomad/alloc/4d497db5-12fc-9895-0fe0-790089845842/alloc:/alloc",
                "/var/lib/nomad/alloc/4d497db5-12fc-9895-0fe0-790089845842/test/local:/local",
                "/var/lib/nomad/alloc/4d497db5-12fc-9895-0fe0-790089845842/test/secrets:/secrets",
                "/var/lib/nomad/alloc/4d497db5-12fc-9895-0fe0-790089845842/test/test:/testing"
            ],
---snip---
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/var/lib/nomad/alloc/4d497db5-12fc-9895-0fe0-790089845842/test/test",
                "Destination": "/testing",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/lib/nomad/alloc/4d497db5-12fc-9895-0fe0-790089845842/alloc",
                "Destination": "/alloc",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/lib/nomad/alloc/4d497db5-12fc-9895-0fe0-790089845842/test/local",
                "Destination": "/local",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/lib/nomad/alloc/4d497db5-12fc-9895-0fe0-790089845842/test/secrets",
                "Destination": "/secrets",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```

### Job file (if appropriate)
```
cat example.job 
job "test" {
    datacenters = ["dc1"]
    type = "service"
    group "test" {
        task "test" {
            driver = "docker" 
            config {
                image = "alpine:3.9"
                args = [ "sleep", "1000" ]
                volumes = [ "test:/testing" ]
                volume_driver = "local"
            }
        }
    }
}
```
In nomad 0.9.0 the same job result not in an volume mount but an bind mount.

### PR DESCRIPTION
**Pull request by dantoml**
In Nomad 0.9, we made volume driver handling the same for `""`, and
`"local"` volumes. Prior to Nomad 0.9 however these had slightly different
behaviour for relative paths and named volumes.

Prior to 0.9 the empty string would expand relative paths within the task
dir, and `"local"` volumes that are not absolute paths would be treated
as docker named volumes.

This commit reverts to the previous behaviour as follows:

| Nomad Version | Driver  |   Volume Spec    | Behavior  |
| --- | --- | --- | --- |
| all | ""      | testing:/testing | allocdir/testing  |
| 0.8.7 | "local" | testing:/testing | "testing" as named volume |
| 0.9.0 | "local" | testing:/testing | allocdir/testing |
| 0.9.1  | "local" | testing:/testing | "testing" as named volume |

This fixes #5562

### CODE REVIEW

File: drivers/docker/driver.go [hunk 1]
```diff
@@ -618,12 +618,15 @@ func (d *Driver) containerBinds(task *drivers.TaskConfig, driverConfig *TaskConf
 		// Paths inside task dir are always allowed, Relative paths are always allowed as they mount within a container
 		// When a VolumeDriver is set, we assume we receive a binding in the format volume-name:container-dest
 		// Otherwise, we assume we receive a relative path binding in the format relative/to/task:/also/in/container
-		if localBindVolume {
+		if taskLocalBindVolume {
 			parts[0] = expandPath(task.TaskDir().Dir, parts[0])
+		} else {
+			// Resolve dotted path segments
+			parts[0] = filepath.Clean(parts[0])
```
Comment (notnoop) [inline drivers/docker/driver.go]: Let's add a test to exercise this path given it's part of 0.8.7.  That being said, if `part[0]` is to be treated as a volume name and not a path, I think we ought to pass the string verbatim without modification.

File: drivers/docker/driver_unix_test.go [hunk 2]
```diff
@@ -299,10 +299,10 @@ func TestDockerDriver_BindMountsHonorVolumesEnabledFlag(t *testing.T) {
 		},
 		{
 			name:            "relative local driver",
```
Comment (notnoop) [inline drivers/docker/driver_unix_test.go]: ~~ Maybe update the name to reflect this being treated as a volume name rather than a relative path.

File: drivers/docker/driver.go [hunk 3]
```diff
@@ -603,9 +603,9 @@ func (d *Driver) containerBinds(task *drivers.TaskConfig, driverConfig *TaskConf
 	secretDirBind := fmt.Sprintf("%s:%s", task.TaskDir().SecretsDir, task.Env[taskenv.SecretsDir])
 	binds := []string{allocDirBind, taskLocalBind, secretDirBind}
 
-	localBindVolume := driverConfig.VolumeDriver == "" || driverConfig.VolumeDriver == "local"
+	taskLocalBindVolume := driverConfig.VolumeDriver == ""
 
-	if !d.config.Volumes.Enabled && !localBindVolume {
+	if !d.config.Volumes.Enabled && !taskLocalBindVolume {
```
Comment (notnoop) [inline drivers/docker/driver.go]: Actually this might have a regression.  Can you double check behavior for interpolation in 0.8.7?  Looking at 0.8.7 code, if a user set volume driver to an absolute path to alloc dir (maybe through env-var interpolation?!), we would allow it.  I assume that's what the comment below is about:

> 		// Paths inside task dir are always allowed, Relative paths are always allowed as they mount within a container

Comment (notnoop) [reply drivers/docker/driver.go]: Never mind - `local` isn't allowed in - https://github.com/hashicorp/nomad/blob/v0.8.7/client/driver/docker.go#L1166 .  Maybe need to update comment then.  Paths inside task dir are allowed only if volume driver is empty.
