### PR TITLE
Filter executor log messages

### LINKED ISSUE #2106: [question] - executor can't create pid
### Nomad version
Nomad v0.5.0

### Operating system and Environment details
I am using raw_exec and sucessfully running docker without isolation. I am getting weired logs in the executor 

### Question
Can some one explain what am i doing wrong/what is the meaning of these lines in the executor logs?
my executor logs are filled with thousands of these:
016/12/14 14:48:39 [DEBUG] executor: unable to create new process with pid: 30390
2016/12/14 14:48:40 [DEBUG] executor: unable to create new process with pid: 30390
2016/12/14 14:48:41 [DEBUG] executor: unable to create new process with pid: 30390
2016/12/14 14:48:42 [DEBUG] executor: unable to create new process with pid: 30390
2016/12/14 14:48:44 [DEBUG] executor: unable to create new process with pid: 30405
2016/12/14 14:48:45 [DEBUG] executor: unable to create new process with pid: 30405
2016/12/14 14:48:46 [DEBUG] executor: unable to create new process with pid: 30405
2016/12/14 14:48:47 [DEBUG] executor: unable to create new process with pid: 30405

Thanks!

### PR DESCRIPTION
**Pull request by diptanu**
WIP: Tests needs to be fixed. PR for running tests on Travis.

Fixes #2106

### CODE REVIEW

File: client/driver/plugins.go [hunk 1]
```diff
@@ -14,15 +17,18 @@ var HandshakeConfig = plugin.HandshakeConfig{
...
 }
 
-func GetPluginMap(w io.Writer) map[string]plugin.Plugin {
+func GetPluginMap(w io.Writer, logLevel string) map[string]plugin.Plugin {
 	e := new(ExecutorPlugin)
-	e.logger = log.New(w, "", log.LstdFlags)
+	filter := &logutils.LevelFilter{
+		Levels:   []logutils.LogLevel{"TRACE", "DEBUG", "INFO", "WARN", "ERR"},
+		MinLevel: logutils.LogLevel(strings.ToUpper(logLevel)),
+		Writer:   ioutil.Discard,
```
Comment (dadgar) [inline client/driver/plugins.go]: Doesn't the Discard make all logs disappear

File: client/driver/plugins.go [hunk 2]
```diff
@@ -14,15 +17,18 @@ var HandshakeConfig = plugin.HandshakeConfig{
...
+	}
+
+	e.logger = log.New(filter, "", log.LstdFlags)
```
Comment (dadgar) [inline client/driver/plugins.go]: `log.New(logOutput, "", log.LstdFlags|log.Lmicroseconds)` to be like the client. Easier to correlate stuff when debugging

File: command/executor_plugin.go [hunk 3]
```diff
@@ -25,19 +27,23 @@ func (e *ExecutorPluginCommand) Synopsis() string {
 }
 
 func (e *ExecutorPluginCommand) Run(args []string) int {
-	if len(args) == 0 {
-		e.Ui.Error("log output file isn't provided")
+	if len(args) != 1 {
+		e.Ui.Error("log output file and log level are not provided")
```
Comment (dadgar) [inline command/executor_plugin.go]: `"json configuration not provided"`
