### PR TITLE
Services should not require a port

### LINKED ISSUE #3673: `port label not found` error in case when ports are not needed
### Nomad version
Nomad v0.7.1-rc1 (b81a2b64e659d297b0d90ef6003b8af8e5edb578)

### Issue
Some of our jobs are don't bind any ports.
But with the latest version we started to get error:
```
unable to get address for service "job_name": invalid port "": port label not found
```
It seems that all work fine before this PR: https://github.com/hashicorp/nomad/pull/3619

### Job file (if appropriate)
```
job "test-job" {
  datacenters = ["staging"]
  type = "service"

  update {
    max_parallel = 1
    min_healthy_time = "10s"
    healthy_deadline = "3m"
  }

  group "test-job" {
    count = 1
    restart {
      attempts = 10
      interval = "5m"
      delay = "20s"
      mode = "delay"
    }

    task "test-job" {
      driver = "docker"
      user = "test-user"
      config {
        image = "test-image"
        force_pull = true
        network_mode = "host"
      }

      env {
        APP_ENV = "staging"
      }

      resources {
        cpu    = 500
        memory = 128
      }

      service {
        name = "test-job"
        tags = ["test-job", "staging"]
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by schmichael**
Fixes #3673

### CODE REVIEW

File: nomad/structs/structs.go [hunk 1]
```diff
@@ -3131,7 +3131,7 @@ func (s *Service) Validate() error {
 	}
 
 	for _, c := range s.Checks {
-		if s.PortLabel == "" && c.RequiresPort() {
+		if s.PortLabel == "" && c.PortLabel == "" && c.RequiresPort() {
 			mErr.Errors = append(mErr.Errors, fmt.Errorf("check %s invalid: check requires a port but the service %+q has no port", c.Name, s.Name))
```
Comment (dadgar) [inline nomad/structs/structs.go]: Shouldn't this say neither the check or service specify the port

File: nomad/structs/structs_test.go [hunk 2]
```diff
@@ -1309,23 +1345,60 @@ func TestTask_Validate_Service_Check_AddressMode(t *testing.T) {
...
+					{
+						Name:     "empty-is-not-ok",
+						Type:     "tcp",
+						Interval: time.Second,
+						Timeout:  time.Second,
+					},
+				},
+			},
+			ErrContains: `check requires a port but the service "empty-address-3673-fails" has no port`,
+		},
```
Comment (dadgar) [inline nomad/structs/structs_test.go]: Can we have a test w/ no checks and no port label
