### PR TITLE
Fix regression with requiring docker auth email

### LINKED ISSUE #5412: Docker registry auth no longer working in 0.9 beta
### Nomad version
Nomad v0.9.0-beta3 (2f55f78b21a5e55ab122f2c1e1ed1ec21fde9566)

### Operating system and Environment details
Ubuntu 16.04.5 LTS (amd64)
Docker version 18.09.3, build 774a1f4

### Issue
We are testing the latest 0.9 beta as we are keen to start using the new GPU functionality. I have found that basic authentication has stopped working for us with private docker hub images and am unsure if this has been caused by the new nomad version or by a new docker version (or something else).

This was all working with nomad 0.8.x so any help identifying the problem would be much appreciated!

### Reproduction steps
Run a job using the docker driver and a private image with basic auth. We are using the `dns_servers` option so that the container can resolve addresses using consul on the host - I don't believe this should impact the docker driver resolving `docker.io`.

### Nomad Client logs (if appropriate)
```
Failed to pull `docker.io/<dockerhub_org>/keycloak:<image tag>`: API error (404): pull access denied for <dockerhub_org>/keycloak, repository does not exist or may require 'docker login'
```

### Job file (if appropriate)
```
task "keycloak" {
    driver = "docker"

    config {
        force_pull = true
        dns_servers = [ "172.17.0.1" ]
        image = "docker.io/<dockerhub_org>/keycloak:<image tag>"
        auth {
            username = "hardcoded_username"
            password = "hardcoded_password"
        }
    }
}
```
Removing `docker.io/` from the image produces the same behaviour.

### PR DESCRIPTION
**Pull request by preetapan**
Fixes #5412 

In 0.8.7 we looked for a overall non empty config. This fixes a bug in 0.9 beta3 where we checked for email being non empty. Instead, this only returns nil if all auth fields are empty.

### CODE REVIEW

File: drivers/docker/driver_test.go [hunk 1]
```diff
@@ -1664,6 +1664,55 @@ func TestDockerDriver_AuthConfiguration(t *testing.T) {
 	}
 }
 
+func TestDockerDriver_AuthFromTaskConfig(t *testing.T) {
+	if !tu.IsCI() {
+		t.Parallel()
+	}
+	testutil.DockerCompatible(t)
```
Comment (notnoop) [inline drivers/docker/driver_test.go]: This unit test doesn't require Docker

File: drivers/docker/driver_test.go [hunk 2]
```diff
@@ -1664,6 +1664,55 @@ func TestDockerDriver_AuthConfiguration(t *testing.T) {
...
+				Email:         "foo@bar.com",
+				ServerAddress: "www.foobar.com",
+			},
+		},
+		{
+			Auth: DockerAuth{
+				Username:   "foo",
+				Password:   "bar",
+				ServerAddr: "www.foobar.com",
+			},
```
Comment (notnoop) [inline drivers/docker/driver_test.go]: would be useful to note what these cases cover; particularly how the third case is missing Email field.
