### PR TITLE
consul/connect: in-place update service definition when connect upstreams are modified

### LINKED ISSUE #8754: System jobs require restart after adding upstreams
### Nomad version
0.12.3

### Issue

When a proxy upstream is added to a job of `type = "system"`, the container is not restarted but the new configuration is not taken into account. The new upstream is unreachable from the container and we need to restart the job to make it work.
When the job type is set to `service` everything works as expected: the container is not restarted and the new upstream can be reached.

### Reproduction steps

1. Run job `api1`
2. Run job `api2` without upstream
3. Run job `api2` with upstream to `api1` (uncomment the upstream part of the following job)
4. Enter the job `api2` container and try to curl `api1`: `curl http://127.0.0.1:7777`

### Job file (if appropriate)

`api1`
```
job "api" {
  datacenters = ["dc1"]

  group "api1" {

    count = 1

    network {
      mode ="bridge"
      port "http" {
        to     = 8080
      }
    }

    service {
      name = "api1"
      port = 8080

      connect {
        sidecar_service {}
      }

      check {
        name     = "alive"
        port     = "http"
        type     = "http"
        path     = "/"
        interval = "10s"
        timeout  = "2s"
      }
    }

    task "api1" {
      driver = "docker"

      env {
        PORT = 8080
        NAME = "api1"
      }

      config {
        image = "patatra/test-connections-server:latest"
      }
    }
  }
}
```

`api2`
```
job "api2" {
  datacenters = ["dc1"]
  type = "system"

  group "api2" {

    network {
      mode ="bridge"
      port "http" {
        to     = 8081
      }
    }

    service {
      name = "api2"
      port = 8081

      check {
        name     = "alive"
        port     = "http"
        type     = "http"
        path     = "/"
        interval = "10s"
        timeout  = "2s"
      }

      connect {
        sidecar_service {
          proxy {
//            upstreams {
//              destination_name = "api1"
//              local_bind_port = 7777
//            }
          }
        }
      }
    }

    task "api2" {
      driver = "docker"

      env {
        PORT = 8081
        NAME = "api2"
      }

      config {
        image = "patatra/test-connections-server:latest"
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by shoenig**
This PR fixes a bug where modifying the upstreams of a Connect sidecar proxy
would not result Consul applying the changes, unless an additional change to
the job would trigger a task replacement (thus replacing the service definition).

The fix is to check if upstreams have been modified between Nomad's view of the
sidecar service definition and the service definition for the sidecar that is
actually registered in Consul during service reconciliation. 

Fixes #8754

### CODE REVIEW

File: command/agent/consul/service_client.go [hunk 1]
```diff
@@ -248,9 +248,74 @@ func sidecarTagsDifferent(parent, wanted, sidecar []string) bool {
...
+				return true
+			case A.DestinationName != B.DestinationName:
+				return true
+			case A.LocalBindAddress != B.LocalBindAddress:
+				return true
+			case A.LocalBindPort != B.LocalBindPort:
+				return true
+			case A.MeshGateway.Mode != B.MeshGateway.Mode:
+				return true
+			case !reflect.DeepEqual(A.Config, B.Config):
```
Comment (tgross) [inline command/agent/consul/service_client.go:300]: It looks like this big switch/case is a performance optimization to avoid doing `reflect.DeepEqual` on the `api.Upstream` if we can avoid it, but from a maintenance perspective this seems like it's brittle. If we upgrade the Consul library and they add new fields this check will silently break. 

(Alternately, is there maybe a way we can write a unit test that automatically gives us non-default values for all fields so that we have a breaking test on upgrade? I don't know of one off the top of my head but that would be really cool.)

**Review by tgross — APPROVED** [review]
LGTM with the one caveat about maintenance.

File: command/agent/consul/service_client.go (hunk 1 above)
Comment (shoenig) [reply command/agent/consul/service_client.go:300]: I think  you just gave me an excuse to play around with https://blog.golang.org/fuzz-beta :slightly_smiling_face: 

Using `reflect.DeepEqual` is similarly dangerous, for example it always returns false if a function is added to the struct fields:
https://play.golang.org/p/Yfu4d2RdTKd
Really thought the only _correct_ thing to do here would be fore Consul to provide equality methods in their `api` package - they are the ones who define what the thing is and know how it compares.

Comment (tgross) [reply command/agent/consul/service_client.go:300]: Totally agreed there.
