### PR TITLE
heartbeat: Handle transitioning from disconnected to down

### LINKED ISSUE #12470: disconnected clients: Node does not transition to `down` after last `max_client_disconnect` expires
### Nomad version

Nomad 1.3.0-beta

### Operating system and Environment details

1 Server
2 Clients

### Issue

When the last job configured with a `max_client_disconnect` value expires, the node should transition from `disconnected` to `down` if it is still not able to heartbeat. 

### Reproduction steps

- Create a job that ensures allocations are spread across multiple clients. For testing, define a short `max_client_disconnect` duration.
- Once the jobs are running, simulate a network drop on one of the clients.
- Notice the allocation on the lost client transitions to unknown.
- After the timeout passes, the allocation transitions to lost.
- Run `nomad node status`.

#### Expected Result

Once the last alloc expires, the node should transition to `down`. 

#### Actual Result

The node status is still `disconnected`.

### Job file (if appropriate)

```hcl
job "spread" {
  datacenters = ["dc1"]

  group "cache" {
    count = 2

    max_client_disconnect = "10s"
    
    spread {
      attribute = "${node.datacenter}"
    }

    network {
      port "db" {
        to = 6379
      }
    }

    task "redis" {
      driver = "docker"

      config {
        image = "redis:3.2"

        ports = ["db"]
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by DerekStrickland**
Closes #12470

This PR updates the `nodeHeartbeater` to handle transitioning a client from `disconnected` to `down`

It does this by:

- Updating `node_endpoint` to allow `disconnect` updates to participate in the heartbeat timer process
- Checking to see if the node has any pending reconnectable allocations on each heartbeat
- Setting the node status to `down` when there are no more pending reconnectable allocations

### CODE REVIEW

File: nomad/heartbeat.go [hunk 1]
```diff
@@ -172,21 +174,44 @@ func (h *nodeHeartbeater) invalidateHeartbeat(id string) {
...
 	if err != nil {
 		h.logger.Error("error retrieving allocs by node", "error", err)
-		return false
+		return false, false
 	}
 
 	now := time.Now().UTC()
+	// Check if the node has any allocs that are configured with max_client_disconnect,
+	// and if so, whether it has pending reconnects. If one alloc isn't yet expired
+	// it still has pending reconnects.
```
Comment (tgross) [inline nomad/heartbeat.go:198]: I think this is more accurate in terms of the first conditional below?

```suggestion
	// Check if the node has any allocs that are configured with max_client_disconnect,
	// that are past the disconnect window, and if so, whether it has at least one alloc
	// that isn't yet expired.
```

File: nomad/heartbeat.go [hunk 2]
```diff
@@ -172,21 +174,44 @@ func (h *nodeHeartbeater) invalidateHeartbeat(id string) {
...
 	for _, alloc := range allocs {
-		if alloc.DisconnectTimeout(now).After(now) {
-			return true
+		if !canDisconnect && alloc.DisconnectTimeout(now).After(now) {
+			canDisconnect = true
+		}
+		if !hasPendingReconnects && alloc.DesiredStatus == structs.AllocDesiredStatusRun && !alloc.Expired(now) {
+			hasPendingReconnects = true
+			break
+		}
```
Comment (tgross) [inline nomad/heartbeat.go:208]: Is an alloc that meets the second case always guaranteed to be true for the first case? If not, breaking early creates an ordering problem where the order of allocs we iterate matters. If so, maybe we can make that relationship explicit here by moving this conditional under the first one? We know we can only hit the `hasPendingReconnects` once, so we can reduce it down to something like:

```go
var canDisconnect bool
for _, alloc := range allocs {
	if !canDisconnect && alloc.DisconnectTimeout(now).After(now) {
		canDisconnect = true
		if alloc.DesiredStatus == structs.AllocDesiredStatusRun && !alloc.Expired(now) {
			return true, true
		}
	}
}
return canDisconnect, false
```

Comment (DerekStrickland) [reply nomad/heartbeat.go:208]: We can't do exactly this. You can only have pending reconnects if you are configured with a disconnect. So yes, if something evaluates to true for the second case, then by definition it needs to evaluate true for the first. However, you've made me realize I'm conflating nodes with allocs here. I'll rework this and resubmit.

File: nomad/node_endpoint.go [hunk 3]
```diff
@@ -487,7 +487,10 @@ func (n *Node) UpdateStatus(args *structs.NodeUpdateStatusRequest, reply *struct
 
 	// Check if we should trigger evaluations
 	transitionToReady := transitionedToReady(args.Status, node.Status)
-	if structs.ShouldDrainNode(args.Status) || transitionToReady || args.Status == structs.NodeStatusDisconnected {
+	if structs.ShouldDrainNode(args.Status) ||
+		transitionToReady ||
+		// Don't create evals if heartbeat is just resetting the timer.
+		(args.Status == structs.NodeStatusDisconnected && node.Status != structs.NodeStatusDisconnected) {
```
[the remark this answers is not in the document]
Comment (DerekStrickland) [reply nomad/node_endpoint.go:493]: I updated this to share the logic that `Register` uses. Let me know if you think this refactoring makes sense. It required making a copy of the node before updating to conform to the interface of that function, but I think maybe that's worth it for consistency.

File: nomad/node_endpoint.go [hunk 4]
```diff
@@ -486,8 +488,7 @@ func (n *Node) UpdateStatus(args *structs.NodeUpdateStatusRequest, reply *struct
 	}
 
 	// Check if we should trigger evaluations
-	transitionToReady := transitionedToReady(args.Status, node.Status)
-	if structs.ShouldDrainNode(args.Status) || transitionToReady || args.Status == structs.NodeStatusDisconnected {
+	if shouldCreateNodeEval(originalNode, node) {
```
Comment (tgross) [inline nomad/node_endpoint.go:491]: I think we took this refactoring a little too far.

`Register` and `UpdateStatus` are distinct because register includes the full fingerprint. Folding the check for status updates together with the check for the register code path has several disadvantages:
* We're doing a bunch of resources checks that are meaningless because they'll never have changed as part of an `UpdateStatus` call
* We have to copy the `Node`, which is extra allocations. (And I'm not even sure why a check for changes mutates the object?)
* We've introducing implicit coupling between fingerprinting and `UpdateStatus` that didn't exist before and can introduce future bugs if we want to change the fingerprinting conditionals.

File: nomad/heartbeat.go [hunk 5]
```diff
@@ -172,21 +174,46 @@ func (h *nodeHeartbeater) invalidateHeartbeat(id string) {
...
 
 	now := time.Now().UTC()
+	// Check if the node has any allocs that are configured with max_client_disconnect,
+	// that are past the disconnect window, and if so, whether it has at least one
+	// alloc that isn't yet expired.
+	nodeCanDisconnect := false
 	for _, alloc := range allocs {
-		if alloc.DisconnectTimeout(now).After(now) {
-			return true
+		allocCanDisconnect := alloc.DisconnectTimeout(now).After(now)
```
Comment (tgross) [inline nomad/heartbeat.go:201]: Making the distinction here between `nodeCanDisconnect` and `allocCanDisconnect` is 👍

**Review by tgross — CHANGES_REQUESTED** [review]

File: nomad/node_endpoint.go (hunk 4 above)
Comment (DerekStrickland) [reply nomad/node_endpoint.go:491]: Gotcha. Exactly the feedback I was looking for. I'll back this up a level.

File: nomad/node_endpoint.go [hunk 6]
```diff
@@ -486,8 +486,8 @@ func (n *Node) UpdateStatus(args *structs.NodeUpdateStatusRequest, reply *struct
 	}
 
 	// Check if we should trigger evaluations
-	transitionToReady := transitionedToReady(args.Status, node.Status)
-	if structs.ShouldDrainNode(args.Status) || transitionToReady || args.Status == structs.NodeStatusDisconnected {
+	if structs.ShouldDrainNode(args.Status) ||
```
Comment (DerekStrickland) [inline nomad/node_endpoint.go:489]: @tgross  How does this look?

Comment (tgross) [reply nomad/node_endpoint.go:489]: LGTM!

**Review by tgross — APPROVED** [review]
