### PR TITLE
[ui] Fixes a bug for first-time SecVars users on namespaces

### LINKED ISSUE #13949: Bug:  We need to figure out which namespace to check on the `/variables` view to check if a user has access to create a variable at the root level.

### PR DESCRIPTION
**Pull request by philrenaud**
Resolves #13949 and #14061

Makes the empty-variables-list link adhere to the same rules as the create button
Adds a more permissive check when you're on * namespace and * path

Added a TODO for handling * namespace on a specific path. We're being too restricted about that currently and should consider modifying allPaths to account for checking against multiple namespaces at once.

### CODE REVIEW

**Review by ChaiWithJai — APPROVED** [review]
This has TODO comments and more lines of comments than code for the core logic. I'm just "approving" to make sure I'm not blocking you from doing things your way. But IMHO this should remain in draft.

File: ui/app/abilities/variable.js [hunk 1]
```diff
@@ -101,10 +109,23 @@ export default class Variable extends AbstractAbility {
 
   @computed('path', 'allPaths')
```
Comment (ChaiWithJai) [inline ui/app/abilities/variable.js:110]: `blocking` you're missing declaring dependencies here.
