### PR TITLE
Use bind address for consul checks

### LINKED ISSUE #1574: Consul service health check defaults to advertise address
### Nomad version
`Nomad v0.4.0`

### Operating system and Environment details
Ubuntu Xenial

### Issue
The consul services published by nomad set the service address to the advertise address. This is expected behavior, however the health check which is registered against that service is also registered against the service address.

This is unexpected because often times the service address is unreachable from the localhost. Since the Consul agent is expected to run locally, and the default address is on the loopback adapter, it makes sense for the default endpoint of all associated ServiceChecks to be configured against the bind address as opposed to the advertise address. Additionally, the address for the ServiceCheck is not configurable.

### Reproduction steps
1. Install Nomad
1. Configure Addresses with the interface address
1. Configure Advertise with unreachable IP
1. Start Nomad

Registered consul checks will fail against unreachable service address, even though Nomad is healthy.

### Suggested Solution
Configure all ServiceChecks with endpoint address and port equal to the bind address (config.Addresses.HTTP and so on)

### PR DESCRIPTION
**Pull request by dadgar**
Fixes #1574 

Thank you @evan2645 for the original PR #1600

### CODE REVIEW

File: nomad/structs/config/consul.go [hunk 1]
```diff
@@ -33,6 +33,10 @@ type ConsulConfig struct {
 	// services with Consul.
 	AutoAdvertise bool `mapstructure:"auto_advertise"`
 
+	// ChecksUseAdvertise specifies that Consul checks should use advertise
+	// address instead of bind address
+	ChecksUseAdvertise bool `mapstructure:"checks_use_advertise"`
```
Comment (diptanu) [inline nomad/structs/config/consul.go]: Add this to the list of valid tags in `config_parse.go`
