### PR TITLE
Consul Catalog Integration Fixes

### LINKED ISSUE #4537: Service maintenance mode check removed by nomad agent from consul
### Nomad & Consul version
`Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)`
`Consul v1.2.0
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)`

### Operating system and Environment details
Server - Windows 2016 Datacenter, run on VM
Agent - Windows 2016 Datacenter, inside container microsoft/windowsservercore:latest.

### Issue
Service maintenance mode check removed by nomad agent from consul. It is probably a bug related to #4170.

We have the following setup:
nomad agent and consul agent are installed on the same VM.
When running nomad job, it is successfully registered a service and it's health checks and it is visible from consul agent and server.
Then, we switch the service registered by nomad into maintenance mode, by directly calling the agent api (or running by command line).
```
consul maint  -enable -service=:_nomad-task-7jnnnudilvhc7up4z6yjvm2vjwx576jw -reason "Testing"
```
For some time the service is shown in consul as it should be - in maintenance mode, then it is switched back to normal state.
Studying the logs of both nomad and consul agents show explicitly that consul agent receives a request from localhost to de-register service maintenance health check:
```
018/07/27 10:44:12 [INFO] agent: Service "_nomad-task-7jnnnudilvhc7up4z6yjvm2vjwx576jw" entered maintenance mode
2018/07/27 10:44:12 [DEBUG] agent: Service "_nomad-task-7jnnnudilvhc7up4z6yjvm2vjwx576jw" in sync
2018/07/27 10:44:12 [DEBUG] agent: Check "_service_maintenance:_nomad-task-7jnnnudilvhc7up4z6yjvm2vjwx576jw" in sync
2018/07/27 10:44:12 [DEBUG] http: Request PUT /v1/agent/service/maintenance/_nomad-task-7jnnnudilvhc7up4z6yjvm2vjwx576jw?enable=true&reason=Testing (42.0073ms) from=127.0.0.1:62209
...
...
2018/07/27 10:44:40 [DEBUG] http: Request PUT /v1/agent/check/deregister/_service_maintenance:_nomad-task-7jnnnudilvhc7up4z6yjvm2vjwx576jw (21.0081ms) from=127.0.0.1:52544
```

And it looks like this is triggered by nomad agent:
Corresponding long from nomad agent:
```
2018/07/27 10:44:39.764948 [DEBUG] http: Request GET /v1/agent/health?type=client (997.6µs)
2018/07/27 10:44:40.152101 [DEBUG] consul.sync: registered 0 services, 0 checks; deregistered 0 services, 1 checks
``` 
#### I have a feeling that nomad should not remove maintenance mode checks from services in consul in this case, though the rest should be synced as it works now according to #4170 . 
The tests also showed that If node as a whole is set to maintenance, then it remains in this state until explicitly removed from maintenance mode.

P.S. There is no any traces at all in consul server and nomad servers logs.

### Reproduction steps
0. Run consul agent and nomad agent on the same VM. Point nomad agent to consul on localhost: `consul-address=127.0.0.1:8500`. It is not matter will consul run in dev mode or consul agent will connect to the server.
1. Run nomad job with service registration
2. Set the registered (by nomad) service into maintenance mode
3. After some time the maintenance mode health-check is automatically removed

### Nomad Client logs (if appropriate)
```
2018/07/27 10:44:39.764948 [DEBUG] http: Request GET /v1/agent/health?type=client (997.6µs)
2018/07/27 10:44:40.152101 [DEBUG] consul.sync: registered 0 services, 0 checks; deregistered 0 services, 1 checks
```

### LINKED ISSUE #4566: Promoting a canary causes its service check to immediately become critical
### Nomad version
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)
Consul v1.2.0

### Operating system and Environment details
CentOS Linux release 7.5.1804 (Core) (EC2)

### Issue

Our engineering teams have noticed that their web apps sometimes brown out whenever we promote canaries. Many of these apps are very small, and we only run two containers. Therefore in our update stanza we set `canary = 2` to do a blue-green update, wait for the canaries to become healthy, and then promote them. We use consul and consul-template to add services to our load balancers so that as new services become healthy, they're entered into the catalog and consequently into the load balancer config.

What we've noticed is that at the moment of promotion, suddenly the service seems to disappear from the load balancer. The 2 old containers are removed from the consul catalog because we've just promoted the job, and that's expected. But the new 2 containers also seem to disappear, even though they were healthy a moment ago. They'll then re-appear a few seconds later, but not before we drop a bunch of traffic on the floor.

As far as I can tell this is because when a nomad task is promoted, it service definition in consul is _replaced._ This is kind of bad since all consul services start out critical by default.

### Reproduction steps

You can watch this in real-time if nomad and consul are both running. Deploy a job to nomad which will register with consul, and then deploy an update with a canary. You can look at service definitions in Consul with:

```
$ curl -Ss 127.0.0.1:8500/v1/health/checks/training-wheels | egrep 'ServiceID|Status'
        "Status": "passing",
        "ServiceID": "_nomad-task-kigfngvz6escims3tgkv6wz774op3w5a",   << old container
        "Status": "passing",
        "ServiceID": "_nomad-task-zas7siokij4xhdj5bigqxhzuynixm2kf",   << new container
```

So far so good. As soon as the job is promoted, however:

```
$ curl -Ss 127.0.0.1:8500/v1/health/checks/training-wheels | egrep 'ServiceID|Status'
        "ServiceID": "_nomad-task-2rmpcuvevadkpuvvduwu6my33yxqoo3v",   << new container; also a new service definition
        "Status": "critical",
```

This is a new service definition in Consul, and therefore its healthcheck starts out critical. We have a couple of ways we can work around this but neither are appealing:

1. Deploy a single canary instead of blue-greening the whole thing. Not really desirable since this doubles deployment time. This isn't that great of a workaround for a service with only two allocations anyway, since it will roll over the second allocation the moment the first one becomes (temporarily) healthy.
1. Set `initial_status = "passing"` in the service definition. Potentially worse, since this means that unhealthy services will immediately start accepting traffic ("unhealthy" meaning an unready service, but also a completely broken service).

In other words we're in a pretty bad place right now.

### Job file (if appropriate)

A playground app of ours:

```
job "training-wheels" {

  datacenters = ["vagrant"]
  type = "service"

  update {
    max_parallel = 1
    min_healthy_time = "5s"
    healthy_deadline = "5m"
    health_check = "checks"
    auto_revert = true
    canary = 1
  }

  migrate {
    max_parallel = 1
    health_check = "checks"
    min_healthy_time = "5s"
    healthy_deadline = "5m"
  }

  group "training-wheels" {
    count = 1
    restart {
      attempts = 10
      interval = "5m"
      delay = "10s"
      mode = "delay"
    }

    task "training-wheels" {
      driver = "docker"
      config {
        image = "redacted-repo/training-wheels:0.1.5"
        command = "/apps/shinatra.sh"
        hostname = "training-wheels"
        dns_servers = ["172.17.0.1"]
        port_map {
          http = 8080
        }
      }

      shutdown_delay = "45s"

      resources {
        cpu    = 250
        memory = 128
        network {
          mbits = 100
          port "http" {}
        }
      }

      service {
        name = "training-wheels"
        port = "http"
        tags = [
          "0.1.5",
          "backend",
          "http",
          "microservice"
        ]
        check {
          name     = "healthcheck"
          type     = "http"
          port     = "http"
          path     = "/api/healthcheck"
          interval = "15s"
          timeout  = "10s"

          check_restart {
            limit = 3
            grace = "1m"
          }
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by endocrimes**
fixes #4566 
fixes #4537

The current implementation of Service Registration uses a hash of the nomad-internal state of a service to register it with Consul, this means that any update to the service invalidates this name and we then de-register, and recreate the service in Consul.

While this behavior slightly simplifies reasoning about service registration, this becomes problematic when we add consul health checks to a service. When the service is re-registered, so are the checks, which default to failing for at least one check period. This causes issues when a canary is promoted, as the old, stable allocs are immediately stopped, and the new ones updated, which causes a consul registration cycle and takes your service offline for one health check period.

This pull request introduces `v3` of the Nomad-Consul integration style that moves back to having a stable identifier for a service, and registers updates based on changes to the internal struct state and remote state.

## Notes

* There is currently a UX issue in Consul that means that when you update a Service's tags, its Checks will still return the ones they were registered against, however this does not effect the functionality of Consul or Nomad (https://github.com/hashicorp/consul/issues/5631).

* There is an outstanding Nomad bug where the consul reconciler races against task restoration on a host, which means when restarting or updating a client, services will be removed from consul and re-registered, causing a 1-health-check-period status flap. This PR does not attempt to solve that bug as it will require a larger refactor of the client startup flow to be reliable, thus this PR does not attempt to handle older registrations outside of removing them as expected.

### CODE REVIEW

**Comment by endocrimes** [comment]
Only travis job that's failing on push is the website and that seems unrelated.

File: command/agent/consul/client.go [hunk 1]
```diff
@@ -1082,14 +1110,14 @@ func makeAgentServiceID(role string, service *structs.Service) string {
...
 // Checks. This allows updates to merely compare IDs.
 //
-//	Example Service ID: _nomad-task-TNM333JKJPM5AK4FAS3VXQLXFDWOF4VH
+//	Example Service ID: _nomad-task-b4e61df9-b095-d64e-f241-23860da1375f-redis-http
 func makeTaskServiceID(allocID, taskName string, service *structs.Service, canary bool) string {
-	return nomadTaskPrefix + service.Hash(allocID, taskName, canary)
+	return fmt.Sprintf("%s%s-%s-%s", nomadTaskPrefix, allocID, taskName, service.Name)
 }
 
 // makeCheckID creates a unique ID for a check.
```
Comment (nickethier) [inline command/agent/consul/client.go]: could you add a comment of an example check ID? having it above for the service is really helpful I think
