### PR TITLE
docker: support group allocated ports and host_networks

### LINKED ISSUE #8488: docker and group level network
### Nomad version

```
Nomad v0.12.0 (8f7fbc8e7b5a4ed0d0209968faf41b238e6d5817)
```

### Operating system and Environment details

```
vagrant@linux:/opt/gopath/src/github.com/hashicorp/nomad$ cat /etc/os-release  | grep VERSION=
VERSION="18.04.4 LTS (Bionic Beaver)"
vagrant@linux:/opt/gopath/src/github.com/hashicorp/nomad$ uname -a
Linux linux 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Networks `eth0` and `eth2`:

```
$ ip addr show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:81:14:5e brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 76021sec preferred_lft 76021sec
    inet6 fe80::a00:27ff:fe81:145e/64 scope link
       valid_lft forever preferred_lft forever
$ ip addr show eth1
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:2b:28:6c brd ff:ff:ff:ff:ff:ff
    inet 10.199.0.200/24 brd 10.199.0.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe2b:286c/64 scope link
       valid_lft forever preferred_lft forever
```
### Issue

When specifying network in the group level, and assign portings, docker container fail to start with `Trying to map ports but no network interface is available`.

### Reproduction steps

1. Spin up a nomad agent configured with a host_network
2. submit the job
3. watch the allocation fail with "Trying to map ports but no network interface is available" error like in

```
$ nomad alloc status 7faaf70a
ID                     = 7faaf70a-ab1a-9d4a-dcfa-fa78f2b11305
Eval ID                = 2931e497
Name                   = lb-example.lb-example[0]
Node ID                = 6fcb0b06
Node Name              = nomad-devagent
Job ID                 = lb-example
Job Version            = 0
Client Status          = failed
Client Description     = Failed tasks
Desired Status         = run
Desired Description    = <none>
Created                = 5s ago
Modified               = 1s ago
Deployment ID          = 31ec75b9
Deployment Health      = unhealthy
Reschedule Eligibility = 25s from now

Allocation Addresses
Label  Dynamic  Address
*http  yes      10.199.0.200:80

Task "lb-example" is "dead"
Task Resources
CPU      Memory   Disk     Addresses
100 MHz  300 MiB  300 MiB

Task Events:
Started At     = N/A
Finished At    = 2020-07-21T23:39:48Z
Total Restarts = 0
Last Restart   = N/A

Recent Events:
Time                  Type             Description
2020-07-21T23:39:50Z  Killing          Sent interrupt. Waiting 5s before force killing
2020-07-21T23:39:48Z  Alloc Unhealthy  Unhealthy because of failed task
2020-07-21T23:39:48Z  Not Restarting   Error was unrecoverable
2020-07-21T23:39:48Z  Driver Failure   Failed to create container configuration for image "redis:3.2" ("sha256:87856cc39862cec77541d68382e4867d7ccb29a85a17221446c857ddaebca916"): Trying to map ports but no network interface is available
2020-07-21T23:39:48Z  Task Setup       Building Task Directory
2020-07-21T23:39:48Z  Received         Task received by client
```

### Job file (if appropriate)

```hcl
job "lb-example" {
  datacenters = "dc1"

  group "lb-example" {
    network {
      port "http" {
        static       = "80"
        host_network = "lb"
      }
    }

    task "lb-example" {
      driver = "docker"
      config {
        image = "redis:3.2"
        port_map {
          http = 80
        }

      }
    }
  }
}
```

Client config:
```
log_level = "TRACE"
enable_debug = true
datacenter = "dc1"
data_dir = "/tmp/nomad-data-dir"

client {
  enabled = true

  host_network "lb" {
    interface = "eth2"
  }

  servers = ["127.0.0.1:4647"]
  options = {
    "driver.raw_exec.enable" = "1"
    "docker.image.delay" = "10s"
  }
}

server {
  enabled          = true
  bootstrap_expect = 1
}

### PR DESCRIPTION
**Pull request by nickethier**
This PR correctly plumbs through allocated group ports to tasks and adds a new `ports` field to the docker driver to support docker native port mapping with group allocated ports.

Since group ports are shared among all tasks, the docker tasks needs to specify which ports it needs to map. This differs from the old `port_map` driver config in two ways:
1. Task ports where always mapped and `port_map` was just used to override individual port destinations. With the new `ports` field, only specified labels are mapped.
1. `ports` does not include the container port like `port_map` does because it can be set in the individual `port { }` stanzas as the `to` field. 

Multi-Interface host networks are also supported with this, setting the host IP correctly based on the configured `host_network` field of the port.

Ex.
```
group "example" {
  network {
    port "http" { }
    port "redis" {
      to = 6379
    }
  }
  task "example"
    driver = "docker"
    config {
      ports = ["http", "redis"]
    }
  }
}
```

fixes #8488

### CODE REVIEW

File: drivers/docker/driver.go [hunk 1]
```diff
@@ -1032,61 +1032,39 @@ func (d *Driver) createContainerConfig(task *drivers.TaskConfig, driverConfig *T
 	}
 
 	// Setup port mapping and exposed ports
-	if len(task.Resources.NomadResources.Networks) == 0 {
-		if len(driverConfig.PortMap) > 0 {
-			return c, fmt.Errorf("Trying to map ports but no network interface is available")
+	ports := newPublishedPorts(logger)
+	switch {
+	case task.Resources.Ports != nil && len(driverConfig.Ports) > 0:
```
Comment (notnoop) [inline drivers/docker/driver.go:1037]: This supports the case where only one source of ports is specified?  Should we report an error, if we notice multiple sources as well?

Comment (nickethier) [reply drivers/docker/driver.go:1037]: Idk if we should prevent the task from running since one of the fields is deprecated. It is documented in the docs that the two fields are incompatible.

Comment (Legogris) [reply drivers/docker/driver.go:1037]: Shouldn't a deprecated incompatible spec result in the job spec being invalid? I can see this easily tripping up people. Or at least log a warning?

Comment (nickethier) [reply drivers/docker/driver.go:1037]: We could log a warning but I do t think that would help the user if they have to go digging through client logs. With driver plugins, the driver configuration can’t be validated until runtime. There’s an open issue somewhere to explore fixing that but it’s an in-depth change.

So our only option is to return an error and fail the allocation which is totally reasonable. I can argue either way 😅

Comment (Legogris) [reply drivers/docker/driver.go:1037]: Makes sense.

This is just my 5c as a user but I'd much rather have unsupported things fail on first attempt with an explanatory error message than scratching my head about why it's not working as intended ^^

Comment (notnoop) [reply drivers/docker/driver.go:1037]: IIUC it's invalid if both group level network as well as task level network is specified?  Is that true?  If so, we can validate early on job submission regardless of driver?

For driver configuration warnings, we can also emit a TaskEvent, in leu of a log line.  It'll be visible with `nomad {alloc|job} status`, though I agree it's still not very discoverable.
