### PR TITLE
Fix old services not getting removed from consul on update

### LINKED ISSUE #1661: Updating service tags appends instead of replaces in consul
When updating tags from `["foo", "bar"]` to `["foo", "x"]`, `x` will be appended and `bar` won't be removed in consul. So the result is `["foo", "bar", "x"]` instead of `["foo", "x"]`

### Nomad version
0.4 - master (152c11d657c1fec4cbc6857c4218a5fc8121340f)
### Issue
Original submisison:

> Hi, I'm using Nomad 0.4 to run some jobs. Is it expected that when you update a service (Consul) tag, the old tag is not removed but instead appended to the service?

### Reproduction steps

1. Start consul + nomad
2. run example.nomad
3. Change `cache` tag to `cache2` tag
4. run example.nomad
5. Observe tags in consul include both `cache` and `cache2`

### PR DESCRIPTION
**Pull request by schmichael**
Fixes #1661 

I'm not terribly happy with the thoroughness of my tests, so feel free to suggest improvements there.

Also includes a tiny unrelated change I made while meandering through the code base:

* Remove unused embedded lock on ExecContext 53d7dfb

### CODE REVIEW

File: command/agent/consul/syncer.go [hunk 1]
```diff
@@ -174,6 +174,8 @@ func NewSyncer(consulConfig *config.ConsulConfig, shutdownCh chan struct{}, logg
 		trackedChecks:     make(map[consulCheckID]*consul.AgentCheckRegistration),
 		checkRunners:      make(map[consulCheckID]*CheckRunner),
 		periodicCallbacks: make(map[string]types.PeriodicCallback),
+		// default noop implementation of addrFinder
+		addrFinder: func(string) (string, int) { return "", 0 },
```
Comment (schmichael) [inline command/agent/consul/syncer.go]: Not sure if this is a safe or wise thing to do.

File: command/agent/consul/syncer_test.go [hunk 2]
```diff
@@ -95,148 +110,136 @@ func TestCheckRegistration(t *testing.T) {
...
+	agentServices, err := cs.queryAgentServices()
+	if err != nil {
+		t.Fatalf("error querying consul services: %v", err)
+	}
+	if len(agentServices) != 3 {
+		t.Fatalf("expected 3 services in consul but found %d:\n%#v", len(agentServices), agentServices)
+	}
+
+	found := 0
+	for _, s := range cs.flattenedServices() {
```
Comment (diptanu) [inline command/agent/consul/syncer_test.go]: Can we use `reflect.DeepEquals` here to check whether the agentServices are what we expect them to be? The assertion logic would be simpler.

Comment (schmichael) [inline command/agent/consul/syncer_test.go]: Hm, good call. Right now I'm just asserting the internal syncer state. I'll add comparisons of internal state against `queryAgentServices` too to make sure everything is consistent.

Comment (schmichael) [inline command/agent/consul/syncer_test.go]: Sadly queryAgent and fllatenedServices use different types, so I couldn't just DeepEquals.

Added the checks manually because they're important.

File: command/agent/consul/syncer.go [hunk 3]
```diff
@@ -355,7 +376,12 @@ func (c *Syncer) Shutdown() error {
 	}
 
 	// De-register all the services from Consul
-	for serviceID := range c.trackedServices {
+	services, err := c.queryAgentServices()
```
Comment (dadgar) [inline command/agent/consul/syncer.go]: I would change the comment above:

`// De-register all services registered by this syncer from Consul`

File: command/agent/consul/syncer.go [hunk 4]
```diff
@@ -355,7 +376,12 @@ func (c *Syncer) Shutdown() error {
...
+	if err != nil {
+		c.logger.Printf("[WARN] consul.syncer: failed to register services due to error: %v", err)
```
Comment (dadgar) [inline command/agent/consul/syncer.go]: This message is wrong

File: command/agent/consul/syncer_test.go [hunk 5]
```diff
@@ -95,148 +110,157 @@ func TestCheckRegistration(t *testing.T) {
...
-// 	// 		mErr.Errors = append(mErr.Errors, fmt.Errorf("service ID %q not synced", configuredService.ServiceID))
-// 	// 	}
-// 	// }
-// 	return mErr.ErrorOrNil()
-// }
-
-func checksPresent(t *testing.T, checkIDs []string, syncer *Syncer) error {
-	var mErr multierror.Error
-	checks, err := syncer.client.Agent().Checks()
+	agentServices, err := cs.queryAgentServices()
```
Comment (dadgar) [inline command/agent/consul/syncer_test.go]: Hmm are we biasing the test in our favor by using this? Since that does the filter?

Comment (schmichael) [inline command/agent/consul/syncer_test.go]: I changed the test above to not rely on this method's filtering.

I'd like to keep the helper method here and elsewhere since doing it manually everywhere seems like it would only add needless noise.

**Comment by dadgar** [comment]
LGTM
