### PR TITLE
e2e: run client/allocs metrics nightly tests vs Windows

### LINKED ISSUE #6825: Update OS-sensitive E2E tests to run on Windows
There are some critical existing e2e tests which we want to also run on Windows, because they exercise potentially OS-specific behaviors:

* [x] [`allocstats`](https://github.com/hashicorp/nomad/tree/master/e2e/allocstats) has been a known issue on Windows (https://github.com/hashicorp/nomad/pull/6775)
* [x] ~[`clientstate`](https://github.com/hashicorp/nomad/tree/master/e2e/clientstate) tests crash-safety~ (moved this to https://github.com/hashicorp/nomad/issues/6851 because this needs some non-Windows infra work as well)
* [ ] [`metrics`](https://github.com/hashicorp/nomad/tree/master/e2e/metrics) has been a known issue on Windows (https://github.com/hashicorp/nomad/pull/6850)

### PR DESCRIPTION
**Pull request by tgross**
Fixes #6825, and builds on the work done earlier in #6842

Adds Windows targets to the client/allocs metrics tests. Removes the `allocstats` test, which covers less than these tests and is now redundant.

Adds a firewall rule to our Windows instances so that the prometheus server can scrape the Nomad HTTP API for metrics. (Addresses my comment in https://github.com/hashicorp/nomad/pull/6842#discussion_r356840450)

---

Test output:

```
▶ go test -v ./e2e -run TestE2E/Metrics -count=1
=== RUN   TestE2E
=== RUN   TestE2E/Metrics
=== RUN   TestE2E/Metrics/*metrics.MetricsTest
=== RUN   TestE2E/Metrics/*metrics.MetricsTest/TestMetricsLinux
=== RUN   TestE2E/Metrics/*metrics.MetricsTest/TestMetricsWindows
--- PASS: TestE2E (31.56s)
    --- PASS: TestE2E/Metrics (31.56s)
        --- PASS: TestE2E/Metrics/*metrics.MetricsTest (31.47s)
            --- PASS: TestE2E/Metrics/*metrics.MetricsTest/TestMetricsLinux (21.56s)
            --- PASS: TestE2E/Metrics/*metrics.MetricsTest/TestMetricsWindows (8.71s)
PASS
ok      github.com/hashicorp/nomad/e2e  32.194s
```

### CODE REVIEW

File: e2e/metrics/metrics.go [hunk 1]
```diff
@@ -89,7 +89,28 @@ func (tc *MetricsTest) TestMetricsLinux(f *framework.F) {
...
-// Run workloads from and wait for allocations
+// TestMetricsWindows runs a collection of jobs that exercise alloc metrics.
+// Then we query prometheus to verify we're collecting client and alloc metrics
+// and correctly presenting them to the prometheus scraper.
+func (tc *MetricsTest) TestMetricsWindows(f *framework.F) {
+	t := f.T()
+	clientNodes, err := e2eutil.ListWindowsClientNodes(tc.Nomad())
+	require.Nil(t, err)
+	if len(clientNodes) == 0 {
+		t.Skip("no Windows clients")
```
Comment (notnoop) [inline e2e/metrics/metrics.go]: Should we check if we expect windows clients as well?  To avoid accidentally skipping tests in CI if windows clients unexpectedly fail to join cluster?

We ran into such case before where java driver tests were accidentally ignored.  Sadly, java driver tests and `javaCompatible` still doesn't protect against this problem.

Comment (tgross) [reply e2e/metrics/metrics.go]: I think that's a good idea but maybe not at the level of an individual test case. There are plenty of cases where you'll want to stand up a less-than-complete environment and run a subset of tests against it. There's some code in `framework/provisioning` that we're not currently using to define the test environment, and I'm planning on bringing that back into use. That should cover this kind of thing.
