### PR TITLE
Fix cpu_total_compute override

### LINKED ISSUE #2638: cpu_total_compute not working
If you have a question, prepend your issue with `[question]` or preferably use the [nomad mailing list](https://www.nomadproject.io/community.html).

If filing a bug please include the following:

### Nomad version
Output from `nomad version`
Nomad v0.5.6

### Operating system and Environment details
SUSE 12
s390x

### Issue
The client stanza variable cpu_total_compute is not working.   There is no MHZ variable in /proc/cpuinfo.  So the MHZ defaults to zero.  I wish to set that value using this cput_total_compute but it does not change the value.  I have also tried in a VM running in an x86 VM using VirtualBox without any luck.

### Reproduction steps
Create a client configuration with the value set.
client {
        enabled = true
        servers = ["x.x.x.x"]
        cpu_total_compute = 4200
}
Run nomad.  
nomad node-status --verbose <node_id>
cpu.totalcompute              = 0

### PR DESCRIPTION
**Pull request by schmichael**
Fixes #2638 

* Refactor some CPU fingerprinting code to make it more robust.
* Add a test for the total compute override
* Document the total compute attribute

### CODE REVIEW

File: client/fingerprint/cpu.go [hunk 1]
```diff
@@ -31,39 +31,47 @@ func (f *CPUFingerprint) Fingerprint(cfg *config.Config, node *structs.Node) (bo
...
 
-	node.Attributes["cpu.totalcompute"] = fmt.Sprintf("%.0f", tt)
+		if node.Resources == nil {
+			node.Resources = &structs.Resources{}
+		}
 
-	setResources(int(tt))
+		node.Resources.CPU = tt
+	} else {
+		f.logger.Printf("[INFO] fingerprint.cpu: cannot detect cpu total compute. "+
```
Comment (dadgar) [inline client/fingerprint/cpu.go]: Shouldn't this be an error? Nothing will be allocatable on the node otherwise?
