### PR TITLE
drainer: respect max parallel setting when draining

### LINKED ISSUE #25979: max_parallel ignored when draining multiple nodes
### Nomad version

Nomad v1.10.0
BuildDate 2025-04-09T16:40:54Z
Revision e26a2bd2acac2dcdcb623f4d293bac096beef478

### Operating system and Environment details

Ubuntu 24.04.2 LTS
aarch64

### Issue

I have a service job with count 2, and migrate.max_parallel 1. When we want to redeploy client nodes, we start new nodes, then drain the old ones. In this case we have two new nodes, and two old nodes. If the service is running with one instance on each node, and I drain both at the same time, it will stop both jobs right away. 

If both service instances are on the same node, it seems to work most of the time, but it's also not stable.

The documentation here: https://developer.hashicorp.com/nomad/tutorials/manage-clusters/node-drain says (referencing a job with count 9 and max_parallel 2): 

> Even if multiple nodes running allocations for this job were draining at the same time, only 2 allocations would be migrated at a time.

It seems like this is not the case.

### Reproduction steps

Start a cluster with 4 client nodes, start the job, making sure it's running on two different nodes. Drain those two nodes at the same time.

#### Expected Result

It should only stop one job at a time.

#### Actual Result

Both jobs are stopped right away, causing downtime on the whole service.

### Job file (if appropriate)

```
job "test-job" {
  type = "service"
  region = "eu-west-1"

  migrate {
    max_parallel = 1
    health_check = "checks"
    min_healthy_time = "15s"
    healthy_deadline = "5m"
  }

  group "test-job" {
    count = 2

    network {
      port "http" { }
    }

    task "test-job" {
      driver = "docker"
      config {
        image = "hashicorp/http-echo:1.0.0"
        args  = ["-text", "ok", "-listen", ":${NOMAD_PORT_http}"]
        ports = ["http"]
      }

      service {
        name = "test-job"
        port = "http"
        check {
          name = "http-ok"
          type = "http"
          path = "/"
          interval = "10s"
          timeout  = "2s"
        }
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)

```
$ nomad node drain -enable -yes f36dd73a
2025-06-04T12:32:30+02:00: Ctrl-C to stop monitoring: will not cancel the node drain
2025-06-04T12:32:30+02:00: Node "f36dd73a-f5c9-8d8d-ce92-0c250f11568f" drain strategy set
2025-06-04T12:32:32+02:00: Alloc "63b9d8f4-68e0-9ce6-f2ff-e5c518e59581" marked for migration

$ nomad node drain -enable -yes 74995fa4
2025-06-04T12:32:30+02:00: Ctrl-C to stop monitoring: will not cancel the node drain
2025-06-04T12:32:30+02:00: Node "74995fa4-8cc4-6efc-8a81-a7154e9cdec5" drain strategy set
2025-06-04T12:32:31+02:00: Alloc "3d97c300-e298-ca06-cdfe-4d2c88b355ca" marked for migration
```

### PR DESCRIPTION
**Pull request by chrisroberts**
### Description
When draining nodes allocs are checked for a healthy state and
marked to be drained, with the value in the max parallel setting
determining how many allocs will be migrated. Depending on the
circumstances, however, the max parallel setting may not be
properly respected.

Given a job with max parallel set to one, a group count greater
than one, and allocs on multiple nodes: Draining a single node
will result in one alloc being marked to drain. If another
node is immediately drained the alloc running on the first
node will be seen as "healthy" and another alloc will be
marked to be drained resulting in two allocs being marked
for migration at the same time. This can lead to issues with
service availablility.

To prevent this allocs can only be marked as healthy when the
alloc has not been marked for migration. This prevents migrating
allocs being seen as healthy which results in the max parallel
setting being properly respected.

### Testing & Reproduction steps
This can be reproduced by creating a job with task group having a count of 2. Spread placement so that allocs are placed on different nodes. Drain both nodes simultaneously. Currently, both allocs will be drained immediately:

```
docker-service.docker-group 2025-06-30T16:59:45-07:00: b272f076 - begin drain
docker-service.docker-group 2025-06-30T16:59:46-07:00: 9bc29c5d - begin drain
docker-service.docker-group 2025-06-30T16:59:46-07:00: b272f076 - finish drain
docker-service.docker-group 2025-06-30T16:59:47-07:00: 9bc29c5d - finish drain
```

With this change, draining both nodes results in allocs being drained individually:

```
docker-service.docker-group 2025-06-30T16:57:27-07:00: 18c95bdb - begin drain
docker-service.docker-group 2025-06-30T16:57:28-07:00: 18c95bdb - finish drain
docker-service.docker-group 2025-06-30T16:57:50-07:00: 19380095 - begin drain
docker-service.docker-group 2025-06-30T16:57:50-07:00: 19380095 - finish drain
```

### Links
Fixes #25979 

### Contributor Checklist
- [ ] **Changelog Entry** If this PR changes user-facing behavior, please generate and add a
  changelog entry using the `make cl` command.
- [ ] **Testing** Please add tests to cover any new functionality or to demonstrate bug fixes and
  ensure regressions will be caught.
- [ ] **Documentation** If the change impacts user-facing functionality such as the CLI, API, UI,
  and job configuration, please update the  Nomad website documentation to reflect this. Refer to
  the [website README](../website/README.md) for docs guidelines. Please also consider whether the
  change requires notes within the [upgrade guide](../website/content/docs/upgrade/upgrade-specific.mdx).

### Reviewer Checklist
- [ ] **Backport Labels** Please add the correct backport labels as described by the internal
  backporting document.
- [ ] **Commit Type** Ensure the correct merge method is selected which should be "squash and merge"
  in the majority of situations. The main exceptions are long-lived feature branches or merges where
  history should be preserved.
- [ ] **Enterprise PRs** If this is an enterprise only PR, please add any required changelog entry
  within the public repository.

### CODE REVIEW

File: nomad/drainer/watch_jobs_test.go [hunk 1]
```diff
@@ -40,6 +40,34 @@ func testNodes(t *testing.T, state *state.StateStore) (drainingNode, runningNode
...
+func testNodesMultiDrain(t *testing.T, state *state.StateStore) (drainingNode, otherDrainingNode, runningNode *structs.Node) {
+	n1 := mock.Node()
+	n1.Name = "draining"
+	n1.DrainStrategy = &structs.DrainStrategy{
+		DrainSpec: structs.DrainSpec{
+			Deadline: time.Minute,
+		},
+		ForceDeadline: time.Now().Add(time.Minute),
+	}
+	require.Nil(t, state.UpsertNode(structs.MsgTypeTestSetup, 100, n1))
```
Comment (tgross) [inline nomad/drainer/watch_jobs_test.go]: Let's not add new tests using `testify` over `shoenig/test`:

```suggestion
	must.NoError(t, state.UpsertNode(structs.MsgTypeTestSetup, 100, n1))
```

File: nomad/drainer/watch_jobs_test.go [hunk 2]
```diff
@@ -344,6 +372,31 @@ func TestDrainingJobWatcher_HandleTaskGroup(t *testing.T) {
...
 		},
+		{
+			name:           "migrating-allocs-not-healty-max-parallel-1",
+			expectDrained:  0,
+			expectMigrated: 0,
+			expectDone:     false,
+			addAllocFn: func(i int, a *structs.Allocation, drainingID, runningID string) {
+				if i == 1 {
+					migrate := true
+					a.DesiredTransition.Migrate = &migrate
```
Comment (tgross) [inline nomad/drainer/watch_jobs_test.go]: Non-blocking, but this construct is common enough that we have a helper for this kind of thing:

```suggestion
					a.DesiredTransition.Migrate = pointer.Of(true)
```
