### PR TITLE
job, task group, and task IDs should not allow null characters

### LINKED ISSUE #8796: job ID allows null character
### Nomad version
nomad 0.12.3

### Issue
validation for nomad job name and ID does not prohibit the null character. the job can be registered, but it causes unexpected problems downstream with multiple task drivers, and potentially causes problems because of indexing in memdb.

job validation should prohibit null character from name/ID of job, task group, task, etc..

this is a breaking change and should be added to the upgrade guide for the release which include it.

### Update

The following environment variables are set in each task: 
* NOMAD_REGION=global
* NOMAD_DC=dc1
* NOMAD_NAMESPACE=default
* NOMAD_JOB_NAME=example
* NOMAD_GROUP_NAME=cache
* NOMAD_TASK_NAME=redis
* NOMAD_PORT_db=6379
* NOMAD_ALLOC_NAME=example.cache[0]

If any of region, dc, namespace, job id/name, group name, task name, or port name include null characters, this will fail for most task drivers.

Namespace and port are currently restricted. Region, DC and the job identifiers are not.

### PR DESCRIPTION
**Pull request by cgbaker**
resolves #8796 

null characters in region, datacenter, job ID/name, task group name, and task name can break a lot of things, including:
* memdb compound indexing
* default task environment variables

changelog summary:
* d4ef12e42ebfde8575caa86e8b649cf0d6fcb2e5 is a documenting test
* 39c73f1b3256b1f780d329de381a3bf2d1a21d9b introduces the additional validation, but fails, because other tests actually rely on the ability to use null characters 😦 . also, updates CHANGELOG and upgrade guide.
* 5062e74b3e644887ffc39b41e07f341c1ba9af47 relaxes the tests which protect this backwards compatibility
* b0c2e5176a8e0dff88c152460f3d59f9310df62a adds additional tests for agent Region and Datacenter, as well as Job.Name

### CODE REVIEW

File: nomad/structs/structs_test.go [hunk 1]
```diff
@@ -170,6 +170,25 @@ func TestJob_ValidateScaling(t *testing.T) {
...
+	assert.Error(job.Validate(), "null character in job ID should not validate")
+
+	// task group name should not allow null characters
+	job.ID = "happy_little_job_id"
+	job.TaskGroups[0].Name = "oh_no_another_\000_char"
+	assert.Error(job.Validate(), "null character in task group name should not validate")
+
+	// task name should not allow null characters
+	job.TaskGroups[0].Name = "so_much_better"
+	job.TaskGroups[0].Tasks[0].Name = "ive_had_it_with_these_\000_chars_in_these_names"
```
Comment (tgross) [inline nomad/structs/structs_test.go:188]: 😆

File: nomad/structs/structs.go [hunk 2]
```diff
@@ -3943,6 +3943,8 @@ func (j *Job) Validate() error {
 		mErr.Errors = append(mErr.Errors, errors.New("Missing job ID"))
 	} else if strings.Contains(j.ID, " ") {
 		mErr.Errors = append(mErr.Errors, errors.New("Job ID contains a space"))
+	} else if strings.Contains(j.ID, "\000") {
+		mErr.Errors = append(mErr.Errors, errors.New("Job ID contains a null chararacter"))
 	}
 	if j.Name == "" {
```
Comment (tgross) [inline nomad/structs/structs.go:3949]: It doesn't come up except when using the API, but Jobs have both a name and an ID. Should we be validating that `Job.Name` also doesn't contain a null char?

**Review by tgross — APPROVED** [review]

File: nomad/structs/structs.go (hunk 2 above)
Comment (cgbaker) [reply nomad/structs/structs.go:3949]: yeah, good point. i don't see any indexing there, but a quick test showed that null in `Name` put a docker job into a failing state:
```
2020-10-05T12:55:36Z  Driver Failure  Failed to start container cc77616db08d0701b20b438af789855e56eb343f7ce9c0636c779e399e052177: API error (500): OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"setenv: invalid argument\"": unknown
```

will update PR to include `Job.Name`

Comment (cgbaker) [reply nomad/structs/structs.go:3949]: ooh, in addition, the task drivers set the `NOMAD_DC` environment variable, which will fail if the node datacenter includes a null character 🤦

Comment (cgbaker) [reply nomad/structs/structs.go:3949]: and region 🤦++

File: command/agent/command_test.go [hunk 3]
```diff
@@ -142,3 +143,101 @@ func TestCommand_MetaConfigValidation(t *testing.T) {
...
+        client{
+			enabled = true
+    	}`), 0600)
+		if err != nil {
+			t.Fatalf("err: %s", err)
+		}
+
+		// Make a new command. We preemptively close the shutdownCh
+		// so that the command exits immediately instead of blocking.
+		ui := new(cli.MockUi)
```
Comment (tgross) [inline command/agent/command_test.go:172]: According to https://github.com/hashicorp/nomad/issues/9026 this should be `cli.NewMockUi()`

**Review by tgross — CHANGES_REQUESTED** [review]

File: command/agent/command_test.go (hunk 3 above)
Comment (cgbaker) [reply command/agent/command_test.go]: done, thanks 👍

**Review by tgross — APPROVED** [review]
LGTM!
