### PR TITLE
Persisted shared ports during inplace update

### LINKED ISSUE #9360: system job leaks service registration
### Nomad version
0.12.5

### Operating system and Environment details
linux + Consul 1.8.3

### Issue

tested:
When removing the additional service stanzas from `system` type jobs and redeploy, the service registration leaks (not removed from Consul).

### Reproduction steps

1. Deploy the job file below
1. Remove the following
  ```diff
-    service {
-      name = "example-service-2"
-      port = "api"
-    }
  ```
1. Redeploy the job file
1. The service registration still in Consul, and will remain there even after the job is stopped and gc-ed.

### Job file (if appropriate)
```hcl
job "example-system-job" {
  region      = "global"
  datacenters = ["dc1"]
  type        = "system"

  group "example-service-api-group" {
    count = 1

    network {
      mode = "bridge"
      port api  {}
    }

    service {
      name = "example-service-2"
      port = "api"
    }

    service {
      name = "example-service"
      port = "api"
      
      # this check seems have to be here, otherwise it will not trigger this bug.
      check {
        type     = "http"
        port     = "api"
        path     = "/ready"
        interval = "5s"
        timeout  = "1s"
      }
    }

    task "example-fake" {
      driver = "docker"

      config {
        image = "nicholasjackson/fake-service:v0.12.0"
      }

      env {
        LISTEN_ADDR = "0.0.0.0:${NOMAD_PORT_api}"
      }
    }
  }
}
```

### LINKED ISSUE #9735: Allocated Resources Shared ports dropped on inplace update
### Issue

Allocations AllocatedResources shared ports are dropped on in place updates

### Reproduction steps

```diff
-    service {
-      name = "example-service-1"
-      port = "api"
-    }

```

### Job file (if appropriate)
```
job "example-system-job" {
  region      = "global"
  datacenters = ["dc1"]
  type        = "system"

  group "example-service-api-group" {
    count = 1

    network {
      port api {}
    }

    service {
      name = "example-service-1"
      port = "api"
    }

    service {
      name = "example-service-2"
      port = "api"
    }


    task "example-fake" {
      driver = "docker"

      config {
        image = "nicholasjackson/fake-service:v0.12.0"
      }

      env {
        LISTEN_ADDR = "0.0.0.0:${NOMAD_PORT_api}"
      }
    }
  }
}
```

- run job

```
→ curl localhost:4646/v1/allocation/016ad5ec-90bb-c27c-ba6f-e9c97e486a97 | jq '.AllocatedResources.Shared.Ports'
[
  {
    "Label": "api",
    "Value": 24383,
    "To": 0,
    "HostIP": "127.0.0.1"
  }
]
```

- remove one of the service blocks, run job, causing in place update

```
→ curl localhost:4646/v1/allocation/016ad5ec-90bb-c27c-ba6f-e9c97e486a97 | jq '.AllocatedResources.Shared.Ports'
null

```

Side effect first reported in  https://github.com/hashicorp/nomad/issues/9360

### PR DESCRIPTION
**Pull request by drewbailey**
Ensure that allocation AllocatedResources Shared Ports are not dropped during inplace updates.

When performing in place updates, the scheduler creates a shallow copy of the allocation and updates a few fields. It's not immediately clear to me why we do a shallow copy instead of something like `allocation.Copy()`. The AllocatedSharedResources Ports were not copied over causing issues after the plan was applied.

As a side effect, removing or updating a task group service stanza, resulting in an inplace update would error and prevent a service from being registered or deregistered during an inplace update.  This issue was reported in  https://github.com/hashicorp/nomad/issues/9360 

This error was displayed in the logs like so:
```
    2021-01-06T12:49:47.127-0500 [ERROR] client.alloc_runner: error running update hooks: alloc_id=13ff640d-7426-4763-1be1-427a3594dec3 error="1 error occurred:
        * update hook "group_services" failed: error getting address for check "service: \"example-service\" check": invalid port "api": port label not found
"
```

fixes #9360
fixes #9735

### CODE REVIEW

**Review by nickethier — APPROVED** [review]
:tada:

**Review by krishicks — APPROVED** [review]

File: scheduler/util.go [hunk 1]
```diff
@@ -728,7 +728,9 @@ func inplaceUpdate(ctx Context, eval *structs.Evaluation, job *structs.Job,
 			Tasks:          option.TaskResources,
 			TaskLifecycles: option.TaskLifecycles,
 			Shared: structs.AllocatedSharedResources{
-				DiskMB: int64(update.TaskGroup.EphemeralDisk.SizeMB),
+				DiskMB:   int64(update.TaskGroup.EphemeralDisk.SizeMB),
+				Ports:    update.Alloc.AllocatedResources.Shared.Ports,
+				Networks: update.Alloc.AllocatedResources.Shared.Networks,
```
Comment (drewbailey) [inline scheduler/util.go:733]: @nickethier pining if you happen to know, but noticed networks was dropped too, I'm guessing we want to carry over all fields

Comment (nickethier) [reply scheduler/util.go:733]: I think so, but I think we'd want a copy of it. I wonder if we should just set `Shared` on line 730 to `update.Alloc.AllocatedResources.Shared.Copy()`?

Comment (drewbailey) [reply scheduler/util.go:733]: Yeah, its not clear to me why `DiskMB` is `update.TaskGroup.EphemeralDisk.SizeMB` instead of `update.Alloc.AllocatedResources.Shared.DiskMB`

Comment (nickethier) [reply scheduler/util.go:733]: Ah I see, above Ports and Networks are set from the existing alloc because those cannot be updated inplace and is guarded by `tasksUpdated`. 
The same is happening when setting the `DiskMB` here. So I think we can leave as is but would still add a `.Copy()` to the `Networks`.
