### PR TITLE
Fix dispatched optional meta correctly

### LINKED ISSUE #3720: Optional meta should really be optional
### Nomad version
0.6.3

### Operating system and Environment details
Ubuntu 16.04

### Issue
Omitting a `meta_optiona` parameter leads to the verbatim name of the variable in the output:

```
⌘ nomad logs ee6a
before ${NOMAD_META_optional:-} after
```

I would expect: `before  after`

### Reproduction steps
1. `nomad run jobfile.nomad`
2. `nomad job dispatch -meta command=echo test_meta_optional`
3. `nomad logs <alloc-id>`

### Job file (if appropriate)
```
job "test_meta_optional" {
  datacenters = ["NL1"]
  type = "batch"

  parameterized {
    payload       = "forbidden"
    meta_required = ["command"]
    meta_optional = ["optional"]
  }

  group "test_meta_optional" {

    # Fail hard, immediately
    restart {
      attempts = 0
      mode = "fail"
    }

    task "test_meta_optional" {
      driver = "exec"
      config {
        command = "${NOMAD_META_command}"
        args = ["before", "${NOMAD_META_optional:-}", "after"]
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by nickethier**
This fixes a bug in PR #4262 due to the fact that dispatched jobs never return true for `job.IsParameterized` thus missing the logic implemented in the PR. The fix was to add a new `Dispatched` field to the `Job` struct which is set when a new job is dispatched and not allowed to be mutated from the api.

fixes #3720

### CODE REVIEW

File: nomad/job_endpoint.go [hunk 1]
```diff
@@ -1327,6 +1325,13 @@ func validateJob(job *structs.Job) (invalid, warnings error) {
 
 // validateJobUpdate ensures updates to a job are valid.
 func validateJobUpdate(old, new *structs.Job) error {
+	if old == nil {
```
Comment (dadgar) [inline nomad/job_endpoint.go]: Add a comment above saying we are validating a new job

File: client/driver/env/env.go [hunk 2]
```diff
@@ -397,7 +397,23 @@ func (b *Builder) setAlloc(alloc *structs.Allocation) *Builder {
...
 	combined := alloc.Job.CombinedTaskMeta(alloc.TaskGroup, b.taskName)
-	b.taskMeta = make(map[string]string, len(combined)*2)
+	// taskMetaSize is double to total meta keys to account for given and upper
+	// cased values
+	taskMetaSize := len(combined) * 2
+
+	// if job is parameterized initialize optional meta to empty strings
+	if alloc.Job.Dispatched {
+		b.taskMeta = make(map[string]string,
+			taskMetaSize+(len(alloc.Job.ParameterizedJob.MetaOptional)*2))
```
Comment (chelseakomlo) [inline client/driver/env/env.go]: Extract the size into a named variable so reading this is clearer.

File: nomad/job_endpoint_test.go [hunk 3]
```diff
@@ -458,6 +458,33 @@ func TestJobEndpoint_Register_ParameterizedJob(t *testing.T) {
 	}
 }
 
+func TestJobEndpoint_Register_Dispatched(t *testing.T) {
```
Comment (chelseakomlo) [inline nomad/job_endpoint_test.go]: Use `require` for new tests

File: nomad/job_endpoint_test.go [hunk 4]
```diff
@@ -4343,6 +4381,9 @@ func TestJobEndpoint_Dispatch(t *testing.T) {
 				if out.ParentID != tc.parameterizedJob.ID {
 					t.Fatalf("bad parent ID")
 				}
+				if !out.Dispatched {
+					t.Fatal("expected dispatched job")
```
[the remark this answers is not in the document]
Comment (nickethier) [reply nomad/job_endpoint_test.go]: :heavy_check_mark: https://github.com/hashicorp/nomad/pull/4403/commits/e79d31480710afbba913b65bb6052d42788c9cb0#diff-efdbe31d39fdcbfd8e0b5f8aeffcae96R4387

File: nomad/job_endpoint.go [hunk 5]
```diff
@@ -1403,6 +1412,7 @@ func (j *Job) Dispatch(args *structs.JobDispatchRequest, reply *structs.JobDispa
 	dispatchJob.ParentID = parameterizedJob.ID
 	dispatchJob.Name = dispatchJob.ID
 	dispatchJob.SetSubmitTime()
+	dispatchJob.Dispatched = true
```
[the remark this answers is not in the document]
Comment (nickethier) [reply nomad/job_endpoint.go]: :heavy_check_mark: https://github.com/hashicorp/nomad/pull/4403/commits/e79d31480710afbba913b65bb6052d42788c9cb0#diff-35c6f86a8cbf16fa487e40ebbc528dadL1410

File: nomad/job_endpoint_test.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (nickethier) [reply nomad/job_endpoint_test.go]: :heavy_check_mark: https://github.com/hashicorp/nomad/pull/4403/commits/e79d31480710afbba913b65bb6052d42788c9cb0#diff-efdbe31d39fdcbfd8e0b5f8aeffcae96R4387

File: client/driver/env/env_test.go [hunk 6]
```diff
@@ -372,3 +373,19 @@ func TestEnvironment_UpdateTask(t *testing.T) {
...
+func TestEnvironment_InterpolateEmptyOptionalMeta(t *testing.T) {
+	a := mock.Alloc()
+	a.Job.ParameterizedJob = &structs.ParameterizedJobConfig{
+		MetaOptional: []string{"metaopt1", "metaopt2"},
+	}
+	a.Job.Dispatched = true
+	task := a.Job.TaskGroups[0].Tasks[0]
+	task.Meta = map[string]string{"metaopt1": "metaopt1val"}
+	env := NewBuilder(mock.Node(), a, task, "global").Build()
+	require.Equal(t, "metaopt1val", env.ReplaceEnv("${NOMAD_META_metaopt1}"))
```
Comment (chelseakomlo) [inline client/driver/env/env_test.go]: For consistency with other tests, initialize `require := require.New(t)`

File: nomad/job_endpoint_test.go [hunk 7]
```diff
@@ -3988,6 +4016,16 @@ func TestJobEndpoint_ValidateJobUpdate(t *testing.T) {
 	} else {
 		t.Log(err)
 	}
+
+	new = mock.Job()
+	new.Dispatched = true
+	require.Error(validateJobUpdate(old, new),
```
Comment (dadgar) [inline nomad/job_endpoint_test.go]: Generally you want to assert the error you are expecting. require.Contains(err.Error(), "foo bar")
