### PR TITLE
consul: always include task services hook

### LINKED ISSUE #9707: Service not registered in consul when service block is added as job update
### Nomad version

Nomad v1.0.1 (c9c68aa55a7275f22d2338f2df53e67ebfcb9238)

### Consul version

Consul v1.9.0
Revision a417fe510

### Operating system and Environment details

I originally stumbled upon this problem on a cluster running on Ubuntu 20.04
I can reproduce it on macOS Catalina 10.15.7 (the steps below)

### Issue

When the job has been running without a `service` definition, adding a `service` block and re-submitting the job has no effect - the service is not registered in consul.

Logs don't contain any warnings nor errors, it looks like there's no attempt of service registration at all.

### Reproduction steps

Start consul: `consul agent -dev`
Start nomad: `nomad agent -dev`
Run the job file below: `nomad run echo.nomad`
Verify the __service has not been registered in consul, as expected__.
Uncomment the `service` block, and submit the updated job: `nomad run echo.nomad`
Verify the __service has not been registered in consul, while it should have been__.

I also tested the reverse scenario:

I first submitted a fresh job (previously not existing in nomad cluster) _with the service block_. It has been successfully registered in consul. Then I removed the `service` block from the job spec and re-submitted the job. The __service has been properly removed from consul__. So it seems only registration is affected by this bug.

### Job file (if appropriate)

```
job "echo" {
  datacenters = ["dc1"]

  group "web" {
    network {
      port "http" {
        to = 5678
      }
    }

    task "server" {
      driver = "docker"

      config {
        image = "hashicorp/http-echo"
        args  = ["-text", "hello world"]
        ports = ["http"]
      }

    //   service {
    //     name = "echo"
    //     port = "http"
    //   }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by shoenig**
Previously, Nomad would optimize out the services task runner
hook for tasks which were initially submitted with no services
defined. This causes a problem when the job is later updated to
include service(s) on that task, which will result in nothing
happening because the hook is not present to handle the service
registration in the .Update.

Instead, always enable the services hook. The group services
alloc runner hook is already always enabled.

Fixes #9707

### CODE REVIEW

File: e2e/consul/consul.go [hunk 1]
```diff
@@ -73,42 +77,58 @@ func (tc *ConsulE2ETest) TestConsulRegistration(f *framework.F) {
...
+	// Assert service is now registered.
+	e2eutil.RequireConsulRegistered(r, tc.Consul(), "nc-service", 1)
 }
 
 // TestCanaryInplaceUpgrades verifies setting and unsetting canary tags
 func (tc *ConsulE2ETest) TestCanaryInplaceUpgrades(f *framework.F) {
 	t := f.T()
+
+	// TODO(shoenig) https://github.com/hashicorp/nomad/issues/9627
+	t.Skip("THIS TEST IS BROKEN (#9627)")
```
Comment (shoenig) [inline e2e/consul/consul.go:130]: Assigned this to myself for 1.1

**Review by schmichael — APPROVED** [review]
