### PR TITLE
Remove unnecessary locking and serverlist syncing in heartbeats

### LINKED ISSUE #4666: Seems that after leader fail, some agents may forgot about servers except leader, what leads this nodes to miss they heartbeats
### Nomad version
Nomad v0.8.4 (dbee1d7d051619e90a809c23cf7e55750900742a)

### Issue
We see this situation time to time, when one of nomad servers hung due hardware failure or network connectivity problems. At last time was follow situation due aws fail, one of nomad servers hung, and exactly this server was leader:

```
2018/09/06 10:40:03 [WARN] raft: Rejecting vote request from 172.29.4.194:4647 since we have a leader: 172.29.20.70:4647
2018/09/06 10:40:03 [WARN] raft: Heartbeat timeout from "172.29.20.70:4647" reached, starting election
```

By this logs lines we conclude that node with ip `172.29.20.70`, was leader, while aws autoscale begin shutdown failed node, and bring up new(this process took about 5-7 minutes), the remaining two elect new leader, but 2 nomad agents forgot about remaining server and still communicate only with failed leader, only after 15-20 seconds those agents see server list and begin send heartbeats to proper RPC server, but this time was enough for the nomad server(new leader) conclude that this agents miss they hearbeats TTL and begin reallocate all allocation placed on that agents. Follow logs demonstrate situation:

```
2018-09-06T10:41:00.460+0300 [DEBUG] plugin.nomad: 2018/09/06 10:41:00 [ERR] plugin: plugin server: accept unix /tmp/plugin320636499: use of closed network connection
2018/09/06 10:41:00 [ERR] yamux: Failed to write header: write unix @->/tmp/plugin185990052: write: broken pipe
2018-09-06T10:41:00.461+0300 [DEBUG] plugin: plugin process exited: path=/opt/nomad/nomad_0.8.4/nomad
2018-09-06T10:41:00.459+0300 [DEBUG] plugin: plugin process exited: path=/opt/nomad/nomad_0.8.4/nomad
2018-09-06T10:41:00.459+0300 [DEBUG] plugin.nomad: 2018/09/06 10:41:00 [ERR] plugin: plugin server: accept unix /tmp/plugin622419670: use of closed network connection
2018/09/06 10:41:00.433332 [WARN] client: heartbeat missed (request took 15.898862ms). Heartbeat TTL was 13.446301173s and heartbeated after 26.197845989s
2018/09/06 10:41:00.416017 [ERR] client: heartbeating failed. Retrying in 1.473438241s: failed to update status: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:41:00.414357 [ERR] nomad: "Node.UpdateStatus" RPC failed to server 172.29.20.70:4647: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:41:00.414170 [ERR] nomad: "Alloc.GetAllocs" RPC failed to server 172.29.20.70:4647: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:41:00.414207 [ERR] client: failed to query updated allocations: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:41:00.414226 [ERR] nomad: "ACL.ResolveToken" RPC failed to server 172.29.20.70:4647: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:41:00.414242 [WARN] client: failed to resolve token, using expired cached value: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:40:50.409838 [WARN] client: failed to resolve token, using expired cached value: rpc error: failed to get conn: dial tcp 172.29.20.70:4647: i/o timeout
2018/09/06 10:40:50.410347 [ERR] nomad: "Node.UpdateStatus" RPC failed to server 172.29.20.70:4647: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:40:50.409804 [ERR] nomad: "ACL.ResolveToken" RPC failed to server 172.29.20.70:4647: rpc error: failed to get conn: dial tcp 172.29.20.70:4647: i/o timeout
2018/09/06 10:40:50.410172 [ERR] nomad: "ACL.ResolveToken" RPC failed to server 172.29.20.70:4647: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:40:50.410185 [WARN] client: failed to resolve token, using expired cached value: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:40:50.410380 [ERR] client: heartbeating failed. Retrying in 1.847214154s: failed to update status: rpc error: failed to get conn: rpc error: lead thread didn't get connection
2018/09/06 10:40:34.229367 [WARN] client: failed to resolve token, using expired cached value: rpc error: EOF
2018/09/06 10:40:34.228986 [ERR] nomad: "Node.UpdateStatus" RPC failed to server 172.29.20.70:4647: rpc error: EOF
2018/09/06 10:40:34 [ERR] yamux: keepalive failed: i/o deadline reached
2018/09/06 10:40:34.229006 [ERR] client: heartbeating failed. Retrying in 1.398842761s: failed to update status: rpc error: EOF
2018/09/06 10:40:34.229353 [ERR] nomad: "ACL.ResolveToken" RPC failed to server 172.29.20.70:4647: rpc error: EOF
```

As you can see no any server rotation was made after each failed RPC(so we conclude that agent forgot about all server except `172.29.20.70`), as it must be done due code https://github.com/hashicorp/nomad/blob/master/client/rpc.go#L76

For now we think that potential reason could be due absolute setting new server list  in follow code https://github.com/hashicorp/nomad/blob/master/client/client.go#L1509

Our hypothesis is. Before fully hung, leader forget about another servers and provide this info to some nomad clients(this agents not lucky, and they made RPC request to this faulty server), after that nomad server fully hung and stop processing RPC requests, so unlucky clients have not any chance to communicate with healthy servers. But it is strange that consul discovery doesn't helps, and also strange that distance betwen follow erro records

```
2018/09/06 10:40:34.228986 [ERR] nomad: "Node.UpdateStatus" RPC failed to server 172.29.20.70:4647: rpc error: EOF
``` 

and 

```
2018/09/06 10:40:50.410380 [ERR] client: heartbeating failed. Retrying in 1.847214154s: failed to update status: rpc error: failed to get conn: rpc error: lead thread didn't get connection
```

is more than 15 seconds, but in theory this distance should be very small

### PR DESCRIPTION
**Pull request by preetapan**
This removes an unnecessary shared lock between discovery and heartbeating
which was causing heartbeats to be missed upon retries when a single server
fails. Also made a drive by fix to call the periodic server shuffler goroutine. 

I took some of the approach in #4688, but have kept the triggerDiscovery logic upon failure with the change that the server list is not retouched if the discovered servers are same as existing servers. 

Fixes #4666

Prior to this change, running a three server cluster where one of the servers is arbitrarily paused caused many unnecessary reschedule events due the clients being considered lost. With this change, I see a dramatic difference, with the caveat that if a server is paused when a client is about to send its hearbeat and there's not enough grace period left for it to retry another server, it will still be considered a missed heartbeat.

### CODE REVIEW

File: client/client.go [hunk 1]
```diff
@@ -2432,6 +2427,26 @@ DISCOLOOP:
 
 	consulLogger.Info("discovered following servers", "servers", nomadServers)
 
+	// Check if the list of servers discovered is identical to the list we already have
```
Comment (schmichael) [inline client/client.go]: Hm, I think this code would be better placed in `servers.SetServers`. That way it could be done inside the server manager's lock and prevent concurrent RPCs from rotating the list and making this comparison stale.

Not a big deal as there's no data race here, just the possibility of a comparison against stale data which shouldn't do much harm.

File: client/client.go [hunk 2]
```diff
@@ -2432,6 +2427,26 @@ DISCOLOOP:
...
+	allFound := true
+	for _, s := range nomadServers {
+		_, known := knownServers[s.Addr.String()]
+		if !known {
+			allFound = false
+			break
+		}
+	}
+	if allFound && len(nomadServers) == len(serverList) {
+		c.logger.Info("Not replacing server list, current server list is identical to servers discovered in Consul")
```
Comment (schmichael) [inline client/client.go]: Debug log level at most. This should only matter when debugging heartbeating which is hopefully very rare!

```suggestion
		c.logger.Debug("Not replacing server list, current server list is identical to servers discovered in Consul")
```

File: dev/cluster/server1.hcl [hunk 3]
```diff
@@ -16,5 +16,5 @@ server {
   }
 
   # Self-elect, should be 3 or 5 for production
-  bootstrap_expect = 3
+  bootstrap_expect = 1
```
Comment (schmichael) [inline dev/cluster/server1.hcl]: This the dev cluster config, so bootstrap expect should match server2 and server3's.

You can override the value on the command line to use this config for a single server cluster or we could add a new config for single server clusters.

File: dev/cluster/client2.hcl [hunk 4]
```diff
@@ -7,6 +7,9 @@ data_dir = "/tmp/client2"
 # Give the agent a unique name. Defaults to hostname
 name = "client2"
 
+# Enable debugging
+enable_debug = true
```
Comment (schmichael) [inline dev/cluster/client2.hcl]: Keep client3 in sync with client1 and 2.

File: client/client.go (hunk 1 above)
Comment (schmichael) [reply client/client.go]: (It would be easily unit testable in server manager as well)

Comment (preetapan) [reply client/client.go]: The method for comparing whether the two server lists are equal in `servers.SetServers` does a sort - https://github.com/hashicorp/nomad/blob/9da25adc548acaf0443ce4c9f084d053ae496ddc/client/servers/manager.go#L209 
This approach avoids that sort step/modification. I can move over the code though and change the logic in SerServers to avoid the sort of existing servers, which modifies the observable server list.

File: client/servers/manager.go [hunk 5]
```diff
@@ -201,12 +201,16 @@ func (m *Manager) SetServers(servers Servers) bool {
 	m.Lock()
 	defer m.Unlock()
 
-	// Sort both the  existing and incoming servers
-	servers.Sort()
-	m.servers.Sort()
-
 	// Determine if they are equal
-	equal := servers.Equal(m.servers)
+	equal := m.serversAreEqual(servers)
```
Comment (preetapan) [inline client/servers/manager.go]: @schmichael this is ready for another look

File: client/client.go [hunk 6]
```diff
@@ -315,6 +315,9 @@ func NewClient(cfg *config.Config, consulCatalog consul.CatalogAPI, consulServic
 	// Initialize the server manager
 	c.servers = servers.New(c.logger, c.shutdownCh, c)
 
+	// Start server manager rebalancing go routine
+	go c.servers.Start()
```
Comment (notnoop) [inline client/client.go]: Curious how this call was dropped?  Was it a regression?

File: client/servers/manager_test.go [hunk 7]
```diff
@@ -66,6 +66,14 @@ func TestServers_SetServers(t *testing.T) {
 	require.True(m.SetServers([]*servers.Server{s1}))
 	require.Equal(1, m.NumServers())
 	require.Len(m.GetServers(), 1)
+
+	// Test that the list of servers does not get shuffled
+	// as a side effect when incoming list is equal
+	require.True(m.SetServers([]*servers.Server{s1, s2}))
+	before := m.GetServers()
+	require.False(m.SetServers([]*servers.Server{s1, s2}))
+	after := m.GetServers()
```
Comment (notnoop) [inline client/servers/manager_test.go]: Maybe another test with s2 and s1 order swapped to check set equality?

File: client/client.go (hunk 6 above)
Comment (preetapan) [reply client/client.go]: I don't think it was ever there so for long running clients only failed rpcs or discovering new servers would cause reshuffling.

File: client/servers/manager.go [hunk 8]
```diff
@@ -215,6 +219,23 @@ func (m *Manager) SetServers(servers Servers) bool {
...
+	copy = make([]*Server, 0, len(m.servers))
+	for _, s := range m.servers {
+		copy = append(copy, s.Copy())
+	}
+
+	// Sort both the  existing and incoming servers
+	copy.Sort()
+	servers.Sort()
+
+	return copy.Equal(servers)
```
Comment (AlexanderZagaevskiy) [inline client/servers/manager.go]: Isn't it better to compare servers lists omitting their DC, only by IP-addresses? Cause servers coming from `consulDiscovery()` method would be without any DC, whereas current servers would have it.
See https://github.com/hashicorp/nomad/blob/master/client/client.go#L2436

Comment (schmichael) [reply client/servers/manager.go]: Great catch! As far as I can tell the code to prefer the local DC's server has been broken since v0.8.0. I'm going to remove the DC field and add an issue+TODO.
