### PR TITLE
stale allocation data leads to incorrect (and even negative) metrics

### LINKED ISSUE #5570: Negative metrics in 0.9.0 for service tasks.
### Nomad version
`Nomad v0.9.0`

### Operating system and Environment details
Alpine Linux AMD64

### Issue
Unallocated client CPU appears to be affected by service/batch tasks and is reporting negative values for these tasks.

### Reproduction steps
Install Nomad 0.9.0, enable telemetry, submit a service job, observe bug.

### PR DESCRIPTION
**Pull request by cgbaker**
client: was not using up-to-date client state in determining which alloc count towards allocated resources

this is the second issue where using `AllocRunner.Alloc()` instead of `AllocRunner.AllocState()` meant that the `ClientState` had the wrong data. @schmichael [previously noted](https://github.com/hashicorp/nomad/pull/5541#pullrequestreview-227352591) how nefarious this is, that we should look for a solution. i haven't done anything to address the underlying issue with this PR; I've just made the simplest fix to correct the metrics calculation. in fact, the call to `AllocState()` may be a little more expensive than is necessary for this; we only need to know whether the allocation is still resident.

fixes #5570

### CODE REVIEW

**Comment by cgbaker** [comment]
per the comment above about using `AllocState()`, could maybe get the info we need like this instead: 
https://github.com/hashicorp/nomad/blob/e964c7fe941fa1201e0cce005e5319cc21bd0ef8/client/allocrunner/alloc_runner.go#L541-L547

File: client/client.go [hunk 1]
```diff
@@ -2766,6 +2766,8 @@ func (c *Client) allAllocs() map[string]*structs.Allocation {
 	allocs := make(map[string]*structs.Allocation, len(ars))
 	for _, ar := range ars {
 		a := ar.Alloc()
+		as := ar.AllocState()
+		a.ClientStatus = as.ClientStatus
```
Comment (schmichael) [inline client/client.go]: I don't think this is safe as you're modifying `ar.alloc`. I think you need to copy it first.

This also gives `allAllocs` pretty special behavior. It returns a view of each alloc not available anywhere else. At a minimum we should comment this unusual special case, but since there only appears to be a single caller I think we should probably scrap this method entirely and inline the behavior in the caller (or write a one-off function we can unit test).

Comment (cgbaker) [reply client/client.go]: agreed with the criticism and the suggestion.

File: client/client_test.go [hunk 2]
```diff
@@ -1414,6 +1414,116 @@ func TestClient_computeAllocatedDeviceStats(t *testing.T) {
...
+	allocPends.AllocatedResources.Tasks["web"].Cpu = structs.AllocatedCpuResources{CpuShares: 512}
+	allocPends.AllocatedResources.Tasks["web"].Memory = structs.AllocatedMemoryResources{MemoryMB: 512}
+	require.Nil(client.addAlloc(allocPends, ""))
+
+	// wait for allocStops to stop running and for allocRuns to be pending/running
+	testutil.WaitForResult(func() (bool, error) {
+		as, err := client.GetAllocState(allocPends.ID)
+		if as.ClientStatus != structs.AllocClientStatusPending {
+			return false, fmt.Errorf("allocPends not yet pending: %#v", as)
+		} else if err != nil {
```
Comment (notnoop) [inline client/client_test.go]: Generally, it's recommended go check error first.  If `GetAllocState` returned an error, `as.ClientStatus` will panic due to `as` being nil.

File: client/client_test.go [hunk 3]
```diff
@@ -1414,6 +1414,116 @@ func TestClient_computeAllocatedDeviceStats(t *testing.T) {
...
+		as, err = client.GetAllocState(allocFails.ID)
+		if as.ClientStatus != structs.AllocClientStatusFailed {
+			return false, fmt.Errorf("allocFails not yet failed: %#v", as)
+		} else if err != nil {
+			return false, err
+		}
+
+		return true, nil
+	}, func(err error) {
+		t.Fatalf("err: %v", err)
```
Comment (notnoop) [inline client/client_test.go]: I'd suggest using `require.NoError` here, as it provides better error reporting with stack traces.

File: client/client.go (hunk 1 above)
Comment (cgbaker) [reply client/client.go]: @schmichael , updated as suggested.

File: client/client_test.go [hunk 4]
```diff
@@ -1414,6 +1414,116 @@ func TestClient_computeAllocatedDeviceStats(t *testing.T) {
...
+
+	result := client.getAllocatedResources(client.config.Node)
+
+	expected := structs.ComparableResources{
+		Flattened: structs.AllocatedTaskResources{
+			Cpu: structs.AllocatedCpuResources{
+				CpuShares: 768,
+			},
+			Memory: structs.AllocatedMemoryResources{
+				MemoryMB: 768,
```
Comment (langmartin) [inline client/client_test.go]: I figured out right here why you were doubling the resource settings through this test, and I like it. Maybe worth a comment up near the top just to draw attention to it?

Comment (cgbaker) [reply client/client_test.go]: i actually started to write a comment and it felt like i was ruining the joke ;)

File: client/client.go [hunk 5]
```diff
@@ -2709,11 +2709,11 @@ func (c *Client) getAllocatedResources(selfNode *structs.Node) *structs.Comparab
...
 
 	// Sum the allocated resources
-	allocs := c.allAllocs()
 	var allocated structs.ComparableResources
 	allocatedDeviceMbits := make(map[string]int)
-	for _, alloc := range allocs {
-		if alloc.TerminalStatus() {
+	for _, ar := range c.getAllocRunners() {
+		alloc := ar.Alloc()
+		if ar.Alloc().ServerTerminalStatus() || ar.AllocState().ClientTerminalStatus() {
```
Comment (schmichael) [inline client/client.go]:
```suggestion
		if ar.alloc.ServerTerminalStatus() || ar.AllocState().ClientTerminalStatus() {
```
