### PR TITLE
alloc exec: don't panic rootless raw_exec tasks

### LINKED ISSUE #26287: Failure in running exec command in rootless nomad
### Nomad version
1.10.3

### Operating system and Environment details
```
cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
```

### Issue
When running a job in _raw_exec_ driver in rootless environment, where nomad agent run as _non-root_ user, running **exec** command will fail, either through UI or `nomad alloc exec ...`. Even worse, seems like the raw_driver executor was killed because of this, and leave the underlying process leaked in the background. In another word, this running service will keep running in the host server in the background, and nomad will just try to run a new job. #24219

### Reproduction steps
1. Run nomad in dev mode: `nomad agent -dev -bind 0.0.0.0 -log-include-location`
2. Run a simple test job, attached below
3. try run `nomad alloc exec ...` command, through UI or local command

#### Expected Result
Exec command should succeed, and the driver executor should survive

#### Actual Result
Exec command failed, and even killed the underlying executor

### Job file (if appropriate)
```
job "python-service" {
  group "python-service-nomad" {
    network {
      port "webapp0" {}
    }
    
    task "web-app-nomad" {
      driver = "raw_exec"

      config {
        command   = "python3"
        args    = ["-m","http.server","${NOMAD_PORT_webapp0}"]
      }
    }
  }
}
```

### Nomad Server+Client logs (if appropriate)
```
==> No configuration files loaded
==> Starting Nomad agent...
==> Nomad agent configuration:

       Advertise Addrs: HTTP: 10.49.20.225:4646; RPC: 10.49.20.225:4647; Serf: 10.49.20.225:4648
            Bind Addrs: HTTP: [0.0.0.0:4646]; RPC: 0.0.0.0:4647; Serf: 0.0.0.0:4648
                Client: true
             Log Level: DEBUG
               Node Id: 2035675e-899b-146d-f5d1-4f2110290296
                Region: global (DC: dc1)
                Server: true
               Version: 1.10.3

==> Nomad agent started! Log data will stream in below:

    2025-07-16T17:18:57.015+0100 [DEBUG] nomad/server.go:437: nomad: issuer not set; OIDC Discovery endpoint for workload identities disabled
    2025-07-16T17:18:57.017+0100 [INFO]  raft@v1.7.3/api.go:609: nomad.raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:e5d9932f-ed21-8bda-54db-00d9a89da64e Address:10.49.20.225:4647}]"
    2025-07-16T17:18:57.017+0100 [INFO]  raft@v1.7.3/raft.go:161: nomad.raft: entering follower state: follower="Node at 10.49.20.225:4647 [Follower]" leader-address= leader-id=
    2025-07-16T17:18:57.017+0100 [INFO]  go-hclog@v1.6.3/stdlog.go:60: nomad: serf: EventMemberJoin: txvtlccath004.global 10.49.20.225
    2025-07-16T17:18:57.018+0100 [INFO]  nomad/server.go:1796: nomad: starting scheduling worker(s): num_workers=8 schedulers=["service", "batch", "system", "sysbatch", "_core"]
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/server.go:1803: nomad: started scheduling worker: id=cdad5954-b0be-ec6a-db70-11d0606d01fe index=1 of=8
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/server.go:1803: nomad: started scheduling worker: id=fa8b022c-9899-69f4-83a2-a5bd75f85d33 index=2 of=8
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/server.go:1803: nomad: started scheduling worker: id=29ea1e1e-b523-4b61-43c7-500c1dd70123 index=3 of=8
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/server.go:1803: nomad: started scheduling worker: id=14eb1772-7db5-5929-4173-db92d432dfe4 index=4 of=8
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/server.go:1803: nomad: started scheduling worker: id=e319763b-401c-47fe-8e46-55030d40524e index=5 of=8
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/worker.go:403: worker: running: worker_id=cdad5954-b0be-ec6a-db70-11d0606d01fe
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/worker.go:403: worker: running: worker_id=14eb1772-7db5-5929-4173-db92d432dfe4
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/server.go:1803: nomad: started scheduling worker: id=621ff069-cf3d-ab16-4737-d512c67ebdd4 index=6 of=8
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/worker.go:403: worker: running: worker_id=fa8b022c-9899-69f4-83a2-a5bd75f85d33
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/server.go:1803: nomad: started scheduling worker: id=584881f6-54c3-e00e-e4b3-d9b2aa6f6314 index=7 of=8
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/worker.go:403: worker: running: worker_id=e319763b-401c-47fe-8e46-55030d40524e
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/worker.go:403: worker: running: worker_id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/worker.go:403: worker: running: worker_id=29ea1e1e-b523-4b61-43c7-500c1dd70123
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/server.go:1803: nomad: started scheduling worker: id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2 index=8 of=8
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/worker.go:403: worker: running: worker_id=584881f6-54c3-e00e-e4b3-d9b2aa6f6314
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/worker.go:403: worker: running: worker_id=621ff069-cf3d-ab16-4737-d512c67ebdd4
    2025-07-16T17:18:57.018+0100 [INFO]  nomad/server.go:1808: nomad: started scheduling worker(s): num_workers=8 schedulers=["service", "batch", "system", "sysbatch", "_core"]
    2025-07-16T17:18:57.018+0100 [INFO]  nomad/serf.go:62: nomad: adding server: server="txvtlccath004.global (Addr: 10.49.20.225:4647) (DC: dc1)"
    2025-07-16T17:18:57.018+0100 [DEBUG] nomad/encrypter.go:1103: nomad.keyring.replicator: starting encryption key replication
    2025-07-16T17:18:57.019+0100 [DEBUG] docker/driver.go:1983: agent.plugin_loader.docker: using client connection initialized from environment: plugin_dir=""
    2025-07-16T17:18:57.019+0100 [DEBUG] validators/validators.go:50: agent.plugin_loader.raw_exec.id_validator: user range configured: plugin_dir="" denied range=""
    2025-07-16T17:18:57.019+0100 [DEBUG] validators/validators.go:56: agent.plugin_loader.raw_exec.id_validator: group range configured: plugin_dir="" denied range=""
    2025-07-16T17:18:57.019+0100 [DEBUG] validators/validators.go:50: agent.plugin_loader.exec.id_validator: user range configured: plugin_dir="" denied range=""
    2025-07-16T17:18:57.019+0100 [DEBUG] validators/validators.go:56: agent.plugin_loader.exec.id_validator: group range configured: plugin_dir="" denied range=""
    2025-07-16T17:18:57.019+0100 [INFO]  agent/plugins.go:41: agent: detected plugin: name=java type=driver plugin_version=0.1.0
    2025-07-16T17:18:57.019+0100 [INFO]  agent/plugins.go:41: agent: detected plugin: name=docker type=driver plugin_version=0.1.0
    2025-07-16T17:18:57.019+0100 [INFO]  agent/plugins.go:41: agent: detected plugin: name=raw_exec type=driver plugin_version=0.1.0
    2025-07-16T17:18:57.019+0100 [INFO]  agent/plugins.go:41: agent: detected plugin: name=exec type=driver plugin_version=0.1.0
    2025-07-16T17:18:57.019+0100 [INFO]  agent/plugins.go:41: agent: detected plugin: name=qemu type=driver plugin_version=0.1.0
    2025-07-16T17:18:57.019+0100 [INFO]  client/client.go:677: client: using state directory: state_dir=/tmp/NomadClient1455348335
    2025-07-16T17:18:57.019+0100 [INFO]  client/client.go:739: client: using alloc directory: alloc_dir=/tmp/NomadClient1795140844
    2025-07-16T17:18:57.019+0100 [INFO]  client/client.go:747: client: using dynamic ports: min=20000 max=32000 reserved=""
    2025-07-16T17:18:57.025+0100 [DEBUG] client/fingerprint_manager.go:88: client.fingerprint_mgr: built-in fingerprints: fingerprinters=["arch", "bridge", "cgroup", "cni", "consul", "cpu", "host", "host_volume_plugins", "landlock", "memory", "network", "nomad", "plugins_cni", "signal", "storage", "vault", "env_digitalocean", "env_aws", "env_gce", "env_azure"]
    2025-07-16T17:18:57.037+0100 [DEBUG] fingerprint/cni.go:31: client.fingerprint_mgr: CNI config dir is not set or does not exist, skipping: cni_config_dir=/opt/cni/config
    2025-07-16T17:18:57.038+0100 [WARN]  fingerprint/consul.go:236: client.fingerprint_mgr.consul: failed to acquire consul self endpoint: cluster=default error="Get \"http://127.0.0.1:8500/v1/agent/self\": dial tcp 127.0.0.1:8500: connect: connection refused"
    2025-07-16T17:18:57.038+0100 [DEBUG] client/fingerprint_manager.go:170: client.fingerprint_mgr: fingerprinting periodically: fingerprinter=consul initial_period=15s
    2025-07-16T17:18:57.040+0100 [DEBUG] fingerprint/cpu.go:104: client.fingerprint_mgr.cpu: detected CPU model: name="Intel(R) Xeon(R) Gold 6354 CPU @ 3.00GHz"
    2025-07-16T17:18:57.041+0100 [DEBUG] fingerprint/cpu.go:122: client.fingerprint_mgr.cpu: detected CPU frequency: mhz=2992
    2025-07-16T17:18:57.041+0100 [DEBUG] fingerprint/cpu.go:148: client.fingerprint_mgr.cpu: detected CPU core count: cores=8
    2025-07-16T17:18:57.045+0100 [DEBUG] fingerprint/dynamic_host_volumes.go:36: client.fingerprint_mgr.host_volume_plugins: detected plugin built-in: plugin_id=mkdir version=0.0.1
    2025-07-16T17:18:57.045+0100 [WARN]  fingerprint/landlock.go:34: client.fingerprint_mgr.landlock: failed to fingerprint kernel landlock feature: error="function not implemented"
    2025-07-16T17:18:57.046+0100 [WARN]  fingerprint/network_linux.go:65: client.fingerprint_mgr.network: unable to parse speed: path=/sbin/ethtool device=lo
    2025-07-16T17:18:57.046+0100 [DEBUG] fingerprint/network_linux.go:22: client.fingerprint_mgr.network: unable to read link speed: path=/sys/class/net/lo/speed device=lo
    2025-07-16T17:18:57.046+0100 [DEBUG] fingerprint/network.go:99: client.fingerprint_mgr.network: link speed could not be detected and no speed specified by user, falling back to default speed: interface=lo mbits=1000
    2025-07-16T17:18:57.046+0100 [DEBUG] fingerprint/network.go:114: client.fingerprint_mgr.network: detected interface IP: interface=lo IP=127.0.0.1
    2025-07-16T17:18:57.046+0100 [DEBUG] fingerprint/network.go:114: client.fingerprint_mgr.network: detected interface IP: interface=lo IP=::1
    2025-07-16T17:18:57.047+0100 [WARN]  fingerprint/network_linux.go:65: client.fingerprint_mgr.network: unable to parse speed: path=/sbin/ethtool device=lo
    2025-07-16T17:18:57.047+0100 [DEBUG] fingerprint/network_linux.go:22: client.fingerprint_mgr.network: unable to read link speed: path=/sys/class/net/lo/speed device=lo
    2025-07-16T17:18:57.047+0100 [DEBUG] fingerprint/network.go:143: client.fingerprint_mgr.network: link speed could not be detected, falling back to default speed: interface=lo mbits=1000
    2025-07-16T17:18:57.048+0100 [WARN]  fingerprint/plugins_cni.go:53: client.fingerprint_mgr.cni_plugins: failed to read CNI plugins directory: cni_path=/opt/cni/bin error="open /opt/cni/bin: no such file or directory"
    2025-07-16T17:18:57.049+0100 [DEBUG] client/fingerprint_manager.go:170: client.fingerprint_mgr: fingerprinting periodically: fingerprinter=vault initial_period=15s
    2025-07-16T17:18:57.050+0100 [DEBUG] fingerprint/env_aws.go:89: client.fingerprint_mgr.env_aws: error querying AWS IDMS URL, skipping
    2025-07-16T17:18:57.052+0100 [DEBUG] fingerprint/env_gce.go:110: client.fingerprint_mgr.env_gce: could not read value for attribute: attribute=machine-type error="Get \"http://169.254.169.254/computeMetadata/v1/instance/machine-type\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
    2025-07-16T17:18:57.052+0100 [DEBUG] fingerprint/env_gce.go:286: client.fingerprint_mgr.env_gce: error querying GCE Metadata URL, skipping
    2025-07-16T17:18:57.054+0100 [DEBUG] fingerprint/env_azure.go:94: client.fingerprint_mgr.env_azure: could not read value for attribute: attribute=compute/azEnvironment error="Get \"http://169.254.169.254/metadata/instance/compute/azEnvironment?api-version=2019-06-04&format=text\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
    2025-07-16T17:18:57.055+0100 [DEBUG] fingerprint/env_digitalocean.go:84: client.fingerprint_mgr.env_digitalocean: failed to request metadata: attribute=region error="Get \"http://169.254.169.254/metadata/v1/region\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
    2025-07-16T17:18:57.055+0100 [DEBUG] client/fingerprint_manager.go:163: client.fingerprint_mgr: detected fingerprints: node_attrs=["arch", "bridge", "consul", "cpu", "host", "host_volume_plugins", "network", "nomad", "signal", "storage"]
    2025-07-16T17:18:57.055+0100 [INFO]  cgroupslib/init.go:29: client.proclib.cg2: initializing nomad cgroups: cores=0-7
    2025-07-16T17:18:57.055+0100 [INFO]  pluginmanager/group.go:46: client.plugin: starting plugin manager: plugin-type=csi
    2025-07-16T17:18:57.055+0100 [INFO]  pluginmanager/group.go:46: client.plugin: starting plugin manager: plugin-type=driver
    2025-07-16T17:18:57.055+0100 [INFO]  pluginmanager/group.go:46: client.plugin: starting plugin manager: plugin-type=device
    2025-07-16T17:18:57.055+0100 [DEBUG] devicemanager/manager.go:145: client.device_mgr: exiting since there are no device plugins
    2025-07-16T17:18:57.055+0100 [INFO]  pluginmanager/group.go:46: client.plugin: starting plugin manager: plugin-type=dynamic_host_volume
    2025-07-16T17:18:57.055+0100 [DEBUG] validators/validators.go:50: client.driver_mgr.raw_exec.id_validator: user range configured: driver=raw_exec denied range=""
    2025-07-16T17:18:57.055+0100 [DEBUG] validators/validators.go:56: client.driver_mgr.raw_exec.id_validator: group range configured: driver=raw_exec denied range=""
    2025-07-16T17:18:57.055+0100 [DEBUG] validators/validators.go:50: client.driver_mgr.exec.id_validator: user range configured: driver=exec denied range=""
    2025-07-16T17:18:57.055+0100 [DEBUG] validators/validators.go:56: client.driver_mgr.exec.id_validator: group range configured: driver=exec denied range=""
    2025-07-16T17:18:57.055+0100 [DEBUG] pluginmanager/group.go:70: client.plugin: waiting on plugin manager initial fingerprint: plugin-type=driver
    2025-07-16T17:18:57.055+0100 [DEBUG] drivermanager/instance.go:386: client.driver_mgr: initial driver fingerprint: driver=exec health=undetected description="Driver must run as root"
    2025-07-16T17:18:57.055+0100 [DEBUG] drivermanager/instance.go:386: client.driver_mgr: initial driver fingerprint: driver=raw_exec health=healthy description=Healthy
    2025-07-16T17:18:57.055+0100 [DEBUG] pluginmanager/group.go:70: client.plugin: waiting on plugin manager initial fingerprint: plugin-type=device
    2025-07-16T17:18:57.055+0100 [DEBUG] pluginmanager/group.go:74: client.plugin: finished plugin manager initial fingerprint: plugin-type=device
    2025-07-16T17:18:57.055+0100 [DEBUG] pluginmanager/group.go:70: client.plugin: waiting on plugin manager initial fingerprint: plugin-type=dynamic_host_volume
    2025-07-16T17:18:57.055+0100 [DEBUG] pluginmanager/group.go:74: client.plugin: finished plugin manager initial fingerprint: plugin-type=dynamic_host_volume
    2025-07-16T17:18:57.055+0100 [DEBUG] docker/driver.go:1983: client.driver_mgr.docker: using client connection initialized from environment: driver=docker
    2025-07-16T17:18:57.055+0100 [DEBUG] drivermanager/instance.go:386: client.driver_mgr: initial driver fingerprint: driver=java health=undetected description="Driver must run as root"
    2025-07-16T17:18:57.056+0100 [DEBUG] drivermanager/instance.go:386: client.driver_mgr: initial driver fingerprint: driver=qemu health=undetected description=""
    2025-07-16T17:18:57.056+0100 [WARN]  docker/fingerprint.go:96: client.driver_mgr.docker: docker driver requires running as root: resources.cores and NUMA-aware scheduling will not function correctly on this node, including for non-docker tasks: driver=docker
    2025-07-16T17:18:57.056+0100 [DEBUG] docker/fingerprint.go:115: client.driver_mgr.docker: could not connect to docker daemon: driver=docker endpoint=unix:///var/run/docker.sock error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
    2025-07-16T17:18:57.056+0100 [DEBUG] drivermanager/instance.go:386: client.driver_mgr: initial driver fingerprint: driver=docker health=undetected description="Failed to connect to docker daemon"
    2025-07-16T17:18:57.056+0100 [DEBUG] drivermanager/manager.go:281: client.driver_mgr: detected drivers: drivers="map[healthy:[raw_exec] undetected:[exec java qemu docker]]"
    2025-07-16T17:18:57.056+0100 [DEBUG] pluginmanager/group.go:74: client.plugin: finished plugin manager initial fingerprint: plugin-type=driver
    2025-07-16T17:18:57.056+0100 [ERROR] docker/driver.go:867: client.driver_mgr.docker: failed to list pause containers for recovery: driver=docker error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
    2025-07-16T17:18:57.056+0100 [DEBUG] servers/manager.go:208: client.server_mgr: new server list: new_servers=[0.0.0.0:4647, 10.49.20.225:4647] old_servers=[]
    2025-07-16T17:18:57.056+0100 [INFO]  client/client.go:642: client: started client: node_id=59d4827b-ba2c-94cb-fda9-948e6f16785d
    2025-07-16T17:18:57.057+0100 [DEBUG] agent/http.go:524: http: UI is enabled
    2025-07-16T17:18:57.058+0100 [DEBUG] agent/http.go:524: http: UI is enabled
    2025-07-16T17:18:58.660+0100 [WARN]  raft@v1.7.3/raft.go:243: nomad.raft: heartbeat timeout reached, starting election: last-leader-addr= last-leader-id=
    2025-07-16T17:18:58.660+0100 [INFO]  raft@v1.7.3/raft.go:287: nomad.raft: entering candidate state: node="Node at 10.49.20.225:4647 [Candidate]" term=2
    2025-07-16T17:18:58.660+0100 [DEBUG] raft@v1.7.3/raft.go:2108: nomad.raft: pre-voting for self: term=2 id=e5d9932f-ed21-8bda-54db-00d9a89da64e
    2025-07-16T17:18:58.660+0100 [DEBUG] raft@v1.7.3/raft.go:317: nomad.raft: calculated votes needed: needed=1 term=2
    2025-07-16T17:18:58.660+0100 [DEBUG] raft@v1.7.3/raft.go:329: nomad.raft: pre-vote received: from=e5d9932f-ed21-8bda-54db-00d9a89da64e term=2 tally=0
    2025-07-16T17:18:58.660+0100 [DEBUG] raft@v1.7.3/raft.go:341: nomad.raft: pre-vote granted: from=e5d9932f-ed21-8bda-54db-00d9a89da64e term=2 tally=1
    2025-07-16T17:18:58.660+0100 [INFO]  raft@v1.7.3/raft.go:349: nomad.raft: pre-vote successful, starting election: term=2 tally=1 refused=0 votesNeeded=1
    2025-07-16T17:18:58.660+0100 [DEBUG] raft@v1.7.3/raft.go:2018: nomad.raft: voting for self: term=2 id=e5d9932f-ed21-8bda-54db-00d9a89da64e
    2025-07-16T17:18:58.660+0100 [DEBUG] raft@v1.7.3/raft.go:376: nomad.raft: vote granted: from=e5d9932f-ed21-8bda-54db-00d9a89da64e term=2 tally=1
    2025-07-16T17:18:58.660+0100 [INFO]  raft@v1.7.3/raft.go:381: nomad.raft: election won: term=2 tally=1
    2025-07-16T17:18:58.660+0100 [INFO]  raft@v1.7.3/raft.go:469: nomad.raft: entering leader state: leader="Node at 10.49.20.225:4647 [Leader]"
    2025-07-16T17:18:58.660+0100 [INFO]  nomad/leader.go:114: nomad: cluster leadership acquired
    2025-07-16T17:18:58.662+0100 [DEBUG] raft-autopilot@v0.1.6/run.go:103: nomad.autopilot: autopilot is now running
    2025-07-16T17:18:58.662+0100 [DEBUG] raft-autopilot@v0.1.6/run.go:175: nomad.autopilot: state update routine is now running
    2025-07-16T17:18:58.662+0100 [INFO]  nomad/leader.go:2703: nomad.core: established cluster id: cluster_id=bd3fd6d5-fba1-ea43-5c00-d5e266f09e08 create_time=1752682738662462161
    2025-07-16T17:18:58.662+0100 [INFO]  nomad/leader.go:2755: nomad: eval broker status modified: paused=false
    2025-07-16T17:18:58.662+0100 [INFO]  nomad/leader.go:2762: nomad: blocked evals status modified: paused=false
    2025-07-16T17:18:58.676+0100 [DEBUG] servers/manager.go:208: client.server_mgr: new server list: new_servers=[10.49.20.225:4647] old_servers=[10.49.20.225:4647, 0.0.0.0:4647]
    2025-07-16T17:18:58.676+0100 [INFO]  client/client.go:2119: client: node registration complete
    2025-07-16T17:18:58.676+0100 [DEBUG] client/client.go:2540: client: updated allocations: index=1 total=0 pulled=0 filtered=0
    2025-07-16T17:18:58.676+0100 [DEBUG] client/client.go:2613: client: allocation updates: added=0 removed=0 updated=0 ignored=0
    2025-07-16T17:18:58.676+0100 [DEBUG] client/client.go:2651: client: allocation updates applied: added=0 removed=0 updated=0 ignored=0 errors=0
    2025-07-16T17:18:58.676+0100 [DEBUG] client/client.go:2166: client: state updated: node_status=ready
    2025-07-16T17:18:58.884+0100 [INFO]  nomad/leader.go:2688: nomad.keyring: initialized keyring: id=06392859-f37f-a19c-7ce1-0cd33101de37
    2025-07-16T17:18:59.676+0100 [DEBUG] client/client.go:2586: client: state changed, updating node and re-registering
    2025-07-16T17:18:59.677+0100 [INFO]  client/client.go:2119: client: node registration complete
==> Failed to check for updates: Get "https://checkpoint-api.hashicorp.com/v1/check/nomad?arch=amd64&os=linux&signature=&version=1.10.3": Proxy Authentication Required
    2025-07-16T17:19:06.082+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/namespaces duration="519.988µs"
    2025-07-16T17:19:08.616+0100 [DEBUG] agent/http.go:723: http: request complete: method=POST path="/v1/jobs/parse?namespace=*" duration=1.412808ms
    2025-07-16T17:19:08.620+0100 [DEBUG] scheduler/generic_sched.go:390: nomad.job.service_sched: reconciled current state with desired state: eval_id=a08b9ff4-5241-5e90-dab9-bdde073c38b1 job_id=python-service namespace=default
  results=
  | Total changes: (place 1) (destructive 0) (inplace 0) (stop 0) (disconnect 0) (reconnect 0)
  | Created Deployment: "b6003325-422f-8aea-988b-7d65c9e21ddf"
  | Desired Changes for "python-service-nomad": (place 1) (inplace 0) (destructive 0) (stop 0) (migrate 0) (ignore 0) (canary 0)

    2025-07-16T17:19:08.621+0100 [DEBUG] scheduler/util.go:596: nomad.job.service_sched: setting eval status: eval_id=a08b9ff4-5241-5e90-dab9-bdde073c38b1 job_id=python-service namespace=default status=complete
    2025-07-16T17:19:08.621+0100 [DEBUG] agent/http.go:723: http: request complete: method=POST path=/v1/job/python-service/plan duration=2.608755ms
    2025-07-16T17:19:10.208+0100 [DEBUG] nomad/worker.go:524: worker: dequeued evaluation: worker_id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2 eval_id=61090549-c457-b48b-b666-250b86aab5e8 type=service namespace=default job_id=python-service node_id="" triggered_by=job-register
    2025-07-16T17:19:10.208+0100 [DEBUG] scheduler/generic_sched.go:390: worker.service_sched: reconciled current state with desired state: eval_id=61090549-c457-b48b-b666-250b86aab5e8 job_id=python-service namespace=default worker_id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2
  results=
  | Total changes: (place 1) (destructive 0) (inplace 0) (stop 0) (disconnect 0) (reconnect 0)
  | Created Deployment: "49ce2d3d-fb14-f011-9f1d-4ee32f9afbff"
  | Desired Changes for "python-service-nomad": (place 1) (inplace 0) (destructive 0) (stop 0) (migrate 0) (ignore 0) (canary 0)

    2025-07-16T17:19:10.208+0100 [DEBUG] agent/http.go:723: http: request complete: method=POST path=/v1/jobs duration=1.884839ms
    2025-07-16T17:19:10.211+0100 [DEBUG] nomad/worker.go:689: worker: submitted plan for evaluation: worker_id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2 eval_id=61090549-c457-b48b-b666-250b86aab5e8
    2025-07-16T17:19:10.211+0100 [DEBUG] scheduler/util.go:596: worker.service_sched: setting eval status: eval_id=61090549-c457-b48b-b666-250b86aab5e8 job_id=python-service namespace=default worker_id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2 status=complete
    2025-07-16T17:19:10.211+0100 [DEBUG] nomad/worker.go:752: worker: updated evaluation: worker_id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2 eval="<Eval \"61090549-c457-b48b-b666-250b86aab5e8\" JobID: \"python-service\" Namespace: \"default\">"
    2025-07-16T17:19:10.211+0100 [DEBUG] nomad/worker.go:559: worker: ack evaluation: worker_id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2 eval_id=61090549-c457-b48b-b666-250b86aab5e8 type=service namespace=default job_id=python-service node_id="" triggered_by=job-register
    2025-07-16T17:19:10.212+0100 [DEBUG] client/client.go:2540: client: updated allocations: index=12 total=1 pulled=1 filtered=0
    2025-07-16T17:19:10.212+0100 [DEBUG] client/client.go:2613: client: allocation updates: added=1 removed=0 updated=0 ignored=0
    2025-07-16T17:19:10.212+0100 [INFO]  taskrunner/task_runner.go:1454: client.alloc_runner.task_runner: Task event: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad type=Received msg="Task received by client" failed=false
    2025-07-16T17:19:10.212+0100 [DEBUG] client/client.go:2651: client: allocation updates applied: added=1 removed=0 updated=0 ignored=0 errors=0
    2025-07-16T17:19:10.212+0100 [DEBUG] widmgr/widmgr.go:120: client.alloc_runner.widmgr: retrieving and renewing workload identities: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 num_identities=0
    2025-07-16T17:19:10.213+0100 [DEBUG] taskrunner/task_runner.go:642: client.alloc_runner.task_runner: lifecycle start condition has been met, proceeding: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad
    2025-07-16T17:19:10.213+0100 [INFO]  taskrunner/task_runner.go:1454: client.alloc_runner.task_runner: Task event: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad type="Task Setup" msg="Building Task Directory" failed=false
    2025-07-16T17:19:10.213+0100 [DEBUG] cmdrunner/cmd_runner.go:73: client.alloc_runner.task_runner.task_hook.logmon: starting plugin: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad path=/dat/cathedral_core/developers/nomad/nomad1.10.3 args=["/dat/cathedral_core/developers/nomad/nomad1.10.3", "logmon"]
    2025-07-16T17:19:10.214+0100 [DEBUG] cmdrunner/cmd_runner.go:80: client.alloc_runner.task_runner.task_hook.logmon: plugin started: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad path=/dat/cathedral_core/developers/nomad/nomad1.10.3 pid=13678
    2025-07-16T17:19:10.214+0100 [DEBUG] go-plugin@v1.6.3/client.go:827: client.alloc_runner.task_runner.task_hook.logmon: waiting for RPC address: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad plugin=/dat/cathedral_core/developers/nomad/nomad1.10.3
    2025-07-16T17:19:10.224+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/job/python-service duration="326.286µs"
    2025-07-16T17:19:10.242+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/namespaces duration="380.985µs"
    2025-07-16T17:19:10.244+0100 [DEBUG] go-plugin@v1.6.3/client.go:1226: client.alloc_runner.task_runner.task_hook.logmon.nomad1.10.3: plugin address: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad @module=logmon address=/tmp/plugin33962801 network=unix timestamp="2025-07-16T17:19:10.244+0100"
    2025-07-16T17:19:10.244+0100 [DEBUG] go-plugin@v1.6.3/client.go:880: client.alloc_runner.task_runner.task_hook.logmon: using plugin: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad version=2
    2025-07-16T17:19:10.246+0100 [DEBUG] go-plugin@v1.6.3/client.go:1226: client.alloc_runner.task_runner.task_hook.logmon.nomad1.10.3: opening fifo: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad path=/tmp/NomadClient1795140844/1a5aec90-187c-5da7-4aee-83dcc7d32758/alloc/logs/.web-app-nomad.stdout.fifo @module=logmon timestamp="2025-07-16T17:19:10.246+0100"
    2025-07-16T17:19:10.246+0100 [DEBUG] go-plugin@v1.6.3/client.go:1226: client.alloc_runner.task_runner.task_hook.logmon.nomad1.10.3: opening fifo: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad @module=logmon path=/tmp/NomadClient1795140844/1a5aec90-187c-5da7-4aee-83dcc7d32758/alloc/logs/.web-app-nomad.stderr.fifo timestamp="2025-07-16T17:19:10.246+0100"
    2025-07-16T17:19:10.248+0100 [INFO]  rawexec/driver.go:415: client.driver_mgr.raw_exec: starting task: driver=raw_exec driver_cfg="{Command:python3 Args:[-m http.server 23299] OverrideCgroupV2: OverrideCgroupV1:map[] OOMScoreAdj:0 WorkDir: DeniedEnvvars:[]}"
    2025-07-16T17:19:10.248+0100 [DEBUG] cmdrunner/cmd_runner.go:73: client.driver_mgr.raw_exec.executor: starting plugin: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad path=/dat/cathedral_core/developers/nomad/nomad1.10.3 args=["/dat/cathedral_core/developers/nomad/nomad1.10.3", "executor", "{\"LogFile\":\"/tmp/NomadClient1795140844/1a5aec90-187c-5da7-4aee-83dcc7d32758/web-app-nomad/executor.out\",\"LogLevel\":\"debug\",\"FSIsolation\":false,\"Compute\":{\"tc\":23936,\"nc\":8}}"]
    2025-07-16T17:19:10.248+0100 [DEBUG] cmdrunner/cmd_runner.go:80: client.driver_mgr.raw_exec.executor: plugin started: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad path=/dat/cathedral_core/developers/nomad/nomad1.10.3 pid=13689
    2025-07-16T17:19:10.248+0100 [DEBUG] go-plugin@v1.6.3/client.go:827: client.driver_mgr.raw_exec.executor: waiting for RPC address: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad plugin=/dat/cathedral_core/developers/nomad/nomad1.10.3
    2025-07-16T17:19:10.279+0100 [DEBUG] go-plugin@v1.6.3/client.go:880: client.driver_mgr.raw_exec.executor: using plugin: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad version=2
    2025-07-16T17:19:10.285+0100 [INFO]  taskrunner/task_runner.go:1454: client.alloc_runner.task_runner: Task event: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad type=Started msg="Task started by client" failed=false
    2025-07-16T17:19:11.155+0100 [DEBUG] client/client.go:2540: client: updated allocations: index=14 total=1 pulled=0 filtered=1
    2025-07-16T17:19:11.155+0100 [DEBUG] client/client.go:2613: client: allocation updates: added=0 removed=0 updated=0 ignored=1
    2025-07-16T17:19:11.155+0100 [DEBUG] client/client.go:2651: client: allocation updates applied: added=0 removed=0 updated=0 ignored=1 errors=0
    2025-07-16T17:19:19.920+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path="/v1/jobs/statuses?filter=&namespace=%2A&per_page=25" duration="420.156µs"
    2025-07-16T17:19:19.924+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/namespaces duration="154.898µs"
    2025-07-16T17:19:19.925+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/node/pools duration="269.359µs"
    2025-07-16T17:19:19.927+0100 [DEBUG] agent/http.go:723: http: request complete: method=POST path="/v1/jobs/statuses?namespace=*" duration="555.425µs"
    2025-07-16T17:19:21.105+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/job/python-service duration="556.417µs"
    2025-07-16T17:19:21.111+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/namespaces duration="516.972µs"
    2025-07-16T17:19:21.148+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/stats duration="659.704µs"
    2025-07-16T17:19:21.231+0100 [DEBUG] client/client.go:2540: client: updated allocations: index=15 total=1 pulled=0 filtered=1
    2025-07-16T17:19:21.231+0100 [DEBUG] client/client.go:2613: client: allocation updates: added=0 removed=0 updated=0 ignored=1
    2025-07-16T17:19:21.231+0100 [DEBUG] client/client.go:2651: client: allocation updates applied: added=0 removed=0 updated=0 ignored=1 errors=0
    2025-07-16T17:19:21.232+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path="/v1/jobs/statuses?filter=&namespace=%2A&per_page=25&index=14" duration=1.305491247s
    2025-07-16T17:19:22.483+0100 [DEBUG] nomad/worker.go:524: worker: dequeued evaluation: worker_id=584881f6-54c3-e00e-e4b3-d9b2aa6f6314 eval_id=7fb06288-b58d-4ec2-1f34-deb03bd5b607 type=service namespace=default job_id=python-service node_id="" triggered_by=deployment-watcher
    2025-07-16T17:19:22.483+0100 [DEBUG] scheduler/generic_sched.go:390: worker.service_sched: reconciled current state with desired state: eval_id=7fb06288-b58d-4ec2-1f34-deb03bd5b607 job_id=python-service namespace=default worker_id=584881f6-54c3-e00e-e4b3-d9b2aa6f6314
  results=
  | Total changes: (place 0) (destructive 0) (inplace 0) (stop 0) (disconnect 0) (reconnect 0)
  | Deployment Update for ID "49ce2d3d-fb14-f011-9f1d-4ee32f9afbff": Status "successful"; Description "Deployment completed successfully"
  | Desired Changes for "python-service-nomad": (place 0) (inplace 0) (destructive 0) (stop 0) (migrate 0) (ignore 1) (canary 0)

    2025-07-16T17:19:22.484+0100 [DEBUG] nomad/worker.go:689: worker: submitted plan for evaluation: worker_id=584881f6-54c3-e00e-e4b3-d9b2aa6f6314 eval_id=7fb06288-b58d-4ec2-1f34-deb03bd5b607
    2025-07-16T17:19:22.484+0100 [DEBUG] scheduler/util.go:596: worker.service_sched: setting eval status: eval_id=7fb06288-b58d-4ec2-1f34-deb03bd5b607 job_id=python-service namespace=default worker_id=584881f6-54c3-e00e-e4b3-d9b2aa6f6314 status=complete
    2025-07-16T17:19:22.484+0100 [DEBUG] nomad/worker.go:752: worker: updated evaluation: worker_id=584881f6-54c3-e00e-e4b3-d9b2aa6f6314 eval="<Eval \"7fb06288-b58d-4ec2-1f34-deb03bd5b607\" JobID: \"python-service\" Namespace: \"default\">"
    2025-07-16T17:19:22.484+0100 [DEBUG] nomad/worker.go:559: worker: ack evaluation: worker_id=584881f6-54c3-e00e-e4b3-d9b2aa6f6314 eval_id=7fb06288-b58d-4ec2-1f34-deb03bd5b607 type=service namespace=default job_id=python-service node_id="" triggered_by=deployment-watcher
    2025-07-16T17:19:22.485+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/job/python-service?index=12 duration=12.241315029s
    2025-07-16T17:19:22.485+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/job/python-service?index=12 duration=1.368746468s
    2025-07-16T17:19:23.662+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/stats duration="210.976µs"
    2025-07-16T17:19:26.189+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/stats duration="270.764µs"
    2025-07-16T17:19:27.056+0100 [WARN]  docker/fingerprint.go:96: client.driver_mgr.docker: docker driver requires running as root: resources.cores and NUMA-aware scheduling will not function correctly on this node, including for non-docker tasks: driver=docker
    2025-07-16T17:19:27.784+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758 duration="608.562µs"
    2025-07-16T17:19:27.785+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/namespaces duration="179.093µs"
    2025-07-16T17:19:27.786+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758 duration="255.077µs"
    2025-07-16T17:19:27.806+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/job/python-service duration="233.106µs"
    2025-07-16T17:19:27.846+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/stats duration="172.781µs"
    2025-07-16T17:19:27.866+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/node/59d4827b-ba2c-94cb-fda9-948e6f16785d duration="661.701µs"
    2025-07-16T17:19:29.800+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/job/python-service duration="795.439µs"
    2025-07-16T17:19:29.817+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/namespaces duration="465.282µs"
    2025-07-16T17:19:29.847+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/stats duration="466.607µs"
    2025-07-16T17:19:29.850+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/stats duration="471.981µs"
    2025-07-16T17:19:32.421+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/stats duration="158.828µs"
    2025-07-16T17:19:32.429+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/stats duration="181.849µs"
    2025-07-16T17:19:32.559+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/regions duration="171.693µs"
    2025-07-16T17:19:32.610+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/acl/token/self duration="294.954µs"
    2025-07-16T17:19:32.621+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/operator/license duration="4.437µs"
    2025-07-16T17:19:32.622+0100 [DEBUG] agent/http.go:723: http: request complete: method=POST path=/v1/search/fuzzy duration="317.58µs"
    2025-07-16T17:19:32.623+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/agent/members duration="470.112µs"
    2025-07-16T17:19:32.635+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/job/python-service duration="486.226µs"
    2025-07-16T17:19:32.644+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/agent/self duration="850.169µs"
    2025-07-16T17:19:32.671+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/job/python-service/allocations duration="504.878µs"
    2025-07-16T17:19:36.747+0100 [INFO]  client/alloc_endpoint.go:278: client: task exec session starting: exec_id=c6543ce9-04f1-d83d-ee68-2e0bfebea45b alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad command=["/bin/bash"] tty=true action=""
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3: panic: cgroup must be set: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3: goroutine 76 [running]:: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3: github.com/hashicorp/nomad/drivers/shared/executor.(*UniversalExecutor).setSubCmdCgroup(0xc000c1c000?, 0x41d6a5?, {0x0?, 0x389a460?}): alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3:      github.com/hashicorp/nomad/drivers/shared/executor/executor_universal_linux.go:83 +0x105: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3: github.com/hashicorp/nomad/drivers/shared/executor.(*UniversalExecutor).ExecStreaming.func4(): alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3:      github.com/hashicorp/nomad/drivers/shared/executor/executor.go:535 +0x85: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3: github.com/hashicorp/nomad/drivers/shared/executor.(*execHelper).runTTY(0xc000b979a0, {0x41d6a5?, 0x10?}, {0x7f7250342bf8, 0xc0007c1e80}): alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3:      github.com/hashicorp/nomad/drivers/shared/executor/exec_utils.go:58 +0x1ba: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3: github.com/hashicorp/nomad/drivers/shared/executor.(*execHelper).run(0x40054f8?, {0x40054f8?, 0xc0007bedb0?}, 0x1?, {0x7f7250342bf8?, 0xc0007c1e80?}): alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3:      github.com/hashicorp/nomad/drivers/shared/executor/exec_utils.go:43 +0x32: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3: github.com/hashicorp/nomad/drivers/shared/executor.(*UniversalExecutor).ExecStreaming(0xc000994960, {0x40054f8, 0xc0007bedb0}, {0xc00078c0d0?, 0x47b1d9?, 0x10?}, 0x1, {0x7f7250342bf8, 0xc0007c1e80}): alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3:      github.com/hashicorp/nomad/drivers/shared/executor/executor.go:548 +0x29b: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3: github.com/hashicorp/nomad/drivers/shared/executor.(*grpcExecutorServer).ExecStreaming(0xc000692fc0, {0x4017e68, 0xc0007c1e80}): alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3:      github.com/hashicorp/nomad/drivers/shared/executor/grpc_server.go:181 +0x11b: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3: github.com/hashicorp/nomad/drivers/shared/executor/proto._Executor_ExecStreaming_Handler({0x3621e80?, 0xc000692fc0}, {0x40100f0, 0xc000abe8c0}): alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3:      github.com/hashicorp/nomad/drivers/shared/executor/proto/executor.pb.go:1354 +0xd8: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3: google.golang.org/grpc.(*Server).processStreamingRPC(0xc0007ae800, {0x40054f8, 0xc0007becf0}, 0xc0002c9b00, 0xc0009a15f0, 0x605d5c0, 0x0): alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3:      google.golang.org/grpc@v1.73.0/server.go:1695 +0x1252: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3: google.golang.org/grpc.(*Server).handleStream(0xc0007ae800, {0x4006770, 0xc0004b0ea0}, 0xc0002c9b00): alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3:      google.golang.org/grpc@v1.73.0/server.go:1819 +0xb47: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3: google.golang.org/grpc.(*Server).serveStreams.func2.1(): alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3:      google.golang.org/grpc@v1.73.0/server.go:1035 +0x7f: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3: created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 67: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.750+0100 [DEBUG] go-plugin@v1.6.3/client.go:1216: client.driver_mgr.raw_exec.executor.nomad1.10.3:      google.golang.org/grpc@v1.73.0/server.go:1046 +0x11d: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:36.752+0100 [ERROR] go-plugin@v1.6.3/client.go:777: client.driver_mgr.raw_exec.executor: plugin process exited: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad plugin=/dat/cathedral_core/developers/nomad/nomad1.10.3 id=13689 error="exit status 2"
==> Caught signal: broken pipe
    2025-07-16T17:19:36.752+0100 [INFO]  client/alloc_endpoint.go:218: client: task exec session ended with an error: error="plugin is shut down" code=0xc0020dc250
    2025-07-16T17:19:36.752+0100 [INFO]  taskrunner/task_runner.go:1454: client.alloc_runner.task_runner: Task event: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad type=Terminated msg="Exit Code: -1, Exit Message: \"executor: error waiting on process: rpc error: code = Unavailable desc = error reading from server: EOF\"" failed=false
    2025-07-16T17:19:36.752+0100 [DEBUG] go-plugin@v1.6.3/grpc_stdio.go:142: client.driver_mgr.raw_exec.executor.stdio: received EOF, stopping recv loop: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad err="rpc error: code = Unavailable desc = error reading from server: EOF"
    2025-07-16T17:19:36.752+0100 [INFO]  taskrunner/task_runner.go:907: client.alloc_runner.task_runner: restarting task: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad reason="Restart within policy" delay=16.880001849s
    2025-07-16T17:19:36.752+0100 [ERROR] agent/http.go:760: http: request failed: method=GET path="/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/exec?task=web-app-nomad&tty=true&ws_handshake=true&command=%5B%22%2Fbin%2Fbash%22%5D" error="plugin is shut down" code=500
    2025-07-16T17:19:36.752+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path="/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/exec?task=web-app-nomad&tty=true&ws_handshake=true&command=%5B%22%2Fbin%2Fbash%22%5D" duration=9.709527ms
    2025-07-16T17:19:36.752+0100 [INFO]  taskrunner/task_runner.go:1454: client.alloc_runner.task_runner: Task event: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad type=Restarting msg="Task restarting in 16.880001849s" failed=false
    2025-07-16T17:19:36.924+0100 [DEBUG] client/client.go:2540: client: updated allocations: index=19 total=1 pulled=0 filtered=1
    2025-07-16T17:19:36.925+0100 [DEBUG] client/client.go:2613: client: allocation updates: added=0 removed=0 updated=0 ignored=1
    2025-07-16T17:19:36.925+0100 [DEBUG] client/client.go:2651: client: allocation updates applied: added=0 removed=0 updated=0 ignored=1 errors=0
    2025-07-16T17:19:36.925+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/job/python-service/allocations?index=17 duration=4.219501175s
    2025-07-16T17:19:36.925+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758?index=15 duration=9.107215008s
    2025-07-16T17:19:36.926+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/namespaces duration="140.145µs"
    2025-07-16T17:19:36.926+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/stats duration="146.489µs"
    2025-07-16T17:19:36.927+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/stats duration="134.212µs"
    2025-07-16T17:19:53.633+0100 [DEBUG] taskrunner/task_runner.go:642: client.alloc_runner.task_runner: lifecycle start condition has been met, proceeding: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad
    2025-07-16T17:19:53.635+0100 [INFO]  rawexec/driver.go:415: client.driver_mgr.raw_exec: starting task: driver=raw_exec driver_cfg="{Command:python3 Args:[-m http.server 23299] OverrideCgroupV2: OverrideCgroupV1:map[] OOMScoreAdj:0 WorkDir: DeniedEnvvars:[]}"
    2025-07-16T17:19:53.635+0100 [DEBUG] cmdrunner/cmd_runner.go:73: client.driver_mgr.raw_exec.executor: starting plugin: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad path=/dat/cathedral_core/developers/nomad/nomad1.10.3 args=["/dat/cathedral_core/developers/nomad/nomad1.10.3", "executor", "{\"LogFile\":\"/tmp/NomadClient1795140844/1a5aec90-187c-5da7-4aee-83dcc7d32758/web-app-nomad/executor.out\",\"LogLevel\":\"debug\",\"FSIsolation\":false,\"Compute\":{\"tc\":23936,\"nc\":8}}"]
    2025-07-16T17:19:53.639+0100 [DEBUG] cmdrunner/cmd_runner.go:80: client.driver_mgr.raw_exec.executor: plugin started: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad path=/dat/cathedral_core/developers/nomad/nomad1.10.3 pid=13824
    2025-07-16T17:19:53.639+0100 [DEBUG] go-plugin@v1.6.3/client.go:827: client.driver_mgr.raw_exec.executor: waiting for RPC address: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad plugin=/dat/cathedral_core/developers/nomad/nomad1.10.3
    2025-07-16T17:19:53.670+0100 [DEBUG] go-plugin@v1.6.3/client.go:880: client.driver_mgr.raw_exec.executor: using plugin: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad version=2
    2025-07-16T17:19:53.674+0100 [INFO]  taskrunner/task_runner.go:1454: client.alloc_runner.task_runner: Task event: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad type=Started msg="Task started by client" failed=false
    2025-07-16T17:19:53.832+0100 [DEBUG] client/client.go:2540: client: updated allocations: index=20 total=1 pulled=0 filtered=1
    2025-07-16T17:19:53.833+0100 [DEBUG] client/client.go:2613: client: allocation updates: added=0 removed=0 updated=0 ignored=1
    2025-07-16T17:19:53.833+0100 [DEBUG] client/client.go:2651: client: allocation updates applied: added=0 removed=0 updated=0 ignored=1 errors=0
    2025-07-16T17:19:53.833+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/job/python-service/allocations?index=19 duration=16.903427729s
    2025-07-16T17:19:53.835+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/stats duration="274.086µs"
    2025-07-16T17:19:53.870+0100 [INFO]  taskrunner/task_runner.go:1454: client.alloc_runner.task_runner: Task event: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad type=Terminated msg="Exit Code: 1" failed=false
==> Caught signal: broken pipe
    2025-07-16T17:19:53.871+0100 [DEBUG] go-plugin@v1.6.3/grpc_stdio.go:142: client.driver_mgr.raw_exec.executor.stdio: received EOF, stopping recv loop: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad err="rpc error: code = Unavailable desc = error reading from server: EOF"
    2025-07-16T17:19:53.873+0100 [INFO]  go-plugin@v1.6.3/client.go:780: client.driver_mgr.raw_exec.executor: plugin process exited: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad plugin=/dat/cathedral_core/developers/nomad/nomad1.10.3 id=13824
    2025-07-16T17:19:53.873+0100 [DEBUG] go-plugin@v1.6.3/client.go:558: client.driver_mgr.raw_exec.executor: plugin exited: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:19:53.873+0100 [INFO]  taskrunner/task_runner.go:907: client.alloc_runner.task_runner: restarting task: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad reason="Restart within policy" delay=17.16452627s
    2025-07-16T17:19:53.873+0100 [INFO]  taskrunner/task_runner.go:1454: client.alloc_runner.task_runner: Task event: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad type=Restarting msg="Task restarting in 17.16452627s" failed=false
    2025-07-16T17:19:54.084+0100 [DEBUG] client/client.go:2540: client: updated allocations: index=21 total=1 pulled=0 filtered=1
    2025-07-16T17:19:54.084+0100 [DEBUG] client/client.go:2613: client: allocation updates: added=0 removed=0 updated=0 ignored=1
    2025-07-16T17:19:54.084+0100 [DEBUG] client/client.go:2651: client: allocation updates applied: added=0 removed=0 updated=0 ignored=1 errors=0
    2025-07-16T17:19:57.057+0100 [WARN]  docker/fingerprint.go:96: client.driver_mgr.docker: docker driver requires running as root: resources.cores and NUMA-aware scheduling will not function correctly on this node, including for non-docker tasks: driver=docker
    2025-07-16T17:20:11.038+0100 [DEBUG] taskrunner/task_runner.go:642: client.alloc_runner.task_runner: lifecycle start condition has been met, proceeding: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad
    2025-07-16T17:20:11.040+0100 [INFO]  rawexec/driver.go:415: client.driver_mgr.raw_exec: starting task: driver=raw_exec driver_cfg="{Command:python3 Args:[-m http.server 23299] OverrideCgroupV2: OverrideCgroupV1:map[] OOMScoreAdj:0 WorkDir: DeniedEnvvars:[]}"
    2025-07-16T17:20:11.040+0100 [DEBUG] cmdrunner/cmd_runner.go:73: client.driver_mgr.raw_exec.executor: starting plugin: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad path=/dat/cathedral_core/developers/nomad/nomad1.10.3 args=["/dat/cathedral_core/developers/nomad/nomad1.10.3", "executor", "{\"LogFile\":\"/tmp/NomadClient1795140844/1a5aec90-187c-5da7-4aee-83dcc7d32758/web-app-nomad/executor.out\",\"LogLevel\":\"debug\",\"FSIsolation\":false,\"Compute\":{\"tc\":23936,\"nc\":8}}"]
    2025-07-16T17:20:11.040+0100 [DEBUG] cmdrunner/cmd_runner.go:80: client.driver_mgr.raw_exec.executor: plugin started: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad path=/dat/cathedral_core/developers/nomad/nomad1.10.3 pid=14072
    2025-07-16T17:20:11.040+0100 [DEBUG] go-plugin@v1.6.3/client.go:827: client.driver_mgr.raw_exec.executor: waiting for RPC address: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad plugin=/dat/cathedral_core/developers/nomad/nomad1.10.3
    2025-07-16T17:20:11.072+0100 [DEBUG] go-plugin@v1.6.3/client.go:880: client.driver_mgr.raw_exec.executor: using plugin: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad version=2
    2025-07-16T17:20:11.080+0100 [INFO]  taskrunner/task_runner.go:1454: client.alloc_runner.task_runner: Task event: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad type=Started msg="Task started by client" failed=false
    2025-07-16T17:20:11.183+0100 [DEBUG] client/client.go:2540: client: updated allocations: index=23 total=1 pulled=0 filtered=1
    2025-07-16T17:20:11.184+0100 [DEBUG] client/client.go:2613: client: allocation updates: added=0 removed=0 updated=0 ignored=1
    2025-07-16T17:20:11.184+0100 [DEBUG] client/client.go:2651: client: allocation updates applied: added=0 removed=0 updated=0 ignored=1 errors=0
    2025-07-16T17:20:11.219+0100 [INFO]  taskrunner/task_runner.go:1454: client.alloc_runner.task_runner: Task event: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad type=Terminated msg="Exit Code: 1" failed=false
==> Caught signal: broken pipe
    2025-07-16T17:20:11.220+0100 [DEBUG] go-plugin@v1.6.3/grpc_stdio.go:142: client.driver_mgr.raw_exec.executor.stdio: received EOF, stopping recv loop: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad err="rpc error: code = Unavailable desc = error reading from server: EOF"
    2025-07-16T17:20:11.222+0100 [INFO]  go-plugin@v1.6.3/client.go:780: client.driver_mgr.raw_exec.executor: plugin process exited: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad plugin=/dat/cathedral_core/developers/nomad/nomad1.10.3 id=14072
    2025-07-16T17:20:11.222+0100 [DEBUG] go-plugin@v1.6.3/client.go:558: client.driver_mgr.raw_exec.executor: plugin exited: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 driver=raw_exec task_name=web-app-nomad
    2025-07-16T17:20:11.222+0100 [INFO]  taskrunner/task_runner.go:901: client.alloc_runner.task_runner: not restarting task: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad reason="Exceeded allowed attempts 2 in interval 30m0s and mode is \"fail\""
    2025-07-16T17:20:11.222+0100 [INFO]  taskrunner/task_runner.go:1454: client.alloc_runner.task_runner: Task event: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad type="Not Restarting" msg="Exceeded allowed attempts 2 in interval 30m0s and mode is \"fail\"" failed=true
    2025-07-16T17:20:12.237+0100 [DEBUG] client/client.go:2540: client: updated allocations: index=24 total=1 pulled=0 filtered=1
    2025-07-16T17:20:12.237+0100 [DEBUG] client/client.go:2613: client: allocation updates: added=0 removed=0 updated=0 ignored=1
    2025-07-16T17:20:12.237+0100 [DEBUG] client/client.go:2651: client: allocation updates applied: added=0 removed=0 updated=0 ignored=1 errors=0
    2025-07-16T17:20:13.223+0100 [WARN]  go-plugin@v1.6.3/client.go:1230: client.alloc_runner.task_runner.task_hook.logmon.nomad1.10.3: failed to read from log fifo: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad error="read /tmp/NomadClient1795140844/1a5aec90-187c-5da7-4aee-83dcc7d32758/alloc/logs/.web-app-nomad.stderr.fifo: file already closed" @module=logmon timestamp="2025-07-16T17:20:13.223+0100"
    2025-07-16T17:20:13.223+0100 [WARN]  go-plugin@v1.6.3/client.go:1230: client.alloc_runner.task_runner.task_hook.logmon.nomad1.10.3: failed to read from log fifo: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad error="read /tmp/NomadClient1795140844/1a5aec90-187c-5da7-4aee-83dcc7d32758/alloc/logs/.web-app-nomad.stdout.fifo: file already closed" @module=logmon timestamp="2025-07-16T17:20:13.223+0100"
==> Caught signal: broken pipe
    2025-07-16T17:20:13.224+0100 [DEBUG] go-plugin@v1.6.3/grpc_stdio.go:142: client.alloc_runner.task_runner.task_hook.logmon.stdio: received EOF, stopping recv loop: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad err="rpc error: code = Unavailable desc = error reading from server: EOF"
    2025-07-16T17:20:13.225+0100 [INFO]  go-plugin@v1.6.3/client.go:780: client.alloc_runner.task_runner.task_hook.logmon: plugin process exited: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad plugin=/dat/cathedral_core/developers/nomad/nomad1.10.3 id=13678
    2025-07-16T17:20:13.225+0100 [DEBUG] go-plugin@v1.6.3/client.go:558: client.alloc_runner.task_runner.task_hook.logmon: plugin exited: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad
    2025-07-16T17:20:13.226+0100 [DEBUG] taskrunner/task_runner.go:803: client.alloc_runner.task_runner: task run loop exiting: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758 task=web-app-nomad
    2025-07-16T17:20:13.226+0100 [INFO]  client/gc.go:236: client.gc: marking allocation for GC: alloc_id=1a5aec90-187c-5da7-4aee-83dcc7d32758
    2025-07-16T17:20:13.291+0100 [DEBUG] nomad/node_endpoint.go:1460: nomad.client: adding evaluations for rescheduling failed allocations: num_evals=1
    2025-07-16T17:20:13.291+0100 [DEBUG] nomad/worker.go:524: worker: dequeued evaluation: worker_id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2 eval_id=107b9603-f2d1-9492-b07a-8460401bb9f9 type=service namespace=default job_id=python-service node_id="" triggered_by=alloc-failure
    2025-07-16T17:20:13.291+0100 [DEBUG] client/client.go:2540: client: updated allocations: index=25 total=1 pulled=0 filtered=1
    2025-07-16T17:20:13.291+0100 [DEBUG] client/client.go:2613: client: allocation updates: added=0 removed=0 updated=0 ignored=1
    2025-07-16T17:20:13.291+0100 [DEBUG] client/client.go:2651: client: allocation updates applied: added=0 removed=0 updated=0 ignored=1 errors=0
    2025-07-16T17:20:13.291+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/job/python-service?index=17 duration=19.455927174s
    2025-07-16T17:20:13.291+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/job/python-service?index=17 duration=43.471506863s
    2025-07-16T17:20:13.291+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/job/python-service?index=17 duration=50.169218412s
    2025-07-16T17:20:13.291+0100 [DEBUG] scheduler/generic_sched.go:390: worker.service_sched: reconciled current state with desired state: eval_id=107b9603-f2d1-9492-b07a-8460401bb9f9 job_id=python-service namespace=default worker_id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2
  results=
  | Total changes: (place 0) (destructive 0) (inplace 0) (stop 0) (disconnect 0) (reconnect 0)
  | Desired Changes for "python-service-nomad": (place 0) (inplace 0) (destructive 0) (stop 0) (migrate 0) (ignore 1) (canary 0)

    2025-07-16T17:20:13.292+0100 [DEBUG] nomad/worker.go:794: worker: created evaluation: worker_id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2 eval="<Eval \"655c6efb-78e2-fd4b-a9e2-6ea06553716a\" JobID: \"python-service\" Namespace: \"default\">" waitUntil="\"2025-07-16 16:20:41.222327397 +0000 UTC\""
    2025-07-16T17:20:13.292+0100 [DEBUG] scheduler/generic_sched.go:326: worker.service_sched: found reschedulable allocs, followup eval created: eval_id=107b9603-f2d1-9492-b07a-8460401bb9f9 job_id=python-service namespace=default worker_id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2 followup_eval_id=655c6efb-78e2-fd4b-a9e2-6ea06553716a
    2025-07-16T17:20:13.293+0100 [DEBUG] nomad/worker.go:689: worker: submitted plan for evaluation: worker_id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2 eval_id=107b9603-f2d1-9492-b07a-8460401bb9f9
    2025-07-16T17:20:13.293+0100 [DEBUG] scheduler/util.go:596: worker.service_sched: setting eval status: eval_id=107b9603-f2d1-9492-b07a-8460401bb9f9 job_id=python-service namespace=default worker_id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2 status=complete
    2025-07-16T17:20:13.293+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/stats duration="466.215µs"
    2025-07-16T17:20:13.293+0100 [DEBUG] nomad/worker.go:752: worker: updated evaluation: worker_id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2 eval="<Eval \"107b9603-f2d1-9492-b07a-8460401bb9f9\" JobID: \"python-service\" Namespace: \"default\">"
    2025-07-16T17:20:13.293+0100 [DEBUG] client/client.go:2540: client: updated allocations: index=27 total=1 pulled=1 filtered=0
    2025-07-16T17:20:13.293+0100 [DEBUG] nomad/worker.go:559: worker: ack evaluation: worker_id=cb302cb0-4eaa-b50d-50a5-7f8aacb340e2 eval_id=107b9603-f2d1-9492-b07a-8460401bb9f9 type=service namespace=default job_id=python-service node_id="" triggered_by=alloc-failure
    2025-07-16T17:20:13.294+0100 [DEBUG] client/client.go:2613: client: allocation updates: added=0 removed=0 updated=1 ignored=0
    2025-07-16T17:20:13.294+0100 [DEBUG] client/client.go:2651: client: allocation updates applied: added=0 removed=0 updated=1 ignored=0 errors=0
    2025-07-16T17:20:13.294+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/stats duration="525.921µs"
    2025-07-16T17:20:13.295+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/job/python-service/allocations?index=20 duration=1.745244ms
    2025-07-16T17:20:21.799+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/stats duration="204.254µs"
    2025-07-16T17:20:21.800+0100 [DEBUG] agent/http.go:723: http: request complete: method=GET path=/v1/client/allocation/1a5aec90-187c-5da7-4aee-83dcc7d32758/stats duration="155.421µs"
```

### PR DESCRIPTION
**Pull request by gulducat**
### Description

`nomad alloc exec` on a `raw_exec` task that is successfully running / managed by a non-root Nomad agent causes an executor panic.

The executor dies, leaving an orphaned process still running.

Note: I initially opened this as a draft, because I'm hazy on potential knock-on issues, and I can't think of a very good way to test this (aside from running it on my laptop).

#### The panic fix (we should at least fix this):

* `setSubCmdCgroup()` - return an error instead of `panic()`ing
* `configureResourceContainer()` - always return empty (but non-nil) func on cgroup error, so `UniversalExecutor.Launch()` doesn't panic trying to run it later.
   * in `Launch()` it explicitly says this should be okay: https://github.com/hashicorp/nomad/blob/v1.10.3/drivers/shared/executor/executor.go#L388-L389

#### Feature fix (this is nice to have):

 * `Exec()` and `ExecStreaming()` - allow non-root agent to proceed with `alloc exec` when cgroups are off

### Testing & Reproduction steps

```shell
$ nomad agent -dev
$ nomad run raw.nomad.hcl
# ...
$ nomad exec -job raw whoami
dbennett
```

with this minimal jobspec:

```hcl
job "raw" {
  group "g" {
    task "t" {
      driver = "raw_exec"
      config {
        command = "sleep"
        args    = ["3600"]
      }
    }
  }
}
```

### Links

Fixes #26287

### Contributor Checklist
- [x] **Changelog Entry** If this PR changes user-facing behavior, please generate and add a
  changelog entry using the `make cl` command.
- [ ] **Testing** Please add tests to cover any new functionality or to demonstrate bug fixes and
  ensure regressions will be caught.
- [ ] **Documentation** If the change impacts user-facing functionality such as the CLI, API, UI,
  and job configuration, please update the  Nomad website documentation to reflect this. Refer to
  the [website README](../website/README.md) for docs guidelines. Please also consider whether the
  change requires notes within the [upgrade guide](../website/content/docs/upgrade/upgrade-specific.mdx).

### Reviewer Checklist
- [x] **Backport Labels** Please add the correct backport labels as described by the internal
  backporting document.
- [ ] **Commit Type** Ensure the correct merge method is selected which should be "squash and merge"
  in the majority of situations. The main exceptions are long-lived feature branches or merges where
  history should be preserved.
- [ ] **Enterprise PRs** If this is an enterprise only PR, please add any required changelog entry
  within the public repository.

### CODE REVIEW

File: drivers/shared/executor/executor.go [hunk 1]
```diff
@@ -441,7 +445,11 @@ func (e *UniversalExecutor) Exec(deadline time.Time, name string, args []string)
 	defer cancel()
 
 	if cleanup, err := e.setSubCmdCgroup(&e.childCmd, e.command.StatsCgroup()); err != nil {
-		return nil, 0, err
+		// do not error if we're non-root and failed to set cgroup,
+		// because a non-root Nomad can still run raw_exec tasks.
+		if !(os.Geteuid() != 0 && errors.Is(err, ErrCgroupMustBeSet)) {
+			return nil, 0, fmt.Errorf("Exec: %w", err)
+		}
```
Comment (tgross) [inline drivers/shared/executor/executor.go]: A non-root Nomad can run use cgroups if the admin has configured cgroup delegation correctly (ref https://github.com/hashicorp/nomad/pull/23803 and https://github.com/hashicorp/nomad/issues/13669#issuecomment-2289769887). Can we get this `ErrCgroupMustBeSet` error in any conditions in which we're root or have delegated cgroups? If not, it'd probably be better to drop the UID check to make for one less thing to rip out if we get rootless Nomad working well later.

Comment (gulducat) [reply drivers/shared/executor/executor.go]: I have more confidence with the below evidence that you're right, but still some vague hesitance. mind spot-checking my reasoning?

cc: @dduzgun-security if you'd like to take a look / chime in

---

as far as I can tell, this (getting an empty `""` cgroup) can happen if
* we're [not on linux](https://github.com/hashicorp/nomad/blob/v1.10.3/drivers/shared/executor/executor.go#L203-L205) according to taskrunner setup
* cgroups are ["off"](https://github.com/hashicorp/nomad/blob/v1.10.3/drivers/shared/executor/executor.go#L177-L179) per [this `mount` func](https://github.com/hashicorp/nomad/blob/main/client/lib/cgroupslib/mount.go#L24) which has a comment that states
  - For cgroups v1 this requires root.
  - For cgroups v2 we look for root or whether we're the owner of the slice.
  - All other cases, including any file permission errors, return OFF.
* that same comment does not mention that the func also checks:
  - for cg v2, requires [these controllers](https://github.com/hashicorp/nomad/blob/main/client/lib/cgroupslib/mount.go#L60-L61) -- the context in [the pr](https://github.com/hashicorp/nomad/pull/19176) for that addition sounds like skipping cgroups is what we want, and applies systemically before we ever get to an `alloc exec` call

so I don't _think_ we'd hit those conditions if Nomad agent is root, but I haven't spent a lot of time in this area of the code, so I could be missing something. the root-check's goal was a pretty-naive attempt at avoiding potential privilege escalation, based more out of fear than evidence.

Comment (tgross) [reply drivers/shared/executor/executor.go]: Oh sorry, I think the double-negative here was throwing me. We're allowing a non-root user to bypass setting the cgroup if we got the `ErrCgroupMustBeSet` error. I think we're trying to fix this at the wrong spot. If the cgroup is `""` the `setSubCmdCgroup` should check if cgroups are off and return an empty cleanup function in that case instead of an error.

Comment (gulducat) [reply drivers/shared/executor/executor.go]: sure that'll avoid the root-check too -- latest commit does this, if I'm reading you right.

edit: I've realized that my change doesn't check cgroup mode, so I suppose I should add that, too.

Comment (dduzgun-security) [reply drivers/shared/executor/executor.go]: Thanks for the refs and good catch for this panic. Here are some minor observations:
- Having a test that checks if delegating access to run exec in cgroups v1 (which requires root) in a non-root Nomad is doable. I think we are good and it shouldn't work with [this](https://github.com/hashicorp/nomad/blob/main/client/lib/cgroupslib/mount.go#L39) condition
- Maybe adding a specific error message if one or many of the controllers `"cpuset", "cpu", "io", "memory", "pids"` are missing. I see that it returns `OFF` [here](https://github.com/hashicorp/nomad/blob/main/client/lib/cgroupslib/mount.go#L41) ad many other places in the [detect function](https://github.com/hashicorp/nomad/blob/main/client/lib/cgroupslib/mount.go#L24-L58). If we want to trace the specific error it may be good to return err in this function

Comment (tgross) [reply drivers/shared/executor/executor.go]: That looks right @gulducat

Comment (gulducat) [reply drivers/shared/executor/executor.go]: @dduzgun-security thanks for the spot-check!

tests: one reason this is tricky is that tests are [run as root](https://github.com/hashicorp/nomad/blob/v1.10.3/.github/workflows/test-core.yaml#L145) in CI, because some features require that, and faking out os-level stuff is tough.

surfacing missing controllers: to do this, we'd either need `cgroupslib.GetMode()` to return an error, or for it to accept a logger.  there are quite a lot of places that do `switch GetMode() {` so making it return an error would necessitate a lot of call-site changes.  passing in a logger would at least not require un`switch`ing everything, but executor logs don't always even show up anywhere. :\

both of those issues could be improved by changing `GetMode()`s signature (for tests, we could pass in a path, rather than hard-coded `/proc/self/mountinfo`), but to me that feels like a heavy hand for this particular PR.

at the moment, I just want it not to panic, while also not mistakenly opening any security holes.

I'll hit "Ready for review" on this PR. let me know if there are any blockers!

**Comment by gulducat** [comment]
Note: not backporting to 1.8.x+ent, because the panic doesn't happen there (and the code is appreciably different)

**Review by tgross — APPROVED** [review]
LGTM!

**Comment by krishgu** [comment]
Thank you. This was immensely helpful.

We were trying to run some jobs that use have shared-memory, and had asked about the `exec` driver capabilities on [shared memory](https://discuss.hashicorp.com/t/linux-shared-memory-of-tasks-for-exec-driver-dev-shm/76525).

Instead we ran a rootless nomad agent, with `raw_exec` capability and used that.
