### PR TITLE
ar/groupservice: remove drivernetwork

### LINKED ISSUE #9221: [1.0.0-beta2]: Wrong port registered in consul
### Nomad and consul version
Nomad v1.0.0-beta2 (3acb12bb809712ab2e63f0adc4a6422c2ade27da)
Consul v1.8.5 Revision 1e03567d3

### Operating system and Environment details
CentOS 7
### Issue
I have a jobfile, provided below, that gives a different result on nomad 1.0.0-beta2 and 0.12.5.

The job uses a network stanza, to map a dynamic port to a port in the container:
```
network {
      port "postgresql" { to = 5432 }
}
```
This port is then used by the Grafana job, also provided below:
```
host = "{{ range service "postgresql" }}{{ .Address }}:{{ .Port }}{{ end }}"
```
In my 0.12.5 setup, the postgres service is registered in consul with the dynamic port (e.g. 192.168.1.100:21010), as you would expect. This address and port are then used by Grafana to connect to. 

However, when I submit the exact same jobs to my 1.0.0-beta2 cluster, the service registration in consul gives another result. There, the `5432` postgres port of the container is registered in consul, instead of the dynamic port that Nomad maps to the Nomad node. 

This makes Grafana fail, as it reads the address with the `5432` port from Consul, on which the Nomad node is not listening of course. It should register the dynamic port instead.

### Reproduce

Submit the provided jobs to nomad and look at the registered port.

#### Postgres jobfile
```
job "postgres" {
  datacenters = ["global"]
  type = "service"

  group "postgres" {
    vault {
      policies = ["postgresql-root-read"]
    }

    constraint {
      attribute = "${meta.postgres}"
      value     = "true"
    }

    count = 1

    reschedule {
      attempts       = 10          // Attempt x times to reschedule
      delay          = "5s"        // Wait x seconds to attempt rescheduling
      delay_function = "fibonacci" // Increase the delay time with the fibonacci scale
      interval       = "24h"       // Only try to reschedule for x time
      max_delay      = "1h"        // Max time between attempts to reschedule
      unlimited      = false       // Don't retry to reschedule an unlimited time
    }

    restart {
      attempts = 3      // Maximum of x restarts
      interval = "10m"  // Maximum of x restarts in the past x minutes
      delay    = "15s"  // Wait x seconds between each restart
      mode     = "fail" // Set as failed after x restarts
    }

    network {
      port "postgresql" { to = 5432 }
    }

    task "postgres" {
      driver = "docker"

      template {
        data        = <<EOF
POSTGRES_PASSWORD="{{ with secret "kv/data/passwords/postgresql/root" }}{{ .Data.data.password }}{{ end }}"
EOF
        destination = "local/env"
        env         = true
      }

      config {
        image = "postgres:11.7"

        ports = ["postgresql"]

        volumes = [
          "/data/postgresql:/var/lib/postgresql/data",
        ]
      }

      resources {
        cpu    = 50
        memory = 50
      }

    }
    service {
      name = "postgresql"
      port = "postgresql"
      check = {
        name     = "postgresql"
        port     = "postgresql"
        type     = "tcp"
        interval = "10s"
        timeout  = "2s"
      }
      check_restart {
        limit           = 3     // 3 failed checks before restart
        grace           = "30s" // wait x seconds after restart to check again
        ignore_warnings = false // Also treat warnings as a failed check
      }
    }
  }
}
```
#### Grafana jobfile
```
job "grafana" {
  datacenters = ["global"]
  type = "service"

  group "grafana" {
    vault {
      policies = ["postgresql-grafana-read"]
    }

    constraint {
      attribute = "${meta.rpi}"
      value     = "true"
    }

    count = 1

    reschedule {
      attempts       = 10          // Attempt x times to reschedule
      delay          = "5s"        // Wait x seconds to attempt rescheduling
      delay_function = "fibonacci" // Increase the delay time with the fibonacci scale
      interval       = "24h"       // Only try to reschedule for x time
      max_delay      = "1h"        // Max time between attempts to reschedule
      unlimited      = false       // Don't retry to reschedule an unlimited time
    }

    restart {
      attempts = 3      // Maximum of x restarts
      interval = "10m"  // Maximum of x restarts in the past x minutes
      delay    = "15s"  // Wait x seconds between each restart
      mode     = "fail" // Set as failed after x restarts
    }

    task "grafana" {
      driver = "docker"
      user   = 472

      env {
        GF_SERVER_HTTP_PORT = "${NOMAD_PORT_grafana_ui}"
        GF_SERVER_SERVE_FROM_SUB_PATH = "true"
      }

      template {
        data = <<EOF
[database]
type = postgres
host = "{{ range service "postgresql" }}{{ .Address }}:{{ .Port }}{{ end }}"
name = grafana
user = grafana
password = "{{ with secret "kv/data/passwords/postgresql/grafana" }}{{ .Data.data.password }}{{ end }}"
EOF
        destination = "local/grafana.ini"
      }

      config {
        image = "grafana/grafana:7.0.1"
        volumes = [
          "/nomad/grafana:/var/lib/grafana",
          "local/grafana.ini:/etc/grafana/grafana.ini",
        ]
      }

      resources {
        cpu    = 100
        memory = 100
        network = {
          port "grafana_ui" {}
        }
      }

      service {
        name = "${NOMAD_TASK_NAME}"
        port = "grafana_ui"
        tags = [
          "metrics",
          "traefik.enable=true",
          "traefik.http.routers.grafana.rule=Host(`grafana.homelab`)",
          "traefik.http.routers.grafana.entrypoints=http",
        ]
        check = {
          name     = "${NOMAD_TASK_NAME}"
          port     = "grafana_ui"
          path     = "/api/health"
          type     = "http"
          interval = "10s"
          timeout  = "2s"
        }
        check_restart {
          limit           = 3     // 3 failed checks before restart
          grace           = "30s" // wait x seconds after restart to check again
          ignore_warnings = false // Also treat warnings as a failed check
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by nickethier**
Fixes a bug introduced in #9095 where the wrong port was used in service registration. This is because group services initially passed the port to the service watcher through use of a DriverNetwork. #9095 switch to using newer apis/interfaces that weren't previously available at the time, but didn't remove this initial functionality causing the wrong port number to be used on registration. 

fixes #9221

### CODE REVIEW

**Review by schmichael — APPROVED** [review]
Looks like a test broke. Maybe we can remove it and associated code? No one should be upgrading clients directly from 0.8 -> 1.0. https://app.circleci.com/pipelines/github/hashicorp/nomad/12842/workflows/41b0e3b2-d70a-4eab-9fc2-14e861417d60/jobs/114246

File: command/agent/consul/service_client.go [hunk 1]
```diff
@@ -1476,10 +1476,24 @@ func getAddress(addrMode, portLabel string, networks structs.Networks, driverNet
...
+				// confusing error message
 				return "", 0, fmt.Errorf("invalid port %q: port label not found", portLabel)
 			}
-			return ip, port, nil
+			if port <= 0 {
+				return "", 0, fmt.Errorf("invalid port: %q: port must be >0", portLabel)
+			}
+
+			// A number was given which will use the Consul agent's address and the given port
+			return "", port, nil
```
Comment (schmichael) [inline command/agent/consul/service_client.go:1496]: Might want to mention a blank ip is a valid return value from this func in the docstring as at a glance L1479 makes it seem like a blank ip is *not* valid.

**Review by shoenig — APPROVED** [review]
LGTM!
