### PR TITLE
client/driver/env: interpolate empty optional meta params as empty strings

### LINKED ISSUE #3720: Optional meta should really be optional
### Nomad version
0.6.3

### Operating system and Environment details
Ubuntu 16.04

### Issue
Omitting a `meta_optiona` parameter leads to the verbatim name of the variable in the output:

```
⌘ nomad logs ee6a
before ${NOMAD_META_optional:-} after
```

I would expect: `before  after`

### Reproduction steps
1. `nomad run jobfile.nomad`
2. `nomad job dispatch -meta command=echo test_meta_optional`
3. `nomad logs <alloc-id>`

### Job file (if appropriate)
```
job "test_meta_optional" {
  datacenters = ["NL1"]
  type = "batch"

  parameterized {
    payload       = "forbidden"
    meta_required = ["command"]
    meta_optional = ["optional"]
  }

  group "test_meta_optional" {

    # Fail hard, immediately
    restart {
      attempts = 0
      mode = "fail"
    }

    task "test_meta_optional" {
      driver = "exec"
      config {
        command = "${NOMAD_META_command}"
        args = ["before", "${NOMAD_META_optional:-}", "after"]
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by nickethier**
fixes #3720

### CODE REVIEW

File: client/driver/env/env.go [hunk 1]
```diff
@@ -397,7 +397,23 @@ func (b *Builder) setAlloc(alloc *structs.Allocation) *Builder {
 
 	// Set meta
 	combined := alloc.Job.CombinedTaskMeta(alloc.TaskGroup, b.taskName)
-	b.taskMeta = make(map[string]string, len(combined)*2)
+	// taskMetaSize is double to total meta keys to account for given and upper
+	// cased values
+	taskMetaSize := len(combined) * 2
+
+	// if job is parameterized initialize optional meta to empty strings
+	if alloc.Job.ParameterizedJob != nil {
```
Comment (dadgar) [inline client/driver/env/env.go]: IsParameterized
