### PR TITLE
Parse Docker mounts correctly

### LINKED ISSUE #3156: docker volume mounts: `'mounts[0].volume_options' expected a map, got 'slice'`
### Nomad version
client: Nomad v0.6.2 (OSX)
server: Nomad v0.6.2 (Linux)

### Issue
Running a task using volume mounts results in the error below:
```hcl
      config {
        image = "jenkins/jenkins:2.76-alpine"
        volumes = [
          "local/config/executors.groovy:/usr/share/jenkins/ref/init.groovy.d/executors.groovy:ro",
        ]
        mounts = [
          {
            target = "/var/jenkins_home"
            source = "jenkins-home"
            readonly = false
            volume_options {
              driver_config {
                name = "local"
              }
            }
          }
        ]
      }
```

Error (from alloc-status):
```
Recent Events:
Time                   Type             Description
09/03/17 19:57:41 PDT  Alloc Unhealthy  Unhealthy because of failed task
09/03/17 19:57:41 PDT  Not Restarting   Error was unrecoverable
09/03/17 19:57:41 PDT  Driver Failure   failed to initialize task "jenkins" for alloc "0862c4f9-890b-9cb8-e8e3-8e3be8134b72": 1 error(s) decoding:

* 'mounts[0].volume_options' expected a map, got 'slice'
09/03/17 19:57:41 PDT  Task Setup       Building Task Directory
09/03/17 19:57:41 PDT  Received         Task received by client
```
Removing the `volume_options` stanza causes the job to be scheduled successfully.
Documentation: https://www.nomadproject.io/docs/drivers/docker.html

### Reproduction steps
1. nomad run jenkins.nomad

### Job file (if appropriate)
```hcl
job "jenkins" {
  region = "us-west"
  datacenters = ["dc1"]

  type = "service"

  constraint {
    attribute = "${attr.kernel.name}"
    value     = "linux"
  }

  group "cicd" {
    count = 1

    restart {
      # The number of attempts to run the job within the specified interval.
      attempts = 10
      interval = "5m"

      delay = "25s"
      mode = "delay"
    }

    ephemeral_disk {
      sticky  = true
      size    = 65536
    }

    task "jenkins" {
      driver = "docker"
      config {
        image = "jenkins/jenkins:2.76-alpine"
        volumes = [
          "local/config/executors.groovy:/usr/share/jenkins/ref/init.groovy.d/executors.groovy:ro",
        ]
        mounts = [
          {
            target = "/var/jenkins_home"
            source = "jenkins-home"
            readonly = false
            volume_options {
              driver_config {
                name = "local"
              }
            }
          }
        ]
      }

      logs {
        max_files     = 50
        max_file_size = 10
      }

      resources {
        cpu    = 4000
        memory = 3072
        network {
          mbits = 100
          port "api" {
            static = 8080
          }
          port "slave" {
            static = 50000
          }
        }
      }

      service {
        name = "jenkins"
        tags = ["us-west", "cicd"]
        port = "api"
        check {
          type     = "tcp"
          interval = "10s"
          timeout  = "2s"
        }
        check {
          name     = "jenkins slave port alive"
          port     = "slave"
          type     = "tcp"
          interval = "10s"
          timeout  = "2s"
        }
      }

      template {
        data = <<EOH
import jenkins.model.*
Jenkins.instance.setNumExecutors(2)
        EOH
        destination = "local/config/executors.groovy"
        splay = "5s"
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by dadgar**
This PR Fixes the parsing of Docker mounts and adds testing to ensure no
regressions.

Fixes #3156

### CODE REVIEW

File: client/driver/docker.go [hunk 1]
```diff
@@ -995,14 +1016,21 @@ func (d *DockerDriver) createContainerConfig(ctx *ExecContext, task *structs.Tas
...
-				NoCopy: m.VolumeOptions.NoCopy,
-				Labels: m.VolumeOptions.Labels,
-				DriverConfig: docker.VolumeDriverConfig{
-					Name:    m.VolumeOptions.DriverConfig.Name,
-					Options: m.VolumeOptions.DriverConfig.Options,
-				},
+				NoCopy: m.VolumeOptions[0].NoCopy,
+			}
+
+			if len(m.VolumeOptions[0].DriverConfig) == 1 {
```
Comment (chelseakomlo) [inline client/driver/docker.go]: m.VolumeOptions[0] could be assigned to a variable as it is used more than once. Same for m.VolumeOptions[0].DriverConfig[0]
