### PR TITLE
scheduler: fix job update placement on prev node penalized

### LINKED ISSUE #5856: Job update always lead to allocations migrate (node-reschedule-penalty )
### Nomad version
Output from `nomad version`
Nomad v0.9.3 

### Operating system and Environment details
3 test linux boxes with client+server mode

### Issue

After changing single Meta or Envar for single task in job file, nomad re-schedules the whole job with several tasks to another node. I think this behavior new (comparing to old versions) and suboptimal.

Digging with console tool I found the following. Originally  job with single task group and 2 tasks in the group, was allocated on  node 4aae63e4. Then i have changed single envar value, and run nomad job plan:

```
nomad job plan --verbose job.hcl 

+/- Job: "test.DeviceIpint"
+/- Task Group: "default" (1 create/destroy update)
  +/- Task: "DeviceIpint.1" (forces create/destroy update)
    +/- Env[RestartTag]: "tag2" => "tag3"
      Task: "VideDecoder.2"
```

Then I have updated job with nomad job run job.hcl . In result nomad moved allocation to another node (9e3a3d78). 

To understand why, I looked to alloc status, and it seems it due node-reschedule-penalty.

```
nomad alloc status -verbose <alloc_id>

---skipped some info----
Placement Metrics
Node                                  node-reschedule-penalty  node-affinity  binpack  job-anti-affinity  final score
9e3a3d78-261f-2b52-ddc8-4a770196a325  0                        0              0.498    0                  0.498
3b36f877-4790-bc64-84a5-6e74d0cd4167  0                        0              0.403    0                  0.403
4aae63e4-6614-2e55-0168-c1b12cc992df  -1                       0              0.417    0                  -0.292

```
I think node-reschedule-penalty in current case should not be taken in account (because task is not failing ), also it is clear that restarting the allocation in the same node is more appropriate than migrating to another node in this case. 

I would like nomad  try to place allocations on the same server by default. Is there any flag or trick I can force nomad not to move allocations ?

### PR DESCRIPTION
**Pull request by tgross**
Fixes #5856

When the scheduler looks for a placement for an allocation that's replacing another allocation, it's supposed to penalize the previous node if the allocation had been rescheduled or failed. But we're currently _always_ penalizing the node, which leads to unnecessary migrations on job update.

This commit leaves in place the existing behavior where if the previous alloc was itself rescheduled, its previous nodes are also penalized. This is conservative but the right behavior especially on larger clusters where a group of hosts might be having correlated trouble (like an AZ failure).

### CODE REVIEW

File: scheduler/generic_sched.go [hunk 1]
```diff
@@ -570,7 +570,9 @@ func getSelectOptions(prevAllocation *structs.Allocation, preferredNode *structs
 	selectOptions := &SelectOptions{}
 	if prevAllocation != nil {
 		penaltyNodes := make(map[string]struct{})
-		penaltyNodes[prevAllocation.NodeID] = struct{}{}
+		if prevAllocation.ClientStatus == "failed" {
```
Comment (schmichael) [inline scheduler/generic_sched.go]:
```suggestion

		// If alloc failed penalize the node it failed on to encourage
		// rescheduling on a new node.
		if prevAllocation.ClientStatus == "failed" {
```

File: scheduler/generic_sched.go [hunk 2]
```diff
@@ -570,7 +570,12 @@ func getSelectOptions(prevAllocation *structs.Allocation, preferredNode *structs
 	selectOptions := &SelectOptions{}
 	if prevAllocation != nil {
 		penaltyNodes := make(map[string]struct{})
-		penaltyNodes[prevAllocation.NodeID] = struct{}{}
+
+		// If alloc failed, penalize the node it failed on to encourage
+		// rescheduling on a new node.
+		if prevAllocation.ClientStatus == "failed" {
```
Comment (langmartin) [inline scheduler/generic_sched.go]: I think it's ok to omit "lost", but it might mean that the whole node reboots, and the job gets scheduled back on the same node when it becomes available again, I'm not sure if we want to apply a penalty there. Also, for google foo I think we should use structs.AllocClientStatusFailed.

Comment (schmichael) [reply scheduler/generic_sched.go]: Yeah, I couldn't think of a reason to penalize `lost` -- if the node comes back in time for the scheduler to place it there (seems _extremely_ unlikely), what's the harm? If it's a flaky node I guess that's a problem, but now we're compounding unlikely scenarios.

If there's a chance the scheduler worker's statestore is using a snapshot that doesn't see the node as being lost yet, that's a good to penalize it I suppose. That could cause a pathological situation where many lost allocations are placed back on the lost node only to fail at placement and go through scheduling all over again at a fresher snapshot. This too seems pretty unlikely to me and impossible if we ensure the snapshot is at least as fresh as the evaluation being processed in the first place.

Comment (preetapan) [reply scheduler/generic_sched.go]: +1 to using `structs.AllocClientStatusFailed`
