### PR TITLE
cli: recover from client ACL lookup failures

### LINKED ISSUE #5754: ACL tokens of type 'client' are unable to use the nomad logs command?
### Nomad version
Output from `nomad version`

Nomad v0.9.1+ent

### Issue
An ACL token with `write` access to a namespace can execute `nomad fs` against an allocation running in that namespace but `nomad logs` fails with a 403 error.

### Reproduction steps
Create ACL policy :

```
$ nomad acl policy info testacl
Name        = testacl
Description = <none>
Rules       = namespace "testacl" {
  policy = "write"
}

# Allow read access to the Quota API
quota {
  policy = "read"
}
CreateIndex = 101545
ModifyIndex = 101545
```

Create ACL token :
```
$ nomad acl token create -policy=testacl
Accessor ID  = 494cf903-7c57-f8ea-fe73-87f7bd31c210
Secret ID    = e7636eb1-ac9f-39be-c7bc-6201c184e3d7
Name         = <none>
Type         = client
Global       = false
Policies     = [testacl]
Create Time  = 2019-05-22 19:39:19.625537207 +0000 UTC
Create Index = 103847
Modify Index = 103847 
```

Export ENV vars for the CLI :
``` 
$ export NOMAD_NAMESPACE=testacl
$ export NOMAD_TOKEN=e7636eb1-ac9f-39be-c7bc-6201c184e3d7
```

Run nomad commands
```
$ nomad status
ID    Type     Priority  Status   Submit Date
foo  service  50        running  2019-05-22T13:52:33+02:00
```

```
$ nomad status foo
ID            = foo
Name          = foo
Submit Date   = 2019-05-22T13:52:33+02:00
Type          = service
Priority      = 50
Datacenters   = XXXX
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group        Queued  Starting  Running  Failed  Complete  Lost
foo               0       0         1        0      2         0

Allocations
ID        Node ID   Task Group        Version  Desired  Status   Created    Modified
b13bef10  8ffa4632  foo               4        run      running  7h50m ago  7h49m ago
```

```
$ nomad fs b13bef10
Mode        Size     Modified Time         Name
drwxrwxrwx  4.0 KiB  2019-05-22T11:52:33Z  alloc/
drwxrwxrwx  4.0 KiB  2019-05-22T11:52:34Z  foo/
```

```
$ nomad logs b13bef10
Error reading file: Unexpected response code: 403 (Permission denied)
```

... even with `capabilities = ["read-logs"]` explicitly set in the ACL policy the above still fails ...
When changing to a 'management' token `nomad logs` works as expected.

### PR DESCRIPTION
**Pull request by notnoop**
This fixes a bug in the CLI handling of node lookup failures when
querying allocation and FS endpoints.

Allocation and FS endpoint are handled by the client; one can query the
relevant client directly, or query a server to have it forwarded
transparently to relevant client.  Querying the client directly is
benefecial to avoid loading servers with IO.

As an optimization, the CLI attempts to query the client directly, but
then falls back to using server forwarding path if it encounters network
or connection errors (e.g. clients are locked down or in a separate
inaccessible network).

Here, we fix a bug where if the CLI fails to find to lookup the client
details because it lacks ACL capability or other unexpected reasons, the
CLI will not go through fallback path.

Fixes #5754

### CODE REVIEW

**Comment by cgbaker** [comment]
this resolves #5754, correct?

**Comment by notnoop** [comment]
Yes, thanks @cgbaker for the reference!

File: api/allocations.go [hunk 1]
```diff
@@ -210,12 +210,7 @@ func (a *Allocations) Exec(ctx context.Context,
 
 func (a *Allocations) execFrames(ctx context.Context, alloc *Allocation, task string, tty bool, command []string,
 	errCh chan<- error, q *QueryOptions) (sendFn func(*ExecStreamingInput) error, output <-chan *ExecStreamingOutput) {
-
-	nodeClient, err := a.client.GetNodeClientWithTimeout(alloc.NodeID, ClientConnTimeout, q)
-	if err != nil {
-		errCh <- err
-		return nil, nil
-	}
+	nodeClient, _ := a.client.GetNodeClientWithTimeout(alloc.NodeID, ClientConnTimeout, q)
```
Comment (nickethier) [inline api/allocations.go]: See other comment about logging this error

File: api/fs.go [hunk 2]
```diff
@@ -244,6 +175,40 @@ func (a *AllocFS) Stream(alloc *Allocation, path, origin string, offset int64,
 	return frames, errCh
 }
 
+func queryClientNode(c *Client, alloc *Allocation, reqPath string, q *QueryOptions, customizeQ func(*QueryOptions)) (io.ReadCloser, error) {
+	nodeClient, _ := c.GetNodeClientWithTimeout(alloc.NodeID, ClientConnTimeout, q)
```
Comment (nickethier) [inline api/fs.go]: Is there a way we could debug log this error? I see a future engineer trying to debug why an api call isn't able to hit the client directly and this error would probably be the key bit of knowledge.

Comment (notnoop) [reply api/fs.go]: Not sure how to best handle it.  We currently don't log anything in api package, and introducing logging might be confusing for cli tools, specially if eventually requests succeeds through server.
