### PR TITLE
bug:  fix filter and search

### LINKED ISSUE #12741: fix filtering logic for API

### LINKED ISSUE #12742: fix copy for no matches

### PR DESCRIPTION
**Pull request by ChaiWithJai**
Resolves #12741
Resolves #12742

Fixes the 400 error that was being returned by the API and uses the new filter expression DSL.

Side Effect:

Conditional logic to generate error and no match copy.

### CODE REVIEW

File: ui/app/routes/evaluations/index.js [hunk 1]
```diff
@@ -32,23 +32,56 @@ export default class EvaluationsIndexRoute extends Route {
...
   }) {
-    const generateFilter = () => {
+    const generateFilterExpression = () => {
       const searchFilter = searchTerm
         ? `ID contains "${searchTerm}" or JobID contains "${searchTerm}" or NodeID contains "${searchTerm}" or TriggeredBy contains "${searchTerm}"`
         : null;
       const typeFilter =
         type === 'client' ? `NodeID is not empty` : `NodeID is empty`;
+      const triggeredByFilter = `TriggeredBy contains "${triggeredBy}"`;
+      const statusFilter = `Status contains "${status}"`;
```
Comment (philrenaud) [inline ui/app/routes/evaluations/index.js:47]: This looks neat; we're generating plain-language filter expressions for our API? Could you provide some context into how this is being used?

**Review by philrenaud — CHANGES_REQUESTED** [review]
This works well for me and the tests look great!

A couple general comments:
- There appear to be some statuses that we reflect in the table, but not among possible statuses to `Trigger By`; for example, `max-disconnect-timeout` isn't filterable but exists in the table here:
image

- When no evaluations match filter criteria for `status`, we state `No evaluations match the status blocked` — but when none match filter criteria for `triggered by`, we simply say `There are no evaluations` which is not as specific as we could be here. I'd like to see some combinational messaging here like `No evaluations match state $STATE and trigger $TRIGGER` etc.
image

File: ui/app/routes/evaluations/index.js (hunk 1 above)
Comment (lgfa29) [reply ui/app/routes/evaluations/index.js:47]: Not sure if this is what you are asking for, but here are the docs on the API filter expression syntax: https://www.nomadproject.io/api-docs#filtering

**Comment by ChaiWithJai** [comment]
> * There appear to be some statuses that we reflect in the table, but not among possible statuses to `Trigger By`; for example, `max-disconnect-timeout` isn't filterable but exists in the table here:

Yup, this is a brand new trigger status for Evaluations by way of Disconnected Clients. This isn't documented anywhere so extremely good catch.

File: ui/tests/acceptance/evaluations-test.js [hunk 2]
```diff
@@ -328,6 +307,81 @@ module('Acceptance | evaluations list', function (hooks) {
         .dom('[data-test-empty-evaluations-list]')
         .exists('Renders a message saying no evaluations match filter status');
     });
+
+    test('it should enable combining filters and search', async function (assert) {
+      assert.expect(5);
```
Comment (lgfa29) [inline ui/tests/acceptance/evaluations-test.js:312]: Out of curiosity, what is this assertion testing?

Comment (ChaiWithJai) [reply ui/tests/acceptance/evaluations-test.js:312]: Its all about testing the request params since everything combines via the `filter` query parameter now instead of individual qps.

Given a user combines multiples filters and search, when they add a new filter (or remove a filter) then we send the appropriate request to the server.

File: ui/app/routes/evaluations/index.js [hunk 3]
```diff
@@ -32,23 +32,56 @@ export default class EvaluationsIndexRoute extends Route {
...
+          const expression = lookup[filter];
+          if (!!filter && result !== '') {
+            result = result.concat(` and ${expression}`);
+          } else if (filter) {
+            result = expression;
+          }
+          return result;
+        }, '');
+        return filterExp;
+      }
```
[the remark this answers is not in the document]
Comment (ChaiWithJai) [reply ui/app/routes/evaluations/index.js:84]: Let me give it another look and exploratory refactor and see if the tests still pass.

File: ui/app/routes/evaluations/index.js [hunk 4]
```diff
@@ -32,23 +32,56 @@ export default class EvaluationsIndexRoute extends Route {
...
+        }
+        filterExp = `(${searchFilter})`;
+        if (type) {
+          filterExp = `${filterExp} and ${typeFilter}`;
+        }
+        if (triggeredBy) {
+          filterExp = `${filterExp} and ${triggeredByFilter}`;
+        }
+        if (status) {
+          filterExp = `${filterExp} and ${statusFilter}`;
```
[the remark this answers is not in the document]
Comment (ChaiWithJai) [reply ui/app/routes/evaluations/index.js:62]: Why would we guard with parenthesis? I'm struggling between defense code and premature optimization. Currently, we guarantee these filters a single-select and not multi-select.

But... I like being defensive. So, let me write a test case for potentially enabling multi-select, however, I hope it doesn't blow up in my face.

File: ui/tests/acceptance/evaluations-test.js (hunk 2 above)
Comment (lgfa29) [reply ui/tests/acceptance/evaluations-test.js:312]: Oh sorry, I meant specifically this line `assert.expect(5);`

Comment (ChaiWithJai) [reply ui/tests/acceptance/evaluations-test.js:312]: It counts the number of assertions in the test when we have an assertion that is in an asynchronous callback.

**Review by philrenaud — APPROVED** [review]

File: ui/app/routes/evaluations/index.js (hunk 1 above)
Comment (ChaiWithJai) [reply ui/app/routes/evaluations/index.js:51]: Is this what you were hoping for @philrenaud?

I like following the Seeker/Stumbler paradigm and linking directly to the documentation and resources in code to help seekers.

File: ui/app/routes/evaluations/index.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (ChaiWithJai) [reply ui/app/routes/evaluations/index.js:66]: I can tackle this in a separate PR. I'd like to extract into a template helper (and utility) and have test specifications.
