### PR TITLE
connect: canonicalize before adding sidecar

### LINKED ISSUE #6853: Connect Proxy Kind is not interpolated
### Nomad version
0.10.2

### Issue

When validating jobs on submission the service names are interpolated but the task kind is not.

This means if a service names uses an interpolated value such as `${JOB}` a Connect-enabled job will fail to validate with the error:

```
Connect proxy service name not found in services from task group
```

Augmenting the error message with details makes the difference of interpolation obvious:

```
Connect proxy service name ("count-${JOB}") not found in services from task group: count-countdash
```

### Job file (if appropriate)

Just add `${JOB}` to the service name in the example Connec job: https://gist.github.com/schmichael/c22e696d6dca0ed585d98ab7a7e2fe63

### PR DESCRIPTION
**Pull request by schmichael**
Fixes #6853

Canonicalize jobs first before adding any sidecars. This fixes a bug
where sidecar tasks were added without interpolated names and broke
validation. Sidecar tasks must be canonicalized independently.

Also adds a group network to the mock connect job because it wasn't a
valid connect job before!

### CODE REVIEW

File: nomad/job_endpoint.go [hunk 1]
```diff
@@ -58,8 +58,8 @@ func NewJobEndpoints(s *Server) *Job {
 		srv:    s,
 		logger: s.logger.Named("job"),
 		mutators: []jobMutator{
-			jobConnectHook{},
 			jobCanonicalizer{},
+			jobConnectHook{},
```
Comment (schmichael) [inline nomad/job_endpoint.go]: Note to reviewers: this is one of those fun things that looks super minor but is actually the key to the entire PR.

Previously we were canonicalizing *after* adding Connect tasks.
This change makes it so we canonicalize *before* adding Connect tasks.

This solves the interpolation issue linked from the PR, but is also generally safer as just about everywhere in `nomad/` we touch Job structs we expect them to be canonicalized. So this should make future work in mutators much more predictable.

The downside is that any mutations must canonicalize themselves. The conservative version of this approach would just canonicalize twice: once at the beginning and once at the end. Since there is so little mutator code today I went with this minimal approach where the connect hook canonicalizes anything it adds.

File: nomad/structs/structs.go [hunk 2]
```diff
@@ -5746,15 +5748,28 @@ const ConnectProxyPrefix = "connect-proxy"
...
+		names = append(names, svc.Name)
 	}
 
 	if !found {
-		return fmt.Errorf("Connect proxy service name not found in services from task group")
+		if len(names) == 0 {
+			return fmt.Errorf("No Connect services in task group with Connect proxy (%q)", serviceName)
+		} else {
+			return fmt.Errorf("Connect proxy service name (%q) not found in Connect services from task group: %s", serviceName, names)
+		}
```
Comment (schmichael) [inline nomad/structs/structs.go]: Sorry for the code churn here. The previous error message was just extremely unhelpful. It might as well have been a hardcoded UUID because it only really made sense once you grepped the code for it.

The new errors are still pretty weird because it's a pretty weird condition that is probably due to a code error. The errors at least include a little more context.
