### PR TITLE
secrets: improve plugin error messages

### LINKED ISSUE #27226: Improve secrets providers error messages handling
### Nomad version
```
Nomad v1.11.1
BuildDate 2025-12-09T20:10:56Z
Revision 5b76eb0535615e32faf4daee479f7155ea16ec0d
```

### Issue
There seems to be room for improve error messages coming from secrets providers handling.

1. When referring secret like this:
```hcl
secret "my_secret" {
  provider = "custom-provider"
  path     = "path/to/secret"
}
```
and plugin returns error it will be visible as:
```
secrets: failed to fetch secret from plugin my_secret: exit status 1
```
which is confusing because `my_secret` is name of the secret, not name of the provider.
Error message like: `failed to fetch secret my_secret from plugin custom-provider` would make more sense.

2. [provider author guide](https://developer.hashicorp.com/nomad/plugins/author/secret-provider) contains example function:
```golang
func returnErr(err string) {
    fmt.Printf(`{"error": "%s"}`, err)
    os.Exit(1)
}
```
but error handling logic
https://github.com/hashicorp/nomad/blob/5b76eb0535615e32faf4daee479f7155ea16ec0d/client/allocrunner/taskrunner/secrets/plugin_provider.go#L38-L44
will not print those error messages unless exit code from plugin is zero.

### PR DESCRIPTION
**Pull request by mismithhisler**
### Description

These changes attempt to improve the error messages of secret plugins.

### Links

Fixes #27226 
### Contributor Checklist
- [ ] **Changelog Entry** If this PR changes user-facing behavior, please generate and add a
  changelog entry using the `make cl` command.
- [ ] **Testing** Please add tests to cover any new functionality or to demonstrate bug fixes and
  ensure regressions will be caught.
- [ ] **Documentation** If the change impacts user-facing functionality such as the CLI, API, UI,
  and job configuration, please update the Nomad product documentation, which is stored in the
  [`web-unified-docs` repo](../web-unified-docs/). Refer to the [`web-unified-docs` contributor guide](../web-unified-docs/tree/docs/contribute.md) for docs guidelines.
  Please also consider whether the change requires notes within the [upgrade
  guide](https://developer.hashicorp.com/nomad/docs/upgrade/upgrade-specific). If you would like help with the docs, tag the `nomad-docs` team in this PR.

### Reviewer Checklist
- [ ] **Backport Labels** Please add the correct backport labels as described by the internal
  backporting document.
- [ ] **Commit Type** Ensure the correct merge method is selected which should be "squash and merge"
  in the majority of situations. The main exceptions are long-lived feature branches or merges where
  history should be preserved.
- [ ] **Enterprise PRs** If this is an enterprise only PR, please add any required changelog entry
  within the public repository.

- [ ] If a change needs to be reverted, we will roll out an update to the code within 7 days.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### CODE REVIEW

File: client/allocrunner/taskrunner/secrets/plugin_provider.go [hunk 1]
```diff
@@ -37,10 +37,10 @@ func NewExternalPluginProvider(plugin commonplugins.SecretsPlugin, name string,
 func (p *ExternalPluginProvider) Fetch(ctx context.Context) (map[string]string, error) {
 	resp, err := p.plugin.Fetch(ctx, p.path)
 	if err != nil {
-		return nil, fmt.Errorf("failed to fetch secret from plugin %s: %w", p.name, err)
+		return nil, fmt.Errorf("failed executing plugin for secret %q: %w", p.name, err)
```
Comment (gulducat) [inline client/allocrunner/taskrunner/secrets/plugin_provider.go]: would it be useful to also include the plugin (name) in the error message? or is that already part of the `err` being wrapped here?

Comment (mismithhisler) [reply client/allocrunner/taskrunner/secrets/plugin_provider.go]: It certainly couldn't hurt to have that information. I didn't add it because there is a one-to-one relationship between secrets and providers so I figured if a user knew the secret, they could easily find the plugin that errored.

Comment (gulducat) [reply client/allocrunner/taskrunner/secrets/plugin_provider.go]: ah I think I misunderstood something because of the code comment change above.

> // name of the secret

and this line

> plugin for secret %q

had me thinking it might be the path or something? like info about the secret itself, rather than the provider... so this is the "name of the provider" and that provider maps to one and only one plugin, so they're not identical, but tied closely together?

if so, I'd be less confused if the comment was `// name of the provider ...` and this line was

```suggestion
		return nil, fmt.Errorf("failed executing plugin for secret provider %q: %w", p.name, err)
```

Comment (mismithhisler) [reply client/allocrunner/taskrunner/secrets/plugin_provider.go]: This isn't the name of the provider though, its the name of the secret. So if you had a secret `my_secret` that used a custom provider plugin `my_plugin`, my thought was it should say `failed executing plugin for secret "my_secret": *some error*`. Although if this needs to be reworded, let me know.

Comment (gulducat) [reply client/allocrunner/taskrunner/secrets/plugin_provider.go]: Ok I think I have unconfused myself then, finally. (and read the open issue)

This `name` is the `my_secret` part of this secret block, yes?

```hcl
secret "my_secret" {
  provider = "my-provider"
}
```

If so, then your change makes good sense!

I still find myself wanting the provider/plugin name in there, too (as the issue reporter suggested `failed to fetch secret my_secret from plugin custom-provider`), but I think that'd be more of a lift, because `p.plugin` is an interface with no `Name()` method or such, so one would need to be added...

**Review by gulducat — DISMISSED** [review]
I'd like to include the plugin in the message, too, but this is an improvement!

**Comment by mismithhisler** [comment]
@gulducat It actually wouldn't be too hard to inject the provider parameter here (which is the plugin name) which could be used in the error message.

File: client/allocrunner/taskrunner/secrets/plugin_provider_test.go [hunk 2]
```diff
@@ -57,10 +57,10 @@ func TestExternalPluginProvider_Fetch(t *testing.T) {
 			Error:  &testError,
 		}, nil)
 
-		testProvider := NewExternalPluginProvider(mockSecretPlugin, "test", "test")
+		testProvider := NewExternalPluginProvider(mockSecretPlugin, "test-provider", "test", "test")
 
 		vars, err := testProvider.Fetch(t.Context())
-		must.ErrorContains(t, err, "secret \"test\" plugin response contained error")
+		must.ErrorContains(t, err, "provider \"test-provider\" for secret \"test\" response contained error")
```
Comment (gulducat) [inline client/allocrunner/taskrunner/secrets/plugin_provider_test.go:63]: ayyy nice :)

**Review by gulducat — APPROVED** [review]
lgtm!
