### PR TITLE
csi: the scheduler allows a job with a volume write claim to be updated

### LINKED ISSUE #7427: CSI: scheduler doesn't consider updated jobs
If you update a job that has CSI volume claims and the volume is at maximum capacity, the scheduler will fail feasibility checking, preventing the job from being updated. Error will look like this (after #7426):

```
▶ nomad job run csi/input/use-ebs-volume.nomad
==> Monitoring evaluation "4d6d0167"
    Evaluation triggered by job "use-ebs-volume"
    Evaluation within deployment: "927be2a6"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "4d6d0167" finished with status "complete" but failed to place all allocations:
    Task Group "group" (failed to place 1 allocation):
      * Constraint "CSI volume ebs-vol0 has exhausted its available writer claims or is read-only" filtered 2 nodes
```

### PR DESCRIPTION
**Pull request by langmartin**
fixes #7427

### CODE REVIEW

File: nomad/structs/csi.go [hunk 1]
```diff
@@ -296,29 +296,39 @@ func (v *CSIVolume) Stub() *CSIVolListStub {
 	return &stub
 }
 
-func (v *CSIVolume) CanReadOnly() bool {
+func (v *CSIVolume) ReadSchedulable() bool {
```
Comment (tgross) [inline nomad/structs/csi.go]: I like this naming change 👍
