### PR TITLE
docker: generate /etc/hosts file for bridge network mode

### LINKED ISSUE #8900: hostname not populated in /etc/hosts for Docker tasks with Connect
### Nomad version
Nomad v0.12.4 (8efaee4ba5e9727ab323aaba2ac91c2d7b572d84) cli

### Operating system and Environment details
Hosts Linux on EC2 Nomad v.0.12.3 Consul 0.1.8
Clients Linux on EC2 Nomad v.0.12.3 Consul 0.1.8

### Issue

When using "bridge" mode alongside with cni plugin, the mode of the container is still host

Hosts are currently not allowed to be set on host mode (should be default according to docs, but when using bridge with connect stanza doesn't honour the default)

This brings with it a series of challenges to applications (namely java ) that use hostname -f or -i or any sort of equivalent by getting local address based on hostname

### Reproduction steps

Enter a container running with consul connect in network "bridge" and try to do a reverse lookup using hostname -i
or hostname -f

hostname -I does return the ip attached to the container

### Job file (if appropriate)
```hcl
job "fail-at-host-resolution" {
  group "minio-group-wfm-job-find-fix" {
     network {
       mode = "bridge"
       port "http" {
         to = 9000
       }
     }
     service {
       name = "just-a-job-sample"
       port = 8080
       connect {
         sidecar_service {}
       }
     }
     task "ubuntu-resolution" {
       driver = "docker"
       config {
         image = "ubuntu"
         entrypoint = ["/bin/sh"]
         args = ["-ec", "sleep 1000"]
       }
     }
   }
}
````

If I try to use :
```hcl
driver = "docker"
config {
  network_mode=bridge
  ...
}
```

Hostname resolution works as expected, however the proxy is not available in localhost

### PR DESCRIPTION
**Pull request by tgross**
Fixes #8900 and #7746. This is heavily based on @nickethier's earlier work on [`/etc/resolv.conf`](https://github.com/hashicorp/nomad/tree/main/drivers/shared/resolvconf)

When `network.mode = "bridge"`, we create a pause container in Docker with no
networking so that we have a process to hold the network namespace we create
in Nomad. The default `/etc/hosts` file of that pause container is then used
for all the Docker tasks that share that network namespace. Some applications
rely on this file being populated.

This changeset generates a `/etc/hosts` file and bind-mounts it to the
container when Nomad owns the network, so that the container's hostname has an
IP in the file as expected. The hosts file will include the entries added by
the Docker driver's `extra_hosts` field.

In this changeset, only the Docker task driver will take advantage of this
option, as the `exec`/`java` drivers currently copy the host's `/etc/hosts`
file and this can't be changed without breaking backwards compatibility. But
the fields are available in the task driver protobuf for community task
drivers to use if they'd like.

---

With this changeset, and the following job:

<details><summary>jobspec</summary>

```hcl
job "example" {
  datacenters = ["dc1"]

  group "web" {

    network {
      mode = "bridge"
      port "www" {
        to = 8001
      }
    }

    task "httpd" {
      driver = "docker"

      config {
        image       = "busybox:1"
        command     = "httpd"
        args        = ["-v", "-f", "-p", "8001", "-h", "/local"]
        extra_hosts = ["wintermute:192.168.1.246"]
        ports       = ["www"]
      }

      template {
        data        = "<html>hello, world</html>"
        destination = "local/index.html"
      }

      resources {
        cpu    = 128
        memory = 128
      }
    }
  }
}

```

</details>

Results:

```
$ docker ps
CONTAINER ID   IMAGE                                      COMMAND                  CREATED         STATUS         PORTS     NAMES
34c0b3a0909c   busybox:1                                  "httpd -v -f -p 8001…"   7 seconds ago   Up 6 seconds             httpd-43714360-04ad-ff9c-d8b4-29d5c7961967
567fb409bebe   gcr.io/google_containers/pause-amd64:3.1   "/pause"                 8 seconds ago   Up 6 seconds             nomad_init_43714360-04ad-ff9c-d8b4-29d5c7961967

$ docker exec -it 34c hostname -f
567fb409bebe

$ docker exec -it 34c cat /etc/hosts
# this file was generated by Nomad
127.0.0.1 localhost
::1 localhost
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts

# this entry is the IP address and hostname of the allocation
# shared with tasks in the task group's network
172.26.64.185 567fb409bebe

# these entries are extra hosts added by the task config
192.168.1.246 wintermute
```

I've tested this out in non-bridge networking modes and we're correctly leaving everything untouched as expected.

### CODE REVIEW

File: client/allocrunner/network_hook.go [hunk 1]
```diff
@@ -9,6 +9,8 @@ import (
 	"github.com/hashicorp/nomad/plugins/drivers"
 )
 
+const dockerNetSpecLabelKey = "docker_sandbox_container_id"
```
Comment (notnoop) [inline client/allocrunner/network_hook.go:12]: The specific value surprised me, specially since I didn't see where it's set. I'd suggest adding context and referencing the key in drivers/docker/network.go .

File: client/allocrunner/network_hook.go [hunk 2]
```diff
@@ -106,7 +108,15 @@ func (h *networkHook) Prerun() error {
 		if err != nil {
 			return fmt.Errorf("failed to configure networking for alloc: %v", err)
 		}
-
+		if hostname, ok := spec.Labels[dockerNetSpecLabelKey]; ok {
+			if len(hostname) > 12 {
+				hostname = hostname[:12]
+			}
```
Comment (notnoop) [inline client/allocrunner/network_hook.go:114]: What's so special about 12?

File: drivers/shared/hostnames/mount.go [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+ff02::2 ip6-allrouters
+ff02::3 ip6-allhosts
+
+# this entry is the IP address and hostname of the allocation
+# shared with tasks in the task group's network
+%s %s
+`, hostsCfg.Address, hostsCfg.Hostname)
+
+	if len(extraHosts) > 0 {
+		content += "\n# these entries are extra hosts added by the task config"
```
Comment (notnoop) [inline drivers/shared/hostnames/mount.go:43]: My past made me cringe whenever I see `+=` string concatenation. [`strings.Builder`](https://golang.org/pkg/strings/#Builder) might be handy. It's not a big deal, as I hope the file is going to be small, and I don't know if golang is smarter under the hood about this.

**Review by notnoop — COMMENTED** [review]
Did a quick read and the approach seems good. A couple of minor comments you can consider, and plan to do another round of review later today.

File: client/allocrunner/network_hook.go (hunk 1 above)
Comment (tgross) [reply client/allocrunner/network_hook.go:12]: Good call.

File: client/allocrunner/network_hook.go (hunk 2 above)
Comment (tgross) [reply client/allocrunner/network_hook.go:114]: The `docker_sandbox_container_id` value is the full container ID, whereas Docker will set the hostname in the pause container as `docker_sandbox_container_id[:12]`. But we should certainly document that here!

File: drivers/shared/hostnames/mount.go (hunk 3 above)
Comment (tgross) [reply drivers/shared/hostnames/mount.go:43]: Fair enough, will fix.

File: drivers/shared/hostnames/mount.go [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+			if net.ParseIP(hostsEntry[1]) == nil {
+				return nil, fmt.Errorf("invalid IP address %q", hostLine)
+			}
+			content += fmt.Sprintf("\n%s %s", hostsEntry[1], hostsEntry[0])
+		}
+		content += "\n"
+	}
+
+	path := filepath.Join(taskDir, "hosts")
+	err := ioutil.WriteFile(path, []byte(content), 0755)
```
Comment (shoenig) [inline drivers/shared/hostnames/mount.go:58]: shouldn't this be `0644` ?

e.g. ubuntu docker image
```
root@5a686742ad73:/# ls -lha /etc/hosts
-rw-r--r-- 1 root root 174 Jun 16 15:02 /etc/hosts
``

Comment (tgross) [reply drivers/shared/hostnames/mount.go]: Yes! Fixed.

File: drivers/shared/hostnames/mount.go (hunk 3 above)
Comment (tgross) [reply drivers/shared/hostnames/mount.go]: Fixed in 40b1545

**Review by shoenig — APPROVED** [review]
LGTM; I like the thought of doing the same to `exec/java` in https://github.com/hashicorp/nomad/issues/10768 in the next feature release

File: website/content/docs/drivers/docker.mdx [hunk 5]
```diff
@@ -239,10 +239,12 @@ config {
...
-  The default `network_mode` for tasks that use [Connect] will be
-  `container:<name>`, where the name is the container name of the parent
-  container used to share network namespaces between tasks. You should not set
-  `network_mode` for Connect-enabled tasks.
+  The default `network_mode` for tasks that use group networking in [`bridge`]
+  mode will be `container:<name>`, where the name is the container name of the
+  parent container used to share network namespaces between tasks. If you set
+  the `network_mode` field in this case, the container will be unable to reach
+  other containers in the task group. This will prevent [Connect]-enabled
+  tasks from reaching the Envoy sidecar proxy. See [GH-10725].
```
Comment (notnoop) [inline website/content/docs/drivers/docker.mdx:247]: Not obvious to me the value of linking to the issue here. It doesn't seem to provide more info on why setting `network_mode` is a bad idea here, and seems to raise unanswered questions so far. If want feedback from customers, maybe we can make an explicit call to action.

**Review by notnoop — APPROVED** [review]
LGTM. Great - thanks!

File: website/content/docs/drivers/docker.mdx (hunk 5 above)
Comment (tgross) [reply website/content/docs/drivers/docker.mdx:247]: You're right, that's not helpful. I'll tweak the language a bit here to me more firm about why and then leave it at that.
