### PR TITLE
docker: set default cpu cfs period

### LINKED ISSUE #6261: Cpu hard limits do not work ( Nomad v0.9.5  )
### Nomad version
Output from `nomad version`
Nomad v0.9.5 (1cbb2b9a81b5715be2f201a4650293c9ae517b87)

### Operating system and Environment details
Codename:	xenial
Docker:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)

### Issue
After upgrade from 0.8 to 0.9.5 cpu hard limits do not work 

### Reproduction steps
Config:
```
name = "localhost"
bind_addr = "::"
datacenter = "dc1"
data_dir = "/var/lib/nomad"
disable_update_check = "true"
log_level = "TRACE"
options {
    "docker.auth.config" = "/root/.docker/config.json"
}
client {
  enabled = "true"

  node_class = "testnomad"
  network_interface = "eth0"
  servers = ["localhost"]
}
telemetry {
  publish_allocation_metrics = "true"
}
server {
  enabled = "true"
}
```

### Job file (if appropriate)

```
# job name
job "job1" {
  datacenters = ["dc1"]
  type = "service"

  group "group1" {
    count = 1
    task "task1" {
      kill_signal = "SIGTERM"
      driver = "docker"
      config {
        cpu_hard_limit = "true"
        image        = "registry/init:md5"
      }
      resources {
        memory = 256
        cpu = 1000
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)

In logs, after "nomad run":
> [DEBUG] client.driver_mgr.docker: configured resources: driver=docker task_name=task1 memory=268435456 cpu_shares=1000 cpu_quota=0 cpu_period=0

Metrics:

> nomad_client_allocs_cpu_throttled_periods{...} 0
> nomad_client_allocs_cpu_throttled_time{...} 0
> nomad_client_allocs_cpu_total_ticks{...} 2937.804931640625

### PR DESCRIPTION
**Pull request by nickethier**
This adds back the default cfs period that seems to have never been set from the 0.9 driver refactor, meaning that CPU hard limit would not have worked.

fixes #6261

### CODE REVIEW

File: drivers/docker/driver_test.go [hunk 1]
```diff
@@ -2498,3 +2502,28 @@ func TestDockerDriver_CreationIdempotent(t *testing.T) {
 		require.NoError(t, err)
 	})
 }
+
+func TestDockerDriver_CreateContainerConfig_CPUHardLimit(t *testing.T) {
```
Comment (schmichael) [inline drivers/docker/driver_test.go]:
```suggestion
// TestDockerDriver_CreateContainerConfig_CPUHardLimit asserts that a default
// CPU quota and period are set when cpu_hard_limit = true.
func TestDockerDriver_CreateContainerConfig_CPUHardLimit(t *testing.T) {
```

File: drivers/docker/driver_test.go [hunk 2]
```diff
@@ -13,12 +13,15 @@ import (
 	"testing"
 	"time"
 
+	"github.com/hashicorp/nomad/helper/pluginutils/hclspecutils"
```
Comment (schmichael) [inline drivers/docker/driver_test.go]: Why is this import so lonely?
