### PR TITLE
Accept vault token for job revert

### LINKED ISSUE #4555: Unable to revert a Nomad job with Vault policies when allow_unauthenticated is set to false
### Nomad version
Nomad v0.8.4

### Operating system and Environment details
CentOS 7.5

### Issue
Unable to revert to a previous revision of a job when `allow_unauthenticated` is set to false on the nomad server. We can create the job and the validation works. However when attempting to do a revert I get a 500 error that the Vault token is missing. This is a similar error I would receive if I did not provide a vault token when attempting a run.

### Reproduction steps
```
$ env | grep VAULT_TOKEN
VAULT_TOKEN=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx

$ nomad run artifacttest.nomad
==> Monitoring evaluation "38c8cd1b"
    Evaluation triggered by job "artifact-test"
    Evaluation within deployment: "e0bc827c"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "38c8cd1b" finished with status "complete"

$ nomad job history artifact-test
Version     = 8
Stable      = false
Submit Date = 2018-08-01T18:10:49-07:00

Version     = 7
Stable      = true
Submit Date = 2018-08-01T17:56:00-07:00

Version     = 6
Stable      = true
Submit Date = 2018-08-01T17:46:38-07:00

Version     = 5
Stable      = true
Submit Date = 2018-08-01T17:38:16-07:00

Version     = 4
Stable      = true
Submit Date = 2018-08-01T17:07:01-07:00

Version     = 3
Stable      = true
Submit Date = 2018-08-01T17:04:50-07:00

$ nomad job revert artifact-test 7
Error retrieving job versions: Unexpected response code: 500 (rpc error: Vault policies requested but missing Vault Token)

### Attempt to run WITHOUT Vault token
$ env | grep VAULT_TOKEN

$ nomad run artifacttest.nomad 
Error submitting job: Unexpected response code: 500 (rpc error: Vault policies requested but missing Vault Token)

```

### Job file (if appropriate)
```
job "artifact-test" {
  region      = "us-west"
  datacenters = ["dc1"]
  type        = "service"

  vault {
    policies = ["secret_policy"]
  }


  group "service-group" {

    count = 2

    task "test-task" {
      driver = "docker"

      config {
        image = "nginx:1.15.1-alpine"
      
        volumes = [ "local/:/usr/share/nginx/html" ]

        port_map {
          http = 80
        }
      }

      resources {
        cpu = 200
        memory = 128

        network {
          mbits = 1

          port "http" {}
        }
      }

      service {
        name = "artifact-test"
        port = "http"
        check {
          name = "artifact"
          type = "http"
          path = "/"
          interval = "10s"
          timeout = "5s"
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by cgbaker**
Consider `-vault-token` or `VAULT_TOKEN` on `nomad job revert ...`. Resolves #4555 

This was straightforward, plumbing all the way from the CLI through the HTTP API and to the RPC endpoints. The vault token is passed through the HTTP API in the JobRevertRequest body, instead of a header as originally discussed, because there wasn't a general way to get it in as a header without replumbing a lot of the (generic) http request work.

### CODE REVIEW

**Comment by cgbaker** [comment]
Not sure why Travis failed... will dig into it more before merge.

File: api/api.go [hunk 1]
```diff
@@ -26,7 +26,7 @@ var (
 	ClientConnTimeout = 1 * time.Second
 )
 
-// QueryOptions are used to parameterize a query
+// QueryOptions are used to parametrize a query
```
Comment (schmichael) [inline api/api.go]: TIL

File: api/jobs.go [hunk 2]
```diff
@@ -930,6 +931,12 @@ type JobRevertRequest struct {
 	// version before reverting.
 	EnforcePriorVersion *uint64
 
+	// VaultToken is the Vault token that proves the submitter of the job revert
+	// has access to any Vault policies specified in the targeted job version. This
+	// field is only used to transfer the token and is not stored after the Job
```
Comment (schmichael) [inline api/jobs.go]: Is this a little more accurate?

```suggestion
	// field is only used to authorize the revert and is not stored after the Job
```

File: command/job_revert.go [hunk 3]
```diff
@@ -32,6 +33,10 @@ Revert Options:
 
   -verbose
     Display full information.
+
+  -vault-token
```
Comment (schmichael) [inline command/job_revert.go]: Put before -verbose

File: nomad/job_endpoint.go [hunk 4]
```diff
@@ -441,8 +441,10 @@ func (j *Job) Revert(args *structs.JobRevertRequest, reply *structs.JobRegisterR
 	}
 
 	// Build the register request
+	revJob := jobV.Copy()
+	revJob.VaultToken = args.VaultToken
```
Comment (schmichael) [inline nomad/job_endpoint.go]: Let's comment this.

```suggestion
	// Use Vault Token from revert request to perform registration of reverted job.
	revJob.VaultToken = args.VaultToken
```

...or something like that?

File: nomad/job_endpoint_test.go [hunk 5]
```diff
@@ -1017,6 +1017,215 @@ func TestJobEndpoint_Revert(t *testing.T) {
...
+	revertReq.VaultToken = errToken
+	err = msgpackrpc.CallWithCodec(codec, "Job.Revert", revertReq, &resp)
+	if err == nil || !strings.Contains(err.Error(), expectedErr.Error()) {
+		t.Fatalf("expected permission denied error: %v", err)
+	}
+
+	// Use a good token
+	revertReq.VaultToken = revertGoodToken
+	if err := msgpackrpc.CallWithCodec(codec, "Job.Revert", revertReq, &resp); err != nil {
+		t.Fatalf("bad: %v", err)
```
Comment (schmichael) [inline nomad/job_endpoint_test.go]: Try to update these to `require.NoError` or `require.Fail` in new tests. Not a blocker.

File: nomad/job_endpoint_test.go [hunk 6]
```diff
@@ -1017,6 +1017,215 @@ func TestJobEndpoint_Revert(t *testing.T) {
...
+	}
+
+	// Fetch the response
+	err = msgpackrpc.CallWithCodec(codec, "Job.Revert", revertReq, &resp)
+	if err == nil || !strings.Contains(err.Error(), "missing Vault Token") {
+		t.Fatalf("expected Vault not enabled error: %v", err)
+	}
+}
+
+func TestJobEndpoint_Revert_Vault_Policies(t *testing.T) {
```
Comment (schmichael) [inline nomad/job_endpoint_test.go]: For big tests let's try to include a comment summarizing their intent. It helps when tests mysteriously fail long after they're written and no one is quite sure what exactly it was meant to be testing (although the name is pretty clear here).

```suggestion
// TestJobEndpoint_Revert_Vault_Policies asserts that job revert uses the
// revert request's Vault token when authorizing policies.
func TestJobEndpoint_Revert_Vault_Policies(t *testing.T) {
```

File: website/source/docs/commands/job/revert.html.md.erb [hunk 7]
```diff
@@ -12,6 +12,14 @@ The `job revert` command is used to revert a job to a prior version of the
 job. The available versions to revert to can be found using [`job
 history`](/docs/commands/job/history.html) command.
 
+The revert command will use a vault token with the following preference:
```
Comment (schmichael) [inline website/source/docs/commands/job/revert.html.md.erb]:
```suggestion
The revert command will use a Vault token with the following preference:
```

File: command/job_revert.go (hunk 3 above)
Comment (cgbaker) [reply command/job_revert.go]: doh! thanks.

File: api/api.go (hunk 1 above)
Comment (cgbaker) [reply api/api.go]: it's one of those i say out-loud when i'm typing.
