### PR TITLE
Fix client restart behavior for Connect

### LINKED ISSUE #6310: Network namespace parent containers lost after client restart
Our network namespaces are associated with ["pause" containers](https://www.nomadproject.io/docs/drivers/docker.html#infra_image). These containers stop when the Nomad client restarts, unlike similar "helpers" containers like logmon. This results our Consul Connect integration breaking because the Envoy proxy can no longer connect to upstreams.

cc @nickethier @schmichael but I'll start looking into this and writing up an e2e test that exercises the behavior this week.

### Nomad version

```
$ nomad version
Nomad v0.10.0-dev (32ad0eef31f0617941555b4b406d92e8986cf18d+CHANGES)
```

### Reproduction steps

We can replicate this easily with the e2e test environment, but it's easier to see with a single client node. Stand up the cluster, reduce it to 1 client node, and deploy the Consul connect demo job found at [./e2e/connect/input/demo.nomad](https://github.com/hashicorp/nomad/blob/master/e2e/connect/input/demo.nomad)

Details below.

```sh
# see our containers
$ sudo docker ps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS               NAMES
8685c7ba836e        envoyproxy/envoy:v1.11.1                   "/docker-entrypoint.…"   15 minutes ago      Up 15 minutes                           connect-proxy-count-dashboard-42aad652-bfa8-78e3-7f81-7e68dd72143e
7143679f3cb7        hashicorpnomad/counter-dashboard:v1        "./dashboard-service"    15 minutes ago      Up 15 minutes                           dashboard-42aad652-bfa8-78e3-7f81-7e68dd72143e
e02244038ea7        envoyproxy/envoy:v1.11.1                   "/docker-entrypoint.…"   15 minutes ago      Up 15 minutes                           connect-proxy-count-api-52292642-91ff-d5ef-6623-4c19ac67f5c1
be89be0697de        hashicorpnomad/counter-api:v1              "./counting-service"     15 minutes ago      Up 15 minutes                           web-52292642-91ff-d5ef-6623-4c19ac67f5c1
aeedfbe3f820        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 15 minutes ago      Up 15 minutes                           nomad_init_42aad652-bfa8-78e3-7f81-7e68dd72143e
1e2cf1c2546e        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 15 minutes ago      Up 15 minutes                           nomad_init_52292642-91ff-d5ef-6623-4c19ac67f5c1

# show the container that owns the API's namespace
$ sudo docker inspect $(sudo docker ps -q -f name=web) | jq -r '.[0].HostConfig.NetworkMode' | awk -F':' '{print $2}'
1e2cf1c2546ec3c1503c25ee7739de3ab0a01730aaac2afbeeb29a595a6361e2

# show the pause container's network settings
$ sudo docker inspect 1e2 | jq '.[0].NetworkSettings'
{
  "Bridge": "",
  "SandboxID": "8dc4a6a55d49b942320cb9629a3f4896c2fc366604bc8b9a24a0eaf510edf781",
  "HairpinMode": false,
  "LinkLocalIPv6Address": "",
  "LinkLocalIPv6PrefixLen": 0,
  "Ports": {},
  "SandboxKey": "/var/run/docker/netns/8dc4a6a55d49",
  "SecondaryIPAddresses": null,
  "SecondaryIPv6Addresses": null,
  "EndpointID": "",
  "Gateway": "",
  "GlobalIPv6Address": "",
  "GlobalIPv6PrefixLen": 0,
  "IPAddress": "",
  "IPPrefixLen": 0,
  "IPv6Gateway": "",
  "MacAddress": "",
  "Networks": {
    "none": {
      "IPAMConfig": null,
      "Links": null,
      "Aliases": null,
      "NetworkID": "9caae10b052f1ff6296cffffe3cff4e239848216fdcc7da1e82aac81842ca176",
      "EndpointID": "a558fadc576f285a51b1602645ceb2f121a74904cc7dd7d5c5523d51aded662e",
      "Gateway": "",
      "IPAddress": "",
      "IPPrefixLen": 0,
      "IPv6Gateway": "",
      "GlobalIPv6Address": "",
      "GlobalIPv6PrefixLen": 0,
      "MacAddress": "",
      "DriverOpts": null
    }
  }
}

# see happy Consul logs
$ journalctl -eu consul
...
Sep 11 15:15:26 ip-172-31-46-38 consul[2138]:     2019/09/11 15:15:26 [INFO] agent: Synced service "_nomad-task-42aad652-bfa8-78e3-7f81-7e68dd72143e-group-dashboard-count-dashboard-9002-sidecar-proxy"
Sep 11 15:17:01 ip-172-31-46-38 consul[2138]:     2019/09/11 15:17:01 [INFO] agent: Synced service "_nomad-task-52292642-91ff-d5ef-6623-4c19ac67f5c1-group-api-count-api-9001-sidecar-proxy"
Sep 11 15:17:02 ip-172-31-46-38 consul[2138]:     2019/09/11 15:17:02 [INFO] agent: Synced service "_nomad-task-42aad652-bfa8-78e3-7f81-7e68dd72143e-group-dashboard-count-dashboard-9002-sidecar-proxy"
Sep 11 15:18:23 ip-172-31-46-38 consul[2138]:     2019/09/11 15:18:23 [INFO] agent: Synced service "_nomad-task-42aad652-bfa8-78e3-7f81-7e68dd72143e-group-dashboard-count-dashboard-9002-sidecar-proxy"
Sep 11 15:18:23 ip-172-31-46-38 consul[2138]:     2019/09/11 15:18:23 [INFO] agent: Synced service "_nomad-task-52292642-91ff-d5ef-6623-4c19ac67f5c1-group-api-count-api-9001-sidecar-proxy"
Sep 11 15:20:22 ip-172-31-46-38 consul[2138]:     2019/09/11 15:20:22 [INFO] agent: Synced service "_nomad-task-52292642-91ff-d5ef-6623-4c19ac67f5c1-group-api-count-api-9001-sidecar-proxy"
Sep 11 15:20:22 ip-172-31-46-38 consul[2138]:     2019/09/11 15:20:22 [INFO] agent: Synced service "_nomad-task-42aad652-bfa8-78e3-7f81-7e68dd72143e-group-dashboard-count-dashboard-9002-sidecar-proxy"

# restart nomad
$ sudo systemctl restart nomad

# see new docker containers
$ sudo docker ps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS               NAMES
3e13c2f5250c        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 21 seconds ago      Up 20 seconds                           nomad_init_52292642-91ff-d5ef-6623-4c19ac67f5c1
f69a2c8325c2        gcr.io/google_containers/pause-amd64:3.0   "/pause"                 21 seconds ago      Up 20 seconds                           nomad_init_42aad652-bfa8-78e3-7f81-7e68dd72143e
8685c7ba836e        envoyproxy/envoy:v1.11.1                   "/docker-entrypoint.…"   16 minutes ago      Up 16 minutes                           connect-proxy-count-dashboard-42aad652-bfa8-78e3-7f81-7e68dd72143e
7143679f3cb7        hashicorpnomad/counter-dashboard:v1        "./dashboard-service"    16 minutes ago      Up 16 minutes                           dashboard-42aad652-bfa8-78e3-7f81-7e68dd72143e
e02244038ea7        envoyproxy/envoy:v1.11.1                   "/docker-entrypoint.…"   16 minutes ago      Up 16 minutes                           connect-proxy-count-api-52292642-91ff-d5ef-6623-4c19ac67f5c1
be89be0697de        hashicorpnomad/counter-api:v1              "./counting-service"     16 minutes ago      Up 16 minutes                           web-52292642-91ff-d5ef-6623-4c19ac67f5c1

# see our network mode is unchanged
$ sudo docker inspect $(sudo docker ps -q -f name=web) | jq -r '.[0].HostConfig.NetworkMode' | awk -F':' '{print $2}'
1e2cf1c2546ec3c1503c25ee7739de3ab0a01730aaac2afbeeb29a595a6361e2

# see both our new pause containers have different network namespaces
$ sudo docker inspect 3e1 | jq '.[0].NetworkSettings
...
$ sudo docker inspect f69 | jq '.[0].NetworkSettings
...

# see sadface Consul logs
$ journalctl -eu consul
Sep 11 15:27:02 ip-172-31-46-38 consul[2138]:     2019/09/11 15:27:02 [WARN] agent: Check "service:_nomad-task-52292642-91ff-d5ef-6623-4c19ac67f5c1-group-api-count-api-9001-sidecar-proxy:1" socket connection failed: dial tcp 127.0.0.1:25862: connect: connection refused
Sep 11 15:27:10 ip-172-31-46-38 consul[2138]:     2019/09/11 15:27:10 [WARN] agent: Check "service:_nomad-task-42aad652-bfa8-78e3-7f81-7e68dd72143e-group-dashboard-count-dashboard-9002-sidecar-proxy:1" socket connection failed: dial tcp 127.0.0.1:23810: connect: connection refused
Sep 11 15:27:12 ip-172-31-46-38 consul[2138]:     2019/09/11 15:27:12 [WARN] agent: Check "service:_nomad-task-52292642-91ff-d5ef-6623-4c19ac67f5c1-group-api-count-api-9001-sidecar-proxy:1" socket connection failed: dial tcp 127.0.0.1:25862: connect: connection refused
Sep 11 15:27:20 ip-172-31-46-38 consul[2138]:     2019/09/11 15:27:20 [WARN] agent: Check "service:_nomad-task-42aad652-bfa8-78e3-7f81-7e68dd72143e-group-dashboard-count-dashboard-9002-sidecar-proxy:1" socket connection failed: dial tcp 127.0.0.1:23810: connect: connection refused

# see unhappy proxy logs
$ sudo docker logs e02
[2019-09-11 15:22:12.608][1][info][main] [source/server/drain_manager_impl.cc:63] shutting down parent after drain
[2019-09-11 15:23:30.577][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 13,
[2019-09-11 15:23:30.730][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
[2019-09-11 15:23:31.409][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
[2019-09-11 15:23:32.790][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:87] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure

# see unhealthy services in Consul, in UI or with curl like
$ curl -s localhost:8500/v1/health/service/count-api-sidecar-proxy | jq '.[0].Checks[] | select(.Name=="Connect Sidecar Listening")'
{
  "Node": "ip-172-31-46-38",
  "CheckID": "service:_nomad-task-52292642-91ff-d5ef-6623-4c19ac67f5c1-group-api-count-api-9001-sidecar-proxy:1",
  "Name": "Connect Sidecar Listening",
  "Status": "critical",
  "Notes": "",
  "Output": "",
  "ServiceID": "_nomad-task-52292642-91ff-d5ef-6623-4c19ac67f5c1-group-api-count-api-9001-sidecar-proxy",
  "ServiceName": "count-api-sidecar-proxy",
  "ServiceTags": [],
  "Definition": {},
  "CreateIndex": 832,
  "ModifyIndex": 832
}
```

### Nomad logs

Unfortunately the Nomad logs don't seem to have anything helpful here but I've included them below for completeness.

<details><summary>Nomad client log</summary>

```
Sep 11 15:23:30 ip-172-31-46-38 systemd[1]: Stopping Nomad Agent...
Sep 11 15:23:30 ip-172-31-46-38 nomad[2961]: ==> Caught signal: interrupt
Sep 11 15:23:30 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:30.264Z [DEBUG] http: shutting down http server
Sep 11 15:23:30 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:30.264Z [INFO ] agent: requesting shutdown
Sep 11 15:23:00 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:00.824Z [DEBUG] client: updated allocations: index=170 total=7 pulled=0 filtered=7
Sep 11 15:23:00 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:00.824Z [DEBUG] client: allocation updates: added=0 removed=0 updated=0 ignored=7
Sep 11 15:23:00 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:00.824Z [DEBUG] client: allocation updates applied: added=0 removed=0 updated=0 ignored=7 errors=0
Sep 11 15:23:07 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:07.924Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=239.636µs
Sep 11 15:23:17 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:17.925Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=165.08µs
Sep 11 15:23:27 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:27.926Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=225.005µs
Sep 11 15:23:30 ip-172-31-46-38 systemd[1]: Stopping Nomad Agent...
Sep 11 15:23:30 ip-172-31-46-38 nomad[2961]: ==> Caught signal: interrupt
Sep 11 15:23:30 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:30.264Z [DEBUG] http: shutting down http server
Sep 11 15:23:30 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:30.264Z [INFO ] agent: requesting shutdown
Sep 11 15:23:30 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:30.264Z [INFO ] client: shutting down
Sep 11 15:23:30 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:30.264Z [DEBUG] client.vault: stopped
Sep 11 15:23:30 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:30.264Z [DEBUG] client.driver_mgr.docker: error collecting stats from container: container_id=8685c7ba836e8ef78081b8a7e6a1f24dedbd478bf433cdd
Sep 11 15:23:30 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:30.264Z [DEBUG] client.driver_mgr.docker: error collecting stats from container: container_id=7143679f3cb72a8f4622b1e14a43ace1977c8b2aafed4c5
Sep 11 15:23:30 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:30.265Z [DEBUG] client.driver_mgr.docker: error collecting stats from container: container_id=be89be0697de6aafc8db3169e6dbec095979120c400b52e
Sep 11 15:23:30 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:30.265Z [DEBUG] client.driver_mgr.docker: error collecting stats from container: container_id=e02244038ea7d37d88c36d2390c649d6bf4429b314b36c2
Sep 11 15:23:30 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:30.608Z [DEBUG] consul.sync: sync complete: registered_services=0 deregistered_services=2 registered_checks=0 deregistered_checks=0
Sep 11 15:23:30 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:30.775Z [DEBUG] client: updated allocations: index=190 total=7 pulled=0 filtered=7
Sep 11 15:23:31 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:31.552Z [INFO ] client.plugin: shutting down plugin manager: plugin-type=device
Sep 11 15:23:31 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:31.553Z [INFO ] client.plugin: plugin manager finished: plugin-type=device
Sep 11 15:23:31 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:31.553Z [INFO ] client.plugin: shutting down plugin manager: plugin-type=driver
Sep 11 15:23:31 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:31.572Z [DEBUG] consul.sync: sync complete: registered_services=0 deregistered_services=2 registered_checks=0 deregistered_checks=0
Sep 11 15:23:31 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:31.578Z [INFO ] client.plugin: plugin manager finished: plugin-type=driver
Sep 11 15:23:31 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:31.579Z [DEBUG] client.server_mgr: shutting down
Sep 11 15:23:31 ip-172-31-46-38 nomad[2961]:     2019-09-11T15:23:31.607Z [INFO ] agent: shutdown complete
Sep 11 15:23:31 ip-172-31-46-38 systemd[1]: nomad.service: Main process exited, code=exited, status=1/FAILURE
Sep 11 15:23:31 ip-172-31-46-38 systemd[1]: Stopped Nomad Agent.
Sep 11 15:23:31 ip-172-31-46-38 systemd[1]: nomad.service: Unit entered failed state.
Sep 11 15:23:31 ip-172-31-46-38 systemd[1]: nomad.service: Failed with result 'exit-code'.
Sep 11 15:23:31 ip-172-31-46-38 systemd[1]: Started Nomad Agent.
Sep 11 15:23:31 ip-172-31-46-38 nomad[8885]: ==> Loaded configuration from /etc/nomad.d/nomad.hcl
Sep 11 15:23:31 ip-172-31-46-38 nomad[8885]: ==> Starting Nomad agent...
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]: ==> Nomad agent configuration:
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:        Advertise Addrs: HTTP: 172.31.46.38:4646
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:             Bind Addrs: HTTP: 0.0.0.0:4646
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:                 Client: true
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:              Log Level: debug
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:                 Region: global (DC: dc1)
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:                 Server: false
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:                Version: 0.10.0-dev
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]: ==> Nomad agent started! Log data will stream in below:
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.677Z [WARN ] agent.plugin_loader: skipping external plugins since plugin_dir doesn't exist: plugin_dir=/opt/nomad/data/plugins
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.678Z [DEBUG] agent.plugin_loader.docker: using client connection initialized from environment: plugin_dir=/opt/nomad/data/plugins
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.678Z [DEBUG] agent.plugin_loader.docker: using client connection initialized from environment: plugin_dir=/opt/nomad/data/plugins
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.679Z [INFO ] agent: detected plugin: name=exec type=driver plugin_version=0.1.0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.679Z [INFO ] agent: detected plugin: name=qemu type=driver plugin_version=0.1.0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.679Z [INFO ] agent: detected plugin: name=java type=driver plugin_version=0.1.0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.679Z [INFO ] agent: detected plugin: name=docker type=driver plugin_version=0.1.0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.679Z [INFO ] agent: detected plugin: name=rkt type=driver plugin_version=0.1.0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.679Z [INFO ] agent: detected plugin: name=mock_driver type=driver plugin_version=0.1.0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.679Z [INFO ] agent: detected plugin: name=raw_exec type=driver plugin_version=0.1.0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.679Z [INFO ] agent: detected plugin: name=nvidia-gpu type=device plugin_version=0.1.0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.679Z [INFO ] client: using state directory: state_dir=/opt/nomad/data/client
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.679Z [INFO ] client: using alloc directory: alloc_dir=/opt/nomad/data/alloc
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.680Z [DEBUG] client.fingerprint_mgr: built-in fingerprints: fingerprinters="[arch cgroup consul cpu host memory network nomad signal stora
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.680Z [INFO ] client.fingerprint_mgr.cgroup: cgroups are available
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.680Z [DEBUG] client.fingerprint_mgr: fingerprinting periodically: fingerprinter=cgroup period=15s
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.682Z [INFO ] client.fingerprint_mgr.consul: consul agent is available
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.682Z [DEBUG] client.fingerprint_mgr: fingerprinting periodically: fingerprinter=consul period=15s
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.682Z [DEBUG] client.fingerprint_mgr.cpu: detected cpu frequency: MHz=2300
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.682Z [DEBUG] client.fingerprint_mgr.cpu: detected core count: cores=2
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.684Z [WARN ] client.fingerprint_mgr.network: unable to parse speed: path=/sbin/ethtool device=eth0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.684Z [DEBUG] client.fingerprint_mgr.network: unable to read link speed: path=/sys/class/net/eth0/speed
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.684Z [DEBUG] client.fingerprint_mgr.network: link speed could not be detected and no speed specified by user, falling back to default spee
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.684Z [DEBUG] client.fingerprint_mgr.network: detected interface IP: interface=eth0 IP=172.31.46.38
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.470Z [DEBUG] client.fingerprint_mgr: fingerprinting periodically: fingerprinter=vault period=15s
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.482Z [DEBUG] client.fingerprint_mgr.env_gce: could not read value for attribute: attribute=machine-type resp_code=404
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.482Z [DEBUG] client.fingerprint_mgr: detected fingerprints: node_attrs="[arch cgroup consul cpu host network nomad signal storage env_aws]
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.482Z [INFO ] client.plugin: starting plugin manager: plugin-type=driver
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.482Z [INFO ] client.plugin: starting plugin manager: plugin-type=device
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.482Z [DEBUG] client.plugin: waiting on plugin manager initial fingerprint: plugin-type=driver
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.482Z [DEBUG] client.plugin: waiting on plugin manager initial fingerprint: plugin-type=device
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.482Z [DEBUG] client.plugin: finished plugin manager initial fingerprint: plugin-type=device
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.483Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=mock_driver health=healthy description=Healthy
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.483Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=raw_exec health=healthy description=Healthy
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.483Z [DEBUG] client.consul: bootstrap contacting Consul DCs: consul_dcs=[dc1]
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.484Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=exec health=healthy description=Healthy
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.484Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=qemu health=undetected description=
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.488Z [INFO ] client.consul: discovered following servers: servers=172.31.33.33:4647,172.31.40.48:4647,172.31.46.188:4647
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.488Z [DEBUG] client.server_mgr: new server list: new_servers=172.31.33.33:4647,172.31.40.48:4647,172.31.46.188:4647 old_servers=
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.502Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=rkt health=healthy description=Healthy
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.542Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=docker health=healthy description=Healthy
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.553Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=java health=healthy description=Healthy
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.553Z [DEBUG] client.driver_mgr: detected drivers: drivers="map[healthy:[mock_driver raw_exec exec rkt docker java] undetected:[qemu]]"
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.553Z [DEBUG] client.plugin: finished plugin manager initial fingerprint: plugin-type=driver
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.562Z [INFO ] client: node registration complete
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.575Z [INFO ] client: started client: node_id=ca2fc04c-a92f-fb02-2a5f-19ef72d52812
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.580Z [INFO ] client.gc: marking allocation for GC: alloc_id=7bad80e1-7100-a9da-b768-794a043a9e09
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.581Z [INFO ] client.gc: marking allocation for GC: alloc_id=a097e6f6-36b7-e86b-e661-2894e8b5a6a3
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.581Z [INFO ] client.gc: marking allocation for GC: alloc_id=e60f2d66-e9b2-58cf-428d-2c36c31011be
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.581Z [DEBUG] client: updated allocations: index=190 total=7 pulled=0 filtered=7
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.582Z [DEBUG] client: allocation updates: added=0 removed=0 updated=0 ignored=7
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.582Z [DEBUG] client: allocation updates applied: added=0 removed=0 updated=0 ignored=7 errors=0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.582Z [INFO ] client.gc: marking allocation for GC: alloc_id=3c4e4be9-9d39-7ecc-b4e8-761678b49e32
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.583Z [INFO ] client.gc: marking allocation for GC: alloc_id=5aae65f6-3beb-a202-0a37-41cec4c424c0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.593Z [DEBUG] client: evaluations triggered by node update: num_evals=2
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.593Z [DEBUG] client: state updated: node_status=ready
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.601Z [DEBUG] consul.sync: sync complete: registered_services=1 deregistered_services=0 registered_checks=1 deregistered_checks=0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.893Z [DEBUG] client.driver_mgr.docker: docker pull succeeded: driver=docker image_ref=gcr.io/google_containers/pause-amd64:3.0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.894Z [DEBUG] client.driver_mgr.docker: image reference count incremented: driver=docker image_name=gcr.io/google_containers/pause-amd64:3.
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.894Z [DEBUG] client.driver_mgr.docker: image reference count incremented: driver=docker image_name=gcr.io/google_containers/pause-amd64:3.
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.923Z [DEBUG] client: updated allocations: index=196 total=7 pulled=0 filtered=7
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.923Z [DEBUG] client: allocation updates: added=0 removed=0 updated=0 ignored=7
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.923Z [DEBUG] client: allocation updates applied: added=0 removed=0 updated=0 ignored=7 errors=0
Sep 11 15:23:36 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:36.667Z [DEBUG] consul.sync: sync complete: registered_services=1 deregistered_services=0 registered_checks=0 deregistered_checks=0
Sep 11 15:23:37 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:37.646Z [DEBUG] consul.sync: sync complete: registered_services=1 deregistered_services=0 registered_checks=0 deregistered_checks=0
Sep 11 15:23:40 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:40.985Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=300.424µs
Sep 11 15:23:44 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:44.511Z [DEBUG] client: state changed, updating node and re-registering
Sep 11 15:23:44 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:44.520Z [INFO ] client: node registration complete
Sep 11 15:23:50 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:50.986Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=236.858µs
Sep 11 15:24:00 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:24:00.987Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=224.665µs
Sep 11 15:24:10 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:24:10.988Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=213.486µs
Sep 11 15:24:20 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:24:20.989Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=243.241µs
Sep 11 15:24:30 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:24:30.990Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=225.984µs
Sep 11 15:24:40 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:24:40.991Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=170.764µs
Sep 11 15:24:50 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:24:50.993Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=219.312µs
Sep 11 15:25:00 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:25:00.994Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=193.719µs
Sep 11 15:25:10 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:25:10.995Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=217.311µs
Sep 11 15:25:20 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:25:20.996Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=240.906µs
Sep 11 15:25:30 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:25:30.997Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=217.607µs
Sep 11 15:25:40 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:25:40.998Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=226.127µs
Sep 11 15:25:51 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:25:50.999Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=224.348µs
Sep 11 15:26:01 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:26:01.000Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=214.561µs
Sep 11 15:26:11 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:26:11.002Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=246.867µs
Sep 11 15:26:21 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:26:21.003Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=219.532µs
Sep 11 15:26:31 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:26:31.004Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=152.165µs
Sep 11 15:26:41 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:26:41.005Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=218.115µs
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.682Z [DEBUG] client.fingerprint_mgr.cpu: detected cpu frequency: MHz=2300
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.682Z [DEBUG] client.fingerprint_mgr.cpu: detected core count: cores=2
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.684Z [WARN ] client.fingerprint_mgr.network: unable to parse speed: path=/sbin/ethtool device=eth0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.684Z [DEBUG] client.fingerprint_mgr.network: unable to read link speed: path=/sys/class/net/eth0/speed
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.684Z [DEBUG] client.fingerprint_mgr.network: link speed could not be detected and no speed specified by user, falling back to default spee
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:31.684Z [DEBUG] client.fingerprint_mgr.network: detected interface IP: interface=eth0 IP=172.31.46.38
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.470Z [DEBUG] client.fingerprint_mgr: fingerprinting periodically: fingerprinter=vault period=15s
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.482Z [DEBUG] client.fingerprint_mgr.env_gce: could not read value for attribute: attribute=machine-type resp_code=404
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.482Z [DEBUG] client.fingerprint_mgr: detected fingerprints: node_attrs="[arch cgroup consul cpu host network nomad signal storage env_aws]
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.482Z [INFO ] client.plugin: starting plugin manager: plugin-type=driver
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.482Z [INFO ] client.plugin: starting plugin manager: plugin-type=device
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.482Z [DEBUG] client.plugin: waiting on plugin manager initial fingerprint: plugin-type=driver
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.482Z [DEBUG] client.plugin: waiting on plugin manager initial fingerprint: plugin-type=device
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.482Z [DEBUG] client.plugin: finished plugin manager initial fingerprint: plugin-type=device
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.483Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=mock_driver health=healthy description=Healthy
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.483Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=raw_exec health=healthy description=Healthy
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.483Z [DEBUG] client.consul: bootstrap contacting Consul DCs: consul_dcs=[dc1]
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.484Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=exec health=healthy description=Healthy
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.484Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=qemu health=undetected description=
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.488Z [INFO ] client.consul: discovered following servers: servers=172.31.33.33:4647,172.31.40.48:4647,172.31.46.188:4647
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.488Z [DEBUG] client.server_mgr: new server list: new_servers=172.31.33.33:4647,172.31.40.48:4647,172.31.46.188:4647 old_servers=
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.502Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=rkt health=healthy description=Healthy
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.542Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=docker health=healthy description=Healthy
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.553Z [DEBUG] client.driver_mgr: initial driver fingerprint: driver=java health=healthy description=Healthy
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.553Z [DEBUG] client.driver_mgr: detected drivers: drivers="map[healthy:[mock_driver raw_exec exec rkt docker java] undetected:[qemu]]"
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.553Z [DEBUG] client.plugin: finished plugin manager initial fingerprint: plugin-type=driver
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.562Z [INFO ] client: node registration complete
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.575Z [INFO ] client: started client: node_id=ca2fc04c-a92f-fb02-2a5f-19ef72d52812
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.580Z [INFO ] client.gc: marking allocation for GC: alloc_id=7bad80e1-7100-a9da-b768-794a043a9e09
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.581Z [INFO ] client.gc: marking allocation for GC: alloc_id=a097e6f6-36b7-e86b-e661-2894e8b5a6a3
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.581Z [INFO ] client.gc: marking allocation for GC: alloc_id=e60f2d66-e9b2-58cf-428d-2c36c31011be
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.581Z [DEBUG] client: updated allocations: index=190 total=7 pulled=0 filtered=7
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.582Z [DEBUG] client: allocation updates: added=0 removed=0 updated=0 ignored=7
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.582Z [DEBUG] client: allocation updates applied: added=0 removed=0 updated=0 ignored=7 errors=0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.582Z [INFO ] client.gc: marking allocation for GC: alloc_id=3c4e4be9-9d39-7ecc-b4e8-761678b49e32
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.583Z [INFO ] client.gc: marking allocation for GC: alloc_id=5aae65f6-3beb-a202-0a37-41cec4c424c0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.593Z [DEBUG] client: evaluations triggered by node update: num_evals=2
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.593Z [DEBUG] client: state updated: node_status=ready
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.601Z [DEBUG] consul.sync: sync complete: registered_services=1 deregistered_services=0 registered_checks=1 deregistered_checks=0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.893Z [DEBUG] client.driver_mgr.docker: docker pull succeeded: driver=docker image_ref=gcr.io/google_containers/pause-amd64:3.0
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.894Z [DEBUG] client.driver_mgr.docker: image reference count incremented: driver=docker image_name=gcr.io/google_containers/pause-amd64:3.
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.894Z [DEBUG] client.driver_mgr.docker: image reference count incremented: driver=docker image_name=gcr.io/google_containers/pause-amd64:3.
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.923Z [DEBUG] client: updated allocations: index=196 total=7 pulled=0 filtered=7
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.923Z [DEBUG] client: allocation updates: added=0 removed=0 updated=0 ignored=7
Sep 11 15:23:35 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:35.923Z [DEBUG] client: allocation updates applied: added=0 removed=0 updated=0 ignored=7 errors=0
Sep 11 15:23:36 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:36.667Z [DEBUG] consul.sync: sync complete: registered_services=1 deregistered_services=0 registered_checks=0 deregistered_checks=0
Sep 11 15:23:37 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:37.646Z [DEBUG] consul.sync: sync complete: registered_services=1 deregistered_services=0 registered_checks=0 deregistered_checks=0
Sep 11 15:23:40 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:40.985Z [DEBUG] http: request complete: method=GET path=/v1/agent/health?type=client duration=300.424µs
Sep 11 15:23:44 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:44.511Z [DEBUG] client: state changed, updating node and re-registering
Sep 11 15:23:44 ip-172-31-46-38 nomad[8885]:     2019-09-11T15:23:44.520Z [INFO ] client: node registration complete
```

</details>

### PR DESCRIPTION
**Pull request by tgross**
Fixes #6310 

I've pulled the test infrastructure work this requires out into #6313 and #6314 to keep the diff size reasonable. ~(Unit tests / linting won't pass till those are merged.)~ Done.

This fixes the client restart bug by:
- making sure we don't run AllocRunner post-run hooks during shutdown
- making the CreateNetwork call safe to re-run on start without recreating existing networks
- making sure the Consul proxy socket is recreated

cc @nickethier @schmichael

### CODE REVIEW

File: client/allocrunner/consulsock_hook.go [hunk 1]
```diff
@@ -159,7 +159,12 @@ func (s *sockProxy) run(alloc *structs.Allocation) error {
 	hostGRPCSockPath := filepath.Join(s.allocDir.AllocDir, allocdir.AllocGRPCSocket)
 	listener, err := net.Listen("unix", hostGRPCSockPath)
 	if err != nil {
-		return fmt.Errorf("unable to create unix socket for Consul gRPC endpoint: %v", err)
+		os.Remove(hostGRPCSockPath)
```
Comment (tgross) [inline client/allocrunner/consulsock_hook.go]: Note to reviewers: I'm not super-wild about this but I'm not catching the error from this because I want the `net.Listen` error to be what bubbles up to the user. Open to suggestions there.

File: drivers/docker/driver.go [hunk 2]
```diff
@@ -397,60 +397,26 @@ CREATE:
 	// If the container already exists determine whether it's already
 	// running or if it's dead and needs to be recreated.
 	if strings.Contains(strings.ToLower(createErr.Error()), "container already exists") {
-		containers, err := client.ListContainers(docker.ListContainersOptions{
-			All: true,
-		})
+
+		container, err := d.containerByName(config.Name)
```
Comment (tgross) [inline drivers/docker/driver.go]: Note for reviewers: I refactored this big chunk of logic in `createContainer` out to `containerByName` because I wanted to reuse it in `CreateNetwork`. We want callers to be able to determine what to do if the container already existed.

**Comment by tgross** [comment]
@nickethier and @schmichael it looks like I've got this working, so this should be ready for review. I've tested out both client restarts and job stops by hand, and run the included e2e test:

```
▶ go test -v ./e2e/ -run 'TestE2E/Connect/connect\.ConnectClientStateE2ETest/TestClientRestart'
=== RUN   TestE2E
=== RUN   TestE2E/Connect
=== RUN   TestE2E/Connect/*connect.ConnectClientStateE2ETest
=== RUN   TestE2E/Connect/*connect.ConnectClientStateE2ETest/TestClientRestart
--- PASS: TestE2E (18.62s)
    --- PASS: TestE2E/Connect (18.62s)
        --- PASS: TestE2E/Connect/*connect.ConnectClientStateE2ETest (18.24s)
            --- PASS: TestE2E/Connect/*connect.ConnectClientStateE2ETest/TestClientRestart (18.11s)
PASS
ok      github.com/hashicorp/nomad/e2e  18.881s
```

File: client/allocrunner/alloc_runner.go [hunk 3]
```diff
@@ -270,6 +270,14 @@ func (ar *allocRunner) Run() {
 	ar.runTasks()
 
 POST:
+	ar.destroyedLock.Lock()
```
Comment (nickethier) [inline client/allocrunner/alloc_runner.go]: Can we wrap this in a func?
```
if ar.isInShutdown() {
  return
}
``

File: client/allocrunner/consulsock_hook.go (hunk 1 above)
Comment (nickethier) [reply client/allocrunner/consulsock_hook.go]: Perhapse we check to see if the socket is found prior to calling `net.Listen`. If so, remove it since we're the creator if it anyways.

File: drivers/docker/driver.go [hunk 4]
```diff
@@ -1074,6 +1040,59 @@ func (d *Driver) detectIP(c *docker.Container, driverConfig *TaskConfig) (string
...
+
+	// container names with a / pre-pended to the Nomad generated container names
+	containerName := "/" + name
+	var (
+		shimContainer docker.APIContainers
+		found         bool
+	)
+OUTER:
+	for _, shimContainer = range containers {
+		d.logger.Debug("listed container", "names", hclog.Fmt("%+v", shimContainer.Names))
```
Comment (nickethier) [inline drivers/docker/driver.go]: trace?

File: drivers/docker/driver.go [hunk 5]
```diff
@@ -1074,6 +1040,59 @@ func (d *Driver) detectIP(c *docker.Container, driverConfig *TaskConfig) (string
...
+		for _, name := range shimContainer.Names {
+			if name == containerName {
+				d.logger.Debug("Found container",
```
Comment (nickethier) [inline drivers/docker/driver.go]: trace?

File: plugins/drivers/proto/driver.proto [hunk 6]
```diff
@@ -331,6 +331,7 @@ message CreateNetworkRequest {
 message CreateNetworkResponse {
 
     NetworkIsolationSpec isolation_spec = 1;
+    bool created = 2;
```
Comment (nickethier) [inline plugins/drivers/proto/driver.proto]: Can you document the meaning and use of created here

File: client/allocrunner/consulsock_hook.go (hunk 1 above)
Comment (tgross) [reply client/allocrunner/consulsock_hook.go]: I was worried about time-of-check/time-of-use there. But given that this method is marked "not safe for concurrent use" I don't think that's a problem. Will do.

**Comment by tgross** [comment]
@nickethier this should be ready for re-review.

File: drivers/docker/driver.go [hunk 7]
```diff
@@ -397,60 +397,26 @@ CREATE:
...
-			}
+		// Delete matching containers
+		err = client.RemoveContainer(docker.RemoveContainerOptions{
+			ID:    container.ID,
+			Force: true,
+		})
+		if err != nil {
+			d.logger.Error("failed to purge container", "container_id", container.ID)
+			return nil, recoverableErrTimeouts(fmt.Errorf("Failed to purge container %s: %s", container.ID, err))
+		} else if err == nil {
```
Comment (schmichael) [inline drivers/docker/driver.go]: Not your change but might as well fixup this weird extraneous conditional.

```suggestion
		} else {
```

File: drivers/docker/network.go [hunk 8]
```diff
@@ -29,35 +29,52 @@ func (d *Driver) CreateNetwork(allocID string) (*drivers.NetworkIsolationSpec, e
...
 	}
 
 	config, err := d.createSandboxContainerConfig(allocID)
 	if err != nil {
-		return nil, err
+		return nil, false, err
 	}
 
-	container, err := d.createContainer(client, *config, d.config.InfraImage)
+	specFromContainer := func(c *docker.Container) *drivers.NetworkIsolationSpec {
```
Comment (schmichael) [inline drivers/docker/network.go]: You could probably just create `container` here and skip the func, but this is a neat way to skip memory allocations for structs that may not be used.

Comment (tgross) [reply drivers/docker/network.go]: I was a little wary of creating a partial `NetworkIsolationSpec` and then populating the fields later just because it's the sort of thing that's easy for someone to come along later and return it early and expose a nil pointer exception in a field access. If you think the indirection of the function here isn't idiomatic I'd be happy to change it though.

**Comment by tgross** [comment]
I'm going to back out the Consul sock suggestion @nickethier made and just remove it unconditionally. There's some case that's still showing up here that's breaking my testing that wasn't showing up before.

**Comment by nickethier** [comment]
The appveyor failure looks like a flake
