### PR TITLE
bugfix: make sure streaming endpoints are only registered once

### LINKED ISSUE #15474: Job Endpoint concurrent map writes
Had a CI fail due to (almost certainly) unrelated changes; concurrent map writes on the Job endpoint

@pkazmierczak 
@jrasell 

```
FAIL nomad
=== RUN   TestACLEndpoint_GetAuthMethods
=== PAUSE TestACLEndpoint_GetAuthMethods
FAIL nomad.TestACLEndpoint_GetAuthMethods (-1.00s)
=== RUN   TestClientEndpoint_UpdateAlloc_Evals_ByTrigger
=== PAUSE TestClientEndpoint_UpdateAlloc_Evals_ByTrigger
FAIL nomad.TestClientEndpoint_UpdateAlloc_Evals_ByTrigger (-1.00s)
=== RUN   TestPlanEndpoint_ApplyConcurrent
=== PAUSE TestPlanEndpoint_ApplyConcurrent
FAIL nomad.TestPlanEndpoint_ApplyConcurrent (-1.00s)
=== RUN   TestRPC_streamingRpcConn_goodMethod_TLS
fatal error: concurrent map writes

goroutine 91524 [running]:
github.com/hashicorp/nomad/nomad/structs.(*StreamingRpcRegistry).Register(...)
	/home/runner/work/nomad/nomad/nomad/structs/streaming_rpc.go:42
github.com/hashicorp/nomad/nomad.(*ClientAllocations).register(...)
	/home/runner/work/nomad/nomad/nomad/client_alloc_endpoint.go:32
github.com/hashicorp/nomad/nomad.(*Server).setupRpcServer(0xc0046aedc0, 0xc005f65880?, 0xc0050bb220)
	/home/runner/work/nomad/nomad/nomad/server.go:1206 +0x16b
github.com/hashicorp/nomad/nomad.(*rpcHandler).handleMultiplexV2(0xc005bfd280, {0x29e92a0?, 0xc0066e5440}, {0x29f51f0?, 0xc005f65880}, 0xc0050bb220)
	/home/runner/work/nomad/nomad/nomad/rpc.go:494 +0x225
github.com/hashicorp/nomad/nomad.(*rpcHandler).handleConn(0xc005bfd280, {0x29e92a0, 0xc0066e5440}, {0x29f51f0, 0xc005f65880?}, 0xc0050bb220)
	/home/runner/work/nomad/nomad/nomad/rpc.go:352 +0xe45
github.com/hashicorp/nomad/nomad.(*rpcHandler).handleConn(0xc005bfd280, {0x29e92a0, 0xc0066e5440}, {0x29f74a8, 0xc005d9b148?}, 0xc0050bb220)
	/home/runner/work/nomad/nomad/nomad/rpc.go:332 +0x9bf
created by github.com/hashicorp/nomad/nomad.(*rpcHandler).listen
	/home/runner/work/nomad/nomad/nomad/rpc.go:183 +0x452
```

### PR DESCRIPTION
**Pull request by pkazmierczak**
Streaming RPCs should only be registered once, not on every RPC call, because they set keys in [`StreamingRpcRegistry.registry` map](https://github.com/hashicorp/nomad/blob/main/nomad/structs/streaming_rpc.go#L42). This PR fixes it by checking whether endpoints are already registered before calling `.register()` method. Fixes #15474

### CODE REVIEW

File: nomad/server.go [hunk 1]
```diff
@@ -1201,28 +1201,52 @@ func (s *Server) setupRpcServer(server *rpc.Server, ctx *RPCContext) error {
...
 	operatorEndpoint := NewOperatorEndpoint(s, ctx)
-	operatorEndpoint.register()
+
+	// streamingEndpoint is a helper interface to make working with endpoint
+	// structs easier
+	type streamingEndpoint interface {
+		register()
+	}
+
+	streaming_endpoints := map[string]streamingEndpoint{
```
Comment (tgross) [inline nomad/server.go:1226]: Hm, this ends up having to allocate this map every time we connect. Trying to test this without allocation seems like we'd need a lock or an atomic, which would be nice to avoid if we can.

What if we move the streaming registration out of this function entirely? This `setupRpcServer` gets called by both `setupRPC` (which is called once) and for each connection. That is, we can move the streaming endpoint registration into `setupRPC` (or into a new function it calls) and we know it'll only ever get called once.

Comment (tgross) [inline nomad/server.go:1226]: Hm, this ends up having to allocate this map every time we connect. Trying to test this without allocation seems like we'd need a lock or an atomic, which would be nice to avoid if we can.

What if we move the streaming registration out of this function entirely? This `setupRpcServer` gets called by both `setupRPC` (which is called once) and for each connection. That is, we can move the streaming endpoint registration into `setupRPC` (or into a new function it calls) and we know it'll only ever get called once.

**Review by tgross — CHANGES_REQUESTED** [review]

File: nomad/server.go (hunk 1 above)
Comment (pkazmierczak) [reply nomad/server.go]: I think I understand better now, thanks. Refactored.

File: nomad/server.go [hunk 2]
```diff
@@ -1193,62 +1193,41 @@ func (s *Server) setupRPC(tlsWrap tlsutil.RegionWrapper) error {
...
 }
 
-// setupRpcServer is used to populate an RPC server with endpoints. This gets
-// called at startup but also once for every new RPC connection so that RPC
-// handlers can have per-connection context.
-func (s *Server) setupRpcServer(server *rpc.Server, ctx *RPCContext) error {
-
+// setupStreamingEndpoints is used to populate an RPC server with streaming
+// endpoints. This only gets called at server startup.
+func (s *Server) setupStreamingEndpoints(server *rpc.Server, ctx *RPCContext) {
```
Comment (tgross) [inline nomad/server.go:1198]: This method never gets a `*RPContext`, so we can eliminate that parameter.

File: nomad/server.go [hunk 3]
```diff
@@ -1193,62 +1193,41 @@ func (s *Server) setupRPC(tlsWrap tlsutil.RegionWrapper) error {
...
-		if _, err := s.streamingRpcs.GetHandler(method); err != nil {
-			endpoint.register()
-		}
-	}
-
-	_ = server.Register(clientAllocs)
-	_ = server.Register(fsEndpoint)
-	_ = server.Register(agentEndpoint)
+	operatorEndpoint.register()
 	_ = server.Register(NewOperatorEndpoint(s, ctx))
```
Comment (tgross) [inline nomad/server.go:1224]: The client allocs, FS, agent, and operator endpoints all have non-streaming RPCs as well, so we should move these `_ = server.Register(..)` method calls into `setupRpcServer`. It looks like the event endpoint is the only one without a non-streaming method.

**Review by tgross — CHANGES_REQUESTED** [review]

File: nomad/server.go (hunk 2 above)
Comment (pkazmierczak) [reply nomad/server.go:1198]: 🤦‍♂️ right...

File: nomad/server.go (hunk 3 above)
Comment (pkazmierczak) [reply nomad/server.go:1224]: Good point.

File: nomad/server.go [hunk 4]
```diff
@@ -1221,14 +1216,26 @@ func (s *Server) setupRpcServer(server *rpc.Server, ctx *RPCContext) error {
...
 	_ = server.Register(NewClientCSIEndpoint(s))
 	_ = server.Register(NewClientStatsEndpoint(s))
 
+	// These endpoints have their streaming component registered in
+	// setupStreamingEndpoints, but their non-streaming RPCs are registered
+	// here.
+	_ = server.Register(NewClientAllocationsEndpoint(s))
+	_ = server.Register(NewFileSystemEndpoint(s))
+	_ = server.Register(NewAgentEndpoint(s))
+	_ = server.Register(NewOperatorEndpoint(s, nil))
```
Comment (tgross) [inline nomad/server.go:1237]:
```suggestion
	_ = server.Register(NewOperatorEndpoint(s, ctx))
```

**Review by tgross — APPROVED** [review]
I left one last item to make sure the operator endpoint has a context, but once that's included LGTM! Thanks for fixing this!

File: nomad/server.go (hunk 4 above)
Comment (pkazmierczak) [reply nomad/server.go:1237]: yikes, thanks for catching.
