### PR TITLE
consul: correctly check consul acl token namespace when using consul oss

### LINKED ISSUE #10718: Unable to submit Connect jobs when disabling allow_unauthenticated
Nomad v1.1.0 introduced consul namespaces support when using Nomad Enterprise + Consul Enterprise, however we broke functionality around ACL validation in the OSS use case. 

Jobs are incorrectly being blocked when following conditions are true
- Submitting a Consul Connect job
- Consul is OSS
- Consul ACLs are enabled
- Nomad's `allow_unauthenticated` is set to `false`

The error looks like,
```
$ nomad job run -consul-token 76221243-1631-e241-9b34-ffbcb6c36025 api.nomad 
Error submitting job: Unexpected response code: 500 (job-submitter consul token denied: consul ACL token cannot use namespace "default")
```

Which is nonsensical, since Namespaces do not exist in Consul OSS.

### PR DESCRIPTION
**Pull request by shoenig**
This PR fixes the Nomad Object Namespace <-> Consul ACL Token relationship
check when using Consul OSS (or Consul ENT without namespace support).

Nomad v1.1.0 introduced a regression where Nomad would fail the validation
when submitting Connect jobs and allow_unauthenticated set to true, with
Consul OSS - because it would do the namespace check against the Consul ACL
token assuming the "default" namespace, which does not work because Consul OSS
does not have namespaces.

Instead of making the bad assumption, expand the namespace check to handle
each special case explicitly.

Fixes #10718

### CODE REVIEW

File: nomad/consul_policy.go [hunk 1]
```diff
@@ -67,17 +67,43 @@ func (c *consulACLsAPI) isManagementToken(token *api.ACLToken) bool {
...
+	case namespace == token.Namespace:
+		// ACLs enabled, namespaces are the same
+		return nil
+
+	case namespace == "" && token.Namespace != "default":
+		// ACLs enabled with non-default token, but namespace on job not set, so
+		// provide a more informative error message.
+		return errors.Errorf("consul ACL token requires using namespace %q", token.Namespace)
+
+	default:
```
Comment (notnoop) [inline nomad/consul_policy.go:104]: I found it a tad harder to reason through conditions, maybe because of ordering. I would probably find it easier if the conditions were order the following way:

1. `namespace == token.Namespace`: either ACL not enabled, or it's enabled and they match
2. `token.Namespace == "default"`: special case
3. `token.Namespace != "default" && namespace == ""` <- `token.Namespace != "default"` is redundant here but included for explicitness
4. `default`: the mismatch case

File: nomad/consul_policy.go [hunk 2]
```diff
@@ -67,17 +67,43 @@ func (c *consulACLsAPI) isManagementToken(token *api.ACLToken) bool {
...
+
+	switch {
+	case namespace == "" && token.Namespace == "":
+		// ACLs not enabled (if Consul ACLs are enabled, the token response from
+		// consul will always set the namespace (to "default" if otherwise unset))
+		return nil
+
+	case token.Namespace == "default":
+		// ACLs enabled, must defer to per-object checking, since the token could
+		// have namespace_prefix blocks allowing the operation
```
Comment (notnoop) [inline nomad/consul_policy.go:92]: I'm not familiar with namespace_prefix. Is it only applicable if token's namespace is default? Why doesn't it apply in the default or `token.Namespace != "default"` cases? Is a special case for handling legacy apps only? Might be useful to add more context.

**Review by notnoop — COMMENTED** [review]
Few questions; approach seems reasonable.

File: nomad/consul_policy.go (hunk 2 above)
Comment (shoenig) [reply nomad/consul_policy.go:92]: Yep, Consul tokens can supply `namespace` or `namespace_prefix` blocks which give the token permission beyond the "default" namespace. Those blocks are only allowable in tokens in the "default" namespace. 

https://www.consul.io/docs/security/acl/acl-rules#namespace-rules

Expanded on the comment to clarify.

File: nomad/consul_policy.go (hunk 1 above)
Comment (shoenig) [reply nomad/consul_policy.go:104]: Thanks for this suggestion, this is easier to read :slightly_smiling_face:

File: nomad/consul_oss_test.go [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+		err := cAPI.CheckPermissions(context.Background(), namespace, usage, secretID)
+		if exp == nil {
+			require.NoError(t, err)
+		} else {
+			require.Equal(t, exp.Error(), err.Error())
+		}
+	}
+
+	t.Run("check-permissions kv read", func(t *testing.T) {
+		t.Run("uses kv has permission", func(t *testing.T) {
```
Comment (notnoop) [inline nomad/consul_oss_test.go:38]: I don't know how I personally feel about this style of nested `t.Run`: When the assertions are simply delegation to `try`, it feels a simple table tests might read better and is more concise.

**Review by notnoop — APPROVED** [review]
Looks great. Awesome tests. LGTM.

File: nomad/consul_oss_test.go (hunk 3 above)
Comment (shoenig) [reply nomad/consul_oss_test.go:38]: Yeah, for tests like these it's hard to find the right balance between readability of the code and readability of the _description_ of the test. By composing `t.Run` we get a free way of composing the description, making it obvious what the difference is between one particular test from the tests surrounding it. OTOH it's a lot of lines of code that aren't actually doing anything. I'll take a look at refactoring these tests some more after the bugfix release.

**Comment by shoenig** [comment]
Spot checking (oss Nomad + oss Consul)

```
$ nomad job run api.nomad
Error submitting job: Unexpected response code: 500 (job-submitter consul token denied: missing consul token)
$ nomad job run -consul-token $(uuid-tool) api.nomad
Error submitting job: Unexpected response code: 500 (job-submitter consul token denied: unable to read consul token: Unexpected response code: 403 (ACL not found))
$ nomad job run -consul-token 76221243-1631-e241-9b34-ffbcb6c36025 api.nomad
==> Monitoring evaluation "3d2dcf7f"
    Evaluation triggered by job "api"
    Evaluation within deployment: "8afe1793"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "3d2dcf7f" finished with status "complete"
```
