### PR TITLE
windows: Fix restarts using the raw_exec driver

### LINKED ISSUE #5803: Task failing with logmon failed to create fifo for extracting logs
### Nomad version
Affect versions: 
- Nomad v0.9.1 (4b2bdbd9ab68a27b10c2ee781cceaaf62e114399)
- Nomad v0.9.2
- Nomad v0.9.3
- Nomad v0.9.0

The issue is NOT present in Nomad v0.8.7.

### Operating system and Environment details
Windows 10 Pro, 64bit

### Issue
Task failing with logmon error:
logmon: rpc error: code = Unknown desc = failed to create fifo for extracting logs: open //./pipe/kapacitor-153973e1.stdout: Access is denied.

2019-06-10 10_44_36-Nomad

### Reproduction steps
- Download TICK executables from:
https://dl.influxdata.com/telegraf/releases/telegraf-1.3.5_windows_amd64.zip
https://dl.influxdata.com/chronograf/releases/chronograf-1.3.8.1_windows_amd64.zip
https://dl.influxdata.com/influxdb/releases/influxdb-1.3.5_windows_amd64.zip
https://dl.influxdata.com/kapacitor/releases/kapacitor-1.3.3_windows_amd64.zip
- from those extract the executables to: c:\tick\bin (you can refer yourself to the job file below)
- Load the job file
- Start the jobs

### Job file 
```
job "tick" {
  datacenters = ["dc1"]

  group "tick" {
	task "influxdb" {
	  driver = "raw_exec"

	  config {
		command = "C:\\tick\\bin\\influxd.exe"
		args = [
		  "-config",
		  "${NOMAD_TASK_DIR}/influxdb.conf"
		]
	  }

	  template {
		destination = "local/influxdb.conf"
		left_delimiter = "<<"
		right_delimiter = ">>"
		data = <<EOF
reporting-disabled = false
bind-address = "<<env `NOMAD_ADDR_influxrpc`>>"

[meta]
  dir = "<<env `NOMAD_TASK_DIR`|js>>\\meta"

[data]
  dir = "<<env `NOMAD_TASK_DIR`|js>>\\data"
  wal-dir = "<<env `NOMAD_TASK_DIR`|js>>\\wal"

[http]
  enabled = true
  bind-address = "<<env `NOMAD_ADDR_influxhttp`>>"
  https-enabled = false
  unix-socket-enabled = false

[[udp]]
  # Default UDP for Telegraf
  enabled = true
  bind-address = "<<env `NOMAD_ADDR_influxudp`>>" # the bind address
  database = "telegraf" # Name of the database that will be written to
  batch-size = 5000 # will flush if this many points get buffered
  batch-timeout = "1s" # will flush at least this often even if the batch-size is not reached
  batch-pending = 10 # number of batches that may be pending in memory
  read-buffer = 0 # UDP read buffer size, 0 means to use OS default

EOF
	  }

	  resources {
		network {
		  # Used for backup and restore
		  port "influxrpc" {
			# static = 8088
		  }
		  port "influxudp" {
			# static = 8089
		  }
		  port "influxhttp" {
			# HACK: Must be static for chronograph to work.
			static = 8086
		  }
		  mbits = 5
		}
	  }

	  service {
		name = "influxrpc"
		port = "influxrpc"

		check {
		  type = "tcp"
		  interval = "20s"
		  timeout = "2s"
		}
	  }

	  service {
		name = "influxhttp"
		port = "influxhttp"

		check {
		  type = "http"
		  path = "/ping"
		  interval = "20s"
		  timeout = "2s"
		}
	  }

	  service {
		name = "influxudp"
		port = "influxudp"

	  }
	  
	}

	task "kapacitor" {
	  driver = "raw_exec"

	  config {
		command = "C:\\tick\\bin\\kapacitord.exe"
		args = [
		  "-config",
		  "${NOMAD_TASK_DIR}\\kapacitor.conf"
		]
	  }

	  template {
		destination = "local/kapacitor.conf"
		left_delimiter = "<<"
		right_delimiter = ">>"
		data = <<EOF
httppost = []
data_dir = "<<env `NOMAD_TASK_DIR`|js>>\\data"
skip-config-overrides = false
default-retention-policy = ""

[http]
  bind-address = "<<env `NOMAD_ADDR_kapacitor`>>"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false
  shutdown-timeout = "10s"
  shared-secret = ""

[replay]
  dir = "<<env `NOMAD_TASK_DIR`|js>>\\replay"

[storage]
  boltdb = "<<env `NOMAD_TASK_DIR`|js>>\\kapacitor.db"

[task]
  dir = "<<env `NOMAD_TASK_DIR`|js>>\\tasks"
  snapshot-interval = "1m0s"

<<with service `influxhttp`>><<with index . 0>>
[[influxdb]]
  enabled = true
  name = "default"
  default = false
	<<if .Address | contains ":" >>
  urls = ["http://[<<.Address>>]:<<.Port>>"]
	<<else>>
	urls = ["http://<<.Address>>:<<.Port>>"]
	<<end>>
  insecure-skip-verify = false
  disable-subscriptions = false
  subscription-protocol = "http"
  [influxdb.excluded-subscriptions]
    _kapacitor = ["autogen"]
<<end>><<end>>

[logging]
  file = "STDERR"
  level = "INFO"

[config-override]
  enabled = true

EOF
	  }

	  resources {
		network {
		  port "kapacitor" {
			# HACK: Must be static for chronograph to work.
			static = 9092
		  }
		  mbits = 5
		}
	  }

	  service {
		name = "kapacitor"
		port = "kapacitor"

		check {
		  type = "tcp"
		  interval = "20s"
		  timeout = "2s"
		}
	  }
	}

	task "chronograf" {
	  driver = "raw_exec"

	  config {
		command = "C:\\tick\\bin\\chronograf.exe"
		args = [
		  "/host:${NOMAD_IP_chronograf}",
		  "/port:${NOMAD_PORT_chronograf}",
		  "/bolt-path:${NOMAD_TASK_DIR}/chronograf-v1.db",
		]
	  }

	   	template {
	   	  left_delimiter = "<<"
	   	  right_delimiter = ">>"
	   	  destination = "local/chronograf.env"
	   	  data = <<EOF
	   <<with service `influxhttp`>><<with index . 0>>
		 <<if .Address | contains ":">>
	   INFLUXDB_URL=http://[<<.Address>>]:<<.Port>>
	   <<else>>
		 INFLUXDB_URL=http://<<.Address>>:<<.Port>>
		 <<end>>
		 <<with service `kapacitor`>><<with index . 0>>
		 <<if .Address | contains ":">>
	   KAPACITOR_URL=http://[<<.Address>>]:<<.Port>>
		 <<else>>
		 KAPACITOR_URL=http://<<.Address>>:<<.Port>>
		 <<end>>
	   <<end>><<end>><<end>><<end>>
	   EOF
	   	  env = true
	   	}

	  resources {
		network {
		  port "chronograf" {
		  }
		  mbits = 5
		}
	  }

	  service {
		name = "chronograf"
		port = "chronograf"
		check {
		  type = "http"
		  path = "/"
		  interval = "10s"
		  timeout  = "2s"		
		}
	  }
	}
  }
}
```

### Nomad Client logs (if appropriate)
```
 2019-06-10T14:19:04.201-0400 [INFO ] client.alloc_runner.task_runner.task_hook.logmon.nomad.exe: opening fifo: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 task=kapacitor @module=logmon path=//./pipe/kapacitor-2cd52e07.stdout timestamp=2019-06-10T14:19:04.201-0400
    2019-06-10T14:19:04.202-0400 [INFO ] client.alloc_runner.task_runner.task_hook.logmon.nomad.exe: opening fifo: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 task=kapacitor @module=logmon path=//./pipe/kapacitor-2cd52e07.stderr timestamp=2019-06-10T14:19:04.201-0400
    2019/06/10 14:19:04.203209 [INFO] (runner) creating new runner (dry: false, once: false)
    2019/06/10 14:19:04.203209 [INFO] (runner) creating watcher
    2019/06/10 14:19:04.203705 [INFO] (runner) starting
    2019-06-10T14:19:04.206-0400 [INFO ] client.alloc_runner.task_runner.task_hook.logmon.nomad.exe: opening fifo: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 task=influxdb @module=logmon path=//./pipe/influxdb-128b35b7.stdout timestamp=2019-06-10T14:19:04.206-0400
    2019-06-10T14:19:04.212-0400 [INFO ] client.alloc_runner.task_runner.task_hook.logmon.nomad.exe: opening fifo: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 task=influxdb @module=logmon path=//./pipe/influxdb-128b35b7.stderr timestamp=2019-06-10T14:19:04.212-0400
    2019-06-10T14:19:04.212-0400 [INFO ] client.alloc_runner.task_runner.task_hook.logmon.nomad.exe: opening fifo: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 task=chronograf @module=logmon path=//./pipe/chronograf-e7084e4d.stdout timestamp=2019-06-10T14:19:04.212-0400
    2019-06-10T14:19:04.213-0400 [INFO ] client.alloc_runner.task_runner.task_hook.logmon.nomad.exe: opening fifo: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 task=chronograf @module=logmon path=//./pipe/chronograf-e7084e4d.stderr timestamp=2019-06-10T14:19:04.213-0400
    2019/06/10 14:19:04.213625 [INFO] (runner) creating new runner (dry: false, once: false)
    2019/06/10 14:19:04.214121 [INFO] (runner) creating watcher
    2019/06/10 14:19:04.214121 [INFO] (runner) starting
    2019/06/10 14:19:04.214121 [INFO] (runner) creating new runner (dry: false, once: false)
    2019/06/10 14:19:04.214121 [INFO] (runner) creating watcher
    2019/06/10 14:19:04.214617 [INFO] (runner) starting
    2019/06/10 14:19:04.217605 [INFO] (runner) rendered "(dynamic)" => "C:\\Users\\Owner\\.genvid\\nomad\\data\\alloc\\3167c038-6a1c-fb41-2476-34bb7c621bb6\\kapacitor\\local\\kapacitor.conf"
    2019-06-10T14:19:04.218-0400 [WARN ] client.alloc_runner.task_runner: some environment variables not available for rendering: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 task=kapacitor keys=
    2019-06-10T14:19:04.218-0400 [INFO ] client.driver_mgr.raw_exec: starting task: driver=raw_exec driver_cfg="{Command:C:\repos\fast\samples\tick\bin\kapacitord.exe Args:[-config C:\Users\Owner\.genvid\nomad\data\alloc\3167c038-6a1c-fb41-2476-34bb7c621bb6\kapacitor\local\kapacitor.conf]}"
    2019/06/10 14:19:04.221563 [INFO] (runner) rendered "(dynamic)" => "C:\\Users\\Owner\\.genvid\\nomad\\data\\alloc\\3167c038-6a1c-fb41-2476-34bb7c621bb6\\influxdb\\local\\influxdb.conf"
    2019/06/10 14:19:04.222062 [INFO] (runner) rendered "(dynamic)" => "C:\\Users\\Owner\\.genvid\\nomad\\data\\alloc\\3167c038-6a1c-fb41-2476-34bb7c621bb6\\chronograf\\local\\chronograf.env"
    2019-06-10T14:19:04.222-0400 [WARN ] client.alloc_runner.task_runner: some environment variables not available for rendering: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 task=chronograf keys=
    2019-06-10T14:19:04.222-0400 [WARN ] client.alloc_runner.task_runner: some environment variables not available for rendering: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 task=influxdb keys=
    2019-06-10T14:19:04.223-0400 [INFO ] client.driver_mgr.raw_exec: starting task: driver=raw_exec driver_cfg="{Command:C:\repos\fast\samples\tick\bin\chronograf.exe Args:[/host:::1 /port:28027 /bolt-path:C:\Users\Owner\.genvid\nomad\data\alloc\3167c038-6a1c-fb41-2476-34bb7c621bb6\chronograf\local/chronograf-v1.db]}"
    2019-06-10T14:19:04.223-0400 [INFO ] client.driver_mgr.raw_exec: starting task: driver=raw_exec driver_cfg="{Command:C:\repos\fast\samples\tick\bin\influxd.exe Args:[-config C:\Users\Owner\.genvid\nomad\data\alloc\3167c038-6a1c-fb41-2476-34bb7c621bb6\influxdb\local/influxdb.conf]}"
    2019/06/10 14:19:06.404288 [INFO] (runner) rendered "(dynamic)" => "C:\\Users\\Owner\\.genvid\\nomad\\data\\alloc\\3167c038-6a1c-fb41-2476-34bb7c621bb6\\chronograf\\local\\chronograf.env"
    2019/06/10 14:19:06.404288 [INFO] (runner) rendered "(dynamic)" => "C:\\Users\\Owner\\.genvid\\nomad\\data\\alloc\\3167c038-6a1c-fb41-2476-34bb7c621bb6\\kapacitor\\local\\kapacitor.conf"
    2019/06/10 14:19:06.418174 [INFO] (runner) rendered "(dynamic)" => "C:\\Users\\Owner\\.genvid\\nomad\\data\\alloc\\3167c038-6a1c-fb41-2476-34bb7c621bb6\\chronograf\\local\\chronograf.env"
    2019/06/10 14:19:06.419166 [INFO] (runner) rendered "(dynamic)" => "C:\\Users\\Owner\\.genvid\\nomad\\data\\alloc\\3167c038-6a1c-fb41-2476-34bb7c621bb6\\kapacitor\\local\\kapacitor.conf"
    2019-06-10T14:19:09.119-0400 [WARN ] client.driver_mgr.raw_exec.executor: error closing client during Kill: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 driver=raw_exec task_name=kapacitor err="rpc error: code = Canceled desc = grpc: the client connection is closing"
    2019-06-10T14:19:09.119-0400 [WARN ] client.driver_mgr.raw_exec.executor: plugin failed to exit gracefully: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 driver=raw_exec task_name=kapacitor
    2019-06-10T14:19:09.119-0400 [ERROR] client.driver_mgr.raw_exec: error receiving stream from Stats executor RPC, closing stream: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 driver=raw_exec task_name=kapacitor error="rpc error: code = Unavailable desc = transport is closing"
    2019-06-10T14:19:09.135-0400 [INFO ] client.alloc_runner.task_runner: restarting task: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 task=kapacitor reason= delay=0s
    2019-06-10T14:19:09.139-0400 [INFO ] client.alloc_runner.task_runner.task_hook.logmon.nomad.exe: opening fifo: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 task=kapacitor @module=logmon path=//./pipe/kapacitor-2cd52e07.stdout timestamp=2019-06-10T14:19:09.139-0400
    2019-06-10T14:19:09.139-0400 [ERROR] client.alloc_runner.task_runner.task_hook: failed to start logmon: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 task=kapacitor error="rpc error: code = Unknown desc = failed to create fifo for extracting logs: open //./pipe/kapacitor-2cd52e07.stdout: Access is denied."
    2019-06-10T14:19:09.139-0400 [ERROR] client.alloc_runner.task_runner: prestart failed: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 task=kapacitor error="prestart hook "logmon" failed: rpc error: code = Unknown desc = failed to create fifo for extracting logs: open //./pipe/kapacitor-2cd52e07.stdout: Access is denied."
    2019-06-10T14:19:09.139-0400 [INFO ] client.alloc_runner.task_runner: not restarting task: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 task=kapacitor reason="Error was unrecoverable"
    2019-06-10T14:19:09.163-0400 [ERROR] client.driver_mgr.raw_exec: error receiving stream from Stats executor RPC, closing stream: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 driver=raw_exec task_name=influxdb error="rpc error: code = Unavailable desc = transport is closing"
    2019-06-10T14:19:09.172-0400 [ERROR] client.driver_mgr.raw_exec: error receiving stream from Stats executor RPC, closing stream: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6 driver=raw_exec task_name=chronograf error="rpc error: code = Unavailable desc = transport is closing"
    2019/06/10 14:19:09.210163 [INFO] (runner) stopping
    2019/06/10 14:19:09.210163 [INFO] (runner) received finish
    2019/06/10 14:19:09.254509 [INFO] (runner) stopping
    2019/06/10 14:19:09.254509 [INFO] (runner) received finish
    2019/06/10 14:19:09.254509 [INFO] (runner) stopping
    2019/06/10 14:19:09.255006 [INFO] (runner) received finish
    2019-06-10T14:19:09.255-0400 [INFO ] client.gc: marking allocation for GC: alloc_id=3167c038-6a1c-fb41-2476-34bb7c621bb6
```

### PR DESCRIPTION
**Pull request by endocrimes**
fixes #5803

This currently uses a personal fork of `go-winio` to add an api that can safely open multiple listeners for a named pipe.

It fixes local restarts on Windows by:
- No longer trying to recreate named pipes that already exist
- Correctly closing connections when stopping a Read

### CODE REVIEW

**Comment by nickethier** [comment]
Instead of repackaging we could use `govendor fetch github.com/microsoft/go-winio::github.com/endocrimes/go-winio` to keep the same paths. This seems like something we should try and upstream if possible so we don't have to maintain a fork.

File: client/logmon/logmon.go [hunk 1]
```diff
@@ -211,24 +223,24 @@ func newLogRotatorWrapper(path string, logger hclog.Logger, rotator *logging.Fil
...
+		reader, err := openFn()
+		close(l.openCompleted)
 		if err != nil {
-			close(l.openCompleted)
-			l.logger.Warn("failed to open log fifo", "error", err)
+			l.logger.Warn("failed to open fifo", "error", err)
 			return
 		}
 		l.processOutReader = reader
-		close(l.openCompleted)
```
Comment (notnoop) [inline client/logmon/logmon.go]: `l.openCompleted` channel is currently synchronizing access for `l.processOutReader` which is accessed in a goroutine in https://github.com/hashicorp/nomad/blob/f3652ee95bc80cf5cb0d1750e8ab9c85ed5febe6/client/logmon/logmon.go#L278-L284 .

File: client/lib/fifo/fifo_test.go [hunk 2]
```diff
@@ -50,13 +48,14 @@ func TestFIFO(t *testing.T) {
...
 
-		var err error
-		reader, err = readerOpenFn()
 		assert.NoError(t, err)
 		if err != nil {
 			return
 		}
 
+		reader, err = openFn()
+		require.NoError(err)
```
Comment (notnoop) [inline client/lib/fifo/fifo_test.go]: I think there a couple of issues here:
* In the goroutine, we cannot use `require.NoError` effectively, so must use `assert` instead.
* We want to have a goroutine specific error variable rather than reuse the err variable in multiple goroutine and have race conditions.  With this change, `assert.NoError(t, err)` currently assert on errors unrelated to the goroutine.

Any particular issue here you tried to address with this change?

File: client/lib/fifo/fifo_test.go [hunk 3]
```diff
@@ -95,23 +95,23 @@ func TestWriteClose(t *testing.T) {
...
```
Comment (notnoop) [inline client/lib/fifo/fifo_test.go]: Same as above

File: client/lib/fifo/fifo_unix.go [hunk 4]
```diff
@@ -21,11 +21,13 @@ func CreateAndRead(path string) (func() (io.ReadCloser, error), error) {
 		return nil, fmt.Errorf("error creating fifo %v: %v", path, err)
 	}
 
-	openFn := func() (io.ReadCloser, error) {
+	return func() (io.ReadCloser, error) {
 		return os.OpenFile(path, unix.O_RDONLY, os.ModeNamedPipe)
-	}
+	}, nil
```
Comment (notnoop) [inline client/lib/fifo/fifo_unix.go]: Would it make sense to have the `unix` and `Windows` behave the same?  So `CreateAndRead` fails if the file is already present?  Or have the windows `CreateAndRead` handle if file is already present by using `winio.ListenOnlyPipe` (which may simplify the openfunction call)?

Have the subtle difference in behavior makes it notice this issue as we don't test with Windows much.

File: client/logmon/logmon.go (hunk 1 above)
Comment (endocrimes) [reply client/logmon/logmon.go]: oh yep - this was a totally accidental change as I was reverting some other stuff.

File: client/lib/fifo/fifo_test.go (hunk 2 above)
Comment (endocrimes) [reply client/lib/fifo/fifo_test.go]: Nope - This is a hangover from another change, I'll revert it.

File: client/lib/fifo/fifo_unix.go (hunk 4 above)
Comment (endocrimes) [reply client/lib/fifo/fifo_unix.go]: I'll can make the unix implementation fail on file exist errors, but I'm not sure it's actually worth it. Trying to make the windows implementation behave like unix is going to bite us in too many ways.

Comment (notnoop) [reply client/lib/fifo/fifo_unix.go]: I guess we can call out at the documentation behavior in the doc - i.e. call out that if `CreateAndRead` behavior is undefined or platform-specific if path already exists.  But I suspect making it a well-defined consistent behavior is better though.

Comment (endocrimes) [reply client/lib/fifo/fifo_unix.go]: FWIW we already call it out in the `godoc`, but I guess most people only see `linux|posixish|unix` docs.

Comment (notnoop) [reply client/lib/fifo/fifo_unix.go]: Ideally the docs for the function is the same in all files, or that we link to each other. It's quite fragile otherwise imo and a recipe for folks missing subtitles based on what files they happened to open.

File: client/logmon/logmon_test.go [hunk 5]
```diff
@@ -16,13 +17,23 @@ import (
 
 func TestLogmon_Start_rotate(t *testing.T) {
 	require := require.New(t)
+
+	stdoutLog := "stdout"
+	stderrLog := "stderr"
```
Comment (notnoop) [inline client/logmon/logmon_test.go]: Do you happen to know the value of having these as variables or their significance?  If they aren't used anywhere else, I might suggest using literal in the `LogConfig` initialization directly.

File: client/lib/fifo/fifo_windows.go [hunk 6]
```diff
@@ -64,6 +65,11 @@ func (f *winFIFO) Write(p []byte) (n int, err error) {
 }
 
 func (f *winFIFO) Close() error {
+	f.connLock.Lock()
+	if f.conn != nil {
+		f.conn.Close()
+	}
+	f.connLock.Unlock()
```
Comment (notnoop) [inline client/lib/fifo/fifo_windows.go]: How would the lock interact with a Read call?   A Read call will block while holding the `f.connLock` which would then block `Close()`.

Curious - why not initialize `f.conn` in the open functions?  It would avoid the lock and checking `f.conn` in Read and `Write`?

Comment (endocrimes) [reply client/lib/fifo/fifo_windows.go]: Waiting for an Accept in the `Open` call would block indefinitely during some more-edgier cases. It should be safe to reduce the scope of the lock however, to make this a little bit better if we don't have any parallel read/writes going on.

File: client/logmon/logmon_test.go (hunk 5 above)
Comment (endocrimes) [reply client/logmon/logmon_test.go]: I have no idea. I assume they were used prior to some past refactoring somewhere else.

File: client/lib/fifo/fifo_windows.go (hunk 6 above)
Comment (notnoop) [reply client/lib/fifo/fifo_windows.go]: FWIW, the linux fifo implementation also blocks indefinitely, as logmon reader blocks until the writer opens.  As such, logmon ensures that the open happens in non-main goroutine.  But yeah, having a finer scoped lock would be ok too.

File: client/lib/fifo/fifo_windows.go [hunk 7]
```diff
@@ -31,6 +31,7 @@ func (f *winFIFO) Read(p []byte) (n int, err error) {
 
 		f.conn = c
 	}
+	f.connLock.Unlock()
```
Comment (notnoop) [inline client/lib/fifo/fifo_windows.go]: The pattern of using `f.connLock` for synchronizing some `f.conn` accesses but not others feel a bit odd and raises a yellow flag even if it's correct.  I'm not sure if our tests run these paths in goroutines for `-race` to pick it up and reading memory model[1] doesn't fell me with confidence about this.

I would suggest setting a local variable to `conn := f.conn` inside the lock and using it in rest of function or comment why this pattern is valid; if for nothing else to ease future reviewer of code.

[1] https://golang.org/ref/mem#tmp_8

File: client/lib/fifo/fifo_windows.go [hunk 8]
```diff
@@ -31,6 +31,7 @@ func (f *winFIFO) Read(p []byte) (n int, err error) {
```
Comment (notnoop) [inline client/lib/fifo/fifo_windows.go]: Also, need to unlock before returning in line 29.
