### PR TITLE
client: avoid unconsumed channel in timer construction

### LINKED ISSUE #15198: Restart-Stanza: Delay not working
### Nomad version
1.4.1

### Operating system and Environment details
System:      Linux 4.18.0-372.26.1.el8_6.x86_64 x86_64 (Rocky Linux release 8.6 (Green Obsidian))

### Issue
The delay paraemeter in the restart-stanza is not working as expected. 

### Reproduction steps
Execute the attached jobs-specifcation

#### Expected Result
The job should restart in approx 15 seconds (+- 25%).

#### Actual Result
The job restarts immediately which we can see in the following output
Nov 09, '22 08:42:**53** +0100 | Started | Task started by client
Nov 09, '22 08:42:**52** +0100 | Restarting | Task restarting in **15.587610296s**
Nov 09, '22 08:42:52 +0100 | Terminated | Exit Code: 2, Exit Message: Docker container exited with non-zero exit code: 2
Nov 09, '22 08:42:51 +0100 | Restart Signaled | healthcheck: check fail_service health using http endpoint ‘/health’ unhealthy
Nov 09, '22 08:41:**57** +0100 | Started | Task started by client
Nov 09, '22 08:41:**56** +0100 | Restarting | Task restarting in **16.822710794s**
Nov 09, '22 08:41:56 +0100 | Terminated | Exit Code: 2, Exit Message: Docker container exited with non-zero exit code: 2

### Job file (if appropriate)
(sorry for the formatting issue, I do not know why, but the editor did not like my example somehow...)
``
job "fail-service" {
  datacenters = ["isys_poc"]
 
  type = "service"
 
  group "fail-service" {
    count = 1
 
    network {
      port "http" {
        to = 8080
        }
    }

    task "fail-service" {
      driver = "docker"
      config {
        image = "thobe/fail_service:v0.0.12"
        ports = ["http"]
      }
 
      service {
        name = "${TASK}"
        port = "http"
        check {
          name     = "fail_service health using http endpoint '/health'"
          port     = "http"
          type     = "http"
          path     = "/health"
          method   = "GET"
          interval = "10s"
          timeout  = "2s"
        }
        tags = [
          "traefik.enable=true",
          "traefik.http.routers.fail-service.rule=Host(`fail-service.poc-nomad.intersys.internal`)",
        ]
      }
 
      env {
        HEALTHY_FOR    = -1 # Stays healthy forever
      }
 
      resources {
        cpu    = 100 # MHz
        memory = 256 # MB
      }
    }
  }
}
``

### PR DESCRIPTION
**Pull request by shoenig**
This PR fixes a bug introduced in #11983 where a Timer initialized with 0
duration causes an immediate tick, even if Reset is called before reading the
channel. The fix is to avoid doing that, instead creating a Timer with a non-zero
initial wait time, and then immediately calling Stop.

Fixes #15198

### CODE REVIEW

File: client/allocrunner/taskrunner/task_runner.go [hunk 1]
```diff
@@ -563,7 +563,9 @@ func (tr *TaskRunner) Run() {
 	// Set the initial task state.
 	tr.stateUpdater.TaskStateUpdated()
 
-	timer, stop := helper.NewSafeTimer(0) // timer duration calculated JIT
+	// start with a stopped timer; actual restart delay computed later
+	timer, stop := helper.NewStoppedTimer()
+	timer.Stop()
```
Comment (shoenig) [inline client/allocrunner/taskrunner/task_runner.go:568]: dangit, left this in

**Review by tgross — APPROVED** [review]
LGTM!
