### PR TITLE
Fixed permission issues on client

### LINKED ISSUE #1916: exec driver: folder permissions in chroot env lack execute permissions
### Nomad version
Nomad v0.4.1
Nomad v0.5.0-rc1 ('a8c8199e413d387021a15d7a1400c8b8372124d6+CHANGES')

### Operating system and Environment details
Linux. Tested on Fedora 24 and CoreOS Stable 1123

### Issue
If the chroot_env configuration maps an individual file, the containing folder in the chroot environment lacks execute permissions. 

### Reproduction steps
1. create nomad.conf containing:
```
data_dir  = "/var/lib/nomad"
log_level = "DEBUG"

client {
  chroot_env {
    "/etc/resolv.conf" = "/etc/resolv.conf"
  }
}
```
2. Run Nomad agent ```nomad agent -dev -config=nomad.conf```
3. Run an exec type job, e.g.  ```nomad run helloword.nomad```
4. Inspect alloc folder ```nomad fs <alloc-id> helloworld```
5. etc folder lacks execute permissions
> Mode        Size     Modified Time          Name
> drwxrwxrwx  4.0 KiB  11/02/16 14:04:18 CET  alloc/
> drwxr-xr-x  4.2 KiB  11/02/16 08:46:32 CET  dev/
> **drw-r--r--**  4.0 KiB  11/02/16 14:04:43 CET  etc/
> ....

### Nomad Server logs (if appropriate)
don't provide any details 

### Nomad Client logs (if appropriate)
don't provide any details 

### Job file (if appropriate)
Any exec job will do. Helloword.nomad (0.4.1 version):
```
job "helloworld" {
  datacenters = ["dc1"]
  type = "service"

  update {
    stagger = "5s"
    max_parallel = 1
  }

  group "helloworld" {
    count = 1

    task "helloworld" {
      driver = "exec"
      config {
        command = "helloworld"
      }

      artifact {
        source = "https://storage.googleapis.com/global-datacenter-eu/helloworld/helloworld"
        options {
          checksum = "sha256:ee4751f7b17775e0d34514f0a00b9e92b39a8b859fc00d8e2f69e5aa6cceea4e"
        }
      }

      resources {
        cpu = 100
        disk = 200
        memory = 64
        network {
          mbits = 1
          port "http" {}
        }
      }

      service {
        name = "helloworld"
        tags = ["urlprefix-helloworld.gce.nauts.io/"]
        port = "http"
        check {
          type = "http"
          name = "health"
          interval = "15s"
          timeout = "5s"
          path = "/health"
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by diptanu**
Fixes #1916

### CODE REVIEW

File: client/allocdir/alloc_dir.go [hunk 1]
```diff
@@ -313,24 +313,23 @@ func (d *AllocDir) Embed(task string, entries map[string]string) error {
...
 			}
 
 			continue
 		}
 
-		// Create destination directory.
 		destDir := filepath.Join(taskdir, dest)
-		if err := os.MkdirAll(destDir, s.Mode().Perm()); err != nil {
-			return fmt.Errorf("Couldn't create destination directory %v: %v", destDir, err)
+		// Create destination directory.
```
Comment (dadgar) [inline client/allocdir/alloc_dir.go]: Can you move the comment above or leave a blank line in-between

File: client/allocdir/alloc_dir.go [hunk 2]
```diff
@@ -313,24 +313,23 @@ func (d *AllocDir) Embed(task string, entries map[string]string) error {
 
 		// Embedding a single file
 		if !s.IsDir() {
-			destDir := filepath.Join(taskdir, filepath.Dir(dest))
-			if err := os.MkdirAll(destDir, s.Mode().Perm()); err != nil {
-				return fmt.Errorf("Couldn't create destination directory %v: %v", destDir, err)
+			if err := d.createDir(taskdir, filepath.Dir(dest)); err != nil {
+				return fmt.Errorf("Couldn't create destination directory 11 %v: %v", dest, err)
```
Comment (dadgar) [inline client/allocdir/alloc_dir.go]: directory 11?

File: client/allocdir/alloc_dir.go [hunk 3]
```diff
@@ -313,24 +313,23 @@ func (d *AllocDir) Embed(task string, entries map[string]string) error {
...
 			continue
 		}
 
-		// Create destination directory.
 		destDir := filepath.Join(taskdir, dest)
-		if err := os.MkdirAll(destDir, s.Mode().Perm()); err != nil {
-			return fmt.Errorf("Couldn't create destination directory %v: %v", destDir, err)
+		// Create destination directory.
+		if err := d.createDir(taskdir, dest); err != nil {
+			return fmt.Errorf("Couldn't create destination directory 22 %v: %v", destDir, err)
```
Comment (dadgar) [inline client/allocdir/alloc_dir.go]: 22

File: client/allocdir/alloc_dir.go [hunk 4]
```diff
@@ -565,3 +564,56 @@ func (d *AllocDir) GetSecretDir(task string) (string, error) {
...
+
+// createDir creates a directory structure inside the basepath. This functions
+// preserves the permissions of each of the subdirectories in the relative path
+// by looking up the permissions in the host.
+func (d *AllocDir) createDir(basePath, relPath string) error {
+	filePerms, err := d.splitPath(relPath)
+	if err != nil {
+		return err
+	}
+	for i := len(filePerms) - 1; i >= 0; i-- {
```
Comment (dadgar) [inline client/allocdir/alloc_dir.go]: Comment why you are going backwards

File: client/allocdir/alloc_dir.go [hunk 5]
```diff
@@ -565,3 +564,56 @@ func (d *AllocDir) GetSecretDir(task string) (string, error) {
...
+	return nil
+}
+
+// fileInfo holds the path and the permissions of a file
+type fileInfo struct {
+	Name string
+	Perm os.FileMode
+}
+
+// splitPath stats each subdirectory of a path
```
Comment (dadgar) [inline client/allocdir/alloc_dir.go]: The order that is returned?

File: client/allocdir/alloc_dir.go [hunk 6]
```diff
@@ -565,3 +564,56 @@ func (d *AllocDir) GetSecretDir(task string) (string, error) {
...
+func (d *AllocDir) splitPath(path string) ([]fileInfo, error) {
+	var mode os.FileMode
+	i, err := os.Stat(path)
+	if err != nil {
+		mode = os.ModePerm
```
Comment (dadgar) [inline client/allocdir/alloc_dir.go]: Comment what this is doing
