### PR TITLE
decompress response body from websocket error

### LINKED ISSUE #6545: Bad error message on alloc exec when streaming through ELB
### Nomad version
Nomad v0.10.0-rc1 (c49bf41779d2ee462f46e2f58328e58c51970a83)

### Operating system and Environment details
Linux in AWS EC2

### Issue
Nomad alloc exec does not work through EC2 Classic ELB. However, the error message returned in this scenario is not human-readable, complicating the ability for operators to diagnose this issue.

### Reproduction steps
1. Spin up Nomad cluster in EC2 (for example, using TF config in `/terraform`)
2. Front the server(s) with a classic ELB, with a listener configured for `HTTP/4646` (Layer 7)
3. Note that `alloc fs` commands work.
4. Note that `alloc exec` commands do not: 
```
$ nomad alloc exec -job nginx  bash
�0iled to exec into task: Unexpected response code: 400 (�<��
�mHG���������N�x,E��ڋ��XC�2~�
G���-#]���v�O�!��H��"����H�#U�)##6�6�t�<0��z��
```

### Nomad Server log

When encountering the error, the server emits the following error message: 
```
Oct 24 15:43:40 ip-172-31-41-217 nomad[2198]:     2019-10-24T15:43:40.285Z [ERROR] http: request failed: method=GET path=/v1/client/allocation/ea145ac4-56e7-7c45-47a1-2ad3dfb334d2/exec?command=%5B%22bash%22%5D&task=nginx&tty=true error="failed to upgrade connection: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header" code=500
```

### Summary

The root cause is that Level 7 (HTTP) ELBs in EC2 do not support WebSockets. Readers should note that there are multiple approaches to resolving this: change the listener to Level 4 (TCP); or use the newer EC2 Application Load Balancer (ALB). Regardless, the error message emitted by the CLI should propagate the error from the server, if possible.

### PR DESCRIPTION
**Pull request by drewbailey**
If a websocket connection errors we currently return the error with a
copy of the response body. The response body from the websocket can
often times be gzipped, so check if the content-encoding was gzipped
and decompress.

Example error responses that were getting appended:

```
 �JK��IMQ(�W�M,*�H�QH���M�KQ��+�W�*�ϳR��P��W04��'�~�-
```
which was the result of the following response body
```
 Reader: (*bytes.Reader)(0xc00014a540)({
  s: ([]uint8) (len=69 cap=1024) {
   00000000  1f 8b 08 00 00 00 00 00  00 ff 4a 4b cc cc 49 4d  |..........JK..IM|
   00000010  51 28 c9 57 c8 4d 2c 2a  ce 48 cc 51 48 ce cf cd  |Q(.W.M,*.H.QH...|
   00000020  4d cc 4b 51 c8 cc 2b c9  57 c8 2a ce cf b3 52 c8  |M.KQ..+.W.*...R.|
   00000030  cf 50 c8 cb 57 30 34 00  04 00 00 ff ff 27 ea 7e  |.P..W04......'.~|
   00000040  f4 2d 00 00 00                                    |.-...|
  },

```

fixes #6545

### CODE REVIEW

File: api/api.go [hunk 1]
```diff
@@ -741,11 +741,8 @@ func (c *Client) websocket(endpoint string, q *QueryOptions) (*websocket.Conn, *
 
 	// check resp status code, as it's more informative than handshake error we get from ws library
 	if resp != nil && resp.StatusCode != 101 {
-		var buf bytes.Buffer
-		io.Copy(&buf, resp.Body)
 		resp.Body.Close()
-
-		return nil, nil, fmt.Errorf("Unexpected response code: %d (%s)", resp.StatusCode, buf.Bytes())
+		return nil, nil, fmt.Errorf("Unexpected response code: %d", resp.StatusCode)
```
Comment (schmichael) [inline api/api.go]: The status code alone isn't very helpful. Is the response body gzipped? Could we recover the plaintext of the error message somehow?

If it's considerable effort this is ok, but I'm concerned it will leave users with no avenue forward for diagnosing what went wrong.

Comment (drewbailey) [reply api/api.go]: Ah woops good call, can definitely check for gzip and un-gzip, so the error would end up looking like

 ```
"Unexpected response code: 301 (<a href=\"/v1/client/allocation/exec?co
mmand=%5B%22command%22%5D&amp;task=bar&amp;tty=false\">Moved Permanently</a>.\n\n)"```

File: api/allocations_test.go [hunk 2]
```diff
@@ -247,6 +249,58 @@ func TestAllocations_RescheduleInfo(t *testing.T) {
...
+	}
+	job.Canonicalize()
+
+	uuidGen := func() string {
+		ret, err := uuid.GenerateUUID()
+		if err != nil {
+			t.Fatal(err)
+		}
+		return ret
+	}
```
Comment (notnoop) [inline api/allocations_test.go]: We could switch to using our helper `uuid.Generate()`[1] that panics if fails.  It's used in commonly in test files, but looks like this file and `api/api_test.go` haven't been updated to use it yet.

[1] https://github.com/hashicorp/nomad/blob/v0.10.0/helper/uuid/uuid.go

File: api/allocations_test.go [hunk 3]
```diff
@@ -247,6 +249,58 @@ func TestAllocations_RescheduleInfo(t *testing.T) {
...
+		Job:       job,
+	}
+	// Querying when no allocs exist returns nothing
+	sizeCh := make(chan TerminalSize, 1)
+
+	// make a request that will result in an error
+	// ensure the error is what we expect
+	_, err := a.Exec(context.Background(), alloc, "bar", false, []string{"command"}, os.Stdin, os.Stdout, os.Stderr, sizeCh, nil)
+	require.Contains(t, err.Error(), "Unexpected response code: 301")
+	require.Contains(t, err.Error(), "Moved Permanently")
```
Comment (notnoop) [inline api/allocations_test.go]: Not your change but I find it very sad that we return redirect to `/ui` if an `/v1/` endpoint isn't found.

File: api/allocations_test.go (hunk 2 above)
Comment (drewbailey) [reply api/allocations_test.go]: oh nice, will update!

File: api/allocations_test.go (hunk 3 above)
Comment (schmichael) [reply api/allocations_test.go]: That is so strange. Filed an issue: https://github.com/hashicorp/nomad/issues/6656
