### PR TITLE
client: do not restart restored tasks until server is contacted

### LINKED ISSUE #1795: Clients try to rerun old allocations after machine reboot
### Nomad version

Nomad v0.3.2
### Operating system and Environment details

Ubuntu 14.04
### Issue

Nomad client puts some of the temporary files to `/tmp`. In the situation when `alloc_dir` is not erased on reboot, Nomad client tries to restart all the allocations that were run previously on this node and terminates them after receiving a command from server (note `Started`,`Started`, `Killed` event sequence in the allocation status). Since the socket in `/tmp` is gone after reboot, the client produces an error log (see below). 

In our setup we solved it by putting `alloc_dir`  to `/tmp`.
### Reproduction steps
- Create a Nomad cluster with 2 clients
- Submit a job on 1 of the clients
- Reboot the client which runs the job
### Nomad job status

```
ID          = infra-cluster-broccoli
Name        = infra-cluster-broccoli
Type        = service
Priority    = 50
Datacenters = dc1
Status      = running
Periodic    = false

==> Evaluations
ID        Priority  Triggered By  Status
194b03f7  50        node-update   complete
36b8d462  50        node-update   complete
319c009c  50        node-update   complete

==> Allocations
ID        Eval ID   Node ID   Task Group  Desired  Status
6d9c70aa  36b8d462  3df25888  server      run      running
c130ac62  319c009c  449c9ba8  server      stop     complete
```
### Nomad alloc-status

```
ID            = c130ac62
Eval ID       = 319c009c
Name          = infra-cluster-broccoli.server[0]
Node ID       = 449c9ba8
Job ID        = infra-cluster-broccoli
Client Status = complete

==> Task Resources
Task: "server"
CPU  Memory MB  Disk MB  IOPS  Addresses
500  1024       300      0     http: 10.250.18.29:9000

==> Task "server" is "dead"
Recent Events:
Time                    Type                   Description
06/10/16 14:12:30 CEST  Killed                 Task successfully killed
06/10/16 14:12:23 CEST  Started                Task started by client
04/10/16 16:59:45 CEST  Started                Task started by client
04/10/16 16:59:44 CEST  Downloading Artifacts  Client is downloading artifacts
04/10/16 16:59:44 CEST  Received               Task received by client
```
### Nomad Client configuration

```
log_level = "INFO"
datacenter = "dc1"
data_dir = "/var/lib/nomad"
bind_addr = "0.0.0.0"
advertise {
  http = "10.250.18.28:4646"
  rpc = "10.250.18.28:4647"
  serf = "10.250.18.28:4648"
}
client {
  enabled = true
  servers = ["10.250.18.27"]
  options {
    "driver.raw_exec.enable" = "1"
    "driver.exec.enable" = "1"
    "driver.docker.enable" = "1"
  }
}
```
### Nomad Client logs (if appropriate)

```
==> Caught signal: terminated
    2016/10/06 14:10:43 [INFO] agent: requesting shutdown
    2016/10/06 14:10:43 [INFO] client: shutting down
    2016/10/06 14:10:43 [INFO] agent: shutdown complete
    Loaded configuration from /etc/nomad.d/client/config.hcl
==> Starting Nomad agent...
==> Nomad agent configuration:

                 Atlas: <disabled>
                Client: true
             Log Level: INFO
                Region: global (DC: dc1)
                Server: false

==> Nomad agent started! Log data will stream in below:

    2016/10/06 14:12:19 [INFO] client: using state directory /var/lib/nomad/client
    2016/10/06 14:12:19 [INFO] client: using alloc directory /var/lib/nomad/alloc
    2016/10/06 14:12:19 [INFO] fingerprint.cgroups: cgroups are available
    2016/10/06 14:12:23 [WARN] fingerprint.env_gce: Could not read value for attribute "machine-type"
    2016/10/06 14:12:23 [WARN] fingerprint.network: Unable to parse Speed in output of '/sbin/ethtool eth0'
    2016/10/06 14:12:23 [WARN] fingerprint.network: Unable to read link speed from /sys/class/net/eth0/speed
    2016/10/06 14:12:23 [WARN] client: port not specified, using default port
    2016/10/06 14:12:23 [INFO] client: setting server address list: [10.250.18.27:4647]
    2016/10/06 14:12:23 [ERR] driver.raw_exec: error connecting to plugin so destroying plugin pid and user pid
    2016/10/06 14:12:23 [ERR] driver.raw_exec: error destroying plugin and userpid: 2 error(s) occurred:

* os: process already finished
* os: process already finished
    2016/10/06 14:12:23 [ERR] client: failed to open handle to task 'server' for alloc 'c130ac62-268f-3ae8-3aac-95d315f37b99': error connecting to plugin: error creating rpc client for executor plugin: Reattachment process not found
```

### PR DESCRIPTION
**Pull request by schmichael**
Fixes #1795

Running restored allocations and pulling what allocations to run from
the server happen concurrently. This means that if a client is rebooted,
and has its allocations rescheduled, it may restart the dead allocations
before it contacts the server and determines they should be dead.

This commit makes tasks that fail to reattach on restore wait until the
server is contacted before restarting.

The PR also includes a small mock_driver fix and systemd unit file improvement from failed testing efforts.

I gave up on e2e testing reboots as there were many non-deterministic aspects and even if the correct assertions were made for each possible series of events, I couldn't figure out a way to prevent false-positives (as in the old buggy code would still often pass the test due to the specific setup of the test environment).

### CODE REVIEW

File: drivers/mock/driver.go [hunk 1]
```diff
@@ -495,7 +495,13 @@ func (d *Driver) DestroyTask(taskID string, force bool) error {
...
 
 func (d *Driver) InspectTask(taskID string) (*drivers.TaskStatus, error) {
-	panic("not implemented")
+	h, ok := d.tasks.Get(taskID)
+	if !ok {
+		return nil, drivers.ErrTaskNotFound
+	}
+
+	return h.TaskStatus(), nil
+
```
Comment (schmichael) [inline drivers/mock/driver.go]: Ended up not using this code during testing, but it seems generally safe and useful.

File: helper/gate/gate.go [hunk 2]
```diff
@@ -0,0 +1,87 @@
+// Package gate implements a simple on/off latch or gate: it blocks waiters
```
Comment (schmichael) [inline helper/gate/gate.go]: TR.Update runs concurrently with Client.runAllocs, both of which may open the gate. This means I couldn't simply close an unsynchronized chan to unblock waiting TRs. I decided to encapsulate the concurrent unblockers in this gate package as it also provides a concise API (IsClosed) for determining whether a TR is about to block and logging beforehand.

File: client/allocrunner/taskrunner/task_runner.go [hunk 3]
```diff
@@ -858,7 +882,18 @@ func (tr *TaskRunner) Restore() error {
...
 		//TODO if RecoverTask returned the DriverNetwork we wouldn't
 		//     have to persist it at all!
-		tr.restoreHandle(taskHandle, tr.localState.DriverNetwork)
+		restored := tr.restoreHandle(taskHandle, tr.localState.DriverNetwork)
+		if !restored && !tr.Alloc().TerminalStatus() {
+			// Restore failed, close the restore gate to block
+			// until server is contacted to prevent restarting
+			// terminal allocs. #1795
+			tr.logger.Trace("failed to reattach to task; will not run until server is contacted")
+			tr.restoreGate.Close()
```
Comment (notnoop) [inline client/allocrunner/taskrunner/task_runner.go]: This assumes that `Restore` is called strictly before attempting to contacting server.  Otherwise, we may risk opening gate then closing it indefinitely here.  Is that an accurate assumption?

File: client/allocrunner/taskrunner/task_runner.go [hunk 4]
```diff
@@ -381,6 +393,18 @@ func (tr *TaskRunner) Run() {
 	// - should be handled serially.
 	go tr.handleUpdates()
 
+	// If restore failed, don't proceed until servers are contacted
+	if tr.restoreGate.IsClosed() {
+		tr.logger.Info("task failed to restore; waiting to contact server before restarting")
+		select {
```
Comment (schmichael) [inline client/allocrunner/taskrunner/task_runner.go]: Should there be a timeout after which we allow the task to restart? Some people may be relying on the fact that disconnected Nomad nodes will continue to run their tasks. :thinking:

File: client/allocrunner/taskrunner/task_runner.go [hunk 5]
```diff
@@ -858,7 +882,18 @@ func (tr *TaskRunner) Restore() error {
 	if taskHandle := tr.localState.TaskHandle; taskHandle != nil {
 		//TODO if RecoverTask returned the DriverNetwork we wouldn't
 		//     have to persist it at all!
-		tr.restoreHandle(taskHandle, tr.localState.DriverNetwork)
+		restored := tr.restoreHandle(taskHandle, tr.localState.DriverNetwork)
+		if !restored && !tr.Alloc().TerminalStatus() {
```
Comment (schmichael) [inline client/allocrunner/taskrunner/task_runner.go]: This logic might need to get more complicated :(

I don't think we ever want to block system jobs from restarting.

File: client/allocrunner/taskrunner/task_runner.go [hunk 6]
```diff
@@ -381,6 +396,19 @@ func (tr *TaskRunner) Run() {
...
+	// #1795
+	if tr.waitOnServers {
+		tr.logger.Info("task failed to restore; waiting to contact server before restarting")
+		select {
+		case <-tr.killCtx.Done():
+		case <-tr.shutdownCtx.Done():
+			return
+		case <-tr.serversContactedCh:
+			tr.logger.Trace("server contacted; unblocking waiting task")
+		}
```
Comment (schmichael) [inline client/allocrunner/taskrunner/task_runner.go]: Should there be a timeout after which we allow the task to restart? Some people may be relying on the fact that disconnected Nomad nodes will continue to run their tasks. thinking

Alternatively we could have a client config and/or jobspec parameter for controlling this behavior.

File: client/allocrunner/taskrunner/task_runner.go [hunk 7]
```diff
@@ -193,6 +193,16 @@ type TaskRunner struct {
 	// maxEvents is the capacity of the TaskEvents on the TaskState.
 	// Defaults to defaultMaxEvents but overrideable for testing.
 	maxEvents int
+
+	// serversContactedCh is passed to TaskRunners so they can detect when
+	// servers have been contacted for the first time in case of a failed
+	// restore.
+	serversContactedCh <-chan struct{}
```
Comment (notnoop) [inline client/allocrunner/taskrunner/task_runner.go]: This is more precisely: fetched expected running allocations from server - not heartbeat/registration/etc. Not sure if it's worth making the distinction or where to add it.

File: client/allocrunner/taskrunner/task_runner.go (hunk 6 above)
Comment (notnoop) [reply client/allocrunner/taskrunner/task_runner.go]: I'm not sure - but I'd probably avoid adding more knobs to maintain until we hear clear demand.

To me the problem is that some tasks are not restarted and having partially running alloc while the nomad agent isn't running, potentially for hours.  I find it easier to reason that in recovery a client that starts without being able to connect to server has the same behavior as no client starting.  Adding a timeout seems to complicate the story for such a narrow case, without really addressing the big problem of having partially failing/running alloc while client is gone.

File: client/allocrunner/taskrunner/task_runner.go (hunk 7 above)
Comment (schmichael) [reply client/allocrunner/taskrunner/task_runner.go]: Yeah, we've never had good nomenclature for this. The code base often talks about "syncing" allocs, but since `client->server` and `server->client` updates are completely independent code paths it's always ambiguous to say "syncing".

* `syncedFromServersCh`
* `allocsPulledCh`
* `allocsRetrievedCh`
* `unblockedRestoredCh` - we could go with a name related to its _use_ instead of the event/state it represents, but that doesn't seem as good.

Any thoughts/preferences? `allocsPulledCh` might be my preference as we use the term `pulled` in related code/logging.

Comment (notnoop) [reply client/allocrunner/taskrunner/task_runner.go]: I'd be ok with clarifying in comment with keeping the field name the same.

File: client/allocrunner/taskrunner/task_runner.go (hunk 6 above)
Comment (schmichael) [reply client/allocrunner/taskrunner/task_runner.go]: My one big concern is that when this is released it will break the ability for _disconnected_ nodes to restart.

Right now completely disconnected nodes can fully reboot and will restart anything they were running before regardless of whether or not contact is ever made with servers.

It's difficult to know if anyone is relying on this behavior because it is much more of an emergent property of the client's code than an intentional and documented design choice.

Comment (schmichael) [reply client/allocrunner/taskrunner/task_runner.go]: Discussed offline and decided to block indefinitely. If a client can't contact servers in a timely fashion (seconds) it's likely to have its non-system allocs marked as lost and rescheduled elsewhere anyway so there's even less reason to restart at that point.
