### PR TITLE
csi: move volume claim release into volumewatcher

### LINKED ISSUE #7629: csi: controller plugin timeouts
With the fixes in https://github.com/hashicorp/nomad/pull/7626 I've got most of the unpublish workflow working again.

But we're getting controller timeouts when trying to unpublish with the EBS plugin. It appears that the controller plugin is sending the AWS API call and the volume is getting detached, but the RPC call is not returning, so it then times out and bubbles up as an error so we don't release the claim.

Logs from the controller plugin:

```
I0404 19:01:57.186105       1 controller.go:275] ControllerUnpublishVolume: called with args {VolumeId:vol-0564768ab4da32abb NodeId:i-0eb5420cb5752a46e Secrets:map[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0404 19:02:08.010019       1 controller.go:298] ControllerGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0404 19:02:38.010766       1 controller.go:298] ControllerGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0404 19:03:08.011877       1 controller.go:298] ControllerGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0404 19:03:38.012855       1 controller.go:298] ControllerGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
I0404 19:04:08.013598       1 controller.go:298] ControllerGetCapabilities: called with args {XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
E0404 19:04:14.836283       1 driver.go:109] GRPC error: rpc error: code = Internal desc = Could not detach volume "vol-0564768ab4da32abb" from node "i-0eb5420cb5752a46e": RequestCanceled: request context canceled
caused by: context canceled
```

### PR DESCRIPTION
**Pull request by tgross**
Fixes #7629 

This changeset adds a subsystem to run on the leader, similar to the deployment watcher or node drainer. The `Watcher` performs a blocking query on updates to the `CSIVolumes` table and triggers reaping of volume claims.

This will avoid tying up scheduling workers by immediately sending volume claim workloads into their own loop, rather than blocking the scheduling workers in the core GC job doing things like talking to CSI controllers.

---

Notes:

* There's unfortunately a _lot_ of code in this PR but about third of it is tests and a third is removing the old GC job. I've broken it into commit-by-commit chunks that should be a bit more manageable.
* Unit tests for this are pretty comprehensive, and I've hand-tested this with the hostpath, EBS, and EFS plugins.
* I've pulled https://github.com/hashicorp/nomad/pull/7824 out into its own PR, but we'll need #7824 for correctness with pre-0.11.2 clusters that are upgraded.
* This is a resurrection of https://github.com/hashicorp/nomad/pull/7708, after https://github.com/hashicorp/nomad/pull/7782 was pulled out into separate work.
* We'll also want a periodic job for iterating over batches of volumes to GC, similar to current periodic job GC. That work will be https://github.com/hashicorp/nomad/issues/7825

### CODE REVIEW

File: nomad/volumewatcher/batcher.go [hunk 1]
```diff
@@ -0,0 +1,125 @@
+package volumewatcher
```
Comment (tgross) [inline nomad/volumewatcher/batcher.go:1]: Note for review: this file draws heavily on https://github.com/hashicorp/nomad/blob/master/nomad/deploymentwatcher/batcher.go

File: nomad/fsm.go [hunk 2]
```diff
@@ -1156,33 +1158,35 @@ func (n *nomadFSM) applyCSIVolumeDeregister(buf []byte, index uint64) interface{
 	return nil
 }
 
-func (n *nomadFSM) applyCSIVolumeClaim(buf []byte, index uint64) interface{} {
```
Comment (tgross) [inline nomad/fsm.go:1159]: note for review: it's worth looking at this file without the diff... the diff really tangled this up because the `applyCSIVolumeBatchClaim` is similar to the `applyCSIVolumeClaim`. This should be entirely an addition.

File: nomad/interfaces.go [hunk 3]
```diff
@@ -1,11 +0,0 @@
-package nomad
```
Comment (tgross) [inline nomad/interfaces.go:1]: Note for review: this only supported the now-removed `nomad/core_sched_test.go` file.

File: nomad/volumewatcher/interfaces.go [hunk 4]
```diff
@@ -0,0 +1,28 @@
+package volumewatcher
```
Comment (tgross) [inline nomad/volumewatcher/interfaces.go:1]: Note for review: these interfaces exist solely to give us handles for RPC mocks in the tests (so we don't have to set up clients with CSI plugins in unit tests).

File: nomad/volumewatcher/volume_watcher.go [hunk 5]
```diff
@@ -0,0 +1,382 @@
...
+	}
+
+	collect(vol.ReadAllocs, vol.ReadClaims)
+	collect(vol.WriteAllocs, vol.WriteClaims)
+
+	if len(vol.PastClaims) == 0 {
+		return nil
+	}
+
+	for _, claim := range vol.PastClaims {
```
Comment (tgross) [inline nomad/volumewatcher/volume_watcher.go:243]: Note for review: from here down we're almost entirely copying the code over from the `nomad/core_sched.go` file that's been removed. Changes mostly include better trace logging and naming/comments.

File: nomad/volumewatcher/volumes_watcher.go [hunk 6]
```diff
@@ -0,0 +1,232 @@
...
+	}
+
+	watcher := newVolumeWatcher(w, v)
+	w.watchers[v.ID+v.Namespace] = watcher
+	return watcher, nil
+}
+
+// TODO: this is currently dead code; we'll call a public remove
+// method on the Watcher once we have a periodic GC job
+// remove stops watching a volume and should only be called when locked.
```
Comment (tgross) [inline nomad/volumewatcher/volumes_watcher.go:217]: ref https://github.com/hashicorp/nomad/issues/7825

File: nomad/volumewatcher/volume_watcher.go [hunk 7]
```diff
@@ -0,0 +1,382 @@
...
+		updateClaims: parent.updateClaims,
+		v:            vol,
+		state:        parent.state,
+		rpc:          parent.rpc,
+		logger:       parent.logger.With("volume_id", vol.ID, "namespace", vol.Namespace),
+		shutdownCtx:  parent.ctx,
+	}
+
+	// Start the long lived watcher that scans for allocation updates
+	w.Start()
```
Comment (langmartin) [inline nomad/volumewatcher/volume_watcher.go:58]: For the long term, I'm a little worried about starting a go routine for every volume. It seems at least possible that some operators could set us up for more goroutines than we want running for these, maybe in a followup if warranted we could use a fixed pool?

File: nomad/volumewatcher/volume_watcher.go [hunk 8]
```diff
@@ -0,0 +1,382 @@
...
+	jobs := map[string]bool{}      // namespace+jobID -> stopped
+
+	// if a job is purged, the subsequent alloc updates can't
+	// trigger a GC job because there's no job for them to query.
+	// Job.Deregister will send a claim release on all claims
+	// but the allocs will not yet be terminated. save the status
+	// for each job so that we don't requery in this pass
+	checkStopped := func(jobID string) bool {
+		namespace := vw.v.Namespace
+		isStopped, ok := jobs[namespace+jobID]
```
Comment (langmartin) [inline nomad/volumewatcher/volume_watcher.go:184]: Isn't namespace in any given vw always going to be the same so that just `jobID` is unique here?

Comment (tgross) [reply nomad/volumewatcher/volume_watcher.go:184]: Good catch. Will fix.

File: nomad/volumewatcher/volume_watcher.go (hunk 7 above)
Comment (tgross) [reply nomad/volumewatcher/volume_watcher.go:58]: I think that's a great idea. But it occurs to me we could also simply `Stop()` the goroutine when we've completed processing an incoming update (when we've determined either there are no more past claims to process or no more claims at all). This is a small change but will require some test reworking so I'm going to spin it off into https://github.com/hashicorp/nomad/issues/7837

File: nomad/volumewatcher/volumes_watcher.go [hunk 9]
```diff
@@ -0,0 +1,232 @@
...
+// flush is used to clear the state of the watcher
+func (w *Watcher) flush() {
+	// Stop all the watchers and clear it
+	for _, watcher := range w.watchers {
+		watcher.Stop()
+	}
+
+	// Kill everything associated with the watcher
+	if w.exitFn != nil {
+		w.exitFn()
```
[the remark this answers is not in the document]
Comment (tgross) [reply nomad/volumewatcher/volumes_watcher.go:120]: Yeah. 

* If the follower was recently a leader, we drop the blocking query it was making. Any in-flight work will be canceled except for client RPCs (which we can't yet cancel but are idempotent).
* If the follower was not recently a leader but we call the `flush()` on it anyways for some spurious reason, it's safe to call a cancel function twice.

File: nomad/volumewatcher/batcher.go [hunk 10]
```diff
@@ -0,0 +1,125 @@
...
+			if timerCh == nil {
+				timerCh = time.After(b.batch)
+			}
+
+			// de-dupe and store the claim update, and attach the future
+			for _, upd := range w.claims {
+				claims[upd.VolumeID+upd.RequestNamespace()] = upd
+			}
+			w.f <- future
+		case <-timerCh:
```
[the remark this answers is not in the document]
Comment (tgross) [reply nomad/volumewatcher/batcher.go:78]: Good call. Spun out to https://github.com/hashicorp/nomad/issues/7838

File: nomad/volumewatcher/volumes_watcher.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (langmartin) [reply nomad/volumewatcher/volumes_watcher.go:120]: I'd convinced myself it was already, sorry, that was a note I made on the first pass and meant to remove before I hit the button. First read I thought `exitFn` looked like it was actually running the rpcs.
