### PR TITLE
Respect alloc job version for lost/failed allocs

### LINKED ISSUE #8439: Replacement allocations use unpromoted job versions
### Nomad version
v0.12.0

### Issue

When using deployments with canaries, replacement allocations created when an old allocation was stopped with `nomad alloc stop 1234` incorrectly use the *new unpromoted canary Job version* instead of the last promoted/stable Job version.

### Reproduction steps

1. nomad run [example.nomad](https://gist.github.com/schmichael/1f306ae8217fa5a32a715db647f772c5)
2. Bump "V" env var or make some other change to example.nomad that will cause a destructive update
3. nomad run example.nomad
4. Observe the deployment has 1 canary alloc at job v1
5. nomad alloc stop <alloc id @ job v0>
6. Observe the replacement alloc is v1, not v0

#### Expected behavior

Replacement allocations should be the last promoted/stable Job version until the new canary is promoted.

### PR DESCRIPTION
**Pull request by notnoop**
This change fixes a bug where lost/failed allocations are replaced by
allocations with the latest versions, even if the version hasn't been
promoted yet.

Now, when generating a plan for lost/failed allocations, the scheduler
first checks if the current deployment is in Canary stage, and if so, it
ensures that any lost/failed allocations is replaced one with the latest
promoted version instead.

## Implementation High Level

In high level, the fix makes the following changes:

1. First, when rescheduling (or migrating) non-canary allocations, the reconciler marks the resulting `allocPlaceResult` struct with downgrade indicator along with the minimum version
  * the minimum version is used to ensure that no allocations is accidentally rollback when rescheduling
2. When making the placement and computing resources, the generic scheduler finds the latest non-canary deployment associated with the task group and uses it for scheduling purposes
3. When inserting the resulting alloc in the plan, we ensure that the job info is attached to the alloc.
  * Typically, we don't populate Allocation.Job field in the plan, as it's typically duplicated, and nomad FSM ensures that the alloc.Job field is populated from plan.  Here, we want the alloc to differ from the plan one
4. When applying the plan results to the FSM, nomad will respect the alloc.Job field and avoid populating it
  * This is already current behavior, no changes there, but the test ensures that's the case

### Why use latest promoted or non-canary version?  Why not latest job Stable version?

The promotion semantics is somewhat group specific.  Consider a job has two TaskGroups: A, B in Version 0, and then Version 1 updated A significantly (requiring a Canary) but only updated B's count and metadata.  B allocations should always use Version 1, and non-Canary A should use version 0.  Using latest Stable job will not appropriate here

### In this approach, does the scheduler respect the count and resources found in latest promoted deployment?

The scheduler will use the resources of the appropriate job version for the alloc, if the resources changed. However, the latest job Count field is the canonical value, and this PR doesn't change that.  If a job has TG count=3 in Version 0, and changed count to 2 and requested large resources; immediately, a Version 0 allocation will be stopped, so we'd have 2 Version=0 allocations along with some canaries.

### Can this PR handle cases where we reschedule a Canary and NonCanary failed allocations

Yes, when migrating allocations, the canary will be replaced by another canary, and non-canaries will be replaced by non-canary instances, each with the expected versions for them.

Fixes  #8439

### CODE REVIEW

File: scheduler/generic_sched.go [hunk 1]
```diff
@@ -457,6 +484,31 @@ func (s *GenericScheduler) computePlacements(destructive, place []placementResul
...
+			var downgradedJob *structs.Job
+
+			if missing.DowngradeNonCanary() {
+				jobDeploymentID, job, err := s.downgradedJobForPlacement(missing)
+				if err != nil {
+					return err
+				}
+
+				// Defensive check - if there is no appropriate deployment for this job, use the latest
+				if job != nil && job.Version >= missing.MinJobVersion() && job.LookupTaskGroup(tg.Name) != nil {
```
Comment (notnoop) [inline scheduler/generic_sched.go:496]: I made few defensive checks here, where if we see unexpected state (e.g. jobs without expected TaskGroup, no non-promoted version), we'd fallback to using the latest version.  This seems better than a panic, but not sure if we should simplify this.

File: scheduler/reconcile.go [hunk 2]
```diff
@@ -424,10 +424,10 @@ func (a *allocReconciler) computeGroup(group string, all allocSet) bool {
 
 	// The fact that we have destructive updates and have less canaries than is
 	// desired means we need to create canaries
-	numDestructive := len(destructive)
 	strategy := tg.Update
 	canariesPromoted := dstate != nil && dstate.Promoted
-	requireCanary := numDestructive != 0 && strategy != nil && len(canaries) < strategy.Canary && !canariesPromoted
+	requireCanary := (len(destructive) != 0 || (len(untainted) == 0 && len(migrate)+len(lost) != 0)) &&
+		strategy != nil && len(canaries) < strategy.Canary && !canariesPromoted
```
Comment (notnoop) [inline scheduler/reconcile.go:430]: This is semi-related band-aid that we'll probably need to investigate further.  The code here determines if canaries are needed by checking if we have any destructive update.  However, if all allocations are dead (because the nodes are lost), `len(destructive)` will be 0.  I changed the condition to account for such scenario.

File: scheduler/reconcile.go [hunk 3]
```diff
@@ -533,9 +533,12 @@ func (a *allocReconciler) computeGroup(group string, all allocSet) bool {
 		})
 		a.result.place = append(a.result.place, allocPlaceResult{
 			name:          alloc.Name,
-			canary:        false,
+			canary:        alloc.DeploymentStatus.IsCanary(),
```
Comment (notnoop) [inline scheduler/reconcile.go:536]: The code here assumed that all alloc migrations are non-canary.  An odd assumption.

File: scheduler/generic_sched.go (hunk 1 above)
Comment (notnoop) [reply scheduler/generic_sched.go:496]: Yes, it's unexpected. `missing.DowngradeNonCanary()` should be always false.

File: scheduler/generic_sched.go [hunk 4]
```diff
@@ -457,6 +484,31 @@ func (s *GenericScheduler) computePlacements(destructive, place []placementResul
...
+					deploymentID = jobDeploymentID
+
+					// ensure we are operating on the correct job
+					s.stack.SetJob(job)
+				} else {
+					jobVersion := -1
+					if job != nil {
+						jobVersion = int(job.Version)
+					}
+					s.logger.Warn("failed to find appropriate job; using the latest", "expected_version", missing.MinJobVersion, "found_version", jobVersion)
```
[the remark this answers is not in the document]
Comment (notnoop) [reply scheduler/generic_sched.go:508]: if MaxParallel == 0, it will be canonicalized to `job.Update = nil`, and downgrading will not be relevant, and this path isn't executed.
