### PR TITLE
refact: only reload job if job has no taskGroups

### LINKED ISSUE #14644: UI making frequent requests with no delay on task groups page
### Nomad version
Output from `nomad version`
Nomad v1.3.5 (1359c2580fed080295840fb888e28f0855e42d50)
I've also seen this on Nomad v1.2.12 (ad603b02153700fae06e2487ae2b5a164ffa2c4d)
### Operating system and Environment details
Ubuntu 22.04 (I've also seen this on other versions of Ubuntu)
### Issue
The task groups page is making requests for /v1/job/jobname with no delay between them. I've noticed this only seems to happen if there's a completed alloc on the page.
### Reproduction steps
1. Run `nomad agent -dev -bind=0.0.0.0`
2. Deploy a job (I used the example from the docs) - `nomad job run docs.nomad`
3. Make a change to the job and deploy it again
4. Go to the task group page in the nomad UI (http://ip:4646/ui/jobs/docs@default/example)
#### Expected Result
UI periodically updates with some delay between requests 
#### Actual Result
Thousands of requests within seconds 
image

### Job file (if appropriate)
[Example job](https://learn.hashicorp.com/tutorials/nomad/jobs-submit)

### Nomad Server logs (if appropriate)
```
    2022-09-21T22:01:07.421Z [DEBUG] http: request complete: method=GET path=/v1/job/docs duration="124.123µs"
    2022-09-21T22:01:07.427Z [DEBUG] http: request complete: method=GET path=/v1/job/docs duration="120.276µs"
    2022-09-21T22:01:07.433Z [DEBUG] http: request complete: method=GET path=/v1/job/docs duration="121.839µs"
    2022-09-21T22:01:07.440Z [DEBUG] http: request complete: method=GET path=/v1/job/docs duration="106.069µs"
    2022-09-21T22:01:07.448Z [DEBUG] http: request complete: method=GET path=/v1/job/docs duration="116.078µs"
```

### PR DESCRIPTION
**Pull request by ChaiWithJai**
Resolves #14644

This PR guards calling `job.reload` in the `AllocationRow` component by checking if the `job` on the `allocation` argument on the `AllocationRow` component is a `partial job` (a job without task groups).

The challenge we're trying to solve is an infinite loop of dispatching asynchronous requests reported in #14644.

### CODE REVIEW

File: ui/app/components/allocation-row.js [hunk 1]
```diff
@@ -106,7 +106,7 @@ async function qualifyAllocation() {
     // Make sure that the job record in the store for this allocation
     // is complete and not a partial from the list endpoint
     const job = allocation.get('job.content');
-    if (job) await job.reload();
+    if (job.isPartial) await job.reload();
```
Comment (ChaiWithJai) [inline ui/app/components/allocation-row.js:109]: More [context](https://github.com/hashicorp/nomad/commit/8f811d50463774233e95c01cd019b542c15c0552#r85482632) on this solution.

**Review by philrenaud — APPROVED** [review]
