### PR TITLE
Fix panic when monitoring a local client node

### LINKED ISSUE #7052: Panics in /v1/agent/monitor endpoint on clients
### Nomad version
1.10.3

### Operating system and Environment details
- Centos 7.6
- Docker version 1.13.1, build 4ef4b30/1.13.1
- Three servers and three clients, all 1.10.3

### Issue
We are reliably seeing panics from nomad clients on boot, unsure of specific root cause.

Will add more details once we finish rollback to 10.2.

### Reproduction steps
Unclear at this time

### Nomad Client logs 

```
Feb 03 08:15:09 nomad: goroutine 448144 [running]:
Feb 03 08:15:09 nomad: net/http.(*conn).serve.func1(0xc002b4c0a0)
Feb 03 08:15:09 nomad: /usr/local/go/src/net/http/server.go:1769 +0x139
Feb 03 08:15:09 nomad: panic(0x1f88340, 0x3eb90e0)
Feb 03 08:15:09 nomad: /usr/local/go/src/runtime/panic.go:522 +0x1b5
Feb 03 08:15:09 nomad: github.com/hashicorp/nomad/nomad.(*Server).ResolveToken(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Feb 03 08:15:09 nomad: /opt/gopath/src/github.com/hashicorp/nomad/nomad/acl.go:17 +0x4e
Feb 03 08:15:09 nomad: github.com/hashicorp/nomad/command/agent.(*HTTPServer).AgentMonitor(0xc00114e140, 0x27bc580, 0xc001734240, 0xc002060100, 0xc00022f840, 0xc0044feac0, 0x38, 0xc0044feab8)
Feb 03 08:15:09 nomad: /opt/gopath/src/github.com/hashicorp/nomad/command/agent/agent_endpoint.go:162 +0x9b
Feb 03 08:15:09 nomad: github.com/hashicorp/nomad/command/agent.(*HTTPServer).wrap.func1(0x27bc580, 0xc001734240, 0xc002060100)
Feb 03 08:15:09 nomad: /opt/gopath/src/github.com/hashicorp/nomad/command/agent/http.go:388 +0x149
Feb 03 08:15:09 nomad: net/http.HandlerFunc.ServeHTTP(0xc0011fc200, 0x27bc580, 0xc001734240, 0xc002060100)
Feb 03 08:15:09 nomad: /usr/local/go/src/net/http/server.go:1995 +0x44
Feb 03 08:15:09 nomad: net/http.(*ServeMux).ServeHTTP(0xc00101d500, 0x27bc580, 0xc001734240, 0xc002060100)
Feb 03 08:15:09 nomad: /usr/local/go/src/net/http/server.go:2375 +0x1d6
Feb 03 08:15:09 nomad: github.com/hashicorp/nomad/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x27bf780, 0xc002926ee0, 0xc002060100)
Feb 03 08:15:09 nomad: /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/NYTimes/gziphandler/gzip.go:269 +0x1db
Feb 03 08:15:09 nomad: net/http.HandlerFunc.ServeHTTP(0xc001140f90, 0x27bf780, 0xc002926ee0, 0xc002060100)
Feb 03 08:15:09 nomad: /usr/local/go/src/net/http/server.go:1995 +0x44
Feb 03 08:15:09 nomad: net/http.serverHandler.ServeHTTP(0xc00113c340, 0x27bf780, 0xc002926ee0, 0xc002060100)
Feb 03 08:15:09 nomad: /usr/local/go/src/net/http/server.go:2774 +0xa8
Feb 03 08:15:09 nomad: net/http.(*conn).serve(0xc002b4c0a0, 0x27cf040, 0xc00255e000)
Feb 03 08:15:09 nomad: /usr/local/go/src/net/http/server.go:1878 +0x851
Feb 03 08:15:09 nomad: created by net/http.(*Server).Serve
Feb 03 08:15:09 nomad: /usr/local/go/src/net/http/server.go:2884 +0x2f4
Feb 03 08:15:09 nomad: 
                                                net/http.(*conn).serve.func1(0xc002b4c0a0)
                                                        /usr/local/go/src/net/http/server.go:1769 +0x139
                                                panic(0x1f88340, 0x3eb90e0)
                                                        /usr/local/go/src/runtime/panic.go:522 +0x1b5
                                                github.com/hashicorp/nomad/nomad.(*Server).ResolveToken(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
                                                        /opt/gopath/src/github.com/hashicorp/nomad/nomad/acl.go:17 +0x4e
                                                github.com/hashicorp/nomad/command/agent.(*HTTPServer).AgentMonitor(0xc00114e140, 0x27bc580, 0xc001734240, 0xc002060100, 0xc00022f840, 0xc0044feac0, 0x38, 0xc0044feab8)
                                                        /opt/gopath/src/github.com/hashicorp/nomad/command/agent/agent_endpoint.go:162 +0x9b
                                                github.com/hashicorp/nomad/command/agent.(*HTTPServer).wrap.func1(0x27bc580, 0xc001734240, 0xc002060100)
                                                        /opt/gopath/src/github.com/hashicorp/nomad/command/agent/http.go:388 +0x149
                                                net/http.HandlerFunc.ServeHTTP(0xc0011fc200, 0x27bc580, 0xc001734240, 0xc002060100)
                                                        /usr/local/go/src/net/http/server.go:1995 +0x44
                                                net/http.(*ServeMux).ServeHTTP(0xc00101d500, 0x27bc580, 0xc001734240, 0xc002060100)
                                                        /usr/local/go/src/net/http/server.go:2375 +0x1d6
                                                github.com/hashicorp/nomad/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x27bf780, 0xc002926ee0, 0xc002060100)
                                                        /opt/gopath/src/github.com/hashicorp/nomad/vendor/github.com/NYTimes/gziphandler/gzip.go:269 +0x1db
                                                net/http.HandlerFunc.ServeHTTP(0xc001140f90, 0x27bf780, 0xc002926ee0, 0xc002060100)
                                                        /usr/local/go/src/net/http/server.go:1995 +0x44
                                                net/http.serverHandler.ServeHTTP(0xc00113c340, 0x27bf780, 0xc002926ee0, 0xc002060100)
                                                        /usr/local/go/src/net/http/server.go:2774 +0xa8
                                                net/http.(*conn).serve(0xc002b4c0a0, 0x27cf040, 0xc00255e000)
                                                        /usr/local/go/src/net/http/server.go:1878 +0x851
                                                created by net/http.(*Server).Serve
                                                        /usr/local/go/src/net/http/server.go:2884 +0x2f4
```

The panic is seen across all 3 clients, and afterwards they _may_ become unresponsive.

### PR DESCRIPTION
**Pull request by drewbailey**
Fixes a panic when accessing a.agent.Server() when agent is a client
and not a server. This pr removes a redundant ACL check since ACLs are validated
at the RPC layer. It also nil checks the agent server and uses Client()
when appropriate.

fixes #7052

### CODE REVIEW

File: command/agent/agent_endpoint.go [hunk 1]
```diff
@@ -229,8 +219,12 @@ func (s *HTTPServer) AgentMonitor(resp http.ResponseWriter, req *http.Request) (
...
 		}
 	} else {
-		// No node id monitor server
-		handler, handlerErr = s.agent.Server().StreamingRpcHandler("Agent.Monitor")
+		// No node id monitor current server/client
+		if srv := s.agent.Server(); srv != nil {
+			handler, handlerErr = srv.StreamingRpcHandler("Agent.Monitor")
+		} else {
+			handler, handlerErr = s.agent.Client().StreamingRpcHandler("Agent.Monitor")
+		}
```
Comment (notnoop) [inline command/agent/agent_endpoint.go]: You can avoid the nesting here - the same applies to conditionals below:

```golang
if nodeID != "" {
	...
} else if srv := s.agent.Server(); srv != nil {
	...
} else {
	...
}

File: command/agent/agent_endpoint_test.go [hunk 2]
```diff
@@ -386,6 +386,46 @@ func TestHTTP_AgentMonitor(t *testing.T) {
...
+			req, err := http.NewRequest("GET", "/v1/agent/monitor?log_level=warn", nil)
+			require.Nil(t, err)
+			resp := newClosableRecorder()
+			defer resp.Close()
+
+			go func() {
+				// set server to nil to monitor as client
+				s.Agent.server = nil
+				_, err = s.Server.AgentMonitor(resp, req)
+				require.NoError(t, err)
```
Comment (notnoop) [inline command/agent/agent_endpoint_test.go]: I would suggest using separate tests or `Run()` invocations.  Given that this mutates the agent, it may interfere unexpectedly with other tests, if this section is moved or new tests are added.  Also, `require.NoError` doesn't work so well in a goroutine, as it uses a panic; you can use `assert.NoError` here or require the error in the main test goroutine.

File: command/agent/agent_endpoint_test.go [hunk 3]
```diff
@@ -481,11 +521,17 @@ func TestAgent_PprofRequest(t *testing.T) {
 		addNodeID   bool
 		addServerID bool
 		expectedErr string
+		nilServer   bool
```
Comment (notnoop) [inline command/agent/agent_endpoint_test.go]: Maybe this is more appropriate as `clientOnly`? or `serverDisabled` as it conveys the concept better?

File: command/agent/agent_endpoint_test.go (hunk 2 above)
Comment (drewbailey) [reply command/agent/agent_endpoint_test.go]: :+1: replaced closures with Run()

File: command/agent/agent_endpoint_test.go [hunk 4]
```diff
@@ -537,6 +586,10 @@ func TestAgent_PprofRequest(t *testing.T) {
 					url = url + "?server_id=" + s.server.LocalMember().Name
 				}
 
+				if tc.nilServer {
```
Comment (notnoop) [inline command/agent/agent_endpoint_test.go]:
```suggestion
				if tc.clientOnly {
```
