### PR TITLE
api: exit EventStream.Stream on first error

### LINKED ISSUE #27133: api Client EventStream; can not detect nomad server‘s disconnet，and reconnect to server automaticly
### Nomad version
Output from `nomad version`
nomad newtest version

### Operating system and Environment details
golang

### Issue
api Client EventStream; can not detect nomad server‘s disconnet，and reconnect to server automaticly

### Reproduction steps
	config := api.DefaultConfig()
	config.Address = url

	client, err := api.NewClient(config)
	if err != nil {
		return
	}

	defer client.Close()

	topics := map[api.Topic][]string{
		//api.TopicJob:        {"*"},
		api.TopicAllocation: {"*"},
	}

	ctx, _ := context.WithCancel(context.Background())

	stream, err := client.EventStream().Stream(ctx, topics, 0, &api.QueryOptions{})
	if err != nil {
	}

       
	for {
		select {
		case events, ok := <-stream:
			if !ok {
				log.Infof("stream close")
			}
		case <-ctx.Done():
			log.Infof("Nomad Job stop")
		}
	}

1 use these code to connect to nomad server
2 close nomad server
3 can not detect nomd disconnect event
4 restart the nomad server
5 can not rec any event for ever

### PR DESCRIPTION
**Pull request by schmichael**
Errors from Decode are non-recoverable and should cause Stream to return. Otherwise Stream will loop forever on EOF from Decode.

Fixes #27133

Repro: https://gist.github.com/schmichael/247a39bf36406c08c8a95fc8c85bd56a

### Contributor Checklist
- [x] **Changelog Entry** If this PR changes user-facing behavior, please generate and add a
  changelog entry using the `make cl` command.
- [ ] **Testing** Please add tests to cover any new functionality or to demonstrate bug fixes and
  ensure regressions will be caught.
- [ ] **Documentation** If the change impacts user-facing functionality such as the CLI, API, UI,
  and job configuration, please update the Nomad product documentation, which is stored in the
  [`web-unified-docs` repo](../web-unified-docs/). Refer to the [`web-unified-docs` contributor guide](../web-unified-docs/tree/docs/contribute.md) for docs guidelines.
  Please also consider whether the change requires notes within the [upgrade
  guide](https://developer.hashicorp.com/nomad/docs/upgrade/upgrade-specific). If you would like help with the docs, tag the `nomad-docs` team in this PR.

### Reviewer Checklist
- [x] **Backport Labels** Please add the correct backport labels as described by the internal
  backporting document.
- [ ] **Commit Type** Ensure the correct merge method is selected which should be "squash and merge"
  in the majority of situations. The main exceptions are long-lived feature branches or merges where
  history should be preserved.
- [ ] **Enterprise PRs** If this is an enterprise only PR, please add any required changelog entry
  within the public repository.

- [ ] If a change needs to be reverted, we will roll out an update to the code within 7 days.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### CODE REVIEW

**Review by jrasell — DISMISSED** [review]
LGTM!

I think we will also need a changelog entry and backport labels.

File: api/event_stream_test.go [hunk 1]
```diff
@@ -118,6 +119,42 @@ func TestEvent_Stream(t *testing.T) {
...
+	s.Stop()
+
+	for {
+		select {
+		case event, ok := <-streamCh:
+			if !ok {
+				must.Unreachable(t, must.Sprintf("chan closed before EOF received"))
+			}
+
+			// Sadly decode doesn't return io.EOF
```
Comment (chrisroberts) [inline api/event_stream_test.go]: Poking through this, it looks like decode is kicking back an `io.ErrUnexpectedEOF` and swapping this out with an `errors.Is(event.Err, io.ErrUnexpectedEOF)` works as expected.

Comment (schmichael) [reply api/event_stream_test.go]: Great catch! Fixed.

**Review by chrisroberts — APPROVED** [review]
