### PR TITLE
Show node attribute in node-status

### LINKED ISSUE #303: nomad node-status <node id> should show capabilities and cpu/memory max/available
Related to #302 it would be helpful when trying to troubleshoot bugs and setup issues if there was an easy way to see node capabilities and resource availability. Sometimes it's hard to tell if something is failing to allocate because there is an actual problem or if nomad is simply not seeing some resources it actually does have available.

### PR DESCRIPTION
**Pull request by achanda**
Adds node attributes to the node-status command when a single
node ID is passed

Closes #303

### CODE REVIEW

**Comment by achanda** [comment]
Currently this looks like this:
```
Abhishek@dev:~/gosrc/bin$ nomad node-status 2649b1ef-de9a-1427-9a19-42b899725ece
ID         = 2649b1ef-de9a-1427-9a19-42b899725ece
Name       = dev
Class      = <none>
Datacenter = dc1
Drain      = false
Status     = ready
Attributes = cpu.numcores:128, cpu.frequency:2600.000000, driver.docker.version:1.8.3, hostname:dev, platform.gce.machine-type:n1-standard-16, storage.bytestotal:105654812672, driver.docker:1, driver.exec:1, driver.rkt.version:rkt version 0.9.0, memory.totalbytes:63332859904, platform.gce.scheduling.on-host-maintenance:MIGRATE, storage.bytesfree:91570016256, driver.java.runtime:OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1), os.version:14.04, platform.gce.cpu-platform:Intel Sandy Bridge, platform.gce.network.default:true, platform.gce.tag.https-server:true, driver.java:1, driver.java.vm:OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode), driver.rkt:1, platform.gce.network.default.ip:10.240.209.200, platform.gce.scheduling.automatic-restart:TRUE, os.name:ubuntu, platform.gce.hostname:dev.c.cloudblocks.cloudscaling.com.internal, platform.gce.network.default.external-ip.0:104.197.131.232, cpu.totalcompute:332800.000000, driver.java.version:1.7.0_79, driver.rkt.appc.version:0.9., kernel.version:3.19.0-30-generic, network.ip-address:10.240.209.200, storage.volume:/dev/sda1, arch:amd64, cpu.modelname:Intel(R) Xeon(R) CPU @ 2.60GHz, kernel.name:linux, platform.gce.id:13085678475098123138, platform.gce.zone:us-central1-a, platform.gce.tag.http-server:true

### Allocations
ID  EvalID  JobID  TaskGroup  DesiredStatus  ClientStatus
```

Trying to see how to make this equally human and machine readable. Open to feedback.

File: command/node_status.go [hunk 1]
```diff
@@ -111,6 +116,7 @@ func (c *NodeStatusCommand) Run(args []string) int {
 		fmt.Sprintf("Datacenter|%s", node.Datacenter),
 		fmt.Sprintf("Drain|%v", node.Drain),
 		fmt.Sprintf("Status|%s", node.Status),
+                fmt.Sprintf("Attributes|%s", strings.Join(attributes, ", ")),
```
Comment (jippi) [inline command/node_status.go]: indent is off by one

Comment (achanda) [inline command/node_status.go]: That's because of the + sign. If you click on 'View', you will see that it lines up.

File: command/node_status.go [hunk 2]
```diff
@@ -103,6 +103,11 @@ func (c *NodeStatusCommand) Run(args []string) int {
 		return 1
 	}
 
+        var attributes []string
+        for k, v := range node.Attributes {
+                attributes = append(attributes, fmt.Sprintf("%s:%s", k, v))
+        }
```
Comment (dadgar) [inline command/node_status.go]: I would sort the keys and then create the attributes by iterating through the sorted keys and making the list. That way looking for a particular attribute in the output will be a lot easier!

File: command/node_status.go (hunk 1 above)
Comment (cbednarski) [inline command/node_status.go]: I think this is because that line uses spaces instead of tabs. `gofmt` should fix it. @achanda Not sure which editor you use but I have mine set to run `gofmt` when I save a file -- helps with things like this.

**Comment by achanda** [comment]
Example looks like
```
Abhishek@dev:~/gosrc/bin$ nomad node-status cb31a305-3d23-b1ea-a06c-eb9adb37965b
ID         = cb31a305-3d23-b1ea-a06c-eb9adb37965b
Name       = dev
Class      = <none>
Datacenter = dc1
Drain      = false
Status     = ready
Attributes = arch:amd64, cpu.frequency:2600.000000, cpu.modelname:Intel(R) Xeon(R) CPU @ 2.60GHz, cpu.numcores:128, cpu.totalcompute:332800.000000, driver.docker:1, driver.docker.version:1.8.3, driver.exec:1, driver.java:1, driver.java.runtime:OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1), driver.java.version:1.7.0_79, driver.java.vm:OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode), driver.rkt:1, driver.rkt.appc.version:0.9., driver.rkt.version:rkt version 0.9.0, hostname:dev, kernel.name:linux, kernel.version:3.19.0-30-generic, memory.totalbytes:63332859904, network.ip-address:10.240.209.200, os.name:ubuntu, os.version:14.04, platform.gce.cpu-platform:Intel Sandy Bridge, platform.gce.hostname:dev.c.cloudblocks.cloudscaling.com.internal, platform.gce.id:13085678475098123138, platform.gce.machine-type:n1-standard-16, platform.gce.network.default:true, platform.gce.network.default.external-ip.0:104.197.131.232, platform.gce.network.default.ip:10.240.209.200, platform.gce.scheduling.automatic-restart:TRUE, platform.gce.scheduling.on-host-maintenance:MIGRATE, platform.gce.tag.http-server:true, platform.gce.tag.https-server:true, platform.gce.zone:us-central1-a, storage.bytesfree:91253256192, storage.bytestotal:105654812672, storage.volume:/dev/sda1

### Allocations
ID  EvalID  JobID  TaskGroup  DesiredStatus  ClientStatus
```

**Comment by dadgar** [comment]
Awesome! Thanks @achanda
