### PR TITLE
CLI: Return non-zero exit code when deployment fails in `nomad run`

### LINKED ISSUE #10994: CLI: Failed job run with successful rollback should still result in rc != 0
### Nomad version, OS version
Nomad v1.1.2 (60638a086ef9630e2a9ba1e237e8426192a44244)
Centos 7.9

### Issue
A failed deployment, started with "nomad job run", that gets rolled back due to a failure with the update exits with return code 0. This is an error imho, as the initial intention of the command failed. 

Sample output:
```
$ nomad run -var version=1 server-staging.nomad
==> 2021-08-02T18:57:12+02:00: Monitoring evaluation "d26d2bf1"
    2021-08-02T18:57:12+02:00: Evaluation triggered by job "jobspec-staging"
    2021-08-02T18:57:12+02:00: Evaluation within deployment: "c0b8a749"
    2021-08-02T18:57:12+02:00: Allocation "2edcde23" created: node "c152d901", group "jobspec"
    2021-08-02T18:57:12+02:00: Evaluation status changed: "pending" -> "complete"
==> 2021-08-02T18:57:12+02:00: Evaluation "d26d2bf1" finished with status "complete"
==> 2021-08-02T18:57:12+02:00: Monitoring deployment "c0b8a749"
  ⠦ Deployment "c0b8a749" failed
    2021-08-02T19:02:12+02:00
    ID          = c0b8a749
    Job ID      = jobspec-staging
    Job Version = 23
    Status      = failed
    Description = Failed due to progress deadline - rolling back to job version 22
    Deployed
    Task Group         Auto Revert  Desired  Placed  Healthy  Unhealthy  Progress
    Deadline
    jobspec  true         1        3       0        3
    2021-08-02T19:02:12+02:00
  ⠙ Deployment "769e7273" successful
    2021-08-02T19:02:47+02:00
    ID          = 769e7273
    Job ID      = jobspec-staging
    Job Version = 24
    Status      = successful
    Description = Deployment completed successfully
    Deployed
    Task Group         Auto Revert  Desired  Placed  Healthy  Unhealthy  Progress
    Deadline
    jobspec  true         1        1       1        0
    2021-08-02T19:07:45+02:00

$ echo $?
0
```

### Reproduction steps
Configure the job-wide update stanza with "auto_revert = true":
```
    update {
      max_parallel      = 1
      min_healthy_time  = "10s"
      healthy_deadline  = "2m"
      progress_deadline = "5m"
      auto_revert       = true
      stagger           = "30s"
    }
```

#### Expected Result
The initial update failed, the cli should exit with an rc != 0 to enable automation systems (like jenkins) to react without parsing the output or requesting further status. 

#### Actual Result
The "nomad" cli exits with rc=0. I guess this is the case because the rollback succeded.

### LINKED ISSUE #11082: `nomad run` should return non-zero exit code in case of any errors
### Proposal
Return non-zero exit code in case of any errors during deploying an app.

### Use-cases

We switched to `nomad run` from `levant deploy` in our CI scripts, but we noticed, that `nomad run` can return code 0 even when  a deployment is failed:
```
~ $ nomad run my-app.nomad
...
2021-08-25T16:53:10+03:00
ID          = 098fb4b6
Job ID      = my-app
Job Version = 0
Status      = failed
Description = Failed due to progress deadline

Deployed
Task Group  Desired  Placed  Healthy  Unhealthy  Progress Deadline
my-app         1        1       0        1          2021-08-25T16:53:10+03:00

~ $ echo $?
0
```

### Attempted Solutions
Return non-zero code in case of any failures :)

### PR DESCRIPTION
**Pull request by lukas-w**
This PR changes the `nomad run` command (and other commands using the `monitor.monitor` function) to return a non-zero exit code when monitoring is enabled and deployment fails just like `levant deploy` does. This enables CI scripts to easily detect deployment failures. I chose return code `1` to match the existing documentation stating `0` on success, `2` on scheduling problems, and `1` for any other failures. A dedicated return code for deployment failures may makes sense though.

I also noticed and fixed a supposed typo from #10661 via 24fbb5eeb9ad0ae5eeb7ed88afe6ab0928efc1eb: The monitoring code was using `DeploymentStatusDescriptionBlocked` instead of `DeploymentStatusBlocked`.

Fixes #11082, fixes #10994.

### CODE REVIEW

File: command/deployment_status.go [hunk 1]
```diff
@@ -208,7 +208,7 @@ func isStdoutTerminal() bool {
 // but only used for tty and non-Windows machines since glint doesn't work with
 // cmd/PowerShell and non-interactive interfaces
 // Margins are used to match the text alignment from job run
-func (c *DeploymentStatusCommand) ttyMonitor(client *api.Client, deployID string, index uint64, verbose bool) {
+func (c *DeploymentStatusCommand) ttyMonitor(client *api.Client, deployID string, index uint64, verbose bool) (status string, err error) {
```
Comment (tgross) [inline command/deployment_status.go:211]: There's an "inner" `c.ttyMonitor` call that happens on rollback. 

When the outer function returns, we're swallowing the status for the rollback deployment, which seems correct. But we're also swallowing any error returned by the inner `c.ttyMonitor`. If the outer monitor function's `err` is nil, then we should probably set `err` to the error returned by the inner `c.ttyMonitor`. There's no current case where `(*monitor).monitor()` does anything that'd be useful with that error, but it's a place that's easy for someone to change later and then we'd miss the inner error. It's also potentially handy for tests.

(This also applies to `c.defaultMonitor` and its inner `c.defaultMonitor`.)

**Review by tgross — CHANGES_REQUESTED** [review]
Hi @lukas-w! This is looking good! Once you've addressed the comments here, if you'd like to add a changelog item for the [improvement](https://github.com/hashicorp/nomad/blob/main/contributing/CHANGELOG.md#improvements) that'd be great. If that's a confusing mess (understandable), let me know and I'll get that added.

File: command/deployment_status.go (hunk 1 above)
Comment (lukas-w) [reply command/deployment_status.go:211]: I had decided to swallow that inner error because I figured that the most important information to a caller will be whether the deployment succeeded. As far as I understand Go though a caller wouldn't usually use the value of `status` if `err != nil` because a function's return value is considered unreliable if the function errored? So we'd lose that information. Sorry if this is a beginner's question, I'm still new to the language.

**Comment by lukas-w** [comment]
Thanks for the review @tgross! I added a changelog entry via e78fd43216651221fae2f6b238552d365403b5a7 but included the ` release-note:improvement ` formatting. Is that just missing in the part of the page you linked? I couldn't  find any other changelog entry without a type and if I omit it, the entry isn't included in `make changelog`'s output.

File: command/deployment_status.go (hunk 1 above)
Comment (tgross) [reply command/deployment_status.go:211]: Hm... you've got a point there. "Ideomatic go" would say the first value in the returned tuple should be the empty value, but in this case we're using it because it's a status string. Tell you what, let's leave it as you have it here; I'm thinking of future code that hasn't been written yet and might never be written. YAGNI 😀

**Review by tgross — APPROVED** [review]

**Comment by tgross** [comment]
LGTM. The changelog entry is perfect. Thanks @lukas-w!
