### PR TITLE
Change Docker ENV behavior

### LINKED ISSUE #295: nomad agent -dev fails on Windows
OS: Windows Server 2012 R2 Standard
ARCH: amd64

```
C:\>nomad version
Nomad v0.1.2

C:\>nomad agent -dev
==> Starting Nomad agent...
2015/10/16 13:02:05 [ERR] fingerprint.env_aws: Error querying AWS Metadata URL, skipping
==> Error starting agent: client setup failed: driver setup failed: Get http://unix.sock/version: dial unix /var/run/docker.sock: socket: An address incompatible with the requested protocol was used.
```

### PR DESCRIPTION
**Pull request by cbednarski**
- Docker ENV variables now work the same way in production, dev, and test
- Docker ENV variables are *ignored* if docker.endpoint is present in the Nomad config file
- Remote tests now work correctly
- Docker fingerprints correctly on Windows

Fixes #295

### CODE REVIEW

File: client/driver/docker_test.go [hunk 1]
```diff
@@ -147,7 +172,7 @@ func TestDockerDriver_Start_Wait(t *testing.T) {
 }
 
 func TestDockerDriver_Start_Wait_AllocDir(t *testing.T) {
-	if !dockerLocated() {
+	if !dockerIsConnected() || dockerIsRemote() {
```
Comment (dadgar) [inline client/driver/docker_test.go]: Do you need the `|| dockerIsRemote()`?

File: client/driver/docker_test.go [hunk 2]
```diff
@@ -20,11 +21,35 @@ func testDockerDriverContext(task string) *DriverContext {
 	return NewDriverContext(task, cfg, cfg.Node, testLogger())
 }
 
-// dockerLocated looks to see whether docker is available on this system before
-// we try to run tests. We'll keep it simple and just check for the CLI.
-func dockerLocated() bool {
-	_, err := exec.Command("docker", "-v").CombinedOutput()
-	return err == nil
+// dockerIsConnected checks to see if a docker daemon is available (local or remote)
+func dockerIsConnected() bool {
```
Comment (dadgar) [inline client/driver/docker_test.go]: Maybe pass the testing variable in and then instead of returning true/false you can use `t.Skip` and even put the reason. Also `t.Logf`

**Comment by dadgar** [comment]
LGTM

File: client/driver/docker_test.go (hunk 1 above)
Comment (cbednarski) [inline client/driver/docker_test.go]: This test fails with a remote docker host because the alloc dir cannot be mounted remotely.

File: client/driver/docker_test.go (hunk 2 above)
Comment (cbednarski) [inline client/driver/docker_test.go]: That's a good suggestion, but it would change the semantics for the `TestDockerDriver_Fingerprint` case.

**Comment by dadgar** [comment]
Ah I see now why you can't just skip in `dockerIs` methods. Looks good

**Comment by diptanu** [comment]
LGTM
