### PR TITLE
Fix bug in log framer only affecting Windows

### LINKED ISSUE #3342: The `nomad logs -f` command can make windows clients unresponsive/crash.
### Nomad version
Nomad v. 0.6.3

### Operating system and Environment details
Nomad Server - CentOS 7
Nomad Client - Windows Server 2016
Task Driver - Windows Docker container; sample job attached.
Nomad CLI was run on one of the Linux server nodes.

### Issue
After running `nomad logs -f «allocation id» example-task` the allocation will eventually become unresponsive.

### Reproduction steps

Start job
```
nomad run 4973-reproducer.nomad 
```
Note allocation id, get ip:port via
```
nomad alloc-status «allocation id»
```
Tail logs with
```
nomad logs -f «allocation id» example-task
```
While tail is running, request the web page around 20 times at the IP and port noted in alloc-status.  Should see access style logs returned via the nomad logs process.  Stop the tail and wait.

Nomad agent on client will emit massive panic.  One time it was too many threads, this time it was out of memory.

### Nomad Client logs (if appropriate)
[output.log.zip](https://github.com/hashicorp/nomad/files/1369380/output.log.zip)

### Job file (if appropriate)
[4973-reproducer.nomad.zip](https://github.com/hashicorp/nomad/files/1369337/4973-reproducer.nomad.zip)

### PR DESCRIPTION
**Pull request by schmichael**
Fixes #3342

Manually tested on Windows and Linux using the reproducer attached to #3342 on Windows. Although there's nothing special about the job: streaming logs from any job on Windows would cause the issue.

The root cause is that a super subtle misused variable bug in `parseFramerError` would cause a `nil` error to be returned to *after* the framer had exited. `HTTPServer.logs` would see the `nil` error and think it should continue, but since the framer had exited it would immediately return an error which `parseFramerError` would again discard and the loop would repeat.

Normally this sort of tight loop would merely consume a single cpu core and be a nuisance. However this loop spawned a goroutine which would very quickly consume all memory until Nomad itself would OOM.

The 4 commits actually contain distinct fixes:

* 88cb8bb updates some very old dependencies. I was hoping that would fix it, but it did not. Therefore *I'm happy to remove this commit*, but I think keeping these deps up to date is ideal.
* ac3fffc fixes at least 2 races in StreamFramer, however, I did *not* see any evidence either was hit.
* ac3fffc also fixes the error handling bug in `parseFramerError` :point_left: 
* 13a69bd is purely defensive code that should not be hit. I *hate* adding code like that and will remove if asked. I added it in this case because the surrounding code is extremely brittle and it would be extremely easy to cause #3342 another way without this safety check.
* b4bacd6 adds a check for Windows special flavor of "connection closed" error. I looked and looked and found no other way to detect it other than that string comparison. It merely squelches an error from being logged, so the worst case scenario isn't so bad if the string is sometimes wrong (it worked in my testing).

### CODE REVIEW

File: command/agent/fs_endpoint.go [hunk 1]
```diff
@@ -466,8 +473,8 @@ func (s *StreamFramer) Send(file, fileEvent string, data []byte, offset int64) e
 	// If we are not running, return the error that caused us to not run or
 	// indicated that it was never started.
 	if !s.running {
-		if s.Err != nil {
-			return s.Err
+		if s.err != nil {
```
Comment (chelseakomlo) [inline command/agent/fs_endpoint.go]: Should this be `s.Err()`? Otherwise add a comment about why this can be accessed directly.

Comment (chelseakomlo) [reply command/agent/fs_endpoint.go]: Same for line 477

File: command/agent/fs_endpoint.go [hunk 2]
```diff
@@ -916,7 +932,21 @@ func (s *HTTPServer) logs(follow, plain bool, offset int64,
...
 		}
 
-		//Since we successfully streamed, update the overall offset/idx.
+		// defensively check to make sure StreamFramer hasn't stopped
+		// running to avoid tight loops with goroutine leaks as in
+		// #3342
+		select {
+		case <-framer.ExitCh():
+			err := parseFramerErr(framer.Err())
+			if err == syscall.EPIPE {
```
Comment (chelseakomlo) [inline command/agent/fs_endpoint.go]: Can this logic be in parseFramerErr instead, since it already has logic related to translating errors? I.e, does the caller need to do the translation of `syscall.EPIPE` -> nil error directly?

File: command/agent/fs_endpoint.go [hunk 3]
```diff
@@ -379,16 +379,23 @@ func (s *StreamFramer) ExitCh() <-chan struct{} {
...
 // run is the internal run method. It exits if Destroy is called or an error
 // occurs, in which case the exit channel is closed.
 func (s *StreamFramer) run() {
 	var err error
 	defer func() {
-		close(s.exitCh)
 		s.l.Lock()
 		s.running = false
-		s.Err = err
+		s.err = err
```
Comment (chelseakomlo) [inline command/agent/fs_endpoint.go]: Should this be set using a `SetErr()` method that has guards against concurrent access?

Comment (schmichael) [reply command/agent/fs_endpoint.go]: The appropriate lock is acquired on L394 and this should be the only place that sets `s.err` so I don't want to add a helper to encourage other uses.

File: command/agent/fs_endpoint.go (hunk 1 above)
Comment (schmichael) [reply command/agent/fs_endpoint.go]: This method holds the appropriate lock (L470)

File: command/agent/fs_endpoint.go (hunk 2 above)
Comment (preetapan) [reply command/agent/fs_endpoint.go]: it returns the error from parseFramerErr in line 740, but has this extra logic here where it turns that to nil. Good question though - why do we treat the error two different ways?

Comment (preetapan) [reply command/agent/fs_endpoint.go]: Reading this again, I am not convinced this block is necessary (saw your comment about defensive code). But if its here, I would make it return the value of parseFramerErr rather than `nil`.

**Comment by dadgar** [comment]
Does this fix: https://github.com/hashicorp/nomad/issues/2840?

**Comment by schmichael** [comment]
> Does this fix: #2840?
> @dadgar 

I'm unsure. It sounds the same, but I could only reproduce this bug on Windows. Only 16 of the 120 goroutines listed in the snippet of output include the telltale `blockUntilNextLog` function that dominated the vast majority of the goroutines in this case.

File: command/agent/fs_endpoint.go (hunk 2 above)
Comment (schmichael) [reply command/agent/fs_endpoint.go]: This change makes more sense in the actual code and not in the code review I promise. :) The code review cuts out the code 10 lines up that follow similar return behavior when handling the error from `s.stream()`

The error returned from `s.stream()` is already passed through `parseFramerErr()`, then line 924 converts EPIPE to nil in this func.

So this defensive code converts the framer error with the helper func and then follows the same `if err == EPIPE { return nil }` behavior as above.

Sorry the code is obtuse but the good news is that it only determines whether or not an error is logged when a client disconnects (EPIPE errors are *not* logged as they're expected).

The important thing in this defensive code is that we return from this infinite `for{}` loop if the framer has exited. The error code only matters for logging.
