### PR TITLE
UI: Cross region server monitor

### LINKED ISSUE #8885: UI server monitor doesn't work for remote region nodes
### Nomad version
`0.12.4`

### Issue
The servers pages lists all nodes from all regions. When selecting a server you can view the monitor tab to watch the agent logs. However, this only works when the server selected is in the same region. 

### Reproduction steps
Setup a multi-region cluster, and access the server's monitor tab from a different region.

### PR DESCRIPTION
**Pull request by DingoEatingFuzz**
Fixes #8885

This was just some oversight. Switching regions and monitoring a server worked, but since the serves page lists all servers across all regions, we need to special case this one.

### CODE REVIEW

File: ui/tests/integration/components/agent-monitor-test.js [hunk 1]
```diff
@@ -72,13 +72,15 @@ module('Integration | Component | agent-monitor', function(hooks) {
     assert.ok(logRequest.url.startsWith('/v1/agent/monitor'));
     assert.ok(logRequest.url.includes('client_id=client1'));
     assert.ok(logRequest.url.includes('log_level=info'));
+    assert.ok(logRequest.url.includes('log_level=info'));
```
Comment (backspace) [inline ui/tests/integration/components/agent-monitor-test.js:75]: Is this meant to be a different assertion? Or accidental copypaste? 😯

**Review by backspace — CHANGES_REQUESTED** [review]
nice minimal intervention, there’s one tiny duplicated line but 👍🏻 otherwise 😀

File: ui/tests/integration/components/agent-monitor-test.js (hunk 1 above)
Comment (DingoEatingFuzz) [reply ui/tests/integration/components/agent-monitor-test.js:75]: I think this was vim betraying me? Dunno, but I'll clean it up.

**Review by backspace — APPROVED** [review]
😎
