### PR TITLE
account for discontinuous node IDs in numa detection

### LINKED ISSUE #27266: runtime error: index out of range [8] with length 8
### Nomad version
root@nomad-gh200-01:~# nomad version
Nomad v1.11.0
BuildDate 2025-11-11T16:18:19Z
Revision 9103d938133311b2da905858801f0e111a2df0a1

### Operating system and Environment details
# cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.3 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

# uname -a
Linux nomad-gh200-01 6.8.0-1043-nvidia-64k #46-Ubuntu SMP PREEMPT_DYNAMIC Thu Oct 23 22:15:33 UTC 2025 aarch64 aarch64 aarch64 GNU/Linux

### Issue
nomad will usually not start, eventually with auto restarting it will

Both are grace hopper 1 gpu boxes are having the same symptoms

### Nomad Client logs (if appropriate)
```
Dec 15 23:18:21 nomad-gh200-01 systemd[1]: nomad.service: Scheduled restart job, restart counter is at 2.
Dec 15 23:18:21 nomad-gh200-01 systemd[1]: Started nomad.service - Nomad.
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: ==> WARNING: mTLS is not configured - Nomad is not secure without mTLS!
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: ==> Loaded configuration from /etc/nomad.d/nomad.hcl
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: ==> Starting Nomad agent...
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: panic: runtime error: index out of range [8] with length 8
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: goroutine 1 [running]:
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/client/lib/numalib.(*Sysfs).discoverCosts.func1(0x98?)
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/client/lib/numalib/detect_linux.go:118 +0x10c
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/client/lib/idset.(*Set[...]).ForEach-range1(...)
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/client/lib/idset/idset.go:188
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/client/lib/idset.(*Set[...]).Items.func1(...)
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/go-set/v3@v3.0.1/set.go:308
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/client/lib/idset.(*Set[...]).ForEach(0x14aa9cc?, 0x4000b16d40?)
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/client/lib/idset/idset.go:187 +0xc4
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/client/lib/numalib.(*Sysfs).discoverCosts(0x68?, 0x4000c06a80, 0x382b568)
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/client/lib/numalib/detect_linux.go:110 +0x16c
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/client/lib/numalib.(*Sysfs).ScanSystem(0x5fea940, 0x4000c06a80)
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/client/lib/numalib/detect_linux.go:64 +0x40
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/client/lib/numalib.Scan(...)
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/client/lib/numalib/detect.go:23
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/client/fingerprint.(*CPUFingerprint).initialize(0x400107fe40, 0x4001076290)
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/client/fingerprint/cpu.go:90 +0x630
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/client/fingerprint.(*CPUFingerprint).Fingerprint(0x400107fe40, 0x1c83f08?, 0x400108ad80)
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/client/fingerprint/cpu.go:40 +0x24
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/client.(*FingerprintManager).fingerprint(0x4000bf1e00, {0x3?, 0x3da5ec8?}, {0x3d67668, 0x400107fe40})
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/client/fingerprint_manager.go:200 +0x114
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/client.(*FingerprintManager).setupFingerprinters(0x4000bf1e00, {0x4000eee800?, 0x3698dfb?, 0x4000bf6bc0?})
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/client/fingerprint_manager.go:143 +0xac
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/client.(*FingerprintManager).Run(0x4000bf1e00)
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/client/fingerprint_manager.go:107 +0x400
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/client.NewClient(0x4000beea88, {0x3d5ec18, 0x400052fe90}, 0x4000b816a0, {0x3d89680, 0x400098e180}, 0x0)
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/client/client.go:477 +0xda4
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/command/agent.(*Agent).setupClient(0x4000351b00)
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/command/agent/agent.go:1309 +0x22c
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/command/agent.NewAgent(0x4000089408, {0x3daf948, 0x4000ba1140}, {0x3d33e88, 0x4000923518}, 0x4000263400)
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/command/agent/agent.go:161 +0x184
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/command/agent.(*Command).setupAgent(0x400039ce40, 0x4000089408, {0x3daf948, 0x4000ba1140}, {0x3d33e88, 0x4000923518}, 0x4000263400)
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/command/agent/command.go:665 +0x6c
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/nomad/command/agent.(*Command).Run(0x400039ce40, {0x40000720e0, 0x2, 0x2})
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/command/agent/command.go:877 +0x43c
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: github.com/hashicorp/cli.(*CLI).Run(0x4000ed6a00)
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/cli@v1.1.7/cli.go:265 +0x420
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: main.Run({0x40000720d0, 0x3, 0x3})
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/main.go:111 +0x1f8
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]: main.main()
Dec 15 23:18:21 nomad-gh200-01 nomad[369297]:         github.com/hashicorp/nomad/main.go:82 +0x50
Dec 15 23:18:21 nomad-gh200-01 systemd[1]: nomad.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 15 23:18:21 nomad-gh200-01 systemd[1]: nomad.service: Failed with result 'exit-code'.
Dec 15 23:18:23 nomad-gh200-01 systemd[1]: nomad.service: Scheduled restart job, restart counter is at 3.
Dec 15 23:18:23 nomad-gh200-01 systemd[1]: nomad.service: Start request repeated too quickly.
Dec 15 23:18:23 nomad-gh200-01 systemd[1]: nomad.service: Failed with result 'exit-code'.
Dec 15 23:18:23 nomad-gh200-01 systemd[1]: Failed to start nomad.service - Nomad.
```

```
[Mon Dec 15 22:39:57 2025] Fallback order for Node 1: 0
[Mon Dec 15 22:39:57 2025] Built 8 zonelists, mobility grouping on.  Total pages: 7574393
[Mon Dec 15 22:39:57 2025] Policy zone: Normal
[Mon Dec 15 22:39:57 2025] Fallback order for Node 0: 0 1
[Mon Dec 15 22:39:57 2025] Fallback order for Node 1: 1 0
[Mon Dec 15 22:39:57 2025] Fallback order for Node 2: 0 1
[Mon Dec 15 22:39:57 2025] Fallback order for Node 3: 0 1
[Mon Dec 15 22:39:57 2025] Fallback order for Node 4: 0 1
[Mon Dec 15 22:39:57 2025] Fallback order for Node 5: 0 1
[Mon Dec 15 22:39:57 2025] Fallback order for Node 6: 0 1
[Mon Dec 15 22:39:57 2025] Fallback order for Node 7: 0 1
[Mon Dec 15 22:39:57 2025] Fallback order for Node 8: 0 1
[Mon Dec 15 22:39:57 2025] Built 9 zonelists, mobility grouping on.  Total pages: 7582553
[Mon Dec 15 22:39:57 2025] Policy zone: Normal
[Mon Dec 15 22:39:58 2025] Fallback order for Node 0: 0
[Mon Dec 15 22:39:58 2025] Fallback order for Node 1: 0
[Mon Dec 15 22:39:58 2025] Fallback order for Node 2: 0
[Mon Dec 15 22:39:58 2025] Fallback order for Node 3: 0
[Mon Dec 15 22:39:58 2025] Fallback order for Node 4: 0
[Mon Dec 15 22:39:58 2025] Fallback order for Node 5: 0
[Mon Dec 15 22:39:58 2025] Fallback order for Node 6: 0
[Mon Dec 15 22:39:58 2025] Fallback order for Node 7: 0
[Mon Dec 15 22:39:58 2025] Fallback order for Node 8: 0
[Mon Dec 15 22:39:58 2025] Built 9 zonelists, mobility grouping on.  Total pages: 7574393
[Mon Dec 15 22:39:58 2025] Policy zone: Normal
[Mon Dec 15 22:40:02 2025] Fallback order for Node 1: 0
```

### PR DESCRIPTION
**Pull request by tgross**
When we read from the distance tables for NUMA, the code iterates over the node list but implicitly assumes that the node ID is equivalent to the index within the distance table. As it turns out, it's entirely possible to have 8 nodes with IDs like `0,2-8`, which will then hit an index out of range error when we try to read the final node. The unit tests included this case, but obscured this bug because they had invalid distance data where a single distance was listed for 2 nodes.

Use the index of the node ID within the slice when recording the values in the distance tables, and correct the tests.

Fixes: https://github.com/hashicorp/nomad/issues/27266

### Contributor Checklist
- [x] **Changelog Entry** If this PR changes user-facing behavior, please generate and add a
  changelog entry using the `make cl` command.
- [x] **Testing** Please add tests to cover any new functionality or to demonstrate bug fixes and
  ensure regressions will be caught.
- [ ] **Documentation** If the change impacts user-facing functionality such as the CLI, API, UI,
  and job configuration, please update the Nomad product documentation, which is stored in the
  [`web-unified-docs` repo](../web-unified-docs/). Refer to the [`web-unified-docs` contributor guide](../web-unified-docs/tree/docs/contribute.md) for docs guidelines.
  Please also consider whether the change requires notes within the [upgrade
  guide](https://developer.hashicorp.com/nomad/docs/upgrade/upgrade-specific). If you would like help with the docs, tag the `nomad-docs` team in this PR.

### Reviewer Checklist
- [x] **Backport Labels** Please add the correct backport labels as described by the internal
  backporting document.
- [ ] **Commit Type** Ensure the correct merge method is selected which should be "squash and merge"
  in the majority of situations. The main exceptions are long-lived feature branches or merges where
  history should be preserved.
- [ ] **Enterprise PRs** If this is an enterprise only PR, please add any required changelog entry
  within the public repository.

- [ ] If a change needs to be reverted, we will roll out an update to the code within 7 days.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### CODE REVIEW

File: client/lib/numalib/detect_linux_test.go [hunk 1]
```diff
@@ -43,12 +44,12 @@ func badSysData(path string) ([]byte, error) {
 
 func goodSysData(path string) ([]byte, error) {
 	return map[string][]byte{
-		"/sys/devices/system/node/online":                            []byte("0-1"),
+		"/sys/devices/system/node/online":                            []byte("1,3"),
```
Comment (gulducat) [inline client/lib/numalib/detect_linux_test.go:47]: were these `goodSysData`s not actually good? I ask mainly because I'd hate to discard useful variations in valid data.

File: client/lib/numalib/detect_linux_test.go [hunk 2]
```diff
@@ -99,9 +100,36 @@ func goodSysDataAMD(path string) ([]byte, error) {
...
+		"/sys/devices/system/node/online":         []byte("0,2-4"),
+		"/sys/devices/system/cpu/online":          []byte("0-15"),
+		"/sys/devices/system/node/node0/distance": []byte("10 80 80 80"),
+		"/sys/devices/system/node/node0/cpulist":  []byte("0-15"),
+		"/sys/devices/system/node/node2/distance": []byte("80 10 80 80"),
+		"/sys/devices/system/node/node2/cpulist":  []byte(""),
+		"/sys/devices/system/node/node3/distance": []byte("80 80 10 80"),
+		"/sys/devices/system/node/node3/cpulist":  []byte(""),
+		"/sys/devices/system/node/node4/distance": []byte("80 80 80 10"),
+		"/sys/devices/system/node/node4/cpulist":  []byte(""),
```
Comment (gulducat) [inline client/lib/numalib/detect_linux_test.go:117]: are these nodes' `cpulist`s empty just because they're irrelevant to the test? I haven't looked at a lot of these device files in reality, but intuitively we're leaving `1,5-15` out of this test data, and I'm not sure why.

**Review by gulducat — APPROVED** [review]
I have a couple questions about test data, but LGTM!

**Review by chrisroberts — APPROVED** [review]

File: client/lib/numalib/detect_linux_test.go (hunk 1 above)
Comment (tgross) [reply client/lib/numalib/detect_linux_test.go:47]: Exactly! The `node/online` didn't match with the actual nodes in the test cases, and the distance tables were those of a single node system and not a two node system. That's how the bug slipped through.

File: client/lib/numalib/detect_linux_test.go (hunk 2 above)
Comment (tgross) [reply client/lib/numalib/detect_linux_test.go:117]: In #27266 we saw a real-world system where the nodes were discontinuously numbered _and_ all the CPUs were on one of those nodes. Which I certainly would never have guessed could be the case, but upon reflection I think you can simulate with a weird enough QEMU config. This test data reproduces that case.
