### PR TITLE
pool: track usage of incoming streams

### LINKED ISSUE #10579: Alloc Exec spontaneously disconnects after some time
### Nomad version
```
$ nomad version
Nomad v1.0.4 (a480eed0815c54612856d9115a34bb1d1a773e8c)
```

### Operating system and Environment details

Observed with Ubuntu and Void Linux clients, observed with macOS clients, observed with Alpine, Void, and ResinStack servers.  All x64, tested with diversity in network path, underlying provider, and Nomad versions at both ends.

### Issue
When using the `alloc exec` command the shell connects as expected and interactive commands work great.  After some time the session spontaneously disconnects.  Sometimes it disconnects with an error such as `failed to exec into task: disconnected without receiving the exit code`.  Sometimes it disconnects with no error printed at all.

### Reproduction steps

  1. Launch a container of your choosing that contains an interactive shell.  Busybox with the entrypoint set to ["/bin/sleep", "3600"] works well for this.  
  2. Exec into the alloc with `-i -t` options.  
  3. Wait.

After some time you will be disconnected.

#### Expected Result
I expect that unless an external and intentional factor is at play, the session should remain connected.  Examples of external factors include but are not limited to: network path disruption, token expiry, user explicitly disconnecting the session.

#### Actual Result
The interactive exec is disconnected without warning and no discernible cause.

So far I have not found anything in the logs and the job being exec'd into seems to have no effect on how long the session survives.  I think this may be some context internal to Nomad not being renewed, but I have not traced the execution yet.

### PR DESCRIPTION
**Pull request by notnoop**
Track usage of incoming streams on a connection. Connections without
reference counts get marked as unused and reaped in a periodic job.

This fixes a bug where `alloc exec` and `alloc fs` sessions get terminated
unexpectedly. Previously, when a client heartbeats switches between
servers, the pool connection reaper eventually identifies the connection
as unused and closes it even if it has an active exec/fs sessions.

I've tested this code in a live cluster, and had an `alloc exec` command session almost 3 hours before I killed it. Without the change, an `alloc exec` session used to last around 7-20 minutes or so.

Fixes #10579

### CODE REVIEW

File: client/rpc.go [hunk 1]
```diff
@@ -301,7 +300,7 @@ func (c *Client) rpcConnListener() {
 
 // listenConn is used to listen for connections being made from the server on
 // pre-existing connection. This should be called in a goroutine.
-func (c *Client) listenConn(s *yamux.Session) {
+func (c *Client) listenConn(s *pool.Conn) {
```
Comment (tgross) [inline client/rpc.go:303]: Tiniest of nitpicks, but with the type being changed to `*pool.Conn`, naming this argument `s` doesn't make sense anymore. Maybe rename the arg to `p`?

(`pool.Conn` is kind of a weirdly named type in general because it's more like "connection factory" or "connect proxy" given that `Accept()` returns `net.Conn`, but it isn't a "connection pool" either as it contains the connection pool. But probably best not to rework the whole thing. 😀 )

File: helper/pool/pool.go [hunk 2]
```diff
@@ -461,7 +496,7 @@ func (p *ConnPool) RPC(region string, addr net.Addr, version int, method string,
 			p.clearConn(conn)
 		}
 
-		p.releaseConn(conn)
+		conn.releaseUse()
```
Comment (tgross) [inline helper/pool/pool.go:499]: While reviewing this PR I'm noticing we have an existing hidden temporal coupling of `conn.releaseUse()` to `getRPCClient`. If someone were to call `conn.releaseUse` outside of this method without first calling `p.clearConn(conn)`, we can get a value of -1 for the reference count and then not close the connection. The current code is correct but easy for someone to break.

Two suggestions:
* Move this into a `defer conn.releaseUse()` right after we check the error from `getRPCClient` to make the temporal coupling more explicit.
* Maybe make `releaseUse` tolerant of misuse by having it close on `refCount < 1`:

```go
// releaseUse is the complement of `markForUse`, to free up the reference count
func (c *Conn) releaseUse() {
	refCount := atomic.AddInt32(&c.refCount, -1)
	if refCount < 1 && atomic.LoadInt32(&c.shouldClose) == 1 {
		c.Close()	
	}
}
```

**Review by tgross — APPROVED** [review]
Nice work, LGTM. I've left some a couple of comments where I think we could make the existing code harder for developers to break, but I'll leave that to your judgement.

File: client/rpc.go (hunk 1 above)
Comment (notnoop) [reply client/rpc.go:303]: I'll change it to `c`.  FWIW, `pool.Conn` is the underlying physical connection - `pool.Accept()` returns a wrapped `yamux.Session` which also implements `net.Conn` (and clients expect)..

File: helper/pool/pool.go (hunk 2 above)
Comment (notnoop) [reply helper/pool/pool.go:499]: I agree it's brittle, I'll move to defer.

I'm unsure about handling negative refCounts. It's unclear how refCount can be negative by re-ordering calls. Only `conn.releaseUse` decrement the `refCount`. So negative values indicate double-release bugs, and defensive handling will probably lead to yet more subtle cases of unexpected connection closing like this one. I wish we can simply panic on negative values so we can find the source of double free case.

Comment (tgross) [reply helper/pool/pool.go:499]: > So negative values indicate double-release bugs, and defensive handling will probably lead to yet more subtle cases of unexpected connection closing like this one.

That's a good point. Totally agreed on that.
