### PR TITLE
api: Allow tagging latest version of a job

### LINKED ISSUE #27759: Create Job Version Tag API without version number always tagging version 0, must be latest version
### Nomad version
Nomad v1.11.3
BuildDate 2026-03-11T09:10:27Z
Revision 173ab08a0210789da531847c4ce3c3518f7fb34b

### Operating system and Environment details
MacOS Tahoe 26.3.1
### Issue
Trying to use API /v1/job/:job_id/versions/:tag_name/tag without property "Version" to tag the latest version of the job. This behavior is described in the documentation: https://developer.hashicorp.com/nomad/api-docs/jobs#create-job-version-tag
The issue is - in this case, Nomad always tags version 0, not the latest.
Potential root cause: Version is a uint64 in JobApplyTagRequest structure,  so omitted JSON/omitempty behavior yields 0; the state store matches that literally and never resolves "latest".
To solve: implementing optional *uint64 and resolving nil to the highest tracked version.
### Reproduction steps
1. Create a new job. It will be version 0
2. Update job. It will be version 1
3. Send request 
Post /v1/job/:job_id/versions/version_123/tag
Body:
{
    "Description": "The version we can roll back to. V123"
}
#### Expected Result
Tag "version_123" assigned to version 1

#### Actual Result
Tag "version_123" assigned to version 0

### Job file (if appropriate)
Really, any job. Reproducible 100% with any job/any number of versions.

### PR DESCRIPTION
**Pull request by tgross**
The Create Job Version Tag API is documented to tag the latest version if the version flag is omitted. Unfortunately this is only a property of the CLI, which queries the job first to get the latest version (also note this is racy with concurrent job registrations anyways). The struct we use for the API uses a uint64 and not a pointer, so we can't use the zero value of the version field to indicate the latest version either.

Add a `Latest` field on the struct which indicates that we should ignore the zero value of the `Version` field and tag the latest version instead. For backwards compatibility in the CLI, we'll keep the existing approach there for another Nomad major version.

Fixes: https://github.com/hashicorp/nomad/issues/27759

### Testing & Reproduction steps

Deploy a job, update it and deploy it again so there are two versions. Then tag the latest version:

```
$ echo '{"Latest": true, "Description": "something something"}' \
    | nomad operator api /v1/job/example/versions/foo/tag
````

Review the history:

```
$ nomad job history example
Version         = 1
Stable          = false
Submit Date     = 2026-03-26T12:28:14-04:00
Tag Name        = foo
Tag Description = something something

Version     = 0
Stable      = false
Submit Date = 2026-03-26T12:28:05-04:00
```

### Contributor Checklist
- [x] **Changelog Entry** If this PR changes user-facing behavior, please generate and add a
  changelog entry using the `make cl` command.
- [x] **Testing** Please add tests to cover any new functionality or to demonstrate bug fixes and
  ensure regressions will be caught.
- [ ] **Documentation** need to update the API docs. TBD

### Reviewer Checklist
- [x] **Backport Labels** Please add the correct backport labels as described by the internal
  backporting document.
- [ ] **Commit Type** Ensure the correct merge method is selected which should be "squash and merge"
  in the majority of situations. The main exceptions are long-lived feature branches or merges where
  history should be preserved.
- [ ] **Enterprise PRs** If this is an enterprise only PR, please add any required changelog entry
  within the public repository.

- [ ] If a change needs to be reverted, we will roll out an update to the code within 7 days.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### CODE REVIEW

File: api/jobs.go [hunk 1]
```diff
@@ -1701,18 +1701,22 @@ type JobStatusesRequest struct {
 }
 
 type TagVersionRequest struct {
-	Version     uint64
-	Description string
+	Version     uint64 // numeric version of the job to tag
+	Latest      bool   // tag the latest version of the job, if Version if zero/unset
```
Comment (gulducat) [inline api/jobs.go:1705]: I get why this is a uint, because versions only go up, but an int64 could have allowed a -1 for this case, alas.

File: nomad/state/state_store.go [hunk 2]
```diff
@@ -4848,6 +4848,14 @@ func (s *StateStore) updateJobStabilityImpl(index uint64, namespace, jobID strin
 func (s *StateStore) UpdateJobVersionTag(index uint64, namespace string, req *structs.JobApplyTagRequest) error {
 	jobID := req.JobID
 	jobVersion := req.Version
+	if jobVersion == 0 && req.Latest {
```
Comment (gulducat) [inline nomad/state/state_store.go:4851]: We could validate on some layer or another that if Latest, Version must be zero. Not necessary, as Latest is a very clear name, just a thought.

**Review by gulducat — DISMISSED** [review]
LGTM!

File: api/jobs.go (hunk 1 above)
Comment (tgross) [reply api/jobs.go:1705]: `structs.Job.Version` is a uint64 as well, so if we used an int64 for versions anywhere else we'd hypothetically truncate half the possible space of versions. Not likely to be a problem in practice, but then we'd end up having "safe conversion" functions everywhere.

File: nomad/state/state_store.go (hunk 2 above)
Comment (tgross) [reply nomad/state/state_store.go:4851]: Good call! Done in the RPC handler.

File: nomad/job_endpoint.go [hunk 3]
```diff
@@ -2425,6 +2425,9 @@ func (j *Job) TagVersion(args *structs.JobApplyTagRequest, reply *structs.JobTag
 		return structs.ErrPermissionDenied
 	}
 
+	if args.Latest && args.Version > 0 {
+		return fmt.Errorf("version cannot be non-zero when tagging latest")
```
Comment (gulducat) [inline nomad/job_endpoint.go]: nits: this is a `fmt.Errorf` with no formatting, and personally I'd avoid the double negative

```suggestion
		return errors.New("version must be zero when tagging latest")
```

OR the version could be informative to a user?


```suggestion
		return fmt.Errorf("version must be zero when tagging latest, got: %d", args.Version)
```

Comment (tgross) [reply nomad/job_endpoint.go]: Accepted your second suggestion.

> nits: this is a fmt.Errorf with no formatting

Just FYI as of Go 1.26.0 this doesn't matter, which is nice for avoiding churn on lines over time https://go.dev/doc/go1.26#fmtpkgfmt https://go-review.googlesource.com/c/go/+/708836

Comment (gulducat) [reply nomad/job_endpoint.go]: Oh neat, TIL :)

**Review by gulducat — APPROVED** [review]
LGTM 👍
