### PR TITLE
Properly interpolate services on updated tasks

### LINKED ISSUE #2180: Nomad does not register service checks of type script
### Environment

Nomad v0.5.2
Consul v0.7.2
Linux 4.4.0-31-generic

### Issue

Nomad does not register service checks of type `scripts` in case of scaling out the instances. One can see that service check is registered with type `http` (will be detailed later) is registered properly. The scripts have been added to the container using `volumes` configuration. 

I was able to test the same behaviour with `raw_exec` and `Docker`. Both have 100% reproducibility each and every time with the same pattern, so it should be pretty easy to reproduce.

### Reproduction steps

1. Start with below job definition file in (a), replace `LOCAL_SCRIPT_PATH` with the local file path you put the script (b)

    (a) https://gist.github.com/gokhansengun/c3bc63a38649784b0b6ff33b43190b70#file-nginx-nomad
    (b) https://gist.github.com/gokhansengun/c3bc63a38649784b0b6ff33b43190b70#file-cpu-utilization-sh

2. Schedule the job using `nomad run <job_file_path>`. Everything is fine until this point.

    nomad_service_check_initial_status

3. Increase the count to 2 and reschedule with `nomad run <job_file_path>`.

    You should see that the service check of type `http` and name `Serving Pages Status` is registered for the new instance but not service check of type `script` and name `nginx - cpu util`.

    nomad_service_check_scale_by_1_status

4. Increase the count to 3 and again reschedule.

    You should see that the two instances have both the service checks registered but one instance not.

    nomad_service_check_scale_by_2_status

### PR DESCRIPTION
**Pull request by schmichael**
Previously was interpolating the original task's services again.

Fixes #2180

Also fixes a slight memory leak in the new consul agent. Script check
handles weren't being deleted after cancellation.

### CODE REVIEW

File: client/task_runner.go [hunk 1]
```diff
@@ -1442,7 +1442,7 @@ func (r *TaskRunner) updateServices(d driver.Driver, h driver.ScriptExecutor, ol
 		// Allow set the script executor if the driver supports it
 		exec = h
 	}
-	interpolateServices(r.getTaskEnv(), r.task)
+	interpolateServices(r.getTaskEnv(), new)
```
Comment (dadgar) [inline client/task_runner.go]: Won't `r.getTaskEnv()` be materializing the wrong environment variables as well.

The task is only updated after this call on the task_runner: https://github.com/hashicorp/nomad/pull/2591/files#diff-e14e934fe7956cfba40a0a0f1419a173L1434

**Comment by schmichael** [comment]
Fixed and added a test which I should have done from the beginning.
