### PR TITLE
env_aws: use best-effort lookup table for CPU performance in EC2

### LINKED ISSUE #7681: Available CPU MHz Varying Wildly for Same Instance Type
### Nomad version
Nomad v0.10.4 (f750636ca68e17dcd2445c1ab9c5a34f9ac69345)

### Operating system and Environment details
Amazon Linux 2 with a fixed head node and an auto-scaling group of `c5.24xlarge` instances, with scaling driven by Nomad state using a custom cloud metric.

### Issue
The number of MHz available on a node varies wildly.  For the exact same instance type (96 cores, 3 GHz stock, 3.9 GHz max), I'm seeing as low as 1.6E5 MHz all the way up to 3.4E5 MHz.  Just now, I've launched 3 `c5.24xlarge` nodes, and their max MHz are
* 305184
* 280128
* 340800

I'd rather not hard-wire `cpu_total_compute` in the client config, and everything else I've read claims Nomad sets the MHz based on core count multiplied by rated clock speed rather than current.

Having MHz vary like this causes jobs to not be placed, even when the node actually has the capacity.  Would a short-term fix be forcing all but one core to 100%, launching the Nomad client, and taking the load off of CPU?  The docs I've read claim Nomad uses stock clock speed, so I'm kind of at a loss here. 

### Reproduction steps
Launch a few instances of the same type with the Nomad client running on boot (I'm using `systemctl`).  Rated MHz for each client in the web UI should vary appreciably.

### PR DESCRIPTION
**Pull request by shoenig**
Fixes #7681

The current behavior of the CPU fingerprinter in AWS is that it
reads the **current** speed from `/proc/cpuinfo` (`CPU MHz` field).

This is because the max CPU frequency is not available by reading
anything on the EC2 instance itself. Normally on Linux one would
look at e.g. `sys/devices/system/cpu/cpuN/cpufreq/cpuinfo_max_freq`
or perhaps parse the values from the `CPU max MHz` field in
`/proc/cpuinfo`, but those values are not available.

Furthermore, no metadata about the CPU is made available in the
EC2 metadata service.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-categories.html

Since `go-psutil` cannot determine the max CPU speed it defaults to
the current CPU speed, which could be basically any number between
0 and the true max. This is particularly bad on large, powerful
reserved instances which often idle at ~800 MHz while Nomad does
its fingerprinting (typically IO bound), which Nomad then uses as
the max, which results in severe loss of available resources.

Since the CPU specification is unavailable programmatically (at least
not without sudo) use a best-effort lookup table. This table was
generated by going through every instance type in AWS documentation
and copy-pasting the numbers.
https://aws.amazon.com/ec2/instance-types/

This approach obviously is not ideal as future instance types will
need to be added as they are introduced to AWS. However, using the
table should only be an improvement over the status quo since right
now Nomad miscalculates available CPU resources on all instance types.

### CODE REVIEW

**Comment by shoenig** [comment]
Running Nomad with this change on a `c5.24xlarge` like the original reporter:

#### run 1
```
2020-04-29T01:22:55.187Z [DEBUG] client.fingerprint_mgr.cpu: detected cpu frequency: MHz=3346
2020-04-29T01:22:55.187Z [DEBUG] client.fingerprint_mgr.cpu: detected core count: cores=96
2020-04-29T01:22:55.201Z [DEBUG] client.fingerprint_mgr.env_aws: lookup ec2 cpu model name: model="3.6 GHz Intel Xeon Scalable"
2020-04-29T01:22:55.201Z [DEBUG] client.fingerprint_mgr.env_aws: lookup ec2 cpu frequency: MHz=3600
2020-04-29T01:22:55.201Z [DEBUG] client.fingerprint_mgr.env_aws: lookup ec2 cpu cores: cores=96
2020-04-29T01:22:55.201Z [DEBUG] client.fingerprint_mgr.env_aws: setting ec2 cpu ticks: ticks=345600
```

#### run 2
```
2020-04-29T01:23:58.743Z [DEBUG] client.fingerprint_mgr.cpu: detected cpu frequency: MHz=1335
2020-04-29T01:23:58.743Z [DEBUG] client.fingerprint_mgr.cpu: detected core count: cores=96
2020-04-29T01:23:58.755Z [DEBUG] client.fingerprint_mgr.env_aws: lookup ec2 cpu model name: model="3.6 GHz Intel Xeon Scalable"
2020-04-29T01:23:58.755Z [DEBUG] client.fingerprint_mgr.env_aws: lookup ec2 cpu frequency: MHz=3600
2020-04-29T01:23:58.755Z [DEBUG] client.fingerprint_mgr.env_aws: lookup ec2 cpu cores: cores=96
2020-04-29T01:23:58.755Z [DEBUG] client.fingerprint_mgr.env_aws: setting ec2 cpu ticks: ticks=345600
```

#### run 3
```
2020-04-29T01:25:19.395Z [DEBUG] client.fingerprint_mgr.cpu: detected cpu frequency: MHz=2218
2020-04-29T01:25:19.395Z [DEBUG] client.fingerprint_mgr.cpu: detected core count: cores=96
2020-04-29T01:25:19.407Z [DEBUG] client.fingerprint_mgr.env_aws: lookup ec2 cpu model name: model="3.6 GHz Intel Xeon Scalable"
2020-04-29T01:25:19.407Z [DEBUG] client.fingerprint_mgr.env_aws: lookup ec2 cpu frequency: MHz=3600
2020-04-29T01:25:19.407Z [DEBUG] client.fingerprint_mgr.env_aws: lookup ec2 cpu cores: cores=96
2020-04-29T01:25:19.407Z [DEBUG] client.fingerprint_mgr.env_aws: setting ec2 cpu ticks: ticks=345600
```

#### plumbing works
```
ubuntu@ip-172-31-84-116:~$ ./nomad node status 17
ID              = 1707aadb-c741-b6ac-b487-b1d713466260
Name            = ip-172-31-84-116
Class           = <none>
DC              = dc1
Drain           = false
Eligibility     = eligible
Status          = ready
CSI Controllers = <none>
CSI Drivers     = <none>
Uptime          = 7m3s
Host Volumes    = <none>
CSI Volumes     = <none>
Driver Status   = mock_driver,raw_exec

Node Events
Time                  Subsystem  Message
2020-04-29T01:25:37Z  Cluster    Node registered

Allocated Resources
CPU           Memory       Disk
0/345600 MHz  0 B/185 GiB  0 B/6.5 GiB

Allocation Resource Utilization
CPU           Memory
0/345600 MHz  0 B/185 GiB

Host Resource Utilization
CPU             Memory           Disk
244/345600 MHz  669 MiB/185 GiB  1.2 GiB/7.7 GiB

Allocations
No allocations placed
```

File: client/fingerprint/env_aws.go [hunk 1]
```diff
@@ -128,25 +475,52 @@ func (f *EnvAWSFingerprint) Fingerprint(request *FingerprintRequest, response *F
...
+		response.AddAttribute("cpu.modelname", specs.model)
+		f.logger.Debug("lookup ec2 cpu model name", "model", specs.model)
 
-		response.NodeResources = &structs.NodeResources{
-			Networks: []*structs.NetworkResource{newNetwork},
+		response.AddAttribute("cpu.frequency", fmt.Sprintf("%.0f", specs.mhz))
+		f.logger.Debug("lookup ec2 cpu frequency", "MHz", log.Fmt("%.0f", specs.mhz))
+
+		response.AddAttribute("cpu.numcores", fmt.Sprintf("%d", specs.cores))
+		f.logger.Debug("lookup ec2 cpu cores", "cores", specs.cores)
```
Comment (notnoop) [inline client/fingerprint/env_aws.go:505]: How would you feel about condensing these to be the same log line?

File: client/fingerprint/env_aws.go [hunk 2]
```diff
@@ -128,25 +475,52 @@ func (f *EnvAWSFingerprint) Fingerprint(request *FingerprintRequest, response *F
...
+			f.logger.Debug("setting ec2 cpu ticks", "ticks", ticks)
+			resources = new(structs.Resources)
+			resources.CPU = ticks
+			if nodeResources == nil {
+				nodeResources = new(structs.NodeResources)
+			}
+			nodeResources.Cpu = structs.NodeCpuResources{CpuShares: int64(ticks)}
 		}
+	} else {
+		f.logger.Warn("no cpu specification found for this instance type")
```
Comment (notnoop) [inline client/fingerprint/env_aws.go:518]: We've been moving to `failed to ...` pattern, so maybe:

```suggestion
		f.logger.Warn("failed to find the cpu specification for this instance type")
```

File: client/fingerprint/env_aws.go [hunk 3]
```diff
@@ -156,6 +530,28 @@ func (f *EnvAWSFingerprint) Fingerprint(request *FingerprintRequest, response *F
...
+	if err != nil {
+		return "", err
+	}
+	return strings.TrimSpace(response), nil
+}
+
+func (f *EnvAWSFingerprint) lookupCPU(ec2meta *ec2metadata.EC2Metadata) *ec2Specs {
+	instanceType, err := f.instanceType(ec2meta)
+	if err != nil {
+		f.logger.Error("error reading instance-type", "error", err)
```
Comment (notnoop) [inline client/fingerprint/env_aws.go:544]: I would downgrade the log to warning.  It's not an actionable for operators, and it's possible they are running on environments that mimic some EC2 metadata but don't show instance-type.

```suggestion
		f.logger.Warn("failed to read EC2 metadata instance-type", "error", err)
```

File: client/fingerprint/env_aws.go [hunk 4]
```diff
@@ -46,6 +46,353 @@ var ec2InstanceSpeedMap = map[*regexp.Regexp]int{
...
+
+func specs(ghz float64, vCores int, model string) ec2Specs {
+	return ec2Specs{
+		mhz:   ghz * 1000,
+		cores: vCores,
+		model: model,
+	}
+}
+
+// Map of instance type to documented CPU speed.
```
Comment (jippi) [inline client/fingerprint/env_aws.go:67]: wonder if this could be automatically build from open source data like [ec2instances.info](https://ec2instances.info/) or AWS's own [API](https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-instance-types.html)

**Comment by jippi** [comment]
Will the [client settings](https://www.nomadproject.io/docs/configuration/client/#cpu_total_compute) still take precedence when configured?

File: client/fingerprint/env_aws.go (hunk 1 above)
Comment (shoenig) [reply client/fingerprint/env_aws.go]: done!

File: client/fingerprint/env_aws.go (hunk 4 above)
Comment (shoenig) [reply client/fingerprint/env_aws.go:67]: Ideally, yes!! Unfortunately ec2instances.info doesn't report `processor-info.sustained-clock-speed-in-ghz` from the API, and using the API requires configuring AWS keys which we don't want Nomad Clients to be burdened with.
Created https://github.com/hashicorp/nomad/issues/7830 which notes an idea of how to automate getting the data from the API

File: client/fingerprint/env_aws.go [hunk 5]
```diff
@@ -46,6 +46,353 @@ var ec2InstanceSpeedMap = map[*regexp.Regexp]int{
...
+//
+// In a few cases, AWS has upgraded the generation of CPU while keeping the same
+// instance designation. Since it is possible to launch on the lower performance
+// CPU, that one is used as the spec for the instance type.
+//
+// This table is provided as a best-effort to determine the number of CPU ticks
+// available for use by Nomad tasks. If an instance type is missing, the fallback
+// behavior is to use values from go-psutil, which is only capable of reading
+// "current" CPU MHz.
+var ec2ProcSpeedTable = map[string]ec2Specs{
```
[the remark this answers is not in the document]
Comment (shoenig) [reply client/fingerprint/env_aws.go:81]: Create https://github.com/hashicorp/nomad/issues/7830 with ideas on how to create a better automated process

**Comment by shoenig** [comment]
@jippi Yep, configuring `cpu_total_compute` continues to take the highest precedence.
