### PR TITLE
docker: Fix volume driver_config options spec

### LINKED ISSUE #5308: Error specifying options in the driver_config for the volume_options of a docker mount
### Nomad version
Nomad v0.9.0-beta2 (29a5d242e69d2db5a36cf58d975f15c279f49a7e)

### Operating system and Environment details
Ubuntu 16.04
Docker 18.09.1

### Issue
Docker driver no longer lets you specify `options` in the `driver_config` for the `volume_options` of a `mount`. (See code example)

### Reproduction steps
Try to start a job which specifies these options.

### Job file
```
    task "some-docker-task" {
      driver = "docker"

      config {
        image = "image:v1.0.0"
        mounts = [
          {
            target = "/storage"
            source = "volume-name"
            volume_options {
              driver_config {
                name = "local"
                options = {
                  type = "nfs"
                  device = "nfs-server.domain:/path/volume-name"
                  o = "addr=nfs-server.domain,vers=3,timeo=180,tcp,rw"
                }
              }
            }
          }
        ]
      }
```
This used to work in 0.8.7, now results in the following error:
```
Driver Failure
2 error(s) occurred: * failed to parse config * :1,79-88: Extraneous JSON object property; No argument or block type is named "options".
```
When commenting out the `mounts[]` block the job starts without issue.

When I stop and purge the job after it gives the error it also isn't properly deregistered in consul. It looks like it also keeps registering it, as it keeps coming back when I deregister it manually until I restart the nomad agent. (This might need it's own ticket, please let me know)

### PR DESCRIPTION
**Pull request by groggemans**
Fixes #5308

### CODE REVIEW

File: drivers/docker/config.go [hunk 1]
```diff
@@ -278,7 +278,7 @@ var (
 				"labels":  hclspec.NewBlockAttrs("labels", "string", false),
 				"driver_config": hclspec.NewBlockSet("driver_config", hclspec.NewObject(map[string]*hclspec.Spec{
```
Comment (notnoop) [inline drivers/docker/config.go]: I think there is another bug in this line, where it should be - I'll follow up in another PR.

```suggestion
				"driver_config": hclspec.NewBlock("driver_config", false, hclspec.NewObject(map[string]*hclspec.Spec{
```
