### PR TITLE
Making the docker driver retry when an image is not found

### LINKED ISSUE #2014: Temporary docker failure - is unrecoverable error
### Nomad version
Nomad v0.5.0

### Operating system and Environment details
Ubuntu server 16.04
Docker 1.12.3

### Issue
Temporary docker failure - is unrecoverable error for nomad.

### Reproduction steps
No.

### Nomad Server logs (if appropriate)

Docker
```
2016-11-20 12:53:28 c1 [docker 27877]  time="2016-11-20T12:53:28.710121858+03:00" level=error msg="Handler for POST /containers/create returned error: No such image: kaktuss/nginx-frontend:0.15"
```

Nomad
```
2016-11-20 12:53:28 c1 [nomad 16781]      2016/11/20 12:53:28.711646 [ERR] driver.docker: failed to create container: no such image
2016-11-20 12:53:28 c1 [nomad 16781]  driver.docker: failed to create container: no such image
2016-11-20 12:53:28 c1 [nomad 16781]      2016/11/20 12:53:28.714431 [INFO] client: failed to start task 'nginx' for alloc '4a9b5678-7e74-fd65-4e36-80d44013edeb': Failed to create container: no such image
2016-11-20 12:53:28 c1 [nomad 16781]  client: failed to start task 'nginx' for alloc '4a9b5678-7e74-fd65-4e36-80d44013edeb': Failed to create container: no such image
2016-11-20 12:53:28 c1 [nomad 16781]      2016/11/20 12:53:28.714987 [INFO] client: Not restarting task: nginx for alloc: 4a9b5678-7e74-fd65-4e36-80d44013edeb
2016-11-20 12:53:28 c1 [nomad 16781]  client: Not restarting task: nginx for alloc: 4a9b5678-7e74-fd65-4e36-80d44013edeb
```

### Nomad Client logs (if appropriate)

```
nomad alloc-status 4a9b5678
ID                 = 4a9b5678
Eval ID            = 9fc2c79d
Name               = nginx-frontend.nginx-frontend[0]
Node ID            = d0eead01
Job ID             = nginx-frontend
Client Status      = failed
Client Description = <none>
Created At         = 11/20/16 12:53:22 MSK

Task "nginx" is "dead"
Task Resources
CPU      Memory  Disk  IOPS  Addresses
100 MHz  64 MiB  0 B   0     http: some ip:80
                             https: some ip:443

Recent Events:
Time                   Type            Description
11/20/16 12:53:28 MSK  Not Restarting  Error was unrecoverable
11/20/16 12:53:28 MSK  Driver Failure  failed to start task 'nginx' for alloc '4a9b5678-7e74-fd65-4e36-80d44013edeb': Failed to create container: no such image
11/20/16 12:53:27 MSK  Received        Task received by client
```

### Job file (if appropriate)

```
job "nginx-frontend" {
  region = "europe"
  datacenters = ["dc-firstbyte", "dc-vmland"]
  type = "system"

  group "nginx-frontend" {

    restart {
      interval = "1m"
      attempts = 2
      delay = "15s"
      mode = "delay"
    }

    task "nginx" {
      driver = "docker"

      config {
        image = "kaktuss/nginx-frontend:0.15"
        hostname = "nginx-frontend.weave.local"
        port_map {
          http = 80
          https = 443
        }
        dns_servers = ["172.18.0.1"]
        network_mode = "host"
        tty = true
        logging = {
          type = "syslog"
          config = {
            syslog-facility = "daemon"
            tag = "nginx"
          }
        }
      }

      service {
        name = "nginx-frontend"
        port = "http"
        check {
          type = "tcp"
          interval = "10s"
          timeout = "2s"
        }
      }

      env {
        CONSUL_HTTP_ADDR = "consul.service.consul:8500"
        CONSUL_TOKEN = "..."
        VAULT_ADDR = "http://vault.service.consul:8200/"
        VAULT_TOKEN = "..."
      }

      resources {
        cpu = 100
        memory = 64
        network {
          mbits = 1
          port "http" {
            static = 80
          }
          port "https" {
            static = 443
          }
        }
      }
    }

  }
}
```

### PR DESCRIPTION
**Pull request by diptanu**
Fixes #2014

### CODE REVIEW

File: client/driver/docker.go [hunk 1]
```diff
@@ -53,7 +53,8 @@ var (
 	recoverableErrTimeouts = func(err error) *structs.RecoverableError {
 		r := false
 		if strings.Contains(err.Error(), "Client.Timeout exceeded while awaiting headers") ||
-			strings.Contains(err.Error(), "EOF") {
+			strings.Contains(err.Error(), "EOF") ||
+			strings.Contains(err.Error(), "no such image") {
```
Comment (dadgar) [inline client/driver/docker.go]: Can you put an XXX to remove in a later release and explain why.
