### PR TITLE
[scheduler] fix scheduling behavior of batch job allocs

### LINKED ISSUE #26929: scheduler: incorrect scheduling of batch job allocations on drain
Nomad scheduling of batch job allocations is currently inconsistent with the documented behavior. From the documentation, batch job allocations should behave in the following ways:

* when stopped with `nomad alloc stop` - [the allocation should be rescheduled](https://developer.hashicorp.com/nomad/commands/alloc/stop)
* when any task statuses become `failed` - [the allocation should be rescheduled](https://developer.hashicorp.com/nomad/docs/job-specification/reschedule)
* when drained - [the allocation should not be replaced](https://developer.hashicorp.com/nomad/commands/node/drain) (allocation is allowed to complete, or killed if deadline reached)

Currently the drain behavior is not working as documented. 

To document the current behavior, a cluster with 3 agents will be used along with the simple jobspec below defining a batch job:

<details><summary>batch jobspec</summary>

```hcl
job "sleep-job" {
  type = "batch"

  group "sleeper" {
    count = 5

    ephemeral_disk {
      size = 10
    }

    task "do_sleep" {
      driver = "raw_exec"

      logs {
        disabled      = true
        max_files     = 1
        max_file_size = 1
      }

      config {
        command = "sleep"
        args    = ["1d"]
      }

      resources {
        memory = 10
        cpu    = 5
      }
    }

    task "extra_sleep" {
      driver = "raw_exec"

      logs {
        disabled      = true
        max_files     = 1
        max_file_size = 1
      }

      config {
        command = "sleep"
        args    = ["1d"]
      }

      resources {
        memory = 10
        cpu    = 5
      }
    }
  }
}
```
</details>

## drain behavior

Running the job we get an initial status:

```
Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
sleeper     0       0         5        0       0         0     0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created  Modified
25f432b7  490b97bb  sleeper     0        run      running  3s ago   2s ago
a8eb00d4  717d40fd  sleeper     0        run      running  3s ago   2s ago
d05c5866  52a010ff  sleeper     0        run      running  3s ago   2s ago
dffa4043  490b97bb  sleeper     0        run      running  3s ago   2s ago
ec349a28  52a010ff  sleeper     0        run      running  3s ago   2s ago
```

Now, draining node `490b97bb` with a deadline of 2s results in:

```
Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
sleeper     0       0         5        2       0         0     0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created   Modified
7ab9320e  52a010ff  sleeper     0        run      running  3s ago    2s ago
ccb7284f  717d40fd  sleeper     0        run      running  3s ago    2s ago
25f432b7  490b97bb  sleeper     0        stop     failed   2m6s ago  3s ago
a8eb00d4  717d40fd  sleeper     0        run      running  2m6s ago  2m5s ago
d05c5866  52a010ff  sleeper     0        run      running  2m6s ago  2m5s ago
dffa4043  490b97bb  sleeper     0        stop     failed   2m6s ago  2s ago
ec349a28  52a010ff  sleeper     0        run      running  2m6s ago  2m5s ago
```

The two allocations which were running on node `490b97bb` have a status of `failed` and were rescheduled. The expected behavior should be the two allocations having a status of `complete` and not being rescheduled.

### PR DESCRIPTION
**Pull request by chrisroberts**
### Description

Batch jobs have a few documented behaviors which are described here:

* when stopped with `nomad alloc stop` - [the allocation should be rescheduled](https://developer.hashicorp.com/nomad/commands/alloc/stop)
* when any task statuses become `failed` - [the allocation should be rescheduled](https://developer.hashicorp.com/nomad/docs/job-specification/reschedule)
* when drained - [the allocation should not be replaced](https://developer.hashicorp.com/nomad/commands/node/drain) (allocation is allowed to complete, or killed if deadline reached)
* when `job restart` is used with the `-reschedule` flag - [stops and migrates allocations instead of restarting in-place](https://developer.hashicorp.com/nomad/commands/job/restart#reschedule) (this command migrates but does not reschedule allocations, so it ignores the `reschedule` block)

This changeset updates Nomad's behavior with batch job allocations so they behave as documented. Within this changeset, modifications introduced in dfa07e1 (#26025) that forced batch job allocations into a failed state when migrating. The reported issue it was attempting to resolve was itself incorrect behavior. The reconciler has been adjusted to properly handle batch job allocations as documented.

##### Eval trigger reasons

A new new eval trigger reason was added to provide better information to the user. It is shown and explained in the last examples below.

* [EvalTriggerAllocReschedule](https://github.com/hashicorp/nomad/pull/26961/files#diff-297649e31d8e88fd89ff63dac7aff450569cca19009616f08c1d73d1e8239725R12451)

##### Allocations API

The [Allocations.Stop](https://github.com/hashicorp/nomad/pull/26961/files#diff-b4fa614bde4cb3604e2b5a1b95d00e4381a06e6e1cb1a29f2c34fe44a0444d01L192) function was using an old helper which was resulting in any defined query parameters being silently dropped. This was updated to use the newer helper when passes the full query.

The `Allocation.DesiredTransition` was also [updated](https://github.com/hashicorp/nomad/pull/26961/files#diff-b4fa614bde4cb3604e2b5a1b95d00e4381a06e6e1cb1a29f2c34fe44a0444d01R580) to match its counterpart along with the same helper functions.

##### New desired transition field

A new field is added to the `DesiredTransition` - [MigrateDisablePlacement](https://github.com/hashicorp/nomad/pull/26961/files#diff-297649e31d8e88fd89ff63dac7aff450569cca19009616f08c1d73d1e8239725R10989). This is used when draining to allow the allocation to be stopped, but prevents it from being placed to achieve the desired draining behavior.

### Testing & Reproduction steps

<details><summary>batch jobspec</summary>

```hcl
job "sleep-job" {
  type = "batch"

  group "sleeper" {
    count = 5

    reschedule {
      attempts       = 3
      interval       = "15m"
      delay          = "4m"
      delay_function = "constant"
      max_delay      = "5m"
      unlimited      = false
    }

    ephemeral_disk {
      size = 10
    }

    task "do_sleep" {
      driver = "raw_exec"

      logs {
        disabled      = true
        max_files     = 1
        max_file_size = 1
      }

      config {
        command = "sleep"
        args    = ["1d"]
      }

      resources {
        memory = 10
        cpu    = 5
      }
    }

    task "extra_sleep" {
      driver = "raw_exec"

      logs {
        disabled      = true
        max_files     = 1
        max_file_size = 1
      }

      config {
        command = "sleep"
        args    = ["2d"]
      }

      resources {
        memory = 10
        cpu    = 5
      }
    }
  }
}
```

</details>

##### alloc stop command

This shows the behavior of the `alloc stop` command on a batch job allocation. The job is started and then a single allocation is stopped:

```
➜ nomad run sleep.hcl

==> View this job in the Web UI: http://10.86.244.24:4646/ui/jobs/sleep-job@default

==> 2025-10-17T17:51:06-07:00: Monitoring evaluation "40250ff8"
    2025-10-17T17:51:06-07:00: Evaluation triggered by job "sleep-job"
    2025-10-17T17:51:07-07:00: Allocation "71d6882e" created: node "0e569f27", group "sleeper"
    2025-10-17T17:51:07-07:00: Allocation "8e671f60" created: node "0e569f27", group "sleeper"
    2025-10-17T17:51:07-07:00: Allocation "c72be233" created: node "b0dccea3", group "sleeper"
    2025-10-17T17:51:07-07:00: Allocation "ca3f8856" created: node "6c4fcb70", group "sleeper"
    2025-10-17T17:51:07-07:00: Allocation "421b7a60" created: node "b0dccea3", group "sleeper"
    2025-10-17T17:51:07-07:00: Evaluation status changed: "pending" -> "complete"
==> 2025-10-17T17:51:07-07:00: Evaluation "40250ff8" finished with status "complete"

➜ nomad status sleep-job
ID            = sleep-job
Name          = sleep-job
Submit Date   = 2025-10-17T17:51:06-07:00
Type          = batch
Priority      = 50
Datacenters   = *
Namespace     = default
Node Pool     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
sleeper     0       0         5        0       0         0     0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created  Modified
421b7a60  b0dccea3  sleeper     0        run      running  3s ago   2s ago
71d6882e  0e569f27  sleeper     0        run      running  3s ago   2s ago
8e671f60  0e569f27  sleeper     0        run      running  3s ago   2s ago
c72be233  b0dccea3  sleeper     0        run      running  3s ago   2s ago
ca3f8856  6c4fcb70  sleeper     0        run      running  3s ago   2s ago

➜ nomad alloc stop 42
==> 2025-10-17T17:51:31-07:00: Monitoring evaluation "855d8b1a"
    2025-10-17T17:51:31-07:00: Evaluation triggered by job "sleep-job"
    2025-10-17T17:51:32-07:00: Allocation "8b1af122" created: node "6c4fcb70", group "sleeper"
    2025-10-17T17:51:32-07:00: Evaluation status changed: "pending" -> "complete"
==> 2025-10-17T17:51:32-07:00: Evaluation "855d8b1a" finished with status "complete"

➜ nomad status sleep-job
ID            = sleep-job
Name          = sleep-job
Submit Date   = 2025-10-17T17:51:06-07:00
Type          = batch
Priority      = 50
Datacenters   = *
Namespace     = default
Node Pool     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
sleeper     0       0         5        1       0         0     0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created  Modified
8b1af122  6c4fcb70  sleeper     0        run      running  3s ago   2s ago
421b7a60  b0dccea3  sleeper     0        stop     failed   29s ago  3s ago
71d6882e  0e569f27  sleeper     0        run      running  29s ago  28s ago
8e671f60  0e569f27  sleeper     0        run      running  29s ago  28s ago
c72be233  b0dccea3  sleeper     0        run      running  29s ago  28s ago
ca3f8856  6c4fcb70  sleeper     0        run      running  29s ago  28s ago
```

Here we can see the result of the `alloc stop` command is the allocation is stopped in a failed state and the allocation is immediately replaced. The desired behavior here is that the allocation should be stopped with a `complete` status, and the allocation should be rescheduled based on the reschedule policy.

##### drain behavior 

This shows the behavior of a node drain on batch job allocations. The job is started and then a single node is drained with a one second deadline:

```
➜ nomad run sleep.hcl

==> View this job in the Web UI: http://10.86.244.24:4646/ui/jobs/sleep-job@default

==> 2025-10-17T17:58:19-07:00: Monitoring evaluation "28b04ae3"
    2025-10-17T17:58:19-07:00: Evaluation triggered by job "sleep-job"
    2025-10-17T17:58:20-07:00: Allocation "8841e305" created: node "6c4fcb70", group "sleeper"
    2025-10-17T17:58:20-07:00: Allocation "de029dc7" created: node "6c4fcb70", group "sleeper"
    2025-10-17T17:58:20-07:00: Allocation "f33973b8" created: node "0e569f27", group "sleeper"
    2025-10-17T17:58:20-07:00: Allocation "2d9fb037" created: node "b0dccea3", group "sleeper"
    2025-10-17T17:58:20-07:00: Allocation "733eb34d" created: node "b0dccea3", group "sleeper"
    2025-10-17T17:58:20-07:00: Evaluation status changed: "pending" -> "complete"
==> 2025-10-17T17:58:20-07:00: Evaluation "28b04ae3" finished with status "complete"

➜ nomad status sleep-job
ID            = sleep-job
Name          = sleep-job
Submit Date   = 2025-10-17T17:58:19-07:00
Type          = batch
Priority      = 50
Datacenters   = *
Namespace     = default
Node Pool     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
sleeper     0       0         5        0       0         0     0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created  Modified
2d9fb037  b0dccea3  sleeper     0        run      running  4s ago   3s ago
733eb34d  b0dccea3  sleeper     0        run      running  4s ago   3s ago
8841e305  6c4fcb70  sleeper     0        run      running  4s ago   3s ago
de029dc7  6c4fcb70  sleeper     0        run      running  4s ago   3s ago
f33973b8  0e569f27  sleeper     0        run      running  4s ago   3s ago


➜ nomad node drain -enable -yes -deadline 1s b0
2025-10-17T17:58:36-07:00: Ctrl-C to stop monitoring: will not cancel the node drain
2025-10-17T17:58:36-07:00: Node "b0dccea3-ab06-6141-474b-05f5892f72b8" drain strategy set
2025-10-17T17:58:38-07:00: Alloc "2d9fb037-5c72-786b-21c2-5e0938463f53" marked for migration
2025-10-17T17:58:38-07:00: Alloc "733eb34d-a409-6469-1245-8607a8c57804" marked for migration
2025-10-17T17:58:38-07:00: Drain complete for node b0dccea3-ab06-6141-474b-05f5892f72b8
2025-10-17T17:58:38-07:00: Alloc "2d9fb037-5c72-786b-21c2-5e0938463f53" draining
2025-10-17T17:58:38-07:00: Alloc "733eb34d-a409-6469-1245-8607a8c57804" draining
2025-10-17T17:58:39-07:00: Alloc "2d9fb037-5c72-786b-21c2-5e0938463f53" status running -> failed
2025-10-17T17:58:39-07:00: Alloc "733eb34d-a409-6469-1245-8607a8c57804" status running -> failed
2025-10-17T17:58:39-07:00: All allocations on node "b0dccea3-ab06-6141-474b-05f5892f72b8" have stopped

➜ nomad status sleep-job
ID            = sleep-job
Name          = sleep-job
Submit Date   = 2025-10-17T17:58:19-07:00
Type          = batch
Priority      = 50
Datacenters   = *
Namespace     = default
Node Pool     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
sleeper     0       0         5        2       0         0     0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created  Modified
10065b8b  0e569f27  sleeper     0        run      running  5s ago   4s ago
9d99b920  0e569f27  sleeper     0        run      running  5s ago   4s ago
2d9fb037  b0dccea3  sleeper     0        stop     failed   25s ago  5s ago
733eb34d  b0dccea3  sleeper     0        stop     failed   25s ago  5s ago
8841e305  6c4fcb70  sleeper     0        run      running  25s ago  24s ago
de029dc7  6c4fcb70  sleeper     0        run      running  25s ago  24s ago
f33973b8  0e569f27  sleeper     0        run      running  25s ago  24s ago
```

The drain stops the two allocations on the node in a failed state, and immediately places two new allocations. For drains, the allocations should be stopped with a `complete` status and the allocations should not be replaced.

##### alloc stop command

```
➜ nomad run sleep.hcl

==> 2025-10-20T08:10:34-07:00: Monitoring evaluation "d89ce708"
    2025-10-20T08:10:34-07:00: Evaluation triggered by job "sleep-job"
    2025-10-20T08:10:35-07:00: Allocation "05ad7436" created: node "6c4fcb70", group "sleeper"
    2025-10-20T08:10:35-07:00: Allocation "7a1b5420" created: node "0e569f27", group "sleeper"
    2025-10-20T08:10:35-07:00: Allocation "995f5e33" created: node "b0dccea3", group "sleeper"
    2025-10-20T08:10:35-07:00: Allocation "a5fd7420" created: node "0e569f27", group "sleeper"
    2025-10-20T08:10:35-07:00: Allocation "c5c12c43" created: node "6c4fcb70", group "sleeper"
    2025-10-20T08:10:35-07:00: Evaluation status changed: "pending" -> "complete"
==> 2025-10-20T08:10:35-07:00: Evaluation "d89ce708" finished with status "complete"

➜ nomad status sleep-job
ID            = sleep-job
Name          = sleep-job
Submit Date   = 2025-10-20T08:10:34-07:00
Type          = batch
Priority      = 50
Datacenters   = *
Namespace     = default
Node Pool     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
sleeper     0       0         5        0       0         0     0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created  Modified
05ad7436  6c4fcb70  sleeper     0        run      running  3s ago   2s ago
7a1b5420  0e569f27  sleeper     0        run      running  3s ago   2s ago
995f5e33  b0dccea3  sleeper     0        run      running  3s ago   2s ago
a5fd7420  0e569f27  sleeper     0        run      running  3s ago   2s ago
c5c12c43  6c4fcb70  sleeper     0        run      running  3s ago   2s ago

➜ nomad alloc stop 05
==> 2025-10-20T08:10:43-07:00: Monitoring evaluation "abb43bda"
    2025-10-20T08:10:43-07:00: Evaluation triggered by job "sleep-job"
    2025-10-20T08:10:44-07:00: Evaluation status changed: "pending" -> "complete"
==> 2025-10-20T08:10:44-07:00: Evaluation "abb43bda" finished with status "complete"

➜ nomad status sleep-job
ID            = sleep-job
Name          = sleep-job
Submit Date   = 2025-10-20T08:10:34-07:00
Type          = batch
Priority      = 50
Datacenters   = *
Namespace     = default
Node Pool     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
sleeper     0       0         4        0       1         0     0

Future Rescheduling Attempts
Task Group  Eval ID   Eval Time
sleeper     63d25748  3m47s from now

Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created  Modified
05ad7436  6c4fcb70  sleeper     0        stop     complete  14s ago  4s ago
7a1b5420  0e569f27  sleeper     0        run      running   14s ago  13s ago
995f5e33  b0dccea3  sleeper     0        run      running   14s ago  13s ago
a5fd7420  0e569f27  sleeper     0        run      running   14s ago  13s ago
c5c12c43  6c4fcb70  sleeper     0        run      running   14s ago  13s ago

➜ nomad status sleep-job
ID            = sleep-job
Name          = sleep-job
Submit Date   = 2025-10-20T08:10:34-07:00
Type          = batch
Priority      = 50
Datacenters   = *
Namespace     = default
Node Pool     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
sleeper     0       0         5        0       1         0     0

Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created    Modified
0befef56  b0dccea3  sleeper     0        run      running   3m56s ago  3m55s ago
05ad7436  6c4fcb70  sleeper     0        stop     complete  7m57s ago  7m47s ago
7a1b5420  0e569f27  sleeper     0        run      running   7m57s ago  7m56s ago
995f5e33  b0dccea3  sleeper     0        run      running   7m57s ago  7m56s ago
a5fd7420  0e569f27  sleeper     0        run      running   7m57s ago  7m56s ago
c5c12c43  6c4fcb70  sleeper     0        run      running   7m57s ago  7m56s ago
```

Now the allocation is stopped, in a complete state, and a new allocation hasn't immediately replaced it. Instead, the allocation has been rescheduled based on the reschedule policy as expected from the documented behavior. Once the delayed evaluation is executed, the new allocation is placed.

##### drain behavior 

This shows the behavior of a node drain on batch job allocations. The job is started and then a single node is drained with a one second deadline:

```
➜ nomad run sleep.hcl

==> 2025-10-20T08:21:36-07:00: Monitoring evaluation "ad5b6d81"
    2025-10-20T08:21:36-07:00: Evaluation triggered by job "sleep-job"
    2025-10-20T08:21:37-07:00: Allocation "f7af18cc" created: node "0e569f27", group "sleeper"
    2025-10-20T08:21:37-07:00: Allocation "7386d7b1" created: node "b0dccea3", group "sleeper"
    2025-10-20T08:21:37-07:00: Allocation "8392ca41" created: node "6c4fcb70", group "sleeper"
    2025-10-20T08:21:37-07:00: Allocation "8765c6ba" created: node "6c4fcb70", group "sleeper"
    2025-10-20T08:21:37-07:00: Allocation "d647f127" created: node "b0dccea3", group "sleeper"
    2025-10-20T08:21:37-07:00: Evaluation status changed: "pending" -> "complete"
==> 2025-10-20T08:21:37-07:00: Evaluation "ad5b6d81" finished with status "complete"

➜ nomad status sleep-job
ID            = sleep-job
Name          = sleep-job
Submit Date   = 2025-10-20T08:21:36-07:00
Type          = batch
Priority      = 50
Datacenters   = *
Namespace     = default
Node Pool     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
sleeper     0       0         5        0       0         0     0

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created  Modified
7386d7b1  b0dccea3  sleeper     0        run      running  4s ago   3s ago
8392ca41  6c4fcb70  sleeper     0        run      running  4s ago   3s ago
8765c6ba  6c4fcb70  sleeper     0        run      running  4s ago   3s ago
d647f127  b0dccea3  sleeper     0        run      running  4s ago   3s ago
f7af18cc  0e569f27  sleeper     0        run      running  4s ago   4s ago

➜ nomad node drain -enable -yes -deadline 1s b0
2025-10-20T08:22:11-07:00: Ctrl-C to stop monitoring: will not cancel the node drain
2025-10-20T08:22:11-07:00: Node "b0dccea3-ab06-6141-474b-05f5892f72b8" drain strategy set
2025-10-20T08:22:13-07:00: Alloc "7386d7b1-fe02-a718-58a5-54dcd196937c" marked for migration
2025-10-20T08:22:13-07:00: Alloc "d647f127-203f-9536-56ea-5f6ee595c493" marked for migration
2025-10-20T08:22:13-07:00: Drain complete for node b0dccea3-ab06-6141-474b-05f5892f72b8
2025-10-20T08:22:14-07:00: Alloc "7386d7b1-fe02-a718-58a5-54dcd196937c" draining
2025-10-20T08:22:14-07:00: Alloc "d647f127-203f-9536-56ea-5f6ee595c493" draining
2025-10-20T08:22:14-07:00: Alloc "7386d7b1-fe02-a718-58a5-54dcd196937c" status running -> complete
2025-10-20T08:22:14-07:00: Alloc "d647f127-203f-9536-56ea-5f6ee595c493" status running -> complete
2025-10-20T08:22:14-07:00: All allocations on node "b0dccea3-ab06-6141-474b-05f5892f72b8" have stopped

➜ nomad status sleep-job
ID            = sleep-job
Name          = sleep-job
Submit Date   = 2025-10-20T08:21:36-07:00
Type          = batch
Priority      = 50
Datacenters   = *
Namespace     = default
Node Pool     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost  Unknown
sleeper     0       0         3        0       2         0     0

Allocations
ID        Node ID   Task Group  Version  Desired  Status    Created  Modified
7386d7b1  b0dccea3  sleeper     0        stop     complete  41s ago  4s ago
8392ca41  6c4fcb70  sleeper     0        run      running   41s ago  40s ago
8765c6ba  6c4fcb70  sleeper     0        run      running   41s ago  40s ago
d647f127  b0dccea3  sleeper     0        stop     complete  41s ago  4s ago
f7af18cc  0e569f27  sleeper     0        run      running   41s ago  41s ago
```

The drain stops the two allocations on the node in a completed state, and the allocations are not replaced. This matches the documented expected behavior.

#### New evaluation trigger reason

The current behavior of nomad when rescheduling an allocation is to assume the allocation being replaced has failed. When stopping an allocation, this results in an `eval status` with the following:

```
➜ nomad eval status 8dd
ID                 = 8dde8bd1
Create Time        = 24s ago
Modify Time        = 24s ago
Status             = pending
Status Description = created for delayed rescheduling
Type               = batch
TriggeredBy        = alloc-failure
Job ID             = sleep-job
Namespace          = default
...
```

The `TriggeredBy` insinuates that the eval was triggered by the allocation failing, but it was triggered by the allocation being rescheduled due to the `alloc stop` command. To more correctly describe the reason, the `EvalTriggerAllocReschedule` constant was introduced and used in this situation, which gives the value `alloc-reschedule` as shown below:

```
➜ nomad eval status 440
ID                 = 44058981
Create Time        = 10s ago
Modify Time        = 10s ago
Status             = pending
Status Description = created for delayed rescheduling
Type               = batch
TriggeredBy        = alloc-reschedule
Job ID             = sleep-job
Namespace          = default
...
```

### Links

Fixes #26929

### Contributor Checklist
- [ ] **Changelog Entry** If this PR changes user-facing behavior, please generate and add a
  changelog entry using the `make cl` command.
- [ ] **Testing** Please add tests to cover any new functionality or to demonstrate bug fixes and
  ensure regressions will be caught.
- [ ] **Documentation** If the change impacts user-facing functionality such as the CLI, API, UI,
  and job configuration, please update the  Nomad website documentation to reflect this. Refer to
  the [website README](../website/README.md) for docs guidelines. Please also consider whether the
  change requires notes within the [upgrade guide](../website/content/docs/upgrade/upgrade-specific.mdx).

### Reviewer Checklist
- [ ] **Backport Labels** Please add the correct backport labels as described by the internal
  backporting document.
- [ ] **Commit Type** Ensure the correct merge method is selected which should be "squash and merge"
  in the majority of situations. The main exceptions are long-lived feature branches or merges where
  history should be preserved.
- [ ] **Enterprise PRs** If this is an enterprise only PR, please add any required changelog entry
  within the public repository. 

- [ ] If a change needs to be reverted, we will roll out an update to the code within 7 days.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### CODE REVIEW

File: scheduler/reconciler/filters.go [hunk 1]
```diff
@@ -28,12 +28,12 @@ func (set allocSet) filterAndStopAll(cs ClusterState) (uint64, []AllocStopResult
...
 
-// filterServerTerminalAllocs returns a new allocSet the includes only
-// non-server-terminal allocations.
+// filterServerTerminalAllocs returns a new allocSet that includes only
+// batch job type or non-server-terminal allocations.
 func (set allocSet) filterServerTerminalAllocs() (remaining allocSet) {
 	remaining = make(allocSet)
 	for id, alloc := range set {
-		if !alloc.ServerTerminalStatus() {
+		if (alloc.Job.Type == structs.JobTypeBatch && !alloc.DesiredTransition.ShouldReschedule()) || !alloc.ServerTerminalStatus() {
```
Comment (tgross) [inline scheduler/reconciler/filters.go]: We're keeping batch allocs if they're server-terminal and don't have desired-transition reschedule. Is this because of `nomad alloc stop`? I don't think those allocs are actually server-terminal until after they've already been through the scheduler once.

In any case, this weird conditional could definitely use a "why" comment.

File: nomad/structs/structs.go [hunk 2]
```diff
@@ -11461,14 +11461,15 @@ func (a *Allocation) MigrateStrategy() *MigrateStrategy {
...
+	isBatch := a.Job.Type == JobTypeBatch
 
 	// If reschedule is disabled, return early
 	if reschedulePolicy == nil || (reschedulePolicy.Attempts == 0 && !reschedulePolicy.Unlimited) {
 		return time.Time{}, false
 	}
 
 	if (a.DesiredStatus == AllocDesiredStatusStop && !a.LastRescheduleFailed()) ||
-		(a.ClientStatus != AllocClientStatusFailed && a.ClientStatus != AllocClientStatusLost) ||
+		(!isBatch && a.ClientStatus != AllocClientStatusFailed && a.ClientStatus != AllocClientStatusLost) ||
```
Comment (tgross) [inline nomad/structs/structs.go]: If I have a batch alloc that's complete, but not yet stopped on the server, this change will mean `NextRescheduleTime` potentially returns true for the eval where we process that update.

File: scheduler/reconciler/reconcile_cluster.go [hunk 3]
```diff
@@ -323,6 +323,7 @@ func (a *AllocReconciler) handleStop(m allocMatrix) (map[string]*structs.Desired
 		as = as.filterByTerminal()
 		desiredChanges := new(structs.DesiredUpdates)
 		desiredChanges.Stop, allocsToStop = as.filterAndStopAll(a.clusterState)
+		// TODO(spox): what is with allocsToStop here? not appended, only last set returned?
```
Comment (tgross) [inline scheduler/reconciler/reconcile_cluster.go]: Yikes, that seems wrong

File: scheduler/reconciler/filters.go [hunk 4]
```diff
@@ -324,7 +324,7 @@ func (set allocSet) filterByRescheduleable(isBatch, isDisconnecting bool,
 		}
 
 		isUntainted, ignore := shouldFilter(alloc, isBatch)
-		if isUntainted && !isDisconnecting {
+		if isUntainted && !isDisconnecting && !alloc.DesiredTransition.ShouldReschedule() {
```
Comment (tgross) [inline scheduler/reconciler/filters.go]: Should this get pushed down into `shouldFilter`? That already has some similar logic and we can make this check batch-specific.

File: scheduler/reconciler/reconcile_cluster.go [hunk 5]
```diff
@@ -420,6 +421,14 @@ func (a *AllocReconciler) computeGroup(group string, all allocSet) (*ReconcileRe
 		a.jobState.JobIsBatch, false, a.clusterState.Now,
 		a.jobState.EvalID, a.jobState.DeploymentCurrent)
 
+	// Determine what set of migrating allocation need to be rescheduled
```
Comment (tgross) [inline scheduler/reconciler/reconcile_cluster.go]: Might be a good idea to identify when we expect to see this: when we've run `alloc stop` (or what about when the alloc fails after the drain is set but before that eval runs?)

File: scheduler/reconciler/reconcile_cluster.go (hunk 3 above)
Comment (chrisroberts) [reply scheduler/reconciler/reconcile_cluster.go]: Yeah, this is just a note for me to investigate a bit and spin out a separate PR.

File: scheduler/reconciler/filters.go (hunk 1 above)
Comment (chrisroberts) [reply scheduler/reconciler/filters.go]: Yes, that is correct that this is because of `alloc stop`. Without this addition to the conditional, when the future eval is run, no allocation will be placed because any existing complete allocations will be counted for the total. Filtering out those that are marked for being rescheduled allows them to actually be placed when the eval is run.

File: nomad/structs/structs.go (hunk 2 above)
Comment (chrisroberts) [reply nomad/structs/structs.go]: Adjusted this to check for rescheduled batch.

File: api/allocations.go [hunk 6]
```diff
@@ -185,24 +185,10 @@ func (a *Allocations) RestartAllTasks(alloc *Allocation, q *QueryOptions) error
 // Note: for cluster topologies where API consumers don't have network access to
 // Nomad clients, set api.ClientConnTimeout to a small value (ex 1ms) to avoid
 // long pauses on this API call.
-//
-// BREAKING: This method will have the following signature in 1.6.0
-// func (a *Allocations) Stop(allocID string, w *WriteOptions) (*AllocStopResponse, error) {
 func (a *Allocations) Stop(alloc *Allocation, q *QueryOptions) (*AllocStopResponse, error) {
```
Comment (tgross) [inline api/allocations.go:188]: Not having a versioned API makes this super painful to fix these kinds of things. You're right better just to back out that intention to change it, and live with it.

File: nomad/drainer_int_test.go [hunk 7]
```diff
@@ -399,7 +399,7 @@ func TestDrainer_AllTypes_Deadline(t *testing.T) {
 
 	// Wait for allocs to be replaced
 	finalAllocs := waitForAllocsStop(t, store, n1.ID, nil)
-	waitForPlacedAllocs(t, store, n2.ID, 5)
+	waitForPlacedAllocs(t, store, n2.ID, 3)
```
Comment (tgross) [inline nomad/drainer_int_test.go:402]: Bah, no wonder this bug lurked for so long!

File: command/agent/alloc_endpoint.go [hunk 8]
```diff
@@ -152,13 +152,23 @@ func (s *HTTPServer) allocStop(allocID string, resp http.ResponseWriter, req *ht
...
+	}
+
+	reschedule := false
+	if rescheduleQS := req.URL.Query().Get("reschedule"); rescheduleQS != "" {
+		var err error
+		reschedule, err = strconv.ParseBool(rescheduleQS)
+		if err != nil {
+			return nil, fmt.Errorf("reschedule value is not a boolean: %w", err)
 		}
 	}
```
Comment (tgross) [inline command/agent/alloc_endpoint.go]: There's a `parseBool` helper in `command/agent/http.go` that you can use like 

```go
reschedule, err := parseBool(req, "reschedule")
if err != nil {
	return nil, err
}
```

(which we could use above for `no_shutdown_delay` as well)

File: scheduler/reconciler/filters.go [hunk 9]
```diff
@@ -28,12 +28,23 @@ func (set allocSet) filterAndStopAll(cs ClusterState) (uint64, []AllocStopResult
 	return uint64(len(set)), allocsToStop
 }
 
-// filterServerTerminalAllocs returns a new allocSet the includes only
-// non-server-terminal allocations.
+// filterServerTerminalAllocs returns a new allocSet that includes only
+// batch job type that are not marked for rescheduling or non-server-terminal
+// allocations.
```
Comment (tgross) [inline scheduler/reconciler/filters.go]: Clarifying the compound clause a bit:

```suggestion
// filterServerTerminalAllocs returns a new allocSet that includes only
// non-server-terminal allocations, and batch job allocs that are not marked for rescheduling.
```

**Review by tgross — DISMISSED** [review]
LGTM!
