### PR TITLE
fix ACL bugs in listing allocs across all namespaces

### LINKED ISSUE #9268: The allocations endpoint with namespace=* does not interact with ACLs as expected
### Nomad version

1.0.0-beta2

### Issue

When ACLs are enabled and a token has permissions to namespaces individually but no permissions for `*`, requesting `/v1/allocations?namespace=*` results in a `403 Forbidden`.

I expected to get all allocations across all namespaces I have permissions for.
### Reproduction steps

1. Create some namespaces
2. Create policies that grant read access to namespaces individually
3. Create a token using those policies
4. Run `http localhost:4646/v1/allocations?namespace=* -- X-Nomad-Token:<token>` or similar

### PR DESCRIPTION
**Pull request by cgbaker**
resolves #9268 

first commit adds a test that multi-namespace queries actually works... as well as a documenting test that ACLs with multi-namespace query didn't work.

second commit fixes the discovered issues, using the multi-namespace pattern employed by `/v1/jobs` and `/v1/scaling/policies`

### CODE REVIEW

File: nomad/state/state_store.go [hunk 1]
```diff
@@ -3329,35 +3329,17 @@ func allocNamespaceFilter(namespace string) func(interface{}) bool {
...
 	ws.Add(iter.WatchCh())
 
-	// Wrap the iterator in a filter
-	nsesFilter := func(raw interface{}) bool {
-		alloc, ok := raw.(*structs.Allocation)
-		if !ok {
-			return true
-		}
-
-		return namespaces[alloc.Namespace]
```
Comment (cgbaker) [inline nomad/state/state_store.go:3356]: this filter was backwards... it also didn't account for the case where `namespaces == nil`, which is what is returned by a short-circuit for management tokens.

this method ultimately wasn't very useful.

File: nomad/alloc_endpoint_test.go [hunk 2]
```diff
@@ -318,16 +319,26 @@ func TestAllocEndpoint_List_AllNamespaces_OSS(t *testing.T) {
...
-	// Create the register request
-	alloc := mock.Alloc()
-	summary := mock.JobSummary(alloc.JobID)
 	state := s1.fsm.State()
 
-	err := state.UpsertJobSummary(999, summary)
-	require.NoError(t, err)
-	err = state.UpsertAllocs(structs.MsgTypeTestSetup, 1000, []*structs.Allocation{alloc})
-	require.NoError(t, err)
+	// two namespaces
```
Comment (cgbaker) [inline nomad/alloc_endpoint_test.go:324]: this previously didn't test multiple namespaces, so i expanded it while i was here

File: nomad/alloc_endpoint.go [hunk 3]
```diff
@@ -29,6 +29,10 @@ func (a *Alloc) List(args *structs.AllocListRequest, reply *structs.AllocListRes
 	}
 	defer metrics.MeasureSince([]string{"nomad", "alloc", "list"}, time.Now())
 
+	if args.RequestNamespace() == structs.AllNamespacesSentinel {
```
Comment (cgbaker) [inline nomad/alloc_endpoint.go:32]: this early jump is the same pattern employed for `/v1/jobs` and `/v1/scaling/policies`:
https://github.com/hashicorp/nomad/blob/3926317613caae4f75f55c627ab08eb8aeb2a4d7/nomad/job_endpoint.go#L1301-L1303
https://github.com/hashicorp/nomad/blob/3926317613caae4f75f55c627ab08eb8aeb2a4d7/nomad/scaling_endpoint.go#L31-L33

File: nomad/alloc_endpoint.go [hunk 4]
```diff
@@ -29,6 +29,10 @@ func (a *Alloc) List(args *structs.AllocListRequest, reply *structs.AllocListRes
...
+		return a.listAllNamespaces(args, reply)
+	}
```
Comment (cgbaker) [inline nomad/alloc_endpoint.go:34]: this early jump is the same pattern employed for `/v1/jobs` and `/v1/scaling/policies`:
https://github.com/hashicorp/nomad/blob/3926317613caae4f75f55c627ab08eb8aeb2a4d7/nomad/job_endpoint.go#L1301-L1303
https://github.com/hashicorp/nomad/blob/3926317613caae4f75f55c627ab08eb8aeb2a4d7/nomad/scaling_endpoint.go#L31-L33

**Review by schmichael — APPROVED** [review]
Great catch. Thanks @DingoEatingFuzz and @cgbaker !
