### PR TITLE
core: emit evals for system jobs on node updates

### LINKED ISSUE #27495: Since Nomad 1.11.2, system jobs are not rescheduled when a node is marked eligible
### Nomad version
```
Nomad v1.11.2
BuildDate 2026-02-11T19:01:47Z
Revision f876384fe3ab03250c3f324a43286bd793a665a7
```

### Operating system and Environment details
AlmaLinux 9

### Issue
When a node is drained for maintenance (including its system jobs), and then marked eligible again, system jobs are not re-scheduled on it. This used to work, but doesn't anymore in 1.11.2

### Reproduction steps

- Have some nodes running system jobs
- Drain a node for maintenance, including its system jobs
- When maintenance is over, mark the node as eligible again
- System jobs are not started automatically on the node

#### Expected Result
System jobs should be immediatly scheduled on the node (it was the case in previous versions)

#### Actual Result
System jobs are not re-scheduled. You have to run `nomad job eval my-system-job` for it to be scheduled. This is painful when running a lot of system jobs, in different namespaces

### PR DESCRIPTION
**Pull request by schmichael**
hashicorp/nomad#27423 moved where system job evals were emitted on node updates, but did not change deduping so that system job evals would never be emitted for nodes on which they had already run.

This is most commonly hit when draining a node with system jobs and then marking it as eligible again. Marking the node eligible must emit an eval for the system job whose alloc was stopped during the drain so that a new alloc is placed.

Fixes #27495

### Contributor Checklist
- [x] **Changelog Entry** If this PR changes user-facing behavior, please generate and add a
  changelog entry using the `make cl` command.
- [x] **Testing** Please add tests to cover any new functionality or to demonstrate bug fixes and
  ensure regressions will be caught.
- [ ] **Documentation** If the change impacts user-facing functionality such as the CLI, API, UI,
  and job configuration, please update the Nomad product documentation, which is stored in the
  [`web-unified-docs` repo](../web-unified-docs/). Refer to the [`web-unified-docs` contributor guide](../web-unified-docs/tree/CONTRIBUTING.md) for docs guidelines.
  Please also consider whether the change requires notes within the [upgrade
  guide](https://developer.hashicorp.com/nomad/docs/upgrade/upgrade-specific). If you would like help with the docs, tag the `nomad-docs` team in this PR.

### Reviewer Checklist
- [x] **Backport Labels** Please add the correct backport labels as described by the internal
  backporting document.
- [ ] **Commit Type** Ensure the correct merge method is selected which should be "squash and merge"
  in the majority of situations. The main exceptions are long-lived feature branches or merges where
  history should be preserved.
- [ ] **Enterprise PRs** If this is an enterprise only PR, please add any required changelog entry
  within the public repository.

- [ ] If a change needs to be reverted, we will roll out an update to the code within 7 days.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

### CODE REVIEW

File: nomad/node_endpoint.go [hunk 1]
```diff
@@ -1910,6 +1909,7 @@ func (n *Node) createNodeEvals(node *structs.Node, nodeIndex uint64) ([]string,
 
 		evals = append(evals, eval)
 		evalIDs = append(evalIDs, eval.ID)
+		jobIDs[alloc.JobNamespacedID()] = struct{}{}
```
Comment (schmichael) [inline nomad/node_endpoint.go:1912]: It's hard to see in the collapsed diff, but I moved this line from above so that it only marks jobIDs as having been handled if we emit an eval for them.

File: nomad/node_endpoint.go [hunk 2]
```diff
@@ -1936,6 +1935,7 @@ func (n *Node) createNodeEvals(node *structs.Node, nodeIndex uint64) ([]string,
 		}
 		evals = append(evals, eval)
 		evalIDs = append(evalIDs, eval.ID)
+		jobIDs[job.NamespacedID()] = struct{}{}
```
Comment (schmichael) [inline nomad/node_endpoint.go:1938]: There's no intervening conditional continuations like the loop above, so this change doesn't have a functional impact. I moved it just for consistency with above.

File: .changelog/27499.txt [hunk 3]
```diff
@@ -0,0 +1,3 @@
+```release-note:bug
+core: Fixed system jobs being restarted after a node is drained and marked eligible again
```
Comment (jrasell) [inline .changelog/27499.txt]: Minor update as when I initially read through this I thought it was to do with using the restart command.
```suggestion
core: Fixed system jobs being rescheduled after a node is drained and marked eligible again
```

**Review by jrasell — APPROVED** [review]
LGTM, thanks for picking this up @schmichael and sorry I missed it.

I tested this locally using 1.11.2 and then this change to confirm the fix, running the following experiment using a 2 node, 3 server cluster:

1. submit the job below
2. drain a node using `nomad node drain -enable`
3. mark the node as eligible via `nomad node eligibility -enable`
4. check the status of the job and allocations

```hcl
job "example" {
  type = "system"
  group "cache" {
    task "redis" {
      driver = "docker"
      config {
        image = "redis:7"
      }
    }
  }
}
```

**Review by jrasell — APPROVED** [review]
