### PR TITLE
Reorder executor lookupBin ordering

### LINKED ISSUE #4809: [potential-bug] raw_exec artifact not set as executable
### Nomad version
`Nomad v0.8.3 (c85483da3471f4bd3a7c3de112e95f551071769f)`

### Operating system and Environment details
```
Distributor ID:	CentOS
Description:	CentOS Linux release 7.5.1804 (Core)
Release:	7.5.1804
Codename:	Core
```

### Issue

When using the raw_exec driver and downloading an artifact binary, the binary is not getting set as executable.

The file permissions:
```
-rw-r--r-- 1 root root 13234400 Oct 26 09:34 nomad-toast_linux_amd64
```

The job error message:
```
Error: fork/exec /srv/nomad-client/alloc/2cd4397f-83ff-967a-049c-17d44593825e/nomad-toast-deployments/local/nomad-toast_linux_amd64: permission denied
```

As far as I am aware when using the raw_exec driver and downloading a binary, nomad/go-getter should be setting the file as executable.

### Job file (if appropriate)

```
artifact {
        source = "https://github.com/jrasell/nomad-toast/releases/download/v0.0.1-rc1/nomad-toast_linux_amd64"

        options {
          checksum = "sha256:4fd86d228e539fad57de3d154c86ccab02d38a6e3d1b815fa34775351f3c287a"
        }
      }
```

```
config {
        command = ${NOMAD_TASK_DIR}/nomad-toast_linux_amd64
}
```

### PR DESCRIPTION
**Pull request by notnoop**
This is a follow up work to https://github.com/hashicorp/nomad/pull/4813 to fix #4809 and fix a regression introduced in 0.9 in marking files in libcontainer executable.

#4809 bug is that `lookupBin` uses `exec.LookPath` when not inspecting task dir files.  `exec.LookPath` only returns a file if it's already marked as an executable path in https://github.com/golang/go/blob/go1.12.1/src/os/exec/lp_unix.go#L24-L27 .  This affects raw exec as if passed an absolute path to file, `lookupBin` returns an error if file isn't already an executable.  This explains why the error manifests when an absolute interpolated path is used (e.g. `${NOMAD_TASK_DIR}/hellov1`) but not when using a task rel dir (e.g. `local/hellov1`) in the above examples used in ticket.

PR #4813 remedied this problem for raw exec but inadvertably broke libcontainer executor, as it made `lookupBin` returns the paths to host files rather than ones found inside chroot.

This PR reorders the evaluation, so we go back to 0.8 behavior of looking up task directories first, but then check for host paths before using `exec.LookPath`.

This PR is broken into three commits to illustrate evolution and confirming hypothesis:
1. 9adab75ac84b5c2a7b84702fae02c2484abb50ad : Adding a test illustrating how libcontainer executor fails at marking processes as executable in https://travis-ci.org/hashicorp/nomad/jobs/514942694 - note that the test doesn't depend on artifacts or interpolated paths
2. d441cdd52f68912e96dc7ee5baf2dcddb0ac8caa: reverting PR #4809 and showing the test fail now with raw_exec case (as expected) in https://travis-ci.org/hashicorp/nomad/jobs/514944065
2. 244544b735a8dbac0e14e7ee85e12a39780cbbb9: in where we add the check in appropriate place next to `exec.LookPath(...)` for absolute paths and have a green job in https://travis-ci.org/hashicorp/nomad/jobs/514945024

## Future work

Inspecting `lookupBin` in 0.8 and 0.9 case, we have a bug in using `exec.LookPath` for the libcontainer executor case.  We should be looking up paths based on the container chroot and container PATH rather than the host's.  However, this is not a 0.9.0 regression and was present in 0.8; so punting to fix it post 0.9.

### CODE REVIEW

File: drivers/shared/executor/executor_test.go [hunk 1]
```diff
@@ -544,3 +544,62 @@ func TestExecutor_Start_Kill_Immediately_WithGrace(pt *testing.T) {
...
+			testExecCmd := testExecutorCommand(t)
+			execCmd, allocDir := testExecCmd.command, testExecCmd.allocDir
+			execCmd.Cmd = nonExecutablePath
+			factory.configureExecCmd(t, execCmd)
+
+			executor := factory.new(testlog.HCLogger(t))
+			defer executor.Shutdown("", 0)
+
+			// need to configure path in chroot with that file if using isolation executor
+			if _, ok := executor.(*UniversalExecutor); !ok {
```
Comment (notnoop) [inline drivers/shared/executor/executor_test.go]: Not sure how to best customize test for executors.  I could have done a string matching against `LibcontainerExecutor` name instead (maybe with use of const) but couldn't check against `LibcontainerExecutor` in macOS where type isn't defined.

File: drivers/shared/executor/executor.go [hunk 2]
```diff
@@ -567,6 +561,14 @@ func lookupBin(taskDir string, bin string) (string, error) {
 		return root, nil
 	}
 
+	// when checking host paths, check with Stat first if path is absolute
+	// as exec.LookPath only considers files already marked as executable
+	// and only consider this for absolute paths to avoid depending on
+	// current directory of nomad which may cause unexpected behavior
+	if _, err := os.Stat(bin); err == nil && filepath.IsAbs(bin) {
```
Comment (notnoop) [inline drivers/shared/executor/executor.go]: I considered allowing relative paths containing `/` that don't require search through PATH; however, I felt that reliance on nomad process current directory can be risky and uninuitive.  Given that this is a fix for a bug in 0.8, I felt it's fine to start with absolute paths first, then support other types of path if it's an issue.

**Comment by notnoop** [comment]
Thanks! 🙇

File: drivers/shared/executor/executor_test.go [hunk 3]
```diff
@@ -544,3 +544,62 @@ func TestExecutor_Start_Kill_Immediately_WithGrace(pt *testing.T) {
...
+			require := require.New(t)
+
+			tmpDir, err := ioutil.TempDir("", "nomad-executor-tests")
+			require.NoError(err)
+			defer os.RemoveAll(tmpDir)
+
+			nonExecutablePath := filepath.Join(tmpDir, "nonexecutablefile")
+			ioutil.WriteFile(nonExecutablePath,
+				[]byte("#!/bin/sh\necho hello world"),
+				0600)
```
Comment (schmichael) [inline drivers/shared/executor/executor_test.go]: This is a great approach!
