### PR TITLE
client/fingerprint/cpu: use fallback total compute value if cpu not detected

### LINKED ISSUE #7989: Nomad unable to launch on EC2 graviton instance types
We go through the trouble of shipping a table of CPU performance data for EC2 types as of v0.11.2, so we should be able to launch here. It looks like the standard CPU fingerprinter causes an error on graviton (ARM) instances, because there is no MHz information available. (On AMD/Intel, data is available but meaningless and discarded).  
```bash
ubuntu@ip-172-31-17-121:~$ curl -s http://169.254.169.254/latest/meta-data/instance-type
a1.medium
```
```bash
ubuntu@ip-172-31-17-121:~$ lscpu
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          1
On-line CPU(s) list:             0
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
BogoMIPS:                        166.66
L1d cache:                       32 KiB
L1i cache:                       48 KiB
L2 cache:                        2 MiB
NUMA node0 CPU(s):               0
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Branch predictor hardening
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
```
```bash
ubuntu@ip-172-31-17-121:~$ ./nomad version 
Nomad v0.11.2 (807cfebe90d56f9e5beec3e72936ebe86acc8ce3)
```
```bash
ubuntu@ip-172-31-17-121:~$ ./nomad agent -dev -log-level=TRACE
==> No configuration files loaded
==> Starting Nomad agent...
==> Error starting agent: client setup failed: fingerprinting failed: cannot detect cpu total compute. CPU compute must be set manually using the client config option "cpu_total_compute"
    2020-05-16T14:58:28.830Z [DEBUG] agent.plugin_loader.docker: using client connection initialized from environment: plugin_dir=
    2020-05-16T14:58:28.830Z [DEBUG] agent.plugin_loader.docker: using client connection initialized from environment: plugin_dir=
    2020-05-16T14:58:28.831Z [INFO]  agent: detected plugin: name=docker type=driver plugin_version=0.1.0
    2020-05-16T14:58:28.831Z [INFO]  agent: detected plugin: name=raw_exec type=driver plugin_version=0.1.0
    2020-05-16T14:58:28.831Z [INFO]  agent: detected plugin: name=exec type=driver plugin_version=0.1.0
    2020-05-16T14:58:28.831Z [INFO]  agent: detected plugin: name=qemu type=driver plugin_version=0.1.0
    2020-05-16T14:58:28.831Z [INFO]  agent: detected plugin: name=java type=driver plugin_version=0.1.0
    2020-05-16T14:58:28.831Z [INFO]  agent: detected plugin: name=nvidia-gpu type=device plugin_version=0.1.0
    2020-05-16T14:58:28.835Z [INFO]  nomad.raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:127.0.0.1:4647 Address:127.0.0.1:4647}]"
    2020-05-16T14:58:28.836Z [INFO]  nomad: serf: EventMemberJoin: ip-172-31-17-121.global 127.0.0.1
    2020-05-16T14:58:28.836Z [INFO]  nomad: starting scheduling worker(s): num_workers=1 schedulers=[service, batch, system, _core]
    2020-05-16T14:58:28.836Z [INFO]  client: using state directory: state_dir=/tmp/NomadClient618123295
    2020-05-16T14:58:28.837Z [INFO]  client: using alloc directory: alloc_dir=/tmp/NomadClient800920818
    2020-05-16T14:58:28.842Z [DEBUG] client.fingerprint_mgr: built-in fingerprints: fingerprinters=[arch, cgroup, consul, cpu, host, memory, network, nomad, signal, storage, vault, env_aws, env_gce]
    2020-05-16T14:58:28.843Z [INFO]  client.fingerprint_mgr.cgroup: cgroups are available
    2020-05-16T14:58:28.843Z [INFO]  nomad.raft: entering follower state: follower="Node at 127.0.0.1:4647 [Follower]" leader=
    2020-05-16T14:58:28.843Z [INFO]  nomad: adding server: server="ip-172-31-17-121.global (Addr: 127.0.0.1:4647) (DC: dc1)"
    2020-05-16T14:58:28.843Z [DEBUG] client.fingerprint_mgr: fingerprinting periodically: fingerprinter=cgroup period=15s
    2020-05-16T14:58:28.844Z [DEBUG] client.fingerprint_mgr.cpu: detected core count: cores=1
```

### PR DESCRIPTION
**Pull request by shoenig**
Previously, Nomad would fail to startup if the CPU fingerprinter could
not detect the cpu total compute (i.e. cores * mhz). This is common on
some EC2 instance types (graviton class), where the env_aws fingerprinter
will override the detected CPU performance with a more accurate value
anyway.

Instead of crashing on startup, have Nomad use a low default for available
cpu performance of 1000 ticks (e.g. 1 core * 1 GHz). This enables Nomad
to get past the ignored cpu fingerprinting on those EC2 instances. The
crashing error message is now a log statement suggesting the setting of
cpu_total_compute in client config.

Fixes #7989

### CODE REVIEW

**Comment by shoenig** [comment]
Quick spot testing on a t4gsmall:

#### env_aws enabled

```
2020-12-09T16:24:47.024Z [DEBUG] client.fingerprint_mgr.cpu: detected core count: cores=2
2020-12-09T16:24:47.024Z [INFO]  client.fingerprint_mgr.cpu: fallback to default cpu total compute, set client config option cpu_total_compute to override
    
2020-12-09T16:24:47.041Z [DEBUG] client.fingerprint_mgr.env_aws: lookup ec2 cpu: cores=2 ghz=2.5
2020-12-09T16:24:47.041Z [DEBUG] client.fingerprint_mgr.env_aws: setting ec2 cpu: ticks=5000

Allocated Resources
CPU         Memory       Disk
0/5000 MHz  0 B/1.8 GiB  0 B/4.3 GiB
```

#### env_aws disabled

```
2020-12-09T16:30:51.484Z [DEBUG] client.fingerprint_mgr.cpu: detected core count: cores=2
2020-12-09T16:30:51.484Z [INFO]  client.fingerprint_mgr.cpu: fallback to default cpu total compute, set client config option cpu_total_compute to override
    
2020-12-09T16:30:51.488Z [DEBUG] client.fingerprint_mgr: fingerprint modules skipped due to allow/denylist: skipped_fingerprinters=[env_aws]

Allocated Resources
CPU         Memory       Disk
0/1000 MHz  0 B/1.8 GiB  0 B/4.3 GiB
```

File: client/fingerprint/cpu.go [hunk 1]
```diff
@@ -64,12 +72,13 @@ func (f *CPUFingerprint) Fingerprint(req *FingerprintRequest, resp *FingerprintR
...
-	// node would be unable to receive any allocations.
+	// If we cannot detect the cpu total compute, fallback to a very low default
+	// value and log a message about configuring cpu_total_compute. This happens
+	// on Graviton instances where CPU information is unavailable. In that case,
+	// the env_aws fingerprinter updates the value with correct information.
 	if tt == 0 {
-		return fmt.Errorf("cannot detect cpu total compute. "+
-			"CPU compute must be set manually using the client config option %q",
-			"cpu_total_compute")
+		f.logger.Info("fallback to default cpu total compute, set client config option cpu_total_compute to override")
```
Comment (tgross) [inline client/fingerprint/cpu.go:80]: The log line is a little unfortunate in that it's important to see in non-AWS cases but in AWS cases we're going to fix it in the fingerprinter, which logs at debug. But I don't see a good way around that other than dropping this one to debug... which I think would be a bad idea?

**Review by tgross — APPROVED** [review]
LGTM. This seems like a much nicer user experience.

File: client/fingerprint/cpu.go (hunk 1 above)
Comment (shoenig) [reply client/fingerprint/cpu.go:80]: Yeah I could be convinced to pick any of the possible combinations of Info/Debug. Realistically the most correct solution to all of this would involve plumbing to enable fingerprinters to coordinate. But for this, that would be like driving a thumbtack with sledgehammer.
