### PR TITLE
Task lifecycle restart

### LINKED ISSUE #9464: Alloc restart does not restart one-shot lifecycle tasks
### Nomad version
```
Nomad v1.0.0-beta3 (fcb32ef7ba037b2b83e7a0fd1c53c7410a2990db)
```

### Issue
The alloc restart command optimistically attempts to restart all tasks in the allocation; it collects any task-level errors and returns them:
https://github.com/hashicorp/nomad/blob/v1.0.0-beta3/client/allocrunner/alloc_runner.go#L1173-L1178

For an allocation with a dead `poststart` task, the main task will be restarted, but the `poststart` task will fail to restart with `Task not running` (because it's dead). 

There are a few changes we could make here:
* There is an argument that `poststart` tasks should be re-run when the main tasks are restarted. 
* Otherwise, I think there's an argument that `RestartAll` should not return an error; for an alloc-level restart, we should not attempt to restart dead `poststart` tasks
* Even if we keep the behavior the same, the error message could be improved to indicate *which task* failed to restart. Currently, if there are are multiple dead `poststart` tasks, each will return an error on restart, resulting in the increasingly unhelpful error message: 
```
$ nomad alloc restart bab9
Failed to restart allocation:

Unexpected response code: 500 (2 errors occurred:
	* Task not running
	* Task not running

)
```

### Reproduction steps
1. Run the job below
2. After the poststart allocation has stopped, run `nomad alloc restart <alloc-id>`
3. Note the error message

### Job file (if appropriate)
```
job "repro7875" {
  type = "service"
  datacenters = ["dc1"]
  group "repro" {
    task "main" {
      driver = "exec"
      config {
        command = "sleep"
        args = ["3600"]
      }  
    }
    task "poststart" {
      driver = "exec"
      config {
        command = "env"
      }
      lifecycle {
        hook = "poststart"
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)
If possible please post relevant logs in the issue.

Logs and other artifacts may also be sent to: nomad-oss-debug@hashicorp.com

Please link to your Github issue in the email and reference it in the subject
line:

> To: nomad-oss-debug@hashicorp.com
>
> Subject: GH-1234: Errors garbage collecting allocs

Emails sent to that address are readable by all HashiCorp employees but are *not* publicly visible.

### LINKED ISSUE #9688: poststart task completion does not impede poststop tasks
### Nomad version
1.0.1

### Issue
I was curious about whether tasks with lifecycle hook `poststop` should wait for tasks with lifecycle hook `poststart` to be dead? Is there a plan to support this "hard-gating" functionality?

### LINKED ISSUE #9841: Nomad prestart task breaks "alloc restart"
### Nomad version
Nomad v0.12.0 (8f7fbc8e7b5a4ed0d0209968faf41b238e6d5817)

### Operating system and Environment details
CentOs 7.5 VM env on Virtualbox 6.1

### Issue
Nomad alloc restart not working with `prestart` lifecycle task

Expected behaviour, alloc restart the `prestart` task and then the `main` task. 

### Reproduction steps
- Run the nomad task with the following task file
```
 nomad job status test
ID            = test
Name          = test
Submit Date   = 2021-01-18T11:47:41Z
Type          = service
Priority      = 50
Datacenters   = dc1
Namespace     = default
Status        = running
Periodic      = false
Parameterized = false

Summary
Task Group  Queued  Starting  Running  Failed  Complete  Lost
test        0       0         1        0       0         0

Latest Deployment
ID          = ff4a14b1
Status      = running
Description = Deployment is running

Deployed
Task Group  Desired  Placed  Healthy  Unhealthy  Progress Deadline
test        1        1       0        0          2021-01-18T11:57:41Z

Allocations
ID        Node ID   Task Group  Version  Desired  Status   Created  Modified
df20b14a  1d358dc0  test        0        run      running  15s ago  7s ago

```
- Run `nomad alloc restart`
```
nomad alloc restart df20b14a
Failed to restart allocation:

Unexpected response code: 500 (rpc error: 2 errors occurred:
	* Task not running
	* Task not running

)
```

### Job file (if appropriate)
```
job "test" {
  datacenters = ["dc1"]
  type = "service"

  group "test" {
    restart {
      interval = "6m"
      attempts = 10
      delay    = "10s"
      mode     = "delay"
    }

    # add prestart task
    task "test-pre" {
      driver = "docker"
      lifecycle {
        hook = "prestart"
        sidecar = false
      }

      config {
        image = "alpine:3.8"
        command = "sh"

        args = ["-c", "echo test > /alloc/test_file"]
      }
    }

    task "test" {
      driver = "docker"

      config {
        image = "alpine:3.8"
        command = "sh"

        args = ["-c", "if [ ! -s /alloc/test_file ]; then sleep 5; exit 1; else while sleep 3600; do :; done; fi"]
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by lgfa29**
Following-up on the work done in #14009, this PR implements a new restart mode that allows for all tasks of an allocation to be restarted, even those that have already run, such as non-sidecar prestart or poststop tasks.

It also solves some related issues, such as the restart command failing with `Task not running` due to dead tasks in the allocation. These errors are now ignore when restarting the allocation (restarting a dead task with `-task` will still result in this error).

Closes #9464
Closes #9688
Closes #9841

-----------

_Note to reviewers_: The internal RFC proposed a new task state (`complete`) to differentiate between a task that is really `dead` (and would never run again) from that a task that finished running, but is waiting for a restart. 

But during implementation I noticed that there are quite a few places where the `dead` state was being checked, but then I also noticed that it didn't really matter if the task was `dead` or `complete` so I was able to implement this functionally without the need for the extra state.

### CODE REVIEW

File: api/allocations.go [hunk 1]
```diff
@@ -127,6 +127,16 @@ func (a *Allocations) Restart(alloc *Allocation, taskName string, q *QueryOption
 	return err
 }
 
+func (a *Allocations) RestartAllTasks(alloc *Allocation, q *QueryOptions) error {
```
Comment (lgfa29) [inline api/allocations.go:130]: I created a new method here to avoid an `api` package breaking change in the `Restart` method above.

File: client/allocrunner/alloc_runner.go [hunk 2]
```diff
@@ -1205,19 +1227,55 @@ func (ar *allocRunner) GetTaskEventHandler(taskName string) drivermanager.EventH
...
 
-// RestartTask signalls the task runner for the  provided task to restart.
-func (ar *allocRunner) RestartTask(taskName string, taskEvent *structs.TaskEvent) error {
+// Restart satisfies the WorkloadRestarter interface and restarts all tasks
+// that are currently running. Only the TaskRestartRunningSignal event type may
+// be used.
+func (ar *allocRunner) Restart(ctx context.Context, event *structs.TaskEvent, failure bool) error {
+	if event.Type != structs.TaskRestartRunningSignal {
+		return fmt.Errorf("Invalid event %s for alloc restart request", event.Type)
+	}
```
Comment (lgfa29) [inline client/allocrunner/alloc_runner.go:1236]: I was wondering if it would be better to just overwrite `event.Type` here since I don't think it _really_ matters for callers, but I may be missing something so it would be good to hear from others.

File: client/allocrunner/alloc_runner_test.go [hunk 3]
```diff
@@ -483,6 +484,468 @@ func TestAllocRunner_Lifecycle_Poststop(t *testing.T) {
...
+				"prestart-oneshot":  structs.TaskState{State: "dead", Restarts: 0},
+				"prestart-sidecar":  structs.TaskState{State: "running", Restarts: 0},
+				"poststart-oneshot": structs.TaskState{State: "dead", Restarts: 0},
+				"poststart-sidecar": structs.TaskState{State: "running", Restarts: 0},
+				"poststop":          structs.TaskState{State: "pending", Restarts: 0},
+			},
+		},
+		{
+			name:      "restart leader main task",
+			hasLeader: true,
```
Comment (lgfa29) [inline client/allocrunner/alloc_runner_test.go:644]: These tests were pulled from #10785 where, in these leader tests, it [mentions](https://github.com/hashicorp/nomad/pull/10785/files#diff-95deb9e4e5232c48e5c186b01e002fd8689a2d38bcee018c08548401b25daa25R1674) that: 

> // TODO: currently fails because sidecars aren't restarted

I think this was to test a fix for https://github.com/hashicorp/nomad/issues/10578 which would synchronize the lifecycle of sidecar tasks with the leader, but this was not implemented here, so I adjusted the test to match the current behaviour (restarting the leader will _not_ restart sidecars). Once a fix for #10578 is done these tests will fail and will need to be adjusted.

File: client/allocrunner/alloc_runner_unix_test.go [hunk 4]
```diff
@@ -154,9 +154,10 @@ func TestAllocRunner_Restore_CompletedBatch(t *testing.T) {
 	alloc := mock.Alloc()
 	alloc.Job.Type = structs.JobTypeBatch
 	task := alloc.Job.TaskGroups[0].Tasks[0]
-	task.Driver = "mock_driver"
+	task.Driver = "raw_exec"
 	task.Config = map[string]interface{}{
-		"run_for": "2ms",
+		"command": "sleep",
+		"args":    []string{"2"},
```
Comment (lgfa29) [inline client/allocrunner/alloc_runner_unix_test.go:160]: I had to use the `raw_exec` driver instead of `mock_driver` here and in the other restore test (`TestTaskRunner_Restore_Dead`) because, for some reason, the `mock_driver` behaved differently from others.

For some reason the task handle was not `nil` when restoring a `dead` task, so the `Run` method would get stuck here, with `handleKill` never exiting: https://github.com/hashicorp/nomad/blob/4ac9de1aa619c852b31e02c809f5a4b30299a230/client/allocrunner/taskrunner/task_runner.go#L673-L674

I'm not sure if it's a problem with the `mock_driver` or my task restore changes.

File: client/allocrunner/taskrunner/sids_hook_test.go [hunk 5]
```diff
@@ -297,11 +296,7 @@ func TestTaskRunner_DeriveSIToken_UnWritableTokenFile(t *testing.T) {
 	go tr.Run()
 
 	// wait for task runner to finish running
-	select {
-	case <-tr.WaitCh():
-	case <-time.After(time.Duration(testutil.TestMultiplier()*15) * time.Second):
-		r.Fail("timed out waiting for task runner")
-	}
+	testWaitForTaskToDie(t, tr)
```
Comment (lgfa29) [inline client/allocrunner/taskrunner/sids_hook_test.go:299]: Changes like this had to be done because the task runner `Run()` method doesn't return anymore, it gets blocked waiting for a possible restart, so `WaitCh` is not closed until the task reaches a point where it will not restart anymore.

File: client/allocrunner/taskrunner/task_runner.go [hunk 6]
```diff
@@ -505,12 +514,14 @@ func (tr *TaskRunner) Run() {
 	var result *drivers.ExitResult
 
 	tr.stateLock.RLock()
-	dead := tr.state.State == structs.TaskStateDead
+	restoredDead := tr.state.State == structs.TaskStateDead
```
Comment (lgfa29) [inline client/allocrunner/taskrunner/task_runner.go:517]: As I mentioned in https://github.com/hashicorp/nomad/pull/14127#discussion_r948582301, I'm not sure if the restore logic is 100% correct. It would be good to investigate this more.

File: client/allocrunner/taskrunner/task_runner.go [hunk 7]
```diff
@@ -505,12 +514,14 @@ func (tr *TaskRunner) Run() {
...
 	tr.stateLock.RUnlock()
 
-	// if restoring a dead task, ensure that task is cleared and all post hooks
-	// are called without additional state updates
-	if dead {
+	// If restoring a dead task, ensure that task is cleared and all post hooks
+	// are called without additional state updates.
+	// If the alloc is not terminal we must proceed until the ALLOC_RESTART
+	// loop to allow the task to run again in case the alloc is restarted.
+	if restoredDead && tr.Alloc().TerminalStatus() {
```
Comment (tgross) [inline client/allocrunner/taskrunner/task_runner.go:524]: This includes both the server intent and the current client state, which means we're relying on one of them to get the updated allocation. I think if we hit this for a task before the client status is updated we'll end up falling past the driver handle cleanup, which might explain the results you're seeing with the mock driver.

File: client/allocrunner/taskrunner/task_runner.go (hunk 6 above)
Comment (tgross) [reply client/allocrunner/taskrunner/task_runner.go:517]: Commented a bit further down on the `restoredDead` check.

Also, I'm not sure I understand the changed name. Calling it `restoredDead` reads to me like it's been restored in the past from the dead state. But I think the code change means "it's _currently_ dead but eligible to be restored"? `deadAndCanBeRestored` is kind of wordy but maybe there's something better that's not coming to mind?

File: client/allocrunner/alloc_runner.go (hunk 2 above)
Comment (tgross) [reply client/allocrunner/alloc_runner.go:1236]: Normally we'd probably validate this at the RPC handler but in this case the same handler gets used for all three methods. That being said, we switch on the method based on `Event.Type`, right? So if it's wrong down here in the alloc runner that's a programmer's error where I'd expect it's fine to assert the right value via overwriting `event.Type`.

**Review by tgross — CHANGES_REQUESTED** [review]
This is looking really good @lgfa29! I think it's probably worth hunting down that `rawexec` vs `mock` behavior before merging though.

File: api/allocations.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (lgfa29) [reply api/allocations.go:130]: Good point, I will add it to both methods 👍

File: command/alloc_restart.go [hunk 8]
```diff
@@ -31,9 +34,14 @@ General Options:
 
 Restart Specific Options:
 
+  -all-tasks
+    If set, all tasks in the allocation will be restarted, even the ones that
+    already ran. This option cannot be used if a task is defined.
```
[the remark this answers is not in the document]
Comment (lgfa29) [reply command/alloc_restart.go:39]: I avoided `-task` here because the task name can also be passed as an argument (`nomad alloc restart 1234 web`) but I can mention both.

File: .changelog/14127.txt [hunk 9]
```diff
@@ -0,0 +1,7 @@
+```release-note:improvement
+client: add option to restart all tasks of an allocation, even if the task already run, such as non-sidecar prestart and poststart tasks.
```
Comment (shoenig) [inline .changelog/14127.txt:2]:
```suggestion
client: add option to restart all tasks of an allocation, regardless of lifecycle type or state.
```

i dunno, seems shorter

File: .changelog/14127.txt [hunk 10]
```diff
@@ -0,0 +1,7 @@
...
+```
+
+```release-note:improvement
+client: only start poststop tasks after poststart tasks are done.
+```
```
Comment (shoenig) [inline .changelog/14127.txt:7]: bug or feature?

File: api/allocations.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (shoenig) [reply api/allocations.go:130]: :headstone: godoc.org

File: client/alloc_endpoint_test.go [hunk 11]
```diff
@@ -68,6 +68,45 @@ func TestAllocations_Restart(t *testing.T) {
...
+		var resp2 nstructs.GenericResponse
+		err := client.ClientRPC("Allocations.Restart", &req, &resp2)
+		if err != nil && strings.Contains(err.Error(), "not running") {
+			return false, err
+		}
+
+		return true, nil
+	}, func(err error) {
+		t.Fatalf("err: %v", err)
+	})
```
Comment (shoenig) [inline client/alloc_endpoint_test.go:107]: looks like this is copied form elsewhere, can it be extracted into a helper function?

File: client/allocrunner/alloc_runner.go [hunk 12]
```diff
@@ -547,40 +546,63 @@ func (ar *allocRunner) handleTaskStateUpdates() {
...
-			switch killEvent.Type {
-			case structs.TaskLeaderDead:
-				ar.logger.Debug("leader task dead, destroying all tasks", "leader_task", killTask)
-			case structs.TaskMainDead:
-				ar.logger.Debug("main tasks dead, destroying all sidecar tasks")
-			default:
-				ar.logger.Debug("task failure, destroying all tasks", "failed_task", killTask)
+		if len(liveRunners) > 0 {
+			// if all live runners are sidecars - kill alloc
+			if killEvent == nil && hasSidecars && !hasNonSidecarTasks(liveRunners) {
```
Comment (shoenig) [inline client/allocrunner/alloc_runner.go:551]: could the double negative here be wrapped in a `hasLiveSidecars(...)` helper?

File: client/allocrunner/alloc_runner.go [hunk 13]
```diff
@@ -547,40 +546,63 @@ func (ar *allocRunner) handleTaskStateUpdates() {
...
+				}
 
-			// Kill 'em all
-			states = ar.killTasks()
+				// Emit kill event for live runners
+				for _, tr := range liveRunners {
+					tr.EmitEvent(killEvent)
+				}
+
+				// Kill 'em all
```
Comment (shoenig) [inline client/allocrunner/alloc_runner.go:573]: :scream:

File: client/allocrunner/alloc_runner.go [hunk 14]
```diff
@@ -547,40 +546,63 @@ func (ar *allocRunner) handleTaskStateUpdates() {
...
+				states = ar.killTasks()
+
+				// Wait for TaskRunners to exit before continuing to
+				// prevent looping before TaskRunners have transitioned
+				// to Dead.
```
Comment (shoenig) [inline client/allocrunner/alloc_runner.go:578]:
```suggestion
				// Wait for TaskRunners to exit before continuing. This will
				// prevent looping before TaskRunners have transitioned
				// to Dead.
```

File: client/allocrunner/alloc_runner.go [hunk 15]
```diff
@@ -547,40 +546,63 @@ func (ar *allocRunner) handleTaskStateUpdates() {
...
+				for _, tr := range liveRunners {
+					ar.logger.Info("killing task", "task", tr.Task().Name)
```
Comment (shoenig) [inline client/allocrunner/alloc_runner.go:580]: more clear if we say like "waiting for task to exit ..."

File: client/allocrunner/alloc_runner_test.go [hunk 16]
```diff
@@ -1213,7 +1676,11 @@ func TestAllocRunner_MoveAllocDir(t *testing.T) {
 	ar.Run()
 	defer destroy(ar)
 
-	require.Equal(t, structs.AllocClientStatusComplete, ar.AllocState().ClientStatus)
+	testutil.WaitForResult(func() (bool, error) {
+		return ar.AllocState().ClientStatus == structs.AllocClientStatusComplete, nil
+	}, func(_ error) {
+		t.Fatalf("expected alloc to be complete")
+	})
```
Comment (shoenig) [inline client/allocrunner/alloc_runner_test.go:1683]: copied below; make a helper?

File: client/allocrunner/alloc_runner_unix_test.go (hunk 4 above)
Comment (shoenig) [reply client/allocrunner/alloc_runner_unix_test.go:160]: Probably worth getting to the bottom of this; just debug logging the plugin interface entrypoints and the parameters being passed in should shed light on what's happening

Comment (lgfa29) [reply client/allocrunner/alloc_runner_unix_test.go]: Yup, thanks for the push back, my implementation was wrong 😅

File: client/allocrunner/taskrunner/task_runner.go (hunk 6 above)
Comment (lgfa29) [reply client/allocrunner/taskrunner/task_runner.go]: Yeah, good point. What got me confused initially was that this variable was never updated, so it was only `true` when restoring a dead task. 

Since my initial implementation was incorrect there's now another value that needs to be checked here, so I reverted this one to `dead`.

File: client/allocrunner/taskrunner/task_runner.go (hunk 7 above)
Comment (lgfa29) [reply client/allocrunner/taskrunner/task_runner.go]: Nice find. I'm not 100% if this was the problem with the tests, but it made me realize that important information here is actually whether the `Run()` method exited or not. Using the local client state fixed the problems with the `mock` driver 🎉

File: .changelog/14127.txt (hunk 9 above)
Comment (lgfa29) [reply .changelog/14127.txt:2]: Thanks!

File: .changelog/14127.txt (hunk 10 above)
Comment (lgfa29) [reply .changelog/14127.txt:7]: We never specified the expected behaviour here, so it's not like it was doing something wrong. The code change will now always follow this order, so I think it' an `improvement`.

File: client/alloc_endpoint_test.go (hunk 11 above)
Comment (lgfa29) [reply client/alloc_endpoint_test.go:107]: Ah yeah, it came from [here](https://github.com/hashicorp/nomad/blob/main/client/alloc_endpoint_test.go#L58-L68). But I'm not sure if it's generic enough to be extracted as a helper? The two tests happen to call the `Allocations.Restart` RPC, but interpretation of the result may change if the code changes.

File: client/allocrunner/alloc_runner.go (hunk 12 above)
Comment (lgfa29) [reply client/allocrunner/alloc_runner.go:551]: Hum...I don't think it can be extracted into a method because the live or not condition is determined by the method input: here it's passing a map of live runners, so the result will be live runners that are not sidecars.

I could move it to a intermediate variable is more descriptive: 

```go
hasLiveSidecars := hasSidecars && !hasNonSidecarTasks(liveRunners)
if killEvent == nil && hasLiveSidecars {
	killEvent = structs.NewTaskEvent(structs.TaskMainDead)
}
```

Does this look better?

**Comment by lgfa29** [comment]
@tgross @shoenig I think https://github.com/hashicorp/nomad/pull/14127/commits/e66625876fbc9c1dfc3f550d889f165e270bbb2b fixed the problems with task restore and I was able to use the `mock` driver in the tests.

https://github.com/hashicorp/nomad/pull/14127/commits/8b813fdae2b88d19035312903d1c957e2d73147f address the rest of the code review changes.

File: client/allocrunner/taskrunner/task_runner_test.go [hunk 17]
```diff
@@ -349,6 +349,87 @@ func TestTaskRunner_Restore_Running(t *testing.T) {
 	assert.Equal(t, 1, started)
 }
 
+// TestTaskRunner_Restore_Dead asserts that restoring a dead task will place it
+// back in the correct state. If the task was waiting for an alloc restart it
+// must be able to be restarted after restore, otherwise a restart must fail.
```
Comment (tgross) [inline client/allocrunner/taskrunner/task_runner_test.go:354]: Great test!

**Review by tgross — APPROVED** [review]
LGTM!

**Review by DerekStrickland — APPROVED** [review]
Amazing work! Left some questions/suggestions, but not blocking.

File: client/allocrunner/alloc_runner.go [hunk 18]
```diff
@@ -1205,19 +1228,61 @@ func (ar *allocRunner) GetTaskEventHandler(taskName string) drivermanager.EventH
...
 
-// RestartTask signalls the task runner for the  provided task to restart.
-func (ar *allocRunner) RestartTask(taskName string, taskEvent *structs.TaskEvent) error {
+// Restart satisfies the WorkloadRestarter interface and restarts all tasks
+// that are currently running.
+//
+// The event type will be set to TaskRestartRunningSignal to comply with
+// internal restart logic requirements.
+func (ar *allocRunner) Restart(ctx context.Context, event *structs.TaskEvent, failure bool) error {
+	if event.Type != structs.TaskRestartRunningSignal {
```
[the remark this answers is not in the document]
Comment (lgfa29) [reply client/allocrunner/alloc_runner.go:1237]: Hum..not sure if I understood, do you mean something like this?

```go
func (ar *allocRunner) Restart(ctx context.Context, event *structs.TaskEvent, failure bool) error {
	ev := event.Copy()
	ev.Type = structs.TaskRestartRunningSignal
	return ar.restartTasks(ctx, ev, failure)
}
```

[the remark this answers is not in the document]
Comment (tgross) [reply client/allocrunner/alloc_runner.go:1237]: I thought the original reason we were overwriting was a form of assertion? If it's not the right task restart signal, it's a bug?

File: client/allocrunner/taskrunner/lifecycle.go [hunk 19]
```diff
@@ -9,25 +9,63 @@ import (
...
+	switch taskState.State {
+	case structs.TaskStatePending:
+		// Tasks that are "pending" are never allowed to restart.
+		return ErrTaskNotRunning
+	case structs.TaskStateDead:
+		// Tasks that are "dead" are only allowed to restart when restarting
+		// all tasks in the alloc, otherwise the taskCoordinator will prevent
+		// it from running again, and if their Run method is still running.
+		if event.Type != structs.TaskRestartAllSignal || localState.RunComplete {
+			return ErrTaskNotRunning
```
[the remark this answers is not in the document]
Comment (lgfa29) [reply client/allocrunner/taskrunner/lifecycle.go:37]: Hum...I think the error is the same, that task tried to restart but it wasn't running

File: client/allocrunner/taskrunner/task_runner.go [hunk 20]
```diff
@@ -674,6 +685,38 @@ MAIN:
...
+			case <-tr.killCtx.Done():
+				break ALLOC_RESTART
+			case <-tr.shutdownCtx.Done():
+				return
+			case <-tr.restartCh:
+				// Restart without delay since the task is not running anymore.
+				restart, _ := tr.shouldRestart()
+				if restart {
+					// Set runner as not dead to allow the MAIN loop to run.
+					dead = false
```
[the remark this answers is not in the document]
Comment (lgfa29) [reply client/allocrunner/taskrunner/task_runner.go:705]: Nope, `dead` is a local variable, so not shared with anything else. It's initialized from state, and that _is_ protected with lock.

File: client/allocrunner/alloc_runner.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (lgfa29) [reply client/allocrunner/alloc_runner.go:1237]: Yeah, my understanding is that, for the caller of the `allocRunner.Restart*` functions, the event type doesn't matter, so overwriting it was a way to "correct" the call if, for some reason, it was done using the wrong type.

There is no valid scenario where you would call, for example, `RestartRunning` with anything other than the `TaskRestartRunningSignal` event type, so instead of returning an error we correct the call.

The `Restart` method specifically is an interesting one. It is used to implement the `WorkloadRestarter` interface (defined [here](https://github.com/hashicorp/nomad/blob/v1.3.3/command/agent/consul/check_watcher.go#L24-L27) and [here](https://github.com/hashicorp/nomad/blob/v1.3.3/client/serviceregistration/service_registration.go#L48-L52)) so, in theory, it could be used to perform different types of restart, but I chose to keep it as-is (restart only tasks that are currently running).

[the remark this answers is not in the document]
Comment (DerekStrickland) [reply client/allocrunner/alloc_runner.go:1237]: That's almost what I meant. I was suggesting we make the copy and emit both events. I was thinking that with this implementation you lose the info on which code path triggered the restart.

File: client/allocrunner/taskrunner/task_runner.go (hunk 20 above)
[the remark this answers is not in the document]
Comment (DerekStrickland) [reply client/allocrunner/taskrunner/task_runner.go:705]: Perfect. That was my concern.

File: client/allocrunner/alloc_runner.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (lgfa29) [reply client/allocrunner/alloc_runner.go:1237]: A few things to note here:

- task events are used to surface information to users, they are not something like code tracing.
- event types have a fairly restrict [set of possible values](https://github.com/hashicorp/nomad/blob/v1.3.3/nomad/structs/structs.go#L8005-L8098), so they are not the best to help trace code path.
- events have other, more meaningful fields, like `DisplayMessage`, `Details`, `ReastartReason` etc. and those will be kept from the input.
- task events are stored in state, and we only keep the last 10, so emitting (almost) duplicate events will take up a slot and provide little value to users.

That being said, my implementation does abuse the task event mechanism a bit. I tried to think of an alternative, but couldn't think of one yet. I will take another look to see if I can think of something else.

[the remark this answers is not in the document]
Comment (lgfa29) [reply client/allocrunner/alloc_runner.go]: https://github.com/hashicorp/nomad/pull/14127/commits/e620cd187452b45ab04bf65d56aa2f90fabfc9eb removes all of this task event nonsense 😅 

I also got ride of the new task event types to avoid any confusion on the developer side as to which type to use. I think it's easy enough for users to distinguish between them given their [event description](https://github.com/hashicorp/nomad/blob/e620cd187452b45ab04bf65d56aa2f90fabfc9eb/client/client.go#L939-L953):
image
