### PR TITLE
gracefully recover tasks that use csi node plugins

### LINKED ISSUE #13028: Allocations with CSI volume fail during Nomad agent restart
### Nomad version

```Nomad v1.3.0 (52e95d64113e01be05d585d8b4c07f6f19efebbc)```

### Operating system and Environment details

Debian 10 Buster

### Issue

* Allocations using CSI volume will fail on client after Nomad agent restart
* while the CSI node and controller jobs stayed running and were unaffected by restart

### Reproduction steps

* Run CSI node/controller jobs as system job (on all nodes)
* Run Nomad job using CSI volume
* Restart nomad agent on client where Job with CSI volume runs by running:
  * `systemctl restart nomad`

#### Expected Result

* Allocation with CSI volume to stay running

#### Actual Result

* Allocation fails and is rescheduled

### Unit file

```
$ cat /lib/systemd/system/nomad.service
[Unit]
Description=Nomad
Documentation=https://nomadproject.io/docs/
Wants=network-online.target
After=network-online.target
ConditionPathExists=/etc/nomad.d

# When using Nomad with Consul it is not necessary to start Consul first. These
# lines start Consul before Nomad as an optimization to avoid Nomad logging
# that Consul is unavailable at startup.
Wants=consul.service
After=consul.service

[Service]
ExecReload=/bin/kill -HUP $MAINPID
ExecStart=/usr/local/bin/nomad agent -config /etc/nomad.d
KillMode=process
KillSignal=SIGINT
LimitNOFILE=infinity
LimitNPROC=infinity
Restart=on-failure
RestartSec=2
StartLimitBurst=3
StartLimitIntervalSec=10
TasksMax=infinity

[Install]
WantedBy=multi-user.target
```

### Job file (if appropriate)

CSI plugin:
```
$ cat cinder_csi.hcl 
job "cinder_csi" {
  datacenters = ["dc1"]
  type = "system"

  update {
    max_parallel = 1
    min_healthy_time = "10s"
  }

  group "node" {

    vault {
      policies = ["nomad_jobs_policy"]
    }

    task "node" {
      driver = "docker"

      config {
        image = "docker.io/k8scloudprovider/cinder-csi-plugin:v1.23.0"
        dns_servers = ["172.17.0.1"]
        privileged = true

        devices = [
          {
            host_path      = "/dev"
            container_path = "/dev"
          },
        ]

        args = [
          "/bin/cinder-csi-plugin",
          "--endpoint=unix:///csi/csi.sock",
          "--cloud-config=/local/cloud.conf",
          "--nodeid=$${node.unique.name}",
          "--cluster=$${NOMAD_DC}",
          "-v=4",
        ]
      }

      template {
        destination = "local/cloud.conf"
        change_mode = "restart"
        data = <<EOF
{{ with secret "secret/nomad_csi/xxx/xxxxx" -}}
[Global]
application-credential-name = xxx
application-credential-id = {{ .Data.id }}
application-credential-secret = {{ .Data.secret }}
auth-url = https://xxxx.xxxxx.xxxx/v3
region = xxxx
{{- end }}

[BlockStorage]
rescan-on-resize = true
ignore-volume-az = true
EOF
      }

      csi_plugin {
        id        = "cinder_csi_plugin"
        type      = "node"
        mount_dir = "/csi"
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }

  group "controller" {

    vault {
      policies = ["nomad_jobs_policy"]
    }

    task "controller" {
      driver = "docker"

      config {
        image = "docker.io/k8scloudprovider/cinder-csi-plugin:v1.23.0"
        dns_servers = ["172.17.0.1"]
        privileged = true

        args = [
          "/bin/cinder-csi-plugin",
          "--endpoint=unix:///csi/csi.sock",
          "--cloud-config=/local/cloud.conf",
          "--nodeid=$${node.unique.name}",
          "--cluster=$${NOMAD_DC}",
          "-v=4",
        ]
      }

      template {
        destination = "local/cloud.conf"
        change_mode = "restart"
        data = <<EOF
{{ with secret "secret/nomad_csi/xxxx/xxxxx" -}}
[Global]
application-credential-name = xxx
application-credential-id = {{ .Data.id }}
application-credential-secret = {{ .Data.secret }}
auth-url = https://xxxx.xxxxx.xxxxx/v3
region = xxxx
{{- end }}

[BlockStorage]
rescan-on-resize = true
ignore-volume-az = true
EOF
      }

      csi_plugin {
        id        = "cinder_csi_plugin"
        type      = "controller"
        mount_dir = "/csi"
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

CSI volume using job:
```
$ cat csitest.hcl 
job "csitest" {
  datacenters = ["dc1"]

  update {
    max_parallel = 1
    min_healthy_time = "10s"
    stagger = "30s"
  }

  group "csitest" {
    count = 3

    volume "csitest" {
      type = "csi"
      source = "csitest"
      attachment_mode = "file-system"
      access_mode = "single-node-writer"
      per_alloc = true
    }

    task "csitest" {
      driver = "docker"

      config {
        image = "python:3.7-alpine"
        entrypoint = ["sleep", "infinity"]
        dns_servers = ["172.17.0.1"]
      }

      volume_mount {
        volume = "csitest"
        destination = "/vol"
      }

      resources {
        memory = 128
      }
    }
  }
}
```

### Nomad Client logs (if appropriate)

```
Stopping Nomad...
==> Caught signal: interrupt
    2022-05-16T11:42:51.166Z [INFO]  agent: requesting shutdown
    2022-05-16T11:42:51.166Z [INFO]  client: shutting down
    2022-05-16T11:42:51.509Z [INFO]  client.plugin: shutting down plugin manager: plugin-type=device
    2022-05-16T11:42:51.509Z [INFO]  client.plugin: plugin manager finished: plugin-type=device
    2022-05-16T11:42:51.509Z [INFO]  client.plugin: shutting down plugin manager: plugin-type=driver
    2022-05-16T11:42:51.554Z [INFO]  client.plugin: plugin manager finished: plugin-type=driver
    2022-05-16T11:42:51.554Z [INFO]  client.plugin: shutting down plugin manager: plugin-type=csi
    2022-05-16T11:42:51.554Z [INFO]  client.plugin: plugin manager finished: plugin-type=csi
    2022-05-16T11:42:51.636Z [INFO]  agent: shutdown complete
nomad.service: Main process exited, code=exited, status=1/FAILURE
nomad.service: Failed with result 'exit-code'.
Stopped Nomad.
nomad.service: Found left-over process 15733 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 15743 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 15755 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 15766 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 15788 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 15907 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 16150 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 16274 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 16420 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 16437 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 16746 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 16892 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 18358 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 18424 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19500 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19509 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19544 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19555 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19566 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19576 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19586 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19592 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19963 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 19991 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 20040 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 20157 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 20422 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 20617 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 21007 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 21096 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 21469 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 21673 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 22190 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 24329 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 25803 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
nomad.service: Found left-over process 25893 (nomad) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Started Nomad.
==> Loaded configuration from /etc/nomad.d/nomadclient.hcl, /etc/nomad.d/plugins.hcl
==> Starting Nomad agent...
2022-05-16T11:42:53.368Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.372Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.375Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.383Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.385Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.393Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.398Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.402Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.409Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.411Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.433Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.440Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.442Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.448Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.456Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.476Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.481Z [TRACE] plugin.stdio: waiting for stdio data
2022-05-16T11:42:53.489Z [TRACE] plugin.stdio: waiting for stdio data
==> Nomad agent configuration:
       Advertise Addrs: HTTP: 10.177.83.139:4646
            Bind Addrs: HTTP: [0.0.0.0:4646]
                Client: true
             Log Level: INFO
                Region: global (DC: dc1)
                Server: false
               Version: 1.3.0
==> Nomad agent started! Log data will stream in below:
    2022-05-16T11:42:51.717Z [WARN]  agent.plugin_loader: skipping external plugins since plugin_dir doesn't exist: plugin_dir=/var/lib/nomad/plugins
    2022-05-16T11:42:51.720Z [INFO]  agent: detected plugin: name=docker type=driver plugin_version=0.1.0
    2022-05-16T11:42:51.720Z [INFO]  agent: detected plugin: name=raw_exec type=driver plugin_version=0.1.0
    2022-05-16T11:42:51.720Z [INFO]  agent: detected plugin: name=exec type=driver plugin_version=0.1.0
    2022-05-16T11:42:51.720Z [INFO]  agent: detected plugin: name=qemu type=driver plugin_version=0.1.0
    2022-05-16T11:42:51.720Z [INFO]  agent: detected plugin: name=java type=driver plugin_version=0.1.0
    2022-05-16T11:42:51.720Z [INFO]  client: using state directory: state_dir=/var/lib/nomad/client
    2022-05-16T11:42:51.720Z [INFO]  client: using alloc directory: alloc_dir=/var/lib/nomad/alloc
    2022-05-16T11:42:51.720Z [INFO]  client: using dynamic ports: min=20000 max=32000 reserved=""
    2022-05-16T11:42:51.722Z [INFO]  client.cpuset.v1: initialized cpuset cgroup manager: parent=/nomad cpuset=0-15
    2022-05-16T11:42:51.759Z [INFO]  client.fingerprint_mgr.cgroup: cgroups are available
    2022-05-16T11:42:51.764Z [INFO]  client.fingerprint_mgr.consul: consul agent is available
    2022-05-16T11:42:51.803Z [WARN]  client.fingerprint_mgr.network: unable to parse speed: path=/usr/sbin/ethtool device=ens3
    2022-05-16T11:42:51.805Z [WARN]  client.fingerprint_mgr.network: unable to parse speed: path=/usr/sbin/ethtool device=lo
    2022-05-16T11:42:51.809Z [WARN]  client.fingerprint_mgr.network: unable to parse speed: path=/usr/sbin/ethtool device=ens3
    2022-05-16T11:42:51.816Z [WARN]  client.fingerprint_mgr.network: unable to parse speed: path=/usr/sbin/ethtool device=docker0
    2022-05-16T11:42:51.870Z [INFO]  client.fingerprint_mgr.vault: Vault is available
    2022-05-16T11:42:52.932Z [WARN]  client.fingerprint_mgr.env_aws: failed to find the cpu specification for this instance type
    2022-05-16T11:42:53.324Z [INFO]  client.plugin: starting plugin manager: plugin-type=csi
    2022-05-16T11:42:53.324Z [INFO]  client.plugin: starting plugin manager: plugin-type=driver
    2022-05-16T11:42:53.324Z [INFO]  client.plugin: starting plugin manager: plugin-type=device
    2022-05-16T11:42:53.331Z [INFO]  client.consul: discovered following servers: servers=[10.177.83.242:4647, 10.177.83.206:4647, 10.177.83.251:4647]
    2022-05-16T11:42:53.386Z [INFO]  client: node registration complete
    2022-05-16T11:42:53.489Z [INFO]  client: started client: node_id=12aa7338-c26e-7b38-f8e3-e05ce43b938a
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=351c27f9-1176-32f0-5984-a06c78083cd6
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=ed76561f-4a4d-3737-198a-2b05a8b7bd14
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=f7e22142-0f79-22ad-f470-9938ee95f2be
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=a6d27ae4-d78c-0eb6-a7ad-4ffb0d4000b3
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=cdbbbca0-4f38-aab9-cba7-aa04fe387deb
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=59077433-a255-cee6-e86f-8cc0ca64fff5
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=55a22db0-043e-1622-6900-efd95a6ebc34
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=b11dca3a-6003-d374-903c-aa1a679bb55b
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=5d808708-3b3f-7d75-8f84-2878bfe9866b
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=5dafa7ce-03b3-2c48-1b29-7dc08074e94b
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=7368b43d-5ab5-fcf7-9877-5b81a37492c6
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=a83c3fe7-31ae-3726-6267-db85c2e70a43
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=7216f331-038e-6f5c-8286-1413deeba57d
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=b77c8b9a-49e6-c611-ea8a-328dafef050a
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=45bdd92b-23f5-3c09-cd1f-f8f6926b1351
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=7ed89a3e-5dae-25af-3519-d370bcbfaa41
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=2d07c54d-cb0b-8dc7-ad41-e8c9cb067e34
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=9618e1b8-6ac2-0261-e223-54b906dac72b
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=10455e8f-a5dc-a693-cea4-ba2ace05e15e
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=c49754aa-d7ed-4f0b-6b8e-b988ccba087a
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=5d6a6be3-21cb-1857-4f3d-49bb9b19e717
    2022-05-16T11:42:53.490Z [INFO]  client.gc: marking allocation for GC: alloc_id=8e6b028c-3d02-f644-ec54-c255b98fca4b
    2022-05-16T11:42:53.489Z [INFO]  client.gc: marking allocation for GC: alloc_id=0e01cb08-eeb2-fc0e-bf39-adeed5555d5d
    2022-05-16T11:42:53.508Z [ERROR] client.rpc: error performing RPC to server: error="rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client" rpc=CSIVolume.Claim server=10.177.83.251:4647
    2022-05-16T11:42:53.508Z [ERROR] client.rpc: error performing RPC to server which is not safe to automatically retry: error="rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client" rpc=CSIVolume.Claim server=10.177.83.251:4647
    2022-05-16T11:42:53.508Z [ERROR] client.alloc_runner: prerun failed: alloc_id=e753aac0-42ab-2b33-504d-b1734e79aad8 error="pre-run hook \"csi_hook\" failed: claim volumes: could not claim volume elastic_test_data_az-1[0]: rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client"
    2022-05-16T11:42:53.515Z [ERROR] client.rpc: error performing RPC to server: error="rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client" rpc=CSIVolume.Claim server=10.177.83.251:4647
    2022-05-16T11:42:53.515Z [ERROR] client.rpc: error performing RPC to server which is not safe to automatically retry: error="rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client" rpc=CSIVolume.Claim server=10.177.83.251:4647
    2022-05-16T11:42:53.515Z [ERROR] client.alloc_runner: prerun failed: alloc_id=94ce152e-a06d-530d-6bb7-8c89b1d5b4df error="pre-run hook \"csi_hook\" failed: claim volumes: could not claim volume csitest[1]: rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client"
    2022-05-16T11:42:53.515Z [ERROR] client.rpc: error performing RPC to server: error="rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client" rpc=CSIVolume.Claim server=10.177.83.251:4647
    2022-05-16T11:42:53.515Z [ERROR] client.rpc: error performing RPC to server which is not safe to automatically retry: error="rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client" rpc=CSIVolume.Claim server=10.177.83.251:4647
    2022-05-16T11:42:53.515Z [ERROR] client.alloc_runner: prerun failed: alloc_id=0dcf7f65-d665-a574-fdd1-54462182cba2 error="pre-run hook \"csi_hook\" failed: claim volumes: could not claim volume csitest[0]: rpc error: controller publish: failed to find storage provider info for client \"12aa7338-c26e-7b38-f8e3-e05ce43b938a\", node plugin \"cinder_csi_plugin\" is not running or has not fingerprinted on this client"
    2022-05-16T11:42:53.549Z [INFO]  agent: (runner) creating new runner (dry: false, once: false)
    2022-05-16T11:42:53.550Z [INFO]  agent: (runner) creating watcher
    2022-05-16T11:42:53.550Z [INFO]  agent: (runner) starting
    2022-05-16T11:42:53.563Z [INFO]  client.gc: marking allocation for GC: alloc_id=94ce152e-a06d-530d-6bb7-8c89b1d5b4df
    2022-05-16T11:42:53.568Z [INFO]  client.gc: marking allocation for GC: alloc_id=0dcf7f65-d665-a574-fdd1-54462182cba2
    2022-05-16T11:42:53.579Z [INFO]  client.gc: marking allocation for GC: alloc_id=e753aac0-42ab-2b33-504d-b1734e79aad8
    2022-05-16T11:42:53.588Z [INFO]  agent: (runner) creating new runner (dry: false, once: false)
```

### PR DESCRIPTION
**Pull request by gulducat**
With happy running tasks that use a CSI volume, on client restart they may fail to be recovered and instead be killed and rescheduled, even though there is a healthy happy CSI plugin running right next to them.

The simplest version of the error condition I could replicate was using this repo's `demo/csi/hostpath` example.  With the tasks all set up, I stop the client and start it again:

```
2023-04-05T22:10:33.940Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=0480ac51-dd38-49ec-8831-48fd3c674279 task=redis type=Received msg="Task received by client" failed=false
2023-04-05T22:10:33.948Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=d013ee08-10fc-ff0e-ef5e-cc444048fbfd task=plugin type=Received msg="Task received by client" failed=false
2023-04-05T22:10:33.959Z [ERROR] client.alloc_runner: prerun failed: alloc_id=0480ac51-dd38-49ec-8831-48fd3c674279 error="pre-run hook \"csi_hook\" failed: plugin hostpath-plugin0 for type csi-node not found"
2023-04-05T22:10:33.964Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=0480ac51-dd38-49ec-8831-48fd3c674279 task=redis type="Setup Failure" msg="failed to setup alloc: pre-run hook \"csi_hook\" failed: plugin hostpath-plugin0 for type csi-node not found" failed=true
2023-04-05T22:10:33.974Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=d013ee08-10fc-ff0e-ef5e-cc444048fbfd task=plugin type="Plugin became healthy" msg="plugin: hostpath-plugin0" failed=false
2023-04-05T22:10:36.973Z [INFO]  client.gc: marking allocation for GC: alloc_id=0480ac51-dd38-49ec-8831-48fd3c674279
```

The client doesn't know yet that the CSI plugin task is healthy, because it happens to try to recover the task that needs it first.

After this change, which retries for some time (one minute (is that ok?)) to find the plugin that it expects to exist:

```
2023-04-05T22:18:03.805Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=3f38e8b5-106b-87c7-9df4-b5815fa955d5 task=redis type=Received msg="Task received by client" failed=false
2023-04-05T22:18:03.819Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=d6f262f3-b20d-89d2-1bdd-6f92a01c2003 task=plugin type=Received msg="Task received by client" failed=false
2023-04-05T22:18:04.116Z [INFO]  client.alloc_runner.task_runner: Task event: alloc_id=d6f262f3-b20d-89d2-1bdd-6f92a01c2003 task=plugin type="Plugin became healthy" msg="plugin: hostpath-plugin0" failed=false
2023-04-05T22:18:04.262Z [INFO]  client.alloc_runner.runner_hook.csi_hook: found CSI plugin: alloc_id=3f38e8b5-106b-87c7-9df4-b5815fa955d5 type=csi-node name=hostpath-plugin0
```

We may wish to test with a more complex CSI setup to make sure that this fully Fixes #13028

### CODE REVIEW

File: client/dynamicplugins/registry.go [hunk 1]
```diff
@@ -301,6 +303,46 @@ func (d *dynamicRegistry) ListPlugins(ptype string) []*PluginInfo {
...
+	// these numbers are almost arbitrary...
+	delay := 200     // milliseconds between checks, will backoff
+	maxDelay := 5000 // up to 5 seconds between each check
+
+	// put a long upper bound on total time,
+	// just in case callers don't follow directions.
+	ctx, cancel := context.WithTimeout(ctx, 24*time.Hour)
+	defer cancel()
+
+	timer := time.NewTimer(time.Duration(delay) * time.Millisecond)
```
Comment (tgross) [inline client/dynamicplugins/registry.go:320]: There's a `NewSafeTimer` function in `helper/funcs.go` that returns a timer and a stop function that you can defer. That makes it more obvious when we're accidentally leaking the timer's resources by not calling `timer.Stop`.

The other thing that's nice about `NewSafeTimer` is that we can start with a "zero" delay (1ms internally), so that we're not delaying by 200ms for no reason if the plugin is already started (as will be the common case whenever a new allocation is placed).

_That_ being said, because "plugin is already up" is the most typical path, we could probably check `ListPlugins` once before even setting up the context and timer and avoid spinning up the extra goroutine at all!

File: client/pluginmanager/csimanager/manager.go [hunk 2]
```diff
@@ -39,7 +39,7 @@ func New(config *Config) Manager {
 	}
 
 	return &csiManager{
-		logger:    config.Logger,
+		logger:    config.Logger.Named("csiManager"),
```
Comment (tgross) [inline client/pluginmanager/csimanager/manager.go:42]: For some reason we usually snake-case the logger names (probably because it's closer to the file names in a lot of places? I dunno).

```suggestion
		logger:    config.Logger.Named("csi_manager"),
```

File: client/pluginmanager/csimanager/manager.go [hunk 3]
```diff
@@ -75,6 +75,19 @@ func (c *csiManager) PluginManager() pluginmanager.PluginManager {
...
+// WaitForPlugin waits for a specific plugin to be registered and available,
+// unless the context is canceled, or it takes longer than a minute.
+func (c *csiManager) WaitForPlugin(ctx context.Context, pType, pID string) error {
+	ctx, cancel := context.WithTimeout(ctx, time.Minute)
+	defer cancel()
+	p, err := c.registry.WaitForPlugin(ctx, pType, pID)
+	if err != nil {
+		return fmt.Errorf("%s plugin '%s' did not become ready: %w", pType, pID, err)
+	}
+	c.ensureInstance(p)
```
Comment (tgross) [inline client/pluginmanager/csimanager/manager.go:87]: `ensureInstance` has a note that we're assuming `c.instances.Lock` is being held, so that the caller is controlling release of the lock (this allows for safe writes back to the locked resources without interleaving). So we'll need to hold the lock here too.

File: client/dynamicplugins/registry.go [hunk 4]
```diff
@@ -301,6 +303,46 @@ func (d *dynamicRegistry) ListPlugins(ptype string) []*PluginInfo {
...
+	for {
+		for _, p := range d.ListPlugins(ptype) {
+			if p.Name == name {
+				return p, nil
+			}
+		}
+
+		//log.Printf("WaitForPlugin delay: %d", delay) // TODO: get a logger in here?
```
Comment (tgross) [inline client/dynamicplugins/registry.go:328]: Debugging debris to clean up here.

File: client/allocrunner/csi_hook.go [hunk 5]
```diff
@@ -85,11 +85,15 @@ func (c *csiHook) Prerun() error {
 	mounts := make(map[string]*csimanager.MountInfo, len(volumes))
 	for alias, pair := range volumes {
 
-		// We use this context only to attach hclog to the gRPC
-		// context. The lifetime is the lifetime of the gRPC stream,
-		// not specific RPC timeouts, but we manage the stream
-		// lifetime via Close in the pluginmanager.
-		mounter, err := c.csimanager.MounterForPlugin(c.shutdownCtx, pair.volume.PluginID)
+		// make sure the plugin is ready or becomes so quickly.
```
Comment (tgross) [inline client/allocrunner/csi_hook.go:88]: I think this comment is misleading, because we're actually waiting up to 24hr? 

Having the really long timeout on the unpublish workflow makes sense because we need to be able to recover the already-mounted volume from that state. But on the publish workflow we probably want to abandon the attempt within a short-ish amount of time so that we're not delaying a reschedule too much in the case where we've placed a new alloc and it's never going to work. 

Maybe... 5min to allow for a _very_ busy restoring client?

(Ideally we'd be able to distinguish between a "this is the first time" vs a "this is a restore", but we can do that and/or make the timeout tunable later.)

File: client/pluginmanager/csimanager/manager.go (hunk 3 above)
Comment (gulducat) [reply client/pluginmanager/csimanager/manager.go:87]: Oh good lookin out.  I guess I assumed it managed the lock itself since it does the writing.

File: client/dynamicplugins/registry.go (hunk 4 above)
Comment (gulducat) [reply client/dynamicplugins/registry.go:328]: Sometimes I leave these on purpose for a later person debugging to simply uncomment, but sounds like we prefer not to do that, so will remove!

File: client/allocrunner/csi_hook.go (hunk 5 above)
Comment (gulducat) [reply client/allocrunner/csi_hook.go:88]: Up to 24 hours is the last catch-all timeout [on the registry end](https://github.com/hashicorp/nomad/pull/16809/files#diff-533c7964b7d08aa5521e171e5200f35b4618cb7cd53348491b6aafc82d295611R317), just in case callers don't set their own timeouts like they should.  The csiManager's WaitForPlugin() [adds a timeout of 1 Minute](https://github.com/hashicorp/nomad/pull/16809/files#diff-da66b90315db1e7fce5ec609ab6eb1656a48c452e807527caf0416552770d040R81) because it has (or can have) more specific domain knowledge of its plugins' behavior.

I went back and forth on where to put which contexts with which timeout durations, and these values worked okay in my little sandbox.  Should I bump csiManager's up to 5min?  Or move them around some otherlyways?

**Comment by gulducat** [comment]
Thanks!  I made changes for everything except for the timeout durations, but happy to change that logic too as you may advise.  Let me know what you think!

File: client/allocrunner/csi_hook.go (hunk 5 above)
Comment (tgross) [reply client/allocrunner/csi_hook.go:88]: Ah, ok, I missed the 1 min on `csimanager.WaitForPlugin`. If we end up refactoring the postrun hook to use `csimanager.WaitForPlugin` too, we might find we want to lift that timeout configuration into the caller (the prerun or postrun hook), but this should be fine as-is for now.

**Review by tgross — APPROVED** [review]
LGTM, once you're happy that this solves the problem for non-hostpath plugins too. Don't forget to add a changelog and backport labels.
