### PR TITLE
Fix panic when canonicalizing a jobspec with incorrect job type.

### LINKED ISSUE #7203: type = "periodic" seems to trigger a segfault
### Nomad version
Client: Nomad `v0.10.3`
Server: Nomad `v0.10.1`

### Operating system and Environment details

Client: macOS `10.14.6`
Server: `Ubuntu 18.04.3 LTS`

### Issue

When running a job with a type non existing, it's triggering a segfault.

### Reproduction steps

```
nomad job run -verbose --address='https://xxx.example.com' ops-reaper.hcl
```

### Job file

https://gist.github.com/Y-Tian/a37959a21ac6134ab211d51f1b5d93ba

### Nomad Client logs

```
Error submitting job: Unexpected response code: 502 (<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>
)
```

### Nomad Server logs

https://gist.github.com/scalp42/816cb82d2838e2edca6b0ee3966674a5

### PR DESCRIPTION
**Pull request by jrasell**
When canonicalizing the ReschedulePolicy a panic was possible if
the passed job type was not valid. This change protects against
this possibility, in a verbose way to ensure the code path is
clear.

closes #7203

### CODE REVIEW

File: api/tasks_test.go [hunk 1]
```diff
@@ -638,3 +638,59 @@ func TestSpread_Canonicalize(t *testing.T) {
...
+				Delay:         timeToPtr(0),
+				DelayFunction: stringToPtr(""),
+				MaxDelay:      timeToPtr(0),
+				Unlimited:     boolToPtr(false),
+			},
+		},
+	}
+	for _, tc := range testCases {
+		actual := NewDefaultReschedulePolicy(tc.inputJobType)
+		assert.Equal(t, tc.expected, actual)
```
Comment (schmichael) [inline api/tasks_test.go]: Not a blocker but wrapping this in a `t.Run(tc.inputJobType, ...)` would make debugging failures a bit faster.

**Comment by schmichael** [comment]
Don't forget a CHANGELOG.md entry
