### PR TITLE
Fix TLS use in AllocFS API and region/dc detection

### LINKED ISSUE #2290: "nomad logs" with TLS broken
### Nomad version
v0.5.2

### Operating system and Environment details
Ubuntu 16.04 x86_64

root@node-2:~# env | grep NOMAD
NOMAD_CACERT=/etc/pki/tls/certs/ca.pem
NOMAD_CLIENT_CERT=/etc/pki/tls/certs/nomad.pem
NOMAD_CLIENT_KEY=/etc/pki/tls/private/nomad-key.pem
NOMAD_ADDR=https://localhost:4646

### Issue
Get error on "nomad logs":
root@node-2:~# nomad logs 8095d822
Error reading file: Get https://172.28.128.8:4646/v1/client/fs/logs/8095d822-b270-bcdc-d7fc-2db37f69d109?follow=false&offset=0&origin=start&task=nginx&type=stdout: x509: cannot validate certificate for 172.28.128.8 because it doesn't contain any IP SANs

But "nomad status" works:
root@node-2:~# nomad status
ID    Type     Priority  Status
test  service  50        running

### Reproduction steps
Enable TLS and setup env:
export NOMAD_ADDR=https://localhost:4646
export NOMAD_CACERT=/etc/pki/tls/certs/ca.pem
export NOMAD_CLIENT_CERT=/etc/pki/tls/certs/nomad.pem
export NOMAD_CLIENT_KEY=/etc/pki/tls/private/nomad-key.pem

### PR DESCRIPTION
**Pull request by schmichael**
Fixes #2290

### CODE REVIEW

File: api/agent.go [hunk 1]
```diff
@@ -60,10 +60,10 @@ func (a *Agent) populateCache(self *AgentSelf) {
 		a.nodeName = self.Member.Name
 	}
 	if a.datacenter == "" {
-		a.datacenter, _ = self.Member.Tags["dc"]
+		a.datacenter, _ = self.Config["Datacenter"].(string)
```
Comment (dadgar) [inline api/agent.go]: I would feel more comfortable if we validate the value existed to avoid panics

**Comment by dadgar** [comment]
Would mark the issue this fixes. LGTM

File: api/agent.go (hunk 1 above)
Comment (schmichael) [inline api/agent.go]: Technically this code is panic-safe, but it's overly clever so I'll fix it :)

(The 2 form assignment applies to the type assertion, so if the key doesn't exist it returns `interface{}(nil)` which when 2-form-assignment-asserted to string gives you the empty string which datacenter is anyway! Way too "clever" :) https://play.golang.org/p/5jcXxfdthi )
