### PR TITLE
Do not restart successful batch jobs when the node is tainted (removed/drained)

### LINKED ISSUE #1178: dead jobs switch their state back to pending when you shutdown client node
### Nomad Version
nomad version
Nomad v0.3.2

### Operating System and Environment Details
CentOS7 3.10.0-327.13.1.el7.x86_64

### Issue
If I shutdown client nodes, jobs that were in the dead state switch back to the pending state.

### Reproduction Steps
Configure a 3 node server cluster.  Bring up a single client node.  Submit a single batch job with a task count of 1 using the Docker driver.  Let the job run to completion.  If you run a nomad status the jobs will be in the dead state.  Shutdown the client node.  The job switches back to the pending state.

Note: I did not test this with other job types or drivers.  May be specific to this combination... or may not be.

### Nomad Server Config (other 2 are identical except for advertise IP)
```
bind_addr = "0.0.0.0"
log_level = "DEBUG"

data_dir = "/var/log/nomad/data_dir"
disable_update_check = true
region = "global"
datacenter = "dc1"
leave_on_terminate = true
leave_on_interrupt = true

telemetry {
    statsd_address = "127.0.0.1:8125"
}

advertise {
    http = "10.132.0.9:4646"
    rpc  = "10.132.0.9:4647"
    serf = "10.132.0.9:4648"
}

server {
    enabled = true
    bootstrap_expect = 3
    node_gc_threshold = "1m"
    retry_join = ["nomad-svr-global-01","nomad-svr-global-02","nomad-svr-global-03"]
}
```

### Nomad Client Config
```
bind_addr = "0.0.0.0"
log_level = "DEBUG"
region = "global"
datacenter = "dc1"

data_dir = "/var/log/nomad/data_dir"
disable_update_check = true
leave_on_terminate = true
leave_on_interrupt = true

telemetry {
   statsd_address = "127.0.0.1:8125"
}

client {
   enabled = true
   servers = ["nomad-svr-global-01","nomad-svr-global-02","nomad-svr-global-03"]
   options = {
      "driver.raw_exec.enable" = "1"
      "docker.cleanup.image" = false
   }
}
```

### Job File 
```
{
    "Job": {
        "Region": "global",
        "ID": "test-01",
        "Name": "test-01",
        "Type": "batch",
        "Priority": 50,
        "Datacenters": [
            "dc1"
        ],
        "TaskGroups": [
            {
                "Name": "test-group",
                "Count": 1,
                "Tasks": [
                    {
                        "Name": "hello-world",
                        "Driver": "docker",
                        "Config": {
                            "image": "https://docker-cache.service.consul:5000/cdi/nomad-test:v0.0.9",
                            "command": "/opt/test/bin/test_batch.py",
                            "args": ["-t","30"],
                            "network_mode": "host"
                        },
                        "Resources": {
                            "CPU": 2500,
                            "MemoryMB": 256,
                            "DiskMB": 300,
                            "IOPS": 0
                        },
                        "LogConfig": {
                           "MaxFiles": 10,
                           "MaxFileSizeMB": 10
                        }
                    }
                ]
            }
        ]
    }
}
```

### LINKED ISSUE #1193: nomad node-drain rescheduled all completed periodic tasks
### Nomad version

0.3.2

### Operating system and Environment details

Ubuntu 14.04 LTS (all clients and servers)

### Issue

I modified some system settings and brought up a new Nomad client (new instance). I did a `nomad drain` on the other Nomad client. It immediately scheduled seemingly dozens of periodic tasks that had completed, onto the new node. I can verify based on the logs that they all re-ran. 

### Reproduction steps

1. Start a single server, single client
2. Create a periodic job, let it run for awhile, at least a dozen times
3. Start a second client, no allocations go to it (they're all happy on the first client)
4. Drain the first client, run `nomad node-status` on the new client, see all periodic tasks re-enter "pending" state with desired state "run"

### PR DESCRIPTION
**Pull request by dadgar**
This PR fixes an issue in which batch allocations would be restarted when the node that ran the allocation was drained.

Fixes #1193, Fixes #1178 

@armon for review

### CODE REVIEW

File: scheduler/util.go [hunk 1]
```diff
@@ -81,8 +81,12 @@ func diffAllocs(job *structs.Job, taintedNodes map[string]bool,
 			continue
 		}
 
-		// If we are on a tainted node, we must migrate
+		// If we are on a tainted node, we must migrate if we are a service or
+		// if the batch allocation did not finish
 		if taintedNodes[exist.NodeID] {
+			if exist.Job.Type == structs.JobTypeBatch && exist.RanSuccessfully() {
```
Comment (armon) [inline scheduler/util.go]: Add comment as to why only batch, since this seems like it could work for any.

**Comment by armon** [comment]
LGTM
