### PR TITLE
core: enforce strict steps for clients reconnect

### LINKED ISSUE #15483: New behavior when max_client_disconnect is used and the worker node moves from disconnected to ready
### Nomad version
1.3.8/1.4.3

### Issue
A new behavior is seen in 1.3.8 & 1.4.3 (verified) where jobs which have `max_client_disconnect` defined and a prestart task is used to ensure the task only runs on the desired node, changes state from unknown, to running and then to complete once the node is back in a ready state.  Eventually a new alloc will be placed on the desired node, after it has cycled through other non-desired nodes, however this is not the same behavior seen in prior versions tested (eg. 1.3.3/1.4.2)

Behavior seen when testing with 1.3.8/1.4.3:

After the alloc is placed on the desired node; if the nomad service is stopped on the desired node:
- The node status is `disconnected` and the placed alloc status is `unknown`, as expected.
- The alloc status stays as `unknown` for the duration of the node being `disconnected`.
- Once the nomad service is restarted, the node status changes to `ready`
- The alloc initially placed on the preferred node briefly shows a status of `running` but within ~25 seconds the status changes to `complete` and the job is moved to `pending`.
- The job stays in `pending` until a new alloc is placed on the preferred node.

This behavior was only seen when a job uses a prestart task (raw_exec in this example) which ensures the job is placed on the specific/desired node before the main task starts.

### Reproduction steps
The same steps, times and job files were used while testing against 1.3.x (1.3.8 & 1.3.3) and 1.4.x (1.4.3 & 1.4.2).

__Jobs Used for Testing:__

1.  example1.nomad - Generic redis job, `max_client_disconnect` is not set.  Affinity used so the preferred node will be used for the initial placing and can be migrated to other nodes if needed.
2. example2.nomad - Generic redis job, `max_client_disconnect` is set. Constraint used so the alloc will be pinned to the preferred node.
3. 91244_mod-2.nomad - Modified redis job, `max_client_disconnect` is set and a pre-start task is used to ensure that the job is placed on the desired node before the main task starts.

__High Level Steps:__
1.  Deploy the jobs
4. Once the allocs are verified running on the specific/desired node, stop the nomad service on the specific/desired node.
5. Run `nomad node status` and `nomad job status -verbose <JOB_ID>` in intervals.  I used 5 minute intervals, after the nomad service was stopped, for the baseline status.  At the 15 minute mark, I started the nomad service on the specific/desired node and again ran `nomad node status` and `nomad job status -verbose <JOB_ID>` for example2.nomad and 91244_mod-2.nomad.
6. Monitor the job status of 91244_mod-2.nomad 

#### Expected Result
In versions prior to 1.3.8/1.4.3, the alloc status of 91244_mod-2.nomad behavior is:

1.  State after initial placement (Initial alloc placed on the preferred node):  `running`
2. State after the nomad service is stopped on the preferred node (Initial alloc placed on the preferred node):  `unknown`
    State of allocs placed on non-preferred node, after the nomad service is stopped on the preferred node: `failed`
3. State after the nomad service is started again on the preferred node (Initial alloc placed on the preferred node):  `running`

__5 Minute - Alloc Status__

```
Allocations
ID                                    Eval ID                               Node ID                               Node Name         Task Group         Version  Desired  Status   Created                    Modified
636d015e-c81d-2371-646b-5ae756768013  95c4cfde-0704-0adf-f8a0-d7c7e01932fb  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        run      failed   2022-12-05T15:32:42-05:00  2022-12-05T15:32:58-05:00
16394df7-52bd-97f5-34c0-feb610c30546  2458303d-0fbc-012a-1e44-b2cbfa12fba7  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T15:30:26-05:00  2022-12-05T15:32:42-05:00
f96e2ace-29aa-0d6d-9564-06c78f92c573  dba3f5b2-9eec-330b-f407-ca476b7bd979  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T15:29:10-05:00  2022-12-05T15:30:26-05:00
556ce590-0158-29d5-b19c-f545b463ec25  34dda7d8-4fd1-162d-c8a7-84c2f89fff4e  4173785e-c421-3287-51a6-bd35b8cd601b  ip-172-31-20-215  91244_mod_group-2  0        run      unknown  2022-12-05T15:28:08-05:00  2022-12-05T15:29:10-05:00
```

__10 Minute - Alloc Status__

```
Allocations
ID                                    Eval ID                               Node ID                               Node Name         Task Group         Version  Desired  Status   Created                    Modified
25649dde-3ce4-4fdf-cc2a-658fc933d988  03f60b1e-fdff-6648-a107-0af72a9d0527  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        run      failed   2022-12-05T15:36:58-05:00  2022-12-05T15:37:16-05:00
636d015e-c81d-2371-646b-5ae756768013  95c4cfde-0704-0adf-f8a0-d7c7e01932fb  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T15:32:42-05:00  2022-12-05T15:36:58-05:00
16394df7-52bd-97f5-34c0-feb610c30546  2458303d-0fbc-012a-1e44-b2cbfa12fba7  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T15:30:26-05:00  2022-12-05T15:32:42-05:00
f96e2ace-29aa-0d6d-9564-06c78f92c573  dba3f5b2-9eec-330b-f407-ca476b7bd979  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T15:29:10-05:00  2022-12-05T15:30:26-05:00
556ce590-0158-29d5-b19c-f545b463ec25  34dda7d8-4fd1-162d-c8a7-84c2f89fff4e  4173785e-c421-3287-51a6-bd35b8cd601b  ip-172-31-20-215  91244_mod_group-2  0        run      unknown  2022-12-05T15:28:08-05:00  2022-12-05T15:29:10-05:00
```

__15 Minute - Alloc Status (after nomad service started on the worker node)__

```
Allocations
ID                                    Eval ID                               Node ID                               Node Name         Task Group         Version  Desired  Status   Created                    Modified
25649dde-3ce4-4fdf-cc2a-658fc933d988  03f60b1e-fdff-6648-a107-0af72a9d0527  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        run      failed   2022-12-05T15:36:58-05:00  2022-12-05T15:37:16-05:00
636d015e-c81d-2371-646b-5ae756768013  95c4cfde-0704-0adf-f8a0-d7c7e01932fb  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T15:32:42-05:00  2022-12-05T15:36:58-05:00
16394df7-52bd-97f5-34c0-feb610c30546  2458303d-0fbc-012a-1e44-b2cbfa12fba7  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T15:30:26-05:00  2022-12-05T15:32:42-05:00
f96e2ace-29aa-0d6d-9564-06c78f92c573  dba3f5b2-9eec-330b-f407-ca476b7bd979  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T15:29:10-05:00  2022-12-05T15:30:26-05:00
556ce590-0158-29d5-b19c-f545b463ec25  34dda7d8-4fd1-162d-c8a7-84c2f89fff4e  4173785e-c421-3287-51a6-bd35b8cd601b  ip-172-31-20-215  91244_mod_group-2  0        run      running  2022-12-05T15:28:08-05:00  2022-12-05T15:43:58-05:00
```

#### Actual Result
In versions 1.3.8/1.4.3, the alloc status of 91244_mod-2.nomad behavior is:

1.  State after initial placement (Initial alloc placed on the preferred node):  `running`
2. State after the nomad service is stopped on the preferred node (Initial alloc placed on the preferred node):  `unknown`
    State of allocs placed on non-preferred node, after the nomad service is stopped on the preferred node: `failed`
3. State after the nomad service is started again on the preferred node (Initial alloc placed on the preferred node):  Initially the alloc status is `running`, then moves to `complete`

__5 Minute - Alloc Status__

```
Allocations
ID                                    Eval ID                               Node ID                               Node Name         Task Group         Version  Desired  Status   Created                    Modified
645c0ffe-96dd-c92e-d648-60cdbd86a52c  c5f13eda-1c5e-4032-b53c-c86f0bb6aa9b  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        run      failed   2022-12-05T13:26:49-05:00  2022-12-05T13:27:24-05:00
59824c2f-cad5-1e78-67d8-26efb53970b8  d79bcd13-e6e9-3cde-1d99-942346299ead  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T13:24:16-05:00  2022-12-05T13:26:49-05:00
49607b18-8cee-2916-8cb5-03d17bea49e7  4c057e43-3690-14cb-6b4c-e87bbd6782c2  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T13:22:42-05:00  2022-12-05T13:24:16-05:00
0e1ac64e-b641-c1a7-6444-afa52cccd2aa  3a105768-3092-1d49-34b8-98697f999413  4173785e-c421-3287-51a6-bd35b8cd601b  ip-172-31-20-215  91244_mod_group-2  0        run      unknown  2022-12-05T13:21:00-05:00  2022-12-05T13:22:42-05:00
```

__10 Minute - Alloc Status__

```
Allocations
ID                                    Eval ID                               Node ID                               Node Name         Task Group         Version  Desired  Status   Created                    Modified
81bc6e7b-d290-74d4-0494-da7309a74a6d  fc4f3c31-76b3-aeca-5ce3-fc2b413543d4  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        run      failed   2022-12-05T13:31:24-05:00  2022-12-05T13:32:00-05:00
645c0ffe-96dd-c92e-d648-60cdbd86a52c  c5f13eda-1c5e-4032-b53c-c86f0bb6aa9b  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T13:26:49-05:00  2022-12-05T13:31:24-05:00
59824c2f-cad5-1e78-67d8-26efb53970b8  d79bcd13-e6e9-3cde-1d99-942346299ead  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T13:24:16-05:00  2022-12-05T13:26:49-05:00
49607b18-8cee-2916-8cb5-03d17bea49e7  4c057e43-3690-14cb-6b4c-e87bbd6782c2  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T13:22:42-05:00  2022-12-05T13:24:16-05:00
0e1ac64e-b641-c1a7-6444-afa52cccd2aa  3a105768-3092-1d49-34b8-98697f999413  4173785e-c421-3287-51a6-bd35b8cd601b  ip-172-31-20-215  91244_mod_group-2  0        run      unknown  2022-12-05T13:21:00-05:00  2022-12-05T13:22:42-05:00
```

__15 Minute - Alloc Status (after nomad service started on the worker node)__

```
Allocations
ID                                    Eval ID                               Node ID                               Node Name         Task Group         Version  Desired  Status   Created                    Modified
81bc6e7b-d290-74d4-0494-da7309a74a6d  fc4f3c31-76b3-aeca-5ce3-fc2b413543d4  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        run      failed   2022-12-05T13:31:24-05:00  2022-12-05T13:32:00-05:00
645c0ffe-96dd-c92e-d648-60cdbd86a52c  c5f13eda-1c5e-4032-b53c-c86f0bb6aa9b  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T13:26:49-05:00  2022-12-05T13:31:24-05:00
59824c2f-cad5-1e78-67d8-26efb53970b8  d79bcd13-e6e9-3cde-1d99-942346299ead  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T13:24:16-05:00  2022-12-05T13:26:49-05:00
49607b18-8cee-2916-8cb5-03d17bea49e7  4c057e43-3690-14cb-6b4c-e87bbd6782c2  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T13:22:42-05:00  2022-12-05T13:24:16-05:00
0e1ac64e-b641-c1a7-6444-afa52cccd2aa  3a105768-3092-1d49-34b8-98697f999413  4173785e-c421-3287-51a6-bd35b8cd601b  ip-172-31-20-215  91244_mod_group-2  0        run      running  2022-12-05T13:21:00-05:00  2022-12-05T13:37:20-05:00

Allocations
ID                                    Eval ID                               Node ID                               Node Name         Task Group         Version  Desired  Status   Created                    Modified
47d9944f-0c74-3a74-aa82-ec4e1d5758f1  071d33fa-8f71-0c21-6a2b-e06c5ea0e1d4  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        run      pending  2022-12-05T13:39:59-05:00  2022-12-05T13:40:00-05:00
81bc6e7b-d290-74d4-0494-da7309a74a6d  fc4f3c31-76b3-aeca-5ce3-fc2b413543d4  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T13:31:24-05:00  2022-12-05T13:39:59-05:00
645c0ffe-96dd-c92e-d648-60cdbd86a52c  c5f13eda-1c5e-4032-b53c-c86f0bb6aa9b  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T13:26:49-05:00  2022-12-05T13:31:24-05:00
59824c2f-cad5-1e78-67d8-26efb53970b8  d79bcd13-e6e9-3cde-1d99-942346299ead  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T13:24:16-05:00  2022-12-05T13:26:49-05:00
49607b18-8cee-2916-8cb5-03d17bea49e7  4c057e43-3690-14cb-6b4c-e87bbd6782c2  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed   2022-12-05T13:22:42-05:00  2022-12-05T13:24:16-05:00
0e1ac64e-b641-c1a7-6444-afa52cccd2aa  3a105768-3092-1d49-34b8-98697f999413  4173785e-c421-3287-51a6-bd35b8cd601b  ip-172-31-20-215  91244_mod_group-2  0        run      running  2022-12-05T13:21:00-05:00  2022-12-05T13:37:20-05:00

Allocations
ID                                    Eval ID                               Node ID                               Node Name         Task Group         Version  Desired  Status    Created                    Modified
47d9944f-0c74-3a74-aa82-ec4e1d5758f1  071d33fa-8f71-0c21-6a2b-e06c5ea0e1d4  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        run      failed    2022-12-05T13:39:59-05:00  2022-12-05T13:40:34-05:00
81bc6e7b-d290-74d4-0494-da7309a74a6d  fc4f3c31-76b3-aeca-5ce3-fc2b413543d4  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed    2022-12-05T13:31:24-05:00  2022-12-05T13:39:59-05:00
645c0ffe-96dd-c92e-d648-60cdbd86a52c  c5f13eda-1c5e-4032-b53c-c86f0bb6aa9b  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed    2022-12-05T13:26:49-05:00  2022-12-05T13:31:24-05:00
59824c2f-cad5-1e78-67d8-26efb53970b8  d79bcd13-e6e9-3cde-1d99-942346299ead  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed    2022-12-05T13:24:16-05:00  2022-12-05T13:26:49-05:00
49607b18-8cee-2916-8cb5-03d17bea49e7  4c057e43-3690-14cb-6b4c-e87bbd6782c2  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed    2022-12-05T13:22:42-05:00  2022-12-05T13:24:16-05:00
0e1ac64e-b641-c1a7-6444-afa52cccd2aa  3a105768-3092-1d49-34b8-98697f999413  4173785e-c421-3287-51a6-bd35b8cd601b  ip-172-31-20-215  91244_mod_group-2  0        stop     complete  2022-12-05T13:21:00-05:00  2022-12-05T13:40:35-05:00

Allocations
ID                                    Eval ID                               Node ID                               Node Name         Task Group         Version  Desired  Status    Created                    Modified
6ae99016-53a7-b53e-a721-1b50051ec033  688a71e1-66f1-f80b-726d-1c395b4cb8ca  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        run      pending   2022-12-05T13:56:33-05:00  2022-12-05T13:56:52-05:00
47d9944f-0c74-3a74-aa82-ec4e1d5758f1  071d33fa-8f71-0c21-6a2b-e06c5ea0e1d4  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed    2022-12-05T13:39:59-05:00  2022-12-05T13:56:33-05:00
81bc6e7b-d290-74d4-0494-da7309a74a6d  fc4f3c31-76b3-aeca-5ce3-fc2b413543d4  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed    2022-12-05T13:31:24-05:00  2022-12-05T13:39:59-05:00
645c0ffe-96dd-c92e-d648-60cdbd86a52c  c5f13eda-1c5e-4032-b53c-c86f0bb6aa9b  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed    2022-12-05T13:26:49-05:00  2022-12-05T13:31:24-05:00
59824c2f-cad5-1e78-67d8-26efb53970b8  d79bcd13-e6e9-3cde-1d99-942346299ead  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed    2022-12-05T13:24:16-05:00  2022-12-05T13:26:49-05:00
49607b18-8cee-2916-8cb5-03d17bea49e7  4c057e43-3690-14cb-6b4c-e87bbd6782c2  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed    2022-12-05T13:22:42-05:00  2022-12-05T13:24:16-05:00
0e1ac64e-b641-c1a7-6444-afa52cccd2aa  3a105768-3092-1d49-34b8-98697f999413  4173785e-c421-3287-51a6-bd35b8cd601b  ip-172-31-20-215  91244_mod_group-2  0        stop     complete  2022-12-05T13:21:00-05:00  2022-12-05T13:40:35-05:00

Allocations
ID                                    Eval ID                               Node ID                               Node Name         Task Group         Version  Desired  Status    Created                    Modified
6ae99016-53a7-b53e-a721-1b50051ec033  688a71e1-66f1-f80b-726d-1c395b4cb8ca  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        run      failed    2022-12-05T13:56:33-05:00  2022-12-05T13:57:10-05:00
47d9944f-0c74-3a74-aa82-ec4e1d5758f1  071d33fa-8f71-0c21-6a2b-e06c5ea0e1d4  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed    2022-12-05T13:39:59-05:00  2022-12-05T13:56:33-05:00
81bc6e7b-d290-74d4-0494-da7309a74a6d  fc4f3c31-76b3-aeca-5ce3-fc2b413543d4  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed    2022-12-05T13:31:24-05:00  2022-12-05T13:39:59-05:00
645c0ffe-96dd-c92e-d648-60cdbd86a52c  c5f13eda-1c5e-4032-b53c-c86f0bb6aa9b  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed    2022-12-05T13:26:49-05:00  2022-12-05T13:31:24-05:00
59824c2f-cad5-1e78-67d8-26efb53970b8  d79bcd13-e6e9-3cde-1d99-942346299ead  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed    2022-12-05T13:24:16-05:00  2022-12-05T13:26:49-05:00
49607b18-8cee-2916-8cb5-03d17bea49e7  4c057e43-3690-14cb-6b4c-e87bbd6782c2  a21d8f3e-46ba-abd3-6ff7-967ad68996de  ip-172-31-29-24   91244_mod_group-2  0        stop     failed    2022-12-05T13:22:42-05:00  2022-12-05T13:24:16-05:00
0e1ac64e-b641-c1a7-6444-afa52cccd2aa  3a105768-3092-1d49-34b8-98697f999413  4173785e-c421-3287-51a6-bd35b8cd601b  ip-172-31-20-215  91244_mod_group-2  0        stop     complete  2022-12-05T13:21:00-05:00  2022-12-05T13:40:35-05:00
```

### Job file (if appropriate)

_example1.nomad_

```
job "example_no_disconnect" {
  datacenters = ["dc1"]

  affinity {
    attribute = "${unique.hostname}"
    value = "<HOSTNAME_OF_PREFERRED_NODE>"
    weight = 100
  }

  group "cache_no_disconnect" {
    network {
      port "db" {
        to = 6379
      }
    }

    count = 2

    task "redis_no_disconnect" {
      driver = "docker"

      config {
        image          = "redis:7"
        ports          = ["db"]
        auth_soft_fail = true
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

_example2.nomad_

```
job "example_disconnect" {
  datacenters = ["dc1"]

  constraint {
    attribute = "${attr.unique.hostname}"
    value = "<HOSTNAME_OF_PREFERRED_NODE>"
  }

  group "cache_disconnect" {
    network {
      port "db" {
        to = 6379
      }
    }

    count = 2

    max_client_disconnect = "12h"

    task "redis_disconnect" {
      driver = "docker"

      config {
        image          = "redis:7"
        ports          = ["db"]
        auth_soft_fail = true
      }

      resources {
        cpu    = 500
        memory = 256
      }
    }
  }
}
```

_91244_mod-2.nomad_

```
job "91244_mod-2" {
  datacenters = ["dc1"]

  group "91244_mod_group-2" {
    network {
      port "db" {
        to = 6379
      }
    }

    max_client_disconnect = "12h"

    task "91244_mod_pretask-2" {
      driver = "raw_exec"

      lifecycle {
        hook = "prestart"
        sidecar = false
      }

      template {
        data = <<EOH
        #!/bin/bash
        set -e
        echo "Starting maintenance pretask"
        echo $HOSTNAME
        if [[ "$HOSTNAME" = "<HOSTNAME_OF_PREFERRED_NODE>" ]]
        then
        echo "We're good to go, starting redis..." && exit 0
        else
        echo "Wrong host - exiting" && exit 1
        fi

        EOH
        perms = "775"
        destination = "maintenance.sh"
      }

      config {
        command = "/bin/bash"
        args    = ["-c","./maintenance.sh"]
      }

      resources {
        memory = 50
      }
    }

    task "91244_mod_redis-2" {
      driver = "docker"

      config {
        image          = "redis:7"
        ports          = ["db"]
        auth_soft_fail = true
      }

      resources {
        cpu = 500
        memory = 256
      }
    }
  }
}
```

### Nomad Server logs (if appropriate)
Debug bundles taken while testing (1.3.8/1.3.3 & 1.4.3/1.4.2) have been uploaded to: https://drive.google.com/drive/folders/1Ds83JQBQlPQukPELj3Ia_iCUnaaE73Jp?usp=sharing

### PR DESCRIPTION
**Pull request by lgfa29**
When a Nomad client that is running an allocation with `max_client_disconnect` set misses a heartbeat the Nomad server will update its status to `disconnected`.

Upon reconnecting, the client will make three main RPC calls:

- `Node.UpdateStatus` is used to set the client status to `ready`.
- `Node.UpdateAlloc` is used to update the client-side information about
  allocations, such as their `ClientStatus`, task states etc.
- `Node.Register` is used to upsert the entire node information,
  including its status.

These calls are made concurrently and are also running in parallel with the scheduler. Depending on the order they run the scheduler may end up with incomplete data when reconciling allocations. 

#15068 already enforced clients to heartbeat before updating their allocation data, but there are still scenarios that can generate wrong results.

For example, a client disconnects and its replacement allocation cannot be placed anywhere else, so there's a pending eval waiting for resources.

When this client comes back the order of events may be:

1. Client calls `Node.UpdateStatus` and is now `ready`.
2. Scheduler reconciles allocations and places the replacement alloc to
   the client. The client is now assigned two allocations: the original
   alloc that is still `unknown` and the replacement that is `pending`.
3. Client calls `Node.UpdateAlloc` and updates the original alloc to
   `running`.
4. Scheduler notices too many allocs and stops the replacement.

node-disconnect drawio

This creates unnecessary placements or, in a different order of events, may leave the job without any allocations running until the whole state is updated and reconciled.

To avoid problems like this clients must update _all_ of its relevant information before they can be considered `ready` and available for scheduling.

To achieve this goal the RPC endpoints mentioned above have been modified to enforce strict steps for nodes reconnecting:

- `Node.Register` does not set the client status anymore.
- `Node.UpdateStatus` sets the reconnecting client to the `initializing`
  status until it successfully calls `Node.UpdateAlloc`.

node-disconnect drawio

These changes are done server-side to avoid the need of additional coordination between clients and servers. Clients are kept oblivious of these changes and will keep making these calls as they normally would.

The verification of whether allocations have been updates is done by storing and comparing the Raft index of the last time the client missed a heartbeat and the last time it updated its allocations.

Closes #15483

### CODE REVIEW

File: nomad/node_endpoint_test.go [hunk 1]
```diff
@@ -639,29 +805,25 @@ func TestClientEndpoint_Register_GetEvals(t *testing.T) {
...
-		Node:         node,
+	req := &structs.NodeUpdateStatusRequest{
+		NodeID:       node.ID,
+		Status:       structs.NodeStatusDown,
 		WriteRequest: structs.WriteRequest{Region: "global"},
 	}
-
-	// Fetch the response
-	if err := msgpackrpc.CallWithCodec(codec, "Node.Register", reg, &resp); err != nil {
+	if err := msgpackrpc.CallWithCodec(codec, "Node.UpdateStatus", req, &resp); err != nil {
```
Comment (lgfa29) [inline nomad/node_endpoint_test.go:813]: Changes like these were necessary because the `Node.Register` endpoint doesn't set the node status anymore.

File: nomad/node_endpoint_test.go [hunk 2]
```diff
@@ -2581,7 +2743,7 @@ func TestClientEndpoint_UpdateAlloc_NodeNotReady(t *testing.T) {
 	}
 	var allocUpdateResp structs.NodeAllocsResponse
 	err = msgpackrpc.CallWithCodec(codec, "Node.UpdateAlloc", allocUpdateReq, &allocUpdateResp)
-	require.ErrorContains(t, err, "not ready")
+	require.ErrorContains(t, err, "not allow to update allocs")
```
Comment (lgfa29) [inline nomad/node_endpoint_test.go:2746]: I changed the error message in https://github.com/hashicorp/nomad/pull/15808/files#diff-86b976ad80dd125c60d191875f83e20d1e4ee971966b910665d75c3165cb65e4L1182-R1209

File: nomad/structs/structs.go [hunk 3]
```diff
@@ -2090,6 +2090,14 @@ type Node struct {
 	// LastDrain contains metadata about the most recent drain operation
 	LastDrain *DrainMetadata
 
+	// LastMissedHeartbeatIndex stores the Raft index when the node
+	// last missed a heartbeat.
+	LastMissedHeartbeatIndex uint64
```
Comment (lgfa29) [inline nomad/structs/structs.go:2095]: I'm not sure how accurate this name is. It's more like the first time the node transition to an unresponsive status, but I couldn't think of a good name for this 😅

File: nomad/node_endpoint.go [hunk 4]
```diff
@@ -1179,8 +1205,8 @@ func (n *Node) UpdateAlloc(args *structs.AllocUpdateRequest, reply *structs.Gene
 	if node == nil {
 		return fmt.Errorf("node %s not found", nodeID)
 	}
-	if node.Status != structs.NodeStatusReady {
-		return fmt.Errorf("node %s is %s, not %s", nodeID, node.Status, structs.NodeStatusReady)
+	if node.UnresponsiveStatus() {
+		return fmt.Errorf("node %s is not allow to update allocs while in status %s", nodeID, node.Status)
```
Comment (tgross) [inline nomad/node_endpoint.go:1209]: The `UpdateAlloc` method has the following comment in the docstring:

> // Clients must first register and heartbeat successfully before they are able
> // to call this method.

So now we're changing that so that we reject `UpdateStatus` changes (heartbeat) until after `UpdateAlloc` is called, right? Let's update the docstring to match. It also couldn't hurt to add a note to `UpdateStatus` about the same logic.

File: nomad/node_endpoint.go [hunk 5]
```diff
@@ -1313,6 +1339,17 @@ func (n *Node) UpdateAlloc(args *structs.AllocUpdateRequest, reply *structs.Gene
...
+	// Update node alloc update index.
+	copyNode := node.Copy()
+	copyNode.LastAllocUpdateIndex = future.Index()
+
+	_, _, err = n.srv.raftApply(structs.NodeRegisterRequestType, &structs.NodeRegisterRequest{
+		Node: copyNode,
+	})
+	if err != nil {
+		return fmt.Errorf("node update failed: %v", err)
+	}
```
Comment (tgross) [inline nomad/node_endpoint.go:1351]: With this change there are two raft logs in this RPC. It's unlikely, but if there's a failure between the batched alloc/eval update and this one, we'll end up with the `LastAllocUpdateIndex` not having been updated. If I'm reasoning thru the logic above correctly, that would "freeze" the node in an initializing state until something there's a new allocation change on the client (which could be a while!).

It looks like the `AllocClientUpdateRequestType` raft entry is only ever used by this RPC. Could we perform the update for the node's `LastAllocUpdateIndex` in the same raft apply? 

(Another way to handle that, given that we already have to query for allocations, would be to derive the last update from the allocation's modify index. But that seems like we'd risk server-side updates to allocations causing a node to flap from ready to initializing?)

File: .changelog/15808.txt [hunk 6]
```diff
@@ -0,0 +1,3 @@
+```release-note:bug
+core: enforce strict steps for clients reconnect
```
Comment (tgross) [inline .changelog/15808.txt:2]: This is a really important change, so probably worth being a little more explicit about it:

```suggestion
core: enforce strict ordering that node status updates are recorded after allocation updates for reconnecting clients
```

File: nomad/node_endpoint_test.go [hunk 7]
```diff
@@ -524,6 +525,181 @@ func TestClientEndpoint_UpdateStatus_Vault(t *testing.T) {
 	}
 }
 
+func TestClientEndpoint_UpdateStatus_Reconnect(t *testing.T) {
+	ci.Parallel(t)
+
+	// Setup server with tighther heartbeat so we don't have to wait so long
```
Comment (tgross) [inline nomad/node_endpoint_test.go:531]:
```suggestion
	// Setup server with tighter heartbeat so we don't have to wait so long
```

File: nomad/node_endpoint_test.go [hunk 8]
```diff
@@ -524,6 +525,181 @@ func TestClientEndpoint_UpdateStatus_Vault(t *testing.T) {
...
+					return
+				}
+
+				req := &structs.NodeUpdateStatusRequest{
+					NodeID:       node.ID,
+					Status:       structs.NodeStatusReady,
+					WriteRequest: structs.WriteRequest{Region: "global"},
+				}
+				var resp structs.NodeUpdateResponse
+				// Ignore errors since an unexpected failed hearbeat will cause
```
Comment (tgross) [inline nomad/node_endpoint_test.go:572]:
```suggestion
				// Ignore errors since an unexpected failed heartbeat will cause
```

File: nomad/node_endpoint_test.go [hunk 9]
```diff
@@ -524,6 +525,181 @@ func TestClientEndpoint_UpdateStatus_Vault(t *testing.T) {
...
+	reg := &structs.NodeRegisterRequest{
+		Node:         node,
+		WriteRequest: structs.WriteRequest{Region: "global"},
+	}
+	var nodeUpdateResp structs.NodeUpdateResponse
+	err := msgpackrpc.CallWithCodec(codec, "Node.Register", reg, &nodeUpdateResp)
+	must.NoError(t, err)
+
+	// Start heartbeat.
+	stopHeartbeat := make(chan interface{})
```
Comment (tgross) [inline nomad/node_endpoint_test.go:553]: This is fine, but why not use a context w/ cancel here? That way you can both `defer cancel()` and safely call `cancel` to stop the heartbeat during the text, and not worry about leaking the goroutine.

File: nomad/node_endpoint_test.go [hunk 10]
```diff
@@ -524,6 +525,181 @@ func TestClientEndpoint_UpdateStatus_Vault(t *testing.T) {
...
+	heartbeat := func() {
+		ticker := time.NewTicker(heartbeatTTL / 2)
```
Comment (tgross) [inline nomad/node_endpoint_test.go:555]: We should probably be using the safe timer helper, which has a cancel you can defer for when we return.

File: nomad/node_endpoint_test.go [hunk 11]
```diff
@@ -524,6 +525,181 @@ func TestClientEndpoint_UpdateStatus_Vault(t *testing.T) {
...
+		Alloc: []*structs.Allocation{alloc},
+		WriteRequest: structs.WriteRequest{
+			Region: "global",
+		},
+	}
+	var resp structs.GenericResponse
+	err = msgpackrpc.CallWithCodec(codec, "Node.UpdateAlloc", allocUpdateReq, &resp)
+	must.NoError(t, err)
+
+	// Wait for alloc run be running in the server.
```
Comment (tgross) [inline nomad/node_endpoint_test.go:637]:
```suggestion
	// Wait for alloc to be running in the server.
```

File: nomad/node_endpoint_test.go [hunk 12]
```diff
@@ -524,6 +525,181 @@ func TestClientEndpoint_UpdateStatus_Vault(t *testing.T) {
...
+	ws := memdb.NewWatchSet()
+	evals, err := state.EvalsByJob(ws, job.Namespace, job.ID)
+	found := false
+	for _, eval := range evals {
+		if eval.Status == structs.EvalStatusPending {
+			found = true
+			break
+		}
+	}
+	must.True(t, found)
```
Comment (tgross) [inline nomad/node_endpoint_test.go:661]: This section seems racy with the scheduler. Shouldn't we ultimately end up with a blocked eval here because that pending eval is going to get dequeued and there's no node to place the replacement alloc?

**Review by tgross — CHANGES_REQUESTED** [review]
This is looking really good @lgfa29. I think you boiled down the complex problem into a really nice targeted change here. I've mostly left suggestions but also one potentially nasty bug.

File: nomad/node_endpoint_test.go (hunk 11 above)
Comment (lgfa29) [reply nomad/node_endpoint_test.go:637]: I copied and pasted this all over thee place 🤦

File: nomad/node_endpoint.go (hunk 4 above)
Comment (lgfa29) [reply nomad/node_endpoint.go:1209]: The comment is still true. What this PR changes is that the status value in the `UpdateStatus` request may not be applied by the server. 

For example, if the node is `initializing` the heartbeats will send `Status: "ready"` but the server will not transition the node to `ready` until `UpdateAlloc` is called.

What this PR does change is that it allows `UpdateAlloc` to be called when the client is `initializing` as well to allow for the state transition. Previously it was only allowed when `ready`.

File: nomad/node_endpoint.go (hunk 5 above)
Comment (lgfa29) [reply nomad/node_endpoint.go:1351]: Oh right, good catch. I think I misunderstood how the batch updates worked so I thought we wouldn't be able to reuse them. But I see that it may actually be possible.

I also thought about looking at the lowest alloc `ModifyIndex` but I figured there could be other things updating this value (like the server itself).

I will make the index update in the `AllocClientUpdateRequestType` request, thanks!

File: nomad/node_endpoint_test.go (hunk 10 above)
Comment (lgfa29) [reply nomad/node_endpoint_test.go:555]: I think the safe timer is used for one-off delays where it can leak if another `case` is activated right? For ticker I think we're safe to use, but you're right that I can just `defer ticker.Stop()` to make sure it's always stopped.

File: nomad/node_endpoint_test.go (hunk 1 above)
Comment (lgfa29) [reply nomad/node_endpoint_test.go:836]: We do register them earlier in the test, it's that maybe the `UpdateStatus` method didn't exist before so the `Register` was being used to update the status?

File: nomad/node_endpoint_test.go (hunk 12 above)
Comment (lgfa29) [reply nomad/node_endpoint_test.go]: Good point. After reading your comment below I noticed that this check is actually kind of useless. The actual assertion we need to make is that the state of the cluster after the client reconnects stays the same and it's stable (all evals are terminal). 

I updated the test to reflect this.

File: nomad/node_endpoint_test.go (hunk 9 above)
Comment (lgfa29) [reply nomad/node_endpoint_test.go]: Yup, much better with context, thanks!

File: nomad/node_endpoint_test.go (hunk 1 above)
Comment (tgross) [reply nomad/node_endpoint_test.go:836]: Oh, the register call was above the fold and I missed it somehow. :+1:

File: nomad/node_endpoint.go (hunk 4 above)
Comment (tgross) [reply nomad/node_endpoint.go:1209]: Right, I understand that the comment is still strictly true, but it only partially describes the temporal dependency between the values being applied. The text we have is fine, but expanding it to describe that the status updates won't be applied until after `UpdateAlloc` is called too will make it more obvious what the dependencies are the next time someone comes thru here.

File: nomad/node_endpoint.go (hunk 5 above)
Comment (lgfa29) [reply nomad/node_endpoint.go]: Fixed in https://github.com/hashicorp/nomad/pull/15808/commits/952b9712178d17023dc19cde0dac007d0bf6a421.

File: nomad/node_endpoint_test.go (hunk 12 above)
Comment (lgfa29) [reply nomad/node_endpoint_test.go]: Fixed in https://github.com/hashicorp/nomad/pull/15808/commits/0040e1788581762da90573dd91e9013681227631.

File: nomad/node_endpoint.go (hunk 4 above)
Comment (lgfa29) [reply nomad/node_endpoint.go:1226]: Ohh I see now, you're talking about the comment for `UpdateStatus`, I misunderstood and thought you were talking about the comment `UpdateAlloc` 😅 

I updated the comment in https://github.com/hashicorp/nomad/pull/15808/commits/6e1f1d8c4604bcc06287b788fc056eb3fcc0fd2e to add a bit more details and also an ASCII version of the state diagram above, hope this makes it more clear 👍

Comment (lgfa29) [reply nomad/node_endpoint.go:1229]: Ah we do need to update `UpdateAlloc` 😬 

Updated in https://github.com/hashicorp/nomad/pull/15808/commits/8202f0b592109d835c768eecc8151149b78609c9.

File: nomad/state/state_store_test.go [hunk 13]
```diff
@@ -5089,277 +5089,220 @@ func TestStateStore_UpdateAllocsFromClient(t *testing.T) {
...
+	must.NoError(t, err)
 
 	alloc1.CreateIndex = 1000
 	alloc1.ModifyIndex = 1001
 	alloc1.TaskStates = ts
 	alloc1.ClientStatus = structs.AllocClientStatusFailed
-	if !reflect.DeepEqual(alloc1, out) {
-		t.Fatalf("bad: %#v %#v", alloc1, out)
-	}
+	must.Eq(t, alloc1, out)
```
Comment (lgfa29) [inline nomad/state/state_store_test.go:5230]: @shoenig is `must.Eq` equivalent to `reflect.DeepEqual`?

File: nomad/node_endpoint.go [hunk 14]
```diff
@@ -433,7 +439,24 @@ func (n *Node) deregister(args *structs.NodeBatchDeregisterRequest,
...
+//	── Register ─► init ├─ ready ──► Has allocs? ├─ Yes ─► Allocs updated? │
+//	             └──▲───┘          └─────┬───────┘       └────────┬────────┘
+//	                │                    │                        │
+//	              ready                  └─ No ─┐  ┌─────── Yes ──┘
+//	                │                           │  │
+//	         ┌──────┴───────┐                ┌──▼──▼─┐         ┌──────┐
+//	         │ disconnected ◄─ disconnected ─┤ ready ├─ down ──► down │
+//	         └──────────────┘                └───▲───┘         └──┬───┘
+//	                                             │                │
+//	                                             └──── ready ─────┘
```
Comment (tgross) [inline nomad/node_endpoint.go:459]: :heart_eyes:

File: nomad/node_endpoint.go [hunk 15]
```diff
@@ -1179,8 +1225,8 @@ func (n *Node) UpdateAlloc(args *structs.AllocUpdateRequest, reply *structs.Gene
 	if node == nil {
 		return fmt.Errorf("node %s not found", nodeID)
 	}
-	if node.Status != structs.NodeStatusReady {
-		return fmt.Errorf("node %s is %s, not %s", nodeID, node.Status, structs.NodeStatusReady)
+	if node.UnresponsiveStatus() {
+		return fmt.Errorf("node %s is not allow to update allocs while in status %s", nodeID, node.Status)
```
Comment (tgross) [inline nomad/node_endpoint.go:1229]:
```suggestion
		return fmt.Errorf("node %s is not allowed to update allocs while in status %s", nodeID, node.Status)
```

File: nomad/structs/structs.go (hunk 3 above)
Comment (lgfa29) [reply nomad/structs/structs.go]: Ah good point. Resetting it zero may help to indicate that this field is sort edge triggered. I pushed a commit do just that. Thanks!

File: nomad/state/state_store_test.go (hunk 13 above)
Comment (shoenig) [reply nomad/state/state_store_test.go:5326]: It uses `cmp.Equal` under the hood, which can be configured with `cmp.Options` if you want

https://github.com/google/go-cmp

File: nomad/state/state_store.go [hunk 16]
```diff
@@ -3582,8 +3606,13 @@ func (s *StateStore) UpdateAllocsFromClient(msgType structs.MessageType, index u
 	txn := s.db.WriteTxnMsgT(msgType, index)
 	defer txn.Abort()
 
+	// Capture all nodes being affected. Alloc updates from clients are batched
+	// so this request may include allocs from several nodes.
+	nodeIDs := make(map[string]interface{})
+
 	// Handle each of the updated allocations
 	for _, alloc := range allocs {
+		nodeIDs[alloc.NodeID] = struct{}{}
```
Comment (shoenig) [inline nomad/state/state_store.go:3615]: Seems like this is being used only as a set to track NodeID? If so consider using a `set.Set`

File: nomad/state/state_store_test.go (hunk 13 above)
Comment (lgfa29) [reply nomad/state/state_store_test.go:5326]: Ah thanks!

> Unlike reflect.DeepEqual, unexported fields are not compared by default; they result in panics unless suppressed by using an Ignore option (see cmpopts.IgnoreUnexported) or explicitly compared using the AllowUnexported option.

I think we're OK in this case.
