### PR TITLE
ui: fix bug that prevented files streaming

### LINKED ISSUE #12647: Streaming on alloc's file not working in beta
### Nomad version
1.3-beta

### Operating system and Environment details

Reproed on mac, in both firefox and safari

### Issue

From an allocations log page (/ui/allocations/f6c94f7d-362d-24c3-b3da-e04c3dfc7c74/fs/alloc/logs/server.stdout.0), if I hit the play button to "start stream", the file goes completely blank and no streaming occurs.

This is not the case in 1.2.6 but is the case in 1.3-beta.

### Reproduction steps

* Deploy a job that logs something to standard out `nomad-pack run hello_world --var count=1`
* Go to the allocation log file (note: NOT the task's "logs" tab - interestingly this work fine even though it is very similar functionality). This means going to /ui/allocations/<ALLOC_ID>/fs/alloc/logs and selecting standardout
* Click the play button to start streaming
* Note that the screen goes blank
* Open a separate window on the allocation show page (keep this to the side while "streaming" is happening)
* Restart the allcoation from the show page
* Note that the logs do not update and they stay blank

#### Expected Result

The logs should not go blank and the new logs should stream in

#### Actual Result

The log stays completely blank

### Job file (if appropriate)

`pack run hello_world --var count=1`

### Other Info

I was able to reproduce this bug on 1.3-beta using `make dev` and running Nomad locally.

I kept the 1.3 backend running and then checked out 1.2.6 and ran `USE_MIRAGE=false ember serve`. This made the 1.2.6 UI reach out to the 1.3 backend. Using this setup, I was able to confirm that the issue *did not* repro using the 1.2.6 UI and the new backend. So I beleive I have isolated the issue to a code change that happened in the frontend somewhere between 1.2.6 and 1.3-beta.

In the browser console, I sometimes get "Uncaught DOMException: The operation was aborted." in 1.3-beta, but not always. Regardless of whether or not this error shows up, I see the repro.

### Screenshots

Working in 1.2.6

Working in 1 2 6

Not working in 1.3

Failing in 1 3

### PR DESCRIPTION
**Pull request by lgfa29**
During the Ember dependecy upgrade work,
https://github.com/hashicorp/nomad/commit/ce8c039f4ce7359d60ede5dee36b9cef82
moved the `isSupported` method from using Ember's `reopenClass` to a
getter, but `reopenClass` creates a static method, so the getter must be
static as well.

~I couldn't find a way to test this since the test suite uses a mock object.~
Not true, the mocks are for something else.

Closes #12647

### CODE REVIEW

**Review by philrenaud — APPROVED** [review]

**Review by ChaiWithJai — APPROVED** [review]
Great job

File: ui/app/utils/classes/stream-logger.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ import classic from 'ember-classic-decorator';
 export default class StreamLogger extends EmberObject.extend(AbstractLogger) {
   reader = null;
 
-  get isSupported() {
+  static get isSupported() {
```
Comment (ChaiWithJai) [inline ui/app/utils/classes/stream-logger.js:13]: question: Should we have a test to document and protect this behavior?

Comment (lgfa29) [reply ui/app/utils/classes/stream-logger.js:13]: Yeah, I mentioned in the PR body that 

> I couldn't find a way to test this since the test suite uses a mock object.

But turns out that's not true 😅 

Added a test now.

**Review by ChaiWithJai — APPROVED** [review]
Amazing job
