### PR TITLE
`consul-template`:  revert `function_denylist` logic

### LINKED ISSUE #11923: Unable to get nomad config/get template function_denylist option
@notnoop @tgross hi guys! I made an update for 1.2.4 but got another issue with consul templating:
```
Jan 25 08:44:53 microworker03.te01-shr.nl3 nomad: 2022-01-25T08:44:53.234Z [INFO]  client.alloc_runner.task_runner.task_hook.logmon.nomad: opening fifo: alloc_id=a7c04d65-2f29-c778-c34c-2513d29f25f4 task=worker-mpi-resolver @module=logmon path=/data/nomad/alloc/a7c04d65-2f29-c778-c34c-2513d29f25f4/alloc/logs/.worker-mpi-resolver.stdout.fifo timestamp=2022-01-25T08:44:53.234Z
Jan 25 08:44:53 microworker03.te01-shr.nl3 nomad[4342]: client.alloc_runner.task_runner.task_hook.logmon.nomad: opening fifo: alloc_id=a7c04d65-2f29-c778-c34c-2513d29f25f4 task=worker-mpi-resolver @module=logmon path=/data/nomad/alloc/a7c04d65-2f29-c778-c34c-2513d29f25f4/alloc/logs/.worker-mpi-resolver.stdout.fifo timestamp=2022-01-25T08:44:53.234Z
Jan 25 08:44:53 microworker03.te01-shr.nl3 nomad: 2022-01-25T08:44:53.234Z [INFO]  client.alloc_runner.task_runner.task_hook.logmon.nomad: opening fifo: alloc_id=a7c04d65-2f29-c778-c34c-2513d29f25f4 task=worker-mpi-resolver @module=logmon path=/data/nomad/alloc/a7c04d65-2f29-c778-c34c-2513d29f25f4/alloc/logs/.worker-mpi-resolver.stderr.fifo timestamp=2022-01-25T08:44:53.234Z
Jan 25 08:44:53 microworker03.te01-shr.nl3 nomad[4342]: client.alloc_runner.task_runner.task_hook.logmon.nomad: opening fifo: alloc_id=a7c04d65-2f29-c778-c34c-2513d29f25f4 task=worker-mpi-resolver @module=logmon path=/data/nomad/alloc/a7c04d65-2f29-c778-c34c-2513d29f25f4/alloc/logs/.worker-mpi-resolver.stderr.fifo timestamp=2022-01-25T08:44:53.234Z
Jan 25 08:44:53 microworker03.te01-shr.nl3 nomad: 2022-01-25T08:44:53.965Z [INFO]  agent: (runner) creating new runner (dry: false, once: false)
Jan 25 08:44:53 microworker03.te01-shr.nl3 nomad[4342]: agent: (runner) creating new runner (dry: false, once: false)
Jan 25 08:44:53 microworker03.te01-shr.nl3 nomad: 2022-01-25T08:44:53.966Z [INFO]  agent: (runner) creating watcher
Jan 25 08:44:53 microworker03.te01-shr.nl3 nomad: 2022-01-25T08:44:53.966Z [INFO]  agent: (runner) starting
Jan 25 08:44:53 microworker03.te01-shr.nl3 nomad[4342]: agent: (runner) creating watcher
Jan 25 08:44:53 microworker03.te01-shr.nl3 nomad[4342]: agent: (runner) starting
Jan 25 08:44:54 microworker03.te01-shr.nl3 nomad: 2022-01-25T08:44:54.307Z [INFO]  client.gc: marking allocation for GC: alloc_id=a7c04d65-2f29-c778-c34c-2513d29f25f4
Jan 25 08:44:54 microworker03.te01-shr.nl3 nomad[4342]: client.gc: marking allocation for GC: alloc_id=a7c04d65-2f29-c778-c34c-2513d29f25f4
Jan 25 08:44:58 microworker03.te01-shr.nl3 nomad: 2022-01-25T08:44:58.309Z [WARN]  client.alloc_runner.task_runner.task_hook.logmon.nomad: timed out waiting for read-side of process output pipe to close: alloc_id=a7c04d65-2f29-c778-c34c-2513d29f25f4 task=worker-mpi-resolver @module=logmon timestamp=2022-01-25T08:44:58.309Z
Jan 25 08:44:58 microworker03.te01-shr.nl3 nomad[4342]: client.alloc_runner.task_runner.task_hook.logmon.nomad: timed out waiting for read-side of process output pipe to close: alloc_id=a7c04d65-2f29-c778-c34c-2513d29f25f4 task=worker-mpi-resolver @module=logmon timestamp=2022-01-25T08:44:58.309Z
Jan 25 08:44:58 microworker03.te01-shr.nl3 nomad: 2022-01-25T08:44:58.309Z [WARN]  client.alloc_runner.task_runner.task_hook.logmon.nomad: timed out waiting for read-side of process output pipe to close: alloc_id=a7c04d65-2f29-c778-c34c-2513d29f25f4 task=worker-mpi-resolver @module=logmon timestamp=2022-01-25T08:44:58.309Z
Jan 25 08:44:58 microworker03.te01-shr.nl3 nomad[4342]: client.alloc_runner.task_runner.task_hook.logmon.nomad: timed out waiting for read-side of process output pipe to close: alloc_id=a7c04d65-2f29-c778-c34c-2513d29f25f4 task=worker-mpi-resolver @module=logmon timestamp=2022-01-25T08:44:58.309Z
```
Nomad side:

```
Template failed: /data/nomad/alloc/3a20b272-9965-8c1f-6ab0-c841e303b623/worker-mpi-resolver/local/platformConfig/nl3.tmpl: execute: template: :1:36: executing "" at <plugin "/data/tools/consul.php">: error calling plugin: function is disabled
--


<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">
```

_Originally posted by @bubejur in https://github.com/hashicorp/nomad/issues/11547#issuecomment-1020940729_

### PR DESCRIPTION
**Pull request by DerekStrickland**
Closes #11923

This PR fixes a regression that was introduced in 1.2.4 around the Consul Client Template configuration. The changes in that release erroneously merged user configuration with the default configuration for Consul Template. This resulted in a situation where the user could never override the default function deny list. The default `FunctionDenylist` values should only be applied if the user does not specify that field in their config.

### CODE REVIEW

File: command/agent/config_test.go [hunk 1]
```diff
@@ -1413,39 +1413,79 @@ func TestConfig_LoadConsulTemplateConfig(t *testing.T) {
...
+			&client.ClientTemplateConfig{
+				DisableSandbox:   false,
+				FunctionDenylist: []string{},
+			},
+		},
+		{
+			"test-resources/client_with_function_denylist_empty_string.hcl",
+			&client.ClientTemplateConfig{
+				DisableSandbox:   true,
+				FunctionDenylist: []string{""},
```
Comment (tgross) [inline command/agent/config_test.go:1457]: This feels like a bug to me: when would we ever want this to be the result after a merged configuration? Are we validating it elsewhere?

File: client/config/config.go [hunk 2]
```diff
@@ -405,21 +405,12 @@ func (c *ClientTemplateConfig) Merge(b *ClientTemplateConfig) *ClientTemplateCon
 
 	result.DisableSandbox = b.DisableSandbox
 
-	// Maintain backward compatibility for older clients
-	if len(b.FunctionBlacklist) > 0 {
-		for _, fn := range b.FunctionBlacklist {
-			if !helper.SliceStringContains(result.FunctionBlacklist, fn) {
-				result.FunctionBlacklist = append(result.FunctionBlacklist, fn)
-			}
-		}
```
Comment (tgross) [inline client/config/config.go:414]: Do we only ever call `Merge` when merging onto the default configuration? If not, we're potentially dropping the merged-onto result by doing this, and it doesn't seem to be protecting us from the `[""]` case (see the test below).

File: command/agent/config_test.go (hunk 1 above)
Comment (DerekStrickland) [reply command/agent/config_test.go:1457]: Yeah, it probably is, and I think you commented on the issue about that. Unfortunately, I pulled old code and confirmed that this currently does not fail validation. I added that comment to the issue thread as well.

My two thoughts other than continuing to allow this are either:

- Remove this check and open an issue to validate empty strings (or remove them?)
- Update this PR to validate empty strings (or remove them?)

Thoughts?

Comment (tgross) [reply command/agent/config_test.go:1457]: I'd say let's fix this issue once and for all here instead of trying to do it in another issue and having to touch this code again. There are _two_ issues in #11923, but we're really only discussing one of them.

This is the JSON client configuration block from https://github.com/hashicorp/nomad/issues/11923#issuecomment-1021007928:

```json
"template": {
  "function_denylist": [
    ""
  ]
}
```

This is an operator error: we should either correct it silently or return an error on startup. It's not clear to me at any point in the discussion in #11923 whether this configuration actually worked prior to 1.2.4. Generally speaking we don't silently correct things in the configuration, so my take is that this should blow up so the operator can fix their configuration. Especially because this is a security-related configuration.

The second issue is whether the configuration is being merged correctly with the defaults when we're done. It's not clear to me that the merging bug is a problem at all if the configuration were:

```json
"template": {
  "function_denylist": []
}
```

Because in that scenario the configuration is an empty slice and there's nothing to iterate over during the merge.

File: .changelog/12071.txt [hunk 3]
```diff
@@ -0,0 +1,4 @@
+```release-note:bug
+template: Fixes a bug in config parsing that resulted in the default `function_denylist`
```
Comment (DerekStrickland) [inline .changelog/12071.txt:2]:
```suggestion
template: Fixes a bug in config loading that resulted in the default `function_denylist`
```

**Comment by shoenig** [comment]
@DerekStrickland just double checking I understand - are these all true?

- this is just a reversion of trying to merge `function_denylist`
- merging `function_denylist` only happened with the default denylist, which isn't the correct behavior 
- we're not trying to fix the `[""]` quirk here

**Comment by DerekStrickland** [comment]
> @DerekStrickland just double checking I understand - are these all true?
> 
> * this is just a reversion of trying to merge `function_denylist`
> * merging `function_denylist` only happened with the default denylist, which isn't the correct behavior
> * we're not trying to fix the `[""]` quirk here

Exactly that!

File: .changelog/12071.txt [hunk 4]
```diff
@@ -0,0 +1,4 @@
+```release-note:bug
+template: Fixes a bug in config loading that resulted in the default `function_denylist`
+always being appended to whatever the user specified.
```
Comment (shoenig) [inline .changelog/12071.txt:3]:
```suggestion
template: Fixed a bug where the default `function_denylist` would be appended to a specified list
```

Just trying to reword to keep these down to 1 line

**Review by shoenig — APPROVED** [review]
LGTM
