### PR TITLE
#23671 Added synopsis for operator root and operator gossip command.

### LINKED ISSUE #14881: cli: operator `root` and `gossip` subcommands missing synopsis
### Nomad version
`Nomad v1.4.1 (2aa7e66bdb526e25f59883952d74dad7ea9a014e`

### Issue
When running `nomad operator`, the command output is missing synopsis entries for the `root` and `gossip` subcommands. The `nomad operator root` and `nomad operator gossip` commands also output generic help messages rather than potentially useful detail about the command.

I believe this issue is caused because Nomad does not have implementations of the subcommands `operator root` and `operator gossip` which provide the synopsis and additional help output.

### Reproduction steps
Run the `nomad operator` command.

#### Expected Result
All subcommands including synopsis.

#### Actual Result
```
WARNING! The "nomad operator keygen" command is deprecated. Please use "nomad
operator gossip keyring generate" instead. This command will be removed a
later version of Nomad.

Usage: nomad operator <subcommand> [options]

  Provides cluster-level tools for Nomad operators, such as interacting with
  the Raft subsystem. NOTE: Use this command with extreme caution, as improper
  use could lead to a Nomad outage and even loss of data.

  Please see the individual subcommand help for detailed usage information.

Subcommands:
    api          Query Nomad's HTTP API
    autopilot    Provides tools for modifying Autopilot configuration
    debug        Build a debug archive
    gossip
    keygen       Generates a new encryption key
    keyring      Manages gossip layer encryption keys
    metrics      Retrieve Nomad metrics
    raft         Provides access to the Raft subsystem
    root
    scheduler    Provides access to the scheduler configuration
    snapshot     Saves and inspects snapshots of Nomad server state
```

### LINKED ISSUE #23671: CLI: "operator root" and "operator gossip" commands are missing command file
When running the `nomad operator -h` command, the gossip and root sections are missing their synopsis comment. This is because each of these subcommands does not have a command file, which includes this information. We should add both files with the relevant detail, so the command help output is complete.

```
$ nomad operator -h
Usage: nomad operator <subcommand> [options]

  Provides cluster-level tools for Nomad operators, such as interacting with
  the Raft subsystem. NOTE: Use this command with extreme caution, as improper
  use could lead to a Nomad outage and even loss of data.

  Please see the individual subcommand help for detailed usage information.

Subcommands:
    api             Query Nomad's HTTP API
    autopilot       Provides tools for modifying Autopilot configuration
    client-state    Dump the nomad client state
    debug           Build a debug archive
    gossip
    metrics         Retrieve Nomad metrics
    raft            Provides access to the Raft subsystem
    root
    scheduler       Provides access to the scheduler configuration
    snapshot        Saves and inspects snapshots of Nomad server state
 ```

### PR DESCRIPTION
**Pull request by raj-hegde**
Synopsis comment for both gossip and root section has been added. Added the respective command files for each of the subcommands.

closes #14881
closes #23671

### CODE REVIEW

**Comment by raj-hegde** [comment]
Please give feedback if I did anything wrong.

File: command/operator_gossip.go [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+type OperatorGossipCommand struct {
+	Meta
+}
+
+func (*OperatorGossipCommand) Help() string {
+	helpText := `
+	Usage: nomad operator gossip [options]
+	
+	This command is accessed by using one of the subcommands below.
+	`
```
Comment (jrasell) [inline command/operator_gossip.go:18]: When running the command locally, the output format seemed slightly off. The whitespace suggestion fixes that and the change to the usage keeps more consistency with other commands and correctly shows subcommand expectation. 

```suggestion
Usage: nomad operator gossip <subcommand> [options] [args]
	
  This command is accessed by using one of the subcommands below.
`
```

File: command/operator_gossip.go [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+	return strings.TrimSpace(helpText)
+}
+
+func (*OperatorGossipCommand) Synopsis() string {
+	return "Provides access to the Gossip protocol"
+}
+
+func (f *OperatorGossipCommand) Name() string { return "operator gossip" }
+
+func (f *OperatorGossipCommand) Run(args []string) int {
```
Comment (jrasell) [inline command/operator_gossip.go:28]: The args function parameter is unused, so we can use an underscore to show this is ignored.
```suggestion
func (f *OperatorGossipCommand) Run(_ []string) int {
```

File: command/operator_root.go [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+type OperatorRootCommand struct {
+	Meta
+}
+
+func (*OperatorRootCommand) Help() string {
+	helpText := `
+	Usage: nomad operator root [options]
+
+	This command is accessed by using one of the subcommands below.
+	`
```
Comment (jrasell) [inline command/operator_root.go:18]: When running the command locally, the output format seemed slightly off. The whitespace suggestion fixes that and the change to the usage keeps more consistency with other commands and correctly shows subcommand expectation.

```suggestion
Usage: nomad operator root <subcommand> [options] [args]

  This command is accessed by using one of the subcommands below.
`
```

File: command/operator_root.go [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+	return strings.TrimSpace(helpText)
+}
+
+func (*OperatorRootCommand) Synopsis() string {
+	return "Provides access to root encryption keys"
+}
+
+func (f *OperatorRootCommand) Name() string { return "operator gossip" }
+
+func (f *OperatorRootCommand) Run(args []string) int {
```
Comment (jrasell) [inline command/operator_root.go:29]: The args function parameter is unused, so we can use an underscore to show this is ignored.

```suggestion
func (f *OperatorRootCommand) Run(_ []string) int {
```

File: command/operator_root.go [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+	`
+
+	return strings.TrimSpace(helpText)
+}
+
+func (*OperatorRootCommand) Synopsis() string {
+	return "Provides access to root encryption keys"
+}
+
+func (f *OperatorRootCommand) Name() string { return "operator gossip" }
```
Comment (jrasell) [inline command/operator_root.go:27]: I think this may have been a copy/paste error :D

```suggestion
func (f *OperatorRootCommand) Name() string { return "operator root" }
```

**Review by jrasell — CHANGES_REQUESTED** [review]
Hi @raj-hegde and thank you very much for raising this PR. I have added some minor suggestions for you to look at. Once these are resolved, I will get this PR merged.

**Comment by raj-hegde** [comment]
Hi @jrasell, Thanks for the feedback I'll work on it right away.

**Comment by raj-hegde** [comment]
Hi @jrasell  removed white spaces keeping consistency with other commands and changed the args function operator to underscore.  Also made a changlelog entry.

Any feedback is greatly appreciated.

**Comment by raj-hegde** [comment]
@jrasell, Thank you
