### PR TITLE
consul/connect: avoid warn messages on connect proxy errors

### LINKED ISSUE #10933: connection issues with connect native tasks in bridge networking
As pointed out by @apollo13 in https://github.com/hashicorp/nomad/issues/10804#issuecomment-885793340

```
Jul 23 18:31:58 sfo3 nomad[1297]:     2021-07-23T18:31:58.342Z [WARN]  client.alloc_runner.runner_hook: error proxying from Consul: alloc_id=e39dffd5-b719-f4f2-09ee-891e9d96520a error="write unix /opt/nomad/data/alloc/e39dffd5-b719-f4f2-09ee-891e9d96520a/alloc/tmp/consul_http.sock->@: write: broken pipe" dest=127.0.0.1:8501 src_local=/opt/nomad/data/alloc/e39dffd5-b719-f4f2-09ee-891e9d96520a/alloc/tmp/consul_http.sock src_remote=@ bytes=2466
```

~I believe those errors are coming from the `consul_grpc_sock` hook, which I don't think even needs to be present for non-sidecar using connect tasks? Although it's also suspicious there are connection errors...~

JK it's the `consul_http_sock` hook using shared code from the other one.

### PR DESCRIPTION
**Pull request by shoenig**
When creating a TCP proxy bridge for Connect tasks, we are at the
mercy of either end for managing the connection state. For long
lived gRPC connections the proxy could reasonably expect to stay
open until the context was cancelled. For the HTTP connections used
by connect native tasks, we experience connection disconnects.
The proxy gets recreated as needed on follow up requests, however
we also emit a WARN log when the connection is broken. This PR
lowers the WARN to a TRACE, because these disconnects are to be
expected.

Ideally we would be able to proxy at the HTTP layer, however Consul
or the connect native task could be configured to expect mTLS, preventing
Nomad from MiTM the requests.

We also can't mange the proxy lifecycle more intelligently, because
we have no control over the HTTP client or server and how they wish
to manage connection state.

What we have now works, it's just noisy.

Fixes #10933

### CODE REVIEW

File: client/allocrunner/consul_grpc_sock_hook.go [hunk 1]
```diff
@@ -313,7 +313,8 @@ func proxyConn(ctx context.Context, logger hclog.Logger, destAddr string, conn n
 		defer cancel()
 		n, err := io.Copy(dest, conn)
 		if ctx.Err() == nil && err != nil {
-			logger.Warn("error proxying to Consul", "error", err, "dest", destAddr,
+			// expect disconnects when proxying http
+			logger.Trace("error proxying to Consul", "error", err, "dest", destAddr,
```
Comment (apollo13) [inline client/allocrunner/consul_grpc_sock_hook.go:317]: My initial comment (https://github.com/hashicorp/nomad/issues/10804#issuecomment-885793340) also had logs about this in the other direction (namely consul -> socket). Shouldn't we downgrade the warning on line 335 as well?

Comment (shoenig) [reply client/allocrunner/consul_grpc_sock_hook.go:317]: Good catch!

**Comment by jrasell** [comment]
@notnoop I amended the log lines and changelog message.

**Review by schmichael — APPROVED** [review]
