### PR TITLE
Fix CSITopology matching logic for csi storage driver

### LINKED ISSUE #20094: csi: aws-ebs-csi plugin v1.28.0 fails to place allocations
Starting in v1.28.0, the AWS EBS CSI plugin [introduced a new segment key to the repose of `NodeGetInfo`](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1931). 

When this version of the plugin is used, the Nomad client receives the following accessible topology segments.

```json
"AccessibleTopology": {
    "Segments": {
        "topology.ebs.csi.aws.com/zone": "ca-central-1a",
        "topology.kubernetes.io/zone": "ca-central-1a"
    }
}
```

But dynamic volume creation does not add the `topology.kubernetes.io/zone` key, even if requested.

```json
"Topologies": [
    null,
    {
        "Segments": {
            "topology.ebs.csi.aws.com/zone": "ca-central-1a"
        }
    }
],
```

This causes the volume to fail scheduling because the topology segments are compared with strict equality.
https://github.com/hashicorp/nomad/blob/3193ac204f6564711004e00948e43146ce1399c4/nomad/structs/node.go#L63-L68

Any job that tries to use it will fail placement with a constraint violation.

```
==> 2024-03-07T13:17:59-05:00: Monitoring evaluation "ea69ca5b"
    2024-03-07T13:17:59-05:00: Evaluation triggered by job "mysql"
    2024-03-07T13:18:00-05:00: Evaluation within deployment: "2e1cd256"
    2024-03-07T13:18:00-05:00: Evaluation status changed: "pending" -> "complete"
==> 2024-03-07T13:18:00-05:00: Evaluation "ea69ca5b" finished with status "complete" but failed to place all allocations:
    2024-03-07T13:18:00-05:00: Task Group "mysql" (failed to place 1 allocation):
      * Constraint "did not meet topology requirement": 1 nodes excluded by filter
    2024-03-07T13:18:00-05:00: Evaluation "c59054f1" waiting for additional capacity to place remainder
```

I've skimmed the spec a few times, but it's not clear to me how to handle this scenario. 

As pointed out in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/729#issuecomment-1984130759, Kubernetes ignores additional node segments, so the additional segments in the node may be safe to ignore.

### Reproduction steps

1. Create an SSH key on AWS (if you don't have one already).
2. Clone https://gist.github.com/lgfa29/b707d56ace871602cb4955df2a1afad0
    ```console
    git clone https://gist.github.com/b707d56ace871602cb4955df2a1afad0.git
    ```
3. Enter the directory and provision the infrastructure with Terraform.
    ```console
    cd b707d56ace871602cb4955df2a1afad0
    terraform init
    terraform apply 
    ```
4. Enter your SSH key name and approve the plan.
5. Run the `mysql.nomad.hcl` job.
    ```console
    NOMAD_ADDR=$(terraform output -raw nomad_addr) nomad run mysql.nomad.hcl
    ```

#### Expected Result

Job starts successfully. 

#### Actual Result

Job fails placement with constraint error:

```
Constraint "did not meet topology requirement": 1 nodes excluded by filter
```

### PR DESCRIPTION
**Pull request by thefallentree**
### Description

CSI volume is created with following topology
```
  "Topologies": [
        null,
        {
            "Segments": {
                "topology.kubernetes.io/zone": "us-east-1a"
            }
        }
    ],
```

and Node Accessible Topology is reported as 

```
  "6befce82-c4e5-8509-55ad-3b69bde1fa22": {
            "AllocID": "b6b6f136-d4c4-691e-47b6-330e1fbf4c4f",
            "HealthDescription": "healthy",
            "Healthy": true,
            "NodeInfo": {
                "AccessibleTopology": {
                    "Segments": {
                        "topology.kubernetes.io/zone": "us-east-1a",
                        "kubernetes.io/os": "linux",
                        "topology.ebs.csi.aws.com/zone": "us-east-1a"
                    }
                },
                "ID": "i-05feecab254e44c60",
                "MaxVolumes": 26,
                "RequiresNodeStageVolume": true,
                "SupportsCondition": false,
                "SupportsExpand": true,
                "SupportsStats": true
            },
            "PluginID": "aws-ebs",
            "RequiresControllerPlugin": true,
            "RequiresTopologies": true,
            "UpdateTime": "2024-11-20T21:41:43.593062188Z"
        },
```

The current logic assume they completely match, where the accessible topology's Segements just need to be a  superset of the volume topology's Segements

Up until EBS CSI driver version < 1.26.1  , the reported value matches exactly, and after v1.27.0 it has been broken since.

### Testing & Reproduction steps

without this patch , the e2e test for csi driver with a ebs-csi driver > 1.26.1 will fail.

### Links

fix #20094

### Contributor Checklist
- [x] **Changelog Entry** If this PR changes user-facing behavior, please generate and add a
  changelog entry using the `make cl` command.
- [X] **Testing** Please add tests to cover any new functionality or to demonstrate bug fixes and
  ensure regressions will be caught.
- [ ] **Documentation** If the change impacts user-facing functionality such as the CLI, API, UI,
  and job configuration, please update the  Nomad website documentation to reflect this. Refer to
  the [website README](../website/README.md) for docs guidelines. Please also consider whether the
  change requires notes within the [upgrade guide](../website/content/docs/upgrade/upgrade-specific.mdx).

### Reviewer Checklist
- [ ] **Backport Labels** Please add the correct backport labels as described by the internal
  backporting document.
- [ ] **Commit Type** Ensure the correct merge method is selected which should be "squash and merge"
  in the majority of situations. The main exceptions are long-lived feature branches or merges where
  history should be preserved.
- [ ] **Enterprise PRs** If this is an enterprise only PR, please add any required changelog entry
  within the public repository.

### CODE REVIEW

File: nomad/structs/node.go [hunk 1]
```diff
@@ -61,11 +61,18 @@ func (t *CSITopology) Copy() *CSITopology {
 	}
 }
 
-func (t *CSITopology) Equal(o *CSITopology) bool {
+func (t *CSITopology) EqualOrContains(o *CSITopology) bool {
```
Comment (tgross) [inline nomad/structs/node.go:64]: As shown in the test outputs, this no longer compiles because there are other callers of `Equal`. The `TopologyRequest.Equal` can't use the logic change you've made here either, as it's used to detect validity of changes in the volume specification. So we probably want to break out a `Contains` method from the `Equal` method.

A logic change like this should almost certainly include a change to tests, so once you've got the code compiling let's add that too.

**Review by tgross — CHANGES_REQUESTED** [review]
Hi @thefallentree! Thanks for this PR. In addition to resolving the compilation errors and the items I noted in the comments, please run `make cl` to add a changelog entry.

File: nomad/structs/node.go (hunk 1 above)
Comment (thefallentree) [reply nomad/structs/node.go:72]: Ok, I restored the Equal() function.  Do you want me to add a Unit test for EqualOrContains() method? It's funtionality should be covered by the e2e tests already.

Comment (tgross) [reply nomad/structs/node.go:71]: > It's funtionality should be covered by the e2e tests already.

While that's true, E2E takes >1hr to run and are challenging to debug, whereas a unit test could give us confidence in any minor changes very cheaply.

I'd also rename this to `Contains`

**Review by tgross — CHANGES_REQUESTED** [review]

**Review by tgross — APPROVED** [review]
Thanks @thefallentree! 

I've push a small commit to make the changelog message applicable to more users, and tidied up some style items in the unit test (we're trying to get rid of `testify` on Nomad). Once CI is green, I'll merge this and get it backported.
