### PR TITLE
Fix IPv6 advertise addresses

### LINKED ISSUE #1318: Nomad does not correctly register services when IPv6 addresses are advertised
### Nomad version
Nomad v0.4.0-dev ('bc09a0444722617a3a0ee0daa28d24b93d9d3e5b+CHANGES')

### Operating system and Environment details
CentOS 7

### Issue
```
advertise {
    http = "[2001:db8:a0b:12f0::1]:4646"
}
```

Will register in Consul as 
`:0`

Leading to several (minor) errors and unexpected behaviours

### PR DESCRIPTION
**Pull request by 42wim**
Fixes #1318 by making sure it uses the correct syntax for IPv6 addresses. 
Adds 2 helper functions

### CODE REVIEW

File: command/agent/util.go [hunk 1]
```diff
@@ -44,3 +44,23 @@ func ipOfDevice(name string) (net.IP, error) {
 	}
 	return nil, fmt.Errorf("no ips were detected on the interface: %v", name)
 }
+
+// isIPV6 checks if the IP address is an IPv6 address
+func isIPV6(ip string) bool {
```
Comment (diptanu) [inline command/agent/util.go]: Please add a test.

File: command/agent/util.go [hunk 2]
```diff
@@ -44,3 +44,23 @@ func ipOfDevice(name string) (net.IP, error) {
...
+		// ipv6
+		if addr.To4() == nil {
+			return true
+		}
+	}
+	return false
+}
+
+// joinIPPort joins ip and port correctly for IPv4 (ip:port) or IPv6 ([ip]:port)
+func joinIPPort(ip string, port int) string {
```
Comment (diptanu) [inline command/agent/util.go]: Please add a test

Comment (diptanu) [inline command/agent/util.go]: Also why not use https://golang.org/pkg/net/#JoinHostPort ?

**Comment by diptanu** [comment]
@42wim Thanks for the PR! I have made one comment. Once you update the PR, we can merge this.

File: command/agent/util.go (hunk 2 above)
Comment (42wim) [inline command/agent/util.go]: Because I didn't think of it :-)
That's the better option, no extra helpers needed (but strconv.Itoa(everyport).
Should I rebase using JoinHostPort?

Comment (diptanu) [inline command/agent/util.go]: Cool! Just update your branch with the JoinHostPort, and I think the PR would automatically get updated.

**Comment by 42wim** [comment]
Ok, I updated it (without rebase). 
Unrelated but I saw that the one function ```ipOfDevice``` in ```command/agent/util.go``` isn't used anywhere, that file could be removed.

**Comment by 42wim** [comment]
This also seems to fix #1349

**Comment by dadgar** [comment]
Nice thanks!
