### PR TITLE
Include the _ prefix separator in both regexes

### LINKED ISSUE #5745: Possible 0.9.2 UI Bug
I built a test release of the current master branch and deployed it - I believe everything in the scheduler is working as expected but I've encountered a bug in the UI. Seems like it's trying to index into a null array, though the XHR requests to `/v1/jobs` is returning populated arrays . I get this from firefox:

```
TypeError: t.match(...) is null[Learn More] nomad-ui-3862716e00185c2061ad87166e17726a.js:425:336
    a https://nomad.example.com/ui/assets/nomad-ui-3862716e00185c2061ad87166e17726a.js:425
    reduce self-hosted:359
    optionsPrefix https://nomad.example.com/ui/assets/nomad-ui-3862716e00185c2061ad87166e17726a.js:425
    get https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:3379
    ne https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:3296
    compute https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2825
    value https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2821
    value https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2492
    bt https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2961
    create https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2974
    <anonymous> https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2259
    evaluate https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2136
    evaluateSyscall https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2395
    evaluateInner https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2387
    evaluateOuter https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2387
    next https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2513
    execute https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2512
    handleException https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2453
    handleException https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2465
    throw https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2448
    evaluate https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2200
    execute https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2448
    rerender https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2466
    render https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:3004
    C https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:3257
    _renderRoots https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:3025
    _renderRootsTransaction https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:3030
    _revalidate https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:3032
    invoke https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2607
    flush https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2600
    flush https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2611
    _end https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2658
    end https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2624
    _run https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2659
    _join https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2658
    join https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:2635
    h https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:1817
    success https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:7409
    u https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:1283
    fireWith https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:1284
    O https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:1556
    n https://nomad.example.com/ui/assets/vendor-121fbe0a713949ae14198625db799c6f.js:1566
```

and this from chrome:

```
Uncaught TypeError: Cannot read property '1' of null
    at nomad-ui-3862716e00185c2061ad87166e17726a.js:425
    at Array.reduce (<anonymous>)
    at n.<anonymous> (nomad-ui-3862716e00185c2061ad87166e17726a.js:425)
    at n.get (vendor-121fbe0a713949ae14198625db799c6f.js:3379)
    at ne (vendor-121fbe0a713949ae14198625db799c6f.js:3296)
    at t.compute (vendor-121fbe0a713949ae14198625db799c6f.js:2825)
    at t.value (vendor-121fbe0a713949ae14198625db799c6f.js:2821)
    at e.value (vendor-121fbe0a713949ae14198625db799c6f.js:2492)
    at bt (vendor-121fbe0a713949ae14198625db799c6f.js:2961)
    at r.create (vendor-121fbe0a713949ae14198625db799c6f.js:2974)
```

Results in a blank screen at `/ui/jobs`. To build this release, I used `make prerelease` followed by `make release` in the vagrant VM. I had to do a bit of work to get everything actually working in that VM so it's totally possible I messed something up, just wanted to call this out just in case.

### PR DESCRIPTION
**Pull request by DingoEatingFuzz**
And include all prefix types in the test data.

Fixes #5745

### CODE REVIEW

File: ui/app/controllers/jobs/index.js [hunk 1]
```diff
@@ -61,11 +61,7 @@ export default Controller.extend(Sortable, Searchable, {
 
   optionsDatacenter: computed('visibleJobs.[]', function() {
     const flatten = (acc, val) => acc.concat(val);
-    const allDatacenters = new Set(
-      this.visibleJobs
-        .mapBy('datacenters')
-        .reduce(flatten, [])
-    );
+    const allDatacenters = new Set(this.visibleJobs.mapBy('datacenters').reduce(flatten, []));
```
Comment (backspace) [inline ui/app/controllers/jobs/index.js]: Maybe this is an extraneous change?

Comment (DingoEatingFuzz) [reply ui/app/controllers/jobs/index.js]: As you suspected, this was an autofix. Now that husky is working again this shouldn't happen anymore 💃

File: ui/app/controllers/jobs/index.js [hunk 2]
```diff
@@ -88,7 +84,7 @@ export default Controller.extend(Sortable, Searchable, {
     const allNames = this.visibleJobs.mapBy('name');
     const nameHistogram = allNames.reduce((hist, name) => {
       if (hasPrefix.test(name)) {
-        const prefix = name.match(/(.+?)[-.]/)[1];
+        const prefix = name.match(/(.+?)[-._]/)[1];
```
Comment (johncowen) [inline ui/app/controllers/jobs/index.js]: Hey, sorry late to the game here, just noticed a tinsy tiny nitpick, but potentially important for someone skimming the code.

Line 79

```javascript
// A prefix is defined as the start of a job name up to the first - or .
// ex: mktg-analytics -> mktg, ds.supermodel.classifier -> ds
```

^ that specifically states `- or .`, if you are going to keep the comment here I'd probably update that to include the `_`

Actually just looking further while I'm here. Hoisting the at least second regex out of the `reduce` hotpath might also be an option here. Not sure how hot this can get, if at all, but I think this is compiling a new regex for every loop? Usually I try and hoist all RegEx patterns into the top level scope as they can be a 'performance thing'. It might be nice to have them literally one after the other in the code also, that would make any future tiny differences like this even more unlikely? (Not sure if you can make a pattern you can reuse here, but you could also dynamically make a RegExp() that used the same `[.-_]`, if you like that. Theoretically slower than the literal, but if you are only doing it once maybe it doesn't matter)

Anyway, all just suggestions!
