### PR TITLE
CSI snapshot list: do not shorten snapshot ID

### LINKED ISSUE #10660: Nomad CSI snapshot list: do not shorten snapshot ID
### Nomad version
```
[root@ip-70-0-14-127 demo]# nomad version
Nomad v1.1.0 (2678c3604bc9530014208bc167415e167fd440fc)
```

### Operating system and Environment details
CentOS Linux 7 (Core)

### Issue
"nomad volume snapshot delete" is documented to take a snapshot id:
```
[root@ip-70-0-14-127 demo]# nomad volume snapshot delete 
This command takes two arguments: <plugin id> <snapshot id>
For additional help try 'nomad volume snapshot delete -help'
```

However, after trying a few combinations, I noticed the delete only goes through when a snapshot name is provided.

**Update:** After looking into this more, I found that the snapshot id provided in `nomad volume snapshot list` is shortened to  12 characters. I was passing this shortened ID to `nomad volume snapshot delete`, which was not correct. Our snapshot ids are 18 characters. By coincidence, our CSI driver supports deleting snapshots by both name and ID, which explains the deletion succeeding via snapshot name.

Unless I'm missing something, there isn't a way to find the full snapshot id via `nomad volume snapshot list`. Perhaps a `nomad volume snapshot list -json` would be useful here? Similar to `nomad volume status -json`?

### Reproduction steps
An example like the follow could allow users to become confused as to why their snapshots aren't being deleted:
```
[root@ip-70-0-14-127 demo]# nomad volume snapshot create pxvol1 snap2
Snapshot ID   Volume ID     Size    Create Time           Ready?
111599152205  430708984379  10 GiB  1970-01-01T00:00:01Z  true
[root@ip-70-0-14-127 demo]# nomad volume snapshot list
Snapshot ID   Volume ID     Size    Create Time  Ready?
111599152205  430708984379  10 GiB  <none>       true
729104150236  338826921232  10 GiB  <none>       true
[root@ip-70-0-14-127 demo]# nomad volume snapshot delete portworx 111599152205
[root@ip-70-0-14-127 demo]# nomad volume snapshot list
Snapshot ID   Volume ID     Size    Create Time  Ready?
111599152205  430708984379  10 GiB  <none>       true
729104150236  338826921232  10 GiB  <none>       true
[root@ip-70-0-14-127 demo]# nomad volume snapshot delete portworx snap2
[root@ip-70-0-14-127 demo]# nomad volume snapshot list
Snapshot ID   Volume ID     Size    Create Time  Ready?
729104150236  338826921232  10 GiB  <none>       true
```

#### Expected Result

~~`nomad volume snapshot delete` docs and CLI help should reflect that this command takes a snapshot name~~
~~OR~~
~~`nomad volume snapshot delete`  implementation should instead take a snapshot_id as documented~~

`nomad volume snapshot list` should support a `-json` option.

#### Actual Result
~~`nomad volume snapshot delete` only works when a snapshot name is passed.~~

Option is not supported yet

### Job file (if appropriate)
n/a

### Nomad Server logs (if appropriate)
n/a

### Nomad Client logs (if appropriate)
n/a

### PR DESCRIPTION
**Pull request by ggriffiths**
Fixes #10660
Signed-off-by: Grant Griffiths <ggriffiths@purestorage.com>

### CODE REVIEW

File: command/volume_snapshot_list.go [hunk 1]
```diff
@@ -148,14 +148,10 @@ func (c *VolumeSnapshotListCommand) Run(args []string) int {
...
 func csiFormatSnapshots(snapshots []*api.CSISnapshot, verbose bool) string {
 	rows := []string{"Snapshot ID|Volume ID|Size|Create Time|Ready?"}
-	length := 12
-	if verbose {
-		length = 30
-	}
 	for _, v := range snapshots {
 		rows = append(rows, fmt.Sprintf("%s|%s|%s|%s|%v",
-			limit(v.ID, length),
-			limit(v.ExternalSourceVolumeID, length),
```
Comment (tgross) [inline command/volume_snapshot_list.go:158]: The external volume ID can be _extremely_ long for some cloud providers (ex. Azure) and I don't think it's required for Nomad CLI operations the way the snapshot ID is. It might be worth having the limit removed by the `-verbose` flag instead of by default for this field.

**Review by tgross — CHANGES_REQUESTED** [review]

File: command/volume_snapshot_list.go (hunk 1 above)
Comment (ggriffiths) [reply command/volume_snapshot_list.go:158]: Makes sense, I've updated this to still shorten the `ExternalSourceVolumeID`.

**Review by tgross — APPROVED** [review]

**Comment by tgross** [comment]
LGTM!
