### PR TITLE
UI: Update to v4 of Ember Power Select

### LINKED ISSUE #10146: Nomad  UI errors in 1.0.4 when toggling namespaces.
### Nomad version
Nomad v1.0.4 (9294f35f9aa8dbb4acb6e85fa88e3e2534a3e41a)

### Operating system and Environment details
Debian 10

### Issue

After updating to nomad 1.0.4 I get this when I switch between namespace:
```
unreachable code after return statement vendor-0b0c112f994af33e399d2b1c0a1b6634.js:7093
Uncaught (in promise) TypeError: t is null
    animateOut https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:7154
    destroyModifier https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:7089
    Qt https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1579
    invoke https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4131
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4123
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4134
    _end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4186
    _boundAutorunEnd https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4143
    promise callback*n/< https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4109
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3032
    _scheduleAutorun https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4200
    _end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4187
    _boundAutorunEnd https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4143
    promise callback*n/< https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4109
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3032
    _scheduleAutorun https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4200
    _end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4187
    _boundAutorunEnd https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4143
    promise callback*n/< https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4109
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3032
    _scheduleAutorun https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4200
    _ensureInstance https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4198
    ensureInstance https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4183
    <anonymous> https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1527
    A https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4016
    N https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1844
    L https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1848
    Ee https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1901
    updateState https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8290
    handleClose https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8263
    close https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:7178
    _choose https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8264
    r https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8318
    addHandlers https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8319
    addHandlers https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8319
    installModifier https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:7081
    install https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1581
    untrack https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3974
    install https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1581
    commit https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3564
    commit https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3567
    inTransaction https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3422
    _renderRoots https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1717
    _renderRootsTransaction https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1722
vendor-0b0c112f994af33e399d2b1c0a1b6634.js:7154:139
Uncaught TypeError: t is null
    animateOut https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:7154
    destroyModifier https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:7089
    Qt https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1579
    invoke https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4131
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4123
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4134
    _end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4186
    end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4147
    _run https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4188
    _join https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4187
    join https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4158
    d https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3035
    Ae https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1442
    a https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:2961
    Ae https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1442
    r https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1652
    _select https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8264
    _choose https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8264
    r https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8318
    addHandlers https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8319
    addHandlers https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8319
    installModifier https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:7081
    install https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1581
    untrack https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3974
    install https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1581
    commit https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3564
    commit https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3567
    inTransaction https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3422
    _renderRoots https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1717
    _renderRootsTransaction https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1722
    _revalidate https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1722
    invoke https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4131
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4123
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4134
    _end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4186
    _boundAutorunEnd https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4143
    promise callback*n/< https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4109
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3032
    _scheduleAutorun https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4200
    _end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4187
    _boundAutorunEnd https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4143
    promise callback*n/< https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4109
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3032
    _scheduleAutorun https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4200
    _end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4187
    _boundAutorunEnd https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4143
    promise callback*n/< https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4109
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3032
    _scheduleAutorun https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4200
    _ensureInstance https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4198
    ensureInstance https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4183
    <anonymous> https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1527
    A https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4016
    N https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1844
    L https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1848
    Ee https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1901
    updateState https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8290
    _resetHighlighted https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8278
    handleOpen https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8262
    open https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:7176
    toggle https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:7182
    handleMouseDown https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:7165
    ar https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1595
    install https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1599
    commit https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3564
    commit https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3567
    inTransaction https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3422
    _renderRoots https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1717
    _renderRootsTransaction https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1722
    _revalidate https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1722
    invoke https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4131
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4123
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4134
vendor-0b0c112f994af33e399d2b1c0a1b6634.js:7154:139
UNRECOVERABLE ERROR: TypeError: this.element is null
    renderChart https://nomad.infra.bap.co.at/ui/assets/nomad-ui-89241c65904310d44e72c37c2050fa4c.js:265
    updateChart https://nomad.infra.bap.co.at/ui/assets/nomad-ui-89241c65904310d44e72c37c2050fa4c.js:265
    m https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1799
    l https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1806
    flushAsyncObservers https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1807
    flushAsyncObservers https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1806
    flushAsyncObservers https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1805
    setup https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:2162
    s https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4504
    routeEnteredOrUpdated https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4505
    setupContexts https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4502
    finalizeTransition https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4494
    promise https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4488
    g https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4564
    v https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4562
    invoke https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4131
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4123
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4134
    _end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4186
    _boundAutorunEnd https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4143
    promise callback*n/< https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4109
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3032
    _scheduleAutorun https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4200
    _ensureInstance https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4198
    schedule https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4160
    <anonymous> https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:2392
    f https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4560
    d https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4558
    x https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4582
    onload https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4701
    g https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4701
    x https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4582
    x https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4582
    g https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4701
    text https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4713
    determineBodyPromise https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:6203
    ajax https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:6298
    g https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4564
    v https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4562
    invoke https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4131
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4123
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4134
    _end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4186
    _boundAutorunEnd https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4143
    promise callback*n/< https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4109
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3032
    _scheduleAutorun https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4200
    _ensureInstance https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4198
    schedule https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4160
    <anonymous> https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:2392
    f https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4560
    c https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4557
    d https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4560
    x https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4582
    onload https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4749
    setTimeout handler*S/</l.onload https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4749
    S https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4744
    x https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4582
    x https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4582
    S https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4741
    _fetchRequest https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:6309
    ajax https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:6298
    ajax https://nomad.infra.bap.co.at/ui/assets/nomad-ui-89241c65904310d44e72c37c2050fa4c.js:107
    findAll https://nomad.infra.bap.co.at/ui/assets/nomad-ui-89241c65904310d44e72c37c2050fa4c.js:113
    findAll https://nomad.infra.bap.co.at/ui/assets/nomad-ui-89241c65904310d44e72c37c2050fa4c.js:95
    s https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:6762
    g https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4564
    b https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4571
    invoke https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4131
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4123
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4134
    _end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4186
    end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4147
    _run https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4188
    _join https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4187
    join https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4158
    d https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3035
    Ae https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1442
    a https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:2961
    Ae https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1442
    r https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1652
    _select https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8264
    _choose https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8264
    r https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:8318
nomad-ui-89241c65904310d44e72c37c2050fa4c.js:848:878
Uncaught (in promise) TypeError: this.element is null
    renderChart https://nomad.infra.bap.co.at/ui/assets/nomad-ui-89241c65904310d44e72c37c2050fa4c.js:265
    updateChart https://nomad.infra.bap.co.at/ui/assets/nomad-ui-89241c65904310d44e72c37c2050fa4c.js:265
    m https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1799
    l https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:1806
    invoke https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4131
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4123
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4134
    _end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4186
    _boundAutorunEnd https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4143
    promise callback*n/< https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4109
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3032
    _scheduleAutorun https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4200
    _end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4187
    _boundAutorunEnd https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4143
    promise callback*n/< https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4109
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3032
    _scheduleAutorun https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4200
    _end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4187
    _boundAutorunEnd https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4143
    promise callback*n/< https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4109
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3032
    _scheduleAutorun https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4200
    _ensureInstance https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4198
    schedule https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4160
    <anonymous> https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:2392
    f https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4560
    d https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4558
    x https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4582
    onload https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4701
    g https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4701
    x https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4582
    x https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4582
    g https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4701
    text https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4713
    determineBodyPromise https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:6203
    ajax https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:6298
    g https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4564
    v https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4562
    invoke https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4131
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4123
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4134
    _end https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4186
    _boundAutorunEnd https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4143
    promise callback*n/< https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4109
    flush https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:3032
    _scheduleAutorun https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4200
    _ensureInstance https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4198
    schedule https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:4160
    <anonymous> https://nomad.infra.bap.co.at/ui/assets/vendor-0b0c112f994af33e399d2b1c0a1b6634.js:2392
nomad-ui-89241c65904310d44e72c37c2050fa4c.js:265:388
```

### Reproduction steps

Switch around between namespace

#### Expected Result

No error

#### Actual Result

Initially just console errors and then 
image

### PR DESCRIPTION
**Pull request by backspace**
This closes #10146.

Because of cibernox/ember-power-select#1203, which documents
the current impossibility of attaching test selectors to a
PowerSelect invocation, this uses test selectors on parent
containers instead, occasionally adding wrappers when needed.
I chose to leave the existing test selectors in the hopes that
we can return to using them eventually, but I could easily
remove them if it seems like extra noise now.

Presumably for the same reason, `@class` no longer works, so
this adjusts the scoping of global search CSS to preserve the style
of the search control.

I also included an update to the latest version of
ember-test-selectors, since we were far behind and I tried
that before finding the aforelinked issue.

Finally, this replaces ember-cli-uglify with ember-cli-terser to address
production build failures as described at ember-cli/ember-cli#9290.

### CODE REVIEW

File: ui/tests/unit/utils/stream-logger-test.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ module('Unit | Util | StreamLogger', function() {
     });
 
     logger.start();
-    logger.stop();
+    await logger.stop();
```
Comment (DingoEatingFuzz) [inline ui/tests/unit/utils/stream-logger-test.js:16]: Oops. How long has this latent race condition been around?

**Review by DingoEatingFuzz — APPROVED** [review]
Lgtm. Thanks for dealing with this hairy upgrade!

I played around with the facets too and I couldn't reproduce the `appendChild` error that was being thrown.

File: ui/tests/unit/utils/stream-logger-test.js (hunk 1 above)
Comment (backspace) [reply ui/tests/unit/utils/stream-logger-test.js:16]: indeed 😳
