### PR TITLE
client: enable cpuset support for cgroups.v2

### LINKED ISSUE #11289: cpuset support with cgroupsv2
Nomad 1.1 [Reserved CPUs](https://www.hashicorp.com/blog/managing-resources-for-workloads-with-nomad-1-1#reserved-cpu-cores) feature relies on cpuset cgroup capabilities, and uses a technique no longer supported in cgroup-v2.

The reserved CPUs are dedicated to their tasks - other tasks may not access them. Nomad achieve this by using the `cpuset` cgroups controller. Nomad creates a `/nomad/shared` cgroup for all non-reserving tasks, which starts unconstrained. If a reserved CPU task is placed on the host, Nomad removes the reserved core from this shared cgroup - constraining already running tasks from running on the core.

Thus, non-reserving tasks belong to at least two cgroups: the `nomad/shared` cpuset cgroup as well as cgroup that's created by the task driver. For example, a docker task process has the following cgroup assignment (note the `cpuset` value):

```
cat /proc/11050/cgroup
12:devices:/docker/10234c078fce6da0cb3e58c9da71a01852f0241bd5ce6b0e9fd19ec296e1aea0
11:pids:/docker/10234c078fce6da0cb3e58c9da71a01852f0241bd5ce6b0e9fd19ec296e1aea0
10:net_cls,net_prio:/docker/10234c078fce6da0cb3e58c9da71a01852f0241bd5ce6b0e9fd19ec296e1aea0
9:freezer:/docker/10234c078fce6da0cb3e58c9da71a01852f0241bd5ce6b0e9fd19ec296e1aea0
8:rdma:/
7:perf_event:/docker/10234c078fce6da0cb3e58c9da71a01852f0241bd5ce6b0e9fd19ec296e1aea0
6:cpuset:/nomad/shared
5:cpu,cpuacct:/docker/10234c078fce6da0cb3e58c9da71a01852f0241bd5ce6b0e9fd19ec296e1aea0
4:memory:/docker/10234c078fce6da0cb3e58c9da71a01852f0241bd5ce6b0e9fd19ec296e1aea0
3:blkio:/docker/10234c078fce6da0cb3e58c9da71a01852f0241bd5ce6b0e9fd19ec296e1aea0
2:hugetlb:/docker/10234c078fce6da0cb3e58c9da71a01852f0241bd5ce6b0e9fd19ec296e1aea0
1:name=systemd:/docker/10234c078fce6da0cb3e58c9da71a01852f0241bd5ce6b0e9fd19ec296e1aea0
0::/system.slice/containerd.service
```

This technique relies on cgroup-v1 hierarchy flexibility. `cgroup-v2` no longer permits a process to belong to multiple cgroups! We will need to rethink this mechanism.

>  Cgroups v2 unified hierarchy
>       In cgroups v1, the ability to mount different controllers against
>       different hierarchies was intended to allow great flexibility for
>       application design.  In practice, though, the flexibility turned
>       out to be less useful than expected, and in many cases added
>       complexity.  Therefore, in cgroups v2, all available controllers
>       are mounted against a single hierarchy.

From https://man7.org/linux/man-pages/man7/cgroups.7.html

Oddly enough, Nomad uses the same pattern and creates a cpuset cgroup for reserving tasks, instead of setting cpuset cgroup in the driver-managed cgroup. I'm unsure of what the motivation; if deemed unnecessary, we can have the drivers set the cpuset settings appropriately.

## Resources

* [Control Group v2 administrator guide](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html)
* [Control Group v2 man page](https://man7.org/linux/man-pages/man7/cgroups.7.html)
* [FODSEM talk slides](https://chrisdown.name/talks/cgroupv2/cgroupv2-fosdem.pdf)

### LINKED ISSUE #11705: Nomad CPU pinning is moving the container after it's created.
### Nomad version
1.1.6 - Enterprise

### Issue
When the [number of `cores` is defined in the `resources` stanza](https://www.nomadproject.io/docs/job-specification/resources#cores-1), using the docker driver, this is only applied after the container has already started and is not being set for all of the PIDs of the container.

This is a problem, because containers that have more than one process may get spawned before Nomad moves PID 1 to `/sys/fs/cgroup/cpuset/nomad/reserved/, which means the sub-processes may not get the assigned cores.

In this use case, one of the sub-processes pins threads to the available cores, which ends up getting “out-of-sync” because the assigned cores are changed after start-up.

### Reproduction steps
Start a Nomad task with
A docker container having more than one process
Set the number of reserved cores in the resources stanza

#### Expected Result
Task should start directly under `/nomad/reserved`

#### Actual Result
Task starts under `/nomad/shared/<alloc ID>/<task name>` and then gets moved to `/nomad/reserved/<alloc ID>/<task name>`

### PR DESCRIPTION
**Pull request by shoenig**
This PR introduces support for using Nomad on systems with cgroups v2 [1]
enabled as the cgroups controller mounted on `/sys/fs/cgroups`. Newer Linux
distros like Ubuntu 21.10 are shipping with cgroups v2 only, causing problems
for Nomad users.

Nomad mostly "just works" with cgroups v2 due to the indirection via libcontainer,
but not so for managing `cpuset` cgroups. Before, Nomad has been making use of
a feature in v1 where a PID could be a member of more than one cgroup. In v2
this is no longer possible, and so the logic around computing cpuset values
must be modified. When Nomad detects v2, it now manages cpuset values in-process,
rather than making use of cgroup heirarchy inheritence via shared/reserved
parents.

Nomad will only activate the v2 logic when it detects cgroups2 is mounted at
`/sys/fs/cgroups`. This means on systems running in hybrid mode with cgroups2
mounted at `/sys/fs/cgroups/unified` (as is typical) Nomad will continue to
use the v1 logic, and should operate as before. Systems that do not support
cgroups v2 are also not affected.

When v2 is activated, Nomad will create a parent called `nomad.slice` (unless
otherwise configured in Client conifg), and create cgroups for tasks using
naming convention `<allocID>-<task>.scope`. These follow the naming convention
set by systemd and also used by Docker when cgroups v2 is detected.

Client nodes now export a new fingerprint attribute, `unique.cgroup.version`
which will be set to `"v1"` or `"v2"` to indicate the cgroups regime in use by
Nomad.

The new cpuset management strategy fixes #11705, where docker tasks that
spawned processes on startup would "leak" and make use of forbidden cpu cores. 
With the v2 manager, the PIDs are started in the cgroup they will always live in, and 
thus the source of the leak is eliminated.

[1] https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html

Closes #11289
Fixes #11705 #11773 #11933

Review Notes:
- Still missing CI coverage - original plan was to coerce Nomad into using v2 in hybrid mode, but turns out `libcontainer` isn't going to allow that. Presumably we'll be able to use GHA `ubuntu-22.04` runners in April. See manual testing in comments.
- Existing v1 manager logic is basically untouched, but moved around a lot, and driver tests are now entangled with v1/v2 switches.
- Driver tests could use an overhaul, it's surprisingly difficult to predict the code path involved in a test
- Still loose ends for complete cgroups v2 support on non-hybrid systems
  - https://github.com/hashicorp/nomad/issues/12351
  - https://github.com/hashicorp/nomad/issues/12348
- Still need to update drivers we know about
  - https://github.com/hashicorp/nomad-driver-podman/issues/160 (podman)
  - https://github.com/shoenig/nomad-driver-containerd/commit/34a9526bc9a922ac1d50773c5337dd08c9bde04f (containerd)

### CODE REVIEW

File: client/lib/cgutil/cpuset_manager_v1.go [hunk 1]
```diff
@@ -119,24 +134,25 @@ func (c *cpusetManager) CgroupPathFor(allocID, task string) CgroupPathGetter {
...
 
+// task name -> task cgroup info
 type allocTaskCgroupInfo map[string]*TaskCgroupInfo
 
 // Init checks that the cgroup parent and expected child cgroups have been created
 // If the cgroup parent is set to /nomad then this will ensure that the /nomad/shared
 // cgroup is initialized.
-func (c *cpusetManager) Init() error {
-	cgroupParentPath, err := getCgroupPathHelper("cpuset", c.cgroupParent)
+func (c *cpusetManagerV1) Init(_ []uint16) error {
```
Comment (shoenig) [inline client/lib/cgutil/cpuset_manager_v1.go:143]: No need to remember the initial reserve-able cores in the v1 manager, because they're handled implicitly through the cgroup hierarchy.

File: command/agent/config.go [hunk 2]
```diff
@@ -1763,6 +1763,11 @@ func (a *ClientConfig) Merge(b *ClientConfig) *ClientConfig {
 	if b.BindWildcardDefaultHostNetwork {
 		result.BindWildcardDefaultHostNetwork = true
 	}
+
+	if b.CgroupParent != "" {
+		result.CgroupParent = b.CgroupParent
+	}
```
Comment (shoenig) [inline command/agent/config.go:1769]: Not sure if this ever worked

**Comment by shoenig** [comment]
In the absence of CI tests I'll run the interesting ones here

```
➜ mount -l | grep cgroup
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
```

<details><summary>client/lib/cgutil</summary>

```
client/lib/cgutil on f-cgroupsv2 
➜ sudo -E PATH=$PATH go test -v
[sudo] password for shoenig: 
=== RUN   TestUtil_GetCgroupParent
=== PAUSE TestUtil_GetCgroupParent
=== RUN   TestUtil_CreateCPUSetManager
=== PAUSE TestUtil_CreateCPUSetManager
=== RUN   TestUtil_GetCPUsFromCgroup
=== PAUSE TestUtil_GetCPUsFromCgroup
=== RUN   TestUtil_CopyCpuset
=== PAUSE TestUtil_CopyCpuset
=== RUN   TestUtil_SplitPath
=== PAUSE TestUtil_SplitPath
=== RUN   TestCpusetManager_V1_Init
    driver_compatible_linux.go:26: No cgroup.v1 mount point: running in cgroup.v2 mode
    driver_compatible_linux.go:20: Test requires cgroup.v1 support
--- SKIP: TestCpusetManager_V1_Init (0.00s)
=== RUN   TestCpusetManager_V1_AddAlloc_single
    driver_compatible_linux.go:26: No cgroup.v1 mount point: running in cgroup.v2 mode
    driver_compatible_linux.go:20: Test requires cgroup.v1 support
--- SKIP: TestCpusetManager_V1_AddAlloc_single (0.00s)
=== RUN   TestCpusetManager_V1_RemoveAlloc
    driver_compatible_linux.go:26: No cgroup.v1 mount point: running in cgroup.v2 mode
    driver_compatible_linux.go:20: Test requires cgroup.v1 support
--- SKIP: TestCpusetManager_V1_RemoveAlloc (0.00s)
=== RUN   TestCpusetManager_V2_AddAlloc
2022-03-21T11:08:37.067-0500 [DEBUG] cgutil/cpuset_manager_v2.go:71: initializing with: cores=[0, 1]
2022-03-21T11:08:37.067-0500 [TRACE] cgutil/cpuset_manager_v2.go:301: establish cgroup hierarchy: parent=e2152c52.scope
=== RUN   TestCpusetManager_V2_AddAlloc/first
2022-03-21T11:08:37.067-0500 [TRACE] cgutil/cpuset_manager_v2.go:84: add allocation: name="" id=098b9775-c20b-9dd5-a37f-76a51b000884
=== RUN   TestCpusetManager_V2_AddAlloc/second
2022-03-21T11:08:37.068-0500 [TRACE] cgutil/cpuset_manager_v2.go:84: add allocation: name="" id=4c97aa08-7bba-2589-e5b0-5ad5bd33dd0f
--- PASS: TestCpusetManager_V2_AddAlloc (0.04s)
    --- PASS: TestCpusetManager_V2_AddAlloc/first (0.00s)
    --- PASS: TestCpusetManager_V2_AddAlloc/second (0.00s)
=== RUN   TestCpusetManager_V2_RemoveAlloc
2022-03-21T11:08:37.069-0500 [DEBUG] cgutil/cpuset_manager_v2.go:71: initializing with: cores=[0, 1]
2022-03-21T11:08:37.069-0500 [TRACE] cgutil/cpuset_manager_v2.go:301: establish cgroup hierarchy: parent=525fa203.scope
2022-03-21T11:08:37.069-0500 [TRACE] cgutil/cpuset_manager_v2.go:84: add allocation: name="" id=ddf2d168-610e-0ffb-dcba-efb707b1ddeb
2022-03-21T11:08:37.069-0500 [TRACE] cgutil/cpuset_manager_v2.go:84: add allocation: name="" id=1fdbacca-a613-1dc7-2376-0456d73a4e5d
2022-03-21T11:08:37.070-0500 [TRACE] cgutil/cpuset_manager_v2.go:110: remove allocation: id=ddf2d168-610e-0ffb-dcba-efb707b1ddeb
--- PASS: TestCpusetManager_V2_RemoveAlloc (0.00s)
=== CONT  TestUtil_GetCgroupParent
=== CONT  TestUtil_CopyCpuset
=== CONT  TestUtil_SplitPath
=== RUN   TestUtil_CopyCpuset/v2
--- PASS: TestUtil_SplitPath (0.00s)
=== CONT  TestUtil_GetCPUsFromCgroup
=== RUN   TestUtil_GetCPUsFromCgroup/v2
=== RUN   TestUtil_GetCgroupParent/v1
--- PASS: TestUtil_GetCPUsFromCgroup (0.00s)
    --- PASS: TestUtil_GetCPUsFromCgroup/v2 (0.00s)
=== CONT  TestUtil_GetCgroupParent/v1
    driver_compatible_linux.go:26: No cgroup.v1 mount point: running in cgroup.v2 mode
    driver_compatible_linux.go:20: Test requires cgroup.v1 support
=== RUN   TestUtil_GetCgroupParent/v2
=== CONT  TestUtil_CreateCPUSetManager
=== RUN   TestUtil_CreateCPUSetManager/v1
    driver_compatible_linux.go:26: No cgroup.v1 mount point: running in cgroup.v2 mode
    driver_compatible_linux.go:20: Test requires cgroup.v1 support
=== RUN   TestUtil_GetCgroupParent/v2/default
=== RUN   TestUtil_GetCgroupParent/v2/configured
=== RUN   TestUtil_CreateCPUSetManager/v2
--- PASS: TestUtil_GetCgroupParent (0.00s)
    --- SKIP: TestUtil_GetCgroupParent/v1 (0.00s)
    --- PASS: TestUtil_GetCgroupParent/v2 (0.00s)
        --- PASS: TestUtil_GetCgroupParent/v2/default (0.00s)
        --- PASS: TestUtil_GetCgroupParent/v2/configured (0.00s)
2022-03-21T11:08:37.072-0500 [DEBUG] cgutil/cpuset_manager_v2.go:71: cpuset.v2: initializing with: cores=[0]
--- PASS: TestUtil_CopyCpuset (0.00s)
    --- PASS: TestUtil_CopyCpuset/v2 (0.00s)
2022-03-21T11:08:37.072-0500 [TRACE] cgutil/cpuset_manager_v2.go:301: cpuset.v2: establish cgroup hierarchy: parent=9e1d757f.slice
--- PASS: TestUtil_CreateCPUSetManager (0.00s)
    --- SKIP: TestUtil_CreateCPUSetManager/v1 (0.00s)
    --- PASS: TestUtil_CreateCPUSetManager/v2 (0.00s)
PASS
ok  	github.com/hashicorp/nomad/client/lib/cgutil	0.050s
```

</details>

File: drivers/docker/driver_linux.go [hunk 3]
```diff
@@ -7,7 +9,7 @@ import (
 )
 
 func setCPUSetCgroup(path string, pid int) error {
-	// Sometimes the container exists before we can write the
+	// Sometimes the container exits before we can write the
```
Comment (shoenig) [inline drivers/docker/driver_linux.go:12]: !

File: drivers/shared/executor/executor_linux.go [hunk 4]
```diff
@@ -37,10 +38,6 @@ import (
 	"golang.org/x/sys/unix"
 )
 
-const (
-	defaultCgroupParent = "/nomad"
-)
```
Comment (shoenig) [inline drivers/shared/executor/executor_linux.go:42]: Again, not sure `cgroup_parent` ever really worked apart from the `cpuset` controller.

File: drivers/shared/executor/executor_linux.go [hunk 5]
```diff
@@ -665,14 +661,27 @@ func configureIsolation(cfg *lconfigs.Config, command *ExecCommand) error {
...
+			return errors.New("cgroup path must be set")
+		}
+		parent, cgroup := cgutil.SplitPath(command.Resources.LinuxResources.CpusetCgroupPath)
+		cfg.Cgroups.Path = filepath.Join("/", parent, cgroup)
+	} else {
+		// in v1, the cgroup is created using /nomad, which is a bug because it
+		// does not respect the cgroup_parent client configuration
+		// (but makes testing easy)
+		id := uuid.Generate()
+		cfg.Cgroups.Path = filepath.Join("/", cgutil.DefaultCgroupV1Parent, id)
```
Comment (shoenig) [inline drivers/shared/executor/executor_linux.go:683]: !

File: client/fingerprint/cgroup_linux.go [hunk 6]
```diff
@@ -1,37 +1,35 @@
...
 
-	// Check if a cgroup mount point was found
+	// Check if a cgroup mount point was found.
 	if mount == "" {
-
 		f.clearCGroupAttributes(resp)
-
 		if f.lastState == cgroupAvailable {
-			f.logger.Info("cgroups are unavailable")
+			f.logger.Warn("cgroups are now unavailable")
```
Comment (tgross) [inline client/fingerprint/cgroup_linux.go:22]: That seems like a bad situation to be in! 😀 But it looks like you've got the cpuset fixer handling that as gracefully as we can, so 👍

File: drivers/docker/reconcile_cpuset.go [hunk 7]
```diff
@@ -0,0 +1,125 @@
...
+type CpusetFixer interface {
+	Start()
+}
+
+// cpusetFixer adjusts the cpuset.cpus cgroup value to the assigned value by Nomad.
+//
+// Due to Docker not allowing the configuration of the full cgroup path, we must
+// manually fix the cpuset values for all docker containers continuously, as the
+// values will change as tasks of any driver using reserved cores are started and
+// stopped, changing the size of the remaining shared cpu pool.
```
Comment (tgross) [inline drivers/docker/reconcile_cpuset.go:30]: Just for my clarity, in the case of https://github.com/hashicorp/nomad/issues/11705 with cgroups v2: any child processes will be in the same cgroup as their parent that Docker starts. So although they won't be pinned to the right CPU for a very brief window at startup, they'll all get moved together to the correct `cpuset` because we're not moving processes between cgroups, just changing the cgroup in place.

Is my understanding right?

File: drivers/docker/reconcile_cpuset.go [hunk 8]
```diff
@@ -0,0 +1,125 @@
...
+	}
+}
+
+func (cf *cpusetFixer) fix(c coordinate) {
+	source := c.NomadCgroup()
+	destination := c.DockerCgroup()
+	if err := cgutil.CopyCpuset(source, destination); err != nil {
+		cf.logger.Debug("failed to copy cpuset", "err", err)
+	}
+}
```
Comment (tgross) [inline drivers/docker/reconcile_cpuset.go:92]: I really like the design here where we didn't end up plumbing any management code into the driver, but are just copying the cpu sets between the Nomad-managed cgroup and the Docker-managed one.

File: drivers/shared/executor/executor_linux_test.go [hunk 9]
```diff
@@ -336,28 +353,34 @@ func TestExecutor_CgroupPathsAreDestroyed(t *testing.T) {
...
+				// Every cgroup entry should be /nomad/$ALLOC_ID
+				if line == "" {
+					continue
+				}
 
-			if !strings.Contains(line, ":/nomad/") {
-				return false, fmt.Errorf("Not a member of the alloc's cgroup: expected=...:/nomad/... -- found=%q", line)
+				// Skip rdma subsystem; rdma was added in most recent kernels and libcontainer/docker
+				// don't isolate it by default.
+				if strings.Contains(line, ":rdma:") || strings.Contains(line, "::") {
```
Comment (tgross) [inline drivers/shared/executor/executor_linux_test.go:375]: Should we skip `:misc:` here too?

File: plugins/drivers/testutils/exec_testing.go [hunk 10]
```diff
@@ -192,9 +194,35 @@ func TestExecFSIsolation(t *testing.T, driver *DriverHarness, taskID string) {
...
 
-		if !strings.Contains(r.stdout, ":freezer:/nomad") && !strings.Contains(r.stdout, "freezer:/docker") {
-			require.Fail(t, "unexpected freezer cgroup", "expected freezer to be /nomad/ or /docker/, but found:\n%s", r.stdout)
+		if !cgutil.UseV2 {
+			acceptable := []string{
+				":freezer:/nomad", ":freezer:/docker",
+			}
+			if testutil.IsCI() {
+				// github actions freezer cgroup
+				acceptable = append(acceptable, ":freezer:/actions_job")
```
Comment (tgross) [inline plugins/drivers/testutils/exec_testing.go:203]: Oof, I imagine you discovered this experimentally and it wasn't documented? Probably nothing we can do about it but some day that's going to change out from under us and break a bunch of tests. So at least you've documented it! 😀

**Review by tgross — COMMENTED** [review]
This is looking great @shoenig! I've reviewed the driver and fingerprinter changes at this point and have started working thru the cgutil package changes. I'll have to finish my review tomorrow but I wanted to save my review in the meantime so I'll mark it as a comment.

File: client/lib/cgutil/cgutil_linux.go [hunk 11]
```diff
@@ -1,121 +1,106 @@
...
-// cpusetEnsureParent makes sure that the parent directories of current
-// are created and populated with the proper cpus and mems files copied
-// from their respective parent. It does that recursively, starting from
-// the top of the cpuset hierarchy (i.e. cpuset cgroup mount point).
-func cpusetEnsureParent(current string) error {
-	var st unix.Statfs_t
+// CgroupScope returns the name of the scope for Nomad's managed cgroups for
+// the given allocID and task.
+//
+// e.g. "<allocID>-<task>.scope"
```
Comment (tgross) [inline client/lib/cgutil/cgutil_linux.go:52]: I think we want a dot to match what we've done in the code everywhere:


```suggestion
// e.g. "<allocID>.<task>.scope"
```

File: client/lib/cgutil/cpuset_manager.go [hunk 12]
```diff
@@ -37,20 +63,25 @@ type TaskCgroupInfo struct {
 	Error              error
 }
 
-func NoopCpusetManager() CpusetManager { return noopCpusetManager{} }
-
-type noopCpusetManager struct{}
+// identity is the "<allocID>.<taskName>" string that uniquely identifies an
+// individual instance of a task within the flat cgroup namespace
+type identity string
```
Comment (tgross) [inline client/lib/cgutil/cpuset_manager.go:68]: I ❤️ type-aliased IDs

File: client/lib/cgutil/cpuset_manager_v2.go [hunk 13]
```diff
@@ -0,0 +1,332 @@
...
+
+	// DefaultCgroupParentV2 is the name of Nomad's default parent cgroup, under which
+	// all other cgroups are managed. This can be changed with client configuration
+	// in case for e.g. Nomad tasks should be further constrained by an externally
+	// configured systemd cgroup.
+	DefaultCgroupParentV2 = "nomad.slice"
+
+	// rootless is (for now) always false; Nomad clients require root, so we
+	// assume to not need to do the extra plumbing for rootless cgroups.
+	rootless = false
```
Comment (tgross) [inline client/lib/cgutil/cpuset_manager_v2.go:37]: It looks like the version of libcontainer we have would return an error if we passed `rootless = true` anyways. And more recent versions of [`libcontainer/cgroups/fs2`](https://pkg.go.dev/github.com/opencontainers/runc/libcontainer/cgroups/fs2#NewManager) drop this parameter entirely. Not sure whether we want to update the comment to reflect we know that it's safe to remove when we bump versions of libcontainer?

File: client/lib/cgutil/cpuset_manager_v2.go [hunk 14]
```diff
@@ -0,0 +1,332 @@
...
+)
+
+// nothing is used for treating a map like a set with no values
+type nothing struct{}
+
+// null represents nothing
+var null = nothing{}
```
Comment (tgross) [inline client/lib/cgutil/cpuset_manager_v2.go:44]: I like what you're doing here but calling it `null` means we do `c.sharing[id] = null` to add an ID to the sharing set, which reads almost the opposite of what you're going for. Maybe if it were `c.sharing[id] = ok` or something like that?

(What I wouldn't do for a real set type in the stdlib!)

File: client/lib/cgutil/cpuset_manager_v2.go [hunk 15]
```diff
@@ -0,0 +1,332 @@
...
+
+//pathOf returns the absolute path to a task with identity id.
+func (c *cpusetManagerV2) pathOf(id identity) string {
+	return filepath.Join(c.parentAbs, makeScope(id))
+}
+
+// remove does the actual fs delete of the cgroup
+//
+// We avoid removing a cgroup if it still contains a PID, as the cpuset manager
+// may be initially empty on a Nomad client restart.
```
Comment (tgross) [inline client/lib/cgutil/cpuset_manager_v2.go:241]: I don't think we need to do it for this PR, but it might be nice if we can eventually figure out a way to clean up stray cgroup entries. The allocdir hook is the only hook that comes before the cgroup hook, but if its postrun hook throws an error I think we'll never clean up the cgroup entry for that PID?

File: client/lib/cgutil/cpuset_manager_v1.go [hunk 16]
```diff
@@ -99,15 +108,21 @@ func (c *cpusetManager) CgroupPathFor(allocID, task string) CgroupPathGetter {
...
+		timer, stop := helper.NewSafeTimer(0)
+		defer stop()
+
 		for {
+
 			if taskInfo.Error != nil {
 				break
 			}
+
+			timer.Reset(100 * time.Millisecond)
```
Comment (tgross) [inline client/lib/cgutil/cpuset_manager_v1.go:120]: We could move this into the `timer.C` case below, I think. Or do we pretty much always need the initial 100ms?

**Review by tgross — APPROVED** [review]
This looks great @shoenig, nice work! I've left a few small comments and questions.

File: client/lib/cgutil/cpuset_manager_v2.go (hunk 15 above)
Comment (shoenig) [reply client/lib/cgutil/cpuset_manager_v2.go:240]: This is a good point; it's a similar problem for other resources like networks too, right?

File: client/lib/cgutil/cpuset_manager_v2_test.go [hunk 17]
```diff
@@ -0,0 +1,90 @@
...
+	"github.com/hashicorp/nomad/client/testutil"
+	"github.com/hashicorp/nomad/helper/testlog"
+	"github.com/hashicorp/nomad/helper/uuid"
+	"github.com/hashicorp/nomad/lib/cpuset"
+	"github.com/hashicorp/nomad/nomad/mock"
+	"github.com/opencontainers/runc/libcontainer/cgroups"
+	"github.com/stretchr/testify/require"
+)
+
+// Note: these tests need to run on GitHub Actions runners with only 2 cores.
```
[the remark this answers is not in the document]
Comment (shoenig) [reply client/lib/cgutil/cpuset_manager_v2_test.go:19]: good idea, added

File: client/testutil/driver_compatible_linux.go [hunk 18]
```diff
@@ -0,0 +1,56 @@
...
+// - cgroup.v1 mount point is detected
+func CgroupsCompatibleV1(t *testing.T) {
+	if !cgroupsCompatibleV1(t) {
+		t.Skipf("Test requires cgroup.v1 support")
+	}
+}
+
+func cgroupsCompatibleV1(t *testing.T) bool {
+	if runtime.GOOS != "linux" {
+		return false
```
[the remark this answers is not in the document]
Comment (shoenig) [reply client/testutil/driver_compatible_linux.go]: removed in favor of a comment reminding of the build tag

File: drivers/docker/reconcile_cpuset.go (hunk 7 above)
Comment (shoenig) [reply drivers/docker/reconcile_cpuset.go:30]: Yup! And actually this is probably worth amending the RFC and reconsidering. 

Although this behavior is most similar to the way V1 works, I don't see why it wouldn't be worth just setting the cpuset on the docker task config on initial startup now. The drawback is I don't think we have the plumbing to get the `shared` cores - the initial value would only be the `reserved` cores requested by the task resources.

File: drivers/docker/reconcile_cpuset.go (hunk 8 above)
Comment (shoenig) [reply drivers/docker/reconcile_cpuset.go:92]: Still waiting to hear back on https://github.com/moby/moby/issues/43363

Which if that would work, all this goes away!

File: drivers/shared/executor/executor_linux_test.go (hunk 9 above)
Comment (shoenig) [reply drivers/shared/executor/executor_linux_test.go]: Yup

File: plugins/drivers/testutils/exec_testing.go (hunk 10 above)
Comment (shoenig) [reply plugins/drivers/testutils/exec_testing.go:203]: Heh yeah, it's really got me ~concerned~ curious how GHA works under the hood ...

File: client/lib/cgutil/cpuset_manager_v2.go (hunk 15 above)
Comment (tgross) [reply client/lib/cgutil/cpuset_manager_v2.go:240]: Yeah https://github.com/hashicorp/nomad/issues/11096 and https://github.com/hashicorp/nomad/issues/6385.

File: drivers/docker/reconcile_cpuset.go (hunk 7 above)
Comment (aholyoake-bc) [reply drivers/docker/reconcile_cpuset.go:30]: Our trading infrastructure reads the cpus in the cgroup on startup and index into the cpuset to pin threads to specific cores. If the cgroup gets modified after we've done this thread <-> core pinning, I'm not entirely sure what happens but it's bad as either threads will still be pinned to CPUs outside of the allocated cgroup or it just breaks altogether.

cf: https://github.com/hashicorp/nomad/issues/12374
