### PR TITLE
Fix TLS support in api pkg / cli

### LINKED ISSUE #3013: Retrieving stats from CLI doesn't properly support TLS
I think this is a similar bug as #2490.

Original report by @pznamensky:

I've found that at least `nomad alloc-status $alloc-id` doesn't work as expected (for me).

> ~ $ nomad alloc-status e90647d0                       
> ID                  = e90647d0
> Eval ID             = f693f405                                                                                                                   
> ....                                                                                                        
> 
> Couldn't retrieve stats (HINT: ensure Client.Advertise.HTTP is set): Get https://$alloc-ip:4646/v1/client/allocation/e90647d0-6dda-545b-4c48-69094ec65b06/stats: x509: certificate is valid for 127.0.0.1, not $alloc-ip
> 
> Task "redis" is "running"
> Task Resources
> CPU      Memory   Disk     IOPS  Addresses
> 500 MHz  256 MiB  300 MiB  0     db: $alloc-ip:27590
> 
> Task Events:
> ...

This doesn't work in case of using `cli` or `client` certs.
Is this expected behavior?

### PR DESCRIPTION
**Pull request by schmichael**
Fixes #3013

It's a little weird that Client now has a method for returning a
NewClient, but it's a convenient way to dedupe the logic to
connect-directly-to-a-node which is nontrivial and had sutble
differences between locations.

### CODE REVIEW

File: api/api.go [hunk 1]
```diff
@@ -285,6 +285,58 @@ func (c *Client) SetRegion(region string) {
...
+
+	region := ""
+	if q != nil && *q != nil && (*q).Region != "" {
+		region = (*q).Region
+	} else if c.config.Region != "" {
+		// Use the region from the client
+		region = c.config.Region
+	} else {
+		// Use the region from the agent
+		agentRegion, err := c.Agent().Region()
```
Comment (dadgar) [inline api/api.go]: This seems odd. There may not be an agent if this is being embedded in another program and it would cause an error. It should just do nothing as the http handler would default to the global region

File: api/api.go [hunk 2]
```diff
@@ -285,6 +285,58 @@ func (c *Client) SetRegion(region string) {
...
+	if err != nil {
+		return nil, err
+	}
+
+	// Set the query params
+	if q == nil {
+		return nodeClient, nil
+	}
+
+	if *q == nil {
```
Comment (dadgar) [inline api/api.go]: Not sure I understand this logic. If there isn't a reason for it, can you remove and just take a pointer, not a pointer to a pointer.

File: api/api.go (hunk 1 above)
Comment (schmichael) [reply api/api.go]: Won't this query the agent at NOMAD_ADDR for the region? That seems potentially useful even in embedded circumstances.

(This logic was cargo culted from the previous location, so I may not fully grok it)
