### PR TITLE
fix host network reserved port fingerprint

### LINKED ISSUE #9492: Reserved ports are not honored
### Nomad version
`Nomad v0.12.7 (6147cb578794cb2d0c35d68fe1791728a09bb081)`

### Operating system and Environment details
Debian 10

### Issue
Regardless of where `reserved_ports` is specified in the `client` stanza, ports within the range are still allocated.  Just in case the documentation for this was incorrect, I tried it as both an inclusive and exclusive range with the same results.

#### ensure the nomad.hcl has reserved_ports defined
```
client {
  enabled       = true
  network_speed = 1000
  host_network "dummy_net1" { 
    cidr = "10.9.9.1/32"
    # dummy_net1 specifies a small range of ports.  if range is inclusive, it has to pick 32766 or 32767
    reserved_ports = "32766-32767"
  }
  host_network "dummy_net2" { 
    cidr = "10.9.9.2/32"
    # dummy_net2 specifies a large range of ports.  if range is exclusive, it has to pick 65535
    reserved_ports = "1-65534"
  }
}
```
#### bring up a new dummy interface with our IPs
```
# ip link add name nomad type dummy

# ip addr add 10.9.9.1/32 dev nomad
# ip addr add 10.9.9.2/32 dev nomad

# ip link set up dev nomad
```
#### restart nomad, run the job
```
# systemctl restart nomad
# nomad job dispatch  -meta xid=test reserved_ports_test
Dispatched Job ID = reserved_ports_test/dispatch-1606876795-355d4a46
Evaluation ID     = 28d63a84

==> Monitoring evaluation "28d63a84"
    Evaluation triggered by job "reserved_ports_test/dispatch-1606876795-355d4a46"
    Allocation "69636c82" created: node "3a31e222", group "group1"
    Evaluation status changed: "pending" -> "complete"
==> Evaluation "28d63a84" finished with status "complete"
```
#### the allocated ports do not seem to reflect either inclusive or exclusive behavior for the reserved_ports ranges
```
# docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED              STATUS              PORTS                                                                                                        NAMES
8a5ce20df8ff        alpine/socat:latest   "socat tcp-listen:32…"   About a minute ago   Up About a minute   10.9.9.2:28234->32766/tcp, 10.9.9.2:28234->32766/udp, 10.9.9.1:29469->32767/tcp, 10.9.9.1:29469->32767/udp   task-69636c82-ee14-649b-cc6a-c8a7abd77ff3
```

### Job file
```
job "reserved_ports_test" {
  region = "global"
  datacenters = ["dc1"]
  type = "batch"

  parameterized {
    meta_required = ["xid"]
  }

  group "group1" {

    network {
      port "port1" {
        to = 32767
        host_network = "dummy_net1"
      }
      port "port2" {
        to = 32766
        host_network = "dummy_net2"
      }
    }

    task "task" {
      driver = "docker"

      config {
        image = "alpine/socat:latest"
        args = [ "tcp-listen:32767", "file:/etc/hostname" ]
        ports = [ "port1", "port2" ]
      }

      resources {
        cpu    = 20 # MHz
        memory = 16 # MB
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by lgfa29**
During the network fingerprint, client configuration values are mapped to actual network addresses and interfaces. During this process a `ClientHostNetworkConfig` is translated into `NodeNetworkResource`, but reserved ports were not being set.

Closes #9492

### CODE REVIEW

File: client/fingerprint/network_test.go [hunk 1]
```diff
@@ -486,3 +486,98 @@ func TestNetworkFingerPrint_MultipleAliases(t *testing.T) {
 	sort.Strings(aliases)
 	require.Equal(t, expected, aliases, "host networks should match aliases")
 }
+
+func TestNetworkFingerPrint_HostNetorkReservedPorts(t *testing.T) {
```
Comment (tgross) [inline client/fingerprint/network_test.go:490]:
```suggestion
func TestNetworkFingerPrint_HostNetworkReservedPorts(t *testing.T) {
```

**Review by tgross — APPROVED** [review]
LGTM

File: client/fingerprint/network_test.go (hunk 1 above)
Comment (lgfa29) [reply client/fingerprint/network_test.go]: Several times Go wouldn't find any matching test to run. Now I know why 🤦 

Thanks!

**Review by schmichael — APPROVED** [review]
