### PR TITLE
Prevent df on linux from adding line breaks to output

### LINKED ISSUE #151: Parsing of df output fails on Linux when filesystem paths are very long
I was testing nomad in my Linux environment and I was unable to launch the agent:

    $ nomad agent -dev
     ==> Starting Nomad agent...
     ==> Error starting agent: client setup failed: fingerprinting failed: Failed to parse `df` output; expected at least 4 columns

I checked the output from df, and this happens because df on Linux adds breaks up the output when filesystem paths are very long:

```
$ df -hl
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/vg_local-lv_root
                       69G   21G   45G  33% /
tmpfs                  12G  284K   12G   1% /dev/shm
/dev/sda1             504M   70M  409M  15% /boot
```

It seems this can be fixed by adding the -P (portability) flag to df on Linux. I'll attempt to provide a PR which fixes this.

### PR DESCRIPTION
**Pull request by aldergren**
This should fix #151. Apologies in advance if this is not idiomatic code, I'm a total go newbie.

### CODE REVIEW

File: client/fingerprint/storage.go [hunk 1]
```diff
@@ -95,7 +95,15 @@ func (f *StorageFingerprint) Fingerprint(cfg *config.Config, node *structs.Node)
...
-		mountOutput, err := exec.Command("df", "-k", path).Output()
+		var dfArgs string
+		if runtime.GOOS == "linux" {
+			// df on linux needs the -P option to prevent linebreaks on long filesystem paths
+			dfArgs = "-kP"
+		} else {
+			dfArgs = "-k"
+		}
+
+		mountOutput, err := exec.Command("df", dfArgs, path).Output()
```
Comment (sethvargo) [inline client/fingerprint/storage.go]: I would if we should just trim the trailing whitespace instead of special casing this. Is it just the trailing whitespace?

Comment (aldergren) [inline client/fingerprint/storage.go]: Ah, no, not just trailing whitespace. If the filesystem path is sufficiently long df on Linux will print it on a separate line which breaks the parsing. There's example output in the github issue.

**Comment by ryanuber** [comment]
Good catch, thanks!

**Comment by rvm2015** [comment]
Should this really be shelling out? If the format of the df command changes at any point you will once again have this problem. I would thing this should really call out to whatever underlying library, proc, or sys call that df is actually reading though I can see an argument the other way if that would require calling out to C.
